YaWK: /var/www/htdocs/yawk.io/admin/js/accept-friend.php File Reference
accept-friend.php File Reference
Variables
$now = \YAWK\sys::now()
$requestUsername = $_POST['requestUsername']
$sessionUID = $_POST['sessionUID']
$sessionUsername = \YAWK\user::getUserNameFromID($db, $sessionUID)
if(!isset($db)) $uid = $_POST['uid']
if($sql=$db->query("UPDATE {friends} SET confirmed = '1', confirmDate = '". $now."' WHERE confirmed='0' AND friendB = '". $uid."' AND friendA = '". $sessionUID."' OR confirmed = '0' AND friendA = '". $uid."' AND friendB = '". $sessionUID."'")) else
Variable Documentation
$now
$now = \YAWK\sys::now()
Definition at line 18 of file accept-friend.php.
Referenced by YAWK\WIDGETS\FACEBOOK\FEED\fbFeed\basicOutput(), YAWK\WIDGETS\FACEBOOK\EVENTS\fbEvents\display(), YAWK\page\getContent(), and YAWK\template\saveAs().
$requestUsername
$requestUsername = $_POST['requestUsername']
Definition at line 14 of file accept-friend.php.
$sessionUID
$sessionUID = $_POST['sessionUID']
Definition at line 15 of file accept-friend.php.
$sessionUsername
$sessionUsername = \YAWK\user::getUserNameFromID($db, $sessionUID)
Definition at line 16 of file accept-friend.php.
$uid
if (!isset($db)) $uid = $_POST['uid']
Definition at line 13 of file accept-friend.php.
Referenced by YAWK\webmail\deleteMessage(), YAWK\webmail\drawMailboxControls(), YAWK\controller\filterfilename(), YAWK\user\getUserTemplateID(), YAWK\webmail\moveMessage(), YAWK\user\sendResetEmail(), YAWK\user\setNewPassword(), and YAWK\user\setUserTemplate().
else
if ($sql=$db->query("UPDATE {friends} SET confirmed = '1', confirmDate = '". $now."' WHERE confirmed='0' AND friendB = '". $uid."' AND friendA = '". $sessionUID."' OR confirmed = '0' AND friendA = '". $uid."' AND friendB = '". $sessionUID."'")) else
Initial value:
{
    echo \YAWK\alert::draw("warning","Warning!", "Could not confirm friendship status. Please try again.",'',4200)
Definition at line 25 of file accept-friend.php.