YaWK: /var/www/htdocs/yawk.io/admin/includes/stats.php File Reference
stats.php File Reference
Variables
$data = $stats->getStatsArray($db, $defaultInterval, $defaultPeriod)
if(!isset($stats)||(empty($stats))) if(isset($_GET['interval'])) else if(isset($_POST['interval'])) else { $defaultInterval = 1
if(isset($_POST['interval'])) for($i=1; $i<=365; $i++) if (isset($_POST[ 'period']) &&(isset($_POST[ 'period'])))
Variable Documentation
$data
$data = $stats->getStatsArray($db, $defaultInterval, $defaultPeriod)
Definition at line 56 of file stats.php.
Referenced by YAWK\stats\calculateStatsFromArray(), YAWK\stats\countBrowsers(), YAWK\sys\countCodeLines(), YAWK\stats\countDaytime(), YAWK\stats\countDeviceTypes(), YAWK\stats\countOS(), YAWK\stats\countOSVersions(), YAWK\stats\countWeekdays(), YAWK\stats\drawPagesBox(), YAWK\sys\drawPhpInfo(), YAWK\template\saveProperties(), YAWK\installer\step3(), YAWK\installer\writeHtaccessFileToAdminFolder(), and YAWK\installer\writeHtaccessFileToRootFolder().
else
if (isset($_GET[ 'period'])) else if (isset($_POST[ 'period'])) else { $defaultInterval = 1
Definition at line 40 of file stats.php.
if
if (isset($_POST[ 'interval'])) for ($i=1;$i<=365;$i++) if(isset($_POST['period']) &&(isset($_POST['period']))) (isset($_POST[ 'period']) &&(isset($_POST[ 'period'])))
Definition at line 105 of file stats.php.