YaWK: /var/www/htdocs/yawk.io/system/engines/AdminLTE/js/app.js File Reference
app.js File Reference
Functions
_init ()
AdminLTE layout activate ()
btn group[data-toggle="btn-toggle"] each (function() { var group=$(this);$(this).find(".btn").on('click', function(e) { group.find(".btn.active").removeClass("active");$(this).addClass("active");e.preventDefault();});})
if (o.directChat.enable)
if (o.enableControlSidebar)
if (typeof AdminLTEOptions !=="undefined")
if (typeof jQuery==="undefined")
function body removeClass ("hold-transition")
AdminLTE tree ('.sidebar')
Variables
function fn activateBox
AdminLTE = {}
function fn boxRefresh
jQuery
var o = $.AdminLTE.options
AdminLTE options
fn removeBox
function fn todolist
fn toggleBox
Function Documentation
_init()
_init ()
Definition at line 229 of file app.js.
                  {
   'use strict';
   /* Layout
    * ======
    * Fixes the layout height in case min-height fails.
    *
    * @type Object
    * @usage $.AdminLTE.layout.activate()
    *        $.AdminLTE.layout.fix()
    *        $.AdminLTE.layout.fixSidebar()
    */
   $.AdminLTE.layout = {
     activate: function () {
       var _this = this;
       _this.fix();
       _this.fixSidebar();
       $(window, ".wrapper").resize(function () {
         _this.fix();
         _this.fixSidebar();
       });
     },
     fix: function () {
       //Get window height and the wrapper height
       var neg = $('.main-header').outerHeight() + $('.main-footer').outerHeight();
       var window_height = $(window).height();
       var sidebar_height = $(".sidebar").height();
       //Set the min-height of the content and sidebar based on the
       //the height of the document.
       if ($("body").hasClass("fixed")) {
         $(".content-wrapper, .right-side").css('min-height', window_height - $('.main-footer').outerHeight());
       } else {
         var postSetWidth;
         if (window_height >= sidebar_height) {
           $(".content-wrapper, .right-side").css('min-height', window_height - neg);
           postSetWidth = window_height - neg;
         } else {
           $(".content-wrapper, .right-side").css('min-height', sidebar_height);
           postSetWidth = sidebar_height;
         }
         //Fix for the control sidebar height
         var controlSidebar = $($.AdminLTE.options.controlSidebarOptions.selector);
         if (typeof controlSidebar !== "undefined") {
           if (controlSidebar.height() > postSetWidth)
             $(".content-wrapper, .right-side").css('min-height', controlSidebar.height());
         }
       }
     },
     fixSidebar: function () {
       //Make sure the body tag has the .fixed class
       if (!$("body").hasClass("fixed")) {
         if (typeof $.fn.slimScroll != 'undefined') {
           $(".sidebar").slimScroll({destroy: true}).height("auto");
         }
         return;
       } else if (typeof $.fn.slimScroll == 'undefined' && window.console) {
         window.console.error("Error: the fixed layout requires the slimscroll plugin!");
       }
       //Enable slimscroll for fixed layout
       if ($.AdminLTE.options.sidebarSlimScroll) {
         if (typeof $.fn.slimScroll != 'undefined') {
           //Destroy if it exists
           $(".sidebar").slimScroll({destroy: true}).height("auto");
           //Add slimscroll
           $(".sidebar").slimscroll({
             height: ($(window).height() - $(".main-header").height()) + "px",
             color: "rgba(0,0,0,0.2)",
             size: "3px"
           });
         }
       }
     }
   };
   /* PushMenu()
    * ==========
    * Adds the push menu functionality to the sidebar.
    *
    * @type Function
    * @usage: $.AdminLTE.pushMenu("[data-toggle='offcanvas']")
    */
   $.AdminLTE.pushMenu = {
     activate: function (toggleBtn) {
       //Get the screen sizes
       var screenSizes = $.AdminLTE.options.screenSizes;
       //Enable sidebar toggle
       $(document).on('click', toggleBtn, function (e) {
         e.preventDefault();
         //Enable sidebar push menu
         if ($(window).width() > (screenSizes.sm - 1)) {
           if ($("body").hasClass('sidebar-collapse')) {
             $("body").removeClass('sidebar-collapse').trigger('expanded.pushMenu');
           } else {
             $("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');
           }
         }
         //Handle sidebar push menu for small screens
         else {
           if ($("body").hasClass('sidebar-open')) {
             $("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
           } else {
             $("body").addClass('sidebar-open').trigger('expanded.pushMenu');
           }
         }
       });
       $(".content-wrapper").click(function () {
         //Enable hide menu when clicking on the content-wrapper on small screens
         if ($(window).width() <= (screenSizes.sm - 1) && $("body").hasClass("sidebar-open")) {
           $("body").removeClass('sidebar-open');
         }
       });
       //Enable expand on hover for sidebar mini
       if ($.AdminLTE.options.sidebarExpandOnHover
         || ($('body').hasClass('fixed')
         && $('body').hasClass('sidebar-mini'))) {
         this.expandOnHover();
       }
     },
     expandOnHover: function () {
       var _this = this;
       var screenWidth = $.AdminLTE.options.screenSizes.sm - 1;
       //Expand sidebar on hover
       $('.main-sidebar').hover(function () {
         if ($('body').hasClass('sidebar-mini')
           && $("body").hasClass('sidebar-collapse')
           && $(window).width() > screenWidth) {
           _this.expand();
         }
       }, function () {
         if ($('body').hasClass('sidebar-mini')
           && $('body').hasClass('sidebar-expanded-on-hover')
           && $(window).width() > screenWidth) {
           _this.collapse();
         }
       });
     },
     expand: function () {
       $("body").removeClass('sidebar-collapse').addClass('sidebar-expanded-on-hover');
     },
     collapse: function () {
       if ($('body').hasClass('sidebar-expanded-on-hover')) {
         $('body').removeClass('sidebar-expanded-on-hover').addClass('sidebar-collapse');
       }
     }
   };
   /* Tree()
    * ======
    * Converts the sidebar into a multilevel
    * tree view menu.
    *
    * @type Function
    * @Usage: $.AdminLTE.tree('.sidebar')
    */
   $.AdminLTE.tree = function (menu) {
     var _this = this;
     var animationSpeed = $.AdminLTE.options.animationSpeed;
     $(document).off('click', menu + ' li a')
       .on('click', menu + ' li a', function (e) {
         //Get the clicked link and the next element
         var $this = $(this);
         var checkElement = $this.next();
         //Check if the next element is a menu and is visible
         if ((checkElement.is('.treeview-menu')) && (checkElement.is(':visible')) && (!$('body').hasClass('sidebar-collapse'))) {
           //Close the menu
           checkElement.slideUp(animationSpeed, function () {
             checkElement.removeClass('menu-open');
             //Fix the layout in case the sidebar stretches over the height of the window
             //_this.layout.fix();
           });
           checkElement.parent("li").removeClass("active");
         }
         //If the menu is not visible
         else if ((checkElement.is('.treeview-menu')) && (!checkElement.is(':visible'))) {
           //Get the parent menu
           var parent = $this.parents('ul').first();
           //Close all open menus within the parent
           var ul = parent.find('ul:visible').slideUp(animationSpeed);
           //Remove the menu-open class from the parent
           ul.removeClass('menu-open');
           //Get the parent li
           var parent_li = $this.parent("li");
           //Open the target menu and add the menu-open class
           checkElement.slideDown(animationSpeed, function () {
             //Add the class active to the parent li
             checkElement.addClass('menu-open');
             parent.find('li.active').removeClass('active');
             parent_li.addClass('active');
             //Fix the layout in case the sidebar stretches over the height of the window
             _this.layout.fix();
           });
         }
         //if this isn't a link, prevent the page from being redirected
         if (checkElement.is('.treeview-menu')) {
           e.preventDefault();
         }
       });
   };
   /* ControlSidebar
    * ==============
    * Adds functionality to the right sidebar
    *
    * @type Object
    * @usage $.AdminLTE.controlSidebar.activate(options)
    */
   $.AdminLTE.controlSidebar = {
     //instantiate the object
     activate: function () {
       //Get the object
       var _this = this;
       //Update options
       var o = $.AdminLTE.options.controlSidebarOptions;
       //Get the sidebar
       var sidebar = $(o.selector);
       //The toggle button
       var btn = $(o.toggleBtnSelector);
       //Listen to the click event
       btn.on('click', function (e) {
         e.preventDefault();
         //If the sidebar is not open
         if (!sidebar.hasClass('control-sidebar-open')
           && !$('body').hasClass('control-sidebar-open')) {
           //Open the sidebar
           _this.open(sidebar, o.slide);
         } else {
           _this.close(sidebar, o.slide);
         }
       });
       //If the body has a boxed layout, fix the sidebar bg position
       var bg = $(".control-sidebar-bg");
       _this._fix(bg);
       //If the body has a fixed layout, make the control sidebar fixed
       if ($('body').hasClass('fixed')) {
         _this._fixForFixed(sidebar);
       } else {
         //If the content height is less than the sidebar's height, force max height
         if ($('.content-wrapper, .right-side').height() < sidebar.height()) {
           _this._fixForContent(sidebar);
         }
       }
     },
     //Open the control sidebar
     open: function (sidebar, slide) {
       //Slide over content
       if (slide) {
         sidebar.addClass('control-sidebar-open');
       } else {
         //Push the content by adding the open class to the body instead
         //of the sidebar itself
         $('body').addClass('control-sidebar-open');
       }
     },
     //Close the control sidebar
     close: function (sidebar, slide) {
       if (slide) {
         sidebar.removeClass('control-sidebar-open');
       } else {
         $('body').removeClass('control-sidebar-open');
       }
     },
     _fix: function (sidebar) {
       var _this = this;
       if ($("body").hasClass('layout-boxed')) {
         sidebar.css('position', 'absolute');
         sidebar.height($(".wrapper").height());
         if (_this.hasBindedResize) {
           return;
         }
         $(window).resize(function () {
           _this._fix(sidebar);
         });
         _this.hasBindedResize = true;
       } else {
         sidebar.css({
           'position': 'fixed',
           'height': 'auto'
         });
       }
     },
     _fixForFixed: function (sidebar) {
       sidebar.css({
         'position': 'fixed',
         'max-height': '100%',
         'overflow': 'auto',
         'padding-bottom': '50px'
       });
     },
     _fixForContent: function (sidebar) {
       $(".content-wrapper, .right-side").css('min-height', sidebar.height());
     }
   };
   /* BoxWidget
    * =========
    * BoxWidget is a plugin to handle collapsing and
    * removing boxes from the screen.
    *
    * @type Object
    * @usage $.AdminLTE.boxWidget.activate()
    *        Set all your options in the main $.AdminLTE.options object
    */
   $.AdminLTE.boxWidget = {
     selectors: $.AdminLTE.options.boxWidgetOptions.boxWidgetSelectors,
     icons: $.AdminLTE.options.boxWidgetOptions.boxWidgetIcons,
     animationSpeed: $.AdminLTE.options.animationSpeed,
     activate: function (_box) {
       var _this = this;
       if (!_box) {
         _box = document; // activate all boxes per default
       }
       //Listen for collapse event triggers
       $(_box).on('click', _this.selectors.collapse, function (e) {
         e.preventDefault();
         _this.collapse($(this));
       });
       //Listen for remove event triggers
       $(_box).on('click', _this.selectors.remove, function (e) {
         e.preventDefault();
         _this.remove($(this));
       });
     },
     collapse: function (element) {
       var _this = this;
       //Find the box parent
       var box = element.parents(".box").first();
       //Find the body and the footer
       var box_content = box.find("> .box-body, > .box-footer, > form  >.box-body, > form > .box-footer");
       if (!box.hasClass("collapsed-box")) {
         //Convert minus into plus
         element.children(":first")
           .removeClass(_this.icons.collapse)
           .addClass(_this.icons.open);
         //Hide the content
         box_content.slideUp(_this.animationSpeed, function () {
           box.addClass("collapsed-box");
         });
       } else {
         //Convert plus into minus
         element.children(":first")
           .removeClass(_this.icons.open)
           .addClass(_this.icons.collapse);
         //Show the content
         box_content.slideDown(_this.animationSpeed, function () {
           box.removeClass("collapsed-box");
         });
       }
     },
     remove: function (element) {
       //Find the box parent
       var box = element.parents(".box").first();
       box.slideUp(this.animationSpeed);
     }
   };
 }
References activate(), addClass, AdminLTE, close, css(), destroy, document, e, fn, hover, icons, o, off, on, parent(), removeClass(), width, and window.
activate()
AdminLTE layout AdminLTE a enableControlSidebar &&AdminLTE controlSidebar a navbarMenuSlimscroll a sidebarPushMenu &&AdminLTE pushMenu a enableBSToppltip &&body a enableBoxWidget &&AdminLTE boxWidget activate ()
Referenced by _init().
each()
btn group [data-toggle="btn-toggle"] each (function() { var group=$(this);$(this).find(".btn").on('click', function(e) { group.find(".btn.active").removeClass("active");$(this).addClass("active");e.preventDefault();});} function() { var group=$(this);$(this).find(".btn").on('click', function(e) { group.find(".btn.active").removeClass("active");$(this).addClass("active");e.preventDefault();});})
References addClass, and e.
if() [1/4]
if (o.directChat. enable)
Definition at line 202 of file app.js.
{
     $(document).on('click', o.directChat.contactToggleSelector, function () {
       var box = $(this).parents('.direct-chat').first();
       box.toggleClass('direct-chat-contacts-open');
     });
   }
References document, o, and on.
if() [2/4]
if (o. enableControlSidebar)
Definition at line 166 of file app.js.
{
     $.AdminLTE.controlSidebar.activate();
   }
if() [3/4]
if ("undefined" "undefined" = =typeof jQuery) new
Bootstrap v3.3.7 (http://getbootstrap.com) Copyright 2011-2016 Twitter, Inc. Licensed under the MIT license
Definition at line 147 of file app.js.
{
     $.extend(true,
       $.AdminLTE.options,
       AdminLTEOptions);
   }
References AdminLTE.
if() [4/4]
if (typeof jQuery = == "undefined")
AdminLTE app.js
Main JS application file for AdminLTE v2. This file should be included in all pages. It controls some layout options and implements exclusive AdminLTE plugins.
@Author Almsaeed Studio @Support http://www.almsaeedstudio.com @Email abdul.nosp@m.lah@.nosp@m.almsa.nosp@m.eeds.nosp@m.tudio.nosp@m..com
Version
2.3.6 @license MIT http://opensource.org/licenses/MIT
Definition at line 15 of file app.js.
{
   throw new Error("AdminLTE requires jQuery");
 }
removeClass()
function body removeClass ("hold-transition" "hold-transition")
Referenced by _init(), change_skin(), ready(), and setup().
tree()
AdminLTE tree ('.sidebar' '.sidebar')
Variable Documentation
activateBox
function fn activateBox
Initial value:
= function () {
    $.AdminLTE.boxWidget.activate(this);
  }
Definition at line 695 of file app.js.
AdminLTE
AdminLTE = {}
Definition at line 28 of file app.js.
Referenced by _init(), and if().
boxRefresh
function fn boxRefresh
Definition at line 615 of file app.js.
jQuery
jQuery
Definition at line 678 of file app.js.
Referenced by !function(), and if().
o
var o = $.AdminLTE.options
Definition at line 154 of file app.js.
Referenced by !function(), _init(), addEventListener(), YAWK\webmail::drawHeaders(), YAWK\webmail::drawMailboxControls(), if(), install(), ready(), and shuffle().
options
AdminLTE options
Definition at line 35 of file app.js.
Referenced by !function(), animateTokens(), extend(), and ready().
removeBox
fn removeBox
Initial value:
= function () {
    var button = $($.AdminLTE.boxWidget.selectors.remove, this);
    $.AdminLTE.boxWidget.remove(button);
  }
Definition at line 704 of file app.js.
todolist
function fn todolist
Definition at line 723 of file app.js.
toggleBox
fn toggleBox
Initial value:
= function () {
    var button = $($.AdminLTE.boxWidget.selectors.collapse, this);
    $.AdminLTE.boxWidget.collapse(button);
  }
Definition at line 699 of file app.js.