YaWK: /var/www/htdocs/yawk.io/system/plugins/blog/blog.php File Reference
blog.php File Reference
Variables
$blog = new \YAWK\PLUGINS\BLOG\blog()
$templateID = YAWK\template::getCurrentTemplateId($db)
if(!isset($_GET['blogid'])) else
Variable Documentation
$blog
$blog = new \YAWK\PLUGINS\BLOG\blog()
Definition at line 7 of file blog.php.
$templateID
$templateID = YAWK\template::getCurrentTemplateId($db)
Definition at line 9 of file blog.php.
Referenced by YAWK\sys\checkIfAssetsAreLoaded(), YAWK\menu\display(), YAWK\template\downloadTemplate(), YAWK\template\drawAssetsSelectFields(), YAWK\template\drawAssetsTitles(), YAWK\WIDGETS\BLOG\WIDGET\blogWidget\drawBlogWidget(), YAWK\template\getCustomCSSFile(), YAWK\template\getCustomJSFile(), YAWK\template\getPositionIndicatorStatusArray(), YAWK\template\getPositionStatesArray(), YAWK\template\getTemplateSettingsArray(), YAWK\template\loadActiveAssets(), YAWK\template\loadActiveAssetsIntoArray(), YAWK\template\returnCurrentBootstrapVersion(), and YAWK\template\switchPositionIndicators().
else
if ($blog->loadBlogProperties($db, $blog->blogid)===false) if ($blog->published !=0) else
Initial value:
{
        $blog->blogid = $_GET['blogid']
Definition at line 25 of file blog.php.