YaWK: /var/www/htdocs/yawk.io/system/plugins/blog/admin/blog-togglegroup.php File Reference
blog-togglegroup.php File Reference
Variables
if(!isset($language)||(!isset($lang))) $item = new \YAWK\PLUGINS\BLOG\blog()
switch($item->gid) $progress = "success"
$item blogid = $_GET['blogid']
if($item->toggleRole($db, $item->gid, $item->id)) else
if(!isset($db)) $item gid = $_GET['itemgid']
$item id = $_GET['itemid']
Variable Documentation
$item
if (!isset($language)||(!isset($lang))) $item = new \YAWK\PLUGINS\BLOG\blog()
Definition at line 9 of file blog-togglegroup.php.
Referenced by YAWK\sys\array2lines(), YAWK\stats\calculateStatsFromArray(), YAWK\BACKUP\backup\checkFolders(), YAWK\stats\countBrowsers(), YAWK\stats\countOSVersions(), YAWK\webmail\drawFolders(), YAWK\template\drawFontFamilySelectField(), YAWK\webmail\drawHeaders(), and YAWK\sys\multiarray2lines().
$progress
switch ($item->gid) $progress = "success"
Definition at line 44 of file blog-togglegroup.php.
blogid
$item blogid = $_GET['blogid']
Definition at line 17 of file blog-togglegroup.php.
else
if ($item->toggleRole($db, $item->gid, $item->id)) else
Initial value:
{
    print \YAWK\alert::draw("danger", "$lang[ERROR]", "$lang[GROUPS] $lang[TOGGLE_FAILED]","plugin=blog&pluginpage=blog-entries&blogid=" . $item->blogid . "","3800")
Definition at line 51 of file blog-togglegroup.php.
gid
if (!isset($db)) $item gid = $_GET['itemgid']
Definition at line 16 of file blog-togglegroup.php.
id
$item id = $_GET['itemid']
Definition at line 18 of file blog-togglegroup.php.