YaWK: /var/www/htdocs/yawk.io/system/plugins/blog/admin/blog-setup.php File Reference
blog-setup.php File Reference
Variables
$authorChecked = ""
$dateChecked = ""
$descCheckbox = ""
$frontendIconChecked = ""
$permaLinkChecked = ""
$previewChecked = ""
$spacerChecked = ""
$titleCheckedValue = 0
$totalVotesSelectedOff = ""
$totalVotesSelectedOn = ""
$blog comments = $blog->getBlogProperty($db, $blog->blogid, "comments")
$blog description = $blog->getBlogProperty($db, $blog->blogid, "description")
if(isset($_POST['setup'])) else
foreach (YAWK\sys::getGroups($db, "blog") as $gid)
$blog frontendIcon = $blog->getBlogProperty($db, $blog->blogid, "frontendIcon")
$blog gid = $blog->getBlogProperty($db, $blog->blogid, "gid")
$blog icon = $blog->getBlogProperty($db, $blog->blogid, "icon")
$blog layout = $blog->getBlogProperty($db, $blog->blogid, "layout")
$blog limitEntries = $blog->getBlogProperty($db, $blog->blogid, "limitEntries")
if(isset($_GET['blogid'])) $blog name = $blog->getBlogProperty($db, $blog->blogid, "name")
$blog permaLink = $blog->getBlogProperty($db, $blog->blogid, "permaLink")
PHP
$blog preview = $blog->getBlogProperty($db, $blog->blogid, "preview")
$blog sequence = $blog->getBlogProperty($db, $blog->blogid, "sequence")
$blog showAuthor = $blog->getBlogProperty($db, $blog->blogid, "showauthor")
$blog showDate = $blog->getBlogProperty($db, $blog->blogid, "showdate")
$blog showDesc = $blog->getBlogProperty($db, $blog->blogid, "showdesc")
$blog showTitle = 0
$blog showTotalVotes = $blog->getBlogProperty($db, $blog->blogid, "showTotalVotes")
$blog sortation = $blog->getBlogProperty($db, $blog->blogid, "sortation")
$blog spacer = $blog->getBlogProperty($db, $blog->blogid, "spacer")
$blog voting = $blog->getBlogProperty($db, $blog->blogid, "voting")
Variable Documentation
$authorChecked
$authorChecked = ""
Definition at line 175 of file blog-setup.php.
$dateChecked
$dateChecked = ""
Definition at line 169 of file blog-setup.php.
$descCheckbox
$descCheckbox = ""
Definition at line 163 of file blog-setup.php.
$frontendIconChecked
$frontendIconChecked = ""
Definition at line 199 of file blog-setup.php.
$permaLinkChecked
$permaLinkChecked = ""
Definition at line 181 of file blog-setup.php.
$previewChecked
$previewChecked = ""
Definition at line 187 of file blog-setup.php.
$spacerChecked
$spacerChecked = ""
Definition at line 193 of file blog-setup.php.
$titleCheckedValue
$titleCheckedValue = 0
Definition at line 157 of file blog-setup.php.
$totalVotesSelectedOff
$totalVotesSelectedOff = ""
Definition at line 277 of file blog-setup.php.
$totalVotesSelectedOn
$totalVotesSelectedOn = ""
Definition at line 276 of file blog-setup.php.
comments
$blog comments = $blog->getBlogProperty($db, $blog->blogid, "comments")
Definition at line 136 of file blog-setup.php.
description
$blog description = $blog->getBlogProperty($db, $blog->blogid, "description")
Definition at line 49 of file blog-setup.php.
Referenced by YAWK\licenses\__construct(), YAWK\licenses\createLicenseText(), YAWK\template\downloadTemplate(), and YAWK\template\loadProperties().
else
if ($blog->showTotalVotes=='1') else
Initial value:
{
        $blog->showTitle = $blog->getBlogProperty($db, $blog->blogid, "showtitle")
Definition at line 127 of file blog-setup.php.
foreach
foreach(YAWK\sys::getGroups($db, "blog") as $gid) (YAWK\sys::getGroups($db, "blog") as $gid)
Definition at line 537 of file blog-setup.php.
frontendIcon
$blog frontendIcon = $blog->getBlogProperty($db, $blog->blogid, "frontendIcon")
Definition at line 143 of file blog-setup.php.
gid
$blog gid = $blog->getBlogProperty($db, $blog->blogid, "gid")
Definition at line 139 of file blog-setup.php.
Referenced by YAWK\page\loadProperties(), YAWK\page\loadPropertiesByID(), YAWK\stats\prepareData(), and ready().
icon
$blog icon = $blog->getBlogProperty($db, $blog->blogid, "icon")
Definition at line 50 of file blog-setup.php.
layout
$blog layout = $blog->getBlogProperty($db, $blog->blogid, "layout")
Definition at line 138 of file blog-setup.php.
limitEntries
$blog limitEntries = $blog->getBlogProperty($db, $blog->blogid, "limitEntries")
Definition at line 144 of file blog-setup.php.
name
if (isset($_GET[ 'blogid'])) $blog name = $blog->getBlogProperty($db, $blog->blogid, "name")
Definition at line 48 of file blog-setup.php.
permaLink
$blog permaLink = $blog->getBlogProperty($db, $blog->blogid, "permaLink")
Definition at line 137 of file blog-setup.php.
PHP
PHP
Definition at line 556 of file blog-setup.php.
preview
$blog preview = $blog->getBlogProperty($db, $blog->blogid, "preview")
Definition at line 140 of file blog-setup.php.
sequence
$blog sequence = $blog->getBlogProperty($db, $blog->blogid, "sequence")
Definition at line 134 of file blog-setup.php.
showAuthor
$blog showAuthor = $blog->getBlogProperty($db, $blog->blogid, "showauthor")
Definition at line 133 of file blog-setup.php.
showDate
$blog showDate = $blog->getBlogProperty($db, $blog->blogid, "showdate")
Definition at line 132 of file blog-setup.php.
showDesc
$blog showDesc = $blog->getBlogProperty($db, $blog->blogid, "showdesc")
Definition at line 131 of file blog-setup.php.
showTitle
$blog showTitle = 0
Definition at line 156 of file blog-setup.php.
showTotalVotes
$blog showTotalVotes = $blog->getBlogProperty($db, $blog->blogid, "showTotalVotes")
Definition at line 145 of file blog-setup.php.
sortation
$blog sortation = $blog->getBlogProperty($db, $blog->blogid, "sortation")
Definition at line 135 of file blog-setup.php.
spacer
$blog spacer = $blog->getBlogProperty($db, $blog->blogid, "spacer")
Definition at line 142 of file blog-setup.php.
voting
$blog voting = $blog->getBlogProperty($db, $blog->blogid, "voting")
Definition at line 141 of file blog-setup.php.