YaWK: Ifsnop\Mysqldump\Mysqldump Class Reference
Ifsnop\Mysqldump\Mysqldump Class Reference
Public Member Functions
__construct ($dsn='', $user='', $pass='', $dumpSettings=array(), $pdoSettings=array())
__destruct ()
createStandInTable ($viewName)
endListValues ($tableName)
getColumnNames ($tableName)
getColumnStmt ($tableName)
prepareListValues ($tableName)
setTransformColumnValueHook ($callable)
start ($filename='')
Static Public Member Functions
static array_replace_recursive ($array1, $array2)
Public Attributes
$dsn
$fileName = 'php://output'
$pass
$user
const BZIP2 = 'Bzip2'
const GZIP = 'Gzip'
const MAXLINESIZE = 1000000
const NONE = 'None'
const UTF8 = 'utf8'
const UTF8MB4 = 'utf8mb4'
Protected Member Functions
hookTransformColumnValue ($tableName, $colName, $colValue)
Private Member Functions
connect ()
escape ($colValue, $colType)
exportEvents ()
exportProcedures ()
exportTables ()
exportTriggers ()
exportViews ()
getDatabaseStructureEvents ()
getDatabaseStructureProcedures ()
getDatabaseStructureTables ()
getDatabaseStructureTriggers ()
getDatabaseStructureViews ()
getDumpFileFooter ()
getDumpFileHeader ()
getEventStructure ($eventName)
getProcedureStructure ($procedureName)
getTableColumnTypes ($tableName)
getTableStructure ($tableName)
getTriggerStructure ($triggerName)
getViewStructureTable ($viewName)
getViewStructureView ($viewName)
listValues ($tableName)
matches ($table, $arr)
parseDsn ($dsn)
prepareColumnValues ($tableName, $row)
Private Attributes
$compressManager
$dbHandler = null
$dbName
$dbType = ""
$dsnArray = array()
$dumpSettings = array()
$events = array()
$host
$pdoSettings = array()
$procedures = array()
$tableColumnTypes = array()
$tables = array()
$transformColumnValueCallable
$triggers = array()
$typeAdapter
$version
$views = array()
Detailed Description
Definition at line 34 of file Mysqldump.php.
Constructor & Destructor Documentation
__construct()
Ifsnop\Mysqldump\Mysqldump::__construct ($dsn = '', $user = '', $pass = '', $dumpSettings = array(), $pdoSettings = array())
Constructor of Mysqldump. Note that in the case of an SQLite database connection, the filename must be in the $db parameter.
Parameters
string $dsn PDO DSN connection string
string $user SQL account username
string $pass SQL account password
array $dumpSettings SQL database settings
array $pdoSettings PDO configured attributes
Definition at line 111 of file Mysqldump.php.
       {
         $dumpSettingsDefault = array(
             'include-tables' => array(),
             'exclude-tables' => array(),
             'compress' => Mysqldump::NONE,
             'init_commands' => array(),
             'no-data' => array(),
             'reset-auto-increment' => false,
             'add-drop-database' => false,
             'add-drop-table' => false,
             'add-drop-trigger' => true,
             'add-locks' => true,
             'complete-insert' => false,
             'databases' => false,
             'default-character-set' => Mysqldump::UTF8,
             'disable-keys' => true,
             'extended-insert' => true,
             'events' => false,
             'hex-blob' => true, /* faster than escaped content */
             'insert-ignore' => false,
             'net_buffer_length' => self::MAXLINESIZE,
             'no-autocommit' => true,
             'no-create-info' => false,
             'lock-tables' => true,
             'routines' => false,
             'single-transaction' => true,
             'skip-triggers' => false,
             'skip-tz-utc' => false,
             'skip-comments' => false,
             'skip-dump-date' => false,
             'skip-definer' => false,
             'where' => '',
             /* deprecated */
             'disable-foreign-keys-check' => true
         );
         $pdoSettingsDefault = array(
             PDO::ATTR_PERSISTENT => true,
             PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
         );
         $this->user = $user;
         $this->pass = $pass;
         $this->parseDsn($dsn);
         // this drops MYSQL dependency, only use the constant if it's defined
         if ("mysql" === $this->dbType) {
             $pdoSettingsDefault[PDO::MYSQL_ATTR_USE_BUFFERED_QUERY] = false;
         }
         $this->pdoSettings = self::array_replace_recursive($pdoSettingsDefault, $pdoSettings);
         $this->dumpSettings = self::array_replace_recursive($dumpSettingsDefault, $dumpSettings);
         $this->dumpSettings['init_commands'][] = "SET NAMES ".$this->dumpSettings['default-character-set'];
         if (false === $this->dumpSettings['skip-tz-utc']) {
             $this->dumpSettings['init_commands'][] = "SET TIME_ZONE='+00:00'";
         }
         $diff = array_diff(array_keys($this->dumpSettings), array_keys($dumpSettingsDefault));
         if (count($diff) > 0) {
             throw new Exception("Unexpected value in dumpSettings: (".implode(",", $diff).")");
         }
         if (!is_array($this->dumpSettings['include-tables']) ||
             !is_array($this->dumpSettings['exclude-tables'])) {
             throw new Exception("Include-tables and exclude-tables should be arrays");
         }
         // Dump the same views as tables, mimic mysqldump behaviour
         $this->dumpSettings['include-views'] = $this->dumpSettings['include-tables'];
         // Create a new compressManager to manage compressed output
         $this->compressManager = CompressManagerFactory::create($this->dumpSettings['compress']);
     }
References Ifsnop\Mysqldump\Mysqldump\$dsn, Ifsnop\Mysqldump\Mysqldump\$dumpSettings, Ifsnop\Mysqldump\Mysqldump\$pass, Ifsnop\Mysqldump\Mysqldump\$pdoSettings, Ifsnop\Mysqldump\Mysqldump\$user, Ifsnop\Mysqldump\Mysqldump\array_replace_recursive(), Ifsnop\Mysqldump\CompressManagerFactory\create(), Ifsnop\Mysqldump\Mysqldump\NONE, Ifsnop\Mysqldump\Mysqldump\parseDsn(), and Ifsnop\Mysqldump\Mysqldump\UTF8.
__destruct()
Ifsnop\Mysqldump\Mysqldump::__destruct ()
Destructor of Mysqldump. Unsets dbHandlers and database objects.
Definition at line 196 of file Mysqldump.php.
     {
         $this->dbHandler = null;
     }
Member Function Documentation
array_replace_recursive()
static Ifsnop\Mysqldump\Mysqldump::array_replace_recursive ($array1, $array2) static
Custom array_replace_recursive to be used if PHP < 5.3 Replaces elements from passed arrays into the first array recursively
Parameters
array $array1 The array in which elements are replaced
array $array2 The array from which elements will be extracted
Returns
array Returns an array, or NULL if an error occurs.
Definition at line 210 of file Mysqldump.php.
     {
         if (function_exists('array_replace_recursive')) {
             return array_replace_recursive($array1, $array2);
         }
         foreach ($array2 as $key => $value) {
             if (is_array($value)) {
                 $array1[$key] = self::array_replace_recursive($array1[$key], $value);
             } else {
                 $array1[$key] = $value;
             }
         }
         return $array1;
     }
References $value, and as.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
connect()
Ifsnop\Mysqldump\Mysqldump::connect () private
Connect with PDO
Returns
null
Definition at line 276 of file Mysqldump.php.
     {
         // Connecting with PDO
         try {
             switch ($this->dbType) {
                 case 'sqlite':
                     $this->dbHandler = @new PDO("sqlite:".$this->dbName, null, null, $this->pdoSettings);
                     break;
                 case 'mysql':
                 case 'pgsql':
                 case 'dblib':
                     $this->dbHandler = @new PDO(
                         $this->dsn,
                         $this->user,
                         $this->pass,
                         $this->pdoSettings
                     );
                     // Execute init commands once connected
                     foreach ($this->dumpSettings['init_commands'] as $stmt) {
                         $this->dbHandler->exec($stmt);
                     }
                     // Store server version
                     $this->version = $this->dbHandler->getAttribute(PDO::ATTR_SERVER_VERSION);
                     break;
                 default:
                     throw new Exception("Unsupported database type (".$this->dbType.")");
             }
         } catch (PDOException $e) {
             throw new Exception(
                 "Connection to ".$this->dbType." failed with message: ".
                 $e->getMessage()
             );
         }
         if (is_null($this->dbHandler)) {
             throw new Exception("Connection to ".$this->dbType."failed");
         }
         $this->dbHandler->setAttribute(PDO::ATTR_ORACLE_NULLS, PDO::NULL_NATURAL);
         $this->typeAdapter = TypeAdapterFactory::create($this->dbType, $this->dbHandler, $this->dumpSettings);
     }
References $e, as, Ifsnop\Mysqldump\TypeAdapterFactory\create(), and version.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
createStandInTable()
Ifsnop\Mysqldump\Mysqldump::createStandInTable ($viewName)
Write a create table statement for the table Stand-In, show create table would return a create algorithm when used on a view
Parameters
string $viewName Name of view to export
Returns
string create statement
Definition at line 761 of file Mysqldump.php.
{
         $ret = array();
         foreach ($this->tableColumnTypes[$viewName] as $k => $v) {
             $ret[] = "`${k}` ${v['type_sql']}";
         }
         $ret = implode(PHP_EOL.",", $ret);
         $ret = "CREATE TABLE IF NOT EXISTS `$viewName` (".
             PHP_EOL.$ret.PHP_EOL.");".PHP_EOL;
         return $ret;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\getViewStructureTable().
endListValues()
Ifsnop\Mysqldump\Mysqldump::endListValues ($tableName)
Table rows extractor, close locks and commits after dump
Parameters
string $tableName Name of table to export
Returns
null
Definition at line 1073 of file Mysqldump.php.
     {
         if ($this->dumpSettings['disable-keys']) {
             $this->compressManager->write(
                 $this->typeAdapter->end_add_disable_keys($tableName)
             );
         }
         if ($this->dumpSettings['add-locks']) {
             $this->compressManager->write(
                 $this->typeAdapter->end_add_lock_table($tableName)
             );
         }
         if ($this->dumpSettings['single-transaction']) {
             $this->dbHandler->exec($this->typeAdapter->commit_transaction());
         }
         if ($this->dumpSettings['lock-tables']) {
             $this->typeAdapter->unlock_table($tableName);
         }
         // Commit to enable autocommit
         if ($this->dumpSettings['no-autocommit']) {
             $this->compressManager->write(
                 $this->typeAdapter->end_disable_autocommit()
             );
         }
         $this->compressManager->write(PHP_EOL);
         return;
     }
Referenced by Ifsnop\Mysqldump\Mysqldump\listValues().
escape()
Ifsnop\Mysqldump\Mysqldump::escape ($colValue, $colType) private
Escape values with quotes when needed
Parameters
string $tableName Name of table which contains rows
array $row Associative array of column names and values to be quoted
Returns
string
Definition at line 902 of file Mysqldump.php.
     {
         if (is_null($colValue)) {
             return "NULL";
         } elseif ($this->dumpSettings['hex-blob'] && $colType['is_blob']) {
             if ($colType['type'] == 'bit' || !empty($colValue)) {
                 return "0x${colValue}";
             } else {
                 return "''";
             }
         } elseif ($colType['is_numeric']) {
             return $colValue;
         }
         return $this->dbHandler->quote($colValue);
     }
Referenced by Ifsnop\Mysqldump\Mysqldump\prepareColumnValues().
exportEvents()
Ifsnop\Mysqldump\Mysqldump::exportEvents () private
Exports all the events found in database
Returns
null
Definition at line 652 of file Mysqldump.php.
     {
         // Exporting triggers one by one
         foreach ($this->events as $event) {
             $this->getEventStructure($event);
         }
     }
References as, and Ifsnop\Mysqldump\Mysqldump\getEventStructure().
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
exportProcedures()
Ifsnop\Mysqldump\Mysqldump::exportProcedures () private
Exports all the procedures found in database
Returns
null
Definition at line 639 of file Mysqldump.php.
     {
         // Exporting triggers one by one
         foreach ($this->procedures as $procedure) {
             $this->getProcedureStructure($procedure);
         }
     }
References as, and Ifsnop\Mysqldump\Mysqldump\getProcedureStructure().
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
exportTables()
Ifsnop\Mysqldump\Mysqldump::exportTables () private
Exports all the tables selected from database
Returns
null
Definition at line 577 of file Mysqldump.php.
     {
         // Exporting tables one by one
         foreach ($this->tables as $table) {
             if ($this->matches($table, $this->dumpSettings['exclude-tables'])) {
                 continue;
             }
             $this->getTableStructure($table);
             if (false === $this->dumpSettings['no-data']) { // don't break compatibility with old trigger
                 $this->listValues($table);
             } else if (true === $this->dumpSettings['no-data']
                 || $this->matches($table, $this->dumpSettings['no-data'])) {
                 continue;
             } else {
                 $this->listValues($table);
             }
         }
     }
References as, Ifsnop\Mysqldump\Mysqldump\getTableStructure(), Ifsnop\Mysqldump\Mysqldump\listValues(), and Ifsnop\Mysqldump\Mysqldump\matches().
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
exportTriggers()
Ifsnop\Mysqldump\Mysqldump::exportTriggers () private
Exports all the triggers found in database
Returns
null
Definition at line 626 of file Mysqldump.php.
     {
         // Exporting triggers one by one
         foreach ($this->triggers as $trigger) {
             $this->getTriggerStructure($trigger);
         }
     }
References as, and Ifsnop\Mysqldump\Mysqldump\getTriggerStructure().
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
exportViews()
Ifsnop\Mysqldump\Mysqldump::exportViews () private
Exports all the views found in database
Returns
null
Definition at line 601 of file Mysqldump.php.
     {
         if (false === $this->dumpSettings['no-create-info']) {
             // Exporting views one by one
             foreach ($this->views as $view) {
                 if ($this->matches($view, $this->dumpSettings['exclude-tables'])) {
                     continue;
                 }
                 $this->tableColumnTypes[$view] = $this->getTableColumnTypes($view);
                 $this->getViewStructureTable($view);
             }
             foreach ($this->views as $view) {
                 if ($this->matches($view, $this->dumpSettings['exclude-tables'])) {
                     continue;
                 }
                 $this->getViewStructureView($view);
             }
         }
     }
References as, Ifsnop\Mysqldump\Mysqldump\getTableColumnTypes(), Ifsnop\Mysqldump\Mysqldump\getViewStructureTable(), Ifsnop\Mysqldump\Mysqldump\getViewStructureView(), and Ifsnop\Mysqldump\Mysqldump\matches().
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getColumnNames()
Ifsnop\Mysqldump\Mysqldump::getColumnNames ($tableName)
Build SQL List of all columns on current table which will be used for inserting
Parameters
string $tableName Name of table to get columns
Returns
array columns for sql sentence for insert
Definition at line 1140 of file Mysqldump.php.
     {
         $colNames = array();
         foreach($this->tableColumnTypes[$tableName] as $colName => $colType) {
             if ($colType['is_virtual']) {
                 $this->dumpSettings['complete-insert'] = true;
                 continue;
             } else {
                 $colNames[] = "`${colName}`";
             }
         }
         return $colNames;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\listValues().
getColumnStmt()
Ifsnop\Mysqldump\Mysqldump::getColumnStmt ($tableName)
Build SQL List of all columns on current table which will be used for selecting
Parameters
string $tableName Name of table to get columns
Returns
array SQL sentence with columns for select
Definition at line 1114 of file Mysqldump.php.
     {
         $colStmt = array();
         foreach ($this->tableColumnTypes[$tableName] as $colName => $colType) {
             if ($colType['type'] == 'bit' && $this->dumpSettings['hex-blob']) {
                 $colStmt[] = "LPAD(HEX(`${colName}`),2,'0') AS `${colName}`";
             } else if ($colType['is_blob'] && $this->dumpSettings['hex-blob']) {
                 $colStmt[] = "HEX(`${colName}`) AS `${colName}`";
             } else if ($colType['is_virtual']) {
                 $this->dumpSettings['complete-insert'] = true;
                 continue;
             } else {
                 $colStmt[] = "`${colName}`";
             }
         }
         return $colStmt;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\listValues().
getDatabaseStructureEvents()
Ifsnop\Mysqldump\Mysqldump::getDatabaseStructureEvents () private
Reads event names from database. Fills $this->tables array so they will be dumped later.
Returns
null
Definition at line 540 of file Mysqldump.php.
     {
         // Listing all events from database
         if ($this->dumpSettings['events']) {
             foreach ($this->dbHandler->query($this->typeAdapter->show_events($this->dbName)) as $row) {
                 array_push($this->events, $row['event_name']);
             }
         }
         return;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDatabaseStructureProcedures()
Ifsnop\Mysqldump\Mysqldump::getDatabaseStructureProcedures () private
Reads procedure names from database. Fills $this->tables array so they will be dumped later.
Returns
null
Definition at line 523 of file Mysqldump.php.
     {
         // Listing all procedures from database
         if ($this->dumpSettings['routines']) {
             foreach ($this->dbHandler->query($this->typeAdapter->show_procedures($this->dbName)) as $row) {
                 array_push($this->procedures, $row['procedure_name']);
             }
         }
         return;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDatabaseStructureTables()
Ifsnop\Mysqldump\Mysqldump::getDatabaseStructureTables () private
Reads table names from database. Fills $this->tables array so they will be dumped later.
Returns
null
Definition at line 446 of file Mysqldump.php.
     {
         // Listing all tables from database
         if (empty($this->dumpSettings['include-tables'])) {
             // include all tables for now, blacklisting happens later
             foreach ($this->dbHandler->query($this->typeAdapter->show_tables($this->dbName)) as $row) {
                 array_push($this->tables, current($row));
             }
         } else {
             // include only the tables mentioned in include-tables
             foreach ($this->dbHandler->query($this->typeAdapter->show_tables($this->dbName)) as $row) {
                 if (in_array(current($row), $this->dumpSettings['include-tables'], true)) {
                     array_push($this->tables, current($row));
                     $elem = array_search(
                         current($row),
                         $this->dumpSettings['include-tables']
                     );
                     unset($this->dumpSettings['include-tables'][$elem]);
                 }
             }
         }
         return;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDatabaseStructureTriggers()
Ifsnop\Mysqldump\Mysqldump::getDatabaseStructureTriggers () private
Reads trigger names from database. Fills $this->tables array so they will be dumped later.
Returns
null
Definition at line 506 of file Mysqldump.php.
     {
         // Listing all triggers from database
         if (false === $this->dumpSettings['skip-triggers']) {
             foreach ($this->dbHandler->query($this->typeAdapter->show_triggers($this->dbName)) as $row) {
                 array_push($this->triggers, $row['Trigger']);
             }
         }
         return;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDatabaseStructureViews()
Ifsnop\Mysqldump\Mysqldump::getDatabaseStructureViews () private
Reads view names from database. Fills $this->tables array so they will be dumped later.
Returns
null
Definition at line 476 of file Mysqldump.php.
     {
         // Listing all views from database
         if (empty($this->dumpSettings['include-views'])) {
             // include all views for now, blacklisting happens later
             foreach ($this->dbHandler->query($this->typeAdapter->show_views($this->dbName)) as $row) {
                 array_push($this->views, current($row));
             }
         } else {
             // include only the tables mentioned in include-tables
             foreach ($this->dbHandler->query($this->typeAdapter->show_views($this->dbName)) as $row) {
                 if (in_array(current($row), $this->dumpSettings['include-views'], true)) {
                     array_push($this->views, current($row));
                     $elem = array_search(
                         current($row),
                         $this->dumpSettings['include-views']
                     );
                     unset($this->dumpSettings['include-views'][$elem]);
                 }
             }
         }
         return;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDumpFileFooter()
Ifsnop\Mysqldump\Mysqldump::getDumpFileFooter () private
Returns footer for dump file
Returns
string
Definition at line 426 of file Mysqldump.php.
     {
         $footer = '';
         if (!$this->dumpSettings['skip-comments']) {
             $footer .= '-- Dump completed';
             if (!$this->dumpSettings['skip-dump-date']) {
                 $footer .= ' on: '.date('r');
             }
             $footer .= PHP_EOL;
         }
         return $footer;
     }
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getDumpFileHeader()
Ifsnop\Mysqldump\Mysqldump::getDumpFileHeader () private
Returns header for dump file
Returns
string
Definition at line 400 of file Mysqldump.php.
     {
         $header = '';
         if (!$this->dumpSettings['skip-comments']) {
             // Some info about software, source and time
             $header = "-- mysqldump-php https://github.com/ifsnop/mysqldump-php".PHP_EOL.
                 "--".PHP_EOL.
                 "-- Host: {$this->host}\tDatabase: {$this->dbName}".PHP_EOL.
                 "-- ------------------------------------------------------".PHP_EOL;
             if (!empty($this->version)) {
                 $header .= "-- Server version \t".$this->version.PHP_EOL;
             }
             if (!$this->dumpSettings['skip-dump-date']) {
                 $header .= "-- Date: ".date('r').PHP_EOL.PHP_EOL;
             }
         }
         return $header;
     }
References $header, and version.
Referenced by Ifsnop\Mysqldump\Mysqldump\start().
getEventStructure()
Ifsnop\Mysqldump\Mysqldump::getEventStructure ($eventName) private
Event structure extractor
Parameters
string $eventName Name of event to export
Returns
null
Definition at line 856 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['skip-comments']) {
             $ret = "--".PHP_EOL.
                 "-- Dumping events for database '".$this->dbName."'".PHP_EOL.
                 "--".PHP_EOL.PHP_EOL;
             $this->compressManager->write($ret);
         }
         $stmt = $this->typeAdapter->show_create_event($eventName);
         foreach ($this->dbHandler->query($stmt) as $r) {
             $this->compressManager->write(
                 $this->typeAdapter->create_event($r)
             );
             return;
         }
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportEvents().
getProcedureStructure()
Ifsnop\Mysqldump\Mysqldump::getProcedureStructure ($procedureName) private
Procedure structure extractor
Parameters
string $procedureName Name of procedure to export
Returns
null
Definition at line 833 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['skip-comments']) {
             $ret = "--".PHP_EOL.
                 "-- Dumping routines for database '".$this->dbName."'".PHP_EOL.
                 "--".PHP_EOL.PHP_EOL;
             $this->compressManager->write($ret);
         }
         $stmt = $this->typeAdapter->show_create_procedure($procedureName);
         foreach ($this->dbHandler->query($stmt) as $r) {
             $this->compressManager->write(
                 $this->typeAdapter->create_procedure($r)
             );
             return;
         }
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportProcedures().
getTableColumnTypes()
Ifsnop\Mysqldump\Mysqldump::getTableColumnTypes ($tableName) private
Store column types to create data dumps and for Stand-In tables
Parameters
string $tableName Name of table to export
Returns
array type column types detailed
Definition at line 701 of file Mysqldump.php.
{
         $columnTypes = array();
         $columns = $this->dbHandler->query(
             $this->typeAdapter->show_columns($tableName)
         );
         $columns->setFetchMode(PDO::FETCH_ASSOC);
         foreach ($columns as $key => $col) {
             $types = $this->typeAdapter->parseColumnType($col);
             $columnTypes[$col['Field']] = array(
                 'is_numeric'=> $types['is_numeric'],
                 'is_blob' => $types['is_blob'],
                 'type' => $types['type'],
                 'type_sql' => $col['Type'],
                 'is_virtual' => $types['is_virtual']
             );
         }
         return $columnTypes;
     }
References $col, and as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportViews(), and Ifsnop\Mysqldump\Mysqldump\getTableStructure().
getTableStructure()
Ifsnop\Mysqldump\Mysqldump::getTableStructure ($tableName) private
Table structure extractor
Todo:
move specific mysql code to typeAdapter
Parameters
string $tableName Name of table to export
Returns
null
Definition at line 667 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['no-create-info']) {
             $ret = '';
             if (!$this->dumpSettings['skip-comments']) {
                 $ret = "--".PHP_EOL.
                     "-- Table structure for table `$tableName`".PHP_EOL.
                     "--".PHP_EOL.PHP_EOL;
             }
             $stmt = $this->typeAdapter->show_create_table($tableName);
             foreach ($this->dbHandler->query($stmt) as $r) {
                 $this->compressManager->write($ret);
                 if ($this->dumpSettings['add-drop-table']) {
                     $this->compressManager->write(
                         $this->typeAdapter->drop_table($tableName)
                     );
                 }
                 $this->compressManager->write(
                     $this->typeAdapter->create_table($r)
                 );
                 break;
             }
         }
         $this->tableColumnTypes[$tableName] = $this->getTableColumnTypes($tableName);
         return;
     }
References as, and Ifsnop\Mysqldump\Mysqldump\getTableColumnTypes().
Referenced by Ifsnop\Mysqldump\Mysqldump\exportTables().
getTriggerStructure()
Ifsnop\Mysqldump\Mysqldump::getTriggerStructure ($triggerName) private
Trigger structure extractor
Parameters
string $triggerName Name of trigger to export
Returns
null
Definition at line 811 of file Mysqldump.php.
     {
         $stmt = $this->typeAdapter->show_create_trigger($triggerName);
         foreach ($this->dbHandler->query($stmt) as $r) {
             if ($this->dumpSettings['add-drop-trigger']) {
                 $this->compressManager->write(
                     $this->typeAdapter->add_drop_trigger($triggerName)
                 );
             }
             $this->compressManager->write(
                 $this->typeAdapter->create_trigger($r)
             );
             return;
         }
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportTriggers().
getViewStructureTable()
Ifsnop\Mysqldump\Mysqldump::getViewStructureTable ($viewName) private
View structure extractor, create table (avoids cyclic references)
Todo:
move mysql specific code to typeAdapter
Parameters
string $viewName Name of view to export
Returns
null
Definition at line 729 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['skip-comments']) {
             $ret = "--".PHP_EOL.
                 "-- Stand-In structure for view `${viewName}`".PHP_EOL.
                 "--".PHP_EOL.PHP_EOL;
             $this->compressManager->write($ret);
         }
         $stmt = $this->typeAdapter->show_create_view($viewName);
         // create views as tables, to resolve dependencies
         foreach ($this->dbHandler->query($stmt) as $r) {
             if ($this->dumpSettings['add-drop-table']) {
                 $this->compressManager->write(
                     $this->typeAdapter->drop_view($viewName)
                 );
             }
             $this->compressManager->write(
                 $this->createStandInTable($viewName)
             );
             break;
         }
     }
References as, and Ifsnop\Mysqldump\Mysqldump\createStandInTable().
Referenced by Ifsnop\Mysqldump\Mysqldump\exportViews().
getViewStructureView()
Ifsnop\Mysqldump\Mysqldump::getViewStructureView ($viewName) private
View structure extractor, create view
Todo:
move mysql specific code to typeAdapter
Parameters
string $viewName Name of view to export
Returns
null
Definition at line 781 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['skip-comments']) {
             $ret = "--".PHP_EOL.
                 "-- View structure for view `${viewName}`".PHP_EOL.
                 "--".PHP_EOL.PHP_EOL;
             $this->compressManager->write($ret);
         }
         $stmt = $this->typeAdapter->show_create_view($viewName);
         // create views, to resolve dependencies
         // replacing tables with views
         foreach ($this->dbHandler->query($stmt) as $r) {
             // because we must replace table with view, we should delete it
             $this->compressManager->write(
                 $this->typeAdapter->drop_view($viewName)
             );
             $this->compressManager->write(
                 $this->typeAdapter->create_view($r)
             );
             break;
         }
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportViews().
hookTransformColumnValue()
Ifsnop\Mysqldump\Mysqldump::hookTransformColumnValue ($tableName, $colName, $colValue) protected
Give extending classes an opportunity to transform column values
Parameters
string $tableName Name of table which contains rows
string $colName Name of the column in question
string $colValue Value of the column in question
Returns
string
Definition at line 940 of file Mysqldump.php.
     {
         if (! $this->transformColumnValueCallable) {
             return $colValue;
         }
         return call_user_func_array($this->transformColumnValueCallable, array(
             $tableName,
             $colName,
             $colValue,
         ));
     }
Referenced by Ifsnop\Mysqldump\Mysqldump\prepareColumnValues().
listValues()
Ifsnop\Mysqldump\Mysqldump::listValues ($tableName) private
Table rows extractor
Parameters
string $tableName Name of table to export
Returns
null
Definition at line 960 of file Mysqldump.php.
     {
         $this->prepareListValues($tableName);
         $onlyOnce = true;
         $lineSize = 0;
         // colStmt is used to form a query to obtain row values
         $colStmt = $this->getColumnStmt($tableName);
         // colNames is used to get the name of the columns when using complete-insert
         if ($this->dumpSettings['complete-insert']) {
             $colNames = $this->getColumnNames($tableName);
         }
         $stmt = "SELECT ".implode(",", $colStmt)." FROM `$tableName`";
         if ($this->dumpSettings['where']) {
             $stmt .= " WHERE {$this->dumpSettings['where']}";
         }
         $resultSet = $this->dbHandler->query($stmt);
         $resultSet->setFetchMode(PDO::FETCH_ASSOC);
         $ignore = $this->dumpSettings['insert-ignore'] ? '  IGNORE' : '';
         foreach ($resultSet as $row) {
             $vals = $this->prepareColumnValues($tableName, $row);
             if ($onlyOnce || !$this->dumpSettings['extended-insert']) {
                 if ($this->dumpSettings['complete-insert']) {
                     $lineSize += $this->compressManager->write(
                         "INSERT$ignore INTO `$tableName` (".
                         implode(", ", $colNames).
                         ") VALUES (".implode(",", $vals).")"
                     );
                 } else {
                     $lineSize += $this->compressManager->write(
                         "INSERT$ignore INTO `$tableName` VALUES (".implode(",", $vals).")"
                     );
                 }
                 $onlyOnce = false;
             } else {
                 $lineSize += $this->compressManager->write(",(".implode(",", $vals).")");
             }
             if (($lineSize > $this->dumpSettings['net_buffer_length']) ||
                 !$this->dumpSettings['extended-insert']) {
                 $onlyOnce = true;
                 $lineSize = $this->compressManager->write(";".PHP_EOL);
             }
         }
         $resultSet->closeCursor();
         if (!$onlyOnce) {
             $this->compressManager->write(";".PHP_EOL);
         }
         $this->endListValues($tableName);
     }
References as, Ifsnop\Mysqldump\Mysqldump\endListValues(), Ifsnop\Mysqldump\Mysqldump\getColumnNames(), Ifsnop\Mysqldump\Mysqldump\getColumnStmt(), Ifsnop\Mysqldump\Mysqldump\prepareColumnValues(), and Ifsnop\Mysqldump\Mysqldump\prepareListValues().
Referenced by Ifsnop\Mysqldump\Mysqldump\exportTables().
matches()
Ifsnop\Mysqldump\Mysqldump::matches ($table, $arr) private
Compare if $table name matches with a definition inside $arr
Parameters
$table string
$arr array with strings or patterns
Returns
bool
Definition at line 557 of file Mysqldump.php.
{
         $match = false;
         foreach ($arr as $pattern) {
             if ('/' != $pattern[0]) {
                 continue;
             }
             if (1 == preg_match($pattern, $table)) {
                 $match = true;
             }
         }
         return in_array($table, $arr) || $match;
     }
References as.
Referenced by Ifsnop\Mysqldump\Mysqldump\exportTables(), and Ifsnop\Mysqldump\Mysqldump\exportViews().
parseDsn()
Ifsnop\Mysqldump\Mysqldump::parseDsn ($dsn) private
Parse DSN string and extract dbname value Several examples of a DSN string mysql:host=localhost;dbname=testdb mysql:host=localhost;port=3307;dbname=testdb mysql:unix_socket=/tmp/mysql.sock;dbname=testdb
Parameters
string $dsn dsn string to parse
Definition at line 235 of file Mysqldump.php.
     {
         if (empty($dsn) || (false === ($pos = strpos($dsn, ":")))) {
             throw new Exception("Empty DSN string");
         }
         $this->dsn = $dsn;
         $this->dbType = strtolower(substr($dsn, 0, $pos)); // always returns a string
         if (empty($this->dbType)) {
             throw new Exception("Missing database type from DSN string");
         }
         $dsn = substr($dsn, $pos + 1);
         foreach (explode(";", $dsn) as $kvp) {
             $kvpArr = explode("=", $kvp);
             $this->dsnArray[strtolower($kvpArr[0])] = $kvpArr[1];
         }
         if (empty($this->dsnArray['host']) &&
             empty($this->dsnArray['unix_socket'])) {
             throw new Exception("Missing host from DSN string");
         }
         $this->host = (!empty($this->dsnArray['host'])) ?
             $this->dsnArray['host'] : $this->dsnArray['unix_socket'];
         if (empty($this->dsnArray['dbname'])) {
             throw new Exception("Missing database name from DSN string");
         }
         $this->dbName = $this->dsnArray['dbname'];
         return true;
     }
References Ifsnop\Mysqldump\Mysqldump\$dsn, and as.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
prepareColumnValues()
Ifsnop\Mysqldump\Mysqldump::prepareColumnValues ($tableName, $row) private
Prepare values for output
Parameters
string $tableName Name of table which contains rows
array $row Associative array of column names and values to be quoted
Returns
array
Definition at line 882 of file Mysqldump.php.
     {
         $ret = [];
         $columnTypes = $this->tableColumnTypes[$tableName];
         foreach ($row as $colName => $colValue) {
             $colValue = $this->hookTransformColumnValue($tableName, $colName, $colValue);
             $ret[] = $this->escape($colValue, $columnTypes[$colName]);
         }
         return $ret;
     }
References as, Ifsnop\Mysqldump\Mysqldump\escape(), and Ifsnop\Mysqldump\Mysqldump\hookTransformColumnValue().
Referenced by Ifsnop\Mysqldump\Mysqldump\listValues().
prepareListValues()
Ifsnop\Mysqldump\Mysqldump::prepareListValues ($tableName)
Table rows extractor, append information prior to dump
Parameters
string $tableName Name of table to export
Returns
null
Definition at line 1025 of file Mysqldump.php.
     {
         if (!$this->dumpSettings['skip-comments']) {
             $this->compressManager->write(
                 "--".PHP_EOL.
                 "-- Dumping data for table `$tableName`".PHP_EOL.
                 "--".PHP_EOL.PHP_EOL
             );
         }
         if ($this->dumpSettings['single-transaction']) {
             $this->dbHandler->exec($this->typeAdapter->setup_transaction());
             $this->dbHandler->exec($this->typeAdapter->start_transaction());
         }
         if ($this->dumpSettings['lock-tables']) {
             $this->typeAdapter->lock_table($tableName);
         }
         if ($this->dumpSettings['add-locks']) {
             $this->compressManager->write(
                 $this->typeAdapter->start_add_lock_table($tableName)
             );
         }
         if ($this->dumpSettings['disable-keys']) {
             $this->compressManager->write(
                 $this->typeAdapter->start_add_disable_keys($tableName)
             );
         }
         // Disable autocommit for faster reload
         if ($this->dumpSettings['no-autocommit']) {
             $this->compressManager->write(
                 $this->typeAdapter->start_disable_autocommit()
             );
         }
         return;
     }
Referenced by Ifsnop\Mysqldump\Mysqldump\listValues().
setTransformColumnValueHook()
Ifsnop\Mysqldump\Mysqldump::setTransformColumnValueHook ($callable)
Set a callable that will will be used to transform column values.
Parameters
callable $callable
Returns
void
Definition at line 926 of file Mysqldump.php.
     {
         $this->transformColumnValueCallable = $callable;
     }
start()
Ifsnop\Mysqldump\Mysqldump::start ($filename = '')
Main call
Parameters
string $filename Name of file to write sql dump to
Returns
null
Definition at line 324 of file Mysqldump.php.
     {
         // Output file can be redefined here
         if (!empty($filename)) {
             $this->fileName = $filename;
         }
         // Connect to database
         $this->connect();
         // Create output file
         $this->compressManager->open($this->fileName);
         // Write some basic info to output file
         $this->compressManager->write($this->getDumpFileHeader());
         // Store server settings and use sanner defaults to dump
         $this->compressManager->write(
             $this->typeAdapter->backup_parameters()
         );
         if ($this->dumpSettings['databases']) {
             $this->compressManager->write(
                 $this->typeAdapter->getDatabaseHeader($this->dbName)
             );
             if ($this->dumpSettings['add-drop-database']) {
                 $this->compressManager->write(
                     $this->typeAdapter->add_drop_database($this->dbName)
                 );
             }
         }
         // Get table, view, trigger, procedures and events
         // structures from database
         $this->getDatabaseStructureTables();
         $this->getDatabaseStructureViews();
         $this->getDatabaseStructureTriggers();
         $this->getDatabaseStructureProcedures();
         $this->getDatabaseStructureEvents();
         if ($this->dumpSettings['databases']) {
             $this->compressManager->write(
                 $this->typeAdapter->databases($this->dbName)
             );
         }
         // If there still are some tables/views in include-tables array,
         // that means that some tables or views weren't found.
         // Give proper error and exit.
         // This check will be removed once include-tables supports regexps
         if (0 < count($this->dumpSettings['include-tables'])) {
             $name = implode(",", $this->dumpSettings['include-tables']);
             throw new Exception("Table (".$name.") not found in database");
         }
         $this->exportTables();
         $this->exportTriggers();
         $this->exportViews();
         $this->exportProcedures();
         $this->exportEvents();
         // Restore saved parameters
         $this->compressManager->write(
             $this->typeAdapter->restore_parameters()
         );
         // Write some stats to output file
         $this->compressManager->write($this->getDumpFileFooter());
         // Close output file
         $this->compressManager->close();
     }
References $filename, $name, Ifsnop\Mysqldump\Mysqldump\connect(), Ifsnop\Mysqldump\Mysqldump\exportEvents(), Ifsnop\Mysqldump\Mysqldump\exportProcedures(), Ifsnop\Mysqldump\Mysqldump\exportTables(), Ifsnop\Mysqldump\Mysqldump\exportTriggers(), Ifsnop\Mysqldump\Mysqldump\exportViews(), Ifsnop\Mysqldump\Mysqldump\getDatabaseStructureEvents(), Ifsnop\Mysqldump\Mysqldump\getDatabaseStructureProcedures(), Ifsnop\Mysqldump\Mysqldump\getDatabaseStructureTables(), Ifsnop\Mysqldump\Mysqldump\getDatabaseStructureTriggers(), Ifsnop\Mysqldump\Mysqldump\getDatabaseStructureViews(), Ifsnop\Mysqldump\Mysqldump\getDumpFileFooter(), and Ifsnop\Mysqldump\Mysqldump\getDumpFileHeader().
Member Data Documentation
$compressManager
Ifsnop\Mysqldump\Mysqldump::$compressManager private
Definition at line 78 of file Mysqldump.php.
$dbHandler
Ifsnop\Mysqldump\Mysqldump::$dbHandler = null private
Definition at line 76 of file Mysqldump.php.
$dbName
Ifsnop\Mysqldump\Mysqldump::$dbName private
Definition at line 89 of file Mysqldump.php.
$dbType
Ifsnop\Mysqldump\Mysqldump::$dbType = "" private
Definition at line 77 of file Mysqldump.php.
$dsn
Ifsnop\Mysqldump\Mysqldump::$dsn
Definition at line 63 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct(), and Ifsnop\Mysqldump\Mysqldump\parseDsn().
$dsnArray
Ifsnop\Mysqldump\Mysqldump::$dsnArray = array() private
Definition at line 99 of file Mysqldump.php.
$dumpSettings
Ifsnop\Mysqldump\Mysqldump::$dumpSettings = array() private
Definition at line 80 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
$events
Ifsnop\Mysqldump\Mysqldump::$events = array() private
Definition at line 75 of file Mysqldump.php.
$fileName
Ifsnop\Mysqldump\Mysqldump::$fileName = 'php://output'
Definition at line 68 of file Mysqldump.php.
$host
Ifsnop\Mysqldump\Mysqldump::$host private
Definition at line 94 of file Mysqldump.php.
$pass
Ifsnop\Mysqldump\Mysqldump::$pass
Definition at line 58 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
$pdoSettings
Ifsnop\Mysqldump\Mysqldump::$pdoSettings = array() private
Definition at line 81 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
$procedures
Ifsnop\Mysqldump\Mysqldump::$procedures = array() private
Definition at line 74 of file Mysqldump.php.
$tableColumnTypes
Ifsnop\Mysqldump\Mysqldump::$tableColumnTypes = array() private
Definition at line 83 of file Mysqldump.php.
$tables
Ifsnop\Mysqldump\Mysqldump::$tables = array() private
Definition at line 71 of file Mysqldump.php.
$transformColumnValueCallable
Ifsnop\Mysqldump\Mysqldump::$transformColumnValueCallable private
Definition at line 84 of file Mysqldump.php.
$triggers
Ifsnop\Mysqldump\Mysqldump::$triggers = array() private
Definition at line 73 of file Mysqldump.php.
$typeAdapter
Ifsnop\Mysqldump\Mysqldump::$typeAdapter private
Definition at line 79 of file Mysqldump.php.
$user
Ifsnop\Mysqldump\Mysqldump::$user
Definition at line 53 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
$version
Ifsnop\Mysqldump\Mysqldump::$version private
Definition at line 82 of file Mysqldump.php.
$views
Ifsnop\Mysqldump\Mysqldump::$views = array() private
Definition at line 72 of file Mysqldump.php.
BZIP2
const Ifsnop\Mysqldump\Mysqldump::BZIP2 = 'Bzip2'
Definition at line 42 of file Mysqldump.php.
GZIP
const Ifsnop\Mysqldump\Mysqldump::GZIP = 'Gzip'
Definition at line 41 of file Mysqldump.php.
MAXLINESIZE
const Ifsnop\Mysqldump\Mysqldump::MAXLINESIZE = 1000000
Definition at line 38 of file Mysqldump.php.
NONE
const Ifsnop\Mysqldump\Mysqldump::NONE = 'None'
Definition at line 43 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
UTF8
const Ifsnop\Mysqldump\Mysqldump::UTF8 = 'utf8'
Definition at line 46 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\Mysqldump\__construct().
UTF8MB4
const Ifsnop\Mysqldump\Mysqldump::UTF8MB4 = 'utf8mb4'
Definition at line 47 of file Mysqldump.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/mysqldump/Mysqldump.php