YaWK: SSilence\ImapClient\IncomingMessage Class Reference
SSilence\ImapClient\IncomingMessage Class Reference
Public Member Functions
__construct ($imapStream, $id, $decode=self::DECODE)
__debugInfo ()
convertToUtf8 ($str, $charset='ISO-8859-1')
debug ()
getID ()
getSection ($section, $options=null)
getSectionStructure ($section)
Public Attributes
$attachments
$debug
$header
$message
$section
$structure
const DECODE = 'decode'
const NOT_DECODE = 'not_decode'
const SECTION_ATTACHMENTS = 1
const SECTION_BODY = 2
Protected Member Functions
decode ()
decodeAttachments ()
decodeBody ()
decodeHeader ()
getAttachments ()
getBody ()
getCountSection ()
getHeader ()
getObjectStructureFromParts ($inObject, $part)
getRecursiveSections ($obj, $before=null)
getSections ($type=null)
getSectionStructureFromIncomingStructure ($section)
imapBodystruct ($section)
imapFetchbody ($section)
imapFetchOverview ()
imapFetchstructure ()
imapHeaderInfo ()
imapMimeHeaderDecode ($string)
init ()
mimeHeaderDecode ($string)
Private Attributes
$_decode
$countAttachment
$id
$imapStream
$uid
Detailed Description
Class for all incoming messages.
This class get message and generates a message structure of the form:
$incomingMessage = new IncomingMessage();
$incomingMessage->header;
$incomingMessage->message;
$incomingMessage->attachments;
$incomingMessage->section;
$incomingMessage->structure;
$incomingMessage->debug;
And marks the message read. TODO: Format class correctly.
Copyright
Copyright (c) Tobias Zeising (http://www.aditu.de)
Author
Sergey144010
Definition at line 28 of file IncomingMessage.php.
Constructor & Destructor Documentation
__construct()
SSilence\ImapClient\IncomingMessage::__construct ($imapStream, $id, $decode = self::DECODE)
Called when the class has a new instance made of it.
Parameters
resource $imapStream
int $id
string $decode
Returns
IncomingMessage
Definition at line 136 of file IncomingMessage.php.
     {
         $this->imapStream = $imapStream;
         if (is_array($id)) {
             $identifier = $id;
             if (isset($identifier['id'])) {
                 $this->id = $identifier['id'];
                 $this->uid = null;
             }
             if (isset($identifier['uid'])) {
                 $this->uid = $identifier['uid'];
                 $this->id = null;
             }
             unset($identifier);
         }
         if (is_int($id)) {
             $this->id = $id;
         }
         if (isset($decode)) {
             $this->_decode = $decode;
         }
         $this->init();
     }
References SSilence\ImapClient\IncomingMessage\$id, SSilence\ImapClient\IncomingMessage\$imapStream, SSilence\ImapClient\IncomingMessage\init(), and uid.
Member Function Documentation
__debugInfo()
SSilence\ImapClient\IncomingMessage::__debugInfo ()
Info about this object.
Returns
array
Definition at line 761 of file IncomingMessage.php.
     {
         return array(
             'header' => $this->header,
             'message' => $this->message,
             'attachments' => $this->attachments,
             'section' => $this->section,
             'structure' => $this->structure,
             'debug' => $this->debug,
         );
     }
References SSilence\ImapClient\IncomingMessage\debug(), and header.
convertToUtf8()
SSilence\ImapClient\IncomingMessage::convertToUtf8 ($str, $charset = 'ISO-8859-1')
Convert to utf8 if necessary.
Parameters
string $str utf8 encoded string
Returns
string
Definition at line 600 of file IncomingMessage.php.
     {
         if ($charset == 'default') {
             $charset = 'utf-8';
         }
         $encoding = mb_detect_encoding($str, mb_detect_order(), false);
         if($encoding == 'UTF-8'){
             $str = mb_convert_encoding($str, 'UTF-8', 'UTF-8');
         }
         $str = iconv(mb_detect_encoding($str, mb_detect_order(), false), "UTF-8//IGNORE", $str);
 //        $str = iconv($charset, 'UTF-8//IGNORE', $str);
         return $str;
     }
Referenced by SSilence\ImapClient\IncomingMessage\decodeBody(), and SSilence\ImapClient\IncomingMessage\mimeHeaderDecode().
debug()
SSilence\ImapClient\IncomingMessage::debug ()
Returns current object.
Set $this->debug
Returns
void
Definition at line 209 of file IncomingMessage.php.
     {
         $this->debug = $this;
     }
Referenced by SSilence\ImapClient\IncomingMessage\__debugInfo().
decode()
SSilence\ImapClient\IncomingMessage::decode () protected
Decode incoming message.
Returns
void
Definition at line 659 of file IncomingMessage.php.
     {
         $this->decodeHeader();
         $this->decodeBody();
         $this->decodeAttachments();
     }
References SSilence\ImapClient\IncomingMessage\decodeAttachments(), SSilence\ImapClient\IncomingMessage\decodeBody(), and SSilence\ImapClient\IncomingMessage\decodeHeader().
Referenced by SSilence\ImapClient\IncomingMessage\init().
decodeAttachments()
SSilence\ImapClient\IncomingMessage::decodeAttachments () protected
Decode attachments.
Returns
void
Definition at line 695 of file IncomingMessage.php.
     {
         foreach ($this->attachments as $key => $attachment) {
             if(
                 is_object($attachment) &&
                 property_exists($attachment, 'info') &&
                 is_object($attachment->info) &&
                 property_exists($attachment->info, 'structure') &&
                 is_object($attachment->info->structure) &&
                 property_exists($attachment->info->structure, 'encoding')
             ) {
                 /*
                  * Decode body
                  */
                 switch ($attachment->info->structure->encoding) {
                     case 3:
                         $this->attachments[$key]->body = imap_base64($attachment->body);
                         break;
                     case 4:
                         $this->attachments[$key]->body = quoted_printable_decode($attachment->body);
                         break;
                 }
                 /*
                  * Decode name
                  */
                 $this->attachments[$key]->name = $this->mimeHeaderDecode($attachment->name);
             }
         }
     }
References as, and SSilence\ImapClient\IncomingMessage\mimeHeaderDecode().
Referenced by SSilence\ImapClient\IncomingMessage\decode().
decodeBody()
SSilence\ImapClient\IncomingMessage::decodeBody () protected
Decode body.
Returns
void
Definition at line 730 of file IncomingMessage.php.
     {
         if(is_object($this->message)){
             if(property_exists($this->message, 'types')) {
                 foreach ($this->message->types as $typeMessage) {
                     if(is_object($this->message->$typeMessage)){
                         switch ($this->message->$typeMessage->structure->encoding) {
                             case 3:
                                 $this->message->$typeMessage->body = imap_base64($this->message->$typeMessage->body);
                                 break;
                             case 4:
                                 $this->message->$typeMessage->body = imap_qprint($this->message->$typeMessage->body);
                                 break;
                         }
                     }
                     if(is_object($this->message->$typeMessage)){
                         if ($this->message->$typeMessage->charset) {
                             $this->message->$typeMessage->body = $this->convertToUtf8($this->message->$typeMessage->body, $this->message->$typeMessage->charset);
                         }
                     }
                 }
             }
         }
     }
References as, and SSilence\ImapClient\IncomingMessage\convertToUtf8().
Referenced by SSilence\ImapClient\IncomingMessage\decode().
decodeHeader()
SSilence\ImapClient\IncomingMessage::decodeHeader () protected
Decode header.
Returns
void
Definition at line 671 of file IncomingMessage.php.
     {
         if (isset($this->header->subject)) {
             $this->header->subject = $this->mimeHeaderDecode($this->header->subject);
         }
         if (isset($this->header->details->subject)) {
             $this->header->details->subject = $this->mimeHeaderDecode($this->header->details->subject);
         }
         if (isset($this->header->details->Subject)) {
             $this->header->details->Subject = $this->mimeHeaderDecode($this->header->details->Subject);
         }
         if (isset($this->header->from)) {
             $this->header->from = $this->mimeHeaderDecode($this->header->from);
         }
         if (isset($this->header->to)) {
             $this->header->to = $this->mimeHeaderDecode($this->header->to);
         }
     }
References header, and SSilence\ImapClient\IncomingMessage\mimeHeaderDecode().
Referenced by SSilence\ImapClient\IncomingMessage\decode().
getAttachments()
SSilence\ImapClient\IncomingMessage::getAttachments () protected
Get attachments in the current message.
Set $this->attachments->name $this->attachments->body $this->attachments->info
Returns
array
Definition at line 330 of file IncomingMessage.php.
     {
         $attachments = array();
         foreach ($this->getSections(self::SECTION_ATTACHMENTS) as $section) {
             $obj = $this->getSection($section);
             $attachment = new IncomingMessageAttachment($obj);
             $objNew = new \stdClass();
             $objNew->name = $attachment->name;
             $objNew->body = $attachment->body;
             $objNew->info = $obj;
             $attachments[] = $objNew;
         }
         $this->attachments = $attachments;
     }
References SSilence\ImapClient\IncomingMessage\$attachments, SSilence\ImapClient\IncomingMessage\$section, as, SSilence\ImapClient\IncomingMessage\getSection(), and SSilence\ImapClient\IncomingMessage\getSections().
Referenced by SSilence\ImapClient\IncomingMessage\init().
getBody()
SSilence\ImapClient\IncomingMessage::getBody () protected
Get body current message.
Set $this->message->$subtype $this->message->$subtype->charset $this->message->text $this->message->info[] $this->message->types[]
Returns
object
Definition at line 357 of file IncomingMessage.php.
     {
         $objNew = new \stdClass();
         $i = 1;
         $subType = new SubtypeBody();
         foreach ($this->getSections(self::SECTION_BODY) as $section) {
             $obj = $this->getSection($section, array('class' => $subType));
             if(!is_object($obj) || !$obj->__get('structure')) {
                 continue;
             }
             $subtype = strtolower($obj->__get('structure')->subtype);
             if(!empty($subtype)) {
                 if (!isset($objNew->$subtype)) {
                     $objNew->$subtype = $obj;
                 } else {
                     $subtype = $subtype.'_'.$i;
                     $objNew->$subtype = $obj;
                     $i++;
                 }
                 $objNew->info[] = $obj;
                 $objNew->types[] = $subtype;
                 /*
                 * Set charset
                 */
                 foreach ($objNew->$subtype->__get('structure')->parameters as $parameter) {
                     $attribute = strtolower($parameter->attribute);
                     if ($attribute === 'charset') {
                         $value = strtolower($parameter->value);
                         /*
                         * Here must be array, but
                         */
                         //$objNew->$subtype->charset[] = $value;
                         $objNew->$subtype->charset = $value;
                     }
                 }
             }
         }
         if (isset($objNew->plain)) {
             switch ($objNew->plain->structure->encoding) {
                 case 3:
                     $objNew->text = imap_base64(mb_convert_encoding( $objNew->plain, "utf-8", $objNew->plain->charset ));
                     break;
                 default:
                     $objNew->text = quoted_printable_decode(mb_convert_encoding( $objNew->plain, "utf-8", 'ISO-8859-1'));
                     break;
             }
             $objNew->types[] = 'text';
         }
         else
             {
                 $objNew->text = null;
             }
         $this->message = $objNew;
     }
References $i, SSilence\ImapClient\IncomingMessage\$section, $value, as, SSilence\ImapClient\IncomingMessage\getSection(), and SSilence\ImapClient\IncomingMessage\getSections().
Referenced by SSilence\ImapClient\IncomingMessage\init().
getCountSection()
SSilence\ImapClient\IncomingMessage::getCountSection () protected
Get count section.
We take $this->section and make a simple array from an array of arrays. If getRecursiveSections($this->structure) set $this->section to NULL, then we think that there is only one section in the letter. We install $this->section[0] = [0], and then we will take this into account in subsequent processing. Namely here getSection() and $this->getSectionStructure() or getSectionStructureFromIncomingStructure(). Because if the message id is correct and the structure is returned, then there is exactly one section in the message.
Returns
array sections
Definition at line 229 of file IncomingMessage.php.
     {
         $this->getRecursiveSections($this->structure);
         $sections = array();
         if (!isset($this->section)) {
             $this->section[0] = array(0);
         }
         foreach ($this->section as $array) {
             foreach ($array as $section) {
                 $sections[] = $section;
             }
         }
         $sections = array_unique($sections);
         sort($sections);
         $this->section = $sections;
         return $this->section;
     }
References SSilence\ImapClient\IncomingMessage\$section, as, and SSilence\ImapClient\IncomingMessage\getRecursiveSections().
Referenced by SSilence\ImapClient\IncomingMessage\init().
getHeader()
SSilence\ImapClient\IncomingMessage::getHeader () protected
Get headers in the current message.
Set
$this->header
$this->header->details
Returns
void
Definition at line 195 of file IncomingMessage.php.
     {
         $header = $this->imapFetchOverview();
         $this->header = $header[0];
         $this->header->details = $this->imapHeaderInfo();
     }
References SSilence\ImapClient\IncomingMessage\$header, header, SSilence\ImapClient\IncomingMessage\imapFetchOverview(), and SSilence\ImapClient\IncomingMessage\imapHeaderInfo().
Referenced by SSilence\ImapClient\IncomingMessage\init().
getID()
SSilence\ImapClient\IncomingMessage::getID ()
Get the id property of the message
Returns
int
Definition at line 778 of file IncomingMessage.php.
     {
         return $this->id;
     }
References SSilence\ImapClient\IncomingMessage\$id.
getObjectStructureFromParts()
SSilence\ImapClient\IncomingMessage::getObjectStructureFromParts ($inObject, $part) protected
Get object structure from parts.
Parameters
object $inObject
int $part
Returns
object
Definition at line 507 of file IncomingMessage.php.
     {
         return $inObject->parts[$part];
     }
Referenced by SSilence\ImapClient\IncomingMessage\getSectionStructureFromIncomingStructure().
getRecursiveSections()
SSilence\ImapClient\IncomingMessage::getRecursiveSections ($obj, $before = null) protected
Bypasses the recursive parts current message.
Counts sections based on $obj->parts. And sets $this->section as an array of arrays or null. Null if $obj->parts is not.
Parameters
object $obj
string $before
Returns
void
Definition at line 260 of file IncomingMessage.php.
     {
         if (!isset($obj->parts)) {
             return;
         }
         $countParts = count($obj->parts);
         $out = array();
         $beforeSave = $before;
         foreach ($obj->parts as $key => $subObj) {
             if (!isset($beforeSave)) {
                 $before = ($key + 1);
             } else {
                 $before = $beforeSave.'.'.($key + 1);
             }
             $this->getRecursiveSections($subObj, $before);
             $out[] = (string) $before;
         }
         $this->section[] = $out;
     }
References as.
Referenced by SSilence\ImapClient\IncomingMessage\getCountSection().
getSection()
SSilence\ImapClient\IncomingMessage::getSection ($section, $options = null)
Get a section message.
Return object with 2 properties: $obj->structure $obj->body
Parameters
string $section
array | null $options have one option $options['class']. It create object, which must be instance \SSilence\ImapClient\Section.
Exceptions
ImapClientException
Returns
\SSilence\ImapClient\Section object
Definition at line 428 of file IncomingMessage.php.
     {
         if (isset($options['class'])) {
             $sectionObj = new $options['class']();
             if ($sectionObj instanceof Section) {
             } else {
                 throw new ImapClientException('Incoming class not instance \SSilence\ImapClient\Section');
             }
         } else {
             $sectionObj = new Section();
         }
         if ($section === 0) {
             /*
             If the message id is correct and the structure is returned,
             then there is exactly one section in the message.
             */
             $sectionObj->structure = $this->imapBodystruct(1);
             $sectionObj->body = $this->imapFetchbody(1);
         } else {
             $sectionObj->structure = $this->imapBodystruct($section);
             $sectionObj->body = $this->imapFetchbody($section);
         }
         return $sectionObj;
     }
References $options, SSilence\ImapClient\IncomingMessage\$section, SSilence\ImapClient\IncomingMessage\imapBodystruct(), and SSilence\ImapClient\IncomingMessage\imapFetchbody().
Referenced by SSilence\ImapClient\IncomingMessage\getAttachments(), and SSilence\ImapClient\IncomingMessage\getBody().
getSections()
SSilence\ImapClient\IncomingMessage::getSections ($type = null) protected
Gets all sections, or if parameter is specified sections by type.
Parameters
string $type
Exceptions
ImapClientException
Returns
array
Definition at line 289 of file IncomingMessage.php.
     {
         if (!$type) {
             return $this->section;
         }
         $types = null;
         switch ($type) {
             case self::SECTION_ATTACHMENTS:
                 $types = TypeAttachments::get();
                 break;
             case self::SECTION_BODY:
                 $types = TypeBody::get();
                 break;
             default:
                 throw new ImapClientException('Section type not recognised/supported');
                 break;
         }
         $sections = array();
         foreach ($this->section as $section) {
             $obj = $this->getSectionStructure($section);
             if (!isset($obj->subtype)) {
                 continue;
             }
             if (in_array($obj->subtype, $types, false)) {
                 $sections[] = $section;
             }
         }
         return $sections;
     }
References SSilence\ImapClient\IncomingMessage\$section, $type, as, SSilence\ImapClient\TypeAttachments\get(), SSilence\ImapClient\TypeBody\get(), SSilence\ImapClient\IncomingMessage\getSectionStructure(), SSilence\ImapClient\IncomingMessage\SECTION_ATTACHMENTS, and SSilence\ImapClient\IncomingMessage\SECTION_BODY.
Referenced by SSilence\ImapClient\IncomingMessage\getAttachments(), and SSilence\ImapClient\IncomingMessage\getBody().
getSectionStructure()
SSilence\ImapClient\IncomingMessage::getSectionStructure ($section)
Alias for getSectionStructureFromIncomingStructure();.
Parameters
string $section
Returns
object|null
Definition at line 461 of file IncomingMessage.php.
     {
         return $this->getSectionStructureFromIncomingStructure($section);
     }
References SSilence\ImapClient\IncomingMessage\$section, and SSilence\ImapClient\IncomingMessage\getSectionStructureFromIncomingStructure().
Referenced by SSilence\ImapClient\IncomingMessage\getSections().
getSectionStructureFromIncomingStructure()
SSilence\ImapClient\IncomingMessage::getSectionStructureFromIncomingStructure ($section) protected
Get section structure from incoming structure.
Parameters
string $section
Returns
object|null
Definition at line 473 of file IncomingMessage.php.
     {
         $pos = strpos($section, '.');
         if ($pos === false) {
             $section = (int) $section;
             if ($section === 0) {
                 return $this->structure;
             }
             return $this->structure->parts[($section - 1)];
         }
         $sections = explode('.', $section);
         $count = count($sections);
         $outObject = null;
         foreach ($sections as $section) {
             $section = (int) $section;
             if (!isset($outObject)) {
                 $outObject = $this->getObjectStructureFromParts($this->structure, ($section - 1));
             } else {
                 $outObject = $this->getObjectStructureFromParts($outObject, ($section - 1));
             }
         }
         return $outObject;
     }
References SSilence\ImapClient\IncomingMessage\$section, SSilence\ImapClient\IncomingMessage\$structure, as, and SSilence\ImapClient\IncomingMessage\getObjectStructureFromParts().
Referenced by SSilence\ImapClient\IncomingMessage\getSectionStructure().
imapBodystruct()
SSilence\ImapClient\IncomingMessage::imapBodystruct ($section) protected
Structure specific section.
Parameters
string $section
Returns
object
Definition at line 545 of file IncomingMessage.php.
     {
         return imap_bodystruct($this->imapStream, $this->id, $section);
     }
References SSilence\ImapClient\IncomingMessage\$section.
Referenced by SSilence\ImapClient\IncomingMessage\getSection().
imapFetchbody()
SSilence\ImapClient\IncomingMessage::imapFetchbody ($section) protected
Get a specific section.
Parameters
string $section
Returns
string
Definition at line 519 of file IncomingMessage.php.
     {
         /*
      * Update note: We must add FT_PEEK to perserve the unread status of the email.
      * Documentation of this can see seen here: http://php.net/manual/en/function.imap-fetchbody.php under options
      */
         return imap_fetchbody($this->imapStream, $this->id, $section, FT_PEEK);
     }
References SSilence\ImapClient\IncomingMessage\$section.
Referenced by SSilence\ImapClient\IncomingMessage\getSection().
imapFetchOverview()
SSilence\ImapClient\IncomingMessage::imapFetchOverview () protected
Fetch a quick "Overview" on a message.
See also
http://php.net/manual/ru/function.imap-fetch-overview.php
Exceptions
ImapClientException
Returns
object
Definition at line 559 of file IncomingMessage.php.
     {
         if (isset($this->id) && isset($this->uid)) {
             throw new ImapClientException('What to use id or uid?');
         }
         $sequence = null;
         $options = null;
         if (isset($this->id) && !isset($this->uid)) {
             $sequence = $this->id;
             $options = null;
         }
         if (!isset($this->id) && isset($this->uid)) {
             $sequence = $this->uid;
             $options = FT_UID;
         }
         return imap_fetch_overview($this->imapStream, $sequence, $options);
     }
References SSilence\ImapClient\IncomingMessage\$id, $options, SSilence\ImapClient\IncomingMessage\$uid, and uid.
Referenced by SSilence\ImapClient\IncomingMessage\getHeader().
imapFetchstructure()
SSilence\ImapClient\IncomingMessage::imapFetchstructure () protected
Structure all messages.
Returns
object
Definition at line 533 of file IncomingMessage.php.
     {
         return imap_fetchstructure($this->imapStream, $this->id);
     }
Referenced by SSilence\ImapClient\IncomingMessage\init().
imapHeaderInfo()
SSilence\ImapClient\IncomingMessage::imapHeaderInfo () protected
Imap Header Info.
Wrapper for http://php.net/manual/ru/function.imap-headerinfo.php
See also
http://php.net/manual/ru/function.imap-headerinfo.php
http://php.net/manual/en/function.imap-headerinfo.php#98809
Returns
object
Definition at line 588 of file IncomingMessage.php.
     {
      return imap_rfc822_parse_headers(imap_fetchheader($this->imapStream, $this->id));
     }
Referenced by SSilence\ImapClient\IncomingMessage\getHeader().
imapMimeHeaderDecode()
SSilence\ImapClient\IncomingMessage::imapMimeHeaderDecode ($string) protected
Wrapper for imap_mime_header_decode() http://php.net/manual/ru/function.imap-mime-header-decode.php.
See also
http://php.net/manual/ru/function.imap-mime-header-decode.php
Parameters
string $string
Returns
array
Definition at line 628 of file IncomingMessage.php.
     {
         return imap_mime_header_decode($string);
     }
Referenced by SSilence\ImapClient\IncomingMessage\mimeHeaderDecode().
init()
SSilence\ImapClient\IncomingMessage::init () protected
Main process.
Returns
void
Definition at line 167 of file IncomingMessage.php.
     {
         $structure = $this->imapFetchstructure();
         $this->structure = $structure;
         if (isset($structure->parts)) {
             $countSection = count($structure->parts);
             $this->countAttachment = $countSection - 1;
         }
         $this->getCountSection();
         $this->getHeader();
         $this->getAttachments();
         $this->getBody();
         if ($this->_decode === self::DECODE) {
             $this->decode();
         }
     }
References SSilence\ImapClient\IncomingMessage\$structure, SSilence\ImapClient\IncomingMessage\decode(), SSilence\ImapClient\IncomingMessage\getAttachments(), SSilence\ImapClient\IncomingMessage\getBody(), SSilence\ImapClient\IncomingMessage\getCountSection(), SSilence\ImapClient\IncomingMessage\getHeader(), and SSilence\ImapClient\IncomingMessage\imapFetchstructure().
Referenced by SSilence\ImapClient\IncomingMessage\__construct().
mimeHeaderDecode()
SSilence\ImapClient\IncomingMessage::mimeHeaderDecode ($string) protected
Decodes and glues the title bar http://php.net/manual/ru/function.imap-mime-header-decode.php.
See also
http://php.net/manual/ru/function.imap-mime-header-decode.php
Parameters
string $string
Returns
string
Definition at line 643 of file IncomingMessage.php.
     {
         $cache = null;
         $array = $this->imapMimeHeaderDecode($string);
         foreach ($array as $object) {
             $cache .= $this->convertToUtf8($object->text, $object->charset);
         }
         return $cache;
     }
References as, SSilence\ImapClient\IncomingMessage\convertToUtf8(), and SSilence\ImapClient\IncomingMessage\imapMimeHeaderDecode().
Referenced by SSilence\ImapClient\IncomingMessage\decodeAttachments(), and SSilence\ImapClient\IncomingMessage\decodeHeader().
Member Data Documentation
$_decode
SSilence\ImapClient\IncomingMessage::$_decode private
Definition at line 125 of file IncomingMessage.php.
$attachments
SSilence\ImapClient\IncomingMessage::$attachments
Definition at line 69 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getAttachments().
$countAttachment
SSilence\ImapClient\IncomingMessage::$countAttachment private
Definition at line 118 of file IncomingMessage.php.
$debug
SSilence\ImapClient\IncomingMessage::$debug
Definition at line 90 of file IncomingMessage.php.
$header
SSilence\ImapClient\IncomingMessage::$header
Definition at line 55 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getHeader().
$id
SSilence\ImapClient\IncomingMessage::$id private
Definition at line 104 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\__construct(), SSilence\ImapClient\IncomingMessage\getID(), and SSilence\ImapClient\IncomingMessage\imapFetchOverview().
$imapStream
SSilence\ImapClient\IncomingMessage::$imapStream private
Definition at line 97 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\__construct().
$message
SSilence\ImapClient\IncomingMessage::$message
Definition at line 62 of file IncomingMessage.php.
$section
SSilence\ImapClient\IncomingMessage::$section
Definition at line 76 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getAttachments(), SSilence\ImapClient\IncomingMessage\getBody(), SSilence\ImapClient\IncomingMessage\getCountSection(), SSilence\ImapClient\IncomingMessage\getSection(), SSilence\ImapClient\IncomingMessage\getSections(), SSilence\ImapClient\IncomingMessage\getSectionStructure(), SSilence\ImapClient\IncomingMessage\getSectionStructureFromIncomingStructure(), SSilence\ImapClient\IncomingMessage\imapBodystruct(), and SSilence\ImapClient\IncomingMessage\imapFetchbody().
$structure
SSilence\ImapClient\IncomingMessage::$structure
Definition at line 83 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getSectionStructureFromIncomingStructure(), and SSilence\ImapClient\IncomingMessage\init().
$uid
SSilence\ImapClient\IncomingMessage::$uid private
Definition at line 111 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\imapFetchOverview().
DECODE
const SSilence\ImapClient\IncomingMessage::DECODE = 'decode'
Use decode incoming message.
Definition at line 48 of file IncomingMessage.php.
NOT_DECODE
const SSilence\ImapClient\IncomingMessage::NOT_DECODE = 'not_decode'
Do not use decode incoming message.
Definition at line 43 of file IncomingMessage.php.
SECTION_ATTACHMENTS
const SSilence\ImapClient\IncomingMessage::SECTION_ATTACHMENTS = 1
Used to handle sections of the e-mail easier.
Definition at line 33 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getSections().
SECTION_BODY
const SSilence\ImapClient\IncomingMessage::SECTION_BODY = 2
Used to handle sections of the e-mail easier.
Definition at line 38 of file IncomingMessage.php.
Referenced by SSilence\ImapClient\IncomingMessage\getSections().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/imapClient/IncomingMessage.php