YaWK: YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud Class Reference
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud Class Reference
Embed a SoundCloud audio player.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embedPlayer ()
Embed SoundCloud Player.
init ()
Initialize: Set properties and embed SoundCloud player.
printObject ()
Print all object data.
setProperties ()
Prepare SoundCloud Player Properties.
Public Attributes
$errorMsg = ''
$headline = ''
$soundcloudAutoplay = false
$soundcloudHeight = '300'
$soundcloudHideRelated = false
$soundcloudShowComments = false
$soundcloudShowReposts = false
$soundcloudShowTeaser = false
$soundcloudShowUser = false
$soundcloudSubtext = ''
$soundcloudTitle = ''
$soundcloudUrl = ''
$soundcloudVisual = false
$soundcloudWidth = '100%'
$widget = ''
Detailed Description
Embed a SoundCloud audio player.
Embed any soundcloud track or playlist.
If you want to embed a SoundCloud player on your website, this is the widget to do it. All you need is any public SoundCloud URL. The Widget comes with a few settings like: autoplay on or off, show comments, related music, and much more is customizable within the backend.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 16 of file soundcloud.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 54 of file soundcloud.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embedPlayer()
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::embedPlayer ()
Embed SoundCloud Player.
Load SoundCloud Iframe
Definition at line 132 of file soundcloud.php.
         {
             // output headline
             echo $this->headline;
             // throw error (if one occurs)
             echo $this->errorMsg;
             // embed SoundCloud player
             echo "<iframe
                     width=\"$this->soundcloudWidth\"
                     height=\"$this->soundcloudHeight\"
                     scrolling=\"no\"
                     frameborder=\"no\"
                     allow=\"autoplay\"
                     src=\"https://w.soundcloud.com/player/?url=https%3A//$this->soundcloudUrl&color=%23ff5500&auto_play=$this->soundcloudAutoplay&hide_related=$this->soundcloudHideRelated&show_comments=$this->soundcloudShowComments&show_user=$this->soundcloudShowUser&show_reposts=$this->soundcloudShowReposts&show_teaser=$this->soundcloudShowTeaser&visual=$this->soundcloudVisual\">
                   </iframe>";
References YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\$errorMsg, and YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\$headline.
Referenced by YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\init().
init()
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::init ()
Initialize: Set properties and embed SoundCloud player.
use this method to run the clock
Definition at line 81 of file soundcloud.php.
         {
             // set object properties
             $this->setProperties();
             // $this->printObject();
             // embed the SoundCloud Player
             $this->embedPlayer();
References YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\embedPlayer(), and YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\setProperties().
printObject()
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 68 of file soundcloud.php.
         {
             // output all obj data
             echo "<pre>";
             print_r($this);
             echo "</pre>";
             exit;
References exit.
setProperties()
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::setProperties ()
Prepare SoundCloud Player Properties.
Set Player Properties and HTML Markup Code
Definition at line 94 of file soundcloud.php.
         {
             // check if soundcloud URL is set, not empty and a valid type (string)
             if (isset($this->soundcloudUrl) && (!empty($this->soundcloudUrl)
             && (is_string($this->soundcloudUrl))))
             {   // select everything AFTER the soundcloud.com/ part
                 $this->soundcloudUrl = strstr($this->soundcloudUrl, 'soundcloud.com/');
             }
             else
                 {   // throw error msg
                     $this->errorMsg = "Here should be a SoundCloud music player, but no SoundCloud URL was set.";
                 }
             // if a heading is set and not empty
             if (isset($this->soundcloudTitle) && (!empty($this->soundcloudTitle)))
             {
                 // if subtext is set, add <small> subtext to string
                 if (isset($this->soundcloudSubtext) && (!empty($this->soundcloudSubtext)))
                 {   // build a headline with heading and subtext
                     $this->soundcloudSubtext = "<small>$this->soundcloudSubtext</small>";
                     $this->headline = "<h1>$this->soundcloudTitle&nbsp;" . "$this->soundcloudSubtext</h1>";
                 }
                 else
                 {   // build just a headline - without subtext
                     $this->headline = "<h1>$this->soundcloudTitle</h1>";    // draw just the heading
                 }
             }
             else
             {   // leave empty if it's not set
                 $this->headline = '';
             }
References errorMsg.
Referenced by YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\init().
Member Data Documentation
$errorMsg
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$errorMsg = ''
Parameters
string Store an error msg, if one occurs
Definition at line 47 of file soundcloud.php.
Referenced by YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\embedPlayer().
$headline
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$headline = ''
Parameters
string Headline HTML Markup
Definition at line 45 of file soundcloud.php.
Referenced by YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\embedPlayer().
$soundcloudAutoplay
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudAutoplay = false
Parameters
bool true|false - Autoplay enabled?
Definition at line 27 of file soundcloud.php.
$soundcloudHeight
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudHeight = '300'
Parameters
string Player Height (300)
Definition at line 43 of file soundcloud.php.
$soundcloudHideRelated
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudHideRelated = false
Parameters
bool true|false - Hide related?
Definition at line 29 of file soundcloud.php.
$soundcloudShowComments
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudShowComments = false
Parameters
bool true|false - Show Comments?
Definition at line 31 of file soundcloud.php.
$soundcloudShowReposts
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudShowReposts = false
Parameters
bool true|false - Show Reposts?
Definition at line 35 of file soundcloud.php.
$soundcloudShowTeaser
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudShowTeaser = false
Parameters
bool true|false - Show Teaser?
Definition at line 37 of file soundcloud.php.
$soundcloudShowUser
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudShowUser = false
Parameters
bool true|false - Show User?
Definition at line 33 of file soundcloud.php.
$soundcloudSubtext
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudSubtext = ''
Parameters
string Subtext gets drawn as small tag beside the title
Definition at line 25 of file soundcloud.php.
$soundcloudTitle
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudTitle = ''
Parameters
string Title above the player
Definition at line 23 of file soundcloud.php.
$soundcloudUrl
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudUrl = ''
Parameters
string The URL of your soundcloud track or playlist
Definition at line 21 of file soundcloud.php.
$soundcloudVisual
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudVisual = false
Parameters
bool true|false - Visual?
Definition at line 39 of file soundcloud.php.
$soundcloudWidth
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$soundcloudWidth = '100%'
Parameters
string Player Width (100%)
Definition at line 41 of file soundcloud.php.
$widget
YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud::$widget = ''
Parameters
object global widget object data
Definition at line 19 of file soundcloud.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/soundcloud/classes/soundcloud.php