YaWK: YAWK\language Class Reference
YAWK\language Class Reference
The language class - support multilingual backend.
Public Member Functions
getClientLanguage ()
get and return client language
getCurrentLanguage ($db, $referer)
returns the currently set language
getPathToLanguageFile ()
Returns the path to the language file.
getSupportedLanguages ()
sets object supportedLanguages as array including all supported languages
init ($db, $referer)
initialize and return current language
isSupported (string $currentLanguage)
Check if a language is supported. This functions expect currentLanguage string in format "en-EN" or "en".
setDefault (string $defaultLanguage)
Set a language as default and load (set) it current language.
setLanguage (string $currentLanguage)
set client language and parse corresponding ini file to an array called $lang
Static Public Member Functions
static drawLanguageSelectOptions ()
return options (inner html) for a language select field
static getCurrentLanguageStatic ()
returns the currently set backend language, but is static callable
static inject (array $lang, string $pathToFile)
allow plugins to inject language tags to $lang array
Public Attributes
$currentFrontendLanguage
$currentLanguage
$currentLanguageGlobal
$defaultLanguage
$detectedLanguage
$detectedLanguageGlobal
$httpAcceptedLanguage
$lang
$pathToFile
$supportedLanguages
$supportedLanguagesGlobal
Detailed Description
The language class - support multilingual backend.
Get and set the backend language.
Language Support for Backend
The language files are located in
admin/language/lang-en-EN.ini
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2017 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 16 of file language.php.
Member Function Documentation
drawLanguageSelectOptions()
static YAWK\language::drawLanguageSelectOptions () static
return options (inner html) for a language select field
Returns
string returns a string with all possible language options
Definition at line 478 of file language.php.
                                                    : string
         {
             return '<option value=""></option>
                       <option value="af">Afrikaans</option>
                       <option value="sq">Albanian - shqip</option>
                       <option value="am">Amharic - አማርኛ</option>
                       <option value="ar">Arabic - العربية</option>
                       <option value="an">Aragonese - aragonés</option>
                       <option value="hy">Armenian - հայերեն</option>
                       <option value="ast">Asturian - asturianu</option>
                       <option value="az">Azerbaijani - azərbaycan dili</option>
                       <option value="eu">Basque - euskara</option>
                       <option value="be">Belarusian - беларуская</option>
                       <option value="bn">Bengali - বাংলা</option>
                       <option value="bs">Bosnian - bosanski</option>
                       <option value="br">Breton - brezhoneg</option>
                       <option value="bg">Bulgarian - български</option>
                       <option value="ca">Catalan - català</option>
                       <option value="ckb">Central Kurdish - کوردی (دەستنوسی عەرەبی)</option>
                       <option value="zh">Chinese - 中文</option>
                       <option value="zh-HK">Chinese (Hong Kong) - 中文（香港）</option>
                       <option value="zh-CN">Chinese (Simplified) - 中文（简体）</option>
                       <option value="zh-TW">Chinese (Traditional) - 中文（繁體）</option>
                       <option value="co">Corsican</option>
                       <option value="hr">Croatian - hrvatski</option>
                       <option value="cs">Czech - čeština</option>
                       <option value="da">Danish - dansk</option>
                       <option value="nl">Dutch - Nederlands</option>
                       <option value="en">English</option>
                       <option value="en-AU">English (Australia)</option>
                       <option value="en-CA">English (Canada)</option>
                       <option value="en-IN">English (India)</option>
                       <option value="en-NZ">English (New Zealand)</option>
                       <option value="en-ZA">English (South Africa)</option>
                       <option value="en-GB">English (United Kingdom)</option>
                       <option value="en-US">English (United States)</option>
                       <option value="eo">Esperanto - esperanto</option>
                       <option value="et">Estonian - eesti</option>
                       <option value="fo">Faroese - føroyskt</option>
                       <option value="fil">Filipino</option>
                       <option value="fi">Finnish - suomi</option>
                       <option value="fr">French - français</option>
                       <option value="fr-CA">French (Canada) - français (Canada)</option>
                       <option value="fr-FR">French (France) - français (France)</option>
                       <option value="fr-CH">French (Switzerland) - français (Suisse)</option>
                       <option value="gl">Galician - galego</option>
                       <option value="ka">Georgian - ქართული</option>
                       <option value="de">German - Deutsch</option>
                       <option value="de-AT">German (Austria) - Deutsch (Österreich)</option>
                       <option value="de-DE">German (Germany) - Deutsch (Deutschland)</option>
                       <option value="de-LI">German (Liechtenstein) - Deutsch (Liechtenstein)</option>
                       <option value="de-CH">German (Switzerland) - Deutsch (Schweiz)</option>
                       <option value="el">Greek - Ελληνικά</option>
                       <option value="gn">Guarani</option>
                       <option value="gu">Gujarati - ગુજરાતી</option>
                       <option value="ha">Hausa</option>
                       <option value="haw">Hawaiian - ʻŌlelo Hawaiʻi</option>
                       <option value="he">Hebrew - עברית</option>
                       <option value="hi">Hindi - हिन्दी</option>
                       <option value="hu">Hungarian - magyar</option>
                       <option value="is">Icelandic - íslenska</option>
                       <option value="id">Indonesian - Indonesia</option>
                       <option value="ia">Interlingua</option>
                       <option value="ga">Irish - Gaeilge</option>
                       <option value="it">Italian - italiano</option>
                       <option value="it-IT">Italian (Italy) - italiano (Italia)</option>
                       <option value="it-CH">Italian (Switzerland) - italiano (Svizzera)</option>
                       <option value="ja">Japanese - 日本語</option>
                       <option value="kn">Kannada - ಕನ್ನಡ</option>
                       <option value="kk">Kazakh - қазақ тілі</option>
                       <option value="km">Khmer - ខ្មែរ</option>
                       <option value="ko">Korean - 한국어</option>
                       <option value="ku">Kurdish - Kurdî</option>
                       <option value="ky">Kyrgyz - кыргызча</option>
                       <option value="lo">Lao - ລາວ</option>
                       <option value="la">Latin</option>
                       <option value="lv">Latvian - latviešu</option>
                       <option value="ln">Lingala - lingála</option>
                       <option value="lt">Lithuanian - lietuvių</option>
                       <option value="mk">Macedonian - македонски</option>
                       <option value="ms">Malay - Bahasa Melayu</option>
                       <option value="ml">Malayalam - മലയാളം</option>
                       <option value="mt">Maltese - Malti</option>
                       <option value="mr">Marathi - मराठी</option>
                       <option value="mn">Mongolian - монгол</option>
                       <option value="ne">Nepali - नेपाली</option>
                       <option value="no">Norwegian - norsk</option>
                       <option value="nb">Norwegian Bokmål - norsk bokmål</option>
                       <option value="nn">Norwegian Nynorsk - nynorsk</option>
                       <option value="oc">Occitan</option>
                       <option value="or">Oriya - ଓଡ଼ିଆ</option>
                       <option value="om">Oromo - Oromoo</option>
                       <option value="ps">Pashto - پښتو</option>
                       <option value="fa">Persian - فارسی</option>
                       <option value="pl">Polish - polski</option>
                       <option value="pt">Portuguese - português</option>
                       <option value="pt-BR">Portuguese (Brazil) - português (Brasil)</option>
                       <option value="pt-PT">Portuguese (Portugal) - português (Portugal)</option>
                       <option value="pa">Punjabi - ਪੰਜਾਬੀ</option>
                       <option value="qu">Quechua</option>
                       <option value="ro">Romanian - română</option>
                       <option value="mo">Romanian (Moldova) - română (Moldova)</option>
                       <option value="rm">Romansh - rumantsch</option>
                       <option value="ru">Russian - русский</option>
                       <option value="gd">Scottish Gaelic</option>
                       <option value="sr">Serbian - српски</option>
                       <option value="sh">Serbo-Croatian - Srpskohrvatski</option>
                       <option value="sn">Shona - chiShona</option>
                       <option value="sd">Sindhi</option>
                       <option value="si">Sinhala - සිංහල</option>
                       <option value="sk">Slovak - slovenčina</option>
                       <option value="sl">Slovenian - slovenščina</option>
                       <option value="so">Somali - Soomaali</option>
                       <option value="st">Southern Sotho</option>
                       <option value="es">Spanish - español</option>
                       <option value="es-AR">Spanish (Argentina) - español (Argentina)</option>
                       <option value="es-419">Spanish (Latin America) - español (Latinoamérica)</option>
                       <option value="es-MX">Spanish (Mexico) - español (México)</option>
                       <option value="es-ES">Spanish (Spain) - español (España)</option>
                       <option value="es-US">Spanish (United States) - español (Estados Unidos)</option>
                       <option value="su">Sundanese</option>
                       <option value="sw">Swahili - Kiswahili</option>
                       <option value="sv">Swedish - svenska</option>
                       <option value="tg">Tajik - тоҷикӣ</option>
                       <option value="ta">Tamil - தமிழ்</option>
                       <option value="tt">Tatar</option>
                       <option value="te">Telugu - తెలుగు</option>
                       <option value="th">Thai - ไทย</option>
                       <option value="ti">Tigrinya - ትግርኛ</option>
                       <option value="to">Tongan - lea fakatonga</option>
                       <option value="tr">Turkish - Türkçe</option>
                       <option value="tk">Turkmen</option>
                       <option value="tw">Twi</option>
                       <option value="uk">Ukrainian - українська</option>
                       <option value="ur">Urdu - اردو</option>
                       <option value="ug">Uyghur</option>
                       <option value="uz">Uzbek - o‘zbek</option>
                       <option value="vi">Vietnamese - Tiếng Việt</option>
                       <option value="wa">Walloon - wa</option>
                       <option value="cy">Welsh - Cymraeg</option>
                       <option value="fy">Western Frisian</option>
                       <option value="xh">Xhosa</option>
                       <option value="yi">Yiddish</option>
                       <option value="yo">Yoruba - Èdè Yorùbá</option>
                       <option value="zu">Zulu - isiZulu</option>';
         }
getClientLanguage()
YAWK\language::getClientLanguage ()
get and return client language
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
string
Definition at line 204 of file language.php.
                                            : string
         {
             // check if browser tells any accepted language
             if(isset($_SERVER['HTTP_ACCEPT_LANGUAGE']) || (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])))
             {   // format the string to eg: en-EN
                 $this->httpAcceptedLanguage = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 5);
                 $this->currentLanguageGlobal = substr($this->httpAcceptedLanguage, 0, 2);
                 return $this->httpAcceptedLanguage;
             }
             else
                 {   // var empty - cannot detect -
                     return false;
                 }
         }
References YAWK\language\$httpAcceptedLanguage.
Referenced by YAWK\language\init().
getCurrentLanguage()
YAWK\language::getCurrentLanguage ($db, $referer)
returns the currently set language
Copyright
2017 Daniel Retzl
Parameters
object $db database object
string $referer frontend|backend from where it the call referred?
Returns
string
Definition at line 62 of file language.php.
                                                          : string
         {
             if (isset($referer) && (is_string($referer)))
             {
                 if ($referer == "frontend")
                 {
                     if ($this->currentLanguage = settings::getSetting($db, "frontendLanguage"))
                     {
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return current language from db-settings// if not, try to set it - with error supressor to avoid notices if output started before
                         @setcookie('lang', $this->currentLanguage, time() + (60 * 60 * 24 * 1460));
                         return $this->currentLanguage;
                     }
                     else
                     {   // failed to get language
                         $this->currentLanguage = "en-EN";   // default: en-EN
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return default value (en-EN)
                         return $this->currentLanguage;
                     }
                 }
                 else if ($referer == "backend")
                 {
                     if ($this->currentLanguage = settings::getSetting($db, "backendLanguage"))
                     {
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return current language from db-settings// if not, try to set it - with error supressor to avoid notices if output started before
                         @setcookie('lang', $this->currentLanguage, time() + (60 * 60 * 24 * 1460));
                         return $this->currentLanguage;
                     }
                     else
                     {   // failed to get language
                         $this->currentLanguage = "en-EN";   // default: en-EN
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return default value (en-EN)
                         return $this->currentLanguage;
                     }
                 }
                 else
                 {
                     if ($this->currentLanguage = settings::getSetting($db, "backendLanguage"))
                     {
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return current language from db-settings// if not, try to set it - with error supressor to avoid notices if output started before
                         @setcookie('lang', $this->currentLanguage, time() + (60 * 60 * 24 * 1460));
                         return $this->currentLanguage;
                     }
                     else
                     {   // failed to get language
                         $this->currentLanguage = "en-EN";   // default: en-EN
                         $_SESSION['lang'] = $this->currentLanguage;
                         // return default value (en-EN)
                         return $this->currentLanguage;
                     }
                 }
             }
             else
             {
                 if ($this->currentLanguage = settings::getSetting($db, "backendLanguage"))
                 {
                     $_SESSION['lang'] = $this->currentLanguage;
                     // return current language from db-settings// if not, try to set it - with error supressor to avoid notices if output started before
                     @setcookie('lang', $this->currentLanguage, time() + (60 * 60 * 24 * 1460));
                     return $this->currentLanguage;
                 }
                 else
                 {   // failed to get language
                     $this->currentLanguage = "en-EN";   // default: en-EN
                     $_SESSION['lang'] = $this->currentLanguage;
                     // return default value (en-EN)
                     return $this->currentLanguage;
                 }
             }
         }
References YAWK\language\$currentLanguage, $db, and YAWK\settings\getSetting().
Referenced by YAWK\language\init().
getCurrentLanguageStatic()
static YAWK\language::getCurrentLanguageStatic () static
returns the currently set backend language, but is static callable
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2017 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
string
Definition at line 146 of file language.php.
         {
             $currentLanguage = '';
             // check if a GET param is set
             if (isset($_GET['lang']) && (!empty($_GET['lang'])))
             {
                 $currentLanguage = $_GET['lang'];     // set GET param as current language
                 // register and overwrite session var
                 $_SESSION['lang'] = $currentLanguage;
                 // and check if cookie is set
                 if (empty($_COOKIE['lang']))
                 {   // if not, try to set it - with error suppressor to avoid notices if output started before
                     @setcookie('lang', $currentLanguage, time() + (60 * 60 * 24 * 1460));
                 }
                 /* language set, cookie set */
                 return $currentLanguage;
             }
             else
             {
                 // GET param not set, check if there is a $_SESSION[lang]
                 if (isset($_SESSION['lang']) && (!empty($_SESSION['lang'])))
                 {
                     // session var is set
                     return $_SESSION['lang'];
                 }
                 // SESSION param not set, check if there is a $_COOKIE[lang]
                 elseif (isset($_COOKIE['lang']) && (!empty($_COOKIE['lang'])))
                 {
                     // cookie var is set
                     return $_COOKIE['lang'];
                 }
                 else
                 {
                     // get language setting from database
                     if (!isset($db))
                     {   // create new db object
                         require_once '../system/classes/db.php';
                         require_once '../system/classes/settings.php';
                         $db = new db();
                     }
                     // get backend language setting and save string eg. (en-EN) in $this->current
                     if (!($currentLanguage = (settings::getSetting($db, "backendLanguage")) === true)) {   // failed to get backend language
                         $currentLanguage = "en-EN";   // default: en-EN
                         // return default value (en-EN)
                     }
                     return $currentLanguage;
                 }
             }
         }
References $_GET, YAWK\language\$currentLanguage, $db, and YAWK\settings\getSetting().
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\includeJS(), YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\includeJS(), YAWK\language\inject(), and YAWK\sys\time_ago().
getPathToLanguageFile()
YAWK\language::getPathToLanguageFile ()
Returns the path to the language file.
Copyright
2017 Daniel Retzl @license https://opensource.org/licenses/MIT return string
Definition at line 323 of file language.php.
         {
             // check if call comes from frontend or backend
             if(stristr($_SERVER['PHP_SELF'], '/admin/') == TRUE)
             {
                 // call seem to come from BACKEND
                 // check if directory is reachable
                 if (is_dir("language/"))
                 {
                     // set path to backend
                     $this->pathToFile = "language/";
                 }
                 elseif (is_dir("admin/language/"))
                 {
                     $this->pathToFile = "admin/language";
                 }
                 // call seems to come from admin/js/ folder (probably a class called by ajax in /system/classes/*
                 elseif (is_dir("../language/"))
                 {
                     $base_dir = __DIR__;
                     $base_dir = substr($base_dir, 0, -15); // remove last 15 chars
                     $this->pathToFile = $base_dir."/admin/language/";
                 }
                 else
                 {
                     '';
                 }
             }
             // if setup is running
             else if (isset($_SESSION['SETUP']) && ($_SESSION['SETUP'] == TRUE))
             {       // load backend language files
                     $this->pathToFile = "admin/language/";
             }
             // in any other case load frontend language
             else
             {   // set path to FRONTEND
                 if (is_dir("system/language/"))
                 {   // set frontend language path
                     $this->pathToFile = "system/language/";
                 }
                 // if frontend language files are not reachable, check if backend language files exist
                 else if (is_dir("admin/language"))
                 {   // load backend files instead
                     $this->pathToFile = "admin/language/";
                 }
                 // if frontend language files are not reachable, check if backend language files exist
                 else if (is_dir("../../../language"))
                 {   // load backend files instead
                     $this->pathToFile = "../../../language/";
                 }
                 else
                     {   // no language files found (even no backend files)
                         die ("ERROR: Unable to load language files. Several conditions failed - files are missing or corrupt. Please inform the page administrator about this concern.");
                     }
             }
             return $this->pathToFile;
         }
References YAWK\language\$pathToFile, and die.
Referenced by YAWK\language\setLanguage().
getSupportedLanguages()
YAWK\language::getSupportedLanguages ()
sets object supportedLanguages as array including all supported languages
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
bool
Definition at line 226 of file language.php.
                                                : bool
         {
             // walk /admin/language folder and get all language files into an array
             require_once ('system/classes/filemanager.php');
             $languageFiles = filemanager::getFilesFromFolderToArray('admin/language');
             foreach ($languageFiles AS $file)
             {
                 if ($file != ".htaccess")
                 {
                     $globalLanguageTag = substr($file, 5, -7);
                     $this->supportedLanguagesGlobal[] = $globalLanguageTag;
                     $localLanguageTag = substr($file, 5, -4);
                     $this->supportedLanguages[] = $localLanguageTag;
                     // $this->supportedLanguages[] = $globalLanguageTag;
                 }
             }
             if (is_array($this->supportedLanguagesGlobal) && (is_array($this->supportedLanguages)))
             {
                 return true;
             }
             else
                 {
                     return false;
                 }
         }
References YAWK\filemanager\getFilesFromFolderToArray().
Referenced by YAWK\language\isSupported().
init()
YAWK\language::init ($db, $referer)
initialize and return current language
Returns
array|bool
Copyright
2009-2016 Daniel Retzl
Definition at line 46 of file language.php.
         {
             // set current language
             $this->httpAcceptedLanguage = $this->getClientLanguage();
             $this->currentFrontendLanguage = settings::getSetting($db, "frontendLanguage");
             $this->currentLanguage = $this->getCurrentLanguage($db, $referer);
             return $this->setLanguage($this->currentLanguage);
         }
References $db, YAWK\language\getClientLanguage(), YAWK\language\getCurrentLanguage(), YAWK\settings\getSetting(), and YAWK\language\setLanguage().
inject()
static YAWK\language::inject (array $lang, string $pathToFile) static
allow plugins to inject language tags to $lang array
Parameters
array $lang the language data array
string $pathToFile absolute path to the injectable language file
Returns
array $lang returns pushed language array
Definition at line 439 of file language.php.
                                                                : array
         {
             // check if language is saved in session or cookie to prevent unnecessary db actions
             if (isset($_SESSION['lang']))
             {   // set from session setting
                 $currentLanguage = $_SESSION['lang'];
             }
             elseif (isset($_COOKIE['lang']))
             {   // set from cookie setting
                 $currentLanguage = $_COOKIE['lang'];
             }
             elseif (isset($_GET['lang']))
             {   // set from cookie setting
                 $currentLanguage = $_GET['lang'];
             }
             else
                 {   // get current language from db
                     $currentLanguage = language::getCurrentLanguageStatic();
                     if (isset($currentLanguage) && (!empty($currentLanguage)))
                     {   // set session var to save database resources
                         $_SESSION['lang'] = $currentLanguage;
                     }
                 }
             // get injectable tags from additional language file
             $additionalTags = parse_ini_file("$pathToFile"."$currentLanguage".".ini");
             // add every tag, once per row
             foreach ($additionalTags AS $tag => $value)
             {   // add data to $lang array
                 $lang[$tag] = $value;
             }
             // fin -
             return $lang;
         } /* end setLanguage */
References $_GET, YAWK\language\$currentLanguage, YAWK\language\$lang, $value, and YAWK\language\getCurrentLanguageStatic().
isSupported()
YAWK\language::isSupported (string $currentLanguage)
Check if a language is supported. This functions expect currentLanguage string in format "en-EN" or "en".
Parameters
string $currentLanguage language in format: en-EN or en
Returns
bool @license https://opensource.org/licenses/MIT
Copyright
2017 Daniel Retzl
Definition at line 259 of file language.php.
                                                             : bool
         {
             // create arrays with supported languages, one in format "en", the other one "en-EN"
             $this->getSupportedLanguages();
             // check if language is set and not empty
             if (isset($currentLanguage) && (!empty($currentLanguage)))
             {
                 // if language is submitted as global language tag (short, like: en instead of en-EN)
                 if (strlen($currentLanguage) <= 2)
                 {
                     // check if supportedLanguages match with language
                     if (in_array($currentLanguage, $this->supportedLanguagesGlobal))
                     {
                         // language is supported
                         // $language->setLanguage($language->currentLanguageGlobal); // set language
                         return true;
                     }
                     else
                     {
                         // detected language is not supported, set en-EN as default
                         return false;
                     }
                 } // end global language tag (en)
                 else
                     {   // check supportedLanguagesLocal match with detected user language
                         if (in_array($currentLanguage, $this->supportedLanguages))
                         {   // language supported
                             return true;
                         }
                         else
                             {   // language not supported
                                 return false;
                             }
                     }
             }
             else
                 {   // language is not set
                     return false;
                 }
         }
References YAWK\language\$currentLanguage, and YAWK\language\getSupportedLanguages().
setDefault()
YAWK\language::setDefault (string $defaultLanguage)
Set a language as default and load (set) it current language.
Parameters
string $defaultLanguage language in format: en-EN or en
Copyright
2017 Daniel Retzl @license https://opensource.org/licenses/MIT
Definition at line 307 of file language.php.
         {
             if ((!empty($defaultLanguage)))
             {
                 // set default language
                 $this->currentLanguage = $defaultLanguage;
                 $this->setLanguage($defaultLanguage);
             }
         }
References YAWK\language\$defaultLanguage, and YAWK\language\setLanguage().
setLanguage()
YAWK\language::setLanguage (string $currentLanguage)
set client language and parse corresponding ini file to an array called $lang
Parameters
string $currentLanguage the current language as string (e.g. en-US)
Returns
array|bool $lang returns a language array
Definition at line 388 of file language.php.
         {
             $this->pathToFile = $this->getPathToLanguageFile();
             //  short language identify string global (just 2 chars) sent
             if (strlen($currentLanguage) == 2)
             {   // build a proper currentLanguage string
                 $global = $currentLanguage;
                 $local = strtoupper($currentLanguage);
                 $currentLanguage = "$global-$local";
                 $this->currentLanguage = $currentLanguage;
             }
             // if language file exists...
             if (is_file("$this->pathToFile"."lang-"."$currentLanguage".".ini"))
             {   // parse language file into array
                 if ($this->lang = parse_ini_file("$this->pathToFile"."lang-"."$currentLanguage".".ini"))
                 {   // file loaded, return language array
                     return $this->lang;
                 }
                 else
                     {   // file could not be parsed into array - abort with error
                         die ("could not load language file: $this->pathToFile"."lang-"."$currentLanguage".".ini");
                     }
             }
             // language file does not exist - check if an en-EN file exists...
             elseif (is_file("$this->pathToFile"."lang-en-EN.ini"))
             {   // parse language file into array
                 if ($this->lang = parse_ini_file("$this->pathToFile"."lang-en-EN.ini"))
                 {   // file loaded, return language array
                     return $this->lang;
                 }
                 else
                     {   // file could not be parsed into array - abort with error
                         die ("ERROR: Could not load language file: $this->pathToFile"."lang-en-EN.ini");
                     }
             }
             else
                 {   // language file not found
                     // english (default) language file not found
                     // abort with error
                     die ("CRITICAL ERROR: No language file found. It should be there, but it isn't. This is strange. Please check $this->pathToFile and install a language file.");
                 }
         } /* end setLanguage */
References YAWK\language\$currentLanguage, YAWK\language\$lang, die, and YAWK\language\getPathToLanguageFile().
Referenced by YAWK\language\init(), and YAWK\language\setDefault().
Member Data Documentation
$currentFrontendLanguage
YAWK\language::$currentFrontendLanguage
Parameters
string $currentLanguage current setted language in format: en-EN
Definition at line 25 of file language.php.
$currentLanguage
YAWK\language::$currentLanguage
Parameters
string $currentLanguage current setted language in format: en-EN
Definition at line 23 of file language.php.
Referenced by YAWK\language\getCurrentLanguage(), YAWK\language\getCurrentLanguageStatic(), YAWK\language\inject(), YAWK\language\isSupported(), and YAWK\language\setLanguage().
$currentLanguageGlobal
YAWK\language::$currentLanguageGlobal
Parameters
string $currentLanguageGlobal current setted language in format: en
Definition at line 27 of file language.php.
$defaultLanguage
YAWK\language::$defaultLanguage
Parameters
string $defaultLanguage default language if no supported language can be detected
Definition at line 21 of file language.php.
Referenced by YAWK\language\setDefault().
$detectedLanguage
YAWK\language::$detectedLanguage
Parameters
string $detectedLanguage current detected language in format: en-EN
Definition at line 29 of file language.php.
$detectedLanguageGlobal
YAWK\language::$detectedLanguageGlobal
Parameters
string $detectedLanguageGlobal current detected language in format: en
Definition at line 31 of file language.php.
$httpAcceptedLanguage
YAWK\language::$httpAcceptedLanguage
Parameters
string $httpAcceptedLanguage current $_SERVER['HTTP_ACCEPTED_LANGUAGE'] in format: en-EN
Definition at line 33 of file language.php.
Referenced by YAWK\language\getClientLanguage().
$lang
YAWK\language::$lang
Parameters
array $lang language array
Definition at line 19 of file language.php.
Referenced by YAWK\language\inject(), and YAWK\language\setLanguage().
$pathToFile
YAWK\language::$pathToFile
Parameters
string $pathToFile the path to the language file
Definition at line 35 of file language.php.
Referenced by YAWK\language\getPathToLanguageFile().
$supportedLanguages
YAWK\language::$supportedLanguages
Parameters
array $supportedLanguages array that contains all supported languages, but the full tag eg. (en-EN)
Definition at line 39 of file language.php.
$supportedLanguagesGlobal
YAWK\language::$supportedLanguagesGlobal
Parameters
array $supportedLanguagesGlobal array that contains all supported languages, shortened to the first 2 chars eg. (en)
Definition at line 37 of file language.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/language.php