YaWK: YAWK\WIDGETS\SUBMENU\EMBED\submenu Class Reference
YAWK\WIDGETS\SUBMENU\EMBED\submenu Class Reference
Submenu widget - embed any menu on any page in any position.
Public Member Functions
__construct ($db)
display any subMenu (used by widgets to get any menu in any position)
displaySubMenu ($db, $menuID)
drawMenu ($db)
init ($db)
Init submenu widget and call a function for demo purpose.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$menuID = ''
$subMenuClass
$submenuHeading = ''
$subMenuItemClass
$submenuSubtext = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Submenu widget - embed any menu on any page in any position.
Empty submenu Widget - for development and demo purpose
If you want to embed any menu on any page in any position, this should be the widget of your choice! It can handle every menu that you have created before within YaWK's menu system.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 19 of file submenu.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\SUBMENU\EMBED\submenu::__construct ($db)
display any subMenu (used by widgets to get any menu in any position)
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Parameters
object $db database
int $menuID the menuID to get data
Load all widget settings from database and fill object
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 51 of file submenu.php.
         {
             // load this widget settings from db
             $this->widget = new widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
displaySubMenu()
YAWK\WIDGETS\SUBMENU\EMBED\submenu::displaySubMenu ($db, $menuID)
Parameters
db $db
Definition at line 83 of file submenu.php.
         {   /** @param db $db */
             // get menu entries and draw navbar
             $res = $db->query("SELECT * FROM {menu}
                                WHERE published = 1
                                AND menuID = '".$menuID."'
                                ORDER by sort, title");
             $subMenuItem = '';
             $subMenuClass = '';
             $subMenuItemClass = '';
             while ($row = mysqli_fetch_assoc($res))
             {
                 // check if target is set
                 if (!empty($row['target']))
                 {   // target is set
                     $row['target'] = ' target="'.$row['target'].'"';
                 }
                 else
                 {   // target is not set
                     $row['target'] = '';
                 }
                 // check if subMenu class is set
                 if (!empty($this->subMenuClass)){
                     $subMenuClass = ' class="'.$this->subMenuClass.'"';
                 }
                 else
                 {   // subMenuClass is not set
                     $subMenuClass = '';
                 }
                 // check if subMenuItem class is set
                 if (!empty($this->subMenuItemClass)){
                     $submenuItemClass = ' class="'.$this->subMenuItemClass.'"';
                 }
                 else
                 {   // subMenuItemClass is not set
                     $subMenuItemClass = '';
                 }
                 // check if icon is set
                 if (isset($row['icon']))
                 {   // set icon markup
                     $icon = '<i class="'.$row["icon"].' text-muted"></i>';
                 }
                 else
                 {   // no icon set
                     $icon = "";
                 }
                 $subMenuItem .= '<li class="list-group-item">'.$icon.' &nbsp;&nbsp;<a href="'.$row['href'].'"'.$subMenuItemClass.$row['target'].'>'.$row['text'].'</a></li>';
             }
             echo '<div id="subMenu"'.$subMenuClass.'>
                     <ul class="list-group" style="cursor:pointer;">';
             echo '    '.$subMenuItem.'</ul>
                   </div>';
References $db, YAWK\WIDGETS\SUBMENU\EMBED\submenu\$menuID, $res, YAWK\WIDGETS\SUBMENU\EMBED\submenu\$subMenuClass, and YAWK\WIDGETS\SUBMENU\EMBED\submenu\$subMenuItemClass.
Referenced by YAWK\WIDGETS\SUBMENU\EMBED\submenu\drawMenu().
drawMenu()
YAWK\WIDGETS\SUBMENU\EMBED\submenu::drawMenu ($db)
Definition at line 72 of file submenu.php.
         {
             // check if menu obj is set
             if (!isset($menu))
             {
                 require_once 'system/classes/menu.php';
                 $menu = new \YAWK\menu();
             }
             $this->displaySubMenu($db, $this->menuID);
References $db, and YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu().
Referenced by YAWK\WIDGETS\SUBMENU\EMBED\submenu\init().
init()
YAWK\WIDGETS\SUBMENU\EMBED\submenu::init ($db)
Init submenu widget and call a function for demo purpose.
submenu Widget Init
Definition at line 65 of file submenu.php.
         {
             // draw headline
             echo $this->getHeading($this->submenuHeading, $this->submenuSubtext);
             $this->drawMenu($db);
References $db, YAWK\WIDGETS\SUBMENU\EMBED\submenu\drawMenu(), and YAWK\widget\getHeading().
Member Data Documentation
$menuID
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$menuID = ''
Parameters
int ID of the menu to display
Definition at line 28 of file submenu.php.
Referenced by YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu().
$subMenuClass
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$subMenuClass
Parameters
string the class that is applied to the subMenu
Definition at line 31 of file submenu.php.
Referenced by YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu().
$submenuHeading
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$submenuHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 24 of file submenu.php.
$subMenuItemClass
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$subMenuItemClass
Parameters
string the class that is applied to a subMenu Item
Definition at line 34 of file submenu.php.
Referenced by YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu().
$submenuSubtext
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$submenuSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 26 of file submenu.php.
$widget
YAWK\WIDGETS\SUBMENU\EMBED\submenu::$widget = ''
Parameters
object global widget object data
Definition at line 22 of file submenu.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/submenu/classes/submenu.php