YaWK: YAWK\user Class Reference
YAWK\user Class Reference
The default user class. Provide all functions to handle the user object.
Public Member Functions
__construct ($db)
user constructor.
getUserArray ($db)
return user data as an array
isAllowedToOverrideTemplate ($db, $uid)
check if user ID is allowed to override template
isTemplateEqual ($db, $userTemplateID)
check if user template equals selected (active) template
setUserTemplate ($db, $overrideTemplate, $userTemplateID, $uid)
set status and override template for this user ID
Static Public Member Functions
static ajaxLogin ($db, $user, $password)
static checkResetToken ($db, $token)
Check if password reset token matches and return uid.
static countUsers ($db)
count and return all users
static drawLoginBox ($username, $password)
return the html for a default login box
static drawMenuLoginBox ($username, $password, $style)
return the html for a menu login box
static drawPasswordResetForm ($db, $lang, $uid)
Draw the form where users can reset their password.
static getCurrentUserName ($lang)
return current username
static getLatestUsers ($db, $count)
get latest users and return as array
static getLoginData ($db, $user)
return an array with all login data
static getToken ($length)
Generate a safe token for password reset.
static getUserEmail ($db, $user)
return email address of $user
static getUserImage ($location, $user, $cssClass, $w, $h)
return and output user image
static getUserList ($db)
output a list of all users (who have not activated privacy switch)
static getUserTemplateID ($db, $uid)
template ID for given user ID
static isAnybodyThere ($db)
check, if a session username is set and if user is logged in
static sendResetEmail ($db, $username, $email, $lang)
Send password change request email.
static setNewPassword ($db, $newPassword, $uid)
Set a new user password.
Public Attributes
$blocked
$city
$country
$currentuser
$date_changed
$date_created
$date_expired
$date_lastlogin
$email
$facebook
$firstname
$gid
$id
$job
$lastlogin
$lastname
$likes
$logged_in
$login_count
$online
$overrideTemplate
$password
$privacy
$public_email
$published
$street
$templateID
$twitter
$url
$username
$zipcode
Detailed Description
The default user class. Provide all functions to handle the user object.
The default user class. Provide all functions to handle the user object.
All functions that are required to handle a user. Methods are: add, edit, delete, checklogin and many more.
Class covers both, backend & frontend functionality. See Methods Summary for Details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl @license https://opensource.org/licenses/MIT
Definition at line 16 of file user.php.
Constructor & Destructor Documentation
__construct()
YAWK\user::__construct ($db)
user constructor.
Definition at line 84 of file user.php.
         {
             if (!isset($db)){ $db = new \YAWK\db(); }
             if (isset($_SESSION['username']))
             {
                 $this->loadProperties($db, $_SESSION['username']);
             }
         }
References $db.
Member Function Documentation
ajaxLogin()
static YAWK\user::ajaxLogin ($db, $user, $password) static
Definition at line 1626 of file user.php.
         {
             // create new user class object
             $userClass = new \YAWK\user($db);
             // check user and password vars
             if (isset($user) && (!empty($user) && (is_string($user)
                         && (isset($password) && (!empty($password) && (is_string($password)))))))
             {
                 // check if user is logged in
                 if (self::isLoggedIn($db, $user) === false)
                 {
                     // login successful
                     if(self::login($db, $user, $password) === true)
                     {   // login successful
                         $userClass->storeLogin($db, 0, "frontend", $user, $password);
                         // \YAWK\sys::setSyslog($db, "3", "ajax login successful", 0, 0, 0, 0);
                         return true;
                     }
                     else
                     {   // login failed
                         $userClass->storeLogin($db, 1, "frontend", $user, $password);
                         // \YAWK\sys::setSyslog($db, "5", "ajax login failed", 0, 0, 0, 0);
                         return false;
                     }
                 }
                 // in any other case
                 return false;
             }
             else
             {   // login data wrong
                 return false;
             }
         }
References $db, and YAWK\user\$password.
checkResetToken()
static YAWK\user::checkResetToken ($db, $token) static
Check if password reset token matches and return uid.
Parameters
object $db database obj
string $token token that was generated for this user
Returns
mixed returns the affected user id (or false)
Definition at line 129 of file user.php.
         {
             // check if token is set and in valid format
             if (isset($token) && (is_string($token)))
             {
                 // strip tags for security reasons
                 $token = strip_tags($token);
                 // compare with stored token in database
                 if ($res = $db->query("SELECT id FROM {users} WHERE hashValue = '".$token."'"))
                 {
                     // token matches, get user ID
                     if ($row = mysqli_fetch_row($res))
                     {
                         // return user ID
                         return $row[0];
                     }
                     else
                     {   // no ID found
                         return false;
                     }
                 }
                 else
                 {   // no user with this token hash value found
                     return false;
                 }
             }
             else
             {   // user token not set or wrong type
                 return false;
             }
         }
References $db, and $res.
Referenced by YAWK\controller\filterfilename().
countUsers()
static YAWK\user::countUsers ($db) static
count and return all users
Parameters
object $db database
Returns
string|bool
Definition at line 752 of file user.php.
         {
             /* @param $db \YAWK\db */
             if ($result = $db->query("SELECT count(id) FROM {users}"))
             {
                 $i = mysqli_fetch_row($result);
                 return $i[0];
             }
             else
             {
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to count user db ", 0, 0, 0, 0);
                 return false;
             }
         }
References $db, $i, and $result.
drawLoginBox()
static YAWK\user::drawLoginBox ($username, $password) static
return the html for a default login box
Parameters
string $username username, as option
string $password password, as option
Returns
string
Definition at line 1992 of file user.php.
         {
             $html = "
             <form name=\"login\" id=\"loginForm\" role=\"form\" method=\"POST\">
                 <input type=\"text\" id=\"user\" name=\"user\" value=\"".$username."\" class=\"form-control animated fadeIn\" placeholder=\"Benutzername\">
                 <input type=\"password\" id=\"password\" name=\"password\" value=\"".$password."\" class=\"form-control animated fadeIn\" placeholder=\"Passwort\">
                 <input type=\"hidden\" name=\"login\" value=\"login\">
                 <input type=\"submit\" id=\"submitBtn\" value=\"Login\" style=\"margin-top:5px;\" name=\"Login\" class=\"btn btn-success animated fadeIn\">
             </form>";
             return $html;
         }
References YAWK\user\$password.
Referenced by YAWK\controller\filterfilename().
drawMenuLoginBox()
static YAWK\user::drawMenuLoginBox ($username, $password, $style) static
return the html for a menu login box
Parameters
string $username username, as option
string $password password, as option
string $style menu styling: light or dark
Returns
string htmnl that draws the menu login box
Definition at line 2011 of file user.php.
         {
             if (!isset($style) || (empty($style)))
             {
                 $style = "light";
                 $input_style = '';
             }
             else
             {
                 if ($style == "light")
                 {
                     $input_style = '';
                 }
                 elseif ($style == "dark")
                 {
                     $input_style = "style=\"color: #ccc; border-color: #000; background-color: #444;\"";
                 }
                 else
                 {
                     $input_style = '';
                 }
             }
             $html = "<form name=\"login\" class=\"navbar-form navbar-right\" role=\"form\" action=\"welcome.html\" method=\"POST\">
               <div class=\"form-group\">
                 <input type=\"text\" id=\"user\" name=\"user\" value=\"".$username."\" class=\"form-control\" $input_style placeholder=\"Benutzername\">
                 <input type=\"password\" id=\"password\" name=\"password\" value=\"".$password."\" class=\"form-control\" $input_style placeholder=\"Passwort\">
                 <input type=\"hidden\" name=\"login\" value=\"login\">
                 <input type=\"hidden\" name=\"LOCK\" value=\"1\">
                 <input type=\"hidden\" name=\"include\" value=\"login\">
                 <input type=\"submit\" value=\"Login\" name=\"Login\" class=\"btn btn-success\">
                 </div>
             </form>";
             return $html;
         }
References YAWK\user\$password.
Referenced by YAWK\menu\display().
drawPasswordResetForm()
static YAWK\user::drawPasswordResetForm ($db, $lang, $uid) static
Draw the form where users can reset their password.
The password reset email leads to this form.
Parameters
object $db database obj
array $lang language array
int $uid user ID
Definition at line 169 of file user.php.
         {
             echo "<form action=\"index.php?setNewPassword=true\" method=\"POST\" role=\"form\">";
             echo "<label for=\"newPassword1\">$lang[PASSWORD]</label>";
             echo "<input type=\"password\" class=\"form-control\" name=\"newPassword1\" id=\"newPassword1\">";
             echo "<label for=\"newPassword2\">$lang[PASSWORD_REPEAT]</label>";
             echo "<input type=\"password\" class=\"form-control\" name=\"newPassword2\" id=\"newPassword2\">";
             echo "<input type=\"hidden\" value=\"$uid\" class=\"form-control\" name=\"uid\" id=\"uid\">";
             echo "<button type=\"submit\" style=\"margin-top:5px;\" class=\"btn btn-success\">$lang[PASSWORD_SET_NEW]</button>";
             echo "</form>";
         }
Referenced by YAWK\controller\filterfilename().
getCurrentUserName()
static YAWK\user::getCurrentUserName ($lang) static
return current username
Parameters
object $lang language obj
Returns
string current username
Definition at line 342 of file user.php.
         {
             if (isset($_SESSION['username']))
             {
                 return $_SESSION['username'];
             }
             else
             {
                 return $lang['GUEST'];
             }
         }
References $lang.
Referenced by YAWK\BACKEND\AdminLTE\drawHtmlContent().
getLatestUsers()
static YAWK\user::getLatestUsers ($db, $count) static
get latest users and return as array
Parameters
object $db database
int $count limit the query
Returns
array|string
Definition at line 716 of file user.php.
         {
             if (isset($count))
             {   // param
                 $limit = $count;
             }
             else
             {   // default value
                 $limit = 8;
             }
             /* @param $db \YAWK\db */
             if ($result = $db->query("SELECT cu.*, cg.value as gid FROM {users} as cu
                                       JOIN {user_groups} as cg on cu.gid = cg.id ORDER BY id LIMIT $limit"))
             {
                 $userDataArray = array();
                 // cycle trough results
                 while ($row = $result->fetch_assoc())
                 {
                     $userDataArray[] = $row;
                 }
                 /* free result */
                 $result->close();
             }
             else {
                 $userDataArray = '';
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to fetch user list", 0, 0, 0, 0);
                 echo \YAWK\alert::draw("danger", "Error", "Sorry, database error: fetch getLatestUsers failed.","page=users","4800");
             }
             return $userDataArray;
         }
References $db, and $result.
Referenced by YAWK\BACKEND\dashboard\drawLatestUsers().
getLoginData()
static YAWK\user::getLoginData ($db, $user) static
return an array with all login data
Parameters
object $db database
object $user
Returns
array|bool
Definition at line 538 of file user.php.
         {   /* @param $db \YAWK\db */
             if (isset($user) && (!empty($user)))
             {   // check if user is registered
                 if (self::hasLoggedIn($db, $user))
                 {   // user is in list, extend sql string
                     $sqlStr = "WHERE username='$user'";
                     \YAWK\alert::draw("success", "showing login data for user: $user", " ", "",2400);
                 }
                 else
                 {   // user not found in table, so draw an alert and show all logins...
                     $sqlStr = '';
                     \YAWK\alert::draw("warning", "Error!", "<h4>No login data available.</h4> Could not get data for user <b>$user</b>. Displaying all data instead.", "",5000);
                 }
             }
             else
             {   // show all logins
                 $sqlStr = '';
             }
             if ($res = $db->query("SELECT * FROM {logins} $sqlStr"))
             {   // fetch data in loop
                 while ($row = $res->fetch_assoc())
                 {   // store logins into array
                     $loginsArray[] = $row;
                 }
                 if (isset($loginsArray) && (!empty($loginsArray)))
                 {   // if array is set and not empty
                     return $loginsArray;
                 }
                 else
                 {   // something went wrong
                     return false;
                 }
             }
             else
             {   // could not query login data...
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to query login data of $user ", 0, 0, 0, 0);
                 return false;
             }
         }
References $db, $res, and YAWK\alert\draw().
getToken()
static YAWK\user::getToken ($length) static
Generate a safe token for password reset.
Parameters
string $length the length of your token
Returns
string $token function returns the token
Definition at line 99 of file user.php.
         {
             $token = "";
             $code = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
             $code.= "abcdefghijklmnopqrstuvwxyz";
             $code.= "0123456789";
             $max = strlen($code); // edited
             for ($i=0; $i < $length; $i++)
             {
                 $token .= $code[random_int(0, $max-1)];
             }
             // check if token is set
             if (is_string($token))
             {   // ok, return token
                 return $token;
             }
             else
             {   // error generating token
                 return false;
             }
         }
References $i.
Referenced by YAWK\user\sendResetEmail().
getUserArray()
YAWK\user::getUserArray ($db)
return user data as an array
Parameters
object $db database
Returns
array|string
Definition at line 688 of file user.php.
         {
             /* @param $db \YAWK\db */
             if ($result = $db->query("SELECT cu.*, cg.value as gid FROM {users} as cu
                                       JOIN {user_groups} as cg on cu.gid = cg.id ORDER BY id"))
             {
                 $userDataArray = array();
                 // cycle trough results
                 while ($row = $result->fetch_assoc())
                 {
                     $userDataArray[] = $row;
                 }
                 /* free result */
                 $result->close();
             }
             else {
                 $userDataArray = '';
                 echo \YAWK\alert::draw("danger", "Error", "Sorry, database error: fetch getUserArray failed.","page=users","4800");
             }
             return $userDataArray;
         }
References $db, and $result.
getUserEmail()
static YAWK\user::getUserEmail ($db, $user) static
return email address of $user
Parameters
object $db database
string $user username
Returns
bool the emailadress of this $user
Parameters
$db \YAWK\db $res
Definition at line 1252 of file user.php.
         {   /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT email
                               FROM {users}
                               WHERE username = '" . $user. "'"))
             {   // fetch data
                 $row = $res->fetch_row();
                 return $row[0];
             }
             else
             {   // q failed
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to get email address of <b>$user</b> ", 0, 0, 0, 0);
                 return false;
             }
         }
References $db, and $res.
Referenced by YAWK\user\sendResetEmail().
getUserImage()
static YAWK\user::getUserImage ($location, $user, $cssClass, $w, $h) static
return and output user image
Parameters
string $location frontend or backend
string $user username
string $cssClass image css class eg. img-circle
int $w width in pixel
int $h height in pixel
Returns
string
Definition at line 1077 of file user.php.
         {
             if (isset($w) && isset($h))
             {
                 if ($w === 0)
                 {
                     $width = 0;
                 }
                 else
                 {
                     $width = "width=\"$w\" ";
                 }
                 if ($h === 0)
                 {
                     $height = 0;
                 }
                 else
                 {
                     $height = "height=\"$h\" ";
                 }
             }
             else
             {
                 $width = '';
                 $height = '';
             }
             if (isset($cssClass))
             {
                 $css = "class=\"$cssClass\"";
             }
             else
             {
                 $css = '';
             }
             if (isset($location))
             {
                 if ($location == "frontend"){
                     $imageJpg = "media/images/users/".$user.".jpg";
                     $imagePng = "media/images/users/".$user.".png";
                     $defaultPic = "<img src=\"media/images/users/avatar.png\" $width $height $css>";
                 }
                 else
                 {
                     $imageJpg = '';
                     $imagePng = '';
                     $defaultPic = "<img src=\"media/images/users/avatar.png\" $width $height $css>";
                 }
                 if ($location == "backend"){
                     $imageJpg = "../media/images/users/".$user.".jpg";
                     $imagePng = "../media/images/users/".$user.".png";
                     if ($cssClass == "img-circle")
                     {
                         $defaultPic = "<img src=\"../media/images/users/avatar.png\" $width $height $css>";
                     }
                     elseif ($cssClass == "img-circle sidebar-toggle")
                     {
                         $defaultPic = "<img src=\"../media/images/users/avatar-light.png\" $width $height $css>";
                     }
                     if ($cssClass == "user-image")
                     {
                         $defaultPic = "<img src=\"../media/images/users/avatar.png\" $width $height $css>";
                     }
                     if ($cssClass == "profile-user-img img-responsive img-circle")
                     {
                         $defaultPic = "<img src=\"../media/images/users/avatar.png\" $width $height $css>";
                     }
                 }
                 else
                 {
                     $imageJpg = '';
                     $imagePng = '';
                     $defaultPic = "<img src=\"media/images/users/avatar.png\" $width $height $css>";
                 }
             }
             else
             {
                 $imageJpg = '';
                 $imagePng = '';
                 $defaultPic = "<img src=\"media/images/users/avatar.png\" $width $height $css>";
             }
             if (file_exists($imageJpg)){
                 return "<img src=\"".$imageJpg."\" $width $height $css>";
             }
             elseif (file_exists($imagePng)){
                 return "<img src=\"".$imagePng."\" $width $height $css>";
             }
             else
             {
                 return $defaultPic;
             }
         }
Referenced by YAWK\BACKEND\AdminLTE\drawHtmlLeftSidebar(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarMessagesMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarUserAccountMenu(), YAWK\BACKEND\dashboard\drawLatestUsers(), YAWK\menu\drawLogoutMenu(), and YAWK\PLUGINS\MESSAGES\messages\MessageView().
getUserList()
static YAWK\user::getUserList ($db) static
output a list of all users (who have not activated privacy switch)
Parameters
object $db database
Definition at line 2119 of file user.php.
         {   /* @param \YAWK\db $db */
             // show ALL users
             // get all users from db where privacy is set to zero
             // & just pick users who are set to online in database
             $res = $db->query("SELECT username, email, public_email, online FROM {users} WHERE privacy != 1");
             while ($row = mysqli_fetch_assoc($res)){
                 // first char uppcerase
                 $username = ucfirst($row['username']);
                 // check if users email adress is public
                 if ($row['email'] && $row['public_email'] === '0'){
                     $email = $row['email'];
                 } else {
                     $email = "";
                 } // if not, build an empty string
                 if ($row['online'] === '0') {
                     $color = "text-danger";
                 }
                 else {
                     $color = "text-success";
                 }
                 echo "<ul class=\"list-group\">
             <li class=\"list-group-item\"><span class=\"".$color."\"><strong>".$username." &nbsp;&nbsp;<small>".$email."</strong></small></span></li>
             </ul>";
             }
         }
References $db, YAWK\user\$email, $res, and YAWK\user\$username.
Referenced by YAWK\template\setPosition().
getUserTemplateID()
static YAWK\user::getUserTemplateID ($db, $uid) static
template ID for given user ID
Parameters
object $db database
int $uid user ID
Returns
string|bool return template ID to corresponding user ID
Definition at line 419 of file user.php.
         {   /* @param $db \YAWK\db */
             if (!isset($uid) && (empty($uid)))
             {   // uid is missing
                 return false;
             }
             if ($res = $db->query("SELECT templateID FROM {users} WHERE id = $uid"))
             {
                 if ($row = mysqli_fetch_row($res))
                 {   // return $userTemplateID
                     return $row[0];
                 }
                 else
                 {
                     \YAWK\sys::setSyslog($db, 11, 1, "failed to get templateID from user db ", $uid, 0, 0, 0);
                     return false;
                 }
             }
             else
             {
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to query templateID from user db ", $uid, 0, 0, 0);
                 return false;
             }
         }
References $db, $res, and $uid.
isAllowedToOverrideTemplate()
YAWK\user::isAllowedToOverrideTemplate ($db, $uid)
check if user ID is allowed to override template
Parameters
object $db database
int $uid user ID
Returns
bool
Definition at line 450 of file user.php.
         {   /* @param $db \YAWK\db */
             if ($res = $db->query("SELECT overrideTemplate FROM {users} WHERE id = $uid"))
             {
                 if ($row = mysqli_fetch_row($res))
                 {
                     if ($row[0] === "1")
                     {
                         return true;
                     }
                     else
                     {
                         return false;
                     }
                 }
                 else
                 {
                     \YAWK\sys::setSyslog($db, 11, 1, "failed to get overrideTemplate status from user db ", 0, 0, 0, 0);
                     return false;
                 }
             }
             else
             {
                 return false;
             }
         }
References $db, and $res.
isAnybodyThere()
static YAWK\user::isAnybodyThere ($db) static
check, if a session username is set and if user is logged in
Parameters
object $db database obj
Returns
string|bool return current username or false
Definition at line 359 of file user.php.
         {
             // check if session is set
             if (isset($_SESSION))
             {
                 // check if session username + uid is set
                 if (isset($_SESSION['username']) && isset($_SESSION['uid']))
                 {   // check if session logged_in status is true
                     if ($_SESSION['logged_in'] == true)
                     {   // session username is set, check if its a non-empty string
                         if (!empty($_SESSION['username']) && (is_string($_SESSION['username'])))
                         {   // username seems to be valid -
                             return $_SESSION['username'];
                         }
                         else
                         {   // username seems not to be valid
                             return false;
                         }
                     }
                     else
                     {   // user is there, but not logged in
                         return false;
                     }
                 }
                 else
                 {   // session username is not set
                     return false;
                 }
             }
             // no session - check if $_GET is set instead
             else if (isset($_GET))
             {   // check if user param is set
                 if (isset($_GET['user']) && (!empty($_GET['user']) && (is_string($_GET['user']))))
                 {   // check if database says user is logged in
                     if (self::isLoggedIn($db, $_GET['user']))
                     {   // user is logged in
                         return $_GET['user'];
                     }
                     else
                     {   // user is not logged in
                         return false;
                     }
                 }
                 else
                 {   // $_GET user is not set, empty or not valid
                     return false;
                 }
             }
             else
             {   // no user is there
                 return false;
             }
         }
References $_GET, and $db.
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\init().
isTemplateEqual()
YAWK\user::isTemplateEqual ($db, $userTemplateID)
check if user template equals selected (active) template
Parameters
object $db Database
int $userTemplateID the user template ID
Returns
bool
Definition at line 517 of file user.php.
         {
             /* @param $db \YAWK\db */
             // check if userTemplateID param is set
             if (!isset($userTemplateID) && (empty($userTemplateID))) {   // missing templateID - cannot compare,
                 return false;
             }
             $selectedTemplate = \YAWK\settings::getSetting($db, "selectedTemplate");
             if ($selectedTemplate === $userTemplateID) {   // user templateID and primary template (selectedTemplate) are equal
                 return true;
             } else {   // user templateID and selected template do not match
                 return false;
             }
         }
References $db, $userTemplateID, and YAWK\settings\getSetting().
sendResetEmail()
static YAWK\user::sendResetEmail ($db, $username, $email, $lang) static
Send password change request email.
Parameters
object $db database obj
string $username username from pwd reset form
string $email email from pwd reset from
object $lang language obj
Returns
bool true|false
Definition at line 230 of file user.php.
         {
             // first of all we check if user entered a correct username or email string.
             // afterwards, we get the UID for this user and store a personal hash value
             // user will get an email, containing a link with the hash to the form where
             // he can set his new password. If hash matches, password change is possible.
             // Until this last step he can still login with his old credentials - password
             // in database will not be touched until he enters a new one.
             // get UID from username
             if (isset($username) && (!empty($username) && (is_string($username)))) {
                 // user wants to reset with his username
                 $username = trim($username);
                 $username = strip_tags($username);
                 // get user id from username
                 $uid = self::getUserIdFromName($db, $username);
             }
             // or get UID from email
             else if (isset($email) && (!empty($email) && (is_string($email))))
             {
                 // user wants to reset with his email
                 $email = trim($email);
                 $email = strip_tags($email);
                 $uid = self::getUserIdFromEmail($db, $email);
             }
             else
             {
                 \YAWK\alert::draw("warning", $lang['WARNING'], $lang['USERNAME_OR_EMAIL_NOT_SET'], "", 3800);
                 return false;
             }
             // check if UID is valid
             if (empty($uid) || (!is_numeric($uid)))
             {   // throw error - UID is not valid
                 \YAWK\alert::draw("danger", $lang['ERROR'], $lang['PASSWORD_RESET_UID_FAILED'], "", 3800);
                 return false;
             }
             else
             {   // uid is valid, go ahead and generate hash value
                 $token = self::getToken(196);
                 // store token in database
                 if ($res = $db->query("UPDATE {users} SET hashValue = '".$token."' WHERE id = '".$uid."'"))
                 {
                     // get user email address
                     if (!isset($email) || (empty($email)))
                     {
                         // get email address of this user
                         $to = \YAWK\user::getUserEmail($db, $username);
                     }
                     else
                     {   // password recipient
                         $to = $email;
                         // get username
                         $username = self::getUserNameFromID($db, $uid);
                     }
                     // get admin email address
                     $from = \YAWK\settings::getSetting($db, "admin_email");
                     // check if $to is a valid email address
                     if (filter_var($to, FILTER_VALIDATE_EMAIL))
                     {
                         // get full url to build the link
                         $url = \YAWK\sys::getHost($db);
                         // append token and generate complete url
                         $firstCharOfUrl = mb_substr($url, 0,-1);
                         if ($firstCharOfUrl === "/")
                         {   // url missing trailing slash, append it
                             $tokenLink = $url."/index.php?resetPassword=true&token=$token";
                         }
                         else
                         {   // url still got a slash
                             $tokenLink = $url."index.php?resetPassword=true&token=$token";
                         }
                         $mailBody = "$lang[HELLO] $username!\n\r$lang[PASSWORD_RESET_REQUESTED]\n\r$lang[PASSWORD_RESET_MAILBODY]\n\r".$tokenLink."\n\r$lang[PASSWORD_RESET_REQUEST_WARNING].";
                         if (\YAWK\email::sendEmail($from, $to, "", "$lang[PASSWORD_RESET] $url", $mailBody) === true)
                         {   // reset password email sent
                             \YAWK\sys::setSyslog($db, 9, 0, "reset password email requested from $username ($to)", $uid, 0, 0, 0);
                             $_SESSION['passwordFail'] = 0;
                             return true;
                         }
                         else
                         {   // FAILED to send password reset email
                             \YAWK\alert::draw("warning", $lang['ERROR'], "$lang[EMAIL_NOT_SENT] <br>(from: $from)<br>(to: $to)", "", 3800);
                             \YAWK\sys::setSyslog($db, 11, 1, "failed to send reset password email to $username ($to)", $uid, 0, 0, 0);
                             return false;
                         }
                     }
                     else
                     {   // NOT VALID EMAIL ADDRESS (to:)
                         \YAWK\alert::draw("warning", $lang['ERROR'], $lang['EMAIL_ADD_INVALID'], "", 3800);
                         \YAWK\sys::setSyslog($db, 11, 1, "invalid email address $to", $uid, 0, 0, 0);
                         return false;
                     }
                 }
                 else
                 {   // error: hash value could not be stored / updated in database
                     \YAWK\sys::setSyslog($db, 11, 1, "failed to update hash value in database", $uid, 0, 0, 0);
                     \YAWK\alert::draw("warning", "Hash Value", "could not be stored.", "", 3800);
                     return false;
                 }
             }
         }
References $db, YAWK\user\$email, $lang, $res, $uid, YAWK\user\$url, YAWK\user\$username, YAWK\alert\draw(), YAWK\sys\getHost(), YAWK\settings\getSetting(), YAWK\user\getToken(), YAWK\user\getUserEmail(), and YAWK\email\sendEmail().
setNewPassword()
static YAWK\user::setNewPassword ($db, $newPassword, $uid) static
Set a new user password.
Parameters
string $newPassword The new password that will be stored in the database
int $uid The affected user id
object $db database obj
Definition at line 187 of file user.php.
         {
             // check if new password is set and valid
             if (isset($newPassword) && (!empty($newPassword)) && (is_string($newPassword)))
             {   // check if uid is set and valid
                 if (isset($uid) && (!empty($uid)) && (is_numeric($uid)))
                 {
                     // hash password
                     $newPassword = md5($newPassword);
                     // update database - change password
                     if ($res = $db->query("UPDATE {users} SET password = '".$newPassword."' WHERE id = '".$uid."'"))
                     {   // password changed successfully
                         \YAWK\sys::setSyslog($db, 9, 0, "user $uid changed his password", $uid, 0, 0, 0);
                         return true;
                     }
                     else
                     {   // password cannot be changed
                         \YAWK\sys::setSyslog($db, 11, 1, "failed to update password of user $uid ", $uid, 0, 0, 0);
                         return false;
                     }
                 }
                 else
                 {   // uid not set or not valid
                     \YAWK\sys::setSyslog($db, 11, 1, "uid not set, empty or wrong datatype", $uid, 0, 0, 0);
                     return false;
                 }
             }
             else
             {   // new password not set or not valid
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to update user password: new password not set, empty or not valid", $uid, 0, 0, 0);
                 return false;
             }
         }
References $db, $res, and $uid.
Referenced by YAWK\controller\filterfilename().
setUserTemplate()
YAWK\user::setUserTemplate ($db, $overrideTemplate, $userTemplateID, $uid)
set status and override template for this user ID
Parameters
object $db database
int $overrideTemplate 0|1 1 if template could be overridden by this user
int $userTemplateID the template ID you wish to set for this user
int $uid user ID
Returns
bool
Definition at line 485 of file user.php.
         {   /* @param $db \YAWK\db */
             if (!isset($overrideTemplate) && (!is_numeric($overrideTemplate)))
             {   // wrong param
                 return false;
             }
             if (!isset($userTemplateID) && (!is_numeric($userTemplateID)))
             {   // wrong param
                 return false;
             }
             if (!isset($uid) && (!is_numeric($uid)))
             {   // wrong param
                 return false;
             }
             if ($res = $db->query("UPDATE {users} SET overrideTemplate = $overrideTemplate, templateID = $userTemplateID WHERE id = $uid"))
             {
                 return true;
             }
             else
             {
                 \YAWK\sys::setSyslog($db, 11, 1, "failed to update user template override - template ID: $userTemplateID", $uid, 0, 0, 0);
                 return false;
             }
         }
References $db, YAWK\user\$overrideTemplate, $res, $uid, and $userTemplateID.
Member Data Documentation
$blocked
YAWK\user::$blocked
Parameters
int 0|1 if 1, user is blocked and cannot login anymore
Definition at line 23 of file user.php.
$city
YAWK\user::$city
Parameters
string city
Definition at line 63 of file user.php.
$country
YAWK\user::$country
Parameters
string country
Definition at line 65 of file user.php.
$currentuser
YAWK\user::$currentuser
Parameters
string current user name
Definition at line 19 of file user.php.
$date_changed
YAWK\user::$date_changed
Parameters
string datetime when user has changed
Definition at line 39 of file user.php.
$date_created
YAWK\user::$date_created
Parameters
string datetime when user was created
Definition at line 37 of file user.php.
$date_expired
YAWK\user::$date_expired
Parameters
string datetime when user account is about to expire
Definition at line 43 of file user.php.
$date_lastlogin
YAWK\user::$date_lastlogin
Parameters
string datetime when user has last logged in
Definition at line 41 of file user.php.
$email
YAWK\user::$email
Parameters
string user email address
Definition at line 47 of file user.php.
Referenced by YAWK\user\getUserList(), and YAWK\user\sendResetEmail().
$facebook
YAWK\user::$facebook
Parameters
string user facebook url
Definition at line 53 of file user.php.
$firstname
YAWK\user::$firstname
Parameters
string user firstname
Definition at line 55 of file user.php.
$gid
YAWK\user::$gid
Parameters
int group ID
Definition at line 33 of file user.php.
$id
YAWK\user::$id
Parameters
int user ID
Definition at line 25 of file user.php.
$job
YAWK\user::$job
Parameters
string job description - can held any string
Definition at line 67 of file user.php.
$lastlogin
YAWK\user::$lastlogin
Parameters
string datetime when user has last logged in
Definition at line 69 of file user.php.
$lastname
YAWK\user::$lastname
Parameters
string user lastname
Definition at line 57 of file user.php.
$likes
YAWK\user::$likes
Parameters
int how many likes the user has achieved
Definition at line 75 of file user.php.
$logged_in
YAWK\user::$logged_in
Parameters
int 0|1 user is currently logged in - or at least: not logged out
Definition at line 73 of file user.php.
$login_count
YAWK\user::$login_count
Parameters
int how many times the user have logged in
Definition at line 45 of file user.php.
$online
YAWK\user::$online
Parameters
int 0|1 if 1, user is currently online (or at least: not logged out)
Definition at line 31 of file user.php.
$overrideTemplate
YAWK\user::$overrideTemplate
Parameters
int override the current template ID
Definition at line 77 of file user.php.
Referenced by YAWK\user\setUserTemplate().
$password
YAWK\user::$password
Parameters
string user password
Definition at line 35 of file user.php.
Referenced by YAWK\user\ajaxLogin(), YAWK\user\drawLoginBox(), and YAWK\user\drawMenuLoginBox().
$privacy
YAWK\user::$privacy
Parameters
int 0|1 if 1, user privacy needs to be respected
Definition at line 29 of file user.php.
$public_email
YAWK\user::$public_email
Parameters
int 0|1 1 means the email is public and can be shown on the website
Definition at line 71 of file user.php.
$published
YAWK\user::$published
Parameters
int 0|1 if 1, user is published (active)
Definition at line 27 of file user.php.
$street
YAWK\user::$street
Parameters
string street
Definition at line 59 of file user.php.
$templateID
YAWK\user::$templateID
Parameters
int current template ID
Definition at line 79 of file user.php.
$twitter
YAWK\user::$twitter
Parameters
string user twitter url
Definition at line 51 of file user.php.
$url
YAWK\user::$url
Parameters
string user URL
Definition at line 49 of file user.php.
Referenced by YAWK\user\sendResetEmail().
$username
YAWK\user::$username
Parameters
string username
Definition at line 21 of file user.php.
Referenced by YAWK\user\getUserList(), and YAWK\user\sendResetEmail().
$zipcode
YAWK\user::$zipcode
Parameters
string zip code
Definition at line 61 of file user.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/user.php