YaWK: YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive Class Reference
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive Class Reference
Embed CBA (Cultural Broadcasting Archive) Podcast Player.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embed ()
init ()
Initialize: prepare proerties and load javascript.
printObject ()
Print all object data.
setProperties ()
Public Attributes
$cbaDescription = ''
$cbaEmbedCode = ''
$cbaHeading = ''
$cbaHeadline = ''
$cbaHeight = ''
$cbaMeta = ''
$cbaPodcast = ''
$cbaSeries = ''
$cbaSocialmedia = ''
$cbaSource = ''
$cbaSubtext = ''
$cbaTitle = ''
$cbaUrl = ''
$cbaWaveform = ''
$cbaWidth = ''
$widget = ''
Detailed Description
Embed CBA (Cultural Broadcasting Archive) Podcast Player.
Embed audio player from cultural broadcasting archive.
Cultural Broadcasting Archive is an austrian podcast archive. You can embed any public broadcast and set a few settings like player details, waveform display, social media links and much more. All you need to embed a player, is the URL to the cba podcast.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file culturalbroadcasting.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 57 of file culturalbroadcasting.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embed()
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::embed ()
Definition at line 182 of file culturalbroadcasting.php.
         {
             if (isset($cbaEmbedCode) && (!empty($cbaEmbedCode)))
             {
                 echo $this->cbaHeadline;
                 echo $cbaEmbedCode;
             }
             else
             {
                 $this->cbaSource = $this->cbaUrl."/embed?".$this->cbaWaveform.$this->cbaTitle.$this->cbaSocialmedia.$this->cbaPodcast.$this->cbaSeries.$this->cbaDescription.$this->cbaMeta;
                 // HTML output
                 echo "
                 <!-- cba stream iframe -->
                 $this->cbaHeadline
                 <iframe width=\"$this->cbaWidth\"
                         height=\"$this->cbaHeight\"
                         src=\"$this->cbaSource\"
                         frameborder=\"0\"
                         scrolling=\"no\"
                         style=\"border:none; width:$this->cbaWidth; height:$this->cbaHeight;\">
                 </iframe>";
             }
References YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\$cbaEmbedCode, and YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\$cbaHeadline.
Referenced by YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\init().
init()
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::init ()
Initialize: prepare proerties and load javascript.
use this method to run the clock
Definition at line 82 of file culturalbroadcasting.php.
         {
             $this->setProperties();
             $this->embed();
References YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\embed(), and YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\setProperties().
printObject()
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 71 of file culturalbroadcasting.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
setProperties()
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::setProperties ()
Definition at line 88 of file culturalbroadcasting.php.
         {
             // if a heading is set and not empty
             if (isset($this->cbaHeading) && (!empty($this->cbaHeading)))
             {   // add a h1 tag to heading string
                 $this->cbaHeading = "$this->cbaHeading";
                 // if subtext is set, add <small> subtext to string
                 if (isset($this->cbaSubtext) && (!empty($this->cbaSubtext)))
                 {   // build a headline with heading and subtext
                     $this->cbaSubtext = "<small>$this->cbaSubtext</small>";
                     $this->headline = "<h1>$this->cbaHeading&nbsp;"."$this->cbaSubtext</h1>";
                 }
                 else
                 {   // build just a headline - without subtext
                     $this->headline = "<h1>$this->cbaHeading</h1>";    // draw just the heading
                 }
             }
             else
             {   // leave empty if it's not set
                 $this->headline = '';
             }
             /* check if waveform is set to true or false */
             if ($this->cbaWaveform === "1")
             {
                 $this->cbaWaveform = "&waveform=true";
             }
             else
             {   /* waveform false: adjust height correctly */
                 $this->cbaWaveform = "&waveform=false";
             }
             /* is a title set? */
             if ($this->cbaTitle === "1")
             {
                 $this->cbaTitle = "&title=true";
             }
             else
             {
                 $this->cbaTitle = "&title=false";
             }
             /* is socialmedia set? */
             if ($this->cbaSocialmedia === "1")
             {
                 $this->cbaSocialmedia = "&socialmedia=true";
             }
             else
             {
                 $this->cbaSocialmedia = "&socialmedia=false";
             }
             /* is series set? */
             if ($this->cbaSeries === "1")
             {
                 $this->cbaSeries = "&series_link=true";
             }
             else
             {
                 $this->cbaSeries = "&series_link=false";
             }
             /* is podcast set? */
             if ($this->cbaPodcast === "1")
             {
                 $this->cbaPodcast = "&subscribe=true";
             }
             else
             {
                 $this->cbaSeries = "&subscribe=false";
             }
             /* is description set? */
             if ($this->cbaDescription === "1")
             {
                 $this->cbaDescription = "&description=true";
             }
             else
             {
                 $this->cbaDescription = "&description=false";
             }
             /* is meta set? */
             if ($this->cbaMeta === "1")
             {
                 $this->cbaMeta = "&meta=true";
             }
             else
             {
                 $this->cbaMeta = "&meta=false";
             }
Referenced by YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\init().
Member Data Documentation
$cbaDescription
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaDescription = ''
Parameters
string Description
Definition at line 44 of file culturalbroadcasting.php.
$cbaEmbedCode
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaEmbedCode = ''
Parameters
string Embed Code
Definition at line 48 of file culturalbroadcasting.php.
Referenced by YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\embed().
$cbaHeading
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaHeading = ''
Parameters
string Heading
Definition at line 26 of file culturalbroadcasting.php.
$cbaHeadline
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaHeadline = ''
Parameters
string Headline
Definition at line 24 of file culturalbroadcasting.php.
Referenced by YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\embed().
$cbaHeight
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaHeight = ''
Parameters
string Height
Definition at line 30 of file culturalbroadcasting.php.
$cbaMeta
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaMeta = ''
Parameters
string Meta Tags
Definition at line 46 of file culturalbroadcasting.php.
$cbaPodcast
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaPodcast = ''
Parameters
string Podcast
Definition at line 40 of file culturalbroadcasting.php.
$cbaSeries
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaSeries = ''
Parameters
string Series
Definition at line 42 of file culturalbroadcasting.php.
$cbaSocialmedia
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaSocialmedia = ''
Parameters
string Socialmedia Links
Definition at line 38 of file culturalbroadcasting.php.
$cbaSource
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaSource = ''
Parameters
string Source URL
Definition at line 50 of file culturalbroadcasting.php.
$cbaSubtext
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaSubtext = ''
Parameters
string Subtext
Definition at line 28 of file culturalbroadcasting.php.
$cbaTitle
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaTitle = ''
Parameters
string CBA Title
Definition at line 36 of file culturalbroadcasting.php.
$cbaUrl
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaUrl = ''
Parameters
string cba podcast URL
Definition at line 22 of file culturalbroadcasting.php.
$cbaWaveform
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaWaveform = ''
Parameters
string Display waveform?
Definition at line 34 of file culturalbroadcasting.php.
$cbaWidth
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$cbaWidth = ''
Parameters
string Width
Definition at line 32 of file culturalbroadcasting.php.
$widget
YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file culturalbroadcasting.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/culturalbroadcasting/classes/culturalbroadcasting.php