YaWK: YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox Class Reference
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox Class Reference
Loginbox Widget.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
drawLoginBox ($db, $username, $password)
returns the login box html markup
drawLogoutButton ($db)
returns the logout btn html markup
includeJS ()
Load required javascript file.
init ($db)
Init loginbox widget and call a function for demo purpose.
setLoginProperties ()
Prepare Loginbox form settings.
setLogoutProperties ()
Set properties of greeting and logout button.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$currentUser = ''
$loginboxFormClass = ''
$loginboxFormClassMarkup = ''
$loginboxGreeting = ''
$loginboxGreetingMarkup = ''
$loginboxGreetingShowName = 'true'
$loginboxGreetingSubtext = ''
$loginboxGreetingText = ''
$loginboxGreetingTextClass = ''
$loginboxGreetingTextClassMarkup = ''
$loginboxGreetingTextType = 'h2'
$loginboxHeading = ''
$loginboxLoginBtnClass = "btn btn-success"
$loginboxLoginBtnMarginMarkup = ''
$loginboxLoginBtnMarginTop = "5px"
$loginboxLoginBtnText = "Login"
$loginboxLogoutBtnClass = "btn btn-danger"
$loginboxLogoutBtnMarkup = ""
$loginboxLogoutBtnText = "Logout"
$loginboxProcessingMode = 'html'
$loginboxProcessingModeFormMarkup = ''
$loginboxProcessingModeSubmitBtnType = 'submit'
$loginboxRedirect = ''
$loginboxRedirectTime = 0
$loginboxSubtext = ''
$loginboxWidth = ''
$loginboxWidthMarkup = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Loginbox Widget.
Loginbox - draw a loginbox (or logout button)
In case you need a user login form, use this widget. If the user is not logged in, a form will be displayed, requesting username and password where users can login. In case the user is already logged in, a hello {user}! message will be displayed, followed by a logout button
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file loginbox.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 81 of file loginbox.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawLoginBox()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::drawLoginBox ($db, $username, $password)
returns the login box html markup
Parameters
object $db database object
string $username username, as option
string $password password, as option
Definition at line 280 of file loginbox.php.
         {
             // first of all: get settings for this loginbox
             $this->setLoginProperties();
             // bootstrap layout markup
             echo "<div class=\"col-md-12\"".$this->loginboxLoginBtnMarginMarkup.">";
             // draw heading above loginbox
             echo "<div id=\"heading\">";
             echo $this->getHeading($this->loginboxHeading, $this->loginboxSubtext);
             echo "</div>";
             // draw loginbox
             echo"<form name=\"login\" ".$this->loginboxProcessingModeFormMarkup.$this->loginboxFormClassMarkup." id=\"loginForm\" role=\"form\" method=\"POST\"".$this->loginboxWidthMarkup.">
                     <input type=\"text\" id=\"user\" name=\"user\" value=\"".$username."\" class=\"form-control\" placeholder=\"Benutzername\">
                     <input type=\"password\" id=\"password\" name=\"password\" value=\"".$password."\" class=\"form-control\" placeholder=\"Passwort\">
                     <input type=\"hidden\" name=\"login\" value=\"login\">
                     <input type=\"hidden\" id=\"loginboxRedirect\" name=\"loginboxRedirect\" value=\"".$this->loginboxRedirect."\">
                     <input type=\"hidden\" id=\"loginboxRedirectTime\" name=\"loginboxRedirectTime\" value=\"".$this->loginboxRedirectTime."\">
                     <input type=\"hidden\" id=\"loginboxLogoutBtnText\" name=\"logoutBtnText\" value=\"".$this->loginboxLogoutBtnText."\">
                     <input type=\"hidden\" id=\"loginboxLogoutBtnClass\" name=\"logoutBtnClass\" value=\"".$this->loginboxLogoutBtnClass."\">
                     <input type=\"hidden\" id=\"loginboxGreeting\" name=\"loginboxGreeting\" value=\"".$this->loginboxGreeting."\">
                     <input type=\"hidden\" id=\"loginboxGreetingText\" name=\"loginboxGreetingText\" value=\"".$this->loginboxGreetingText."\">
                     <input type=\"hidden\" id=\"loginboxGreetingTextType\" name=\"loginboxGreetingTextType\" value=\"".$this->loginboxGreetingTextType."\">
                     <input type=\"hidden\" id=\"loginboxGreetingTextClass\" name=\"loginboxGreetingTextClass\" value=\"".$this->loginboxGreetingTextClass."\">
                     <input type=\"hidden\" id=\"loginboxGreetingSubtext\" name=\"loginboxGreetingSubtext\" value=\"".$this->loginboxGreetingSubtext."\">
                     <input type=\"hidden\" id=\"loginboxGreetingShowName\" name=\"loginboxGreetingShowName\" value=\"".$this->loginboxGreetingShowName."\">
                     <input type=\"".$this->loginboxProcessingModeSubmitBtnType."\" name=\"submit\" id=\"submit\" class=\"$this->loginboxLoginBtnClass\" value=\"$this->loginboxLoginBtnText\"".$this->loginboxLoginBtnMarginMarkup.">
                 </form>
                 <div id=\"thankYouMessage\"></div>
             </div>";
References $password, $username, YAWK\widget\getHeading(), and YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\setLoginProperties().
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\init().
drawLogoutButton()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::drawLogoutButton ($db)
returns the logout btn html markup
Definition at line 317 of file loginbox.php.
         {
             // get logout button settings
             $this->setLogoutProperties();
             echo "
             <div class=\"col-md-12\">
                 ".$this->loginboxGreetingMarkup."
             </div>";
References YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\setLogoutProperties().
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\init().
includeJS()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::includeJS ()
Load required javascript file.
include required ajax js file
Definition at line 258 of file loginbox.php.
         {
             // load notify js
             echo "<script type=\"text/javascript\" src=\"system/engines/jquery/notify/bootstrap-notify.min.js\"></script>";
             echo "<link rel=\"stylesheet\" href=\"system/engines/jquery/notify/bootstrap-notify.min.css\">";
             // load validate js
             echo "<script type=\"text/javascript\" src=\"system/engines/jquery/jquery.validate.min.js\"></script>";
             // if current language is german
             if (\YAWK\language::getCurrentLanguageStatic() == "de-DE")
             {   // load german language file
                 echo "<script type=\"text/javascript\" src=\"system/engines/jquery/messages_de.min.js\"></script>";
             }
             // load ajax file
             echo "<script type=\"text/javascript\" src=\"system/widgets/loginbox/js/loginbox.ajax.min.js\"></script>";
References YAWK\language\getCurrentLanguageStatic().
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\setLoginProperties().
init()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::init ($db)
Init loginbox widget and call a function for demo purpose.
loginbox Widget Init
Definition at line 95 of file loginbox.php.
         {
             // check if a user is there
             if ($this->currentUser = \YAWK\user::isAnybodyThere($db))
             {   // check if currentUser is logged in
                 if (\YAWK\user::isLoggedIn($db, $this->currentUser))
                 {
                     // user is logged in...
                     $this->drawLogoutButton($db);
                 }
                 else
                     {   // user is not logged in, draw loginbox
                         $this->drawLoginBox($db, $this->currentUser, "");
                     }
             }
             else
                 {   // no user is there, draw loginbox
                     $this->drawLoginBox($db, "", "");
                 }
References $db, YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\drawLoginBox(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\drawLogoutButton(), and YAWK\user\isAnybodyThere().
setLoginProperties()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::setLoginProperties ()
Prepare Loginbox form settings.
Evaluate loginbox settings and prepare html markup
MARGIN TOP
FORM WIDTH
FORM CLASS
FORM PROCESSING MODE
Definition at line 120 of file loginbox.php.
         {
             /** MARGIN TOP */
             // check if loginbox button margin top is set and not empty
             if (isset($this->loginboxLoginBtnMarginTop) && (!empty($this->loginboxLoginBtnMarginTop)))
             {   // check last 2 chars of string to see if user missed px afterwards
                 if (substr($this->loginboxLoginBtnMarginTop, -2) != "px")
                 {   // append px to value
                     $this->loginboxLoginBtnMarginTop = $this->loginboxLoginBtnMarginTop."px";
                 }
                 // generate css style markupd
                 $this->loginboxLoginBtnMarginMarkup = " style=\"margin-top:$this->loginboxLoginBtnMarginTop;\"";
             }
             else
             {   // no markup required
                 $this->loginboxLoginBtnMarginMarkup = '';
             }
             /** FORM WIDTH */
             // check if form width is set and not empty
             if (isset($this->loginboxWidth) && (!empty($this->loginboxWidth)))
             {
                 // check last char of string to see if user missed % sign
                 if (substr($this->loginboxWidth, -1) != "%")
                 {   // append percent sign
                     $this->loginboxWidth = $this->loginboxWidth."%";
                 }
                 // generate css style markup
                 $this->loginboxWidthMarkup = " style=\"width:$this->loginboxWidth;\"";
                 // check if width is set to 100%
                 if ($this->loginboxWidth === "100%" || $this->loginboxWidth === "100" || ($this->loginboxWidth === "0"))
                 {   // default behaviour, no markup needed
                     $this->loginboxWidthMarkup = '';
                 }
             }
             else
             {   // no markup required
                 $this->loginboxWidthMarkup = '';
             }
             /** FORM CLASS */
             // check form class
             if (isset($this->loginboxFormClass) && (!empty($this->loginboxFormClass)))
             {
                 // generate form class markup
                 $this->loginboxFormClassMarkup = " class=\"$this->loginboxFormClass\"";
             }
             else
             {   // no markup required
                 $this->loginboxFormClassMarkup = '';
             }
             /** FORM PROCESSING MODE */
             // check form processing mode (ajax or html)
             if (isset($this->loginboxProcessingMode) && (!empty($this->loginboxProcessingMode)))
             {   // if form processing is html
                 if ($this->loginboxProcessingMode === "html")
                 {   // set form markup html action....
                     $this->loginboxProcessingModeFormMarkup = " action=\"index.html\" ";
                     $this->loginboxProcessingModeSubmitBtnType = "submit";
                 }
                 else
                 {   // ajax request - load required js files
                     $this->includeJS();
                     // no additional form markup required
                     $this->loginboxProcessingModeFormMarkup = "";
                     // set submit btn type to prevent 'traditional' submit behavior
                     $this->loginboxProcessingModeSubmitBtnType = "submit";
                 }
             }
References YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\includeJS().
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\drawLoginBox().
setLogoutProperties()
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::setLogoutProperties ()
Set properties of greeting and logout button.
set properties of greeting and logout button
GREETING TEXT MARKUP
LOGOUT BUTTON MARKUP
SET GREETING AND LOGOUT BUTTON
Definition at line 197 of file loginbox.php.
         {
             /** GREETING TEXT MARKUP */
             // check text type (H1-H6 / globaltext)
             if (isset($this->loginboxGreetingTextType) && ($this->loginboxGreetingTextType === "GLOBALTEXT"))
             {   // set paragraph as default text type
                 $this->loginboxGreetingTextType = "p";
             }
             // check greeting text css class
             if (isset($this->loginboxGreetingTextClass) && (!empty($this->loginboxGreetingTextClass)))
             {   // only add class if it is not empty
                 $this->loginboxGreetingTextClassMarkup = ' class="'.$this->loginboxGreetingTextClass.'"';
             }
             else
             {   // no markup needed
                 $this->loginboxGreetingTextClassMarkup = '';
             }
             /** LOGOUT BUTTON MARKUP */
             if (isset($this->loginboxRedirect) && (!empty($this->loginboxRedirect)))
             {
                 // prepare redirect url
                 $this->loginboxRedirect = rawurlencode($this->loginboxRedirect);
                 // logout button with redirect url
                 $this->loginboxLogoutBtnMarkup = '<a href="logout" id="logoutBtn" style="margin-top:'.$this->loginboxLoginBtnMarginTop.'" class="'.$this->loginboxLogoutBtnClass.'" target="_self">'.$this->loginboxLogoutBtnText.'</a>';
             }
             else
                 {   // logout button without redirect url
                     $this->loginboxLogoutBtnMarkup = '<a href="logout" id="logoutBtn" style="margin-top:'.$this->loginboxLoginBtnMarginTop.'" class="'.$this->loginboxLogoutBtnClass.'" target="_self">'.$this->loginboxLogoutBtnText.'</a>';
                 }
             /** SET GREETING AND LOGOUT BUTTON */
             // maximum greeting
             if ($this->loginboxGreeting === "greeting-max")
             {   // do a personal greeting with username
                     $this->loginboxGreetingMarkup = '<'.$this->loginboxGreetingTextType.$this->loginboxGreetingTextClassMarkup.'>'.$this->loginboxGreetingText.' '.$this->currentUser.' <small>'.$this->loginboxGreetingSubtext.'</small></'.$this->loginboxGreetingTextType.'>'.$this->loginboxLogoutBtnMarkup.'';
             }
             // minimal greeting
             if ($this->loginboxGreeting === "greeting-min")
             {   // greeting without name
                 $this->loginboxGreetingMarkup = '<'.$this->loginboxGreetingTextType.$this->loginboxGreetingTextClassMarkup.'>'.$this->loginboxGreetingText.' <small>'.$this->loginboxGreetingSubtext.'</small></'.$this->loginboxGreetingTextType.'>'.$this->loginboxLogoutBtnMarkup.'';
             }
             // no greeting, just a logout button
             if ($this->loginboxGreeting === "greeting-button")
             {   // display logout button
                 $this->loginboxGreetingMarkup = $this->loginboxLogoutBtnMarkup;
             }
             // no greeting, silent login mode
             if ($this->loginboxGreeting === "greeting-none")
             {   // no welcome message - do nothing
                 $this->loginboxGreetingMarkup = '';
             }
References YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\$loginboxLogoutBtnMarkup.
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\drawLogoutButton().
Member Data Documentation
$currentUser
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$currentUser = ''
Parameters
string Username
Definition at line 26 of file loginbox.php.
$loginboxFormClass
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxFormClass = ''
Parameters
string form css class
Definition at line 46 of file loginbox.php.
$loginboxFormClassMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxFormClassMarkup = ''
Parameters
string form css class markup
Definition at line 48 of file loginbox.php.
$loginboxGreeting
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreeting = ''
Parameters
bool true|false Turn greeting on or off
Definition at line 56 of file loginbox.php.
$loginboxGreetingMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingMarkup = ''
Parameters
string Greeting html markup
Definition at line 60 of file loginbox.php.
$loginboxGreetingShowName
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingShowName = 'true'
Parameters
bool true|false Show name within greeting?
Definition at line 64 of file loginbox.php.
$loginboxGreetingSubtext
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingSubtext = ''
Parameters
string Greeting Subtext
Definition at line 62 of file loginbox.php.
$loginboxGreetingText
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingText = ''
Parameters
string Greeting Text
Definition at line 58 of file loginbox.php.
$loginboxGreetingTextClass
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingTextClass = ''
Parameters
string Greeting text class
Definition at line 68 of file loginbox.php.
$loginboxGreetingTextClassMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingTextClassMarkup = ''
Parameters
string Greeting text class html markup
Definition at line 70 of file loginbox.php.
$loginboxGreetingTextType
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxGreetingTextType = 'h2'
Parameters
string Greeting text type
Definition at line 66 of file loginbox.php.
$loginboxHeading
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 22 of file loginbox.php.
$loginboxLoginBtnClass
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLoginBtnClass = "btn btn-success"
Parameters
string Login Button CSS Class
Definition at line 34 of file loginbox.php.
$loginboxLoginBtnMarginMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLoginBtnMarginMarkup = ''
Parameters
string Login Button margin top css markup
Definition at line 40 of file loginbox.php.
$loginboxLoginBtnMarginTop
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLoginBtnMarginTop = "5px"
Parameters
string Login Button margin-top
Definition at line 38 of file loginbox.php.
$loginboxLoginBtnText
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLoginBtnText = "Login"
Parameters
string Login Button Text
Definition at line 28 of file loginbox.php.
$loginboxLogoutBtnClass
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLogoutBtnClass = "btn btn-danger"
Parameters
string Logout Button CSS Class
Definition at line 36 of file loginbox.php.
$loginboxLogoutBtnMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLogoutBtnMarkup = ""
Parameters
string Logout Button html markup
Definition at line 32 of file loginbox.php.
Referenced by YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\setLogoutProperties().
$loginboxLogoutBtnText
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxLogoutBtnText = "Logout"
Parameters
string Logout Button Text
Definition at line 30 of file loginbox.php.
$loginboxProcessingMode
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxProcessingMode = 'html'
Parameters
string ajax|html form processing mode
Definition at line 50 of file loginbox.php.
$loginboxProcessingModeFormMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxProcessingModeFormMarkup = ''
Parameters
string markup for html/ajax processing mode
Definition at line 52 of file loginbox.php.
$loginboxProcessingModeSubmitBtnType
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxProcessingModeSubmitBtnType = 'submit'
Parameters
string submit button type, depending on processing mode
Definition at line 54 of file loginbox.php.
$loginboxRedirect
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxRedirect = ''
Parameters
string redirect to this page after successful login
Definition at line 72 of file loginbox.php.
$loginboxRedirectTime
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxRedirectTime = 0
Parameters
int delay before redirecting
Definition at line 74 of file loginbox.php.
$loginboxSubtext
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 24 of file loginbox.php.
$loginboxWidth
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxWidth = ''
Parameters
string form width
Definition at line 42 of file loginbox.php.
$loginboxWidthMarkup
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$loginboxWidthMarkup = ''
Parameters
string form width css markup
Definition at line 44 of file loginbox.php.
$widget
YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file loginbox.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/loginbox/classes/loginbox.php