YaWK: YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample Class Reference
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample Class Reference
Facebook Graph API explorer widget - for demo and development purpose only!
Public Member Functions
__construct ($db)
basicOutput ()
checkAccessToken ()
checkApiObjectData ()
checkAppId ()
checkPageId ()
checkRequirements ()
drawGallery ()
loadJSSDK ()
makeApiCall ()
printApiObject ()
Public Attributes
$apiObject
$fbExampleAccessToken = ''
$fbExampleAppId = ''
$fbExampleEndDate = ''
$fbExampleFields = 'id,name,description,place,start_time,cover,maybe_count,attending_count,is_canceled'
$fbExampleGraphRequest = '/events/'
$fbExamplePageId = ''
$fbExampleStartDate = ''
$fbExampleType = 'future'
$fbExampleYearRange = '1'
$jsSDKLoaded = 'false'
$sinceDate = ''
$untilDate = ''
Detailed Description
Facebook Graph API explorer widget - for demo and development purpose only!
Use Facebook Graph API to get any data from a Facebook Page. Require App ID and Access Token.
This is just an empty example widget for development and demo purpose!
It is recommended to play around with the facebook graph explorer. You can set any api call and fields you like to play around and explore the resulting array. You can use this widget as base for your own facebook api projects.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file fbExample.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::__construct ($db)
Definition at line 47 of file fbExample.php.
     {
         // load this widget settings from db
         $widget = new \YAWK\widget();
         $settings = $widget->getWidgetSettingsArray($db);
         foreach ($settings as $property => $value)
         {
             $this->$property = $value;
         }
         // check if required settings are set
         $this->checkRequirements();
References $db, $settings, $value, and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkRequirements().
Member Function Documentation
basicOutput()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::basicOutput ()
Definition at line 265 of file fbExample.php.
     {
         $this->loadJSSDK();
         $this->makeApiCall();
         foreach ($this->apiObject['data'] as $property => $value) {
             echo "<b>$property </b>: $value<br>";
             foreach ($value as $entry => $key) {
                 echo "$entry : $key<br>";
                 if (is_array($key)) {
                     foreach ($key as $p => $v) {
                         echo "&nbsp;&nbsp;&nbsp;&nbsp;$p : $v<br>";
                         if (is_array($v)) {
                             foreach ($v as $a => $b) {
                                 echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$a : $b<br>";
                             }
                         }
                     }
                 }
             }
             echo "<br>";
         }
References $value, YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\loadJSSDK(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\makeApiCall().
checkAccessToken()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::checkAccessToken ()
Definition at line 86 of file fbExample.php.
     {
         if (isset($this->fbExampleAccessToken) && (!empty($this->fbExampleAccessToken)))
         {
             if (is_string($this->fbExampleAccessToken))
             {
                 return true;
             }
             else
             {
                 die ("Access token is set, but not a string value! Please check your access token.");
             }
         }
         else
         {
             die ("Access token is not set. Please add your access token. You can obtain it from http://developers.facebook.com");
         }
References die.
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkRequirements().
checkApiObjectData()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::checkApiObjectData ()
Definition at line 235 of file fbExample.php.
     {
         if (isset($this->apiObject['data']) && (!empty($this->apiObject['data'])))
         {
             return true;
         }
         else
             {
                 return false;
             }
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\printApiObject().
checkAppId()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::checkAppId ()
Definition at line 67 of file fbExample.php.
     {
         if (isset($this->fbExampleAppId) && (!empty($this->fbExampleAppId)))
         {
             if (is_numeric($this->fbExampleAppId))
             {
                 return true;
             }
             else
                 {
                     die ("app ID is set, but not a numeric value! Please check your app ID - it should contain numbers only.");
                 }
         }
         else
             {
                 die ("app ID is not set. Please add your app ID. You can obtain it from http://developers.facebook.com");
             }
References die.
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkRequirements(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\loadJSSDK().
checkPageId()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::checkPageId ()
Definition at line 104 of file fbExample.php.
     {
         if (isset($this->fbExamplePageId) && (!empty($this->fbExamplePageId)))
         {
             if (is_string($this->fbExamplePageId))
             {
                 return true;
             }
             /* to allow custom url requests, this is uncommented.
             else
             {
                 die ("Page ID is set, but not a string value! Please check your page ID.");
             }
             */
         }
         /* to allow custom url requests, this is uncommented.
         else
         {
             die ("Page ID is not set. Please add your page ID. The Page ID is: https://www.facebook.com/{YOURPAGEID}");
         }
         */
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkRequirements().
checkRequirements()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::checkRequirements ()
Definition at line 60 of file fbExample.php.
     {
         $this->checkAppId();
         $this->checkAccessToken();
         $this->checkPageId();
References YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkAccessToken(), YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkAppId(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkPageId().
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\__construct().
drawGallery()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::drawGallery ()
Definition at line 292 of file fbExample.php.
         {
             $this->loadJSSDK();
             $this->makeApiCall();
             if (isset($this->apiObject['data']) && (!empty($this->apiObject))) {
                 echo "<h1>Facebook Photo Albums</h1>";
                 foreach ($this->apiObject['data'] as $property => $value)
                 {
                     if ($value['name'] != "//Profile Pictures"
                     && ($value['name'] !=
                         != "//Cover Photos")
                     {
                     $fn = $value['picture']['data']['url'];
                     echo "<div class=\"col-md-2 text-center\">
                 <img src=\"$fn\" style=\"width:200px;\" class=\"img-responsive hvr-grow\"><h3>$value[name]
                 <small><i>($value[count])</i></small></h3><br>
                 </div>";
                     }
                     /*
                     foreach ($value['images'] as $photo)
                     {
                         echo "<pre>";
                         echo "<img src=\"".$photo['source']."\" class=\"img-responsive\">";
                         echo "</pre>";
                     }
                     */
 /*
                     echo "<br><br>$property : $value<br>";
                     if (is_array($value)) {
                         foreach ($value as $entry => $key) {
                             echo "$entry : $key <br>";
                             if (is_array($key)) {
                                 foreach ($key as $image) {
                                     echo "$key : $image<br>";
                                     if (is_array($key) || (is_array($image))) {
                                         foreach ($key as $arrayKey => $arrayValue) {
                                             echo "&nbsp;&nbsp;$arrayKey : $arrayValue<br>";
                                             if (is_array($arrayValue)) {
                                                 foreach ($arrayValue as $p => $v) {
                                                     echo "&nbsp;&nbsp;$p : $v<br>";
                                                 }
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
 */
                 }
             }
References $value, YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\loadJSSDK(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\makeApiCall().
loadJSSDK()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::loadJSSDK ()
Definition at line 127 of file fbExample.php.
     {   // check if fb JS SDK was loaded before
         if ($this->jsSDKLoaded == 'false')
         {   // check if app ID is set
             if ($this->checkAppId() == true)
             {
                 // include facebook SDK JS
                 echo "<script>
                 window.fbAsyncInit = function() {
                     FB.init({
                     appId      : '" . $this->fbExampleAppId . "',
                     xfbml      : true,
                     version    : 'v3.1'
                     });
                 FB.AppEvents.logPageView();
                 };
                 (function(d, s, id){
                     var js, fjs = d.getElementsByTagName(s)[0];
                     if (d.getElementById(id)) {return;}
                     js = d.createElement(s); js.id = id;
                     js.src = \"https://connect.facebook.net/en_US/sdk.js\";
                     fjs.parentNode.insertBefore(js, fjs);
                 }(document, 'script', 'facebook-jssdk'));
                 </script>";
                 $this->jsSDKLoaded = 'true';
             }
             else
                 {
                     die ("unable to include facebook js SDK - checkAppId failed. Please check your app ID in the widget settings!");
                 }
         }
References YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkAppId(), and die.
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\basicOutput(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\drawGallery().
makeApiCall()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::makeApiCall ()
Definition at line 161 of file fbExample.php.
     {
         // WHICH EVENTS TO DISPLAY?
         // evaluation of event type select field
         if ($this->fbExampleType == "all")
         {
             // ALL EVENTS (FUTURE + PAST)
             $this->sinceDate = date('Y-01-01', strtotime('-' . $this->fbExampleYearRange . ' years'));
             $this->untilDate = date('Y-01-01', strtotime('+' . $this->fbExampleYearRange . ' years'));
         }
         elseif ($this->fbExampleType == "future")
         {
             // UPCOMING EVENTS
             $this->sinceDate = date('Y-m-d');
             $this->untilDate = date('Y-12-31', strtotime('+' . $this->fbExampleYearRange . ' years'));
         }
         elseif ($this->fbExampleType == "past")
         {
             // PAST EVENTS
             $this->sinceDate = date('Y-01-01', strtotime('-' . $this->fbExampleYearRange . ' years'));
             $this->untilDate = date('Y-m-d');
         }
         else
         {   // IF NOT SET - use default:
             // UPCOMING EVENTS
             $this->sinceDate = date('Y-m-d');
             $this->untilDate = date('Y-12-31', strtotime('+' . $this->fbExampleYearRange . ' years'));
         }
         // IF START + END DATE IS SET
         if (isset($this->fbExampleStartDate) && (!empty($this->fbExampleStartDate))
             && (isset($this->fbExampleEndDate) && (!empty($this->fbExampleEndDate))))
         {
             $this->sinceDate = date($this->fbExampleStartDate);
             $this->untilDate = date($this->fbExampleEndDate);
         }
         // unix timestamp years
         $since_unix_timestamp = strtotime($this->sinceDate);
         $until_unix_timestamp = strtotime($this->untilDate);
         // check if pageID is set
         if (isset($this->fbExamplePageId) && (!empty($this->fbExamplePageId)))
         {
             // set markup for pageID string
             $pageIdMarkup = "{$this->fbExamplePageId}";
         }
         else
             {   // leave empty if no page id is given (to build custom graph string)
                 $this->fbExamplePageId = '';
             }
         // check if fields are set
         if (isset($this->fbExampleFields) && (!empty($this->fbExampleFields)))
         {   // set markup for api query string
             $fieldsMarkup = "&fields={$this->fbExampleFields}";
             if (empty($this->fbExamplePageId))
             {
                 $fieldsMarkup = "?fields={$this->fbExampleFields}";
             }
         }
         else
             {   // no fields wanted, leave markup empty
                 $fieldsMarkup = '';
             }
         // prepare API call
         // $json_link = "https://graph.facebook.com/v2.7/{$this->fbExamplePageId}{$this->fbExampleGraphRequest}?fields={$this->fields}&access_token={$this->fbExampleAccessToken}";
         $json_link = "https://graph.facebook.com/v3.1/{$this->fbExamplePageId}{$this->fbExampleGraphRequest}?access_token={$this->fbExampleAccessToken}&since={$since_unix_timestamp}&until={$until_unix_timestamp}" . $fieldsMarkup . "";
         // get json string
         $json = file_get_contents($json_link);
         // convert json to object
         return $this->apiObject = json_decode($json, true, 512, JSON_BIGINT_AS_STRING);
References date.
Referenced by YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\basicOutput(), YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\drawGallery(), and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\printApiObject().
printApiObject()
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::printApiObject ()
Definition at line 247 of file fbExample.php.
     {
         $this->makeApiCall();
         if ($this->checkApiObjectData() === true)
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
         }
         else
             {
                 echo "<pre>";
                 echo "Could not retrieve any data from Facebook. Please check your PageID, API request, field and date settings";
                 echo "</pre>";
                 exit;
             }
References YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\checkApiObjectData(), exit, and YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\makeApiCall().
Member Data Documentation
$apiObject
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$apiObject
Parameters
object api result (as object)
Definition at line 44 of file fbExample.php.
$fbExampleAccessToken
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleAccessToken = ''
Parameters
string your access token (secret word from developers.facebook.com)
Definition at line 24 of file fbExample.php.
$fbExampleAppId
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleAppId = ''
Parameters
string your app ID (from developers.facebook.com)
Definition at line 20 of file fbExample.php.
$fbExampleEndDate
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleEndDate = ''
Parameters
string user defined end date
Definition at line 34 of file fbExample.php.
$fbExampleFields
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleFields = 'id,name,description,place,start_time,cover,maybe_count,attending_count,is_canceled'
Parameters
string fields that should be selected from facebook graph
Definition at line 28 of file fbExample.php.
$fbExampleGraphRequest
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleGraphRequest = '/events/'
Parameters
string your graph request
Definition at line 26 of file fbExample.php.
$fbExamplePageId
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExamplePageId = ''
Parameters
string your page ID (http://facebook.com/{YOURPAGEID}
Definition at line 22 of file fbExample.php.
$fbExampleStartDate
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleStartDate = ''
Parameters
string user defined start date
Definition at line 32 of file fbExample.php.
$fbExampleType
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleType = 'future'
Parameters
string which events should be shown? future|past|all
Definition at line 36 of file fbExample.php.
$fbExampleYearRange
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$fbExampleYearRange = '1'
Parameters
string show events of this time range
Definition at line 30 of file fbExample.php.
$jsSDKLoaded
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$jsSDKLoaded = 'false'
Parameters
string true|false was the js SDK loaded?
Definition at line 42 of file fbExample.php.
$sinceDate
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$sinceDate = ''
Parameters
string events since this date (used for calc)
Definition at line 38 of file fbExample.php.
$untilDate
YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample::$untilDate = ''
Parameters
string events until this date (used for calc)
Definition at line 40 of file fbExample.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/fb_example/classes/fbExample.php