YaWK: YAWK\WIDGETS\BLOG\WIDGET\blogWidget Class Reference
YAWK\WIDGETS\BLOG\WIDGET\blogWidget Class Reference
Embed a blog on your website.
Public Member Functions
__construct ($db)
Load all widget settings on object init.
drawBlogWidget ($db)
Draw the blog.
init ($db)
Init Gallery and load methods.
printObject ()
Print all object data.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
Public Attributes
$blogHeading = ''
$blogID = ''
$blogLimitEntries = ''
$blogSubtext = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Embed a blog on your website.
Embed plugin: blog
This is the widget to the blog plugin. With this widget you can embed any blog that you you've created before using the blog plugin. Simply set the ID of the blog you would like to embed, setup your settings, choose the position and page where you like to display your blog and you're good to go.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2019 Daniel Retzl
Version
1.0.0
Definition at line 17 of file blogWidget.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::__construct ($db)
Load all widget settings on object init.
Load all widget settings from database and fill object
Parameters
object $db Database Object
Definition at line 39 of file blogWidget.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
         }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawBlogWidget()
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::drawBlogWidget ($db)
Draw the blog.
Parameters
db object Database object
(for development and testing purpose)
Parameters
$db \YAWK\db *
$widget \YAWK\widget
Definition at line 76 of file blogWidget.php.
         {
             /** @param $db \YAWK\db * */
             error_reporting(1);
             if (!isset($this->blogID) || (empty($this->blogID)))
             {
                 echo "Error: unable to load blog because there was no blog ID given.";
             }
             else
                 {   // include blog plugin base class
                     require_once 'system/plugins/blog/classes/blog.php';
             // include required JS files
             /* echo "<script type=\"text/javascript\" src=\"../../../plugins/blog/js/comments.js\"></script>
                   <script type=\"text/javascript\" src=\"../../../plugins/blog/js/voting.js\"></script>";
             */
                 /*
                  * FRONTEND BLOG PAGE
                  */
                 // create new blog object
                 $blog = new \YAWK\PLUGINS\BLOG\blog();
                 /* a blog can be called by GET variable or via page include */
                 // assign blog ID
                 $blog->blogid = $this->blogID;
                 // load global blog settings
                 $blog->loadBlogProperties($db, $blog->blogid);
                 // for debug purpose
                 // print_r($blog);
                 /* get templateID */
                 $templateID = \YAWK\template::getCurrentTemplateId($db);
                 // if blog is not offline, get entries from db + draw it on screen.
                 if ($blog->published != 0) {
                     /** @param $widget \YAWK\widget */
                     // get headline
                     $this->headline = $this->getHeading($this->blogHeading, $this->blogSubtext);
                     if (!isset($blog->itemid)) {
                         $blog->itemid = 0;
                     }
                     // load blog title
                     $blog->getTitle($db, $blog->blogid);
                     // check if full view is set
                     if (!isset($full_view)) {
                         $full_view = 0;
                     }
                     // load the blog entries into blog object
                     $blog->getFrontendEntries($db, $blog->blogid, $blog->itemid, $full_view, $this->blogLimitEntries);
                     // check footer setting and load it on demand
                     // if ($blog->getBlogProperty($db, $blog->blogid, "footer")) {
                     //     $blog->getFooter($db);
                     // }
                     // finally: draw the blog
                     print $blog->draw();
                     print "</div>";
                 }
                 else
                     {   // blog is not published, draw message
                         echo \YAWK\alert::draw("warning", "Entschuldigung!", "Dieser Bereich ist im Moment offline, da gerade daran gearbeitet wird. Bitte komm sp&auml;ter wieder.", "", "4800");
                     }
             }
         }
References $blog, YAWK\WIDGETS\BLOG\WIDGET\blogWidget\$blogID, $db, $templateID, YAWK\template\getCurrentTemplateId(), and YAWK\widget\getHeading().
Referenced by YAWK\WIDGETS\BLOG\WIDGET\blogWidget\init().
init()
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::init ($db)
Init Gallery and load methods.
load Javascript and draw image gallery
Definition at line 64 of file blogWidget.php.
         {
             // $this->printObject();
             $this->drawBlogWidget($db);
         }
References $db, and YAWK\WIDGETS\BLOG\WIDGET\blogWidget\drawBlogWidget().
printObject()
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::printObject ()
Print all object data.
(for development and testing purpose)
Reimplemented from YAWK\widget.
Definition at line 53 of file blogWidget.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
         }
Member Data Documentation
$blogHeading
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::$blogHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 24 of file blogWidget.php.
$blogID
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::$blogID = ''
Parameters
int Gallery ID
Definition at line 22 of file blogWidget.php.
Referenced by YAWK\WIDGETS\BLOG\WIDGET\blogWidget\drawBlogWidget().
$blogLimitEntries
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::$blogLimitEntries = ''
Parameters
int Limit Entries (if 0 all items will be displayed) This can overrule the global blog setting and has only impact to the specific blog widget
Definition at line 30 of file blogWidget.php.
$blogSubtext
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::$blogSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 26 of file blogWidget.php.
$widget
YAWK\WIDGETS\BLOG\WIDGET\blogWidget::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file blogWidget.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/blogWidget/classes/blogWidget.php