YaWK: YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover Class Reference
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover Class Reference
Facebook Cover widget - Embed current cover image from your Facebook page.
Public Member Functions
__construct ($db)
checkAccessToken ()
checkAppId ()
checkRequirements ()
drawCoverImage ()
loadJSSDK ()
makeApiCall ()
Public Attributes
$apiObject
$fbCoverAccessToken = ''
$fbCoverAppId = ''
$fbCoverImageAlt = ''
$fbCoverImageClass = ''
$fbCoverImageHeight = ''
$fbCoverImageStyle = ''
$fbCoverImageTitle = ''
$fbCoverImageWidth = ''
$jsSDKLoaded = 'false'
$settings
Detailed Description
Facebook Cover widget - Embed current cover image from your Facebook page.
Use Facebook Graph API to get you latest cover image of your Facebook Page. Require an App ID and a valid Access Token.
This widget shows always your current (newest / latest) cover image of your Facebook page. It is meant to be used as header on top of your template design - or wherever it makes sense.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file fbCover.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::__construct ($db)
fbCover constructor. Loads all widget settings
Parameters
$db
Definition at line 46 of file fbCover.php.
     {
         // create new widget object
         $widget = new \YAWK\widget();
         // load this widget settings from db into array
         $this->settings = $widget->getWidgetSettingsArray($db);
         // add settings to object property
         foreach ($this->settings as $property => $value)
         {
             $this->$property = $value;
         }
         // check if required settings are set
         $this->checkRequirements();
References $db, $value, and YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkRequirements().
Member Function Documentation
checkAccessToken()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::checkAccessToken ()
check if access token is set
Returns
bool return true or die with error message
Definition at line 98 of file fbCover.php.
     {   // check if access token is set and not empty
         if (isset($this->fbCoverAccessToken) && (!empty($this->fbCoverAccessToken)))
         {   // check if access token is a string
             if (is_string($this->fbCoverAccessToken))
             {   // ok...
                 return true;
             }
             else
             {   // access token is not a string - abort with error msg
                 die ("Access token is set, but not a string value! Please check your access token.");
             }
         }
         else
         {   // access token is not set or empty - abort with error msg
             die ("Access token is not set. Please add your access token. You can obtain it from http://developers.facebook.com");
         }
References die.
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkRequirements().
checkAppId()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::checkAppId ()
check if app id is set
Returns
bool return true or die with error message
Definition at line 75 of file fbCover.php.
     {   // check of app id is set and not empty
         if (isset($this->fbCoverAppId) && (!empty($this->fbCoverAppId)))
         {   // app id is set - check if its a number
             if (is_numeric($this->fbCoverAppId))
             {   // ok, seems good
                 return true;
             }
             else
                 {   // not a number - abort with error msg
                     die ("app ID is set, but not a numeric value! Please check your app ID - it should contain numbers only.");
                 }
         }
         else
             {   // app id not set or empty - abort with error msg
                 die ("app ID is not set. Please add your app ID. You can obtain it from http://developers.facebook.com");
             }
References die.
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkRequirements(), and YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\loadJSSDK().
checkRequirements()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::checkRequirements ()
call check app id and access token
Definition at line 65 of file fbCover.php.
     {
         $this->checkAppId();
         $this->checkAccessToken();
References YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkAccessToken(), and YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkAppId().
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\__construct().
drawCoverImage()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::drawCoverImage ()
Draws the cover image onto screen.
Definition at line 186 of file fbCover.php.
     {
         $this->loadJSSDK();
         $this->makeApiCall();
         // check if image class is set
         if (isset($this->fbCoverImageClass) && (empty($this->fbCoverImageClass)))
         {   // if not, use this as default value:
             $this->fbCoverImageClass = "img-responsive";
         }
         // check if alt tag was set
         if (isset($this->fbCoverImageAlt) && (!empty($this->fbCoverImageAlt)))
         {   // it is, generate markup
             $altMarkup = " alt=\"$this->fbCoverImageAlt\"";
         }
         else
             {   // not set, leave empty
                 $altMarkup = '';
             }
         // check if cover image title is set
         if (isset($this->fbCoverImageTitle) && (!empty($this->fbCoverImageTitle)))
         {   // it is, generate markup
             $titleMarkup = " title=\"$this->fbCoverImageTitle\"";
         }
         else
             {   // not set, leave empty
                 $titleMarkup = '';
             }
         // check if image height is set
         if (isset($this->fbCoverImageHeight) && (!empty($this->fbCoverImageHeight)))
         {   // it is, set markup
             $heightMarkup = " height=\"$this->fbCoverImageHeight;\"";
         }
         else
             {   // leave empty
                 $heightMarkup = '';
             }
         // check if image width is set
         if (isset($this->fbCoverImageWidth) && (!empty($this->fbCoverImageWidth)))
         {   // if height is set
             if (isset($heightMarkup) && (!empty($heightMarkup)))
             {   // leave a space between tags
                 $widthMarkup = " width=\"$this->fbCoverImageWidth\"";
             }
             else
                 {   // height is not set - no space needed
                     $widthMarkup = "width=\"$this->fbCoverImageWidth\"";
                 }
         }
         else
             {   // width not set - leave markup empty
                 $widthMarkup = '';
             }
         // check if css style is set
         if (isset($this->fbCoverImageStyle) && (!empty($this->fbCoverImageStyle)))
         {   // add style markup
             $styleMarkup = " style=\"$this->fbCoverImageStyle\"";
         }
         else
             {   // no style markup needed
                 $styleMarkup = '';
             }
         // finally: output the cover image
         echo "<img src=\"".$this->apiObject['cover']['source']."\" class=\"$this->fbCoverImageClass\"$styleMarkup"."$heightMarkup"."$widthMarkup"."$altMarkup"."$titleMarkup>";
References YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\loadJSSDK(), and YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\makeApiCall().
loadJSSDK()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::loadJSSDK ()
Load Facebook JS Code
Definition at line 120 of file fbCover.php.
     {   // check if fb JS SDK was loaded before
         if ($this->jsSDKLoaded == 'false')
         {   // check if app ID is set
             if ($this->checkAppId() == true)
             {
                 /*
                 // include facebook SDK JS
                 echo "<script>
                 window.fbAsyncInit = function() {
                     FB.init({
                     appId      : '" . $this->fbCoverAppId . "',
                     xfbml      : true,
                     version    : 'v3.1'
                     });
                 FB.AppEvents.logPageView();
                 };
                 (function(d, s, id){
                     var js, fjs = d.getElementsByTagName(s)[0];
                     if (d.getElementById(id)) {return;}
                     js = d.createElement(s); js.id = id;
                     js.src = \"https://connect.facebook.net/en_US/sdk.js\";
                     fjs.parentNode.insertBefore(js, fjs);
                 }(document, 'script', 'facebook-jssdk'));
                 </script>";
                 $this->jsSDKLoaded = 'true';
                 */
             }
             else
                 {
                     die ("unable to include facebook js SDK - checkAppId failed. Please check your app ID in the widget settings!");
                 }
         }
References YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\checkAppId(), and die.
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\drawCoverImage().
makeApiCall()
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::makeApiCall ()
Prepare and make the API call and decode the json into the apiObject property
Returns
mixed Returns an array as obj property, containing the data
Definition at line 160 of file fbCover.php.
     {
         // prepare API call
         $json_link = "https://graph.facebook.com/v3.3/me?fields=cover&access_token={$this->fbCoverAccessToken}";
         $curl = curl_init();
         curl_setopt($curl, CURLOPT_URL, $json_link);
         curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
         // decode json and create object
         $this->apiObject = json_decode(curl_exec($curl), true, 512, JSON_BIGINT_AS_STRING);
         curl_close($curl);
         return $this->apiObject;
         // OUTDATED:
         // get json string
         // $json = file_get_contents($json_link);
         // convert json to object
         // return $this->apiObject = json_decode($json, true, 512, JSON_BIGINT_AS_STRING);
References YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\$apiObject.
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\drawCoverImage().
Member Data Documentation
$apiObject
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$apiObject
Parameters
object api result (as object)
Definition at line 40 of file fbCover.php.
Referenced by YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\makeApiCall().
$fbCoverAccessToken
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverAccessToken = ''
Parameters
string your access token (secret word from developers.facebook.com)
Definition at line 22 of file fbCover.php.
$fbCoverAppId
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverAppId = ''
Parameters
string your app ID (from developers.facebook.com)
Definition at line 20 of file fbCover.php.
$fbCoverImageAlt
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageAlt = ''
Parameters
string any image alt tag you like (for screenreaders)
Definition at line 32 of file fbCover.php.
$fbCoverImageClass
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageClass = ''
Parameters
string css class to be set on the cover image
Definition at line 24 of file fbCover.php.
$fbCoverImageHeight
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageHeight = ''
Parameters
string image height in px or %
Definition at line 28 of file fbCover.php.
$fbCoverImageStyle
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageStyle = ''
Parameters
string custom css style attributes
Definition at line 34 of file fbCover.php.
$fbCoverImageTitle
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageTitle = ''
Parameters
string any title you like (important for SEO)
Definition at line 30 of file fbCover.php.
$fbCoverImageWidth
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$fbCoverImageWidth = ''
Parameters
string image width in px or %
Definition at line 26 of file fbCover.php.
$jsSDKLoaded
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$jsSDKLoaded = 'false'
Parameters
string true|false was the js SDK loaded?
Definition at line 36 of file fbCover.php.
$settings
YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover::$settings
Parameters
array array: holds the current widget settings
Definition at line 38 of file fbCover.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/fb_cover/classes/fbCover.php