YaWK: YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage Class Reference
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage Class Reference
Facebook Like Page - embed like my facebook page.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embedLikePage ()
init ()
Init facebook like page.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$fbPageAdaptContainerWidth = "true"
$fbPageAppID = ""
$fbPageHeading = ""
$fbPageHeight = "265"
$fbPageHideCover = "false"
$fbPageSmallHeader = "false"
$fbPageSubtext = ""
$fbPageTabs = "timeline"
$fbPageUrl = "http%3A%2F%2Fwww.facebook.com%2Fplatform"
$fbPageWidth = "450"
$fbShowFacepile = "true"
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Facebook Like Page - embed like my facebook page.
Facebook Like Page - embed a like my facebook page button
If you want to bring attention to your facebook page, you might want to add a 'like my facebook page' button to your page. With this widget, you can do that very easily. You can configure some settings, like width, height, layout, and much more.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file fb_like_page.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 38 of file fb_like_page.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, as, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embedLikePage()
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::embedLikePage ()
Definition at line 60 of file fb_like_page.php.
         {   // check if url is set
             if (isset($this->fbPageUrl) && (!empty($this->fbPageUrl)))
             {   // encode url string
                 $this->fbPageUrl = rawurlencode($this->fbPageUrl);
             }
             // embed facebook like button
             // REMEMBER: this could be blocked by AdBlock Browser Plugins
             echo '<iframe src="https://www.facebook.com/plugins/page.php?href='.$this->fbPageUrl.'&tabs='.$this->fbPageTabs.'&width='.$this->fbPageWidth.'&height='.$this->fbPageHeight.'&small_header='.$this->fbPageSmallHeader.'&adapt_container_width='.$this->fbPageAdaptContainerWidth.'&hide_cover='.$this->fbPageHideCover.'&show_facepile='.$this->fbShowFacepile.'&appId='.$this->fbPageAppID.'" width="'.$this->fbPageWidth.'" height="'.$this->fbPageHeight.'" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>';
Referenced by YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\init().
init()
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::init ()
Init facebook like page.
Facebook Like Page
Definition at line 52 of file fb_like_page.php.
         {
             // embed heading
             echo $this->getHeading($this->fbPageHeading, $this->fbPageSubtext);
             // embed like Page
             $this->embedLikePage();
References YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\embedLikePage(), and YAWK\widget\getHeading().
Member Data Documentation
$fbPageAdaptContainerWidth
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageAdaptContainerWidth = "true"
Definition at line 27 of file fb_like_page.php.
$fbPageAppID
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageAppID = ""
Definition at line 24 of file fb_like_page.php.
$fbPageHeading
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageHeading = ""
Definition at line 30 of file fb_like_page.php.
$fbPageHeight
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageHeight = "265"
Definition at line 22 of file fb_like_page.php.
$fbPageHideCover
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageHideCover = "false"
Definition at line 28 of file fb_like_page.php.
$fbPageSmallHeader
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageSmallHeader = "false"
Definition at line 26 of file fb_like_page.php.
$fbPageSubtext
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageSubtext = ""
Definition at line 31 of file fb_like_page.php.
$fbPageTabs
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageTabs = "timeline"
Definition at line 25 of file fb_like_page.php.
$fbPageUrl
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageUrl = "http%3A%2F%2Fwww.facebook.com%2Fplatform"
Definition at line 23 of file fb_like_page.php.
$fbPageWidth
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbPageWidth = "450"
Definition at line 21 of file fb_like_page.php.
$fbShowFacepile
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$fbShowFacepile = "true"
Definition at line 29 of file fb_like_page.php.
$widget
YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file fb_like_page.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/fb_like_page/classes/fb_like_page.php