YaWK: YAWK\sys Class Reference
YAWK\sys Class Reference
The sys class - handles yawk's system core functions.
Static Public Member Functions
static addPreTags ($customCSS)
THIS SEEMS OUTDATED - obviously not needed anymore....
static addTrailingSlash ($url)
sometimes it is necessary to add a slash to a url.
static array2lines ($array, $property)
Display a multidimensional array line per line. Expects an array and property.
static checkIfAssetsAreLoaded ($db, $assets, $switch)
Check if assets are loaded, load if switch is true.
static checkZlib ()
Check if zlib is available.
static countCodeLines ($path, $fileType)
Count code lines and output a small overview.
static drawPhpInfo ($lang)
Display a complete PHPinfo()
static encodeChars ($string)
convert german special chars and vowels into legal html
static full_copy ($source, $target)
copy an entire folder including subdirectories
static generateRandomPassword ($length)
Generate a random password with given length.
static getBaseDir ()
Return current base directory.
static getBrowser ($useragent)
extract browser from useragent
static getCurrentUserName ()
returns the current user name, if set
static getDirPrefix ($db)
if yawk is installed into a subdirectory, use this to get this prefix directory
static getGroupFromId ($db, $id, $table)
get requested group ID for given page ID
static getGroupId ($db, $id, $table)
get requested group ID for given page ID (used in page-edit)
static getGroups ($db, $table)
get all user groups from database
static getHost ($db)
get hostname (url where yawk is installed) from database
static getLoadingTime ($debugTime)
measure script loading time
static getMenuItem ($db, $id)
get menu item for given page ID
static getMenuLanguage ($db, $id)
returns menu language for given menu ID
static getMenuName ($db, $id)
returns menu name for given menu ID
static getOS ($useragent)
get operating system from useragent string
static getProperty ($db, $property, $table, $id)
get any property from any table where id is given ID
static getRobotsText ($db, $path)
Return the content of /robots.txt.
static getSubMenu ($db, $id)
get submenu ID for given page ID
static getWeekday ($date, $lang)
return weekday from given date
static isBrowscapSet ($useragent)
check if browscap file is set
static iStatusToString ($i, $on, $off)
convert a integer status to string variable (0|1) to online / offline
static minify ($content)
Minify any string: removes spaces, tabs and linebreaks.
static minifyCSS ($input)
Minify any string: removes spaces, tabs and linebreaks.
static minifyHTML ($input)
HTML Minifier - minify any string: removes spaces, tabstops and linebreaks.
static minifyJs ($input)
Minify any string: removes spaces, tabs and linebreaks.
static multiarray2lines ($array, $property)
Display a multidimensional array line per line. Expects an array and property.
static now ()
returns the current datetime
static outputObjects ($template, $lang, $controller, $page, $user, $stats)
check if objects exists and display their data
static parse_phpinfo ()
Read phpinfo() into multidimensional array and return it.
static read_recursive ($path)
Read a directory recursively.
static recurseRmdir ($dir)
remove a directory recurse
static replaceCarriageReturns ($replace, $string)
replace all carriage returns with linebreaks
static replacePreTags ($replace, $customCSS)
removes all unnecessary HTML tags from custom.css
static safeFileReWrite ($fileName, $dataToSave)
Safe way to open a file and update data.
static setRobotsText ($path, $content)
Set the content of /robots.txt (overwrite)
static setTimeout ($location, $wait)
set a timeout and force page reload via JS
static splitDate ($date)
split a date to month, day, year and time
static splitDateShort ($date)
split a date to month, day, year and time this is the same as splitDate() but keep the months short
static time_ago ($userdate, $lang)
how many time is been gone since given date
static writeIniFile ($array, $file)
write ini file
static xcopy ($source, $dest, $permissions=0755)
Copy a file, or recursively copy a folder and its contents.
Detailed Description
The sys class - handles yawk's system core functions.
handles many of yawk's system core functions.
Most of them are static functions, like get and set paths, get ids, roles and so on.
Class covers both, backend & frontend functionality. See Methods Summary for Details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 16 of file sys.php.
Member Function Documentation
addPreTags()
static YAWK\sys::addPreTags ($customCSS) static
THIS SEEMS OUTDATED - obviously not needed anymore....
Parameters
string $customCSS
Returns
string
Definition at line 780 of file sys.php.
         {
             // this function wraps a <pre> tag around the CSS file
             // so that the editor (tinyMCE) can get along with the CSS
             // after submitting the form, <pre> tags will be replaced,
             // so that any browser can interpret the custom.css file proper.
             $preOpen = "<pre style=\"word-wrap: break-word; white-space: pre-wrap;\">";
             $preClose = "</pre>";
             $customCSS = $preOpen .$customCSS;
             $customCSS = $customCSS .$preClose;
             return $customCSS;
         }
References $customCSS.
addTrailingSlash()
static YAWK\sys::addTrailingSlash ($url) static
sometimes it is necessary to add a slash to a url.
Parameters
string $url the url were the slash needs to be added
Returns
string return url containing the slash
Definition at line 1153 of file sys.php.
         {   // check if url contains a trailing slash at the end
             if (substr($url, -1, 1) !== "/")
             {   // if not, it will be added
                 $url = $url."/";
             }
             // return url with trailing slash
             return $url;
         }
References $url.
Referenced by YAWK\sys\getHost().
array2lines()
static YAWK\sys::array2lines ($array, $property) static
Display a multidimensional array line per line. Expects an array and property.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Version
1.0.0
Definition at line 135 of file sys.php.
         {
             if (!isset($array) || (!isset($property)))
             {
                 echo 'array or property not set';
             }
             if (isset($array) && (isset($array[$property]) && (isset($property))))
             {
                 echo "<h2 class=\"myClass\">$property</h2>";
                 foreach ($array[$property] as $item => $key)
                 {
                     $linkProperty = str_replace(" ", "+", $item);
                     if (is_array($key))
                     {
                         echo "<li class=\"list-group-item\"><a href=\"https://www.google.at/search?q=php.net+$linkProperty\" title=\"google this: $item setting\" target=\"_blank\"><b>$item</b> = $key[0]</a></li>";
                     }
                     else
                     {
                         echo "<li class=\"list-group-item\"><a href=\"https://www.google.at/search?q=php.net+$linkProperty\" title=\"google this: $item setting\" target=\"_blank\"><b>$item</b> = $key</a></li>";
                     }
                 }
             }
         }
References $item.
Referenced by YAWK\sys\drawPhpInfo().
checkIfAssetsAreLoaded()
static YAWK\sys::checkIfAssetsAreLoaded ($db, $assets, $switch) static
Check if assets are loaded, load if switch is true.
Parameters
$db object Database object
$assets array Required assets as array
$switch bool true|false If true, required assset gets loaded if not
Returns
mixed
This methods checks if given assets are loaded and load them on demand
Definition at line 26 of file sys.php.
         {
             // check if any assets are sent
             if (isset($assets) && (!empty($assets) && (is_array($assets))))
             {
                 // get current template ID
                 $templateID = \YAWK\template::getCurrentTemplateId($db);
                 // get the number of assets
                 $assetItems = count($assets);
                 // loop counter
                 $successful = 0;
                 // check if templateID is valid
                 if (!isset($templateID) || (empty($templateID) || (!is_numeric($templateID))))
                 {   // unable to get current template ID
                     return false;
                 }
                 else    // valid template ID, go ahead and...
                 {   // walk through required assets array
                     foreach ($assets as $asset => $type)
                     {
                         // check if asset is loaded
                         if ($res = $db->query(("SELECT asset FROM {assets}
                             WHERE asset = '" . $asset . "'
                             AND templateID = '".$templateID."'")))
{
                             if ($row = (mysqli_fetch_row($res)))
{
                                 if (count($row) > 0)
{
                                     // asset found, set loop counter +1
                                     $successful++;
                                 }
                             }
                             else    // asset not found
                             {   // check if switch is true and asset should be loaded...
                                 if (isset($switch) && ($switch == 'true'))
                                 {   // select data from asset types db
                                     if ($res = $db->query("SELECT * FROM {assets_types} WHERE asset = '".$asset."'"))
                                     {   // foreach result
                                         while ($row = (mysqli_fetch_assoc($res)))
{
                                             // check link (internal or external)
                                             if (isset($row['internal']) && (!empty($row['internal'])))
                                             {   // internal link
                                                 $row['link'] = $row['internal'];
                                             }
                                             elseif (isset($row['url1']) && (!empty($row['url1'])))
                                             {   // external link
                                                 $row['link'] = $row['url1'];
                                             }
                                             // load required asset into database
                                             if ($db->query("INSERT INTO {assets} (templateID, type, sortation, asset, link) VALUES ('" . $templateID . "', '" . $type . "', '" . $row['sortation']. "','" . $row['asset'] . "', '" . $row['link'] . "')"))
                                             {   // asset successfully loaded
                                                 $successful++;
                                             }
                                             else
                                             {   // no success - do nothing
                                                 return \YAWK\alert::draw("danger", "ERROR", "Unable to insert Asset into Assets database. Please add this asset $asset manually.", "", 12000);
                                             }
                                         }
                                     }
                                     else
{
                                         // required asset not found in database - add manually!
                                         // die ('required asset is not in database - add manually!');
                                         return \YAWK\alert::draw("danger", "ERROR", "Required Asset is not in the database! Please check, if this asset is registered!", "", 12000);
                                     }
                                     // select data of this asset
                                 }
                                 else
                                 {   // switch is false, means enable asset is not requested
                                     return \YAWK\alert::draw("warning", "Warning - please check this!", "Unable to load asset! $asset Please check required template assets manually!", "", 12000);
                                 }
                             }
                         }
                         else
                         {   // error selecting asset from database
                             return \YAWK\alert::draw("warning", "Warning - this widget requires an additional asset!", "Asset $asset not loaded! Please load this asset within system/asset settings.", "", 12000);
                         }
                     }
                     // check if count and assetItems match to see if everything worked like expected
                     if ($assetItems === $successful)
                     {   // all assets loaded
                         // die ('Required assset was not loaded');
                         return \YAWK\alert::draw("success", "Asset System Information", "I have found out that the required asset was not loaded. I've successfully fixed this for you.", "", 6200);
                     }
                     else
                     {   // not all asset items could get loaded...
                         // die ('Unable to load all assets');
                         return \YAWK\alert::draw("warning", "Warning - please check this!", "Unable to load asset! $asset Please check required template assets manually!", "", 12000);
                     }
                 }
             }
             else
             {   // no assets are set
                 return false;
             }
         }
References $db, $res, $templateID, $type, and YAWK\template\getCurrentTemplateId().
checkZlib()
static YAWK\sys::checkZlib () static
Check if zlib is available.
Returns
bool
Definition at line 451 of file sys.php.
         {   // check if zlib is installed
             if(extension_loaded('zlib'))
             {   // installed
                 return true;
             }
             else
             {   // not installed
                 return false;
             }
         }
countCodeLines()
static YAWK\sys::countCodeLines ($path, $fileType) static
Count code lines and output a small overview.
Parameters
object $db database object
string $path the full path (including base path)
string $fileType file type with leading dot, for example: '.php'
Returns
mixed array
Definition at line 425 of file sys.php.
         {
             $data = \YAWK\sys::read_recursive($path);
             $linesCount = 0;
             $filesCount = 0;
             foreach($data as $value) {
                 // count lines of files with given type
                 if (substr($value, -4) === "$fileType") {
                     $lines = file($value);
                     $i_lines = count($lines);
                     $linesCount += $i_lines;
                     unset($lines, $i_lines);
                     $filesCount++;
                 }
             }
             return $array = [
                 "type" => $fileType,
                 "files" => $filesCount,
                 "lines" => $linesCount,
             ];
         }
References $data, $value, and YAWK\sys\read_recursive().
drawPhpInfo()
static YAWK\sys::drawPhpInfo ($lang) static
Display a complete PHPinfo()
Parameters
$lang
Definition at line 164 of file sys.php.
         {
             // get data from php info into array
             $data = \YAWK\sys::parse_phpinfo();
             // JS filter script
             echo "
             <script>
                 function myFunction() {
                     // Declare variables
                     var input, filter, ul, li, a, i;
                     input = document.getElementById('myInput');
                     filter = input.value.toUpperCase();
                     ul = document.getElementById(\"phpinfoList\");
                     li = ul.getElementsByTagName('li');
                     // Loop through all list items, hide those who don't match the search query
                     for (i = 0; i < li.length; i++) {
                         a = li[i].getElementsByTagName(\"a\")[0];
                         if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                             li[i].style.display = \"\";
                             $('.myClass').show();
                         } else {
                             li[i].style.display = \"none\";
                             $('.myClass').hide();
                         }
                     }
                 }
             </script>";
             echo "<input type=\"text\" id=\"myInput\" class=\"form-control\" onkeyup=\"myFunction()\" placeholder=\"$lang[SEARCH_DOTDOTDOT]\">";
             echo "<ul id=\"phpinfoList\" class=\"list-group\">";
             \YAWK\sys::array2lines($data, "apache2handler");
             \YAWK\sys::array2lines($data, "Apache Environment");
             \YAWK\sys::array2lines($data, "HTTP Headers Information");
             \YAWK\sys::array2lines($data, "bcmath");
             \YAWK\sys::array2lines($data, "bz2");
             \YAWK\sys::array2lines($data, "calendar");
             \YAWK\sys::array2lines($data, "Core");
             \YAWK\sys::array2lines($data, "ctype");
             \YAWK\sys::array2lines($data, "curl");
             \YAWK\sys::array2lines($data, "date");
             \YAWK\sys::array2lines($data, "dom");
             \YAWK\sys::array2lines($data, "ereg");
             \YAWK\sys::array2lines($data, "exif");
             \YAWK\sys::array2lines($data, "fileinfo");
             \YAWK\sys::array2lines($data, "filter");
             \YAWK\sys::array2lines($data, "ftp");
             \YAWK\sys::array2lines($data, "gd");
             \YAWK\sys::array2lines($data, "gettext");
             \YAWK\sys::array2lines($data, "hash");
             \YAWK\sys::array2lines($data, "iconv");
             \YAWK\sys::array2lines($data, "imagick");
             \YAWK\sys::array2lines($data, "json");
             \YAWK\sys::array2lines($data, "libxml");
             \YAWK\sys::array2lines($data, "mbstring");
             \YAWK\sys::array2lines($data, "mcrypt");
             \YAWK\sys::array2lines($data, "mhash");
             \YAWK\sys::array2lines($data, "mysqli");
             \YAWK\sys::array2lines($data, "mysqlnd");
             \YAWK\sys::array2lines($data, "odbc");
             \YAWK\sys::array2lines($data, "openssl");
             \YAWK\sys::array2lines($data, "pcre");
             \YAWK\sys::array2lines($data, "PDO");
             \YAWK\sys::array2lines($data, "pdo_mysql");
             \YAWK\sys::array2lines($data, "pdo_sqlite");
             \YAWK\sys::array2lines($data, "Phar");
             \YAWK\sys::array2lines($data, "Reflection");
             \YAWK\sys::array2lines($data, "session");
             \YAWK\sys::array2lines($data, "SimpleXML");
             \YAWK\sys::array2lines($data, "SPL");
             \YAWK\sys::array2lines($data, "standard");
             \YAWK\sys::array2lines($data, "tokenizer");
             \YAWK\sys::array2lines($data, "wddx");
             \YAWK\sys::array2lines($data, "xml");
             \YAWK\sys::array2lines($data, "xmlreader");
             \YAWK\sys::array2lines($data, "xmlwriter");
             \YAWK\sys::array2lines($data, "zip");
             \YAWK\sys::array2lines($data, "zlib");
             echo "</ul>";
             /*
             echo "</tbody></table>";
             */
         }
References $data, YAWK\sys\array2lines(), and YAWK\sys\parse_phpinfo().
encodeChars()
static YAWK\sys::encodeChars ($string) static
convert german special chars and vowels into legal html
Parameters
string $string to encode
Returns
string return encoded string
Definition at line 1095 of file sys.php.
         {   // requires string. encodes german vowels
             // $string = utf8_decode($string);
             $chars = array("" => "&ouml;", "" => "&auml;", "" => "&uuml;",
                 "" => "&Ouml;", "" => "&Auml;", "" => "&Uuml;",
                 "" => "&szlig;",
                 "" => "&euro;");
             return strtr($string, $chars);
         }
Referenced by YAWK\page\create(), and YAWK\menu\createMenu().
full_copy()
static YAWK\sys::full_copy ($source, $target) static
copy an entire folder including subdirectories
Parameters
string $source source directory
string $target target directory
copy an entire folder into another location
Definition at line 694 of file sys.php.
         {   /** copy an entire folder into another location */
             if (is_dir($source))
             {
                 @mkdir($target);
                 $d = dir($source);
                 while (FALSE !== ($entry = $d->read()))
                 {
                     if ($entry == '.' || $entry == '..')
                     {
                         continue;
                     }
                     $Entry = $source.'/'.$entry;
                     if (is_dir($Entry))
                     {
                         self::full_copy($Entry, $target.'/'.$entry);
                         continue;
                     }
                     copy($Entry, $target.'/'.$entry);
                 }
                 $d->close();
             }
             else
             {
                 copy( $source, $target );
             }
         }
generateRandomPassword()
static YAWK\sys::generateRandomPassword ($length) static
Generate a random password with given length.
Parameters
int $length length of the password you wish to return
Returns
string
Definition at line 314 of file sys.php.
         {
             // if length is not set or wrong type
             if (!isset($length) || (empty($length) || (!is_int($length))))
             {   // generate password with default length (8 chars)
                 $length = 8;
             }
             // string with allowed chars - these can appear in the generated password
             $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_-=+;:,.?";
             // generate password
             $password = substr(str_shuffle($chars), 0, $length);
             return $password;
         }
References $password.
getBaseDir()
static YAWK\sys::getBaseDir () static
Return current base directory.
Returns
string
Definition at line 304 of file sys.php.
         {
             return substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'],basename($_SERVER['SCRIPT_NAME'])));
         }
Referenced by YAWK\installer\step3(), and YAWK\installer\step4().
getBrowser()
static YAWK\sys::getBrowser ($useragent) static
extract browser from useragent
Parameters
string $useragent the full useragent
Returns
array array with useragent, browser, version and platform
Definition at line 917 of file sys.php.
         {
             if (isset($useragent) && (!empty($useragent)))
             {
                 $u_agent = $useragent;
             }
             else
             {
                 $u_agent = $_SERVER['HTTP_USER_AGENT'];
             }
             $bname = 'Unknown';
             $platform = 'Unknown';
             $ub = '';
             $version= "";
             //First get the platform?
             if (preg_match('/linux/i', $u_agent)) {
                 $platform = 'linux';
             }
             elseif (preg_match('/macintosh|mac os x/i', $u_agent)) {
                 $platform = 'mac';
             }
             elseif (preg_match('/windows|win32/i', $u_agent)) {
                 $platform = 'windows';
             }
             elseif(preg_match('/linux|android/i',$u_agent))
             {
                 $bname = 'Android';
                 $ub = "Android";
                 $platform = "Android";
             }
             // Next get the name of the useragent yes seperately and for good reason
             if(preg_match('/MSIE/i',$u_agent) && !preg_match('/Opera/i',$u_agent))
             {
                 $bname = 'Internet Explorer';
                 $ub = "MSIE";
             }
             if(preg_match('/Edge/i',$u_agent) && !preg_match('/Opera/i',$u_agent))
             {
                 $bname = 'Edge';
                 $ub = "Edge";
             }
             elseif(preg_match('/Trident/i',$u_agent))
             { // this condition is for IE11
                 $bname = 'Internet Explorer';
                 $ub = "rv";
             }
             elseif(preg_match('/Firefox/i',$u_agent))
             {
                 $bname = 'Mozilla Firefox';
                 $ub = "Firefox";
             }
             elseif(preg_match('/Chrome/i',$u_agent))
             {
                 $bname = 'Google Chrome';
                 $ub = "Chrome";
             }
             elseif(preg_match('/Safari/i',$u_agent))
             {
                 $bname = 'Apple Safari';
                 $ub = "Safari";
             }
             elseif(preg_match('/Opera/i',$u_agent))
             {
                 $bname = 'Opera';
                 $ub = "Opera";
             }
             elseif(preg_match('/Netscape/i',$u_agent))
             {
                 $bname = 'Netscape';
                 $ub = "Netscape";
             }
             // finally get the correct version number
             // Added "|:"
             $known = array('Version', $ub, 'other');
             $pattern = '#(?<browser>' . join('|', $known) .
                 ')[/|: ]+(?<version>[0-9.|a-zA-Z.]*)#';
             if (!preg_match_all($pattern, $u_agent, $matches)) {
                 // we have no matching number just continue
             }
             // see how many we have
             $i = count($matches['browser']);
             if ($i != 1) {
                 //we will have two since we are not using 'other' argument yet
                 //see if version is before or after the name
                 if (strripos($u_agent,"Version") < strripos($u_agent,$ub)){
                     $version= $matches['version'][0];
                 }
                 else {
                     $version= $matches['version'][1];
                 }
             }
             else {
                 $version= $matches['version'][0];
             }
             // check if we have a number
             if ($version==null || $version=="") {$version="?";}
             return array(
                 'userAgent' => $u_agent,
                 'name'      => $bname,
                 'version'   => $version,
                 'platform'  => $platform,
                 'pattern'    => $pattern
             );
         }
References $i, and $useragent.
Referenced by YAWK\stats\prepareData().
getCurrentUserName()
static YAWK\sys::getCurrentUserName () static
returns the current user name, if set
Returns
string
Definition at line 1290 of file sys.php.
         {
             if (isset($_SESSION['username'])) {
                 return $_SESSION['username'];
             }
             else {
                 return "Gast";
             }
         }
Referenced by YAWK\menu\drawLogoutMenu().
getDirPrefix()
static YAWK\sys::getDirPrefix ($db) static
if yawk is installed into a subdirectory, use this to get this prefix directory
Parameters
object $db database
Returns
string return the directory prefix
Definition at line 1110 of file sys.php.
         {   // returns directory prefix from settings
             $dirprefix = settings::getSetting($db, "dirprefix");
             return $dirprefix;
         }
References $db, $dirprefix, and YAWK\settings\getSetting().
Referenced by YAWK\widget\getCurrentWidgetPath().
getGroupFromId()
static YAWK\sys::getGroupFromId ($db, $id, $table) static
get requested group ID for given page ID
Parameters
object $db database
string $id page ID
string $table the table to select from
Returns
string|bool return the group ID or false
Parameters
$db \YAWK\db $res
Definition at line 1223 of file sys.php.
         {
             /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT cp.gid, cg.value
                     FROM {".$table."} as cp
                     JOIN {user_groups} as cg on cg.id = cp.gid
                     WHERE cp.id = $id"))
             {
                 while ($row = mysqli_fetch_row($res))
                 {
                     echo $row[1];
                 }
                 return $row[0];
             }
             else {
                 \YAWK\alert::draw("warning", "Warning", "Could not fetch Group from page ID $id", "","2000");
                 // q failed
                 return false;
             }
         }
References $db, $res, and YAWK\alert\draw().
getGroupId()
static YAWK\sys::getGroupId ($db, $id, $table) static
get requested group ID for given page ID (used in page-edit)
Parameters
object $db database
string $id page ID
string $table the table to select from
Returns
string|bool return the group ID or false
Parameters
$db \YAWK\db $res
Definition at line 1198 of file sys.php.
         {   /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT cg.id
                               FROM {".$table."} as cp
                               JOIN {user_groups} as cg on cg.id = cp.gid
                               WHERE cp.id = $id"))
             {   // get GroupId (gid) from given table
                 $row = mysqli_fetch_row($res);
                 return $row[0];
             }
             else
             {
                 \YAWK\alert::draw("warning", "Warning", "Could not fetch Group ID from $table", "","2000");
             }
             return false;
         }
References $db, $res, and YAWK\alert\draw().
getGroups()
static YAWK\sys::getGroups ($db, $table) static
get all user groups from database
Parameters
object $db database
string $table the table to select from
Returns
array|bool|string
Parameters
$db \YAWK\db $res
Definition at line 1250 of file sys.php.
         {
             /** @param $db \YAWK\db $res */
             $groupsArray = array();
             if ($res = $db->query("SELECT id, value, (
                                   SELECT COUNT( * )
                                   FROM {".$table."}
                                   WHERE gid = {user_groups.id}
                                  )count
                                  FROM {user_groups} ORDER by id ASC"))
             {
                 while ($row = $res->fetch_assoc())
                 {
                     $groupsArray[] = $row;
                 }
                 return $groupsArray;
             }
             // q failed
             return false;
         }
References $db, and $res.
getHost()
static YAWK\sys::getHost ($db) static
get hostname (url where yawk is installed) from database
Parameters
object $db database
Returns
bool|string
Definition at line 1121 of file sys.php.
         {   // get host from settings db
             $hostname = settings::getSetting($db, "host");
             $hostname = self::addTrailingSlash($hostname);
             return $hostname;
         }
References $db, YAWK\sys\addTrailingSlash(), and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\MESSAGES\messages\__construct(), and YAWK\user\sendResetEmail().
getLoadingTime()
static YAWK\sys::getLoadingTime ($debugTime) static
measure script loading time
Parameters
string $debugTime starting time
Returns
string return formated time in milliseconds
Definition at line 1082 of file sys.php.
         {
             // debugTime to measure script time
             $debugTime = microtime(true) - $debugTime;
             $debugTime = number_format($debugTime, 3);
             return "<small>&nbsp; script execution time: $debugTime Sek.</small>";
         }
getMenuItem()
static YAWK\sys::getMenuItem ($db, $id) static
get menu item for given page ID
Parameters
object $db database
int $id page ID
Returns
bool
Parameters
$db \YAWK\db $res
Definition at line 1335 of file sys.php.
         {
             /** @param $db \YAWK\db $res */
             if ($row = $db->query("SELECT p.menu, m.name
                                   FROM {pages} as p
                                   JOIN {menu_names} as m on m.id = p.menu
                                   WHERE p.id = $id"))
             {
                 $res = mysqli_fetch_row($row);
                 if (isset($res[1])){
                     return $res[1];
                 }
                 else {
                     return null;
                 }
             }
             else
             {
                 return null;
             }
         }
References $db, and $res.
getMenuLanguage()
static YAWK\sys::getMenuLanguage ($db, $id) static
returns menu language for given menu ID
Parameters
object $db database
int $id menu ID
Returns
bool
Parameters
$db \YAWK\db $res
Definition at line 1411 of file sys.php.
         {   /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT menuLanguage
                                   FROM {menu_names}
                                   WHERE id = $id"))
             {   // return menu name
                 $row = mysqli_fetch_row($res);
                 return $row[0];
             }
             else
             {   // q failed
                 return false;
             }
         }
References $db, and $res.
getMenuName()
static YAWK\sys::getMenuName ($db, $id) static
returns menu name for given menu ID
Parameters
object $db database
int $id menu ID
Returns
bool
Parameters
$db \YAWK\db $res
Definition at line 1390 of file sys.php.
         {   /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT name
                                   FROM {menu_names}
                                   WHERE id = $id"))
             {   // return menu name
                 $row = mysqli_fetch_row($res);
                 return $row[0];
             }
             else
             {   // q failed
                 return false;
             }
         }
References $db, and $res.
getOS()
static YAWK\sys::getOS ($useragent) static
get operating system from useragent string
Parameters
string $useragent full useragent string
Returns
mixed|string return string containing the OS (platform)
Definition at line 1033 of file sys.php.
{
             if (isset($useragent) && (!empty($useragent)))
             {
                 $u_agent = $useragent;
             }
             else
             {
                 $u_agent = $_SERVER['HTTP_USER_AGENT'];
             }
             // $os_platform    =   "Unknown OS Platform";
             $os_array       =   array(
                 '/Sec-CH-UA-Platform/i' =>  'Windows 11',
                 '/Windows NT 10.0/i'    =>  'Windows 10',
                 '/windows nt 6.2/i'     =>  'Windows 8',
                 '/windows nt 6.1/i'     =>  'Windows 7',
                 '/windows nt 6.0/i'     =>  'Windows Vista',
                 '/windows nt 5.2/i'     =>  'Windows Server 2003/XP x64',
                 '/windows nt 5.1/i'     =>  'Windows XP',
                 '/windows xp/i'         =>  'Windows XP',
                 '/windows nt 5.0/i'     =>  'Windows 2000',
                 '/windows me/i'         =>  'Windows ME',
                 '/win98/i'              =>  'Windows 98',
                 '/win95/i'              =>  'Windows 95',
                 '/win16/i'              =>  'Windows 3.11',
                 '/macintosh|mac os x/i' =>  'Mac OS X',
                 '/mac_powerpc/i'        =>  'Mac OS 9',
                 '/linux/i'              =>  'Linux',
                 '/ubuntu/i'             =>  'Ubuntu',
                 '/iphone/i'             =>  'iPhone',
                 '/ipod/i'               =>  'iPod',
                 '/ipad/i'               =>  'iPad',
                 '/android/i'            =>  'Android',
                 '/blackberry/i'         =>  'BlackBerry',
                 '/webos/i'              =>  'Mobile'
             );
             foreach ($os_array as $regex => $value) {
                 if (preg_match($regex, $u_agent)) {
                     $os_platform    =   $value;
                 }
             }
             return $os_platform;
         }
References $useragent, and $value.
Referenced by YAWK\stats\prepareData().
getProperty()
static YAWK\sys::getProperty ($db, $property, $table, $id) static
get any property from any table where id is given ID
Parameters
object $db database
string $property what to select (field)
string $table from wich (table)
string $id where id = (id)
Returns
bool
Parameters
$db \YAWK\db $res
Definition at line 1171 of file sys.php.
         {   /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT " . $property . " FROM {$table}
                                    WHERE id = '" . $id . "'"))
             {   // fetch data
                 if ($row = mysqli_fetch_row($res))
                 {   // return property
                     return $row[0];
                 }
                 else
                 {   // fetch failed
                     return false;
                 }
             }
             else
             {   // q failed
                 return false;
             }
         }
References $db, $id, and $res.
getRobotsText()
static YAWK\sys::getRobotsText ($db, $path) static
Return the content of /robots.txt.
Parameters
string $path absolute path to the robots.txt file
Returns
string|bool
Definition at line 334 of file sys.php.
         {
             $robotsText = "$path/robots.txt";
             $file = file_get_contents($robotsText);
             if (!empty($file))
             {
                 return $file;
             }
             else
             {   // try to get robots.txt from database
                 if ($file = \YAWK\settings::getLongSetting($db, "robotsText-long"))
                 {
                     return $file;
                 }
                 else
                 {   // db setting robotsText-long is empty
                     return false;
                 }
             }
         }
References $db, and YAWK\settings\getLongSetting().
getSubMenu()
static YAWK\sys::getSubMenu ($db, $id) static
get submenu ID for given page ID
Parameters
object $db database
string $id page ID
Returns
mixed string|int
Parameters
$db \YAWK\db $res
Definition at line 1306 of file sys.php.
         {
             /** @param $db \YAWK\db $res */
             if ($res = $db->query("SELECT m.id
                                FROM {pages} as p
                                JOIN {menu_names} as m on m.id = p.menu
                                WHERE p.id = $id")){
                 $row = mysqli_fetch_row($res);
                 if (!isset($row[0]) ||(empty($row[0])))
                 {
                     return "0";
                 }
                 else
                 {
                     return $row[0];
                 }
             }
             else
             {
                 return "0";
             }
         }
References $db, and $res.
getWeekday()
static YAWK\sys::getWeekday ($date, $lang) static
return weekday from given date
Parameters
string $date the date to calculate
Returns
bool|false|string
Definition at line 1741 of file sys.php.
         {
             global $lang;
             if (isset($date)){
                 // get weekday
                 $weekday = date("l",strtotime($date));
                 if (isset($lang) && (!empty($lang) && (is_array($lang))))
                 {
                     // translate, if language is set
                     switch($weekday){
                         case "$lang[MONDAY]":
                             $weekday = "$lang[MONDAY]";
                             break;
                         case "$lang[TUESDAY]":
                             $weekday = "$lang[TUESDAY]";
                             break;
                         case "$lang[WEDNESDAY]":
                             $weekday = "$lang[WEDNESDAY]";
                             break;
                         case "$lang[THURSDAY]":
                             $weekday = "$lang[THURSDAY]";
                             break;
                         case "$lang[FRIDAY]":
                             $weekday = "$lang[FRIDAY]";
                             break;
                         case "$lang[SATURDAY]":
                             $weekday = "$lang[SATURDAY]";
                             break;
                         case "$lang[SUNDAY]":
                             $weekday = "$lang[SUNDAY]";
                             break;
                     }
                 }
                 return $weekday;
             }
             else {
                 return false;
             }
         }
References $date, $lang, and date.
Referenced by YAWK\stats\countWeekdays().
isBrowscapSet()
static YAWK\sys::isBrowscapSet ($useragent) static
check if browscap file is set
Parameters
string $useragent full useragent
Returns
bool|null
Definition at line 886 of file sys.php.
         {
             // check if a browscap file is set...
             if (ini_get('browscap'))
             {   // got it, output file path
                 $browscapFile = ini_get('browscap');
                 // print browser info:
                 echo "<pre>"; print_r(get_browser($useragent)); echo "</pre>";
             }
             else
             {   // browscap file not set
                 \YAWK\alert::draw("info", "Warning!", "Browscap file not set in your php.ini", "", 7500);
                 // try to enable via ini_set
                 if (ini_set('browscap', 'browscap.ini'))
                 {   // worked, show browser info...
                     echo "<pre>"; print_r(get_browser($useragent)); echo "</pre>";
                 }
                 else
                 {   // enable failed, exit with error
                     return false;
                     // \YAWK\alert::draw("danger", "Error: ", "Browscap file not set in php.ini Tried to enable via ini_set. Did not work... aborting!", "", 15000);
                 }
             }
             return null;
         }
References $useragent, and YAWK\alert\draw().
iStatusToString()
static YAWK\sys::iStatusToString ($i, $on, $off) static
convert a integer status to string variable (0|1) to online / offline
Parameters
int $i the status var
string $on string for status 1 (online, published...)
string $off string for status 0 (offline, not published...)
Returns
bool|string return the converted string or false
Definition at line 729 of file sys.php.
         {   // check if $i is set and from correct type
             $status = '';
             if (isset($i))
             {
                 // check online string
                 if (!isset($on) || (empty($on)))
                 {
                     $on = "online";
                 }
                 // check offline string
                 if (!isset($off) || (empty($off)))
                 {
                     $off = "offline";
                 }
                 if ($i == "1")
                 {   // return word online
                     $status = $on;
                 }
                 elseif ($i == "0")
                 {   // return word online
                     $status = $off;
                 }
                 else
                 {
                     $status = "error: \$i status undefined";
                 }
             }
             else
             {   // ID not set or not a number
                 return false;
             }
             return $status;
         }
References $i.
Referenced by YAWK\menu\toggleItemOffline(), YAWK\menu\toggleOffline(), and YAWK\page\toggleOffline().
minify()
static YAWK\sys::minify ($content) static
Minify any string: removes spaces, tabs and linebreaks.
Parameters
string $content
Returns
mixed
minify data
Definition at line 528 of file sys.php.
         {   /** minify data */
             // remove comments
             $content = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $content);
             // remove space after colons
             $content = str_replace(': ', ':', $content);
             // remove whitespaces
             $content = str_replace(array("\r\n", "\r", "\n", "\t", '  ', '    ', '    '), '', $content);
             return $content;
         }
References $content.
minifyCSS()
static YAWK\sys::minifyCSS ($input) static
Minify any string: removes spaces, tabs and linebreaks.
Author
Rodrigo54
Version
1.0.0 string $input the CSS string to minify mixed CSS Minifier => http://ideone.com/Q5USEF + improvement(s)
Definition at line 614 of file sys.php.
{
             if(trim($input) === "") return $input;
             return preg_replace(
                 array(
                     // Remove comment(s)
                     '#("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\')|\/\*(?!\!)(?>.*?\*\/)|^\s*|\s*$#s',
                     // Remove unused white-space(s)
                     '#("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\'|\/\*(?>.*?\*\/))|\s*+;\s*+(})\s*+|\s*+([*$~^|]?+=|[{};,>~+]|\s*+-(?![0-9\.])|!important\b)\s*+|([[(:])\s++|\s++([])])|\s++(:)\s*+(?!(?>[^{}"\']++|"(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\')*+{)|^\s++|\s++\z|(\s)\s+#si',
                     // Replace `0(cm|em|ex|in|mm|pc|pt|px|vh|vw|%)` with `0`
                     '#(?<=[\s:])(0)(cm|em|ex|in|mm|pc|pt|px|vh|vw|%)#si',
                     // Replace `:0 0 0 0` with `:0`
                     '#:(0\s+0|0\s+0\s+0\s+0)(?=[;\}]|\!important)#i',
                     // Replace `background-position:0` with `background-position:0 0`
                     '#(background-position):0(?=[;\}])#si',
                     // Replace `0.6` with `.6`, but only when preceded by `:`, `,`, `-` or a white-space
                     '#(?<=[\s:,\-])0+\.(\d+)#s',
                     // Minify string value
                     '#(\/\*(?>.*?\*\/))|(?<!content\:)([\'"])([a-z_][a-z0-9\-_]*?)\2(?=[\s\{\}\];,])#si',
                     '#(\/\*(?>.*?\*\/))|(\burl\‍()([\'"])([^\s]+?)\3(\‍))#si',
                     // Minify HEX color code
                     '#(?<=[\s:,\-]\#)([a-f0-6]+)\1([a-f0-6]+)\2([a-f0-6]+)\3#i',
                     // Replace `(border|outline):none` with `(border|outline):0`
                     '#(?<=[\{;])(border|outline):none(?=[;\}\!])#',
                     // Remove empty selector(s)
                     '#(\/\*(?>.*?\*\/))|(^|[\{\}])(?:[^\s\{\}]+)\{\}#s'
                 ),
                 array(
                     '$1',
                     '$1$2$3$4$5$6$7',
                     '$1',
                     ':0',
                     '$1:0 0',
                     '.$1',
                     '$1$3',
                     '$1$2$4$5',
                     '$1$2$3',
                     '$1:0',
                     '$1$2'
                 ),
                 $input);
         }
Referenced by YAWK\sys\minifyHTML().
minifyHTML()
static YAWK\sys::minifyHTML ($input) static
HTML Minifier - minify any string: removes spaces, tabstops and linebreaks.
Author
Rodrigo54
Version
1.0.0 string $input the CSS string to minify mixed Based on https://github.com/mecha-cms/mecha-cms/blob/master/system/kernel/converter.php
Definition at line 548 of file sys.php.
{
             if(trim($input) === "") return $input;
             // Remove extra white-space(s) between HTML attribute(s)
             $input = preg_replace_callback('#<([^\/\s<>!]+)(?:\s+([^<>]*?)\s*|\s*)(\/?)>#s', function($matches) {
                 return '<' . $matches[1] . preg_replace('#([^\s=]+)(\=([\'"]?)(.*?)\3)?(\s+|$)#s', ' $1$2', $matches[2]) . $matches[3] . '>';
             }, str_replace("\r", "", $input));
             // Minify inline CSS declaration(s)
             if(strpos($input, ' style=') !== false) {
                 $input = preg_replace_callback('#<([^<]+?)\s+style=([\'"])(.*?)\2(?=[\/\s>])#s', function($matches) {
                     return '<' . $matches[1] . ' style=' . $matches[2] . self::minifyCSS($matches[3]) . $matches[2];
                 }, $input);
             }
             if(strpos($input, '</style>') !== false) {
                 $input = preg_replace_callback('#<style(.*?)>(.*?)</style>#is', function($matches) {
                     return '<style' . $matches[1] .'>'. self::minifyCSS($matches[2]) . '</style>';
                 }, $input);
             }
             if(strpos($input, '</script>') !== false) {
                 $input = preg_replace_callback('#<script(.*?)>(.*?)</script>#is', function($matches) {
                     return '<script' . $matches[1] .'>'. self::minifyJs($matches[2]) . '</script>';
                 }, $input);
             }
             return preg_replace(
                 array(
                     // t = text
                     // o = tag open
                     // c = tag close
                     // Keep important white-space(s) after self-closing HTML tag(s)
                     '#<(img|input)(>| .*?>)#s',
                     // Remove a line break and two or more white-space(s) between tag(s)
                     '#(<!--.*?-->)|(>)(?:\n*|\s{2,})(<)|^\s*|\s*$#s',
                     '#(<!--.*?-->)|(?<!>)\s+(<\/.*?>)|(<[^\/]*?>)\s+(?!<)#s', // t+c || o+t
                     '#(<!--.*?-->)|(<[^\/]*?>)\s+(<[^\/]*?>)|(<\/.*?>)\s+(<\/.*?>)#s', // o+o || c+c
                     '#(<!--.*?-->)|(<\/.*?>)\s+(\s)(?!<)|(?<!>)\s+(\s)(<[^\/]*?\/?>)|(<[^\/]*?\/?>)\s+(\s)(?!<)#s', // c+t || t+o || o+t -- separated by long white-space(s)
                     '#(<!--.*?-->)|(<[^\/]*?>)\s+(<\/.*?>)#s', // empty tag
                     '#<(img|input)(>| .*?>)<\/\1>#s', // reset previous fix
                     '#(&nbsp;)&nbsp;(?![<\s])#', // clean up ...
                     '#(?<=>)(&nbsp;)(?=<)#', // --ibid
                     // Remove HTML comment(s) except IE comment(s)
                     '#\s*<!--(?!\[if\s).*?-->\s*|(?<!>)\n+(?=<[^!])#s'
                 ),
                 array(
                     '<$1$2</$1>',
                     '$1$2$3',
                     '$1$2$3',
                     '$1$2$3$4$5',
                     '$1$2$3$4$5$6$7',
                     '$1$2$3',
                     '<$1$2',
                     '$1 ',
                     '$1',
                     ""
                 ),
                 $input);
         }
References YAWK\sys\minifyCSS(), and YAWK\sys\minifyJs().
minifyJs()
static YAWK\sys::minifyJs ($input) static
Minify any string: removes spaces, tabs and linebreaks.
Author
Rodrigo54
Version
1.0.0 string $input the JS string to minify mixed
Definition at line 664 of file sys.php.
{
             if(trim($input) === "") return $input;
             return preg_replace(
                 array(
                     // Remove comment(s)
                     '#\s*("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\')\s*|\s*\/\*(?!\!|@cc_on)(?>[\s\S]*?\*\/)\s*|\s*(?<![\:\=])\/\/.*(?=[\n\r]|$)|^\s*|\s*$#',
                     // Remove white-space(s) outside the string and regex
                     '#("(?:[^"\\\]++|\\\.)*+"|\'(?:[^\'\\\\]++|\\\.)*+\'|\/\*(?>.*?\*\/)|\/(?!\/)[^\n\r]*?\/(?=[\s.,;]|[gimuy]|$))|\s*([!%&*\‍(\‍)\-=+\[\]\{\}|;:,.<>?\/])\s*#s',
                     // Remove the last semicolon
                     '#;+\}#',
                     // Minify object attribute(s) except JSON attribute(s). From `{'foo':'bar'}` to `{foo:'bar'}`
                     '#([\{,])([\'])(\d+|[a-z_][a-z0-9_]*)\2(?=\:)#i',
                     // --ibid. From `foo['bar']` to `foo.bar`
                     '#([a-z0-9_\‍)\]])\[([\'"])([a-z_][a-z0-9_]*)\2\]#i'
                 ),
                 array(
                     '$1',
                     '$1$2',
                     '}',
                     '$1$3',
                     '$1.$3'
                 ),
                 $input);
         }
Referenced by YAWK\sys\minifyHTML().
multiarray2lines()
static YAWK\sys::multiarray2lines ($array, $property) static
Display a multidimensional array line per line. Expects an array and property.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Version
1.0.0 bool
Definition at line 257 of file sys.php.
         {
             echo "<h2><small>".strtoupper($property)."</small></h2>";
             foreach ($array[$property] as $item => $key)
             {
                 echo "<b>$item</b> = $key[0]<br>";
             }
             return true;
         }
References $item.
now()
static YAWK\sys::now () static
returns the current datetime
Returns
string datetime Y-m-d H:i:s
Definition at line 1498 of file sys.php.
         {   // return current datetime in mysql format
             return date("Y-m-d H:i:s");
         }
References date.
Referenced by YAWK\template\downloadTemplate(), YAWK\stats\prepareData(), YAWK\template\saveAs(), and YAWK\BACKUP\FILES\fileBackup\setBackupSettings().
outputObjects()
static YAWK\sys::outputObjects ($template, $lang, $controller, $page, $user, $stats) static
check if objects exists and display their data
Definition at line 2062 of file sys.php.
         {
             $objects = get_defined_vars();
             if (isset($objects) && (is_array($objects)))
             {
                 echo "ALL DECLARED OBJECTS IN THIS SCOPE:<hr>";
                 echo "<pre>";print_r($objects);echo"</pre><hr>";
             }
             exit;
         }
References exit.
parse_phpinfo()
static YAWK\sys::parse_phpinfo () static
Read phpinfo() into multidimensional array and return it.
Author
Ray Chang
Version
1.0.0 array phpinfo() data as multidimensional array
Definition at line 274 of file sys.php.
{
             ob_start(); phpinfo(INFO_MODULES); $s = ob_get_contents(); ob_end_clean();
             $s = strip_tags($s, '<h2><th><td>');
             $s = preg_replace('/<th[^>]*>([^<]+)<\/th>/', '<info>\1</info>', $s);
             $s = preg_replace('/<td[^>]*>([^<]+)<\/td>/', '<info>\1</info>', $s);
             $t = preg_split('/(<h2[^>]*>[^<]+<\/h2>)/', $s, -1, PREG_SPLIT_DELIM_CAPTURE);
             $r = array(); $count = count($t);
             $p1 = '<info>([^<]+)<\/info>';
             $p2 = '/'.$p1.'\s*'.$p1.'\s*'.$p1.'/';
             $p3 = '/'.$p1.'\s*'.$p1.'/';
             for ($i = 1; $i < $count; $i++) {
                 if (preg_match('/<h2[^>]*>([^<]+)<\/h2>/', $t[$i], $matchs)) {
                     $name = trim($matchs[1]);
                     $vals = explode("\n", $t[$i + 1]);
                     foreach ($vals AS $val) {
                         if (preg_match($p2, $val, $matchs)) { // 3cols
                             $r[$name][trim($matchs[1])] = array(trim($matchs[2]), trim($matchs[3]));
                         } elseif (preg_match($p3, $val, $matchs)) { // 2cols
                             $r[$name][trim($matchs[1])] = trim($matchs[2]);
                         }
                     }
                 }
             }
             return $r;
         }
References $i, and $name.
Referenced by YAWK\sys\drawPhpInfo().
read_recursive()
static YAWK\sys::read_recursive ($path) static
Read a directory recursively.
Parameters
string $path full path e.g. /xampp/htdocs/yawk-LTE/
Returns
array
Definition at line 381 of file sys.php.
         {
             global $files_count;
             $result = array();
             $handle = opendir($path);
             if ($handle)
             {
                 while (false !== ($file = readdir($handle)))
                 {
                     if ($file != "." && $file != "..")
                     {
                         if (is_file($file))
{
                             $files_count = $files_count + 1;
                         }
                         $name = $path . "/" . $file;
                         if (is_dir($name))
{
                             $ar = self::read_recursive($name);
                             foreach ($ar as $value)
{
                                 $result[] = $value;
                             }
                         }
                         else
{
                             $result[] = $name;
                             $files_count = $files_count + 1;
                         }
                     }
                 }
             }
             closedir($handle);
             return $result;
         }
References $name, $result, and $value.
Referenced by YAWK\sys\countCodeLines().
recurseRmdir()
static YAWK\sys::recurseRmdir ($dir) static
remove a directory recurse
Parameters
string $dir the directory to delete
Returns
bool
Definition at line 1133 of file sys.php.
{
             if (is_dir(dirname($dir)))
             {
                 $files = array_diff(scandir($dir), array('.','..'));
                 foreach ($files as $file) {
                     (is_dir("$dir/$file")) ? self::recurseRmdir("$dir/$file") : unlink("$dir/$file");
                 }
                 return rmdir($dir);
             }
             else
             {
                 return false;
             }
         }
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup(), and YAWK\BACKUP\backup\doRestore().
replaceCarriageReturns()
static YAWK\sys::replaceCarriageReturns ($replace, $string) static
replace all carriage returns with linebreaks
Parameters
string $replace searchstring
string $string replacestring
Returns
string
Definition at line 770 of file sys.php.
         {
             return str_replace(array("\n\r", "\n", "\r"), $replace, $string);
         }
replacePreTags()
static YAWK\sys::replacePreTags ($replace, $customCSS) static
removes all unnecessary HTML tags from custom.css
Parameters
string $replace
string $customCSS
Returns
string
Definition at line 799 of file sys.php.
         {   // this function removes all unnecessary HTML tags from custom.css
             return str_replace(array("<p>", "</p>", "<br />", "</pre>", "<pre style=\"word-wrap: break-word; white-space: pre-wrap;\">"), "", $customCSS);
         }
References $customCSS.
safeFileReWrite()
static YAWK\sys::safeFileReWrite ($fileName, $dataToSave) static
Safe way to open a file and update data.
Parameters
$fileName
$dataToSave
Returns
bool
Definition at line 2107 of file sys.php.
         {
             if ($fp = fopen($fileName, 'w'))
             {
                 $startTime = microtime(TRUE);
                 do
                 {
                     $canWrite = flock($fp, LOCK_EX);
                     // If lock not obtained sleep for 0 - 100 milliseconds, to avoid collision and CPU load
                     if(!$canWrite) usleep(round(rand(0, 100)*1000));
                 }
                 while ((!$canWrite)and((microtime(TRUE)-$startTime) < 5));
                 //file was locked so now we can store information
                 if ($canWrite)
                 {
                     fwrite($fp, $dataToSave);
                     flock($fp, LOCK_UN);
                 }
                 fclose($fp);
             }
             if (is_file($fileName))
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
setRobotsText()
static YAWK\sys::setRobotsText ($path, $content) static
Set the content of /robots.txt (overwrite)
Parameters
string $path absolute path to the robots.txt file
string $content file content to write in robots.txt
Returns
bool
Definition at line 361 of file sys.php.
         {
             // check if file content is set...
             // set robots.txt path + filename
             $filename = "$path"."robots.txt";
             if (file_put_contents("$filename", "$content"))
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
References $filename.
setTimeout()
static YAWK\sys::setTimeout ($location, $wait) static
set a timeout and force page reload via JS
Parameters
string $location the url to redirect
int $wait the time in ms to wait before redirect
Returns
bool
Definition at line 870 of file sys.php.
         {
             print"<script type=\"text/javascript\">
             setTimeout(\"self.location.href='" . $location . "'\"," . $wait . ");
             </script>
             <noscript>
              <h1>Im Browser muss javascript aktiviert sein, um die Seite richtig nutzen zu k&ouml;nnen.</h1>
             </noscript>";
             return true;
         }
Referenced by YAWK\installer\step5().
splitDate()
static YAWK\sys::splitDate ($date) static
split a date to month, day, year and time
Parameters
string $date the date to split
Returns
array return an array w single items
Definition at line 1508 of file sys.php.
         {
             $year = substr($date, 0, 4);
             $day = substr($date, 8, 2);
             $month = substr($date, 5, 2);
             $time = substr($date, 11, 5);
             /* remove leading null */
             $day = 1 * $day; // to do that, change type from string to integer
             /* calculate months */
             switch ($month) {
                 case "01":
                     $month = "January";
                     // $month = $lang['FEBRUARY'];
                     break;
                 case "02":
                     $month = "February";
                     // $month = $lang['FEBRUARY'];
                     break;
                 case "03":
                     $month = "March";
                     // $month = $lang['MARCH'];
                     break;
                 case "04":
                     $month = "April";
                     // $month = $lang['APRIL'];
                     break;
                 case "05":
                     $month = "May";
                     // $month = $lang['MAY'];
                     break;
                 case "06":
                     $month = "June";
                     // $month = $lang['JUNE'];
                     break;
                 case "07":
                     $month = "July";
                     // $month = $lang['JULY'];
                     break;
                 case "08":
                     $month = "August";
                     // $month = $lang['AUGUST'];
                     break;
                 case "09":
                     $month = "September";
                     // $month = $lang['SEPTEMBER'];
                     break;
                 case "10":
                     $month = "October";
                     // $month = $lang['OCTOBER'];
                     break;
                 case "11":
                     $month = "November";
                     // $month = $lang['NOVEMBER'];
                     break;
                 case "12":
                     $month = "December";
                     // $month = $lang['DECEMBER'];
                     break;
             }
             return $splitDate = array("year" => "$year", "day" => "$day", "month" => "$month", "time" => "$time");
         }
References $date.
Referenced by YAWK\BACKEND\AdminLTE\drawHtmlNavbarUserAccountMenu().
splitDateShort()
static YAWK\sys::splitDateShort ($date) static
split a date to month, day, year and time this is the same as splitDate() but keep the months short
Parameters
string $date the date to split
Returns
array return an array w single items
Definition at line 1578 of file sys.php.
         {
             $year = substr($date, 0, 4);
             $day = substr($date, 8, 2);
             $month = substr($date, 5, 2);
             $time = substr($date, 11, 5);
             /* remove leading null */
             $day = 1 * $day; // to do that, we change type from string to integer
             /* monate umrechnen */
             switch ($month) {
                 case "01":
                     $month = "Jan";
                     break;
                 case "02":
                     $month = "Feb";
                     break;
                 case "03":
                     $month = "Mar";
                     break;
                 case "04":
                     $month = "Apr";
                     break;
                 case "05":
                     $month = "May";
                     break;
                 case "06":
                     $month = "Jun";
                     break;
                 case "07":
                     $month = "Jul";
                     break;
                 case "08":
                     $month = "Aug";
                     break;
                 case "09":
                     $month = "Sep";
                     break;
                 case "10":
                     $month = "Okt";
                     break;
                 case "11":
                     $month = "Nov";
                     break;
                 case "12":
                     $month = "Dez";
                     break;
             }
             return $splitDate = array("year" => "$year", "day" => "$day", "month" => "$month", "time" => "$time");
         }
References $date.
Referenced by YAWK\PLUGINS\MESSAGES\messages\MessageView().
time_ago()
static YAWK\sys::time_ago ($userdate, $lang) static
how many time is been gone since given date
Parameters
string $userdate date to calculate
array $lang language array
Returns
string return how many time has gone since $userdate
Definition at line 1636 of file sys.php.
         {
             $time_ago = '';
             $date = new \DateTime($userdate);
             $diff = $date->diff(new \DateTime('now'));
             if ($t = $diff->format("%y"))
             {
                 if ($t > 1)
                 {
                     $time_ago = (int)$t . ' '.$lang['YEARS'].'';
                 }
                 else if ($t < 2)
                 {
                     $time_ago = (int)$t . ' '.$lang['YEAR'].'';
                 }
             }
             elseif ($t = $diff->format("%m"))
             {
                 if ($t > 1)
                 {
                     $time_ago = (int)$t . ' '.$lang['MONTHS'].'';
                 }
                 else if ($t < 2)
                 {
                     $time_ago = (int)$t . ' '.$lang['MONTH'].'';
                 }
             }
             elseif ($t = $diff->format("%d"))
             {
                 if ($t >= 7 && $t < 13)
                 {
                     $time_ago = $lang['A_WEEK_AGO'];
                 }
                 elseif ($t >= 14 && $t < 20)
                 {
                     $time_ago = $lang['TWO_WEEKS_AGO'];
                 }
                 elseif ($t >= 21 && $t < 27)
                 {
                     $time_ago = $lang['THREE_WEEKS_AGO'];
                 }
                 elseif ($t >= 28 && $t < 31)
                 {
                     $time_ago = $lang['FOUR_WEEKS_AGO'];
                 }
                 else if ($t > 1)
                 {
                     $time_ago = (int)$t . ' '.$lang['DAYS_P'].'';
                 }
                 else if ($t < 2)
                 {
                     $time_ago = (int)$t . ' '.$lang['DAY'].'';
                 }
             }
             elseif ($t = $diff->format("%h"))
             {
                 if ($t > 1)
                 {
                     $time_ago = (int)$t . ' '.$lang['HOURS'].'';
                 }
                 else if ($t < 2)
                 {
                     $time_ago = (int)$t . ' '.$lang['HOUR'].'';
                 }
             }
             elseif ($t = $diff->format("%i"))
             {
                 if ($t > 1)
                 {
                     $time_ago = (int)$t . ' '.$lang['MINUTES'].'';
                 }
                 else if ($t < 2)
                 {
                     $time_ago = (int)$t . ' '.$lang['MINUTE'].'';
                 }
             }
             elseif ($t = $diff->format("%s"))
             {
                 if ($t < 60)
                 {
                     $time_ago = $lang['LESS_THAN_A_MINUTE'];
                 }
             }
             // if language is german, turn around the 'ago' term
             if (\YAWK\language::getCurrentLanguageStatic() === "de-DE")
             {   // return reverse for germans
                 return $lang['AGO'] . ' '.$time_ago.'';
             }
             // default return string
             return $time_ago . ' '.$lang['AGO'].'';
         }
References $date, $lang, and YAWK\language\getCurrentLanguageStatic().
Referenced by YAWK\BACKEND\AdminLTE\drawHtmlNavbarMessagesMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarNotificationsMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarWebmailMenu(), YAWK\BACKEND\dashboard\drawLatestPagesBox(), YAWK\BACKEND\dashboard\drawLatestUsers(), and YAWK\PLUGINS\MESSAGES\messages\MessageView().
writeIniFile()
static YAWK\sys::writeIniFile ($array, $file) static
write ini file
Parameters
$array
$file
Returns
bool
Definition at line 2079 of file sys.php.
         {
             $res = array();
             foreach($array as $key => $val)
             {
                 if(is_array($val))
                 {
                     $res[] = "[$key]";
                     foreach($val as $skey => $sval) $res[] = "$skey = ".(is_numeric($sval) ? $sval : '"'.$sval.'"');
                 }
                 else $res[] = "$key = ".(is_numeric($val) ? $val : '"'.$val.'"');
             }
             if (self::safeFileReWrite($file, implode("\r\n", $res)))
             {   // ini file written
                 return true;
             }
             else
             {   // failed to return ini file
                 return false;
             }
         }
References $res.
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup(), YAWK\template\downloadTemplate(), and YAWK\BACKUP\backup\setIniFile().
xcopy()
static YAWK\sys::xcopy ($source, $dest, $permissions = 0755) static
Copy a file, or recursively copy a folder and its contents.
Author
Aidan Lister aidan.nosp@m.@php.nosp@m..net
Version
1.0.1 string $source Source path string $dest Destination path int $permissions New folder creation permissions bool Returns true on success, false on failure
Definition at line 473 of file sys.php.
         {   // Check for symlinks
             if (is_link($source))
             {
                 return symlink(readlink($source), $dest);
             }
             // Simple copy for a file
             if (is_file($source))
             {
                 if (copy($source, $dest) === false)
                 {
                     return false;
                 }
             }
             // Make destination directory
             if (!is_dir($dest))
             {
                 if (!@mkdir($dest, $permissions)) {
                     // $error = error_get_last();
                     return false;
                 }
             }
             // Loop through the folder
             if(!is_dir($source))
             {
                 return false;
             }
             else
             {
                 $dir = dir($source);
                 while (false !== $entry = $dir->read())
                 {
                     // Skip pointers
                     if ($entry == '.' || $entry == '..')
                     {
                         continue;
                     }
                     // Deep copy directories
                     if (self::xcopy("$source/$entry", "$dest/$entry", $permissions))
                     {
                         // return false;
                     }
                 }
                 // Clean up
                 $dir->close();
                 return true;
             }
         }
Referenced by YAWK\BACKUP\FILES\fileBackup\copyFolder(), YAWK\BACKUP\backup\doRestore(), YAWK\template\downloadTemplate(), YAWK\template\saveAs(), and YAWK\template\uploadTemplate().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/sys.php