YaWK: YAWK\WIDGETS\PREZI\EMBED\prezi Class Reference
YAWK\WIDGETS\PREZI\EMBED\prezi Class Reference
Prezi Widget - embed any prezi presentation on your page.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embedPrezi ()
embed prezi
init ()
Init and embed prezi widget.
markup ()
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$preziHeading = ''
$preziHtml = ''
$preziSubtext = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Prezi Widget - embed any prezi presentation on your page.
Prezi Widget - embed a prezi presentation on your page.
Prezi is a modern presentation tool. With this widget, you can embed any prezi on your page.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 15 of file prezi.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\PREZI\EMBED\prezi::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 31 of file prezi.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embedPrezi()
YAWK\WIDGETS\PREZI\EMBED\prezi::embedPrezi ()
embed prezi
Html Markup to embed the prezi presentation
Definition at line 56 of file prezi.php.
         {   // check if html markup is set and valid
             if (isset($this->preziHtml)
                 && (!empty($this->preziHtml))
                 && (is_string($this->preziHtml)))
             {   // output html markup
                 echo $this->preziHtml;
             }
References YAWK\WIDGETS\PREZI\EMBED\prezi\$preziHtml.
Referenced by YAWK\WIDGETS\PREZI\EMBED\prezi\init().
init()
YAWK\WIDGETS\PREZI\EMBED\prezi::init ()
Init and embed prezi widget.
Example Widget Init
Definition at line 45 of file prezi.php.
         {   // display heading
             echo $this->getHeading($this->preziHeading, $this->preziSubtext);
             // output prezi html code
             $this->embedPrezi();
References YAWK\WIDGETS\PREZI\EMBED\prezi\embedPrezi(), and YAWK\widget\getHeading().
markup()
YAWK\WIDGETS\PREZI\EMBED\prezi::markup ()
Definition at line 66 of file prezi.php.
         {
             /*
             echo '<iframe
                     id="iframe_container"
                     frameborder="0"
                     webkitallowfullscreen=""
                     mozallowfullscreen=""
                     allowfullscreen=""
                     allow="autoplay; fullscreen"
                     width="550"
                     height="400"
                     src="https://prezi.com/embed/dcjy1eieemjl/?bgcolor=ffffff&lock_to_path=0&autoplay=0&autohide_ctrls=0&landing_data=bHVZZmNaNDBIWnNjdEVENDRhZDFNZGNIUE43MHdLNWpsdFJLb2ZHanI0a2R3cmd5QVhqMWtLTUV3TGZnN0pNcGRnPT0&landing_sign=Z8VjbmSXPfIR-zdmkFLgkDRZEu-EjHRhVugJALWgv6M">
                   </iframe>';
             */
Member Data Documentation
$preziHeading
YAWK\WIDGETS\PREZI\EMBED\prezi::$preziHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 22 of file prezi.php.
$preziHtml
YAWK\WIDGETS\PREZI\EMBED\prezi::$preziHtml = ''
Parameters
string Prezi HTML Markup
Definition at line 20 of file prezi.php.
Referenced by YAWK\WIDGETS\PREZI\EMBED\prezi\embedPrezi().
$preziSubtext
YAWK\WIDGETS\PREZI\EMBED\prezi::$preziSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 24 of file prezi.php.
$widget
YAWK\WIDGETS\PREZI\EMBED\prezi::$widget = ''
Parameters
object global widget object data
Definition at line 18 of file prezi.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/prezi/classes/prezi.php