YaWK: YAWK\PLUGINS\SIGNUP\buildForm Class Reference
YAWK\PLUGINS\SIGNUP\buildForm Class Reference
Public Member Functions
buildForm ($db)
loads the header, layout and footer of the form
getAdditionalFields ($db)
draw html output of all additional fields
getFooter ()
html form footer (closing tag)
getForm ($db)
build the form
getHeader ()
get form header
getLayout ($db)
build form on depending layout
getLegend ($db)
get form legend
getMandatoryFields ()
draw html output: all mandatory fields
getSubmitButton ($db)
draw the submit button
getTerms ($db)
draw html output: checkbox for terms of service
getTitle ($db)
get form title
init ($db)
initialize form (build it)
Public Member Functions inherited from YAWK\PLUGINS\SIGNUP\signup
__construct ()
signup constructor.
Public Attributes
$form = ''
$html = ''
Public Attributes inherited from YAWK\PLUGINS\SIGNUP\signup
$userpage
Additional Inherited Members
Static Public Member Functions inherited from YAWK\PLUGINS\SIGNUP\signup
static signUp ($db)
draw html output adultcheck or form on demand
Protected Attributes inherited from YAWK\PLUGINS\SIGNUP\signup
$form
$html
$signup
$username
Detailed Description
Class buildForm
serve all methods to draw the user signup form
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Version
1.0.0
Definition at line 9 of file buildForm.php.
Member Function Documentation
buildForm()
YAWK\PLUGINS\SIGNUP\buildForm::buildForm ($db)
loads the header, layout and footer of the form
Parameters
object $db database
Returns
string return html form
Definition at line 31 of file buildForm.php.
{
             $this->form .= $this->getHeader();
             $this->form .= $this->getLayout($db);
             $this->form .= $this->getFooter();
             return $this->form;
         }
References $db, YAWK\PLUGINS\SIGNUP\buildForm\$form, YAWK\PLUGINS\SIGNUP\buildForm\getFooter(), YAWK\PLUGINS\SIGNUP\buildForm\getHeader(), and YAWK\PLUGINS\SIGNUP\buildForm\getLayout().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\init().
getAdditionalFields()
YAWK\PLUGINS\SIGNUP\buildForm::getAdditionalFields ($db)
draw html output of all additional fields
Parameters
object $db database
Definition at line 217 of file buildForm.php.
{
             // get additional field settings from db
             $firstname = \YAWK\settings::getSetting($db, "signup_firstname");
             $lastname = \YAWK\settings::getSetting($db, "signup_lastname");
             $street = \YAWK\settings::getSetting($db, "signup_street");
             $zipcode = \YAWK\settings::getSetting($db, "signup_zipcode");
             $city = \YAWK\settings::getSetting($db, "signup_city");
             $country = \YAWK\settings::getSetting($db, "signup_country");
             // check if fields are required
             if ($firstname ==='1'){
                 $this->html .= "<label for=\"firstname\">Firstname</label>
                             <input type=\"text\" id=\"firstname\" name=\"firstname\" class=\"form-control\" placeholder=\"Vorname\">";
             }
             if ($lastname ==='1'){
                 $this->html .= "<label for=\"lastname\">Lastname</label>
                             <input type=\"text\" id=\"lastname\" name=\"lastname\" class=\"form-control\" placeholder=\"Nachname\">";
             }
             if ($street ==='1'){
                 $this->html .= "<label for=\"street\">Street</label>
                             <input type=\"text\" id=\"street\" name=\"street\" class=\"form-control\" placeholder=\"Stra&szlig;e\">";
             }
             if ($zipcode ==='1'){
                 $this->html .= "<label for=\"zipcode\">ZIP Code</label>
                             <input type=\"text\" id=\"zipcode\" name=\"zipcode\" class=\"form-control\" placeholder=\"Postleitzahl\">";
             }
             if ($city ==='1'){
                 $this->html .= "<label for=\"city\">City</label>
                             <input type=\"text\" id=\"city\" name=\"city\" class=\"form-control\" placeholder=\"Stadt\">";
             }
             if ($country ==='1'){
                 $this->html .= "<label for=\"country\">Country</label>
                             <input type=\"text\" id=\"country\" name=\"country\" class=\"form-control\" placeholder=\"Land\">";
             }
         }
References $city, $country, $db, $firstname, $lastname, $street, $zipcode, and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getForm().
getFooter()
YAWK\PLUGINS\SIGNUP\buildForm::getFooter ()
html form footer (closing tag)
Definition at line 152 of file buildForm.php.
{
             // form end
             $this->html .= "</form>";
         }
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\buildForm().
getForm()
YAWK\PLUGINS\SIGNUP\buildForm::getForm ($db)
build the form
Parameters
object $db database
Returns
string return html form
Definition at line 43 of file buildForm.php.
{
             $this->form .= $this->getGroupSelect($db);
             $this->form .= $this->getMandatoryFields();
             $this->form .= $this->getAdditionalFields($db);
             $this->form .= $this->getTerms($db);
             $this->form .= $this->getSubmitButton($db);
             return $this->form;
         }
References $db, YAWK\PLUGINS\SIGNUP\buildForm\$form, YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields(), YAWK\PLUGINS\SIGNUP\buildForm\getMandatoryFields(), YAWK\PLUGINS\SIGNUP\buildForm\getSubmitButton(), and YAWK\PLUGINS\SIGNUP\buildForm\getTerms().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getLayout().
getHeader()
YAWK\PLUGINS\SIGNUP\buildForm::getHeader ()
get form header
Definition at line 55 of file buildForm.php.
         {
             // form header
             $this->html .= "<form id=\"form\" action=\"welcome.html\" method=\"POST\">";
         }
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\buildForm().
getLayout()
YAWK\PLUGINS\SIGNUP\buildForm::getLayout ($db)
build form on depending layout
Parameters
object $db database
Definition at line 107 of file buildForm.php.
         {
             // get selected form layout (left, right, 1,2, or 3 cols...)
             $layout = \YAWK\settings::getSetting($db, "signup_layout");
             // layout row
             // switch case layout and load corresponding htmlcode
             switch ($layout) {
                 case "left":
                     // form title
                     $this->html .= "<div class=\"col-md-6\">";
                     $this->html .= self::getLegend($db);
                     $this->html .= "</div>";
                     $this->html .= "<div class=\"col-md-6\">";
                     $this->html .= self::getTitle($db);
                     $this->html .= self::getForm($db);
                     $this->html .= "</div>";
                     break;
                 case "right":
                     $this->html .= "<div class=\"col-md-6\">";
                     $this->html .= self::getTitle($db);
                     $this->html .= self::getForm($db);
                     $this->html .= "</div><div class=\"col-md-6\">";
                     $this->html .= self::getLegend($db);
                     $this->html .= "</div>";
                     break;
                 case "plain":
                     $this->html .= "<div class=\"col-lg-12\">";
                     $this->html .= self::getTitle($db);
                     $this->html .= self::getForm($db);
                     $this->html .= "</div>";
                     break;
                 case "center":
                     $this->html .= "<div class=\"col-md-4\">&nbsp;</div>";
                     $this->html .= "<div class=\"col-md-4\">";
                     $this->html .= self::getTitle($db);
                     $this->html .= self::getForm($db);
                     $this->html .= "</div>";
                     $this->html .= "<div class=\"col-md-4\">&nbsp;</div>";
                     break;
             }
         }
References $db, $layout, YAWK\PLUGINS\SIGNUP\buildForm\getForm(), YAWK\PLUGINS\SIGNUP\buildForm\getLegend(), YAWK\settings\getSetting(), and YAWK\PLUGINS\SIGNUP\buildForm\getTitle().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\buildForm().
getLegend()
YAWK\PLUGINS\SIGNUP\buildForm::getLegend ($db)
get form legend
Parameters
object $db database
Definition at line 75 of file buildForm.php.
         {
                 // gid 0 form legend (public) -- default --
                 $this->html .= "<div id=\"0_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend0");
                 $this->html .= "</div>";
                 // gid 1 form legend (guest)
                 $this->html .= "<div id=\"1_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend1");
                 $this->html .= "</div>";
                 // gid 1 form legend (guest)
                 $this->html .= "<div id=\"2_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend2");
                 $this->html .= "</div>";
                 // gid 1 form legend (guest)
                 $this->html .= "<div id=\"3_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend3");
                 $this->html .= "</div>";
                 // gid 1 form legend (guest)
                 $this->html .= "<div id=\"4_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend4");
                 $this->html .= "</div>";
                 // gid 1 form legend (guest)
                 $this->html .= "<div id=\"5_hidden\">";
                 $this->html .= \YAWK\settings::getLongSetting($db, "signup_legend5");
                 $this->html .= "</div>";
         }
References $db, and YAWK\settings\getLongSetting().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getLayout().
getMandatoryFields()
YAWK\PLUGINS\SIGNUP\buildForm::getMandatoryFields ()
draw html output: all mandatory fields
Definition at line 186 of file buildForm.php.
{
             $this->html .= "<label for=\"username\">Username</label>
                             <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" placeholder=\"Benutzername\">
                             <label for=\"email\">Email</label>
                             <input type=\"text\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"your@email.com\">
                             <label for=\"password1\">Password</label>
                             <input type=\"password\" id=\"password1\" name=\"password1\" class=\"form-control\" placeholder=\"Passwort\">
                             <label for=\"password2\">Password (repeat)</label>
                             <input type=\"password\" id=\"password2\" name=\"password2\" class=\"form-control\" placeholder=\"Passwort wiederholen\">
                             <input type=\"hidden\" name=\"sent\" value=\"1\">";
         }
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getForm().
getSubmitButton()
YAWK\PLUGINS\SIGNUP\buildForm::getSubmitButton ($db)
draw the submit button
Parameters
object $db database
Definition at line 256 of file buildForm.php.
{
             // get selected form layout (left, right, 1,2, or 3 cols...)
             $layout = \YAWK\settings::getSetting($db, "signup_layout");
             $btnStyle = \YAWK\settings::getSetting($db, "signup_submitstyle");
             $btnText = \YAWK\settings::getSetting($db, "signup_submittext");
             if ($layout === 'center' or $layout === 'plain'){
                 $this->html .= "<div class=\"text-center\"><input type=\"submit\" class=\"btn btn-$btnStyle\" value=\"$btnText\"></div>";
             } else {
                 $this->html .= "<br><input type=\"submit\" class=\"btn btn-$btnStyle\" value=\"$btnText\">";
             }
         }
References $db, $layout, and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getForm().
getTerms()
YAWK\PLUGINS\SIGNUP\buildForm::getTerms ($db)
draw html output: checkbox for terms of service
Parameters
$db
Definition at line 205 of file buildForm.php.
{
             $this->html .= "<input type=\"checkbox\" id=\"checkTerms\" name=\"checkTerms\" class=\"form-control\" checked=\"checked\">
                              <div class=\"text-center\">
                                <label for=\"checkTerms\">
                                <a target=\"_blank\" style=\"color:#";$this->html .= \YAWK\settings::getSetting($db, "signup_toscolor");$this->html .= "\" href=\"";$this->html .= \YAWK\settings::getSetting($db, "signup_tospage");$this->html .= ".html\">";$this->html .= \YAWK\settings::getSetting($db, "signup_tostext"); $this->html .= "</a> akzeptieren</label>
                              </div>";
         }
References $db, and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getForm().
getTitle()
YAWK\PLUGINS\SIGNUP\buildForm::getTitle ($db)
get form title
Parameters
object $db database
Definition at line 65 of file buildForm.php.
         {
             // form title
             $this->html .= \YAWK\settings::getSetting($db, "signup_title");
         }
References $db, and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getLayout().
init()
YAWK\PLUGINS\SIGNUP\buildForm::init ($db)
initialize form (build it)
Parameters
object $db database
Returns
string return html code
Definition at line 21 of file buildForm.php.
{
             $this->form = $this->buildForm($db);
             return $this->html;
         }
References $db, YAWK\PLUGINS\SIGNUP\buildForm\$html, and YAWK\PLUGINS\SIGNUP\buildForm\buildForm().
Member Data Documentation
$form
YAWK\PLUGINS\SIGNUP\buildForm::$form = ''
Parameters
string html form
Definition at line 14 of file buildForm.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\buildForm(), and YAWK\PLUGINS\SIGNUP\buildForm\getForm().
$html
YAWK\PLUGINS\SIGNUP\buildForm::$html = ''
Parameters
string html output
Definition at line 12 of file buildForm.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\init().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/plugins/signup/classes/buildForm.php