YaWK: PHPMailer Class Reference
PHPMailer Class Reference
Public Member Functions
__construct ($exceptions=false)
__destruct ()
addAddress ($address, $name='')
addAttachment ($path, $name='', $encoding='base64', $type='', $disposition='attachment')
addBCC ($address, $name='')
addCC ($address, $name='')
addCustomHeader ($name, $value=null)
addEmbeddedImage ($path, $cid, $name='', $encoding='base64', $type='', $disposition='inline')
addrAppend ($type, $addr)
addReplyTo ($address, $name='')
addrFormat ($addr)
addStringAttachment ($string, $filename, $encoding='base64', $type='', $disposition='attachment')
addStringEmbeddedImage ($string, $cid, $name='', $encoding='base64', $type='', $disposition='inline')
alternativeExists ()
attachmentExists ()
base64EncodeWrapMB ($str, $linebreak=null)
clearAddresses ()
clearAllRecipients ()
clearAttachments ()
clearBCCs ()
clearCCs ()
clearCustomHeaders ()
clearReplyTos ()
createBody ()
createHeader ()
DKIM_Add ($headers_line, $subject, $body)
DKIM_BodyC ($body)
DKIM_HeaderC ($signHeader)
DKIM_QP ($txt)
DKIM_Sign ($signHeader)
encodeHeader ($str, $position='text')
encodeQ ($str, $position='text')
encodeQP ($string, $line_max=76)
encodeQPphp ($string, $line_max=76, $space_conv=false)
encodeString ($str, $encoding='base64')
fixEOL ($str)
getAllRecipientAddresses ()
getAttachments ()
getBccAddresses ()
getCcAddresses ()
getLastMessageID ()
getMailMIME ()
getReplyToAddresses ()
getSentMIMEMessage ()
getSMTPInstance ()
getToAddresses ()
getTranslations ()
has8bitChars ($text)
hasMultiBytes ($str)
headerLine ($name, $value)
html2text ($html, $advanced=false)
inlineImageExists ()
isError ()
isHTML ($isHtml=true)
isMail ()
isQmail ()
isSendmail ()
isSMTP ()
msgHTML ($message, $basedir='', $advanced=false)
postSend ()
preSend ()
secureHeader ($str)
send ()
set ($name, $value='')
setFrom ($address, $name='', $auto=true)
setLanguage ($langcode='en', $lang_path='')
setWordWrap ()
sign ($cert_filename, $key_filename, $key_pass)
smtpClose ()
smtpConnect ($options=array())
textLine ($value)
utf8CharBoundary ($encodedText, $maxLength)
wrapText ($message, $length, $qp_mode=false)
Static Public Member Functions
static _mime_types ($ext='')
static filenameToType ($filename)
static mb_pathinfo ($path, $options=null)
static normalizeBreaks ($text, $breaktype="\r\n")
static rfcDate ()
static validateAddress ($address, $patternselect='auto')
Public Attributes
$action_function = ''
$AllowEmpty = false
$AltBody = ''
$AuthType = ''
$Body = ''
$CharSet = 'iso-8859-1'
$ConfirmReadingTo = ''
$ContentType = 'text/plain'
$Debugoutput = 'echo'
$DKIM_domain = ''
$DKIM_identity = ''
$DKIM_passphrase = ''
$DKIM_private = ''
$DKIM_selector = ''
$do_verp = false
$Encoding = '8bit'
$ErrorInfo = ''
$From = 'root@localhost'
$FromName = 'Root User'
$Helo = ''
$Host = 'localhost'
$Hostname = ''
$Ical = ''
$LE = "\n"
$Mailer = 'mail'
$MessageDate = ''
$MessageID = ''
$Password = ''
$PluginDir = ''
$Port = 25
$Priority = 3
$Realm = ''
$ReturnPath = ''
$Sender = ''
$Sendmail = '/usr/sbin/sendmail'
$SingleTo = false
$SingleToArray = array()
$SMTPAuth = false
$SMTPDebug = 0
$SMTPKeepAlive = false
$SMTPSecure = ''
$Subject = ''
$Timeout = 10
$Username = ''
$UseSendmailOptions = true
$Version = '5.2.8'
$WordWrap = 0
$Workstation = ''
$XMailer = ''
const CRLF = "\r\n"
const STOP_CONTINUE = 1
const STOP_CRITICAL = 2
const STOP_MESSAGE = 0
Protected Member Functions
addAnAddress ($kind, $address, $name='')
attachAll ($disposition_type, $boundary)
doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from)
edebug ($str)
encodeFile ($path, $encoding='base64')
endBoundary ($boundary)
getBoundary ($boundary, $charSet, $contentType, $encoding)
lang ($key)
mailSend ($header, $body)
sendmailSend ($header, $body)
serverHostname ()
setError ($msg)
setMessageType ()
smtpSend ($header, $body)
Protected Attributes
$all_recipients = array()
$attachment = array()
$bcc = array()
$boundary = array()
$cc = array()
$CustomHeader = array()
$error_count = 0
$exceptions = false
$language = array()
$lastMessageID = ''
$mailHeader = ''
$message_type = ''
$MIMEBody = ''
$MIMEHeader = ''
$ReplyTo = array()
$sign_cert_file = ''
$sign_key_file = ''
$sign_key_pass = ''
$smtp = null
$to = array()
Private Member Functions
mailPassthru ($to, $subject, $body, $header, $params)
Detailed Description
Definition at line 28 of file class.phpmailer.php.
Constructor & Destructor Documentation
__construct()
PHPMailer::__construct ($exceptions = false)
Constructor.
Parameters
boolean $exceptions Should we throw external exceptions?
Definition at line 576 of file class.phpmailer.php.
     {
         $this->exceptions = ($exceptions == true);
     }
References $exceptions.
__destruct()
PHPMailer::__destruct ()
Destructor.
Definition at line 584 of file class.phpmailer.php.
     {
         if ($this->Mailer == 'smtp') { //close any open SMTP connection nicely
             $this->smtpClose();
         }
     }
References smtpClose().
Member Function Documentation
_mime_types()
static PHPMailer::_mime_types ($ext = '') static
Get the MIME type for a file extension.
Parameters
string $ext File extension @access public
Returns
string MIME type of file.
Definition at line 2984 of file class.phpmailer.php.
     {
         $mimes = array(
             'xl' => 'application/excel',
             'hqx' => 'application/mac-binhex40',
             'cpt' => 'application/mac-compactpro',
             'bin' => 'application/macbinary',
             'doc' => 'application/msword',
             'word' => 'application/msword',
             'class' => 'application/octet-stream',
             'dll' => 'application/octet-stream',
             'dms' => 'application/octet-stream',
             'exe' => 'application/octet-stream',
             'lha' => 'application/octet-stream',
             'lzh' => 'application/octet-stream',
             'psd' => 'application/octet-stream',
             'sea' => 'application/octet-stream',
             'so' => 'application/octet-stream',
             'oda' => 'application/oda',
             'pdf' => 'application/pdf',
             'ai' => 'application/postscript',
             'eps' => 'application/postscript',
             'ps' => 'application/postscript',
             'smi' => 'application/smil',
             'smil' => 'application/smil',
             'mif' => 'application/vnd.mif',
             'xls' => 'application/vnd.ms-excel',
             'ppt' => 'application/vnd.ms-powerpoint',
             'wbxml' => 'application/vnd.wap.wbxml',
             'wmlc' => 'application/vnd.wap.wmlc',
             'dcr' => 'application/x-director',
             'dir' => 'application/x-director',
             'dxr' => 'application/x-director',
             'dvi' => 'application/x-dvi',
             'gtar' => 'application/x-gtar',
             'php3' => 'application/x-httpd-php',
             'php4' => 'application/x-httpd-php',
             'php' => 'application/x-httpd-php',
             'phtml' => 'application/x-httpd-php',
             'phps' => 'application/x-httpd-php-source',
             'js' => 'application/x-javascript',
             'swf' => 'application/x-shockwave-flash',
             'sit' => 'application/x-stuffit',
             'tar' => 'application/x-tar',
             'tgz' => 'application/x-tar',
             'xht' => 'application/xhtml+xml',
             'xhtml' => 'application/xhtml+xml',
             'zip' => 'application/zip',
             'mid' => 'audio/midi',
             'midi' => 'audio/midi',
             'mp2' => 'audio/mpeg',
             'mp3' => 'audio/mpeg',
             'mpga' => 'audio/mpeg',
             'aif' => 'audio/x-aiff',
             'aifc' => 'audio/x-aiff',
             'aiff' => 'audio/x-aiff',
             'ram' => 'audio/x-pn-realaudio',
             'rm' => 'audio/x-pn-realaudio',
             'rpm' => 'audio/x-pn-realaudio-plugin',
             'ra' => 'audio/x-realaudio',
             'wav' => 'audio/x-wav',
             'bmp' => 'image/bmp',
             'gif' => 'image/gif',
             'jpeg' => 'image/jpeg',
             'jpe' => 'image/jpeg',
             'jpg' => 'image/jpeg',
             'png' => 'image/png',
             'tiff' => 'image/tiff',
             'tif' => 'image/tiff',
             'eml' => 'message/rfc822',
             'css' => 'text/css',
             'html' => 'text/html',
             'htm' => 'text/html',
             'shtml' => 'text/html',
             'log' => 'text/plain',
             'text' => 'text/plain',
             'txt' => 'text/plain',
             'rtx' => 'text/richtext',
             'rtf' => 'text/rtf',
             'vcf' => 'text/vcard',
             'vcard' => 'text/vcard',
             'xml' => 'text/xml',
             'xsl' => 'text/xml',
             'mpeg' => 'video/mpeg',
             'mpe' => 'video/mpeg',
             'mpg' => 'video/mpeg',
             'mov' => 'video/quicktime',
             'qt' => 'video/quicktime',
             'rv' => 'video/vnd.rn-realvideo',
             'avi' => 'video/x-msvideo',
             'movie' => 'video/x-sgi-movie'
         );
         return (array_key_exists(strtolower($ext), $mimes) ? $mimes[strtolower($ext)]: 'application/octet-stream');
     }
Referenced by filenameToType().
addAddress()
PHPMailer::addAddress ($address, $name = '')
Add a "To" address.
Parameters
string $address
string $name
Returns
boolean true on success, false if address already used
Definition at line 732 of file class.phpmailer.php.
     {
         return $this->addAnAddress('to', $address, $name);
     }
References $name, and addAnAddress().
addAnAddress()
PHPMailer::addAnAddress ($kind, $address, $name = '') protected
Add an address to one of the recipient arrays. Addresses that have been added already return false, but do not throw exceptions
Parameters
string $kind One of 'to', 'cc', 'bcc', 'ReplyTo'
string $address The email address to send to
string $name
Exceptions
phpmailerException
Returns
boolean true on success, false if address already used or invalid in some way @access protected
Definition at line 782 of file class.phpmailer.php.
     {
         if (!preg_match('/^(to|cc|bcc|Reply-To)$/', $kind)) {
             $this->setError($this->lang('Invalid recipient array') . ': ' . $kind);
             $this->edebug($this->lang('Invalid recipient array') . ': ' . $kind);
             if ($this->exceptions) {
                 throw new phpmailerException('Invalid recipient array: ' . $kind);
             }
             return false;
         }
         $address = trim($address);
         $name = trim(preg_replace('/[\r\n]+/', '', $name)); //Strip breaks and trim
         if (!$this->validateAddress($address)) {
             $this->setError($this->lang('invalid_address') . ': ' . $address);
             $this->edebug($this->lang('invalid_address') . ': ' . $address);
             if ($this->exceptions) {
                 throw new phpmailerException($this->lang('invalid_address') . ': ' . $address);
             }
             return false;
         }
         if ($kind != 'Reply-To') {
             if (!isset($this->all_recipients[strtolower($address)])) {
                 array_push($this->$kind, array($address, $name));
                 $this->all_recipients[strtolower($address)] = true;
                 return true;
             }
         } else {
             if (!array_key_exists(strtolower($address), $this->ReplyTo)) {
                 $this->ReplyTo[strtolower($address)] = array($address, $name);
                 return true;
             }
         }
         return false;
     }
References $name, edebug(), lang(), setError(), and validateAddress().
Referenced by addAddress(), addBCC(), addCC(), and addReplyTo().
addAttachment()
PHPMailer::addAttachment ($path, $name = '', $encoding = 'base64', $type = '', $disposition = 'attachment')
Add an attachment from a path on the filesystem. Returns false if the file could not be found or read.
Parameters
string $path Path to the attachment.
string $name Overrides the attachment name.
string $encoding File encoding (see $Encoding).
string $type File extension (MIME) type.
string $disposition Disposition to use
Exceptions
phpmailerException
Returns
boolean
Definition at line 2070 of file class.phpmailer.php.
     {
         try {
             if (!@is_file($path)) {
                 throw new phpmailerException($this->lang('file_access') . $path, self::STOP_CONTINUE);
             }
             // If a MIME type is not specified, try to work it out from the file name
             if ($type == '') {
                 $type = self::filenameToType($path);
             }
             $filename = basename($path);
             if ($name == '') {
                 $name = $filename;
             }
             $this->attachment[] = array(
                 0 => $path,
                 1 => $filename,
                 2 => $name,
                 3 => $encoding,
                 4 => $type,
                 5 => false, // isStringAttachment
                 6 => $disposition,
                 7 => 0
             );
         } catch (phpmailerException $exc) {
             $this->setError($exc->getMessage());
             $this->edebug($exc->getMessage());
             if ($this->exceptions) {
                 throw $exc;
             }
             return false;
         }
         return true;
     }
References $filename, $name, $type, edebug(), filenameToType(), lang(), and setError().
addBCC()
PHPMailer::addBCC ($address, $name = '')
Add a "BCC" address.
Note
: This function works with the SMTP mailer on win32, not with the "mail" mailer.
Parameters
string $address
string $name
Returns
boolean true on success, false if address already used
Definition at line 756 of file class.phpmailer.php.
     {
         return $this->addAnAddress('bcc', $address, $name);
     }
References $name, and addAnAddress().
addCC()
PHPMailer::addCC ($address, $name = '')
Add a "CC" address.
Note
: This function works with the SMTP mailer on win32, not with the "mail" mailer.
Parameters
string $address
string $name
Returns
boolean true on success, false if address already used
Definition at line 744 of file class.phpmailer.php.
     {
         return $this->addAnAddress('cc', $address, $name);
     }
References $name, and addAnAddress().
addCustomHeader()
PHPMailer::addCustomHeader ($name, $value = null)
Add a custom header. $name value can be overloaded to contain both header name and value (name:value) @access public
Parameters
string $name Custom header name
string $value Header value
Returns
void
Definition at line 2873 of file class.phpmailer.php.
     {
         if ($value === null) {
             // Value passed in as name:value
             $this->CustomHeader[] = explode(':', $name, 2);
         } else {
             $this->CustomHeader[] = array($name, $value);
         }
     }
References $name, and $value.
addEmbeddedImage()
PHPMailer::addEmbeddedImage ($path, $cid, $name = '', $encoding = 'base64', $type = '', $disposition = 'inline')
Add an embedded (inline) attachment from a file. This can include images, sounds, and just about any other document type. These differ from 'regular' attachmants in that they are intended to be displayed inline with the message, not just attached for download. This is used in HTML messages that embed the images the HTML refers to using the $cid value.
Parameters
string $path Path to the attachment.
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML.
string $name Overrides the attachment name.
string $encoding File encoding (see $Encoding).
string $type File MIME type.
string $disposition Disposition to use
Returns
boolean True on successfully adding an attachment
Definition at line 2579 of file class.phpmailer.php.
     {
         if (!@is_file($path)) {
             $this->setError($this->lang('file_access') . $path);
             return false;
         }
         // If a MIME type is not specified, try to work it out from the file name
         if ($type == '') {
             $type = self::filenameToType($path);
         }
         $filename = basename($path);
         if ($name == '') {
             $name = $filename;
         }
         // Append to $attachment array
         $this->attachment[] = array(
             0 => $path,
             1 => $filename,
             2 => $name,
             3 => $encoding,
             4 => $type,
             5 => false, // isStringAttachment
             6 => $disposition,
             7 => $cid
         );
         return true;
     }
References $filename, $name, $type, filenameToType(), lang(), and setError().
Referenced by msgHTML().
addrAppend()
PHPMailer::addrAppend ($type, $addr)
Create recipient headers. @access public
Parameters
string $type
array $addr An array of recipient, where each recipient is a 2-element indexed array with element 0 containing an address and element 1 containing a name, like: array(array('joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User'), array('zoe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Zoe User'))
Returns
string
Definition at line 1455 of file class.phpmailer.php.
     {
         $addresses = array();
         foreach ($addr as $address) {
             $addresses[] = $this->addrFormat($address);
         }
         return $type . ': ' . implode(', ', $addresses) . $this->LE;
     }
References $LE, $type, addrFormat(), and as.
Referenced by createHeader(), and preSend().
addReplyTo()
PHPMailer::addReplyTo ($address, $name = '')
Add a "Reply-to" address.
Parameters
string $address
string $name
Returns
boolean
Definition at line 767 of file class.phpmailer.php.
     {
         return $this->addAnAddress('Reply-To', $address, $name);
     }
References $name, and addAnAddress().
addrFormat()
PHPMailer::addrFormat ($addr)
Format an address for use in a message header. @access public
Parameters
array $addr A 2-element indexed array, element 0 containing an address, element 1 containing a name like array('joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User')
Returns
string
Definition at line 1471 of file class.phpmailer.php.
     {
         if (empty($addr[1])) { // No name provided
             return $this->secureHeader($addr[0]);
         } else {
             return $this->encodeHeader($this->secureHeader($addr[1]), 'phrase') . ' <' . $this->secureHeader(
                 $addr[0]
             ) . '>';
         }
     }
References encodeHeader(), and secureHeader().
Referenced by addrAppend(), createHeader(), and mailSend().
addStringAttachment()
PHPMailer::addStringAttachment ($string, $filename, $encoding = 'base64', $type = '', $disposition = 'attachment')
Add a string or binary attachment (non-filesystem). This method can be used to attach ascii or binary data, such as a BLOB record from a database.
Parameters
string $string String attachment data.
string $filename Name of the attachment.
string $encoding File encoding (see $Encoding).
string $type File extension (MIME) type.
string $disposition Disposition to use
Returns
void
Definition at line 2539 of file class.phpmailer.php.
       {
         // If a MIME type is not specified, try to work it out from the file name
         if ($type == '') {
             $type = self::filenameToType($filename);
         }
         // Append to $attachment array
         $this->attachment[] = array(
             0 => $string,
             1 => $filename,
             2 => basename($filename),
             3 => $encoding,
             4 => $type,
             5 => true, // isStringAttachment
             6 => $disposition,
             7 => 0
         );
     }
References $filename, $type, and filenameToType().
addStringEmbeddedImage()
PHPMailer::addStringEmbeddedImage ($string, $cid, $name = '', $encoding = 'base64', $type = '', $disposition = 'inline')
Add an embedded stringified attachment. This can include images, sounds, and just about any other document type. Be sure to set the $type to an image type for images: JPEG images use 'image/jpeg', GIF uses 'image/gif', PNG uses 'image/png'.
Parameters
string $string The attachment binary data.
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML.
string $name
string $encoding File encoding (see $Encoding).
string $type MIME type.
string $disposition Disposition to use
Returns
boolean True on successfully adding an attachment
Definition at line 2624 of file class.phpmailer.php.
       {
         // If a MIME type is not specified, try to work it out from the name
         if ($type == '') {
             $type = self::filenameToType($name);
         }
         // Append to $attachment array
         $this->attachment[] = array(
             0 => $string,
             1 => $name,
             2 => $name,
             3 => $encoding,
             4 => $type,
             5 => true, // isStringAttachment
             6 => $disposition,
             7 => $cid
         );
         return true;
     }
References $name, $type, and filenameToType().
Referenced by msgHTML().
alternativeExists()
PHPMailer::alternativeExists ()
Check if this message has an alternative body set.
Returns
boolean
Definition at line 2684 of file class.phpmailer.php.
     {
         return !empty($this->AltBody);
     }
References AltBody.
Referenced by setMessageType().
attachAll()
PHPMailer::attachAll ($disposition_type, $boundary) protected
Attach all file, string, and binary attachments to the message. Returns an empty string on failure. @access protected
Parameters
string $disposition_type
string $boundary
Returns
string
Definition at line 2126 of file class.phpmailer.php.
     {
         // Return text of body
         $mime = array();
         $cidUniq = array();
         $incl = array();
         // Add all attachments
         foreach ($this->attachment as $attachment) {
             // Check if it is a valid disposition_filter
             if ($attachment[6] == $disposition_type) {
                 // Check for string attachment
                 $string = '';
                 $path = '';
                 $bString = $attachment[5];
                 if ($bString) {
                     $string = $attachment[0];
                 } else {
                     $path = $attachment[0];
                 }
                 $inclhash = md5(serialize($attachment));
                 if (in_array($inclhash, $incl)) {
                     continue;
                 }
                 $incl[] = $inclhash;
                 $name = $attachment[2];
                 $encoding = $attachment[3];
                 $type = $attachment[4];
                 $disposition = $attachment[6];
                 $cid = $attachment[7];
                 if ($disposition == 'inline' && isset($cidUniq[$cid])) {
                     continue;
                 }
                 $cidUniq[$cid] = true;
                 $mime[] = sprintf('--%s%s', $boundary, $this->LE);
                 $mime[] = sprintf(
                     'Content-Type: %s; name="%s"%s',
                     $type,
                     $this->encodeHeader($this->secureHeader($name)),
                     $this->LE
                 );
                 // RFC1341 part 5 says 7bit is assumed if not specified
                 if ($encoding != '7bit') {
                     $mime[] = sprintf('Content-Transfer-Encoding: %s%s', $encoding, $this->LE);
                 }
                 if ($disposition == 'inline') {
                     $mime[] = sprintf('Content-ID: <%s>%s', $cid, $this->LE);
                 }
                 // If a filename contains any of these chars, it should be quoted,
                 // but not otherwise: RFC2183 & RFC2045 5.1
                 // Fixes a warning in IETF's msglint MIME checker
                 // Allow for bypassing the Content-Disposition header totally
                 if (!(empty($disposition))) {
                     $encoded_name = $this->encodeHeader($this->secureHeader($name));
                     if (preg_match('/[ \‍(\‍)<>@,;:\\"\/\[\]\?=]/', $encoded_name)) {
                         $mime[] = sprintf(
                             'Content-Disposition: %s; filename="%s"%s',
                             $disposition,
                             $encoded_name,
                             $this->LE . $this->LE
                         );
                     } else {
                         $mime[] = sprintf(
                             'Content-Disposition: %s; filename=%s%s',
                             $disposition,
                             $encoded_name,
                             $this->LE . $this->LE
                         );
                     }
                 } else {
                     $mime[] = $this->LE;
                 }
                 // Encode as string attachment
                 if ($bString) {
                     $mime[] = $this->encodeString($string, $encoding);
                     if ($this->isError()) {
                         return '';
                     }
                     $mime[] = $this->LE . $this->LE;
                 } else {
                     $mime[] = $this->encodeFile($path, $encoding);
                     if ($this->isError()) {
                         return '';
                     }
                     $mime[] = $this->LE . $this->LE;
                 }
             }
         }
         $mime[] = sprintf('--%s--%s', $boundary, $this->LE);
         return implode('', $mime);
     }
References $attachment, $boundary, $LE, $name, $type, as, encodeFile(), encodeHeader(), encodeString(), isError(), and secureHeader().
Referenced by createBody().
attachmentExists()
PHPMailer::attachmentExists ()
Check if an attachment (non-inline) is present.
Returns
boolean
Definition at line 2670 of file class.phpmailer.php.
     {
         foreach ($this->attachment as $attachment) {
             if ($attachment[6] == 'attachment') {
                 return true;
             }
         }
         return false;
     }
References $attachment, and as.
Referenced by setMessageType().
base64EncodeWrapMB()
PHPMailer::base64EncodeWrapMB ($str, $linebreak = null)
Encode and wrap long multibyte strings for mail headers without breaking lines within a character. Adapted from a function by paravoid public string $str multi-byte text to wrap encode string $linebreak string to use as linefeed/end-of-line string
Definition at line 2404 of file class.phpmailer.php.
     {
         $start = '=?' . $this->CharSet . '?B?';
         $end = '?=';
         $encoded = '';
         if ($linebreak === null) {
             $linebreak = $this->LE;
         }
         $mb_length = mb_strlen($str, $this->CharSet);
         // Each line must have length <= 75, including $start and $end
         $length = 75 - strlen($start) - strlen($end);
         // Average multi-byte ratio
         $ratio = $mb_length / strlen($str);
         // Base64 has a 4:3 ratio
         $avgLength = floor($length * $ratio * .75);
         for ($i = 0; $i < $mb_length; $i += $offset) {
             $lookBack = 0;
             do {
                 $offset = $avgLength - $lookBack;
                 $chunk = mb_substr($str, $i, $offset, $this->CharSet);
                 $chunk = base64_encode($chunk);
                 $lookBack++;
             } while (strlen($chunk) > $length);
             $encoded .= $chunk . $linebreak;
         }
         // Chomp the last linefeed
         $encoded = substr($encoded, 0, -strlen($linebreak));
         return $encoded;
     }
References $i, and $LE.
Referenced by encodeHeader().
clearAddresses()
PHPMailer::clearAddresses ()
Clear all To recipients.
Returns
void
Definition at line 2693 of file class.phpmailer.php.
     {
         foreach ($this->to as $to) {
             unset($this->all_recipients[strtolower($to[0])]);
         }
         $this->to = array();
     }
References $to, as, and to.
clearAllRecipients()
PHPMailer::clearAllRecipients ()
Clear all recipient types.
Returns
void
Definition at line 2738 of file class.phpmailer.php.
     {
         $this->to = array();
         $this->cc = array();
         $this->bcc = array();
         $this->all_recipients = array();
     }
References to.
clearAttachments()
PHPMailer::clearAttachments ()
Clear all filesystem, string, and binary attachments.
Returns
void
Definition at line 2750 of file class.phpmailer.php.
     {
         $this->attachment = array();
     }
clearBCCs()
PHPMailer::clearBCCs ()
Clear all BCC recipients.
Returns
void
Definition at line 2717 of file class.phpmailer.php.
     {
         foreach ($this->bcc as $bcc) {
             unset($this->all_recipients[strtolower($bcc[0])]);
         }
         $this->bcc = array();
     }
References $bcc, and as.
clearCCs()
PHPMailer::clearCCs ()
Clear all CC recipients.
Returns
void
Definition at line 2705 of file class.phpmailer.php.
     {
         foreach ($this->cc as $cc) {
             unset($this->all_recipients[strtolower($cc[0])]);
         }
         $this->cc = array();
     }
References $cc, and as.
clearCustomHeaders()
PHPMailer::clearCustomHeaders ()
Clear all custom headers.
Returns
void
Definition at line 2759 of file class.phpmailer.php.
     {
         $this->CustomHeader = array();
     }
clearReplyTos()
PHPMailer::clearReplyTos ()
Clear all ReplyTo recipients.
Returns
void
Definition at line 2729 of file class.phpmailer.php.
     {
         $this->ReplyTo = array();
     }
createBody()
PHPMailer::createBody ()
Assemble the message body. Returns an empty string on failure. @access public
Exceptions
phpmailerException
Returns
string The assembled message body
Definition at line 1812 of file class.phpmailer.php.
     {
         $body = '';
         if ($this->sign_key_file) {
             $body .= $this->getMailMIME() . $this->LE;
         }
         $this->setWordWrap();
         $bodyEncoding = $this->Encoding;
         $bodyCharSet = $this->CharSet;
         if ($bodyEncoding == '8bit' and !$this->has8bitChars($this->Body)) {
             $bodyEncoding = '7bit';
             $bodyCharSet = 'us-ascii';
         }
         $altBodyEncoding = $this->Encoding;
         $altBodyCharSet = $this->CharSet;
         if ($altBodyEncoding == '8bit' and !$this->has8bitChars($this->AltBody)) {
             $altBodyEncoding = '7bit';
             $altBodyCharSet = 'us-ascii';
         }
         switch ($this->message_type) {
             case 'inline':
                 $body .= $this->getBoundary($this->boundary[1], $bodyCharSet, '', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->attachAll('inline', $this->boundary[1]);
                 break;
             case 'attach':
                 $body .= $this->getBoundary($this->boundary[1], $bodyCharSet, '', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->attachAll('attachment', $this->boundary[1]);
                 break;
             case 'inline_attach':
                 $body .= $this->textLine('--' . $this->boundary[1]);
                 $body .= $this->headerLine('Content-Type', 'multipart/related;');
                 $body .= $this->textLine("\tboundary=\"" . $this->boundary[2] . '"');
                 $body .= $this->LE;
                 $body .= $this->getBoundary($this->boundary[2], $bodyCharSet, '', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->attachAll('inline', $this->boundary[2]);
                 $body .= $this->LE;
                 $body .= $this->attachAll('attachment', $this->boundary[1]);
                 break;
             case 'alt':
                 $body .= $this->getBoundary($this->boundary[1], $altBodyCharSet, 'text/plain', $altBodyEncoding);
                 $body .= $this->encodeString($this->AltBody, $altBodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->getBoundary($this->boundary[1], $bodyCharSet, 'text/html', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 if (!empty($this->Ical)) {
                     $body .= $this->getBoundary($this->boundary[1], '', 'text/calendar; method=REQUEST', '');
                     $body .= $this->encodeString($this->Ical, $this->Encoding);
                     $body .= $this->LE . $this->LE;
                 }
                 $body .= $this->endBoundary($this->boundary[1]);
                 break;
             case 'alt_inline':
                 $body .= $this->getBoundary($this->boundary[1], $altBodyCharSet, 'text/plain', $altBodyEncoding);
                 $body .= $this->encodeString($this->AltBody, $altBodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->textLine('--' . $this->boundary[1]);
                 $body .= $this->headerLine('Content-Type', 'multipart/related;');
                 $body .= $this->textLine("\tboundary=\"" . $this->boundary[2] . '"');
                 $body .= $this->LE;
                 $body .= $this->getBoundary($this->boundary[2], $bodyCharSet, 'text/html', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->attachAll('inline', $this->boundary[2]);
                 $body .= $this->LE;
                 $body .= $this->endBoundary($this->boundary[1]);
                 break;
             case 'alt_attach':
                 $body .= $this->textLine('--' . $this->boundary[1]);
                 $body .= $this->headerLine('Content-Type', 'multipart/alternative;');
                 $body .= $this->textLine("\tboundary=\"" . $this->boundary[2] . '"');
                 $body .= $this->LE;
                 $body .= $this->getBoundary($this->boundary[2], $altBodyCharSet, 'text/plain', $altBodyEncoding);
                 $body .= $this->encodeString($this->AltBody, $altBodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->getBoundary($this->boundary[2], $bodyCharSet, 'text/html', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->endBoundary($this->boundary[2]);
                 $body .= $this->LE;
                 $body .= $this->attachAll('attachment', $this->boundary[1]);
                 break;
             case 'alt_inline_attach':
                 $body .= $this->textLine('--' . $this->boundary[1]);
                 $body .= $this->headerLine('Content-Type', 'multipart/alternative;');
                 $body .= $this->textLine("\tboundary=\"" . $this->boundary[2] . '"');
                 $body .= $this->LE;
                 $body .= $this->getBoundary($this->boundary[2], $altBodyCharSet, 'text/plain', $altBodyEncoding);
                 $body .= $this->encodeString($this->AltBody, $altBodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->textLine('--' . $this->boundary[2]);
                 $body .= $this->headerLine('Content-Type', 'multipart/related;');
                 $body .= $this->textLine("\tboundary=\"" . $this->boundary[3] . '"');
                 $body .= $this->LE;
                 $body .= $this->getBoundary($this->boundary[3], $bodyCharSet, 'text/html', $bodyEncoding);
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 $body .= $this->LE . $this->LE;
                 $body .= $this->attachAll('inline', $this->boundary[3]);
                 $body .= $this->LE;
                 $body .= $this->endBoundary($this->boundary[2]);
                 $body .= $this->LE;
                 $body .= $this->attachAll('attachment', $this->boundary[1]);
                 break;
             default:
                 // catch case 'plain' and case ''
                 $body .= $this->encodeString($this->Body, $bodyEncoding);
                 break;
         }
         if ($this->isError()) {
             $body = '';
         } elseif ($this->sign_key_file) {
             try {
                 if (!defined('PKCS7_TEXT')) {
                     throw new phpmailerException($this->lang('signing') . ' OpenSSL extension missing.');
                 }
                 // @TODO would be nice to use php://temp streams here, but need to wrap for PHP < 5.1
                 $file = tempnam(sys_get_temp_dir(), 'mail');
                 file_put_contents($file, $body); // @TODO check this worked
                 $signed = tempnam(sys_get_temp_dir(), 'signed');
                 if (@openssl_pkcs7_sign(
                     $file,
                     $signed,
                     'file://' . realpath($this->sign_cert_file),
                     array('file://' . realpath($this->sign_key_file), $this->sign_key_pass),
                     null
                 )
                 ) {
                     @unlink($file);
                     $body = file_get_contents($signed);
                     @unlink($signed);
                 } else {
                     @unlink($file);
                     @unlink($signed);
                     throw new phpmailerException($this->lang('signing') . openssl_error_string());
                 }
             } catch (phpmailerException $exc) {
                 $body = '';
                 if ($this->exceptions) {
                     throw $exc;
                 }
             }
         }
         return $body;
     }
References $CharSet, $Encoding, $LE, AltBody, attachAll(), Body, encodeString(), endBoundary(), getBoundary(), getMailMIME(), has8bitChars(), headerLine(), isError(), lang(), setWordWrap(), and textLine().
Referenced by preSend().
createHeader()
PHPMailer::createHeader ()
Assemble message headers. @access public
Returns
string The assembled headers
Definition at line 1643 of file class.phpmailer.php.
     {
         $result = '';
         // Set the boundaries
         $uniq_id = md5(uniqid(time()));
         $this->boundary[1] = 'b1_' . $uniq_id;
         $this->boundary[2] = 'b2_' . $uniq_id;
         $this->boundary[3] = 'b3_' . $uniq_id;
         if ($this->MessageDate == '') {
             $this->MessageDate = self::rfcDate();
         }
         $result .= $this->headerLine('Date', $this->MessageDate);
         // To be created automatically by mail()
         if ($this->SingleTo === true) {
             if ($this->Mailer != 'mail') {
                 foreach ($this->to as $toaddr) {
                     $this->SingleToArray[] = $this->addrFormat($toaddr);
                 }
             }
         } else {
             if (count($this->to) > 0) {
                 if ($this->Mailer != 'mail') {
                     $result .= $this->addrAppend('To', $this->to);
                 }
             } elseif (count($this->cc) == 0) {
                 $result .= $this->headerLine('To', 'undisclosed-recipients:;');
             }
         }
         $result .= $this->addrAppend('From', array(array(trim($this->From), $this->FromName)));
         // sendmail and mail() extract Cc from the header before sending
         if (count($this->cc) > 0) {
             $result .= $this->addrAppend('Cc', $this->cc);
         }
         // sendmail and mail() extract Bcc from the header before sending
         if ((
                 $this->Mailer == 'sendmail' or $this->Mailer == 'qmail' or $this->Mailer == 'mail'
             )
             and count($this->bcc) > 0
         ) {
             $result .= $this->addrAppend('Bcc', $this->bcc);
         }
         if (count($this->ReplyTo) > 0) {
             $result .= $this->addrAppend('Reply-To', $this->ReplyTo);
         }
         // mail() sets the subject itself
         if ($this->Mailer != 'mail') {
             $result .= $this->headerLine('Subject', $this->encodeHeader($this->secureHeader($this->Subject)));
         }
         if ($this->MessageID != '') {
             $this->lastMessageID = $this->MessageID;
         } else {
             $this->lastMessageID = sprintf('<%s@%s>', $uniq_id, $this->ServerHostname());
         }
         $result .= $this->HeaderLine('Message-ID', $this->lastMessageID);
         $result .= $this->headerLine('X-Priority', $this->Priority);
         if ($this->XMailer == '') {
             $result .= $this->headerLine(
                 'X-Mailer',
                 'PHPMailer ' . $this->Version . ' (https://github.com/PHPMailer/PHPMailer/)'
             );
         } else {
             $myXmailer = trim($this->XMailer);
             if ($myXmailer) {
                 $result .= $this->headerLine('X-Mailer', $myXmailer);
             }
         }
         if ($this->ConfirmReadingTo != '') {
             $result .= $this->headerLine('Disposition-Notification-To', '<' . trim($this->ConfirmReadingTo) . '>');
         }
         // Add custom headers
         for ($index = 0; $index < count($this->CustomHeader); $index++) {
             $result .= $this->headerLine(
                 trim($this->CustomHeader[$index][0]),
                 $this->encodeHeader(trim($this->CustomHeader[$index][1]))
             );
         }
         if (!$this->sign_key_file) {
             $result .= $this->headerLine('MIME-Version', '1.0');
             $result .= $this->getMailMIME();
         }
         return $result;
     }
References $MessageID, $result, addrAppend(), addrFormat(), as, encodeHeader(), getMailMIME(), headerLine(), rfcDate(), secureHeader(), Subject, and to.
Referenced by preSend().
DKIM_Add()
PHPMailer::DKIM_Add ($headers_line, $subject, $body)
Create the DKIM header and body in a new message header. @access public
Parameters
string $headers_line Header lines
string $subject Subject
string $body Body
Returns
string
Definition at line 3312 of file class.phpmailer.php.
     {
         $DKIMsignatureType = 'rsa-sha1'; // Signature & hash algorithms
         $DKIMcanonicalization = 'relaxed/simple'; // Canonicalization of header/body
         $DKIMquery = 'dns/txt'; // Query method
         $DKIMtime = time(); // Signature Timestamp = seconds since 00:00:00 - Jan 1, 1970 (UTC time zone)
         $subject_header = "Subject: $subject";
         $headers = explode($this->LE, $headers_line);
         $from_header = '';
         $to_header = '';
         $current = '';
         foreach ($headers as $header) {
             if (strpos($header, 'From:') === 0) {
                 $from_header = $header;
                 $current = 'from_header';
             } elseif (strpos($header, 'To:') === 0) {
                 $to_header = $header;
                 $current = 'to_header';
             } else {
                 if ($current && strpos($header, ' =?') === 0) {
                     $current .= $header;
                 } else {
                     $current = '';
                 }
             }
         }
         $from = str_replace('|', '=7C', $this->DKIM_QP($from_header));
         $to = str_replace('|', '=7C', $this->DKIM_QP($to_header));
         $subject = str_replace(
             '|',
             '=7C',
             $this->DKIM_QP($subject_header)
         ); // Copied header fields (dkim-quoted-printable)
         $body = $this->DKIM_BodyC($body);
         $DKIMlen = strlen($body); // Length of body
         $DKIMb64 = base64_encode(pack('H*', sha1($body))); // Base64 of packed binary SHA-1 hash of body
         $ident = ($this->DKIM_identity == '') ? '' : ' i=' . $this->DKIM_identity . ';';
         $dkimhdrs = 'DKIM-Signature: v=1; a=' .
             $DKIMsignatureType . '; q=' .
             $DKIMquery . '; l=' .
             $DKIMlen . '; s=' .
             $this->DKIM_selector .
             ";\r\n" .
             "\tt=" . $DKIMtime . '; c=' . $DKIMcanonicalization . ";\r\n" .
             "\th=From:To:Subject;\r\n" .
             "\td=" . $this->DKIM_domain . ';' . $ident . "\r\n" .
             "\tz=$from\r\n" .
             "\t|$to\r\n" .
             "\t|$subject;\r\n" .
             "\tbh=" . $DKIMb64 . ";\r\n" .
             "\tb=";
         $toSign = $this->DKIM_HeaderC(
             $from_header . "\r\n" . $to_header . "\r\n" . $subject_header . "\r\n" . $dkimhdrs
         );
         $signed = $this->DKIM_Sign($toSign);
         return $dkimhdrs . $signed . "\r\n";
     }
References $header, $to, as, DKIM_BodyC(), DKIM_HeaderC(), DKIM_QP(), and DKIM_Sign().
Referenced by preSend().
DKIM_BodyC()
PHPMailer::DKIM_BodyC ($body)
Generate a DKIM canonicalization body. @access public
Parameters
string $body Message Body
Returns
string
Definition at line 3289 of file class.phpmailer.php.
     {
         if ($body == '') {
             return "\r\n";
         }
         // stabilize line endings
         $body = str_replace("\r\n", "\n", $body);
         $body = str_replace("\n", "\r\n", $body);
         // END stabilize line endings
         while (substr($body, strlen($body) - 4, 4) == "\r\n\r\n") {
             $body = substr($body, 0, strlen($body) - 2);
         }
         return $body;
     }
Referenced by DKIM_Add().
DKIM_HeaderC()
PHPMailer::DKIM_HeaderC ($signHeader)
Generate a DKIM canonicalization header. @access public
Parameters
string $signHeader Header
Returns
string
Definition at line 3269 of file class.phpmailer.php.
     {
         $signHeader = preg_replace('/\r\n\s+/', ' ', $signHeader);
         $lines = explode("\r\n", $signHeader);
         foreach ($lines as $key => $line) {
             list($heading, $value) = explode(':', $line, 2);
             $heading = strtolower($heading);
             $value = preg_replace('/\s+/', ' ', $value); // Compress useless spaces
             $lines[$key] = $heading . ':' . trim($value); // Don't forget to remove WSP around the value
         }
         $signHeader = implode("\r\n", $lines);
         return $signHeader;
     }
References $heading, $value, as, and list.
Referenced by DKIM_Add().
DKIM_QP()
PHPMailer::DKIM_QP ($txt)
Quoted-Printable-encode a DKIM header. @access public
Parameters
string $txt
Returns
string
Definition at line 3222 of file class.phpmailer.php.
     {
         $line = '';
         for ($i = 0; $i < strlen($txt); $i++) {
             $ord = ord($txt[$i]);
             if (((0x21 <= $ord) && ($ord <= 0x3A)) || $ord == 0x3C || ((0x3E <= $ord) && ($ord <= 0x7E))) {
                 $line .= $txt[$i];
             } else {
                 $line .= '=' . sprintf('%02X', $ord);
             }
         }
         return $line;
     }
References $i.
Referenced by DKIM_Add().
DKIM_Sign()
PHPMailer::DKIM_Sign ($signHeader)
Generate a DKIM signature. @access public
Parameters
string $signHeader
Exceptions
phpmailerException
Returns
string
Definition at line 3243 of file class.phpmailer.php.
     {
         if (!defined('PKCS7_TEXT')) {
             if ($this->exceptions) {
                 throw new phpmailerException($this->lang('signing') . ' OpenSSL extension missing.');
             }
             return '';
         }
         $privKeyStr = file_get_contents($this->DKIM_private);
         if ($this->DKIM_passphrase != '') {
             $privKey = openssl_pkey_get_private($privKeyStr, $this->DKIM_passphrase);
         } else {
             $privKey = $privKeyStr;
         }
         if (openssl_sign($signHeader, $signature, $privKey)) {
             return base64_encode($signature);
         }
         return '';
     }
References lang().
Referenced by DKIM_Add().
doCallback()
PHPMailer::doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from) protected
Perform a callback.
Parameters
boolean $isSent
array $to
array $cc
array $bcc
string $subject
string $body
string $from
Definition at line 3430 of file class.phpmailer.php.
     {
         if (!empty($this->action_function) && is_callable($this->action_function)) {
             $params = array($isSent, $to, $cc, $bcc, $subject, $body, $from);
             call_user_func_array($this->action_function, $params);
         }
     }
References $bcc, $cc, and $to.
Referenced by mailSend(), sendmailSend(), and smtpSend().
edebug()
PHPMailer::edebug ($str) protected
Output debugging info via user-defined method. Only generates output if SMTP debug output is enabled (
See also
SMTP::$do_debug).
PHPMailer::$Debugoutput
PHPMailer::$SMTPDebug
Parameters
string $str
Definition at line 627 of file class.phpmailer.php.
     {
         if ($this->SMTPDebug <= 0) {
             return;
         }
         if (is_callable($this->Debugoutput)) {
             call_user_func($this->Debugoutput, $str, $this->SMTPDebug);
             return;
         }
         switch ($this->Debugoutput) {
             case 'error_log':
                 //Don't output, just log
                 error_log($str);
                 break;
             case 'html':
                 //Cleans up output a bit for a better looking, HTML-safe output
                 echo htmlentities(
                     preg_replace('/[\r\n]+/', '', $str),
                     ENT_QUOTES,
                     'UTF-8'
                 )
                 . "<br>\n";
                 break;
             case 'echo':
             default:
                 //Normalize line breaks
                 $str = preg_replace('/(\r\n|\r|\n)/ms', "\n", $str);
                 echo gmdate('Y-m-d H:i:s') . "\t" . str_replace(
                     "\n",
                     "\n                   \t                  ",
                     trim($str)
                 ) . "\n";
         }
     }
Referenced by addAnAddress(), addAttachment(), postSend(), and setFrom().
encodeFile()
PHPMailer::encodeFile ($path, $encoding = 'base64') protected
Encode a file attachment in requested format. Returns an empty string on failure.
Parameters
string $path The full path to the file
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable'
Exceptions
phpmailerException
See also
EncodeFile(encodeFile @access protected
Returns
string
Definition at line 2235 of file class.phpmailer.php.
     {
         try {
             if (!is_readable($path)) {
                 throw new phpmailerException($this->lang('file_open') . $path, self::STOP_CONTINUE);
             }
             $magic_quotes = get_magic_quotes_runtime();
             if ($magic_quotes) {
                 if (version_compare(PHP_VERSION, '5.3.0', '<')) {
                     set_magic_quotes_runtime(false);
                 } else {
                     //Doesn't exist in PHP 5.4, but we don't need to check because
                     //get_magic_quotes_runtime always returns false in 5.4+
                     //so it will never get here
                     ini_set('magic_quotes_runtime', 0);
                 }
             }
             $file_buffer = file_get_contents($path);
             $file_buffer = $this->encodeString($file_buffer, $encoding);
             if ($magic_quotes) {
                 if (version_compare(PHP_VERSION, '5.3.0', '<')) {
                     set_magic_quotes_runtime($magic_quotes);
                 } else {
                     ini_set('magic_quotes_runtime', ($magic_quotes?'1':'0'));
                 }
             }
             return $file_buffer;
         } catch (Exception $exc) {
             $this->setError($exc->getMessage());
             return '';
         }
     }
References encodeString(), lang(), and setError().
Referenced by attachAll().
encodeHeader()
PHPMailer::encodeHeader ($str, $position = 'text')
Encode a header string optimally. Picks shortest of Q, B, quoted-printable or none. @access public
Parameters
string $str
string $position
Returns
string
@noinspection PhpMissingBreakStatementInspection
Definition at line 2312 of file class.phpmailer.php.
     {
         $matchcount = 0;
         switch (strtolower($position)) {
             case 'phrase':
                 if (!preg_match('/[\200-\377]/', $str)) {
                     // Can't use addslashes as we don't know the value of magic_quotes_sybase
                     $encoded = addcslashes($str, "\0..\37\177\\\"");
                     if (($str == $encoded) && !preg_match('/[^A-Za-z0-9!#$%&\'*+\/=?^_`{|}~ -]/', $str)) {
                         return ($encoded);
                     } else {
                         return ("\"$encoded\"");
                     }
                 }
                 $matchcount = preg_match_all('/[^\040\041\043-\133\135-\176]/', $str, $matches);
                 break;
             /** @noinspection PhpMissingBreakStatementInspection */
             case 'comment':
                 $matchcount = preg_match_all('/[()"]/', $str, $matches);
                 // Intentional fall-through
             case 'text':
             default:
                 $matchcount += preg_match_all('/[\000-\010\013\014\016-\037\177-\377]/', $str, $matches);
                 break;
         }
         if ($matchcount == 0) { // There are no chars that need encoding
             return ($str);
         }
         $maxlen = 75 - 7 - strlen($this->CharSet);
         // Try to select the encoding which should produce the shortest output
         if ($matchcount > strlen($str) / 3) {
             // More than a third of the content will need encoding, so B encoding will be most efficient
             $encoding = 'B';
             if (function_exists('mb_strlen') && $this->hasMultiBytes($str)) {
                 // Use a custom function which correctly encodes and wraps long
                 // multibyte strings without breaking lines within a character
                 $encoded = $this->base64EncodeWrapMB($str, "\n");
             } else {
                 $encoded = base64_encode($str);
                 $maxlen -= $maxlen % 4;
                 $encoded = trim(chunk_split($encoded, $maxlen, "\n"));
             }
         } else {
             $encoding = 'Q';
             $encoded = $this->encodeQ($str, $position);
             $encoded = $this->wrapText($encoded, $maxlen, true);
             $encoded = str_replace('=' . self::CRLF, "\n", trim($encoded));
         }
         $encoded = preg_replace('/^(.*)$/m', ' =?' . $this->CharSet . "?$encoding?\\1?=", $encoded);
         $encoded = trim(str_replace("\n", $this->LE, $encoded));
         return $encoded;
     }
References $position, base64EncodeWrapMB(), encodeQ(), hasMultiBytes(), and wrapText().
Referenced by addrFormat(), attachAll(), createHeader(), mailPassthru(), and preSend().
encodeQ()
PHPMailer::encodeQ ($str, $position = 'text')
Encode a string using Q encoding. string $str the text to encode string $position Where the text is going to be used, see the RFC for what that means public string
@noinspection PhpMissingBreakStatementInspection
Definition at line 2487 of file class.phpmailer.php.
     {
         // There should not be any EOL in the string
         $pattern = '';
         $encoded = str_replace(array("\r", "\n"), '', $str);
         switch (strtolower($position)) {
             case 'phrase':
                 // RFC 2047 section 5.3
                 $pattern = '^A-Za-z0-9!*+\/ -';
                 break;
             /** @noinspection PhpMissingBreakStatementInspection */
             case 'comment':
                 // RFC 2047 section 5.2
                 $pattern = '\‍(\‍)"';
                 // intentional fall-through
                 // for this reason we build the $pattern without including delimiters and []
             case 'text':
             default:
                 // RFC 2047 section 5.1
                 // Replace every high ascii, control, =, ? and _ characters
                 $pattern = '\000-\011\013\014\016-\037\075\077\137\177-\377' . $pattern;
                 break;
         }
         $matches = array();
         if (preg_match_all("/[{$pattern}]/", $encoded, $matches)) {
             // If the string contains an '=', make sure it's the first thing we replace
             // so as to avoid double-encoding
             $eqkey = array_search('=', $matches[0]);
             if ($eqkey !== false) {
                 unset($matches[0][$eqkey]);
                 array_unshift($matches[0], '=');
             }
             foreach (array_unique($matches[0]) as $char) {
                 $encoded = str_replace($char, '=' . sprintf('%02X', ord($char)), $encoded);
             }
         }
         // Replace every spaces to _ (more readable than =20)
         return str_replace(' ', '_', $encoded);
     }
References $position, and as.
Referenced by encodeHeader().
encodeQP()
PHPMailer::encodeQP ($string, $line_max = 76)
Encode a string in quoted-printable format. According to RFC2045 section 6.7. @access public
Parameters
string $string The text to encode
integer $line_max Number of chars allowed on a line before wrapping
Returns
string Adapted from this comment
Definition at line 2446 of file class.phpmailer.php.
     {
         if (function_exists('quoted_printable_encode')) { // Use native function if it's available (>= PHP5.3)
             return $this->fixEOL(quoted_printable_encode($string));
         }
         // Fall back to a pure PHP implementation
         $string = str_replace(
             array('%20', '%0D%0A.', '%0D%0A', '%'),
             array(' ', "\r\n=2E", "\r\n", '='),
             rawurlencode($string)
         );
         $string = preg_replace('/[^\r\n]{' . ($line_max - 3) . '}[^=\r\n]{2}/', "$0=\r\n", $string);
         return $this->fixEOL($string);
     }
References fixEOL().
Referenced by encodeQPphp(), and encodeString().
encodeQPphp()
PHPMailer::encodeQPphp ($string, $line_max = 76, $space_conv = false)
Backward compatibility wrapper for an old QP encoding function that was removed.
See also
PHPMailer::encodeQP() @access public
Parameters
string $string
integer $line_max
boolean $space_conv
Returns
string
Deprecated:
Use encodeQP instead.
Parameters
$space_conv @noinspection PhpUnusedParameterInspection
Definition at line 2471 of file class.phpmailer.php.
       {
         return $this->encodeQP($string, $line_max);
     }
References encodeQP().
encodeString()
PHPMailer::encodeString ($str, $encoding = 'base64')
Encode a string in requested format. Returns an empty string on failure.
Parameters
string $str The text to encode
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable' @access public
Returns
string
Definition at line 2276 of file class.phpmailer.php.
     {
         $encoded = '';
         switch (strtolower($encoding)) {
             case 'base64':
                 $encoded = chunk_split(base64_encode($str), 76, $this->LE);
                 break;
             case '7bit':
             case '8bit':
                 $encoded = $this->fixEOL($str);
                 // Make sure it ends with a line break
                 if (substr($encoded, -(strlen($this->LE))) != $this->LE) {
                     $encoded .= $this->LE;
                 }
                 break;
             case 'binary':
                 $encoded = $str;
                 break;
             case 'quoted-printable':
                 $encoded = $this->encodeQP($str);
                 break;
             default:
                 $this->setError($this->lang('encoding') . $encoding);
                 break;
         }
         return $encoded;
     }
References $LE, encodeQP(), fixEOL(), lang(), and setError().
Referenced by attachAll(), createBody(), and encodeFile().
endBoundary()
PHPMailer::endBoundary ($boundary) protected
Return the end of a message boundary. @access protected
Parameters
string $boundary
Returns
string
Definition at line 2006 of file class.phpmailer.php.
     {
         return $this->LE . '--' . $boundary . '--' . $this->LE;
     }
References $boundary, and $LE.
Referenced by createBody().
filenameToType()
static PHPMailer::filenameToType ($filename) static
Map a file name to a MIME type. Defaults to 'application/octet-stream', i.e.. arbitrary binary data.
Parameters
string $filename A file name or full path, does not need to exist as a file
Returns
string
Definition at line 3086 of file class.phpmailer.php.
     {
         // In case the path is a URL, strip any query string before getting extension
         $qpos = strpos($filename, '?');
         if ($qpos !== false) {
             $filename = substr($filename, 0, $qpos);
         }
         $pathinfo = self::mb_pathinfo($filename);
         return self::_mime_types($pathinfo['extension']);
     }
References $filename, _mime_types(), and mb_pathinfo().
Referenced by addAttachment(), addEmbeddedImage(), addStringAttachment(), and addStringEmbeddedImage().
fixEOL()
PHPMailer::fixEOL ($str)
Ensure consistent line endings in a string. Changes every end of line from CRLF, CR or LF to $this->LE. @access public
Parameters
string $str String to fixEOL
Returns
string
Definition at line 2853 of file class.phpmailer.php.
     {
         // Normalise to \n
         $nstr = str_replace(array("\r\n", "\r"), "\n", $str);
         // Now convert LE as needed
         if ($this->LE !== "\n") {
             $nstr = str_replace("\n", $this->LE, $nstr);
         }
         return $nstr;
     }
Referenced by encodeQP(), encodeString(), and wrapText().
getAllRecipientAddresses()
PHPMailer::getAllRecipientAddresses ()
Allows for public read access to 'all_recipients' property. @access public
Returns
array
Definition at line 3415 of file class.phpmailer.php.
     {
         return $this->all_recipients;
     }
References $all_recipients.
getAttachments()
PHPMailer::getAttachments ()
Return the array of attachments.
Returns
array
Definition at line 2113 of file class.phpmailer.php.
     {
         return $this->attachment;
     }
References $attachment.
getBccAddresses()
PHPMailer::getBccAddresses ()
Allows for public read access to 'bcc' property. @access public
Returns
array
Definition at line 3395 of file class.phpmailer.php.
     {
         return $this->bcc;
     }
References $bcc.
getBoundary()
PHPMailer::getBoundary ($boundary, $charSet, $contentType, $encoding) protected
Return the start of a message boundary. @access protected
Parameters
string $boundary
string $charSet
string $contentType
string $encoding
Returns
string
Definition at line 1976 of file class.phpmailer.php.
     {
         $result = '';
         if ($charSet == '') {
             $charSet = $this->CharSet;
         }
         if ($contentType == '') {
             $contentType = $this->ContentType;
         }
         if ($encoding == '') {
             $encoding = $this->Encoding;
         }
         $result .= $this->textLine('--' . $boundary);
         $result .= sprintf('Content-Type: %s; charset=%s', $contentType, $charSet);
         $result .= $this->LE;
         // RFC1341 part 5 says 7bit is assumed if not specified
         if ($encoding != '7bit') {
             $result .= $this->headerLine('Content-Transfer-Encoding', $encoding);
         }
         $result .= $this->LE;
         return $result;
     }
References $boundary, $CharSet, $ContentType, $Encoding, $LE, $result, headerLine(), and textLine().
Referenced by createBody().
getCcAddresses()
PHPMailer::getCcAddresses ()
Allows for public read access to 'cc' property. @access public
Returns
array
Definition at line 3385 of file class.phpmailer.php.
     {
         return $this->cc;
     }
References $cc.
getLastMessageID()
PHPMailer::getLastMessageID ()
Return the Message-ID header of the last email. Technically this is the value from the last time the headers were created, but it's also the message ID of the last sent message except in pathological cases.
Returns
string
Definition at line 854 of file class.phpmailer.php.
     {
         return $this->lastMessageID;
     }
References $lastMessageID.
getMailMIME()
PHPMailer::getMailMIME ()
Get the message MIME type headers. @access public
Returns
string
Definition at line 1744 of file class.phpmailer.php.
     {
         $result = '';
         $ismultipart = true;
         switch ($this->message_type) {
             case 'inline':
                 $result .= $this->headerLine('Content-Type', 'multipart/related;');
                 $result .= $this->textLine("\tboundary=\"" . $this->boundary[1] . '"');
                 break;
             case 'attach':
             case 'inline_attach':
             case 'alt_attach':
             case 'alt_inline_attach':
                 $result .= $this->headerLine('Content-Type', 'multipart/mixed;');
                 $result .= $this->textLine("\tboundary=\"" . $this->boundary[1] . '"');
                 break;
             case 'alt':
             case 'alt_inline':
                 $result .= $this->headerLine('Content-Type', 'multipart/alternative;');
                 $result .= $this->textLine("\tboundary=\"" . $this->boundary[1] . '"');
                 break;
             default:
                 // Catches case 'plain': and case '':
                 $result .= $this->textLine('Content-Type: ' . $this->ContentType . '; charset=' . $this->CharSet);
                 $ismultipart = false;
                 break;
         }
         // RFC1341 part 5 says 7bit is assumed if not specified
         if ($this->Encoding != '7bit') {
             // RFC 2045 section 6.4 says multipart MIME parts may only use 7bit, 8bit or binary CTE
             if ($ismultipart) {
                 if ($this->Encoding == '8bit') {
                     $result .= $this->headerLine('Content-Transfer-Encoding', '8bit');
                 }
                 // The only remaining alternatives are quoted-printable and base64, which are both 7bit compatible
             } else {
                 $result .= $this->headerLine('Content-Transfer-Encoding', $this->Encoding);
             }
         }
         if ($this->Mailer != 'mail') {
             $result .= $this->LE;
         }
         return $result;
     }
References $LE, $result, headerLine(), and textLine().
Referenced by createBody(), and createHeader().
getReplyToAddresses()
PHPMailer::getReplyToAddresses ()
Allows for public read access to 'ReplyTo' property. @access public
Returns
array
Definition at line 3405 of file class.phpmailer.php.
     {
         return $this->ReplyTo;
     }
References $ReplyTo.
getSentMIMEMessage()
PHPMailer::getSentMIMEMessage ()
Returns the whole MIME message. Includes complete headers and body. Only valid post preSend().
See also
PHPMailer::preSend() @access public
Returns
string
Definition at line 1799 of file class.phpmailer.php.
     {
         return $this->MIMEHeader . $this->mailHeader . self::CRLF . $this->MIMEBody;
     }
References $MIMEBody.
getSMTPInstance()
PHPMailer::getSMTPInstance ()
Get an instance to use for SMTP operations. Override this function to load your own SMTP implementation
Returns
SMTP
Definition at line 1191 of file class.phpmailer.php.
     {
         if (!is_object($this->smtp)) {
             $this->smtp = new SMTP;
         }
         return $this->smtp;
     }
References $smtp.
Referenced by smtpConnect().
getToAddresses()
PHPMailer::getToAddresses ()
Allows for public read access to 'to' property. @access public
Returns
array
Definition at line 3375 of file class.phpmailer.php.
     {
         return $this->to;
     }
References $to.
getTranslations()
PHPMailer::getTranslations ()
Get the array of strings for the current language.
Returns
array
Definition at line 1440 of file class.phpmailer.php.
     {
         return $this->language;
     }
References $language.
has8bitChars()
PHPMailer::has8bitChars ($text)
Does a string contain any 8-bit chars (in any charset)?
Parameters
string $text
Returns
boolean
Definition at line 2389 of file class.phpmailer.php.
     {
         return (boolean)preg_match('/[\x80-\xFF]/', $text);
     }
Referenced by createBody().
hasMultiBytes()
PHPMailer::hasMultiBytes ($str)
Check if a string contains multi-byte characters. @access public
Parameters
string $str multi-byte text to wrap encode
Returns
boolean
Definition at line 2375 of file class.phpmailer.php.
     {
         if (function_exists('mb_strlen')) {
             return (strlen($str) > mb_strlen($str, $this->CharSet));
         } else { // Assume no multibytes (we can't handle without mbstring functions anyway)
             return false;
         }
     }
Referenced by encodeHeader().
headerLine()
PHPMailer::headerLine ($name, $value)
Format a header line. @access public
Parameters
string $name
string $value
Returns
string
Definition at line 2043 of file class.phpmailer.php.
     {
         return $name . ': ' . $value . $this->LE;
     }
References $LE, $name, and $value.
Referenced by createBody(), createHeader(), getBoundary(), getMailMIME(), and preSend().
html2text()
PHPMailer::html2text ($html, $advanced = false)
Convert an HTML string into plain text.
Parameters
string $html The HTML text to convert
boolean $advanced Should this use the more complex html2text converter or just a simple one?
Returns
string
Definition at line 2963 of file class.phpmailer.php.
     {
         if ($advanced) {
             require_once 'extras/class.html2text.php';
             $htmlconverter = new html2text($html);
             return $htmlconverter->get_text();
         }
         return html_entity_decode(
             trim(strip_tags(preg_replace('/<(head|title|style|script)[^>]*>.*?<\/\\1>/si', '', $html))),
             ENT_QUOTES,
             $this->CharSet
         );
     }
Referenced by msgHTML().
inlineImageExists()
PHPMailer::inlineImageExists ()
Check if an inline attachment is present. @access public
Returns
boolean
Definition at line 2656 of file class.phpmailer.php.
     {
         foreach ($this->attachment as $attachment) {
             if ($attachment[6] == 'inline') {
                 return true;
             }
         }
         return false;
     }
References $attachment, and as.
Referenced by setMessageType().
isError()
PHPMailer::isError ()
Check if an error occurred. @access public
Returns
boolean True if an error did occur.
Definition at line 2841 of file class.phpmailer.php.
     {
         return ($this->error_count > 0);
     }
Referenced by attachAll(), and createBody().
isHTML()
PHPMailer::isHTML ($isHtml = true)
Sets message type to HTML or plain.
Parameters
boolean $isHtml True for HTML mode.
Returns
void
Definition at line 667 of file class.phpmailer.php.
     {
         if ($isHtml) {
             $this->ContentType = 'text/html';
         } else {
             $this->ContentType = 'text/plain';
         }
     }
Referenced by msgHTML().
isMail()
PHPMailer::isMail ()
Send messages using PHP's mail() function.
Returns
void
Definition at line 689 of file class.phpmailer.php.
     {
         $this->Mailer = 'mail';
     }
isQmail()
PHPMailer::isQmail ()
Send messages using qmail.
Returns
void
Definition at line 714 of file class.phpmailer.php.
     {
         $ini_sendmail_path = ini_get('sendmail_path');
         if (!stristr($ini_sendmail_path, 'qmail')) {
             $this->Sendmail = '/var/qmail/bin/qmail-inject';
         } else {
             $this->Sendmail = $ini_sendmail_path;
         }
         $this->Mailer = 'qmail';
     }
isSendmail()
PHPMailer::isSendmail ()
Send messages using $Sendmail.
Returns
void
Definition at line 698 of file class.phpmailer.php.
     {
         $ini_sendmail_path = ini_get('sendmail_path');
         if (!stristr($ini_sendmail_path, 'sendmail')) {
             $this->Sendmail = '/usr/sbin/sendmail';
         } else {
             $this->Sendmail = $ini_sendmail_path;
         }
         $this->Mailer = 'sendmail';
     }
isSMTP()
PHPMailer::isSMTP ()
Send messages using SMTP.
Returns
void
Definition at line 680 of file class.phpmailer.php.
     {
         $this->Mailer = 'smtp';
     }
lang()
PHPMailer::lang ($key) protected
Get an error message in the current language. @access protected
Parameters
string $key
Returns
string
Definition at line 2823 of file class.phpmailer.php.
     {
         if (count($this->language) < 1) {
             $this->setLanguage('en'); // set the default language
         }
         if (isset($this->language[$key])) {
             return $this->language[$key];
         } else {
             return 'Language string failed to load: ' . $key;
         }
     }
References setLanguage().
Referenced by addAnAddress(), addAttachment(), addEmbeddedImage(), createBody(), DKIM_Sign(), encodeFile(), encodeString(), mailSend(), preSend(), sendmailSend(), set(), setError(), setFrom(), smtpConnect(), and smtpSend().
mailPassthru()
PHPMailer::mailPassthru ($to, $subject, $body, $header, $params) private
Call mail() in a safe_mode-aware fashion. Also, unless sendmail_path points to sendmail (or something that claims to be sendmail), don't pass params (not a perfect fix, but it will do)
Parameters
string $to To
string $subject Subject
string $body Message Body
string $header Additional Header(s)
string $params Params @access private
Returns
boolean
Definition at line 604 of file class.phpmailer.php.
     {
         //Check overloading of mail function to avoid double-encoding
         if (ini_get('mbstring.func_overload') & 1) {
             $subject = $this->secureHeader($subject);
         } else {
             $subject = $this->encodeHeader($this->secureHeader($subject));
         }
         if (ini_get('safe_mode') || !($this->UseSendmailOptions)) {
             $result = @mail($to, $subject, $body, $header);
         } else {
             $result = @mail($to, $subject, $body, $header, $params);
         }
         return $result;
     }
References $header, $result, $to, encodeHeader(), and secureHeader().
Referenced by mailSend().
mailSend()
PHPMailer::mailSend ($header, $body) protected
Send mail using the PHP mail() function.
Parameters
string $header The message headers
string $body The message body phpmailerException protected boolean
Definition at line 1150 of file class.phpmailer.php.
     {
         $toArr = array();
         foreach ($this->to as $toaddr) {
             $toArr[] = $this->addrFormat($toaddr);
         }
         $to = implode(', ', $toArr);
         if (empty($this->Sender)) {
             $params = ' ';
         } else {
             $params = sprintf('-f%s', $this->Sender);
         }
         if ($this->Sender != '' and !ini_get('safe_mode')) {
             $old_from = ini_get('sendmail_from');
             ini_set('sendmail_from', $this->Sender);
         }
         $result = false;
         if ($this->SingleTo === true && count($toArr) > 1) {
             foreach ($toArr as $toAddr) {
                 $result = $this->mailPassthru($toAddr, $this->Subject, $body, $header, $params);
                 $this->doCallback($result, array($toAddr), $this->cc, $this->bcc, $this->Subject, $body, $this->From);
             }
         } else {
             $result = $this->mailPassthru($to, $this->Subject, $body, $header, $params);
             $this->doCallback($result, $this->to, $this->cc, $this->bcc, $this->Subject, $body, $this->From);
         }
         if (isset($old_from)) {
             ini_set('sendmail_from', $old_from);
         }
         if (!$result) {
             throw new phpmailerException($this->lang('instantiate'), self::STOP_CRITICAL);
         }
         return true;
     }
References $header, $result, $to, addrFormat(), as, doCallback(), lang(), mailPassthru(), Subject, and to.
Referenced by postSend().
mb_pathinfo()
static PHPMailer::mb_pathinfo ($path, $options = null) static
Multi-byte-safe pathinfo replacement. Drop-in replacement for pathinfo(), but multibyte-safe, cross-platform-safe, old-version-safe. Works similarly to the one in PHP >= 5.2.0 string $path A filename or path, does not need to exist as a file integer|string $options Either a PATHINFO_* constant, or a string name to return only the specified piece, allows 'filename' to work on PHP < 5.2 string|array
Definition at line 3108 of file class.phpmailer.php.
     {
         $ret = array('dirname' => '', 'basename' => '', 'extension' => '', 'filename' => '');
         $pathinfo = array();
         if (preg_match('%^(.*?)[\\\\/]*(([^/\\\\]*?)(\.([^\.\\\\/]+?)|))[\\\\/\.]*$%im', $path, $pathinfo)) {
             if (array_key_exists(1, $pathinfo)) {
                 $ret['dirname'] = $pathinfo[1];
             }
             if (array_key_exists(2, $pathinfo)) {
                 $ret['basename'] = $pathinfo[2];
             }
             if (array_key_exists(5, $pathinfo)) {
                 $ret['extension'] = $pathinfo[5];
             }
             if (array_key_exists(3, $pathinfo)) {
                 $ret['filename'] = $pathinfo[3];
             }
         }
         switch ($options) {
             case PATHINFO_DIRNAME:
             case 'dirname':
                 return $ret['dirname'];
             case PATHINFO_BASENAME:
             case 'basename':
                 return $ret['basename'];
             case PATHINFO_EXTENSION:
             case 'extension':
                 return $ret['extension'];
             case PATHINFO_FILENAME:
             case 'filename':
                 return $ret['filename'];
             default:
                 return $ret;
         }
     }
References $options.
Referenced by filenameToType().
msgHTML()
PHPMailer::msgHTML ($message, $basedir = '', $advanced = false)
Create a message from an HTML string. Automatically makes modifications for inline images and backgrounds and creates a plain-text version by converting the HTML. Overwrites any existing values in $this->Body and $this->AltBody @access public
Parameters
string $message HTML message string
string $basedir baseline directory for path
boolean $advanced Whether to use the advanced HTML to text converter
Returns
string $message
Definition at line 2894 of file class.phpmailer.php.
     {
         preg_match_all('/(src|background)=["\'](.*)["\']/Ui', $message, $images);
         if (isset($images[2])) {
             foreach ($images[2] as $imgindex => $url) {
                 // Convert data URIs into embedded images
                 if (preg_match('#^data:(image[^;,]*)(;base64)?,#', $url, $match)) {
                     $data = substr($url, strpos($url, ','));
                     if ($match[2]) {
                         $data = base64_decode($data);
                     } else {
                         $data = rawurldecode($data);
                     }
                     $cid = md5($url) . '@phpmailer.0'; // RFC2392 S 2
                     if ($this->addStringEmbeddedImage($data, $cid, '', 'base64', $match[1])) {
                         $message = preg_replace(
                             '/' . $images[1][$imgindex] . '=["\']' . preg_quote($url, '/') . '["\']/Ui',
                             $images[1][$imgindex] . '="cid:' . $cid . '"',
                             $message
                         );
                     }
                 } elseif (!preg_match('#^[A-z]+://#', $url)) {
                     // Do not change urls for absolute images (thanks to corvuscorax)
                     $filename = basename($url);
                     $directory = dirname($url);
                     if ($directory == '.') {
                         $directory = '';
                     }
                     $cid = md5($url) . '@phpmailer.0'; // RFC2392 S 2
                     if (strlen($basedir) > 1 && substr($basedir, -1) != '/') {
                         $basedir .= '/';
                     }
                     if (strlen($directory) > 1 && substr($directory, -1) != '/') {
                         $directory .= '/';
                     }
                     if ($this->addEmbeddedImage(
                         $basedir . $directory . $filename,
                         $cid,
                         $filename,
                         'base64',
                         self::_mime_types(self::mb_pathinfo($filename, PATHINFO_EXTENSION))
                     )
                     ) {
                         $message = preg_replace(
                             '/' . $images[1][$imgindex] . '=["\']' . preg_quote($url, '/') . '["\']/Ui',
                             $images[1][$imgindex] . '="cid:' . $cid . '"',
                             $message
                         );
                     }
                 }
             }
         }
         $this->isHTML(true);
         // Convert all message body line breaks to CRLF, makes quoted-printable encoding work much better
         $this->Body = $this->normalizeBreaks($message);
         $this->AltBody = $this->normalizeBreaks($this->html2text($message, $advanced));
         if (empty($this->AltBody)) {
             $this->AltBody = 'To view this email message, open it in a program that understands HTML!' .
                 self::CRLF . self::CRLF;
         }
         return $this->Body;
     }
References $Body, $data, $filename, $url, addEmbeddedImage(), addStringEmbeddedImage(), AltBody, as, Body, CRLF, html2text(), isHTML(), and normalizeBreaks().
normalizeBreaks()
static PHPMailer::normalizeBreaks ($text, $breaktype = "\r\n") static
Normalize line breaks in a string. Converts UNIX LF, Mac CR and Windows CRLF line breaks into a single line break format. Defaults to CRLF (for message bodies) and preserves consecutive breaks.
Parameters
string $text
string $breaktype What kind of line break to use, defaults to CRLF
Returns
string @access public
Definition at line 3196 of file class.phpmailer.php.
     {
         return preg_replace('/(\r\n|\r|\n)/ms', $breaktype, $text);
     }
Referenced by msgHTML().
postSend()
PHPMailer::postSend ()
Actually send a message. Send the email via the selected mechanism
Exceptions
phpmailerException
Returns
boolean
Definition at line 1050 of file class.phpmailer.php.
     {
         try {
             // Choose the mailer and send through it
             switch ($this->Mailer) {
                 case 'sendmail':
                 case 'qmail':
                     return $this->sendmailSend($this->MIMEHeader, $this->MIMEBody);
                 case 'smtp':
                     return $this->smtpSend($this->MIMEHeader, $this->MIMEBody);
                 case 'mail':
                     return $this->mailSend($this->MIMEHeader, $this->MIMEBody);
                 default:
                     $sendMethod = $this->Mailer.'Send';
                     if (method_exists($this, $sendMethod)) {
                         return $this->$sendMethod($this->MIMEHeader, $this->MIMEBody);
                     }
                     return $this->mailSend($this->MIMEHeader, $this->MIMEBody);
             }
         } catch (phpmailerException $exc) {
             $this->setError($exc->getMessage());
             $this->edebug($exc->getMessage());
             if ($this->exceptions) {
                 throw $exc;
             }
         }
         return false;
     }
References edebug(), mailSend(), sendmailSend(), setError(), and smtpSend().
Referenced by send().
preSend()
PHPMailer::preSend ()
Prepare a message for sending.
Exceptions
phpmailerException
Returns
boolean
Definition at line 982 of file class.phpmailer.php.
     {
         try {
             $this->mailHeader = '';
             if ((count($this->to) + count($this->cc) + count($this->bcc)) < 1) {
                 throw new phpmailerException($this->lang('provide_address'), self::STOP_CRITICAL);
             }
             // Set whether the message is multipart/alternative
             if (!empty($this->AltBody)) {
                 $this->ContentType = 'multipart/alternative';
             }
             $this->error_count = 0; // reset errors
             $this->setMessageType();
             // Refuse to send an empty message unless we are specifically allowing it
             if (!$this->AllowEmpty and empty($this->Body)) {
                 throw new phpmailerException($this->lang('empty_message'), self::STOP_CRITICAL);
             }
             $this->MIMEHeader = $this->createHeader();
             $this->MIMEBody = $this->createBody();
             // To capture the complete message when using mail(), create
             // an extra header list which createHeader() doesn't fold in
             if ($this->Mailer == 'mail') {
                 if (count($this->to) > 0) {
                     $this->mailHeader .= $this->addrAppend('To', $this->to);
                 } else {
                     $this->mailHeader .= $this->headerLine('To', 'undisclosed-recipients:;');
                 }
                 $this->mailHeader .= $this->headerLine(
                     'Subject',
                     $this->encodeHeader($this->secureHeader(trim($this->Subject)))
                 );
             }
             // Sign with DKIM if enabled
             if (!empty($this->DKIM_domain)
                 && !empty($this->DKIM_private)
                 && !empty($this->DKIM_selector)
                 && !empty($this->DKIM_domain)
                 && file_exists($this->DKIM_private)) {
                 $header_dkim = $this->DKIM_Add(
                     $this->MIMEHeader . $this->mailHeader,
                     $this->encodeHeader($this->secureHeader($this->Subject)),
                     $this->MIMEBody
                 );
                 $this->MIMEHeader = rtrim($this->MIMEHeader, "\r\n ") . self::CRLF .
                     str_replace("\r\n", "\n", $header_dkim) . self::CRLF;
             }
             return true;
         } catch (phpmailerException $exc) {
             $this->setError($exc->getMessage());
             if ($this->exceptions) {
                 throw $exc;
             }
             return false;
         }
     }
References addrAppend(), AltBody, Body, createBody(), createHeader(), CRLF, DKIM_Add(), encodeHeader(), headerLine(), lang(), secureHeader(), setError(), setMessageType(), Subject, and to.
Referenced by send().
rfcDate()
static PHPMailer::rfcDate () static
Return an RFC 822 formatted date. @access public
Returns
string
Definition at line 2788 of file class.phpmailer.php.
     {
         // Set the time zone to whatever the default is to avoid 500 errors
         // Will default to UTC if it's not set properly in php.ini
         date_default_timezone_set(@date_default_timezone_get());
         return date('D, j M Y H:i:s O');
     }
References date.
Referenced by createHeader().
secureHeader()
PHPMailer::secureHeader ($str)
Strip newlines to prevent header injection. @access public
Parameters
string $str
Returns
string
Definition at line 3181 of file class.phpmailer.php.
     {
         return trim(str_replace(array("\r", "\n"), '', $str));
     }
Referenced by addrFormat(), attachAll(), createHeader(), mailPassthru(), and preSend().
send()
PHPMailer::send ()
Create a message and send it. Uses the sending method specified by $Mailer.
Exceptions
phpmailerException
Returns
boolean false on error - See the ErrorInfo property for details of the error.
Definition at line 960 of file class.phpmailer.php.
     {
         try {
             if (!$this->preSend()) {
                 return false;
             }
             return $this->postSend();
         } catch (phpmailerException $exc) {
             $this->mailHeader = '';
             $this->setError($exc->getMessage());
             if ($this->exceptions) {
                 throw $exc;
             }
             return false;
         }
     }
References postSend(), preSend(), and setError().
sendmailSend()
PHPMailer::sendmailSend ($header, $body) protected
Send mail using the $Sendmail program.
Parameters
string $header The message headers
string $body The message body
See also
PHPMailer::$Sendmail
Exceptions
phpmailerException @access protected
Returns
boolean
Definition at line 1089 of file class.phpmailer.php.
     {
         if ($this->Sender != '') {
             if ($this->Mailer == 'qmail') {
                 $sendmail = sprintf('%s -f%s', escapeshellcmd($this->Sendmail), escapeshellarg($this->Sender));
             } else {
                 $sendmail = sprintf('%s -oi -f%s -t', escapeshellcmd($this->Sendmail), escapeshellarg($this->Sender));
             }
         } else {
             if ($this->Mailer == 'qmail') {
                 $sendmail = sprintf('%s', escapeshellcmd($this->Sendmail));
             } else {
                 $sendmail = sprintf('%s -oi -t', escapeshellcmd($this->Sendmail));
             }
         }
         if ($this->SingleTo === true) {
             foreach ($this->SingleToArray as $toAddr) {
                 if (!@$mail = popen($sendmail, 'w')) {
                     throw new phpmailerException($this->lang('execute') . $this->Sendmail, self::STOP_CRITICAL);
                 }
                 fputs($mail, 'To: ' . $toAddr . "\n");
                 fputs($mail, $header);
                 fputs($mail, $body);
                 $result = pclose($mail);
                 $this->doCallback(
                     ($result == 0),
                     array($toAddr),
                     $this->cc,
                     $this->bcc,
                     $this->Subject,
                     $body,
                     $this->From
                 );
                 if ($result != 0) {
                     throw new phpmailerException($this->lang('execute') . $this->Sendmail, self::STOP_CRITICAL);
                 }
             }
         } else {
             if (!@$mail = popen($sendmail, 'w')) {
                 throw new phpmailerException($this->lang('execute') . $this->Sendmail, self::STOP_CRITICAL);
             }
             fputs($mail, $header);
             fputs($mail, $body);
             $result = pclose($mail);
             $this->doCallback(($result == 0), $this->to, $this->cc, $this->bcc, $this->Subject, $body, $this->From);
             if ($result != 0) {
                 throw new phpmailerException($this->lang('execute') . $this->Sendmail, self::STOP_CRITICAL);
             }
         }
         return true;
     }
References $header, $mail, $result, as, doCallback(), lang(), Subject, and to.
Referenced by postSend().
serverHostname()
PHPMailer::serverHostname () protected
Get the server hostname. Returns 'localhost.localdomain' if unknown. @access protected
Returns
string
Definition at line 2802 of file class.phpmailer.php.
     {
         $result = 'localhost.localdomain';
         if (!empty($this->Hostname)) {
             $result = $this->Hostname;
         } elseif (isset($_SERVER) and array_key_exists('SERVER_NAME', $_SERVER) and !empty($_SERVER['SERVER_NAME'])) {
             $result = $_SERVER['SERVER_NAME'];
         } elseif (function_exists('gethostname') && gethostname() !== false) {
             $result = gethostname();
         } elseif (php_uname('n') !== false) {
             $result = php_uname('n');
         }
         return $result;
     }
References $Hostname, and $result.
Referenced by smtpConnect().
set()
PHPMailer::set ($name, $value = '')
Set or reset instance properties.
Usage Example: $page->set('X-Priority', '3');
@access public
Parameters
string $name
mixed $value NOTE: will not work with arrays, there are no arrays to set/reset
Exceptions
phpmailerException
Returns
boolean @TODO Should this not be using __set() magic function?
Definition at line 3158 of file class.phpmailer.php.
     {
         try {
             if (isset($this->$name)) {
                 $this->$name = $value;
             } else {
                 throw new phpmailerException($this->lang('variable_set') . $name, self::STOP_CRITICAL);
             }
         } catch (Exception $exc) {
             $this->setError($exc->getMessage());
             if ($exc->getCode() == self::STOP_CRITICAL) {
                 return false;
             }
         }
         return true;
     }
References $name, $value, lang(), and setError().
setError()
PHPMailer::setError ($msg) protected
Add an error message to the error container. @access protected
Parameters
string $msg
Returns
void
Definition at line 2770 of file class.phpmailer.php.
     {
         $this->error_count++;
         if ($this->Mailer == 'smtp' and !is_null($this->smtp)) {
             $lasterror = $this->smtp->getError();
             if (!empty($lasterror) and array_key_exists('smtp_msg', $lasterror)) {
                 $msg .= '<p>' . $this->lang('smtp_error') . $lasterror['smtp_msg'] . "</p>\n";
             }
         }
         $this->ErrorInfo = $msg;
     }
References lang().
Referenced by addAnAddress(), addAttachment(), addEmbeddedImage(), encodeFile(), encodeString(), postSend(), preSend(), send(), set(), setFrom(), and smtpSend().
setFrom()
PHPMailer::setFrom ($address, $name = '', $auto = true)
Set the From and FromName properties.
Parameters
string $address
string $name
boolean $auto Whether to also set the Sender address, defaults to true
Exceptions
phpmailerException
Returns
boolean
Definition at line 825 of file class.phpmailer.php.
     {
         $address = trim($address);
         $name = trim(preg_replace('/[\r\n]+/', '', $name)); //Strip breaks and trim
         if (!$this->validateAddress($address)) {
             $this->setError($this->lang('invalid_address') . ': ' . $address);
             $this->edebug($this->lang('invalid_address') . ': ' . $address);
             if ($this->exceptions) {
                 throw new phpmailerException($this->lang('invalid_address') . ': ' . $address);
             }
             return false;
         }
         $this->From = $address;
         $this->FromName = $name;
         if ($auto) {
             if (empty($this->Sender)) {
                 $this->Sender = $address;
             }
         }
         return true;
     }
References $name, edebug(), lang(), setError(), and validateAddress().
setLanguage()
PHPMailer::setLanguage ($langcode = 'en', $lang_path = '')
Set the language for error messages. Returns false if it cannot load the language file. The default language is English.
Parameters
string $langcode ISO 639-1 2-character language code (e.g. French is "fr")
string $lang_path Path to the language file directory, with trailing separator (slash)
Returns
boolean @access public
Definition at line 1393 of file class.phpmailer.php.
     {
         // Define full set of translatable strings in English
         $PHPMAILER_LANG = array(
             'authenticate' => 'SMTP Error: Could not authenticate.',
             'connect_host' => 'SMTP Error: Could not connect to SMTP host.',
             'data_not_accepted' => 'SMTP Error: data not accepted.',
             'empty_message' => 'Message body empty',
             'encoding' => 'Unknown encoding: ',
             'execute' => 'Could not execute: ',
             'file_access' => 'Could not access file: ',
             'file_open' => 'File Error: Could not open file: ',
             'from_failed' => 'The following From address failed: ',
             'instantiate' => 'Could not instantiate mail function.',
             'invalid_address' => 'Invalid address',
             'mailer_not_supported' => ' mailer is not supported.',
             'provide_address' => 'You must provide at least one recipient email address.',
             'recipients_failed' => 'SMTP Error: The following recipients failed: ',
             'signing' => 'Signing Error: ',
             'smtp_connect_failed' => 'SMTP connect() failed.',
             'smtp_error' => 'SMTP server error: ',
             'variable_set' => 'Cannot set or reset variable: '
         );
         if (empty($lang_path)) {
             // Calculate an absolute path so it can work if CWD is not here
             $lang_path = dirname(__FILE__). DIRECTORY_SEPARATOR . 'language'. DIRECTORY_SEPARATOR;
         }
         $foundlang = true;
         $lang_file = $lang_path . 'phpmailer.lang-' . $langcode . '.php';
         if ($langcode != 'en') { // There is no English translation file
             // Make sure language file path is readable
             if (!is_readable($lang_file)) {
                 $foundlang = false;
             } else {
                 // Overwrite language-specific strings.
                 // This way we'll never have missing translations.
                 $foundlang = include $lang_file;
             }
         }
         $this->language = $PHPMAILER_LANG;
         return ($foundlang == true); // Returns false if language not found
     }
Referenced by lang().
setMessageType()
PHPMailer::setMessageType () protected
Set the message type. PHPMailer only supports some preset message types, not arbitrary MIME structures. @access protected
Returns
void
Definition at line 2018 of file class.phpmailer.php.
     {
         $type = array();
         if ($this->alternativeExists()) {
             $type[] = 'alt';
         }
         if ($this->inlineImageExists()) {
             $type[] = 'inline';
         }
         if ($this->attachmentExists()) {
             $type[] = 'attach';
         }
         $this->message_type = implode('_', $type);
         if ($this->message_type == '') {
             $this->message_type = 'plain';
         }
     }
References $type, alternativeExists(), attachmentExists(), and inlineImageExists().
Referenced by preSend().
setWordWrap()
PHPMailer::setWordWrap ()
Set the body wrapping. @access public
Returns
void
Definition at line 1619 of file class.phpmailer.php.
     {
         if ($this->WordWrap < 1) {
             return;
         }
         switch ($this->message_type) {
             case 'alt':
             case 'alt_inline':
             case 'alt_attach':
             case 'alt_inline_attach':
                 $this->AltBody = $this->wrapText($this->AltBody, $this->WordWrap);
                 break;
             default:
                 $this->Body = $this->wrapText($this->Body, $this->WordWrap);
                 break;
         }
     }
References AltBody, Body, and wrapText().
Referenced by createBody().
sign()
PHPMailer::sign ($cert_filename, $key_filename, $key_pass)
Set the public and private key files and password for S/MIME signing. @access public
Parameters
string $cert_filename
string $key_filename
string $key_pass Password for private key
Definition at line 3209 of file class.phpmailer.php.
     {
         $this->sign_cert_file = $cert_filename;
         $this->sign_key_file = $key_filename;
         $this->sign_key_pass = $key_pass;
     }
smtpClose()
PHPMailer::smtpClose ()
Close the active SMTP session if one exists.
Returns
void
Definition at line 1374 of file class.phpmailer.php.
     {
         if ($this->smtp !== null) {
             if ($this->smtp->connected()) {
                 $this->smtp->quit();
                 $this->smtp->close();
             }
         }
     }
Referenced by __destruct().
smtpConnect()
PHPMailer::smtpConnect ($options = array())
Initiate a connection to an SMTP server. Returns false if the operation failed.
Parameters
array $options An array of options compatible with stream_context_create() @uses SMTP @access public
Exceptions
phpmailerException
Returns
boolean
Definition at line 1281 of file class.phpmailer.php.
     {
         if (is_null($this->smtp)) {
             $this->smtp = $this->getSMTPInstance();
         }
         // Already connected?
         if ($this->smtp->connected()) {
             return true;
         }
         $this->smtp->setTimeout($this->Timeout);
         $this->smtp->setDebugLevel($this->SMTPDebug);
         $this->smtp->setDebugOutput($this->Debugoutput);
         $this->smtp->setVerp($this->do_verp);
         $hosts = explode(';', $this->Host);
         $lastexception = null;
         foreach ($hosts as $hostentry) {
             $hostinfo = array();
             if (!preg_match('/^((ssl|tls):\/\/)*([a-zA-Z0-9\.-]*):?([0-9]*)$/', trim($hostentry), $hostinfo)) {
                 // Not a valid host entry
                 continue;
             }
             // $hostinfo[2]: optional ssl or tls prefix
             // $hostinfo[3]: the hostname
             // $hostinfo[4]: optional port number
             // The host string prefix can temporarily override the current setting for SMTPSecure
             // If it's not specified, the default value is used
             $prefix = '';
             $tls = ($this->SMTPSecure == 'tls');
             if ($hostinfo[2] == 'ssl' or ($hostinfo[2] == '' and $this->SMTPSecure == 'ssl')) {
                 $prefix = 'ssl://';
                 $tls = false; // Can't have SSL and TLS at once
             } elseif ($hostinfo[2] == 'tls') {
                 $tls = true;
                 // tls doesn't use a prefix
             }
             $host = $hostinfo[3];
             $port = $this->Port;
             $tport = (integer)$hostinfo[4];
             if ($tport > 0 and $tport < 65536) {
                 $port = $tport;
             }
             if ($this->smtp->connect($prefix . $host, $port, $this->Timeout, $options)) {
                 try {
                     if ($this->Helo) {
                         $hello = $this->Helo;
                     } else {
                         $hello = $this->serverHostname();
                     }
                     $this->smtp->hello($hello);
                     if ($tls) {
                         if (!$this->smtp->startTLS()) {
                             throw new phpmailerException($this->lang('connect_host'));
                         }
                         // We must resend HELO after tls negotiation
                         $this->smtp->hello($hello);
                     }
                     if ($this->SMTPAuth) {
                         if (!$this->smtp->authenticate(
                             $this->Username,
                             $this->Password,
                             $this->AuthType,
                             $this->Realm,
                             $this->Workstation
                         )
                         ) {
                             throw new phpmailerException($this->lang('authenticate'));
                         }
                     }
                     return true;
                 } catch (phpmailerException $exc) {
                     $lastexception = $exc;
                     // We must have connected, but then failed TLS or Auth, so close connection nicely
                     $this->smtp->quit();
                 }
             }
         }
         // If we get here, all connection attempts have failed, so close connection hard
         $this->smtp->close();
         // As we've caught all exceptions, just report whatever the last one was
         if ($this->exceptions and !is_null($lastexception)) {
             throw $lastexception;
         }
         return false;
     }
References $Helo, $host, $options, $port, $Port, $prefix, as, getSMTPInstance(), Host, lang(), serverHostname(), SMTPAuth, and SMTPSecure.
Referenced by smtpSend().
smtpSend()
PHPMailer::smtpSend ($header, $body) protected
Send mail via SMTP. Returns false if there is a bad MAIL FROM, RCPT, or DATA input. Uses the PHPMailerSMTP class by default.
See also
PHPMailer::getSMTPInstance() to use a different class.
Parameters
string $header The message headers
string $body The message body
Exceptions
phpmailerException @uses SMTP @access protected
Returns
boolean
Definition at line 1211 of file class.phpmailer.php.
     {
         $bad_rcpt = array();
         if (!$this->smtpConnect()) {
             throw new phpmailerException($this->lang('smtp_connect_failed'), self::STOP_CRITICAL);
         }
         $smtp_from = ($this->Sender == '') ? $this->From : $this->Sender;
         if (!$this->smtp->mail($smtp_from)) {
             $this->setError($this->lang('from_failed') . $smtp_from . ' : ' . implode(',', $this->smtp->getError()));
             throw new phpmailerException($this->ErrorInfo, self::STOP_CRITICAL);
         }
         // Attempt to send to all recipients
         foreach ($this->to as $to) {
             if (!$this->smtp->recipient($to[0])) {
                 $bad_rcpt[] = $to[0];
                 $isSent = false;
             } else {
                 $isSent = true;
             }
             $this->doCallback($isSent, array($to[0]), array(), array(), $this->Subject, $body, $this->From);
         }
         foreach ($this->cc as $cc) {
             if (!$this->smtp->recipient($cc[0])) {
                 $bad_rcpt[] = $cc[0];
                 $isSent = false;
             } else {
                 $isSent = true;
             }
             $this->doCallback($isSent, array(), array($cc[0]), array(), $this->Subject, $body, $this->From);
         }
         foreach ($this->bcc as $bcc) {
             if (!$this->smtp->recipient($bcc[0])) {
                 $bad_rcpt[] = $bcc[0];
                 $isSent = false;
             } else {
                 $isSent = true;
             }
             $this->doCallback($isSent, array(), array(), array($bcc[0]), $this->Subject, $body, $this->From);
         }
         // Only send the DATA command if we have viable recipients
         if ((count($this->all_recipients) > count($bad_rcpt)) and !$this->smtp->data($header . $body)) {
             throw new phpmailerException($this->lang('data_not_accepted'), self::STOP_CRITICAL);
         }
         if ($this->SMTPKeepAlive == true) {
             $this->smtp->reset();
         } else {
             $this->smtp->quit();
             $this->smtp->close();
         }
         if (count($bad_rcpt) > 0) { // Create error message for any bad addresses
             throw new phpmailerException(
                 $this->lang('recipients_failed') . implode(', ', $bad_rcpt),
                 self::STOP_CONTINUE
             );
         }
         return true;
     }
References $bcc, $cc, $header, $to, as, doCallback(), lang(), setError(), smtpConnect(), Subject, and to.
Referenced by postSend().
textLine()
PHPMailer::textLine ($value)
Return a formatted mail line. @access public
Parameters
string $value
Returns
string
Definition at line 2054 of file class.phpmailer.php.
     {
         return $value . $this->LE;
     }
References $LE, and $value.
Referenced by createBody(), getBoundary(), and getMailMIME().
utf8CharBoundary()
PHPMailer::utf8CharBoundary ($encodedText, $maxLength)
Find the last character boundary prior to $maxLength in a utf-8 quoted (printable) encoded string. Original written by Colin Brown. @access public
Parameters
string $encodedText utf-8 QP text
integer $maxLength find last character boundary prior to this length
Returns
integer
Definition at line 1581 of file class.phpmailer.php.
     {
         $foundSplitPos = false;
         $lookBack = 3;
         while (!$foundSplitPos) {
             $lastChunk = substr($encodedText, $maxLength - $lookBack, $lookBack);
             $encodedCharPos = strpos($lastChunk, '=');
             if ($encodedCharPos !== false) {
                 // Found start of encoded character byte within $lookBack block.
                 // Check the encoded byte value (the 2 chars after the '=')
                 $hex = substr($encodedText, $maxLength - $lookBack + $encodedCharPos + 1, 2);
                 $dec = hexdec($hex);
                 if ($dec < 128) { // Single byte character.
                     // If the encoded char was found at pos 0, it will fit
                     // otherwise reduce maxLength to start of the encoded char
                     $maxLength = ($encodedCharPos == 0) ? $maxLength :
                         $maxLength - ($lookBack - $encodedCharPos);
                     $foundSplitPos = true;
                 } elseif ($dec >= 192) { // First byte of a multi byte character
                     // Reduce maxLength to split at start of character
                     $maxLength = $maxLength - ($lookBack - $encodedCharPos);
                     $foundSplitPos = true;
                 } elseif ($dec < 192) { // Middle byte of a multi byte character, look further back
                     $lookBack += 3;
                 }
             } else {
                 // No encoded character found
                 $foundSplitPos = true;
             }
         }
         return $maxLength;
     }
Referenced by wrapText().
validateAddress()
static PHPMailer::validateAddress ($address, $patternselect = 'auto') static
Check that a string looks like an email address.
Parameters
string $address The email address to check
string $patternselect A selector for the validation pattern to use :
auto Pick strictest one automatically;
pcre8 Use the squiloople.com pattern, requires PCRE > 8.0, PHP >= 5.3.2, 5.2.14;
pcre Use old PCRE implementation;
php Use PHP built-in FILTER_VALIDATE_EMAIL; same as pcre8 but does not allow 'dotless' domains;
html5 Use the pattern given by the HTML5 spec for 'email' type form input elements.
noregex Don't use a regex: super fast, really dumb.
Returns
boolean
@access public
Uses the same RFC5322 regex on which FILTER_VALIDATE_EMAIL is based, but allows dotless domains. 2009-2010 Michael Rushton Feel free to use and redistribute this code. But please keep this copyright notice. This is the pattern used in the HTML5 spec for validation of 'email' type form input elements. http://www.whatwg.org/specs/web-apps/current-work/#e-mail-state-(type=email)
Definition at line 873 of file class.phpmailer.php.
     {
         if (!$patternselect or $patternselect == 'auto') {
             //Check this constant first so it works when extension_loaded() is disabled by safe mode
             //Constant was added in PHP 5.2.4
             if (defined('PCRE_VERSION')) {
                 //This pattern can get stuck in a recursive loop in PCRE <= 8.0.2
                 if (version_compare(PCRE_VERSION, '8.0.3') >= 0) {
                     $patternselect = 'pcre8';
                 } else {
                     $patternselect = 'pcre';
                 }
             } elseif (function_exists('extension_loaded') and extension_loaded('pcre')) {
                 //Fall back to older PCRE
                 $patternselect = 'pcre';
             } else {
                 //Filter_var appeared in PHP 5.2.0 and does not require the PCRE extension
                 if (version_compare(PHP_VERSION, '5.2.0') >= 0) {
                     $patternselect = 'php';
                 } else {
                     $patternselect = 'noregex';
                 }
             }
         }
         switch ($patternselect) {
             case 'pcre8':
                 /**
                  * Uses the same RFC5322 regex on which FILTER_VALIDATE_EMAIL is based, but allows dotless domains.
                  * @link http://squiloople.com/2009/12/20/email-address-validation/
                  * @copyright 2009-2010 Michael Rushton
                  * Feel free to use and redistribute this code. But please keep this copyright notice.
                  */
                 return (boolean)preg_match(
                     '/^(?!(?>(?1)"?(?>\\\[ -~]|[^"])"?(?1)){255,})(?!(?>(?1)"?(?>\\\[ -~]|[^"])"?(?1)){65,}@)' .
                     '((?>(?>(?>((?>(?>(?>\x0D\x0A)?[\t ])+|(?>[\t ]*\x0D\x0A)?[\t ]+)?)(\‍((?>(?2)' .
                     '(?>[\x01-\x08\x0B\x0C\x0E-\'*-\[\]-\x7F]|\\\[\x00-\x7F]|(?3)))*(?2)\‍)))+(?2))|(?2))?)' .
                     '([!#-\'*+\/-9=?^-~-]+|"(?>(?2)(?>[\x01-\x08\x0B\x0C\x0E-!#-\[\]-\x7F]|\\\[\x00-\x7F]))*' .
                     '(?2)")(?>(?1)\.(?1)(?4))*(?1)@(?!(?1)[a-z0-9-]{64,})(?1)(?>([a-z0-9](?>[a-z0-9-]*[a-z0-9])?)' .
                     '(?>(?1)\.(?!(?1)[a-z0-9-]{64,})(?1)(?5)){0,126}|\[(?:(?>IPv6:(?>([a-f0-9]{1,4})(?>:(?6)){7}' .
                     '|(?!(?:.*[a-f0-9][:\]]){8,})((?6)(?>:(?6)){0,6})?::(?7)?))|(?>(?>IPv6:(?>(?6)(?>:(?6)){5}:' .
                     '|(?!(?:.*[a-f0-9]:){6,})(?8)?::(?>((?6)(?>:(?6)){0,4}):)?))?(25[0-5]|2[0-4][0-9]|1[0-9]{2}' .
                     '|[1-9]?[0-9])(?>\.(?9)){3}))\])(?1)$/isD',
                     $address
                 );
             case 'pcre':
                 //An older regex that doesn't need a recent PCRE
                 return (boolean)preg_match(
                     '/^(?!(?>"?(?>\\\[ -~]|[^"])"?){255,})(?!(?>"?(?>\\\[ -~]|[^"])"?){65,}@)(?>' .
                     '[!#-\'*+\/-9=?^-~-]+|"(?>(?>[\x01-\x08\x0B\x0C\x0E-!#-\[\]-\x7F]|\\\[\x00-\xFF]))*")' .
                     '(?>\.(?>[!#-\'*+\/-9=?^-~-]+|"(?>(?>[\x01-\x08\x0B\x0C\x0E-!#-\[\]-\x7F]|\\\[\x00-\xFF]))*"))*' .
                     '@(?>(?![a-z0-9-]{64,})(?>[a-z0-9](?>[a-z0-9-]*[a-z0-9])?)(?>\.(?![a-z0-9-]{64,})' .
                     '(?>[a-z0-9](?>[a-z0-9-]*[a-z0-9])?)){0,126}|\[(?:(?>IPv6:(?>(?>[a-f0-9]{1,4})(?>:' .
                     '[a-f0-9]{1,4}){7}|(?!(?:.*[a-f0-9][:\]]){8,})(?>[a-f0-9]{1,4}(?>:[a-f0-9]{1,4}){0,6})?' .
                     '::(?>[a-f0-9]{1,4}(?>:[a-f0-9]{1,4}){0,6})?))|(?>(?>IPv6:(?>[a-f0-9]{1,4}(?>:' .
                     '[a-f0-9]{1,4}){5}:|(?!(?:.*[a-f0-9]:){6,})(?>[a-f0-9]{1,4}(?>:[a-f0-9]{1,4}){0,4})?' .
                     '::(?>(?:[a-f0-9]{1,4}(?>:[a-f0-9]{1,4}){0,4}):)?))?(?>25[0-5]|2[0-4][0-9]|1[0-9]{2}' .
                     '|[1-9]?[0-9])(?>\.(?>25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3}))\])$/isD',
                     $address
                 );
             case 'html5':
                 /**
                  * This is the pattern used in the HTML5 spec for validation of 'email' type form input elements.
                  * @link http://www.whatwg.org/specs/web-apps/current-work/#e-mail-state-(type=email)
                  */
                 return (boolean)preg_match(
                     '/^[a-zA-Z0-9.!#$%&\'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}' .
                     '[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/sD',
                     $address
                 );
             case 'noregex':
                 //No PCRE! Do something _very_ approximate!
                 //Check the address is 3 chars or longer and contains an @ that's not the first or last char
                 return (strlen($address) >= 3
                     and strpos($address, '@') >= 1
                     and strpos($address, '@') != strlen($address) - 1);
             case 'php':
             default:
                 return (boolean)filter_var($address, FILTER_VALIDATE_EMAIL);
         }
     }
Referenced by addAnAddress(), and setFrom().
wrapText()
PHPMailer::wrapText ($message, $length, $qp_mode = false)
Word-wrap message. For use with mailers that do not automatically perform wrapping and for quoted-printable encoded messages. Original written by philippe.
Parameters
string $message The message to wrap
integer $length The line length to wrap to
boolean $qp_mode Whether to run in Quoted-Printable mode @access public
Returns
string
Definition at line 1493 of file class.phpmailer.php.
     {
         $soft_break = ($qp_mode) ? sprintf(' =%s', $this->LE) : $this->LE;
         // If utf-8 encoding is used, we will need to make sure we don't
         // split multibyte characters when we wrap
         $is_utf8 = (strtolower($this->CharSet) == 'utf-8');
         $lelen = strlen($this->LE);
         $crlflen = strlen(self::CRLF);
         $message = $this->fixEOL($message);
         if (substr($message, -$lelen) == $this->LE) {
             $message = substr($message, 0, -$lelen);
         }
         $line = explode($this->LE, $message); // Magic. We know fixEOL uses $LE
         $message = '';
         for ($i = 0; $i < count($line); $i++) {
             $line_part = explode(' ', $line[$i]);
             $buf = '';
             for ($e = 0; $e < count($line_part); $e++) {
                 $word = $line_part[$e];
                 if ($qp_mode and (strlen($word) > $length)) {
                     $space_left = $length - strlen($buf) - $crlflen;
                     if ($e != 0) {
                         if ($space_left > 20) {
                             $len = $space_left;
                             if ($is_utf8) {
                                 $len = $this->utf8CharBoundary($word, $len);
                             } elseif (substr($word, $len - 1, 1) == '=') {
                                 $len--;
                             } elseif (substr($word, $len - 2, 1) == '=') {
                                 $len -= 2;
                             }
                             $part = substr($word, 0, $len);
                             $word = substr($word, $len);
                             $buf .= ' ' . $part;
                             $message .= $buf . sprintf('=%s', self::CRLF);
                         } else {
                             $message .= $buf . $soft_break;
                         }
                         $buf = '';
                     }
                     while (strlen($word) > 0) {
                         if ($length <= 0) {
                             break;
                         }
                         $len = $length;
                         if ($is_utf8) {
                             $len = $this->utf8CharBoundary($word, $len);
                         } elseif (substr($word, $len - 1, 1) == '=') {
                             $len--;
                         } elseif (substr($word, $len - 2, 1) == '=') {
                             $len -= 2;
                         }
                         $part = substr($word, 0, $len);
                         $word = substr($word, $len);
                         if (strlen($word) > 0) {
                             $message .= $part . sprintf('=%s', self::CRLF);
                         } else {
                             $buf = $part;
                         }
                     }
                 } else {
                     $buf_o = $buf;
                     $buf .= ($e == 0) ? $word : (' ' . $word);
                     if (strlen($buf) > $length and $buf_o != '') {
                         $message .= $buf_o . $soft_break;
                         $buf = $word;
                     }
                 }
             }
             $message .= $buf . self::CRLF;
         }
         return $message;
     }
References $e, $i, $LE, CRLF, fixEOL(), and utf8CharBoundary().
Referenced by encodeHeader(), and setWordWrap().
Member Data Documentation
$action_function
PHPMailer::$action_function = ''
Callback Action function name.
The function that handles the result of the send email action. It is called out by send() for each email sent.
Value can be any php callable: http://www.php.net/is_callable
Parameters: boolean $result result of the send action string $to email address of the recipient string $cc cc email addresses string $bcc bcc email addresses string $subject the subject string $body the email body string $from email address of sender @type string
Definition at line 422 of file class.phpmailer.php.
$all_recipients
PHPMailer::$all_recipients = array() protected
An array of all kinds of addresses. Includes all of $to, $cc, $bcc, $replyto @type array @access protected
Definition at line 472 of file class.phpmailer.php.
Referenced by getAllRecipientAddresses().
$AllowEmpty
PHPMailer::$AllowEmpty = false
Whether to allow sending messages with an empty body. @type boolean
Definition at line 361 of file class.phpmailer.php.
$AltBody
PHPMailer::$AltBody = ''
The plain-text message body. This body can be read by mail clients that do not have HTML email capability such as mutt & Eudora. Clients that can read HTML will view the normal Body. @type string
Definition at line 117 of file class.phpmailer.php.
$attachment
PHPMailer::$attachment = array() protected
The array of attachments. @type array @access protected
Definition at line 479 of file class.phpmailer.php.
Referenced by attachAll(), attachmentExists(), getAttachments(), and inlineImageExists().
$AuthType
PHPMailer::$AuthType = ''
SMTP auth type. Options are LOGIN (default), PLAIN, NTLM, CRAM-MD5 @type string
Definition at line 274 of file class.phpmailer.php.
$bcc
PHPMailer::$bcc = array() protected
The array of 'bcc' addresses. @type array @access protected
Definition at line 457 of file class.phpmailer.php.
Referenced by clearBCCs(), doCallback(), getBccAddresses(), and smtpSend().
$Body
PHPMailer::$Body = ''
An HTML or plain text message body. If HTML then call isHTML(true). @type string
Definition at line 108 of file class.phpmailer.php.
Referenced by msgHTML().
$boundary
PHPMailer::$boundary = array() protected
The array of MIME boundary strings. @type array @access protected
Definition at line 507 of file class.phpmailer.php.
Referenced by attachAll(), endBoundary(), and getBoundary().
$cc
PHPMailer::$cc = array() protected
The array of 'cc' addresses. @type array @access protected
Definition at line 450 of file class.phpmailer.php.
Referenced by clearCCs(), doCallback(), getCcAddresses(), and smtpSend().
$CharSet
PHPMailer::$CharSet = 'iso-8859-1'
The character set of the message. @type string
Definition at line 47 of file class.phpmailer.php.
Referenced by createBody(), and getBoundary().
$ConfirmReadingTo
PHPMailer::$ConfirmReadingTo = ''
The email address that a reading confirmation should be sent to. @type string
Definition at line 188 of file class.phpmailer.php.
$ContentType
PHPMailer::$ContentType = 'text/plain'
The MIME Content-type of the message. @type string
Definition at line 53 of file class.phpmailer.php.
Referenced by getBoundary().
$CustomHeader
PHPMailer::$CustomHeader = array() protected
The array of custom headers. @type array @access protected
Definition at line 486 of file class.phpmailer.php.
$Debugoutput
PHPMailer::$Debugoutput = 'echo'
How to handle debug output. Options:
echo Output plain-text as-is, appropriate for CLI
html Output escaped, line breaks converted to <br>, appropriate for browser output
error_log Output to error log as configured in php.ini
Alternatively, you can provide a callable expecting two params: a message string and the debug level: $mail->Debugoutput = function($str, $level) {echo "debug level $level; message: $str";}; @type string|callable
See also
SMTP::$Debugoutput
Definition at line 324 of file class.phpmailer.php.
$DKIM_domain
PHPMailer::$DKIM_domain = ''
Definition at line 396 of file class.phpmailer.php.
$DKIM_identity
PHPMailer::$DKIM_identity = ''
DKIM Identity. Usually the email address used as the source of the email @type string
Definition at line 382 of file class.phpmailer.php.
$DKIM_passphrase
PHPMailer::$DKIM_passphrase = ''
DKIM passphrase. Used if your key is encrypted. @type string
Definition at line 389 of file class.phpmailer.php.
$DKIM_private
PHPMailer::$DKIM_private = ''
DKIM private key file path. @type string
Definition at line 402 of file class.phpmailer.php.
$DKIM_selector
PHPMailer::$DKIM_selector = ''
DKIM selector. @type string
Definition at line 375 of file class.phpmailer.php.
$do_verp
PHPMailer::$do_verp = false
Whether to generate VERP addresses on send. Only applicable when sending via SMTP. http://www.postfix.org/VERP_README.html Postfix VERP info boolean
Definition at line 355 of file class.phpmailer.php.
$Encoding
PHPMailer::$Encoding = '8bit'
The message encoding. Options: "8bit", "7bit", "binary", "base64", and "quoted-printable". @type string
Definition at line 60 of file class.phpmailer.php.
Referenced by createBody(), and getBoundary().
$error_count
PHPMailer::$error_count = 0 protected
The number of errors encountered. @type integer @access protected
Definition at line 521 of file class.phpmailer.php.
$ErrorInfo
PHPMailer::$ErrorInfo = ''
Holds the most recent mailer error message. @type string
Definition at line 66 of file class.phpmailer.php.
$exceptions
PHPMailer::$exceptions = false protected
Whether to throw exceptions for errors. @type boolean @access protected
Definition at line 550 of file class.phpmailer.php.
Referenced by __construct().
$From
PHPMailer::$From = 'root@localhost'
The From email address for the message. @type string
Definition at line 72 of file class.phpmailer.php.
$FromName
PHPMailer::$FromName = 'Root User'
The From name of the message. @type string
Definition at line 78 of file class.phpmailer.php.
$Helo
PHPMailer::$Helo = ''
The SMTP HELO of the message. Default is $Hostname. @type string
See also
PHPMailer::$Hostname
Definition at line 239 of file class.phpmailer.php.
Referenced by smtpConnect().
$Host
PHPMailer::$Host = 'localhost'
SMTP hosts. Either a single hostname or multiple semicolon-delimited hostnames. You can also specify a different port for each host by using this format: hostname:port. You can also specify encryption type, for example: (e.g. "tls://smtp1.example.com:587;ssl://smtp2.example.com:465"). Hosts will be tried in order. @type string
Definition at line 224 of file class.phpmailer.php.
$Hostname
PHPMailer::$Hostname = ''
The hostname to use in Message-Id and Received headers and as default HELO string. If empty, the value returned by SERVER_NAME is used or 'localhost.localdomain'. @type string
Definition at line 197 of file class.phpmailer.php.
Referenced by serverHostname().
$Ical
PHPMailer::$Ical = ''
An iCal message part body. Only supported in simple alt or alt_inline message types To generate iCal events, use the bundled extras/EasyPeasyICS.php class or iCalcreator http://kigkonsult.se/iCalcreator/ string
Definition at line 127 of file class.phpmailer.php.
$language
PHPMailer::$language = array() protected
The array of available languages. @type array @access protected
Definition at line 514 of file class.phpmailer.php.
Referenced by getTranslations().
$lastMessageID
PHPMailer::$lastMessageID = '' protected
The most recent Message-ID (including angular brackets). @type string @access protected
Definition at line 493 of file class.phpmailer.php.
Referenced by getLastMessageID().
$LE
PHPMailer::$LE = "\n"
The default line ending.
Note
The default remains "\n". We force CRLF where we know it must be used via self::CRLF. @type string
Definition at line 369 of file class.phpmailer.php.
Referenced by addrAppend(), attachAll(), base64EncodeWrapMB(), createBody(), encodeString(), endBoundary(), getBoundary(), getMailMIME(), headerLine(), textLine(), and wrapText().
$Mailer
PHPMailer::$Mailer = 'mail'
Which method to use to send mail. Options: "mail", "sendmail", or "smtp". @type string
Definition at line 161 of file class.phpmailer.php.
$mailHeader
PHPMailer::$mailHeader = '' protected
Extra headers that createHeader() doesn't fold in. @type string @access protected
Definition at line 148 of file class.phpmailer.php.
$message_type
PHPMailer::$message_type = '' protected
The message's MIME type. @type string @access protected
Definition at line 500 of file class.phpmailer.php.
$MessageDate
PHPMailer::$MessageDate = ''
The message Date to be used in the Date header. If empty, the current date will be added. @type string
Definition at line 211 of file class.phpmailer.php.
$MessageID
PHPMailer::$MessageID = ''
An ID to be used in the Message-Id header. If empty, a unique id will be generated. @type string
Definition at line 204 of file class.phpmailer.php.
Referenced by createHeader().
$MIMEBody
PHPMailer::$MIMEBody = '' protected
The complete compiled MIME message body. @access protected @type string
Definition at line 134 of file class.phpmailer.php.
Referenced by getSentMIMEMessage().
$MIMEHeader
PHPMailer::$MIMEHeader = '' protected
The complete compiled MIME message headers. @type string @access protected
Definition at line 141 of file class.phpmailer.php.
$Password
PHPMailer::$Password = ''
SMTP password. @type string
Definition at line 267 of file class.phpmailer.php.
$PluginDir
PHPMailer::$PluginDir = ''
Path to PHPMailer plugins. Useful if the SMTP class is not in the PHP include path. @type string
Deprecated:
Should not be needed now there is an autoloader.
Definition at line 182 of file class.phpmailer.php.
$Port
PHPMailer::$Port = 25
The default SMTP server port. @type integer @TODO Why is this needed when the SMTP class takes care of it?
Definition at line 231 of file class.phpmailer.php.
Referenced by smtpConnect().
$Priority
PHPMailer::$Priority = 3
Email priority. Options: 1 = High, 3 = Normal, 5 = low. @type integer
Definition at line 41 of file class.phpmailer.php.
$Realm
PHPMailer::$Realm = ''
SMTP realm. Used for NTLM auth @type string
Definition at line 281 of file class.phpmailer.php.
$ReplyTo
PHPMailer::$ReplyTo = array() protected
The array of reply-to names and addresses. @type array @access protected
Definition at line 464 of file class.phpmailer.php.
Referenced by getReplyToAddresses().
$ReturnPath
PHPMailer::$ReturnPath = ''
The Return-Path of the message. If empty, it will be set to either From or Sender. @type string
Deprecated:
Email senders should never set a return-path header; it's the receiver's job (RFC5321 section 4.4), so this no longer does anything. RFC5321 reference
Definition at line 95 of file class.phpmailer.php.
$Sender
PHPMailer::$Sender = ''
The Sender email (Return-Path) of the message. If not empty, will be sent via -f to sendmail or as 'MAIL FROM' in smtp mode. @type string
Definition at line 85 of file class.phpmailer.php.
$Sendmail
PHPMailer::$Sendmail = '/usr/sbin/sendmail'
The path to the sendmail program. @type string
Definition at line 167 of file class.phpmailer.php.
$sign_cert_file
PHPMailer::$sign_cert_file = '' protected
The S/MIME certificate file path. @type string @access protected
Definition at line 528 of file class.phpmailer.php.
$sign_key_file
PHPMailer::$sign_key_file = '' protected
The S/MIME key file path. @type string @access protected
Definition at line 535 of file class.phpmailer.php.
$sign_key_pass
PHPMailer::$sign_key_pass = '' protected
The S/MIME password for the key. Used only if the key is encrypted. @type string @access protected
Definition at line 543 of file class.phpmailer.php.
$SingleTo
PHPMailer::$SingleTo = false
Whether to split multiple to addresses into multiple messages or send them all in one message. @type boolean
Definition at line 339 of file class.phpmailer.php.
$SingleToArray
PHPMailer::$SingleToArray = array()
Storage for addresses when SingleTo is enabled. @type array @TODO This should really not be public
Definition at line 346 of file class.phpmailer.php.
$smtp
PHPMailer::$smtp = null protected
An instance of the SMTP sender class. @type SMTP @access protected
Definition at line 436 of file class.phpmailer.php.
Referenced by getSMTPInstance().
$SMTPAuth
PHPMailer::$SMTPAuth = false
Whether to use SMTP authentication. Uses the Username and Password properties. @type boolean
See also
PHPMailer::$Username
PHPMailer::$Password
Definition at line 255 of file class.phpmailer.php.
$SMTPDebug
PHPMailer::$SMTPDebug = 0
SMTP class debug output mode. Debug output level. Options:
0 No output
1 Commands
2 Data and commands
3 As 2 plus connection status
4 Low-level data output @type integer
See also
SMTP::$do_debug
Definition at line 308 of file class.phpmailer.php.
$SMTPKeepAlive
PHPMailer::$SMTPKeepAlive = false
Whether to keep SMTP connection open after each message. If this is set to true then to close the connection requires an explicit call to smtpClose(). @type boolean
Definition at line 332 of file class.phpmailer.php.
$SMTPSecure
PHPMailer::$SMTPSecure = ''
The secure connection prefix. Options: "", "ssl" or "tls" @type string
Definition at line 246 of file class.phpmailer.php.
$Subject
PHPMailer::$Subject = ''
The Subject of the message. @type string
Definition at line 101 of file class.phpmailer.php.
$Timeout
PHPMailer::$Timeout = 10
The SMTP server timeout in seconds. @type integer
Definition at line 294 of file class.phpmailer.php.
$to
PHPMailer::$to = array() protected
The array of 'to' addresses. @type array @access protected
Definition at line 443 of file class.phpmailer.php.
Referenced by clearAddresses(), DKIM_Add(), doCallback(), getToAddresses(), mailPassthru(), mailSend(), and smtpSend().
$Username
PHPMailer::$Username = ''
SMTP username. @type string
Definition at line 261 of file class.phpmailer.php.
$UseSendmailOptions
PHPMailer::$UseSendmailOptions = true
Whether mail() uses a fully sendmail-compatible MTA. One which supports sendmail's "-oi -f" options. @type boolean
Definition at line 174 of file class.phpmailer.php.
$Version
PHPMailer::$Version = '5.2.8'
The PHPMailer Version number. @type string
Definition at line 34 of file class.phpmailer.php.
$WordWrap
PHPMailer::$WordWrap = 0
Word-wrap the message body to this number of chars. @type integer
Definition at line 154 of file class.phpmailer.php.
$Workstation
PHPMailer::$Workstation = ''
SMTP workstation. Used for NTLM auth @type string
Definition at line 288 of file class.phpmailer.php.
$XMailer
PHPMailer::$XMailer = ''
What to use in the X-Mailer header. Options: null for default, whitespace for none, or a string to use @type string
Definition at line 429 of file class.phpmailer.php.
CRLF
const PHPMailer::CRLF = "\r\n"
SMTP RFC standard line ending.
Definition at line 570 of file class.phpmailer.php.
Referenced by msgHTML(), preSend(), and wrapText().
STOP_CONTINUE
const PHPMailer::STOP_CONTINUE = 1
Error severity: message, likely ok to continue processing.
Definition at line 560 of file class.phpmailer.php.
STOP_CRITICAL
const PHPMailer::STOP_CRITICAL = 2
Error severity: message, plus full stop, critical error reached.
Definition at line 565 of file class.phpmailer.php.
STOP_MESSAGE
const PHPMailer::STOP_MESSAGE = 0
Error severity: message only, continue processing.
Definition at line 555 of file class.phpmailer.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/phpMailer/class.phpmailer.php