YaWK: YAWK\widget Class Reference
YAWK\widget Class Reference
Widgets are small, useful tools that you can include everywhere in your website.
Public Member Functions
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Static Public Member Functions
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Public Attributes
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Detailed Description
Widgets are small, useful tools that you can include everywhere in your website.
Widgets are small, useful tools that you can include everywhere on your website.
YaWK comes with a lot of widgets for different purposes. As an example, you can add SocialMedia buttons, Facebook Boxes, Likebuttons or other things like a simple contant and many other small utilities for typical daily needs of nearly every web project. Check out the files in system/widgets to get a clue about how widget's file structure is organized. You miss a widget? Dont worry. It is easy to create your own - or copy and modify an existing one to make it fit your needs. If you want to get deeper into the widget system of YaWK, read the following docs.
Class covers both, backend & frontend functionality. See Methods Summary for Details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 21 of file widget.php.
Member Function Documentation
getAllSettingsIntoArray()
static YAWK\widget::getAllSettingsIntoArray ($db, $widgetID) static
Returns an array with all widget settings data.
Parameters
object $db Database Object
Returns
array|bool
TODO: IMPLEMENT GET WIDGET SETTINGS ARRRAY for issue #61
Definition at line 127 of file widget.php.
         {
             /* @param $db \YAWK\db */
             if ($res = $db->query("SELECT * FROM {widget_settings} WHERE widgetID = '".$widgetID."' ORDER by sortation"))
             {
                 $settingsArray = array();
                 while ($row = $res->fetch_assoc())
                 {   // fill array
                     $settingsArray[] = $row;
                 }
             }
             else
             {   // q failed, throw error
                 \YAWK\sys::setSyslog($db, 39, 1, "failed to get widget settings array of widget ID $widgetID", 0, 0, 0, 0);
                 // \YAWK\alert::draw("warning", "Warning!", "Fetch database error: getSettingsArray failed.","","4800");
                 return false;
             }
             return $settingsArray;
         }
References $db, and $res.
getAllWidgetTypes()
static YAWK\widget::getAllWidgetTypes ($db) static
Return all widget types as associative array.
Parameters
object $db database
Returns
array return all widgets types from database
Definition at line 1211 of file widget.php.
         {
             $row = $db->query("SELECT * FROM {widget_types} ORDER BY name");
             while ($res = mysqli_fetch_assoc($row))
             {
                 $widgetTypes[] = $res;
             }
             if (is_array($widgetTypes) && (!empty($widgetTypes))){
                 return $widgetTypes;
             }
             else
             {
                 \YAWK\sys::setSyslog($db, 39, 1, "failed to get list of widget types. $widgetTypes is empty or not set.", 0, 0, 0, 0);
                 return false;
             }
         }
References $db, $res, and $widgetTypes.
getCurrentWidgetPath()
static YAWK\widget::getCurrentWidgetPath ($db) static
return current widget path
Parameters
object $db database
Returns
string full path to widgets folder
Definition at line 115 of file widget.php.
         {
             return "" . \YAWK\sys::getDirPrefix($db) . "/system/widgets/";
         }
References $db, and YAWK\sys\getDirPrefix().
getFacebookLikeBox()
static YAWK\widget::getFacebookLikeBox () static
return the facebook likebox widget
Definition at line 909 of file widget.php.
         {
             include 'system/widgets/fb_like/fb_like.php';
         }
getHeading()
YAWK\widget::getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
Parameters
string $heading The Heading
string $subtext The Subtext
Returns
string|bool return the correct headline
Definition at line 669 of file widget.php.
         {
             // if a heading is set and not empty
             if (isset($heading) && (!empty($heading)))
             {
                 // if subtext is set, add <small> subtext to string
                 if (isset($subtext) && (!empty($subtext)))
                 {   // build a headline with heading and subtext
                     $subtext = "<small>$subtext</small>";
                     return "<h2>$heading&nbsp;" . "$subtext</h2>";
                 }
                 else
                 {   // build just a headline - without subtext
                     return  "<h2>$heading</h2>";    // draw just the heading
                 }
             }
             else
             {   // leave empty if it's not set
                 return null;
             }
         }
References $heading, and $subtext.
Referenced by YAWK\WIDGETS\BLOG\WIDGET\blogWidget\drawBlogWidget(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\drawImageGallery(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\drawLoginBox(), YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\embed(), YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\embed(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\init(), YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\init(), YAWK\WIDGETS\FACEBOOK\POSTING\fbPosting\init(), YAWK\WIDGETS\FACEBOOK\VIDEO\fbVideo\init(), YAWK\WIDGETS\PINTEREST\FOLLOW\pinterestFollow\init(), YAWK\WIDGETS\PINTEREST\PIN\pinterestPin\init(), YAWK\WIDGETS\PINTEREST\PROFILE\pinterestProfile\init(), YAWK\WIDGETS\PLYR\PLAYER\plyr\init(), YAWK\WIDGETS\PREZI\EMBED\prezi\init(), YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\init(), YAWK\WIDGETS\SPOTIFY\EMBED\spotify\init(), YAWK\WIDGETS\TWITCH\EMBED\twitch\init(), YAWK\WIDGETS\TWITTER\GRID\twitterGrid\init(), YAWK\WIDGETS\TWITTER\TIMELINE\twitterTimeline\init(), YAWK\WIDGETS\TWITTER\TWEET\twitterTweet\init(), YAWK\WIDGETS\TWITTER\BUTTON\twitterTweetButton\init(), and YAWK\WIDGETS\EXAMPLE\DEMO\example\showHeading().
getLoginBox()
static YAWK\widget::getLoginBox () static
return the user login box widget
Definition at line 901 of file widget.php.
         {
             return include 'system/widgets/loginbox/loginbox.php';
         }
getWidgetSettingsArray()
YAWK\widget::getWidgetSettingsArray ($db)
Get widget settings and return it as array.
Parameters
object $db database
Returns
array|bool returns array with widget settings or null
Definition at line 69 of file widget.php.
         {
             // $_GET['widgetID'] will be generated in \YAWK\widget\loadWidgets($db, $position)
             if (isset($_GET['widgetID']))
             {
                 // widget ID
                 $this->id = $_GET['widgetID'];
                 // data array
                 $this->data = array();
                 // get widget settings from db
                 $res = $db->query("SELECT property, value FROM {widget_settings}
                        WHERE widgetID = '".$this->id."'
                        AND activated = '1'");
                 // get data in loop
                 while($row = mysqli_fetch_assoc($res))
                 {   // set widget properties and values into this data array
                     $this->data[$row['property']] = $row['value'];
                 } // end while fetch row (fetch widget settings)
                 // check if data array is set
                 if (is_array($this->data))
                 {   // ok, return widget settings array
                     return ($this->data);
                 }
                 else
                 {   // widget settings could not be retrieved
                     echo "Error: this data object is empty - unable to load widget settings of widget ID: ".$this->id."";
                     echo "<pre>";
                     print_r($this);
                     echo "</pre>";
                 }
             }
             else
             {   // no widget ID requested - do nothing.
                 return null;
             }
             return null;
         }
References $_GET, $db, and $res.
Referenced by YAWK\WIDGETS\BLOG\WIDGET\blogWidget\__construct(), YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus\__construct(), YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\__construct(), YAWK\WIDGETS\CLOCK\CURRENT\clock\__construct(), YAWK\WIDGETS\CONTENTANIMATOR\ANIMATE\contentAnimator\__construct(), YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\__construct(), YAWK\WIDGETS\CUSTOM_HTML\CODE\customHtml\__construct(), YAWK\WIDGETS\EMBED_PAGE\PAGE\embedPage\__construct(), YAWK\WIDGETS\EXAMPLE\DEMO\example\__construct(), YAWK\WIDGETS\FACEBOOK\EVENTS\fbEvents\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEBUTTON\fbLikeButton\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\__construct(), YAWK\WIDGETS\FACEBOOK\POSTING\fbPosting\__construct(), YAWK\WIDGETS\FACEBOOK\VIDEO\fbVideo\__construct(), YAWK\WIDGETS\FUCKADBLOCK\BLOCK\fuckadblock\__construct(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\__construct(), YAWK\WIDGETS\GOOGLE\ANALYTICS\googleAnalytics\__construct(), YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\__construct(), YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\__construct(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\__construct(), YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\__construct(), YAWK\WIDGETS\PINTEREST\FOLLOW\pinterestFollow\__construct(), YAWK\WIDGETS\PINTEREST\PIN\pinterestPin\__construct(), YAWK\WIDGETS\PINTEREST\PROFILE\pinterestProfile\__construct(), YAWK\WIDGETS\PLYR\PLAYER\plyr\__construct(), YAWK\WIDGETS\PREZI\EMBED\prezi\__construct(), YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\__construct(), YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\__construct(), YAWK\WIDGETS\SPOTIFY\EMBED\spotify\__construct(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\__construct(), YAWK\WIDGETS\TWITCH\EMBED\twitch\__construct(), YAWK\WIDGETS\TWITTER\GRID\twitterGrid\__construct(), YAWK\WIDGETS\TWITTER\TIMELINE\twitterTimeline\__construct(), YAWK\WIDGETS\TWITTER\TWEET\twitterTweet\__construct(), YAWK\WIDGETS\TWITTER\BUTTON\twitterTweetButton\__construct(), YAWK\WIDGETS\YOUTUBE\VIDEO\youtube\__construct(), and YAWK\WIDGETS\BOOKING\FORM\bookingWidget\__construct().
loadWidgetsOfPage()
static YAWK\widget::loadWidgetsOfPage ($db, $page) static
Returns an array of all widgets that are linked with given page->id.
Parameters
object $db database
object $page the current page object
Returns
array return all widgets that are connected with this page
Definition at line 1182 of file widget.php.
         {
             if (isset($page->id) && (is_numeric($page->id)))
             {
                 $row = $db->query("SELECT cw.id,cw.published,cw.widgetType,cw.pageID,cw.sort,cw.position, cw.date_publish, cw.date_unpublish, cw.widgetTitle, cwt.name, cwt.folder
                                 FROM {widgets} as cw
                                 JOIN {widget_types} as cwt on cw.widgetType = cwt.id
                                 WHERE (cw.pageID = '" . $page->id . "' OR cw.pageID = '0')
                                 ORDER BY cw.sort");
                 // create list of widgets as associative array and return it
                 while ($result = mysqli_fetch_assoc($row)){
                     $list[] = $result;
                 }
                 if (isset($list) && (is_array($list))){
                     return $list;
                 }
                 else {
                     return false;
                 }
             }
         }
References $db, $page, and $result.
Referenced by YAWK\backend\drawWidgetsOnPageBox().
printObject()
YAWK\widget::printObject ()
Print all object data.
(for development and testing purpose)
Reimplemented in YAWK\WIDGETS\INSTAGRAM\POSTING\instagram, YAWK\WIDGETS\GOOGLE\MAPS\googleMaps, YAWK\WIDGETS\GOOGLE\ANALYTICS\googleAnalytics, YAWK\WIDGETS\GALLERY\IMAGES\gallery, YAWK\WIDGETS\EXAMPLE\DEMO\example, and YAWK\WIDGETS\BLOG\WIDGET\blogWidget.
Definition at line 57 of file widget.php.
         {   // output data to screen
             echo "<pre>";
             print_r($this);
             echo "</pre>";
         }
Member Data Documentation
$data
YAWK\widget::$data
Parameters
array widget settings data array placeholder
Definition at line 50 of file widget.php.
Referenced by YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\drawSocialBar(), and YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\setSocialBarElements().
$date_publish
YAWK\widget::$date_publish
Parameters
string date when widget publishing starts
Definition at line 42 of file widget.php.
$date_unpublish
YAWK\widget::$date_unpublish
Parameters
string date when widget publishing ends
Definition at line 44 of file widget.php.
$folder
YAWK\widget::$folder
Parameters
string foldername of this widget
Definition at line 48 of file widget.php.
$id
YAWK\widget::$id
Parameters
int widget ID
Definition at line 26 of file widget.php.
$marginBottom
YAWK\widget::$marginBottom
Parameters
int margin from bottom in px
Definition at line 38 of file widget.php.
$marginTop
YAWK\widget::$marginTop
Parameters
int margin from top in px
Definition at line 36 of file widget.php.
$name
YAWK\widget::$name
Parameters
string widget name
Definition at line 28 of file widget.php.
$pageID
YAWK\widget::$pageID
Parameters
int ID of the page where this widget should appear
Definition at line 40 of file widget.php.
$position
YAWK\widget::$position
Parameters
string template position to appear
Definition at line 32 of file widget.php.
$published
YAWK\widget::$published
Parameters
int 0|1 published or not
Definition at line 24 of file widget.php.
$sort
YAWK\widget::$sort
Parameters
int order sortation number
Definition at line 30 of file widget.php.
$widgetTitle
YAWK\widget::$widgetTitle
Parameters
string title to identify the widget
Definition at line 46 of file widget.php.
$widgetType
YAWK\widget::$widgetType
Parameters
int widget type number
Definition at line 34 of file widget.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/widget.php