YaWK: YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate Class Reference
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate Class Reference
Embed chaturbate room (or stream) on your website.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embed ()
Embed any chaturbate room on your website.
init ()
printObject ()
Print all object data.
setProperties ()
Set widget properties from database and fill object params.
Public Attributes
$chaturbateDisableSound = ''
$chaturbateHeading = ''
$chaturbateHeadline = ''
$chaturbateHeight = '370'
$chaturbateRoom = ''
$chaturbateSubtext = ''
$chaturbateVideoOnly = '0'
$chaturbateVideoUrl = ''
$chaturbateWidth = '100%'
$widget = ''
Detailed Description
Embed chaturbate room (or stream) on your website.
Embed any chaturbate channel or stream on your page.
Chaturbate.com is an adult webcam streaming service. With this widget, you can embed any public channel or stream from chaturbate onto your website. All you need is any chaturbate username you wish to embed. But there are a few things to setup. If you like to, you are able to set width, height sound settings and more. By using this widget, embedding a stream from chaturbate is very easy.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file chaturbate.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 45 of file chaturbate.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embed()
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::embed ()
Embed any chaturbate room on your website.
This method embeds the chaturbate stream
Definition at line 112 of file chaturbate.php.
         {
 echo"<style>
 .videoWrapper {
             position: relative;
             padding-bottom: 56.25%; /* 16:9 */
             padding-top: 25px;
             height: 0;
 }
 .videoWrapper iframe {
             position: absolute;
             top: 0;
             left: 0;
             width: 100%;
             height: 100%;
             border: none;
         }
 </style>";
             // HTML output
             echo "
 <!-- chaturbate room stream iframe -->
 $this->chaturbateHeadline
 <div class=\"videoWrapper\">
 <iframe src=\"$this->chaturbateVideoUrl\"
         width=\"$this->chaturbateWidth\"
         height=\"$this->chaturbateHeight\"
         frameborder=\"0\"
         scrolling=\"no\">
 </iframe></div>";
Referenced by YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\init().
init()
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::init ()
Definition at line 66 of file chaturbate.php.
         {
             $this->setProperties();
             $this->embed();
References YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\embed(), and YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\setProperties().
printObject()
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 59 of file chaturbate.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
setProperties()
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::setProperties ()
Set widget properties from database and fill object params.
Load all widget settings.
Definition at line 76 of file chaturbate.php.
         {
             // if a heading is set and not empty
             if (isset($this->chaturbateHeading) && (!empty($this->chaturbateHeading)))
             {   // add h1 tag to heading string
                 $this->chaturbateHeading = "$this->chaturbateHeading";
                 // if subtext is set, add <small> subtext to string
                 if (isset($this->chaturbateSubtext) && (!empty($this->chaturbateSubtext)))
                 {   // build a headline with heading and subtext
                     $this->chaturbateSubtext = "<small>$this->chaturbateSubtext</small>";
                     $this->chaturbateHeadline = "<h1>$this->chaturbateHeading&nbsp;"."$this->chaturbateSubtext</h1>";
                 }
                 else
                 {   // build just a headline - without subtext
                     $this->chaturbateHeadline = "<h1>$this->chaturbateHeading</h1>";    // draw just the heading
                 }
             }
             else
             {   // leave empty if it's not set
                 $this->chaturbateHeadline = '';
             }
             if (substr($this->chaturbateWidth, -1) !== "%")
             {
                 $this->chaturbateWidth = $this->chaturbateWidth."%";
             }
             // build video url
             $this->chaturbateVideoUrl = "https://chaturbate.com/embed/$this->chaturbateRoom?bgcolor=transparent&disable_sound=$this->chaturbateDisableSound&fullscreen=true&embed_video_only=$this->chaturbateVideoOnly&target=_blank";
Referenced by YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\init().
Member Data Documentation
$chaturbateDisableSound
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateDisableSound = ''
Parameters
string Disable Sound
Definition at line 30 of file chaturbate.php.
$chaturbateHeading
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateHeading = ''
Parameters
string Heading
Definition at line 34 of file chaturbate.php.
$chaturbateHeadline
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateHeadline = ''
Parameters
string Headline HTML Markup
Definition at line 38 of file chaturbate.php.
$chaturbateHeight
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateHeight = '370'
Parameters
string Height in px
Definition at line 28 of file chaturbate.php.
$chaturbateRoom
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateRoom = ''
Parameters
string Chaturbate room name (username)
Definition at line 22 of file chaturbate.php.
$chaturbateSubtext
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateSubtext = ''
Parameters
string Subtext
Definition at line 36 of file chaturbate.php.
$chaturbateVideoOnly
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateVideoOnly = '0'
Parameters
string Disable Sound
Definition at line 32 of file chaturbate.php.
$chaturbateVideoUrl
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateVideoUrl = ''
Parameters
string URL of your chaturbate stream
Definition at line 24 of file chaturbate.php.
$chaturbateWidth
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$chaturbateWidth = '100%'
Parameters
string Width in percent
Definition at line 26 of file chaturbate.php.
$widget
YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file chaturbate.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/chaturbate/classes/chaturbate.php