YaWK: YAWK\PLUGINS\USERPAGE\userpage Class Reference
YAWK\PLUGINS\USERPAGE\userpage Class Reference
Userpage Profile Class.
Public Member Functions
__construct ($db, $user)
userpage constructor.
getRootPage ($db, $user)
detect admin and build a special 'ROOT' page with admin functions... TODO: in development
getUserPage ($db, $user, $lang)
getUserPage is a wrapper for buildPage
init ($db, $user, $lang)
init function check if backend is allowed and load userpage
Protected Attributes
$appendPanel
$appendTab
$dashboard
Detailed Description
Userpage Profile Class.
Userpage Plugin
Userpage Class check and build the userpage.
Class covers frontend functionality. See Methods Summary for Details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl
Version
1.0.0
Definition at line 14 of file userpage.php.
Constructor & Destructor Documentation
__construct()
YAWK\PLUGINS\USERPAGE\userpage::__construct ($db, $user)
userpage constructor.
Parameters
object $db database
object $user user object
Definition at line 28 of file userpage.php.
{
             /* property $user */
             if (isset($username) && (!empty($username)))
             {
                 $this->user = $username;
             }
             $this->usergroup = \YAWK\user::getGroup($db);
         }
References $db, and $username.
Member Function Documentation
getRootPage()
YAWK\PLUGINS\USERPAGE\userpage::getRootPage ($db, $user)
detect admin and build a special 'ROOT' page with admin functions... TODO: in development
Parameters
object $db database
object $user object
Returns
string buildPage with admin functions
Definition at line 82 of file userpage.php.
{
             // check, if admin tab is enabled
             if (\YAWK\settings::getSetting($db, "userpage_admin") === '1'){
                 // prepare dashboard
                 $this->dashboard = "<h5 class=\"btn-danger\">*** ROOT MODE ***</h5>";
                 // root mode notice
                 $this->dashboard .= "Hello $user->username! You are logged in with root access.";
                 // append admin panel + tab
                 $this->appendTab = "<li class=\"nav-item\" role=\"admin\"><a href=\"#admin\" class=\"nav-link\" aria-controls=\"admin\" role=\"tab\" data-toggle=\"tab\">
                                 <i class=\"fa fa-wrench\"></i>&nbsp; Admin</a></li>";
                 $this->appendPanel = "<div role=\"tabpanel\" class=\"tab-pane animated fadeIn\" id=\"admin\"><h4>
                                       <i class=\"fa fa-lock fa-2x\"></i> &nbsp;Admin Stuff...</h4></div>";
             }
             else {
                 $this->appendTab = "";
                 $this->appendPanel = "";
             }
             return self::buildPage($db, $user->username, $user->gid, $this->appendTab, $this->appendPanel, $this->dashboard, $lang);
         }
References $db, $lang, and YAWK\settings\getSetting().
Referenced by YAWK\PLUGINS\USERPAGE\userpage\init().
getUserPage()
YAWK\PLUGINS\USERPAGE\userpage::getUserPage ($db, $user, $lang)
getUserPage is a wrapper for buildPage
Parameters
object $db database
object $user object
object $lang language
Returns
string buildPage function
Definition at line 72 of file userpage.php.
{
             return $this->buildPage($db, $user->username, $user->gid, $this->appendTab, $this->appendPanel, $this->dashboard, $lang);
         }
References $db, and $lang.
Referenced by YAWK\PLUGINS\USERPAGE\userpage\init().
init()
YAWK\PLUGINS\USERPAGE\userpage::init ($db, $user, $lang)
init function check if backend is allowed and load userpage
Parameters
object $db database
object $user user
Returns
bool|null|string
Definition at line 43 of file userpage.php.
{
             if ($this->usergroup['backend_allowed'] !== '1'){
                 // backend access not allowed
                 // check usergroup
                 if ($this->usergroup['backend_allowed'] === '0') {
                     // load userpage
                     return $this->getUserPage($db, $user, $lang);
                 }
                 else
                 {   // throw error
                     return \YAWK\alert::draw("danger", "Error", "Could not load userpage. Something strange has happened.","",6800);
                 }
             }
             else {
                 // backend access granted, load root page
                 if (\YAWK\user::isAdmin($db)){
                     return $this->getRootPage($db, $user);
                 }
             }
             return null;
         }
References $db, $lang, YAWK\PLUGINS\USERPAGE\userpage\getRootPage(), and YAWK\PLUGINS\USERPAGE\userpage\getUserPage().
Member Data Documentation
$appendPanel
YAWK\PLUGINS\USERPAGE\userpage::$appendPanel protected
Parameters
string append panel
Definition at line 21 of file userpage.php.
$appendTab
YAWK\PLUGINS\USERPAGE\userpage::$appendTab protected
Parameters
string append tab
Definition at line 19 of file userpage.php.
$dashboard
YAWK\PLUGINS\USERPAGE\userpage::$dashboard protected
Parameters
string dashboard
Definition at line 17 of file userpage.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/plugins/userpage/classes/userpage.php