YaWK: YAWK\stats Class Reference
YAWK\stats Class Reference
Statistics - get and set user and page stats.
Public Member Functions
calculateStatsFromArray ($db, $data)
Calculate some basic stats (almost outdated)
construct ()
countBrowsers ($db, $data)
Count and return browsers.
countDaytime ($db, $data, $lang)
Count and set the number of hits for each daytime.
countDeviceTypes ($db, $data)
Count device types (desktop, phone or tablet)
countLogins ($db)
Count system logins.
countMessages ($db)
Count all messages that are stored in the database.
countOS ($db, $data)
Count operating systems.
countOSVersions ($db, $data)
Count operating systems versions.
countWeekdays ($db, $data, $lang, $limit)
Count and set the number of hits for each weekday.
deleteOutdatedSessions ($db)
Check and delete outdated sessions if they are expired.
drawOverviewBox ($lang)
Draw default box containing overview statistics.
drawPagesBox ($data, $lang)
Draw default box containing pages statistics.
drawUserStats ($db, $lang)
Draw a default box containing user statistics.
getBrowserColors ($browser)
Set and return the legend textcolor for each browser.
getDaysOfMonthBox ($lang)
Draw default box containing days of month statistics.
getDaytimeColors ($daytime, $lang)
Set and return the legend textcolor for each daytime.
getDayTimesPercent ($lang)
Calculate hits per daytime and return data in percent.
getDeviceTypeColors ($deviceType)
Set and return the legend textcolor for each device type.
getJsonBrowsers ($db, $browsers)
Output JS: PIE CHART browser data.
getJsonDaytimeBarChart ($db, $daytimes, $lang)
Output JS: BAR CHART daytime data.
getJsonDaytimeLineChart ($db, $daytimes, $lang)
Output JS: LINE CHART daytime data.
getJsonDaytimePieChart ($db, $daytimes, $lang)
Output JS: PIE CHART daytime data.
getJsonDeviceTypes ($db, $deviceTypes, $lang)
Output JS: BAR CHART device types.
getJsonLogins ($db, $logins, $lang)
Output JS: PIE CHART login data.
getJsonOS ($db, $oss)
Output JS: PIE CHART OS data.
getJsonOSVersions ($db, $osVersions)
Output JS: BAR CHART OS versions.
getJsonWeekdayBarChart ($lang)
Output JS: WEEKDAY BAR CHART.
getLoginColors ($login)
Set and return the legend textcolor for logins (failed | success)
getOnlineUsers ($db)
Return the number of all currently online users.
getOsColors ($os)
Set and return the legend textcolor for each operating system.
getOsVersionsColors ($osVersions)
Set and return the legend textcolor for each OS Version.
getStatsArray ($db, $interval, $period)
Returns an array with all stats, ordered by date_created.
getUserStats ($db)
Count and set user stats like, how many users are registered, currently online or blocked.
getWeekdaysPercent ($lang)
Calculate hits in percent for each weekday.
insertData ($db)
Insert data into database.
prepareData ()
Prepare data: get and collect, detect OS and device type.
setOnlineUsers ($db)
Set users online in database (stores and check sessions and timestamps)
setStats ($db)
Insert statistics data into database.
Public Attributes
$acceptLanguage
$activeSessions
$browser
$browserVersion
$currentOnline = 0
$currentTimeStamp
$date_created
$device
$deviceType
$gid = 0
$i_afternoon = 0
$i_afternoonPercent = 0
$i_android = 0
$i_blackberry = 0
$i_blockedUsers = 0
$i_desktop = 0
$i_desktopPercent = 0
$i_evening = 0
$i_eveningPercent = 0
$i_friday = 0
$i_fridayPercent = 0
$i_hits = 0
$i_iOS = 0
$i_iPad = 0
$i_iPhone = 0
$i_iPod = 0
$i_linux = 0
$i_loggedInUsers = 0
$i_loggedUsers = 0
$i_loggedUsersPercentage = 0
$i_loginBackend = 0
$i_loginBackendFailed = 0
$i_loginBackendSuccess = 0
$i_loginFailed = 0
$i_loginFailedPercentage = 0
$i_loginFrontend = 0
$i_loginFrontendFailed = 0
$i_loginFrontendSuccess = 0
$i_loginSuccessful = 0
$i_loginSuccessPercentage = 0
$i_macos9 = 0
$i_macosX = 0
$i_mobile = 0
$i_monday = 0
$i_mondayPercent = 0
$i_morning = 0
$i_morningPercent = 0
$i_night = 0
$i_nightPercent = 0
$i_osAndroid = 0
$i_osLinux = 0
$i_osMac = 0
$i_osUnknown = 0
$i_osWindows = 0
$i_others = 0
$i_phone = 0
$i_phonePercent = 0
$i_publicUsers = 0
$i_publicUsersPercentage = 0
$i_saturday = 0
$i_saturdayPercent = 0
$i_sunday = 0
$i_sundayPercent = 0
$i_tablet = 0
$i_tabletPercent = 0
$i_thursday = 0
$i_thursdayPercent = 0
$i_totalDays = 0
$i_totalLogins = 0
$i_tuesday = 0
$i_tuesdayPercent = 0
$i_ubuntu = 0
$i_users = 0
$i_wednesday = 0
$i_wednesdayPercent = 0
$i_windows10 = 0
$i_windows11 = 0
$i_windows2000 = 0
$i_windows311 = 0
$i_windows7 = 0
$i_windows8 = 0
$i_windows95 = 0
$i_windows98 = 0
$i_windowsME = 0
$i_windowsServer = 0
$i_windowsVista = 0
$i_windowsXP = 0
$id
$logged_in = 0
$os
$osVersion
$page
$phpSessionID
$referer
$remoteAddr
$uid = 0
$userAgent
Detailed Description
Statistics - get and set user and page stats.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Version
1.0.0
Definition at line 9 of file stats.php.
Member Function Documentation
calculateStatsFromArray()
YAWK\stats::calculateStatsFromArray ($db, $data)
Calculate some basic stats (almost outdated)
Parameters
object $db Database Object
array $data Stats Data Array
Definition at line 2097 of file stats.php.
         {   // get stats data
             if (!isset($data) || (empty($data)))
             {
                 // get statistics into array
                 $data = $this->getStatsArray($db, '', '');
             }
             // count and analyze the stats data in a loop
             foreach ($data as $value => $item)
             {
                 // count hits
                 $this->i_hits++;
                 // count how many users were logged in
                 if ($item['logged_in'] === "1")
                 {
                     $this->i_loggedUsers++;
                 }
                 // count how many users were guests (or not logged in)
                 if ($item['logged_in'] === "0")
                 {
                     $this->i_publicUsers++;
                 }
                 // calculate percentage of guests vs logged in users
                 $percentage = 100 / $this->i_hits;
                 $this->i_loggedUsersPercentage = $this->i_loggedUsers * $percentage;
                 $this->i_publicUsersPercentage = $this->i_publicUsers * $percentage;
                 $this->i_loggedUsersPercentage = round($this->i_loggedUsersPercentage, 1, PHP_ROUND_HALF_UP);
                 $this->i_publicUsersPercentage = round($this->i_publicUsersPercentage, 1, PHP_ROUND_HALF_UP);
             }
             /*
             echo "Total hits: ".$this->i_hits."<br>";
             echo "davon Phone: ".$this->i_phone."<br>";
             echo "davon Tablet: ".$this->i_tablet."<br>";
             echo "davon Desktop: ".$this->i_desktop." Win: $this->i_osWindows Mac: $this->i_osMac Linux: $this->i_osLinux<br>";
             echo "<pre>";
             print_r($data);
             echo "</pre>";
             */
References $data, $db, YAWK\stats\$i_hits, $item, $value, and YAWK\stats\getStatsArray().
Referenced by YAWK\stats\getStatsArray().
construct()
YAWK\stats::construct ()
Definition at line 223 of file stats.php.
         {
countBrowsers()
YAWK\stats::countBrowsers ($db, $data)
Count and return browsers.
Parameters
object $db the database object
string $data array containing all the stats data
string $limit contains i number for sql limitation
Returns
array|bool returning array containing the browsers and their hits
Definition at line 1573 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
                 // check if limit (i) is set
                 if (!isset($limit) || (empty($limit)))
                 {   // set default value
                     $limit = 100;
                 }
             */
             // this vars stores the counting for each browser
             $n_msie = 0;
             $n_chrome = 0;
             $n_firefox = 0;
             $n_opera = 0;
             $n_safari = 0;
             $n_netscape = 0;
             $n_others = 0;
             $total = 0;
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 // \YAWK\alert::draw("warning", "database needed", "need to get browser data - array not set, empty or not an array.", "", 0);
                 if ($res = $db->query("SELECT browser FROM {stats} ORDER BY id DESC"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                         $total++;
                     }
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             // count browsers
             foreach ($data AS $item => $browser) {   // add +1 for each found
                 switch ($browser['browser']) {
                     case "Google Chrome":
                         $n_chrome++;
                         break;
                     case "Internet Explorer":
                         $n_msie++;
                         break;
                     case "Mozilla Firefox":
                         $n_firefox++;
                         break;
                     case "Apple Safari":
                         $n_safari++;
                         break;
                     case "Opera":
                         $n_opera++;
                         break;
                     case "Netscape":
                         $n_netscape++;
                         break;
                     default:
                         $n_others++;
                 }
             }
             // get the sum of all detected browsers
             $total = $n_chrome+$n_msie+$n_firefox+$n_safari+$n_opera+$n_netscape+$n_others;
             // build an array, cointaining the browsers and the number how often it's been found
             $browsers = array(
                 "Chrome" => $n_chrome,
                 "IE" => $n_msie,
                 "Firefox" => $n_firefox,
                 "Safari" => $n_safari,
                 "Opera" => $n_opera,
                 "Netscape" => $n_netscape,
                 "Others" => $n_others,
                 "Total" => $total
             );
             // return browser data array
             return $browsers;
References YAWK\stats\$browser, $data, $db, $item, $res, and $total.
Referenced by YAWK\stats\getJsonBrowsers().
countDaytime()
YAWK\stats::countDaytime ($db, $data, $lang)
Count and set the number of hits for each daytime.
Parameters
object $db the database object
string $data array containing all the stats data
string $limit contains i number for sql limitation
Returns
array|bool containing daytimes (and number of hits
Definition at line 1430 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
                 // check if limit (i) is set
                 if (!isset($limit) || (empty($limit)))
                 {   // set default value
                     $limit = 100;
                 }
             */
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 if ($res = $db->query("SELECT date_created FROM {stats} ORDER BY id DESC"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                     }
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             // break up the date & extract the hour to calculate
             foreach ($data as $date => $value)
             {
                 // get only the hour in a new array
                 $hour = substr($value['date_created'], 11, -6);
                 // identify morning, afternoon, evening + night
                 if ($hour === "06" ||
                     ($hour === "07") ||
                     ($hour === "08") ||
                     ($hour === "09") ||
                     ($hour === "10") ||
                     ($hour === "11"))
                 {
                     $this->i_morning++;
                 }
                 if ($hour === "12" ||
                     ($hour === "13") ||
                     ($hour === "14") ||
                     ($hour === "15") ||
                     ($hour === "16") ||
                     ($hour === "17"))
                 {
                     $this->i_afternoon++;
                 }
                 if ($hour === "18" ||
                     ($hour === "19") ||
                     ($hour === "20") ||
                     ($hour === "21") ||
                     ($hour === "22") ||
                     ($hour === "23"))
                 {
                     $this->i_evening++;
                 }
                 if ($hour === "00" ||
                     ($hour === "01") ||
                     ($hour === "02") ||
                     ($hour === "03") ||
                     ($hour === "04") ||
                     ($hour === "05"))
                 {
                     $this->i_night++;
                 }
             }
             // count daytimes
             $total = $this->i_morning+$this->i_afternoon+$this->i_evening+$this->i_night;
             // build an array, cointaining the daytimes
             $dayTimes = array(
                 "$lang[MORNING]" => $this->i_morning,
                 "$lang[AFTERNOON]" => $this->i_afternoon,
                 "$lang[EVENING]" => $this->i_evening,
                 "$lang[NIGHT]" => $this->i_night,
                 "$lang[TOTAL]" => $total
             );
             // return OS data array
             return $dayTimes;
References $data, $date, $db, YAWK\stats\$i_night, $res, $total, and $value.
Referenced by YAWK\stats\getJsonDaytimeBarChart(), YAWK\stats\getJsonDaytimeLineChart(), and YAWK\stats\getJsonDaytimePieChart().
countDeviceTypes()
YAWK\stats::countDeviceTypes ($db, $data)
Count device types (desktop, phone or tablet)
Parameters
object $db the database object
string $data array containing all the stats data
string $limit contains i number for sql limitation
Returns
array|bool returning array containing device types and their hits
Definition at line 1673 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
             // check if limit (i) is set
             if (!isset($limit) || (empty($limit)))
             {   // set default value
                 $limit = 100;
             }
             */
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 $intervalQuery = "WHERE {stats}.date_created > DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
                 if ($res = $db->query("SELECT deviceType FROM {stats} $intervalQuery ORDER BY id DESC"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                     }
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             foreach ($data as $deviceType => $value)
             {
                 // count device types
                 switch ($value['deviceType'])
                 {
                     case "Desktop":
                         $this->i_desktop++;
                         break;
                     case "Tablet":
                         $this->i_tablet++;
                         break;
                     case "Phone":
                         $this->i_phone++;
                         break;
                 }
             }
             // count device types
             $total = $this->i_desktop+$this->i_tablet+$this->i_phone;
             // calculate percentage of device types
             if ($total > 0)
             {
                 $a = 100 / $total;
                 $this->i_desktopPercent = $a * $this->i_desktop;
                 $this->i_tabletPercent = $a * $this->i_tablet;
                 $this->i_phonePercent = $a * $this->i_phone;
                 // build an array, cointaining the device types and the number how often it's been found
                 $deviceTypes = array(
                     "Desktop" => $this->i_desktop,
                     "Tablet" => $this->i_tablet,
                     "Phone" => $this->i_phone,
                     "Total" => $total
                 );
                 // return device type array
                 return $deviceTypes;
             }
             else
             {   // no result,
                 return null;
             }
References $data, $db, YAWK\stats\$deviceType, YAWK\stats\$i_desktop, YAWK\stats\$i_phone, YAWK\stats\$i_tablet, $res, $total, and $value.
Referenced by YAWK\stats\getJsonDeviceTypes().
countLogins()
YAWK\stats::countLogins ($db)
Count system logins.
Parameters
object $db Database Object
int $limit Contains an i number to limit the sql request
Returns
array|bool
Definition at line 575 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
             if (!isset($limit) || (empty($limit)))
             {
                 $limit = 100;
             }
             */
             if ($res = $db->query("SELECT * FROM {logins}"))
             {   // fetch and return how many messages have been sent
                 $loginDataArray = array();
                 // count login data
                 while ($row = mysqli_fetch_assoc($res))
                 {
                     // GET AN ARRAY CONTAINING ALL DATA FROM LOGIN DB
                     // $loginDataArray[] = $row;
                     // count +1 to all logins
                     $this->i_totalLogins++;
                     // count frontend logins
                     if ($row['location'] === "frontend")
                     {
                         // add total frontendlogins +1
                         $this->i_loginFrontend++;
                         if ($row['failed'] === "1")
                         {   // frontend login failed +1
                             $this->i_loginFrontendFailed++;
                         }
                         else
                         {   // frontend login success +1
                             $this->i_loginFrontendSuccess++;
                         }
                     }
                     // count backend logins
                     if ($row['location'] === "backend")
                     {   // add total backend login +1
                         $this->i_loginBackend++;
                         if ($row['failed'] === "1")
                         {   // backend login failed +1
                             $this->i_loginBackendFailed++;
                         }
                         else
                         {   // backend login success +1
                             $this->i_loginBackendSuccess++;
                         }
                     }
                     // total success logins +1
                     if ($row['failed'] === "0")
                     {   // success +1
                         $this->i_loginSuccessful++;
                     }
                     // total failed logins +1
                     if ($row['failed'] === "1")
                     {   // failed +1
                         $this->i_loginFailed++;
                     }
                 }
                 if ($this->i_totalLogins > 0)
                 {
                     // calculate percentage
                     $total = $this->i_totalLogins;
                     $failed = $this->i_loginFailed;
                     $success = $this->i_loginSuccessful;
                     $total = 100 / $total;
                     $this->i_loginFailedPercentage = round($total * $failed);
                     $this->i_loginSuccessPercentage = round($total * $success);
                 }
                 // build an array, cointaining the failed and successful logins
                 $loginDataArray = array(
                     "Failed" => $this->i_loginFailed,
                     "Successful" => $this->i_loginSuccessful,
                     "BackendSuccess" => $this->i_loginBackendSuccess,
                     "BackendFailed" => $this->i_loginBackendFailed,
                     "FrontendSuccess" => $this->i_loginFrontendSuccess,
                     "FrontendFailed" => $this->i_loginFrontendFailed,
                     "FailedPercentage" => $this->i_loginFailedPercentage,
                     "SuccessPercentage" => $this->i_loginSuccessPercentage,
                     "Total" => $this->i_totalLogins
                 );
                 return $loginDataArray;
             }
             else
             {
                 \YAWK\alert::draw("warning", "Could not get login data array.", "error getting data into array", "", 5200);
                 return false;
             }
References $db, YAWK\stats\$i_loginFailed, YAWK\stats\$i_loginSuccessful, YAWK\stats\$i_totalLogins, $res, $total, and YAWK\alert\draw().
Referenced by YAWK\stats\getJsonLogins().
countMessages()
YAWK\stats::countMessages ($db)
Count all messages that are stored in the database.
Parameters
object $db Database Object
Returns
mixed
Definition at line 519 of file stats.php.
         {   /* @param $db \YAWK\db */
             if ($res = $db->query("SELECT COUNT(*) FROM {plugin_msg}"))
             {   // fetch and return how many messages have been sent
                 $messageCount = mysqli_fetch_row($res);
                 return $messageCount[0];
             }
             else
             {
                 $messageCount = "db error: could not count messages";
                 return $messageCount;
             }
References $db, and $res.
countOS()
YAWK\stats::countOS ($db, $data)
Count operating systems.
Parameters
object $db the database object
string $data array containing all the stats data
string $limit contains i number for sql limitation
Returns
array|bool returning array containing all detected operating systems and their hits
Definition at line 1759 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
                 // check if limit (i) is set
                 if (!isset($limit) || (empty($limit)))
                 {   // set default value
                     $limit = 100;
                 }
             */
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 // \YAWK\alert::draw("warning", "database needed", "need to get browser data - array not set, empty or not an array.", "", 0);
                 if ($res = $db->query("SELECT os FROM {stats} ORDER BY id DESC"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                     }
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             foreach ($data as $os => $value)
             {
                 // count Operating Systems
                 switch ($value['os'])
                 {
                     case "Windows";
                         $this->i_osWindows++;
                         break;
                     case "Linux";
                         $this->i_osLinux++;
                         break;
                     case "Mac";
                         $this->i_osMac++;
                         break;
                     case "Android";
                         $this->i_osAndroid++;
                         break;
                     case "iOS";
                         $this->i_iOS++;
                         break;
                     default: $this->i_osUnknown++;
                 }
             }
             // count Operating Systems
             $total = $this->i_osWindows+$this->i_osLinux+$this->i_osMac+$this->i_osAndroid+$this->i_iOS+$this->i_osUnknown;
             // build an array, cointaining the browsers and the number how often it's been found
             $os = array(
                 "Windows" => $this->i_osWindows,
                 "Linux" => $this->i_osLinux,
                 "Mac" => $this->i_osMac,
                 "Android" => $this->i_osAndroid,
                 "iOS" => $this->i_iOS,
                 "Unknown" => $this->i_osUnknown,
                 "Total" => $total
             );
             // return OS data array
             return $os;
References $data, $db, YAWK\stats\$i_osUnknown, YAWK\stats\$os, $res, $total, and $value.
Referenced by YAWK\stats\getJsonOS().
countOSVersions()
YAWK\stats::countOSVersions ($db, $data)
Count operating systems versions.
Parameters
object $db the database object
string $data array containing all the stats data
Returns
array|bool returning array containing all detected OS versions and their hits
Definition at line 1842 of file stats.php.
         {   /* @param $db \YAWK\db */
             /*
                 // check if limit (i) is set
                 if (!isset($limit) || (empty($limit)))
                 {   // set default value
                     $limit = 100;
                 }
             */
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 // \YAWK\alert::draw("warning", "database needed", "need to get browser data - array not set, empty or not an array.", "", 0);
                 if ($res = $db->query("SELECT osVersion FROM {stats} ORDER BY id DESC"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                     }
                     return $data;
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             // count browsers
             foreach ($data AS $item => $osVersion) {   // add +1 for each found
                 // count Operating Systems Versions
                 if ($osVersion['os'] === "Android")
                 {
                     $osVersion['osVersion'] .= "Android ".$osVersion['osVersion'];
                 }
                 switch ($osVersion['osVersion'])
                 {
                     case "Windows 11";
                         $this->i_windows11++;
                         break;
                     case "Windows 10";
                         $this->i_windows10++;
                         break;
                     case "Windows 8";
                         $this->i_windows8++;
                         break;
                     case "Windows 7";
                         $this->i_windows7++;
                         break;
                     case "Windows Vista";
                         $this->i_windowsVista++;
                         break;
                     case "Windows Server 2003/XP x64";
                         $this->i_windowsServer++;
                         break;
                     case "Windows XP";
                         $this->i_windowsXP++;
                         break;
                     case "Windows 2000";
                         $this->i_windows2000++;
                         break;
                     case "Windows ME";
                         $this->i_windowsME++;
                         break;
                     case "Windows 98";
                         $this->i_windows98++;
                         break;
                     case "Windows 95";
                         $this->i_windows95++;
                         break;
                     case "Windows 3.11";
                         $this->i_windows311++;
                         break;
                     case "Max OS X";
                         $this->i_macosX++;
                         break;
                     case "Max OS 9";
                         $this->i_macos9++;
                         break;
                     case "Linux";
                         $this->i_linux++;
                         break;
                     case "Ubuntu";
                         $this->i_ubuntu++;
                         break;
                     case "iPhone";
                         $this->i_iPhone++;
                         break;
                     case "iPad";
                         $this->i_iPad++;
                         break;
                     case "iPod";
                         $this->i_iPod++;
                         break;
                     case "Android":
                         $this->i_android++;
                         break;
                     case "BlackBerry";
                         $this->i_blackberry++;
                         break;
                     case "Mobile";
                         $this->i_mobile++;
                         break;
                     // could not detect OS Version
                     default:
                         $this->i_others++;
                 }
             }
             // count OS Versions
             $total = $this->i_windows11
                 +$this->i_windows10
                 +$this->i_windows8
                 +$this->i_windows7
                 +$this->i_windowsVista
                 +$this->i_windowsServer
                 +$this->i_windows2000
                 +$this->i_windowsXP
                 +$this->i_windowsME
                 +$this->i_windows98
                 +$this->i_windows95
                 +$this->i_windows311
                 +$this->i_macosX
                 +$this->i_macos9
                 +$this->i_linux
                 +$this->i_ubuntu
                 +$this->i_iPhone
                 +$this->i_iPad
                 +$this->i_iPod
                 +$this->i_android
                 +$this->i_blackberry
                 +$this->i_mobile
                 +$this->i_others;
             // build an array, cointaining the counted OS Versions and the sum overall
             $osVersions = array(
                 "Windows 11" => $this->i_windows11,
                 "Windows 10" => $this->i_windows10,
                 "Windows 8" => $this->i_windows8,
                 "Windows 7" => $this->i_windows7,
                 "Windows Vista" => $this->i_windowsVista,
                 "Windows Server" => $this->i_windowsServer,
                 "Windows 2000" => $this->i_windows2000,
                 "Windows XP" => $this->i_windowsXP,
                 "Windows ME" => $this->i_windowsME,
                 "Windows 98" => $this->i_windows98,
                 "Windows 95" => $this->i_windows95,
                 "Windows 3.11" => $this->i_windows311,
                 "Mac OS X" => $this->i_macosX,
                 "Mac OS 9" => $this->i_macos9,
                 "Linux" => $this->i_linux,
                 "Ubuntu" => $this->i_ubuntu,
                 "iPhone" => $this->i_iPhone,
                 "iPad" => $this->i_iPad,
                 "iPod" => $this->i_iPod,
                 "Android" => $this->i_android,
                 "Blackberry" => $this->i_blackberry,
                 "Mobile" => $this->i_mobile,
                 "Unknown" => $this->i_others,
                 "Total" => $total
             );
             // return OS data array
             return $osVersions;
References $data, $db, YAWK\stats\$i_others, $item, YAWK\stats\$osVersion, $res, and $total.
Referenced by YAWK\stats\getJsonOSVersions().
countWeekdays()
YAWK\stats::countWeekdays ($db, $data, $lang, $limit)
Count and set the number of hits for each weekday.
Parameters
object $db the database object
string $data array containing all the stats data
string $limit contains i number for sql limitation
object $lang language array
Returns
array|bool containing weekdays and number of hits
Definition at line 1279 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if limit (i) is set
             if (!isset($limit) || (empty($limit)))
             {   // set default value
                 $limitSql = '';
             }
             else
             {
                 $limitSql = ' LIMIT '.$limit;
             }
             // check if data array is set, if not load data from db
             if (!isset($data) || (empty($data) || (!is_array($data))))
             {   // data is not set or in false format, try to get it from database
                 if ($res = $db->query("SELECT date_created FROM {stats} ORDER BY id DESC$limitSql"))
                 {   // create array
                     $data = array();
                     while ($row = mysqli_fetch_assoc($res))
                     {   // add data to array
                         $data[] = $row;
                     }
                 }
                 else
                 {   // data array not set and unable to get data from db
                     return false;
                 }
             }
             /*
             // LIMIT the data to x entries
             if (isset($limit) && (!empty($limit)))
             {   // if limit is set, cut array to limited range
                 $data = array_slice($data, 0, $limit, true);
             }
             */
             // break up the date & extract the hour to calculate
             foreach ($data as $date => $value)
             {
                 $weekday = \YAWK\sys::getWeekday($value['date_created'], $lang);
                 // identify days
                 if ($weekday === "Monday" ||
                     ($weekday === "$lang[MONDAY]"))
                 {
                     $this->i_monday++;
                 }
                 elseif ($weekday === "Tuesday" ||
                     ($weekday === "$lang[TUESDAY]"))
                 {
                     $this->i_tuesday++;
                 }
                 elseif ($weekday === "Wednesday" ||
                     ($weekday === "$lang[WEDNESDAY]"))
                 {
                     $this->i_wednesday++;
                 }
                 elseif ($weekday === "Thursday" ||
                     ($weekday === "$lang[THURSDAY]"))
                 {
                     $this->i_thursday++;
                 }
                 elseif ($weekday === "Friday" ||
                     ($weekday === "$lang[FRIDAY]"))
                 {
                     $this->i_friday++;
                 }
                 elseif ($weekday === "Saturday" ||
                     ($weekday === "$lang[SATURDAY]"))
                 {
                     $this->i_saturday++;
                 }
                 elseif ($weekday === "Sunday" ||
                     ($weekday === "$lang[SUNDAY]"))
                 {
                     $this->i_sunday++;
                 }
             }
             // count daytimes
             $this->i_totalDays = $this->i_monday
                 +$this->i_tuesday
                 +$this->i_wednesday
                 +$this->i_thursday
                 +$this->i_friday
                 +$this->i_saturday
                 +$this->i_sunday;
             // build an array, cointaining the daytimes
             $weekdays = array(
                 "$lang[MONDAY]" => $this->i_monday,
                 "$lang[TUESDAY]" => $this->i_tuesday,
                 "$lang[WEDNESDAY]" => $this->i_wednesday,
                 "$lang[THURSDAY]" => $this->i_thursday,
                 "$lang[FRIDAY]" => $this->i_friday,
                 "$lang[SATURDAY]" => $this->i_saturday,
                 "$lang[SUNDAY]" => $this->i_sunday,
                 "$lang[TOTAL]" => $this->i_totalDays
             );
             // return OS data array
             return $weekdays;
References $data, $date, $db, YAWK\stats\$i_sunday, $lang, $res, $value, and YAWK\sys\getWeekday().
deleteOutdatedSessions()
YAWK\stats::deleteOutdatedSessions ($db)
Check and delete outdated sessions if they are expired.
Parameters
object $db Database Object
int $expireAfter Time in seconds after a session will be deleted
Returns
bool
Definition at line 262 of file stats.php.
         {   /* @param $db \YAWK\db */
             // set default expire to 60 seconds
             $sessionExpire = time()-60;
             // DELETE OUTDATED SESSIONS
             if ($db->query("DELETE FROM {users_online} WHERE currentTimeStamp < $sessionExpire"))
             {
                 return true;
             }
             else
             {
                 // could not delete outdated sessions
                 // todo: add syslog entry
                 return false;
             }
References $db.
Referenced by YAWK\stats\getOnlineUsers().
drawOverviewBox()
YAWK\stats::drawOverviewBox ($lang)
Draw default box containing overview statistics.
Parameters
array $lang language array
Definition at line 3248 of file stats.php.
         {
             echo "
 <div class=\"row\">
     <div class=\"col-md-12\">
         <!-- box -->
         <div class=\"box\">
             <div class=\"box-header with-border\">
                 <h3 class=\"box-title\">$lang[STATS] <small>$lang[HITS_AND_USER_BEHAVIOR] </small></h3>
             </div>
             <div class=\"box-body\">";
             $this->i_hits = number_format($this->i_hits, 0, '.', '.');
             echo "$lang[ACTIVE_SESSIONS]: <b>$this->currentOnline</b><br>
                 $lang[HITS] $lang[OVERALL]:<b> $this->i_hits</b><br>
                 $lang[GUESTS]: <b> $this->i_publicUsersPercentage</b> % <small>($this->i_publicUsers)</small><br>
                 $lang[MEMBERS]: <b> $this->i_loggedUsersPercentage</b> % <small>($this->i_loggedUsers)</small><br>
             </div>
         </div>
         <!-- / box -->
     </div>
 </div>";
drawPagesBox()
YAWK\stats::drawPagesBox ($data, $lang)
Draw default box containing pages statistics.
Parameters
array $data stats data array
array $lang language array
Definition at line 3277 of file stats.php.
         {
             echo "
         <!-- box -->
         <div class=\"box\">
             <div class=\"box-header with-border\">
                 <h3 class=\"box-title\">$lang[PAGE_VIEWS] <small> $lang[HITS_FROM_MOST_TO_LEAST]</small></h3>
             </div>";
             $res = array();
             if (is_array($data))
             {
                 // $data = array_slice($data, 0, $limit, true);
                 foreach ($data AS $page => $value)
                 {
                     $res[] = $value['page'];
                 }
             }
             $res = (array_count_values($res));
             arsort($res);
             echo "<div class=\"box-footer no-padding\">
                 <ul class=\"nav nav-pills nav-stacked\">";
             // walk through array and display pages as nav pills
             foreach ($res as $page => $value)
             {   // show only items where browser got a value
                 if ($value !== 0 && $page !== 0)
                 {   // get different textcolors
                     echo "<li><a href=\"../$page\" target=\"_blank\"><b>$value</b> &nbsp;<span class=\"text-blue\">$page</span></a></li>";
                 }
             }
             echo "</ul>
             </div>";
References $data, YAWK\stats\$page, $res, and $value.
drawUserStats()
YAWK\stats::drawUserStats ($db, $lang)
Draw a default box containing user statistics.
Parameters
object $db Database Object
object $lang language object
Definition at line 2196 of file stats.php.
         {
             if (self::getUserStats($db))
             {
                 echo "<!-- user settings box -->
         <div class=\"box\">
             <div class=\"box-header with-border\">
                 <h3 class=\"box-title\">$lang[USER] $lang[STATS] <small>$lang[TOTAL_LOGGED_BLOCKED]</small></h3>
             </div>
             <div class=\"box-body\">
                 $lang[USERS]: <b>$this->i_users</b><br>
                 $lang[BLOCKED]: <b>$this->i_blockedUsers</b><br>
                 $lang[LOGGED_IN]: <b>$this->i_loggedInUsers</b>
             </div>
         </div>
         <!-- / stats settings box -->";
             }
References $db.
getBrowserColors()
YAWK\stats::getBrowserColors ($browser)
Set and return the legend textcolor for each browser.
Parameters
object $db Database Object
string $browser contains the browser as string
Returns
string returns the textcolor for this browser as string
Definition at line 1032 of file stats.php.
         {
             switch ($browser) {
                 case "Chrome":
                     $textcolor = "text-red";
                     break;
                 case "Google Chrome":
                     $textcolor = "text-red";
                     break;
                 case "IE":
                     $textcolor = "text-green";
                     break;
                 case "Internet Explorer":
                     $textcolor = "text-green";
                     break;
                 case "Firefox":
                     $textcolor = "text-yellow";
                     break;
                 case "Mozilla Firefox":
                     $textcolor = "text-yellow";
                     break;
                 case "Safari":
                     $textcolor = "text-aqua";
                     break;
                 case "Apple Safari":
                     $textcolor = "text-aqua";
                     break;
                 case "Opera":
                     $textcolor = "text-light-blue";
                     break;
                 case "Netscape":
                     $textcolor = "text-grey";
                     break;
                 case "Navigator":
                     $textcolor = "text-grey";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
References YAWK\stats\$browser.
getDaysOfMonthBox()
YAWK\stats::getDaysOfMonthBox ($lang)
Draw default box containing days of month statistics.
Parameters
array $lang language array
Definition at line 3317 of file stats.php.
         {
             echo "<div class=\"box\">";
             echo "<div class=\"box-header\"><h3 class=\"box-title\">$lang[DAYS_OF_MONTH]</h3></div>";
             echo "<div class=\"box-body\">";
             $daysOfMonth = date("t",mktime(0, 0, 0, 9, 1, 2017));
             $daysOfMonth++; // Zhler bei 1
             for($i = 1; $i < $daysOfMonth; $i++){
                 echo $i."\n";
             }
             echo "</div>";
             echo "</div>"; // end box
References $i, and date.
getDaytimeColors()
YAWK\stats::getDaytimeColors ($daytime, $lang)
Set and return the legend textcolor for each daytime.
Parameters
string $daytime contains the daytime (morning, afternoon, evening, night) as string
Returns
string returns the textcolor for this daytime as string
Definition at line 1133 of file stats.php.
         {
             switch ($daytime) {
                 case "$lang[MORNING]":
                     $textcolor = "text-orange";
                     break;
                 case "$lang[AFTERNOON]":
                     $textcolor = "text-green";
                     break;
                 case "$lang[EVENING]":
                     $textcolor = "text-blue";
                     break;
                 case "$lang[NIGHT]":
                     $textcolor = "text-navy";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
getDayTimesPercent()
YAWK\stats::getDayTimesPercent ($lang)
Calculate hits per daytime and return data in percent.
Parameters
object $db the database object
Returns
array containing daytimes and number of hits in percent
Definition at line 1534 of file stats.php.
         {
             // count daytimes
             $total = $this->i_morning+$this->i_afternoon+$this->i_evening+$this->i_night;
             if ($total > 0)
             {
                 // calculate percentage
                 $a = 100 / $total;
                 $this->i_morningPercent = round($a * $this->i_morning);
                 $this->i_afternoonPercent = round($a * $this->i_afternoon);
                 $this->i_eveningPercent = round($a * $this->i_evening);
                 $this->i_nightPercent = round($a * $this->i_night);
                 // build an array, cointaining the device types and the number how often it's been found
                 $dayTimesPercent = array(
                     "$lang[MORNING]" => $this->i_morningPercent,
                     "$lang[AFTERNOON]" => $this->i_afternoonPercent,
                     "$lang[EVENING]" => $this->i_eveningPercent,
                     "$lang[NIGHT]" => $this->i_nightPercent
                 );
                 arsort($dayTimesPercent);
                 return $dayTimesPercent;
             }
             else
             {
                 return null;
             }
References YAWK\stats\$i_night, and $total.
getDeviceTypeColors()
YAWK\stats::getDeviceTypeColors ($deviceType)
Set and return the legend textcolor for each device type.
Parameters
string $deviceType contains the type (desktop, phone, tablet) as string
Returns
string returns the textcolor for this device type as string
Definition at line 1110 of file stats.php.
         {
             switch ($deviceType) {
                 case "Desktop":
                     $textcolor = "text-orange";
                     break;
                 case "Phone":
                     $textcolor = "text-green";
                     break;
                 case "Tablet":
                     $textcolor = "text-blue";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
References YAWK\stats\$deviceType.
getJsonBrowsers()
YAWK\stats::getJsonBrowsers ($db, $browsers)
Output JS: PIE CHART browser data.
Parameters
object $db Database Object
array $browsers data array
Returns
string output the javascript data
Definition at line 848 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if browsers are set
             if (!isset($browsers) || (empty($browsers)))
             {   // nope, get them from db
                 $browsers = $this->countBrowsers($db, '');
             }
             $jsonData = "[";
             foreach ($browsers AS $browser => $value)
             {
                 // init textcolor
                 $textcolor = '';
                 // set different colors for each browser
                 if ($browser === "Chrome") { $textcolor = "#f56954"; }
                 if ($browser === "IE") { $textcolor = "#00a65a"; }
                 if ($browser === "Edge") { $textcolor = "#00a65a"; }
                 if ($browser === "Kindle") { $textcolor = "#239330"; }
                 if ($browser === "Firefox") { $textcolor = "#f39c12"; }
                 if ($browser === "Safari") { $textcolor = "#00c0ef"; }
                 if ($browser === "Opera") { $textcolor = "#3c8dbc"; }
                 if ($browser === "Netscape") { $textcolor = "#d2d6de"; }
                 if ($browser === "Others") { $textcolor = "#cccccc"; }
                 // only browsers, not the total value
                 if ($browser !== ("Total"))
                 {
                     $jsonData .= "
{
                                 value: $value,
                                 color: \"$textcolor\",
                                 highlight: \"$textcolor\",
                                 label: \"$browser\"
                             },";
                 }
             }
             $jsonData .= "]";
             return $jsonData;
References YAWK\stats\$browser, $db, $value, and YAWK\stats\countBrowsers().
getJsonDaytimeBarChart()
YAWK\stats::getJsonDaytimeBarChart ($db, $daytimes, $lang)
Output JS: BAR CHART daytime data.
Parameters
object $db Database Object
array $daytimes data array
Returns
string output the javascript data
Definition at line 794 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if device types are set
             if (!isset($daytimes) || (empty($daytimes)))
             {   // nope, get them from db
                 $daytimes = $this->countDaytime($db, '', $lang);
             }
             $jsonData = "labels: ['$lang[MORNING]', '$lang[AFTERNOON]', '$lang[EVENING]', '$lang[NIGHT]'],
             datasets: [
                 {
                   label: '$lang[HITS]',
                   fillColor: ['#f39c12', '#00a65a', '#00c0ef', '#003D4C'],
                   strokeColor: 'rgba(210, 214, 222, 1)',
                   pointColor: 'rgba(210, 214, 222, 1)',
                   pointStrokeColor: '#c1c7d1',
                   pointHighlightFill: '#fff',
                   pointHighlightStroke: 'rgba(220,220,220,1)',
                   data: [$this->i_morning, $this->i_afternoon, $this->i_evening, $this->i_night]
                 }
             ]";
             return $jsonData;
References $db, $lang, and YAWK\stats\countDaytime().
getJsonDaytimeLineChart()
YAWK\stats::getJsonDaytimeLineChart ($db, $daytimes, $lang)
Output JS: LINE CHART daytime data.
Parameters
object $db Database Object
array $daytimes data array
array $lang language array
Returns
string output the javascript data
Definition at line 763 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if device types are set
             if (!isset($daytimes) || (empty($daytimes)))
             {   // nope, get them from db
                 $daytimes = $this->countDaytime($db, '', $lang);
             }
             $jsonData = "labels: ['$lang[MORNING]', '$lang[AFTERNOON]', '$lang[EVENING]', '$lang[NIGHT]'],
             datasets: [
                 {
                   label: '$lang[HITS]',
                   fillColor: ['#f39c12', '#00a65a', '#00c0ef', '#003D4C'],
                   strokeColor: 'rgba(210, 214, 222, 1)',
                   pointColor: 'rgba(210, 214, 222, 1)',
                   pointStrokeColor: '#c1c7d1',
                   pointHighlightFill: '#fff',
                   pointHighlightStroke: 'rgba(220,220,220,1)',
                   data: [$this->i_morning, $this->i_afternoon, $this->i_evening, $this->i_night]
                 }
             ]";
             return $jsonData;
References $db, $lang, and YAWK\stats\countDaytime().
getJsonDaytimePieChart()
YAWK\stats::getJsonDaytimePieChart ($db, $daytimes, $lang)
Output JS: PIE CHART daytime data.
Parameters
object $db Database Object
array $daytime data array
array language array
Returns
string return the javascript data
Definition at line 716 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if logins are set
             if (!isset($daytimes) || (empty($daytimes)))
             {   // nope, get them from db
                 $daytimes = $this->countDaytime($db, '', $lang);
             }
             $jsonData = "[";
             foreach ($daytimes AS $daytime => $value)
             {
                 // init textcolor
                 $textcolor = '';
                 // set different colors for each status
                 if ($daytime === "$lang[MORNING]") { $textcolor = "#f39c12"; }
                 if ($daytime === "$lang[AFTERNOON]") { $textcolor = "#00a65a"; }
                 if ($daytime === "$lang[EVENING]") { $textcolor = "#00c0ef"; }
                 if ($daytime === "$lang[NIGHT]") { $textcolor = "#003D4C"; }
                 // only failed + successful logins, exclude all other values
                 if ($daytime !== ("$lang[TOTAL]") &&
                     ($daytime === ("$lang[MORNING]") ||
                         ($daytime === ("$lang[AFTERNOON]") ||
                             ($daytime === ("$lang[EVENING]") ||
                                 ($daytime === ("$lang[NIGHT]"))))))
                 {
                     $jsonData .= "
{
                                 value: $value,
                                 color: \"$textcolor\",
                                 highlight: \"$textcolor\",
                                 label: \"$daytime\"
                             },";
                 }
             }
             $jsonData .= "]";
             return $jsonData;
References $db, $lang, $value, and YAWK\stats\countDaytime().
getJsonDeviceTypes()
YAWK\stats::getJsonDeviceTypes ($db, $deviceTypes, $lang)
Output JS: BAR CHART device types.
Parameters
object $db Database Object
object $lang language
array $deviceTypes data array
Returns
string output the javascript
Definition at line 1001 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if device types are set
             if (!isset($deviceTypes) || (empty($deviceTypes)))
             {   // device types are note set - get them from db
                 $deviceTypes = $this->countDeviceTypes($db, '');
             }
             $jsonData = "labels: ['$lang[DESKTOP]', '$lang[PHONE]', '$lang[TABLET]'],
             datasets: [
                 {
                   label: 'Hits',
                   fillColor: ['#f39c12', '#00a65a', '#00c0ef'],
                   strokeColor: 'rgba(210, 214, 222, 1)',
                   pointColor: 'rgba(210, 214, 222, 1)',
                   pointStrokeColor: '#c1c7d1',
                   pointHighlightFill: '#fff',
                   pointHighlightStroke: 'rgba(220,220,220,1)',
                   data: [$this->i_desktop, $this->i_phone, $this->i_tablet]
                 }
             ]";
             return $jsonData;
References $db, and YAWK\stats\countDeviceTypes().
getJsonLogins()
YAWK\stats::getJsonLogins ($db, $logins, $lang)
Output JS: PIE CHART login data.
Parameters
object $db Database Object
object $lang language
array $logins data array
Returns
string output the javascript data
Definition at line 674 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if logins are set
             if (!isset($logins) || (empty($logins)))
             {   // nope, get them from db
                 $logins = $this->countLogins($db);
             }
             $jsonData = "[";
             foreach ($logins AS $login => $value)
             {
                 // init textcolor
                 $textcolor = '';
                 // set different colors for each status
                 if ($login === "Failed") { $textcolor = "#f56954"; }
                 if ($login === "Successful") { $textcolor = "#00a65a"; }
                 // only failed + successful logins, exclude all other values
                 if ($login !== ("Total") && ($login === ("Failed") || ($login === ("Successful"))))
                 {
                     $jsonData .= "
{
                                 value: $value,
                                 color: \"$textcolor\",
                                 highlight: \"$textcolor\",
                                 label: \"$login\"
                             },";
                 }
             }
             $jsonData .= "]";
             return $jsonData;
References $db, $value, and YAWK\stats\countLogins().
getJsonOS()
YAWK\stats::getJsonOS ($db, $oss)
Output JS: PIE CHART OS data.
Parameters
object $db Database Object
array $oss data array
Returns
string output the javascript data
Definition at line 895 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if browsers are set
             if (!isset($oss) || (empty($oss)))
             {   // nope, get them from db
                 $oss = $this->countOS($db, '');
             }
             $jsonData = "[";
             foreach ($oss AS $os => $value)
             {
                 // init textcolor
                 $textcolor = '';
                 // set different colors for each browser
                 if ($os === "Windows") { $textcolor = "#00c0ef"; }
                 if ($os === "Linux") { $textcolor = "#f56954"; }
                 if ($os === "Mac") { $textcolor = "#f39c12"; }
                 if ($os === "Android") { $textcolor = "#00a65a"; }
                 if ($os === "iOS") { $textcolor = "#000000"; }
                 if ($os === "Unknown") { $textcolor = "#cccccc"; }
                 // only browsers, not the total value
                 if ($os !== ("Total"))
                 {
                     $jsonData .= "
{
                                 value: $value,
                                 color: \"$textcolor\",
                                 highlight: \"$textcolor\",
                                 label: \"$os\"
                             },";
                 }
             }
             $jsonData .= "]";
             return $jsonData;
References $db, YAWK\stats\$os, $value, and YAWK\stats\countOS().
getJsonOSVersions()
YAWK\stats::getJsonOSVersions ($db, $osVersions)
Output JS: BAR CHART OS versions.
Parameters
object $db Database Object
array $osVersions data array
Returns
string output the javascript data
Definition at line 939 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if browsers are set
             if (!isset($osVersions) || (empty($osVersions)))
             {   // nope, get them from db
                 $osVersions = $this->countOSVersions($db, '');
             }
             $jsonData = "[";
             foreach ($osVersions AS $osVersion => $value)
             {
                 // init textcolor
                 $textcolor = '';
                 // set different colors for each OS version
                 if ($osVersion === "Windows 11") { $textcolor = "#00c0ef"; }
                 if ($osVersion === "Windows 10") { $textcolor = "#00c0ef"; }
                 if ($osVersion === "Windows 8") { $textcolor = "#00c0ef"; }
                 if ($osVersion === "Windows 7") { $textcolor = "#00A0C7"; }
                 if ($osVersion === "Windows Vista") { $textcolor = "#00B5E1"; }
                 if ($osVersion === "Windows Server") { $textcolor = "#004E61"; }
                 if ($osVersion === "Windows 2000") { $textcolor = "#005A7F"; }
                 if ($osVersion === "Windows XP") { $textcolor = "#00B5FF"; }
                 if ($osVersion === "Windows ME") { $textcolor = "#0090C9"; }
                 if ($osVersion === "Windows 98") { $textcolor = "#00A5E5"; }
                 if ($osVersion === "Windows 95") { $textcolor = "#0089BF"; }
                 if ($osVersion === "Windows 3.11") { $textcolor = "#00ACBF"; }
                 if ($osVersion === "Mac OS X") { $textcolor = "#f39c12"; }
                 if ($osVersion === "Mac OS 9") { $textcolor = "#BD7A0E"; }
                 if ($osVersion === "Linux") { $textcolor = "#f56954"; }
                 if ($osVersion === "Ubuntu") { $textcolor = "#BF5242"; }
                 if ($osVersion === "iPhone") { $textcolor = "#212121"; }
                 if ($osVersion === "iPad") { $textcolor = "#131313"; }
                 if ($osVersion === "iPod") { $textcolor = "#212121"; }
                 if ($osVersion === "Android") { $textcolor = "#6FF576"; }
                 if ($osVersion === "Blackberry") { $textcolor = "#187521"; }
                 if ($osVersion === "Mobile") { $textcolor = "#437540"; }
                 if ($osVersion === "Unknown") { $textcolor = "#6B756D"; }
                 // only browsers, not the total value
                 if ($osVersion !== ("Total"))
                 {
                     $jsonData .= "
{
                                 value: $value,
                                 color: \"$textcolor\",
                                 highlight: \"$textcolor\",
                                 label: \"$osVersion\"
                             },";
                 }
             }
             $jsonData .= "]";
             return $jsonData;
References $db, YAWK\stats\$osVersion, $value, and YAWK\stats\countOSVersions().
getJsonWeekdayBarChart()
YAWK\stats::getJsonWeekdayBarChart ($lang)
Output JS: WEEKDAY BAR CHART.
Returns
string output the javascript data
Definition at line 823 of file stats.php.
         {   /* @param $db \YAWK\db */
             $jsonData = "labels: ['$lang[MONDAY]', '$lang[TUESDAY]', '$lang[WEDNESDAY]', '$lang[THURSDAY]', '$lang[FRIDAY]', '$lang[SATURDAY]', '$lang[SUNDAY]'],
             datasets: [
                 {
                   label: 'Hits',
                   fillColor: ['#ebebeb', '#ebebeb', '#ebebeb', '#ebebeb', '#ebebeb', '#ebebeb', '#ebebeb'],
                   strokeColor: 'rgba(210, 214, 222, 1)',
                   pointColor: 'rgba(210, 214, 222, 1)',
                   pointStrokeColor: '#c1c7d1',
                   pointHighlightFill: '#fff',
                   pointHighlightStroke: 'rgba(220,220,220,1)',
                   data: [$this->i_monday, $this->i_tuesday, $this->i_wednesday, $this->i_thursday, $this->i_friday, $this->i_saturday, $this->i_sunday]
                 }
             ]";
             return $jsonData;
getLoginColors()
YAWK\stats::getLoginColors ($login)
Set and return the legend textcolor for logins (failed | success)
Parameters
string $login contains the status (Failes, Successful...) as string
Returns
string returns the textcolor for this login status as string
Definition at line 1159 of file stats.php.
         {
             switch ($login) {
                 case "Failed":
                     $textcolor = "text-red";
                     break;
                 case "FailedPercentage":
                     $textcolor = "text-red";
                     break;
                 case "SuccessPercentage":
                     $textcolor = "text-green";
                     break;
                 case "Successful":
                     $textcolor = "text-green";
                     break;
                 case "Frontend":
                     $textcolor = "text-blue";
                     break;
                 case "Backend":
                     $textcolor = "text-orange";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
getOnlineUsers()
YAWK\stats::getOnlineUsers ($db)
Return the number of all currently online users.
Parameters
object $db Database Object
Returns
int|null
Definition at line 234 of file stats.php.
         {   /* @param $db \YAWK\db */
             // first of all: delete all outdated sessions
             $this->deleteOutdatedSessions($db);
             // init count var
             $i = 0;
             // get online users from database
             if ($res = $db->query("SELECT phpSessionID FROM {users_online}"))
             {   // gogo
                 while ($row = $res->fetch_assoc())
                 {   // count entries
                     $i++;
                 }
                 $this->currentOnline = $i;
                 return $i;
             }
             else
             {
                 return null;
             }
References $db, $i, $res, and YAWK\stats\deleteOutdatedSessions().
Referenced by YAWK\stats\getStatsArray().
getOsColors()
YAWK\stats::getOsColors ($os)
Set and return the legend textcolor for each operating system.
Parameters
string $os contains the operating system as string
Returns
string returns the textcolor for this OS as string
Definition at line 1080 of file stats.php.
         {
             switch ($os) {
                 case "Windows":
                     $textcolor = "text-blue";
                     break;
                 case "Linux":
                     $textcolor = "text-red";
                     break;
                 case "Mac":
                     $textcolor = "text-orange";
                     break;
                 case "Android":
                     $textcolor = "text-green";
                     break;
                 case "Unknown":
                     $textcolor = "text-grey";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
References YAWK\stats\$os.
getOsVersionsColors()
YAWK\stats::getOsVersionsColors ($osVersions)
Set and return the legend textcolor for each OS Version.
Parameters
string $osVersions contains the operating system as string
Returns
string returns the textcolor for this os as string
Definition at line 1192 of file stats.php.
         {
             switch ($osVersions) {
                 case "Windows 10":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 8":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 7":
                     $textcolor = "text-blue";
                     break;
                 case "Windows Vista":
                     $textcolor = "text-blue";
                     break;
                 case "Windows Server":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 2000":
                     $textcolor = "text-blue";
                     break;
                 case "Windows XP":
                     $textcolor = "text-blue";
                     break;
                 case "Windows ME":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 98":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 95":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 3.11":
                     $textcolor = "text-blue";
                     break;
                 case "Windows 311":
                     $textcolor = "text-blue";
                     break;
                 case "Mac OS X":
                     $textcolor = "text-orange";
                     break;
                 case "Mac OS 9":
                     $textcolor = "text-orange";
                     break;
                 case "Linux":
                     $textcolor = "text-red";
                     break;
                 case "Ubuntu":
                     $textcolor = "text-red";
                     break;
                 case "iPhone":
                     $textcolor = "text-black";
                     break;
                 case "iPad":
                     $textcolor = "text-black";
                     break;
                 case "iPod":
                     $textcolor = "text-black";
                     break;
                 case "Android":
                     $textcolor = "text-green";
                     break;
                 case "Blackberry":
                     $textcolor = "text-green";
                     break;
                 case "Mobile":
                     $textcolor = "text-green";
                     break;
                 case "Unknown":
                     $textcolor = "text-grey";
                     break;
                 default:
                     $textcolor = "text-black";
             }
             return $textcolor;
getStatsArray()
YAWK\stats::getStatsArray ($db, $interval, $period)
Returns an array with all stats, ordered by date_created.
Parameters
object $db Database Object
string $interval The interval to get data
string $period The time period (YEAR, MONTH, DAY, HOUR, MINUTE or SECOND)
Returns
bool|array containing all stats from database
Definition at line 2025 of file stats.php.
         {
             /* @param $db \YAWK\db */
             // get online users
             $this->currentOnline = $this->getOnlineUsers($db);
             // check if period is set
             if (!isset($period) || (empty($period)))
             {   // set default to show data of the last day (last 24 hours)
                 $period = "DAY";
             }
             // check if interval is set, empty and be sure that it is an integer
             if (!isset($interval) || (empty($interval)))
             {   // if no interval is given or wrong datatype, show all data
                 $intervalQuery = '';    // leave empty in this case
             }
             // check if interval is correct int data type
             if (isset($interval) && (isset($period)))
             {   // ok. lets check it
                 switch ($interval)
                 {   // if zero
                     case 0:
                         // no additional query, leave empty
                         $intervalQuery = '';
                         break;
                     // if any other value than zero
                     default:
                         // extend the query to get data for given time period
                         $intervalQuery = "WHERE {stats}.date_created > DATE_SUB(NOW(), INTERVAL $interval $period)";
                 }
             }
             else
             {   // in any other case leave empty and get all data
                 $intervalQuery = '';
             }
             // get stats data from database feat. prepared string
             if ($res = $db->query("SELECT * FROM {stats} $intervalQuery ORDER BY date_created DESC"))
             {   // this array helds all stats data
                 $statsArray = array();
                 // gogo
                 while ($row = $res->fetch_assoc())
                 {   // fill array
                     $statsArray[] = $row;
                 }
             }
             else
             {   // q failed, set syslog and throw error
                 \YAWK\sys::setSyslog($db, 43, 1, "failed to get stats from database.", 0, 0, 0, 0);
                 \YAWK\alert::draw("warning", "Warning!", "Fetch database error: getStatsArray failed.","","4800");
                 return false;
             }
             // check if there is a stats array
             if (is_array($statsArray) && (!empty($statsArray)))
             {   // ok, go ahead with the data
                 $this->calculateStatsFromArray($db, $statsArray);
                 // and finally...
                 return $statsArray;
             }
             else
             {   // stats array is not an array or empty - in this case
                 return null;
             }
References $db, $res, YAWK\stats\calculateStatsFromArray(), YAWK\alert\draw(), and YAWK\stats\getOnlineUsers().
Referenced by YAWK\stats\calculateStatsFromArray().
getUserStats()
YAWK\stats::getUserStats ($db)
Count and set user stats like, how many users are registered, currently online or blocked.
Parameters
object $db Database Object
Returns
bool
Definition at line 538 of file stats.php.
         {   /* @param $db \YAWK\db */
             // count all users
             if ($res = $db->query("SELECT id, blocked, online, logged_in  FROM {users}"))
             {
                 while ($user = mysqli_fetch_assoc($res))
                 {
                     // add user
                     $this->i_users++;
                     // add blocked users
                     if ($user['blocked'] === "1")
                     {
                         $this->i_blockedUsers++;
                     }
                     // add current online users
                     if ($user['online'] === "1")
                     {
                         $this->i_loggedInUsers++;
                     }
                 }
                 return true;
             }
             else
             {
                 return false;
             }
References $db, and $res.
getWeekdaysPercent()
YAWK\stats::getWeekdaysPercent ($lang)
Calculate hits in percent for each weekday.
Returns
array|bool containing weekdays and number of hits in percent
Definition at line 1389 of file stats.php.
         {
             if ($this->i_totalDays > 0)
             {
                 // calculate percentage
                 $a = 100 / $this->i_totalDays;
                 $this->i_mondayPercent = round($a * $this->i_monday);
                 $this->i_tuesdayPercent = round($a * $this->i_tuesday);
                 $this->i_wednesdayPercent = round($a * $this->i_wednesday);
                 $this->i_thursdayPercent = round($a * $this->i_thursday);
                 $this->i_fridayPercent = round($a * $this->i_friday);
                 $this->i_saturdayPercent = round($a * $this->i_saturday);
                 $this->i_sundayPercent = round($a * $this->i_sunday);
                 // build an array, cointaining the device types and the number how often it's been found
                 $weekdaysPercent = array(
                     "$lang[MONDAY]" => $this->i_mondayPercent,
                     "$lang[TUESDAY]" => $this->i_tuesdayPercent,
                     "$lang[WEDNESDAY]" => $this->i_wednesdayPercent,
                     "$lang[THURSDAY]" => $this->i_thursdayPercent,
                     "$lang[FRIDAY]" => $this->i_fridayPercent,
                     "$lang[SATURDAY]" => $this->i_saturdayPercent,
                     "$lang[SUNDAY]" => $this->i_sundayPercent
                 );
                 arsort($weekdaysPercent);
                 return $weekdaysPercent;
             }
             else
             {
                 return null;
             }
References YAWK\stats\$i_totalDays.
insertData()
YAWK\stats::insertData ($db)
Insert data into database.
Parameters
object $db Database Object
Returns
bool
Definition at line 2148 of file stats.php.
         {   /* @param $db \YAWK\db */
             if ($db->query("INSERT INTO {stats}
                                     (uid,
                                      gid,
                                      logged_in,
                                      acceptLanguage,
                                      remoteAddr,
                                      userAgent,
                                      device,
                                      deviceType,
                                      os,
                                      osVersion,
                                      browser,
                                      browserVersion,
                                      date_created,
                                      referer,
                                      page)
                             VALUES ('".$this->uid."',
                                    '".$this->gid."',
                                    '".$this->logged_in."',
                                    '".$this->acceptLanguage."',
                                    '".$this->remoteAddr."',
                                    '".$this->userAgent."',
                                    '".$this->device."',
                                    '".$this->deviceType."',
                                    '".$this->os."',
                                    '".$this->osVersion."',
                                    '".$this->browser."',
                                    '".$this->browserVersion."',
                                    '".$this->date_created."',
                                    '".$this->referer."',
                                    '".$this->page."')"))
             {
                 return true;
             }
             else
             {
                 return false;
             }
References $db.
Referenced by YAWK\stats\setStats().
prepareData()
YAWK\stats::prepareData ()
Prepare data: get and collect, detect OS and device type.
Returns
null
Definition at line 390 of file stats.php.
         {
             // check if a session is set
             if (isset($_SESSION) && (!empty($_SESSION)))
             {
                 // store current session ID
                 $this->phpSessionID = session_id();
                 // store current timestamp (will be used for users online counter)
                 $this->currentTimeStamp=time();
                 // prepare all session user data
                 if (isset($_SESSION['uid']) && (!empty($_SESSION['uid'])))
                 {   // user id (if logged in)
                     $this->uid = $_SESSION['uid'];
                 }
                 if (isset($_SESSION['gid']) && (!empty($_SESSION['gid'])))
                 {   // user group id (if logged in)
                     $this->gid = $_SESSION['gid'];
                 }
                 if (isset($_SESSION['logged_in']) && (!empty($_SESSION['logged_in'])))
                 {   // user group id (if logged in)
                     $this->logged_in = $_SESSION['logged_in'];
                 }
             }
             else
             {   // no session is set
                 // user is a guest - or obviously not logged in
                 $this->uid = 0;
                 $this->gid = 0;
                 $this->logged_in = 0;
             }
             // user IP address
             $this->remoteAddr = $_SERVER['REMOTE_ADDR'];
             // user client username
             // $this->remoteUser = $_SERVER['REMOTE_HOST'];
             // user agent information
             $this->userAgent = $_SERVER['HTTP_USER_AGENT'];
             // user browser
             // Include and instantiate the class.
             require_once 'system/engines/mobiledetect/Mobile_Detect.php';
             $detect = new \YAWK\Mobile_Detect();
             $this->deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'Tablet' : 'Phone') : 'Desktop');
             // Any mobile device (phones or tablets).
             if ( $detect->isMobile() ) {
                 // $this->deviceType = "Mobile";
                 $browser = array();
                 $browser = \YAWK\sys::getBrowser($this->userAgent);
                 $this->browser = $browser['name'];
                 $this->browserVersion = $browser['version'];
             }
             // Any tablet device.
             if( $detect->isTablet() ){
                 // $this->deviceType = "Tablet";
                 $browser = array();
                 $browser = \YAWK\sys::getBrowser($this->userAgent);
                 $this->browser = $browser['name'];
                 $this->browserVersion = $browser['version'];
             }
             // No Mobile, no tablet - must be a computer
             if( !$detect->isMobile() && !$detect->isTablet() ){
                 // $this->deviceType = "Computer";
                 $browser = array();
                 $browser = \YAWK\sys::getBrowser($this->userAgent);
                 $this->browser = $browser['name'];
                 $this->browserVersion = $browser['version'];
                 $this->os = ucfirst($browser['platform']);
                 $this->osVersion = \YAWK\sys::getOS($this->userAgent);
             }
             // detect wheter its a phone, pad or pod
             if ( $detect->version('iPhone') ) {
                 $this->device = "iPhone";
                 $this->os = "iOS";
                 $this->osVersion = $detect->version('iPhone');
             }
             if ( $detect->version('iPad') ) {
                 $this->device = "iPad";
                 $this->os = "iOS";
                 $this->osVersion = $detect->version('iPad');
             }
             if ( $detect->version('iPod') ) {
                 $this->device = "iPod";
                 $this->os = "iOS";
                 $this->osVersion = $detect->version('iPod');
             }
             if( $detect->version('Android') ){
                 $this->os = "Android";
                 $this->osVersion = $detect->version('Android');
             }
             // set remote user
             $this->acceptLanguage = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
             // the referer page from which the user came
             if (!isset($_SERVER['HTTP_REFERER']) || (empty($_SERVER['HTTP_REFERER'])))
             {   // empty referer
                 $this->referer = '';
             }
             else
             {   // set referer
                 $this->referer = $_SERVER['HTTP_REFERER'];
             }
             // check if include (page request) is set
             if (!isset($_GET['include']) || (empty($_GET['include'])))
             {   // if no page is set, take server variable
                 $this->page = $_SERVER['REQUEST_URI'];
             }
             else
             {   // set requested page
                 $this->page = $_GET['include'];
             }
             // current datetime
             $this->date_created = \YAWK\sys::now();
             return null;
References $_GET, YAWK\stats\$browser, browser, YAWK\sys\getBrowser(), YAWK\sys\getOS(), gid, and YAWK\sys\now().
Referenced by YAWK\stats\setStats().
setOnlineUsers()
YAWK\stats::setOnlineUsers ($db)
Set users online in database (stores and check sessions and timestamps)
Parameters
object $db Database Object
Returns
null
Definition at line 284 of file stats.php.
         {   /* @param $db \YAWK\db */
             // how long
             $this->phpSessionID = session_id();
             $this->currentTimeStamp = time();
             if (!isset($_SESSION['uid']) || (empty($_SESSION['uid'])))
             { $this->uid = 0; }
             else
             { $this->uid = $_SESSION['uid']; }
             // check, if phpSessionID and currentTimeStamp is set
             if (isset($this->phpSessionID) && (isset($this->currentTimeStamp)))
             {
                 // check, if this phpSessionID is already in database
                 if ($row = $db->query("SELECT * from {users_online}
                                                 WHERE phpSessionID = '$this->phpSessionID'"))
                 {
                     // fetch data from users_online
                     if ($res = $row->fetch_assoc())
                     {
                         // create currentTimeStamp
                         $this->currentTimeStamp = time();
                         // user is still online, update currentTimeStamp for this phpSessionID
                         if ($row = $db->query("UPDATE {users_online}
                                                         SET currentTimeStamp = '$this->currentTimeStamp'
                                                         WHERE phpSessionID = '$this->phpSessionID'"))
{
                             // user updated
                         }
                         else
{
                             // could not update user status
                             // todo: add syslog entry
                         }
                     }
                     else
                     {   // failed to fetch data, add new phpSessionID and currentTimeStamp
                         if ($db->query("INSERT INTO {users_online}
                                     (phpSessionID,
                                      uid,
                                      currentTimeStamp)
                             VALUES ('".$this->phpSessionID."',
                                     '".$this->uid."',
                                    '".$this->currentTimeStamp."')"))
{
                             // all good
                         }
                         else
                         {   // insert failed
                             // todo: add syslog entry
                         }
                     }
                 }
                 else
                 {   // failed to fetch data, add new phpSessionID and currentTimeStamp
                     if ($db->query("INSERT INTO {users_online}
                                     (phpSessionID,
                                      currentTimeStamp)
                             VALUES ('".$this->phpSessionID."',
                                    '".$this->currentTimeStamp."')"))
                     {
                         // all good
                     }
                     else
                     {   // insert failed
                         // todo: add syslog entry
                     }
                 }
             }
             else
             {
                 // session ID or currentTimeStamp are not set
                 // todo: add syslog entry
             }
             return true;
References $db, and $res.
Referenced by YAWK\stats\setStats().
setStats()
YAWK\stats::setStats ($db)
Insert statistics data into database.
Parameters
object $db Database Object
Returns
null
Definition at line 368 of file stats.php.
         {   /* @param $db \YAWK\db */
             // check if stats are enabled
             if (\YAWK\settings::getSetting($db, "statsEnable") == 1)
             {   // prepare user information that we can easily collect
                 $this->prepareData();
                 // set online users
                 $this->setOnlineUsers($db);
                 // insert statistics into database
                 if ($this->insertData($db) === false)
                 {   // insert stats failed, add syslog entry
                     \YAWK\sys::setSyslog($db, 43, 1, "could not insert stats into database.", "", "", "","");
                 }
             }
             return null;
References $db, YAWK\settings\getSetting(), YAWK\stats\insertData(), YAWK\stats\prepareData(), and YAWK\stats\setOnlineUsers().
Member Data Documentation
$acceptLanguage
YAWK\stats::$acceptLanguage
Parameters
string detected user language
Definition at line 26 of file stats.php.
$activeSessions
YAWK\stats::$activeSessions
Parameters
string the currently open sessions (active users)
Definition at line 50 of file stats.php.
$browser
YAWK\stats::$browser
Parameters
string detected users browser
Definition at line 40 of file stats.php.
Referenced by YAWK\stats\countBrowsers(), YAWK\stats\getBrowserColors(), YAWK\stats\getJsonBrowsers(), and YAWK\stats\prepareData().
$browserVersion
YAWK\stats::$browserVersion
Parameters
string detected users browser version
Definition at line 42 of file stats.php.
$currentOnline
YAWK\stats::$currentOnline = 0
Parameters
int currentOnline how many users are currently online
Definition at line 22 of file stats.php.
$currentTimeStamp
YAWK\stats::$currentTimeStamp
Parameters
string currentTimeStamp current time stamp
Definition at line 20 of file stats.php.
$date_created
YAWK\stats::$date_created
Parameters
string datetime when entry was created
Definition at line 44 of file stats.php.
$device
YAWK\stats::$device
Parameters
string detected device (eg. iPhone, iPad, iPod)
Definition at line 32 of file stats.php.
$deviceType
YAWK\stats::$deviceType
Parameters
string detected device type (desktop, phone, tablet)
Definition at line 34 of file stats.php.
Referenced by YAWK\stats\countDeviceTypes(), and YAWK\stats\getDeviceTypeColors().
$gid
YAWK\stats::$gid = 0
Parameters
int gid (group id) who affected this entry
Definition at line 16 of file stats.php.
$i_afternoon
YAWK\stats::$i_afternoon = 0
Parameters
int number of hits in the afternoon
Definition at line 176 of file stats.php.
$i_afternoonPercent
YAWK\stats::$i_afternoonPercent = 0
Parameters
int number of hits in the afternoon (in percent)
Definition at line 184 of file stats.php.
$i_android
YAWK\stats::$i_android = 0
Parameters
int how many users came with android?
Definition at line 126 of file stats.php.
$i_blackberry
YAWK\stats::$i_blackberry = 0
Parameters
int how many users came with blackberry?
Definition at line 128 of file stats.php.
$i_blockedUsers
YAWK\stats::$i_blockedUsers = 0
*
Parameters
int total blocked users
Definition at line 70 of file stats.php.
$i_desktop
YAWK\stats::$i_desktop = 0
Parameters
int how many users came with desktop systems?
Definition at line 136 of file stats.php.
Referenced by YAWK\stats\countDeviceTypes().
$i_desktopPercent
YAWK\stats::$i_desktopPercent = 0
Parameters
int how many users came with desktopdevices (in percent) ?
Definition at line 138 of file stats.php.
$i_evening
YAWK\stats::$i_evening = 0
Parameters
int number of hits in the evening
Definition at line 178 of file stats.php.
$i_eveningPercent
YAWK\stats::$i_eveningPercent = 0
Parameters
int number of hits in the evening (in percent)
Definition at line 186 of file stats.php.
$i_friday
YAWK\stats::$i_friday = 0
Parameters
int number of hits on friday
Definition at line 200 of file stats.php.
$i_fridayPercent
YAWK\stats::$i_fridayPercent = 0
Parameters
int number of hits on friday (in percent)
Definition at line 217 of file stats.php.
$i_hits
YAWK\stats::$i_hits = 0
Parameters
int total hits overall
Definition at line 54 of file stats.php.
Referenced by YAWK\stats\calculateStatsFromArray().
$i_iOS
YAWK\stats::$i_iOS = 0
Parameters
int how many users came with iOS?
Definition at line 82 of file stats.php.
$i_iPad
YAWK\stats::$i_iPad = 0
Parameters
int how many users came with iPad?
Definition at line 124 of file stats.php.
$i_iPhone
YAWK\stats::$i_iPhone = 0
Parameters
int how many users came with iPhone?
Definition at line 120 of file stats.php.
$i_iPod
YAWK\stats::$i_iPod = 0
Parameters
int how many users came with iPod?
Definition at line 122 of file stats.php.
$i_linux
YAWK\stats::$i_linux = 0
Parameters
int how many users came with linux?
Definition at line 116 of file stats.php.
$i_loggedInUsers
YAWK\stats::$i_loggedInUsers = 0
*
Parameters
int total logged in users
Definition at line 68 of file stats.php.
$i_loggedUsers
YAWK\stats::$i_loggedUsers = 0
Parameters
int how many logins were successful?
Definition at line 56 of file stats.php.
$i_loggedUsersPercentage
YAWK\stats::$i_loggedUsersPercentage = 0
Parameters
int how many logins were successful? (in percent)
Definition at line 58 of file stats.php.
$i_loginBackend
YAWK\stats::$i_loginBackend = 0
Parameters
int how many logins were made to backend?
Definition at line 158 of file stats.php.
$i_loginBackendFailed
YAWK\stats::$i_loginBackendFailed = 0
Parameters
int how many backend logins failed?
Definition at line 162 of file stats.php.
$i_loginBackendSuccess
YAWK\stats::$i_loginBackendSuccess = 0
Parameters
int how many backend logins were successful?
Definition at line 160 of file stats.php.
$i_loginFailed
YAWK\stats::$i_loginFailed = 0
Parameters
int how many logins failed?
Definition at line 154 of file stats.php.
Referenced by YAWK\stats\countLogins().
$i_loginFailedPercentage
YAWK\stats::$i_loginFailedPercentage = 0
Parameters
int how many logins failed? (in percent)
Definition at line 170 of file stats.php.
$i_loginFrontend
YAWK\stats::$i_loginFrontend = 0
Parameters
int how many logins were made to frontend?
Definition at line 156 of file stats.php.
$i_loginFrontendFailed
YAWK\stats::$i_loginFrontendFailed = 0
Parameters
int how many frontend logins failed?
Definition at line 166 of file stats.php.
$i_loginFrontendSuccess
YAWK\stats::$i_loginFrontendSuccess = 0
Parameters
int how many frontend logins were successful?
Definition at line 164 of file stats.php.
$i_loginSuccessful
YAWK\stats::$i_loginSuccessful = 0
Parameters
int how many logins were successful?
Definition at line 152 of file stats.php.
Referenced by YAWK\stats\countLogins().
$i_loginSuccessPercentage
YAWK\stats::$i_loginSuccessPercentage = 0
Parameters
int how many logins were successful? (in percent)
Definition at line 168 of file stats.php.
$i_macos9
YAWK\stats::$i_macos9 = 0
Parameters
int how many users came with mac os 9?
Definition at line 114 of file stats.php.
$i_macosX
YAWK\stats::$i_macosX = 0
Parameters
int how many users came with mac os x?
Definition at line 112 of file stats.php.
$i_mobile
YAWK\stats::$i_mobile = 0
Parameters
int how many users came with unknown mobile system?
Definition at line 130 of file stats.php.
$i_monday
YAWK\stats::$i_monday = 0
Parameters
int number of hits on monday
Definition at line 192 of file stats.php.
$i_mondayPercent
YAWK\stats::$i_mondayPercent = 0
Parameters
int number of hits on monday (in percent)
Definition at line 209 of file stats.php.
$i_morning
YAWK\stats::$i_morning = 0
Parameters
int number of hits in the morningtime
Definition at line 174 of file stats.php.
$i_morningPercent
YAWK\stats::$i_morningPercent = 0
Parameters
int number of hits in the morningtime (in percent)
Definition at line 182 of file stats.php.
$i_night
YAWK\stats::$i_night = 0
Parameters
int number of hits in the night
Definition at line 180 of file stats.php.
Referenced by YAWK\stats\countDaytime(), and YAWK\stats\getDayTimesPercent().
$i_nightPercent
YAWK\stats::$i_nightPercent = 0
Parameters
int number of hits in the night (in percent)
Definition at line 188 of file stats.php.
$i_osAndroid
YAWK\stats::$i_osAndroid = 0
Parameters
int how many users came with android?
Definition at line 80 of file stats.php.
$i_osLinux
YAWK\stats::$i_osLinux = 0
Parameters
int how many users came with linux?
Definition at line 78 of file stats.php.
$i_osMac
YAWK\stats::$i_osMac = 0
Parameters
int how many users came with macOS?
Definition at line 76 of file stats.php.
$i_osUnknown
YAWK\stats::$i_osUnknown = 0
Parameters
int how many operating systems were unable to detect?
Definition at line 84 of file stats.php.
Referenced by YAWK\stats\countOS().
$i_osWindows
YAWK\stats::$i_osWindows = 0
Parameters
int how many users came with windows?
Definition at line 74 of file stats.php.
$i_others
YAWK\stats::$i_others = 0
Parameters
int how many users came with other systems?
Definition at line 132 of file stats.php.
Referenced by YAWK\stats\countOSVersions().
$i_phone
YAWK\stats::$i_phone = 0
Parameters
int how many users came with mobile devices?
Definition at line 144 of file stats.php.
Referenced by YAWK\stats\countDeviceTypes().
$i_phonePercent
YAWK\stats::$i_phonePercent = 0
Parameters
int how many users came with mobile devices (in percent) ?
Definition at line 146 of file stats.php.
$i_publicUsers
YAWK\stats::$i_publicUsers = 0
Parameters
int how many users did not log in and visited as public guest?
Definition at line 60 of file stats.php.
$i_publicUsersPercentage
YAWK\stats::$i_publicUsersPercentage = 0
Parameters
int how many users did not log in and visited as public guest? (in percent)
Definition at line 62 of file stats.php.
$i_saturday
YAWK\stats::$i_saturday = 0
Parameters
int number of hits on saturday
Definition at line 202 of file stats.php.
$i_saturdayPercent
YAWK\stats::$i_saturdayPercent = 0
Parameters
int number of hits on saturday (in percent)
Definition at line 219 of file stats.php.
$i_sunday
YAWK\stats::$i_sunday = 0
Parameters
int number of hits on sunday
Definition at line 204 of file stats.php.
Referenced by YAWK\stats\countWeekdays().
$i_sundayPercent
YAWK\stats::$i_sundayPercent = 0
Parameters
int number of hits on sunday (in percent)
Definition at line 221 of file stats.php.
$i_tablet
YAWK\stats::$i_tablet = 0
Parameters
int how many users came with tablet devices?
Definition at line 140 of file stats.php.
Referenced by YAWK\stats\countDeviceTypes().
$i_tabletPercent
YAWK\stats::$i_tabletPercent = 0
Parameters
int how many users came with tablet devices (in percent) ?
Definition at line 142 of file stats.php.
$i_thursday
YAWK\stats::$i_thursday = 0
Parameters
int number of hits on thursday
Definition at line 198 of file stats.php.
$i_thursdayPercent
YAWK\stats::$i_thursdayPercent = 0
Parameters
int number of hits on thursday (in percent)
Definition at line 215 of file stats.php.
$i_totalDays
YAWK\stats::$i_totalDays = 0
Parameters
int number of hits on all days (sum)
Definition at line 206 of file stats.php.
Referenced by YAWK\stats\getWeekdaysPercent().
$i_totalLogins
YAWK\stats::$i_totalLogins = 0
Parameters
int how logins were totally made?
Definition at line 150 of file stats.php.
Referenced by YAWK\stats\countLogins().
$i_tuesday
YAWK\stats::$i_tuesday = 0
Parameters
int number of hits on tuesday
Definition at line 194 of file stats.php.
$i_tuesdayPercent
YAWK\stats::$i_tuesdayPercent = 0
Parameters
int number of hits on tuesday (in percent)
Definition at line 211 of file stats.php.
$i_ubuntu
YAWK\stats::$i_ubuntu = 0
Parameters
int how many users came with ubuntu?
Definition at line 118 of file stats.php.
$i_users
YAWK\stats::$i_users = 0
*
Parameters
int total users overall
Definition at line 66 of file stats.php.
$i_wednesday
YAWK\stats::$i_wednesday = 0
Parameters
int number of hits on wednesday
Definition at line 196 of file stats.php.
$i_wednesdayPercent
YAWK\stats::$i_wednesdayPercent = 0
Parameters
int number of hits on wednesday (in percent)
Definition at line 213 of file stats.php.
$i_windows10
YAWK\stats::$i_windows10 = 0
Parameters
int how many users came with windows10?
Definition at line 90 of file stats.php.
$i_windows11
YAWK\stats::$i_windows11 = 0
Parameters
int how many users came with windows11?
Definition at line 88 of file stats.php.
$i_windows2000
YAWK\stats::$i_windows2000 = 0
Parameters
int how many users came with windows 2000?
Definition at line 102 of file stats.php.
$i_windows311
YAWK\stats::$i_windows311 = 0
Parameters
int how many users came with windows 3.11?
Definition at line 110 of file stats.php.
$i_windows7
YAWK\stats::$i_windows7 = 0
Parameters
int how many users came with windows7?
Definition at line 94 of file stats.php.
$i_windows8
YAWK\stats::$i_windows8 = 0
Parameters
int how many users came with windows8?
Definition at line 92 of file stats.php.
$i_windows95
YAWK\stats::$i_windows95 = 0
Parameters
int how many users came with windows 95?
Definition at line 108 of file stats.php.
$i_windows98
YAWK\stats::$i_windows98 = 0
Parameters
int how many users came with windows 98?
Definition at line 106 of file stats.php.
$i_windowsME
YAWK\stats::$i_windowsME = 0
Parameters
int how many users came with windows me?
Definition at line 104 of file stats.php.
$i_windowsServer
YAWK\stats::$i_windowsServer = 0
Parameters
int how many users came with windows server?
Definition at line 98 of file stats.php.
$i_windowsVista
YAWK\stats::$i_windowsVista = 0
Parameters
int how many users came with windows vista?
Definition at line 96 of file stats.php.
$i_windowsXP
YAWK\stats::$i_windowsXP = 0
Parameters
int how many users came with windows xp?
Definition at line 100 of file stats.php.
$id
YAWK\stats::$id
Parameters
int id for every entry
Definition at line 12 of file stats.php.
$logged_in
YAWK\stats::$logged_in = 0
Parameters
int 0|1 was the user logged in?
Definition at line 24 of file stats.php.
$os
YAWK\stats::$os
Parameters
string detected users operating system
Definition at line 36 of file stats.php.
Referenced by YAWK\stats\countOS(), YAWK\stats\getJsonOS(), and YAWK\stats\getOsColors().
$osVersion
YAWK\stats::$osVersion
Parameters
string detected users operating system version
Definition at line 38 of file stats.php.
Referenced by YAWK\stats\countOSVersions(), and YAWK\stats\getJsonOSVersions().
$page
YAWK\stats::$page
Parameters
string page that the user requested
Definition at line 48 of file stats.php.
Referenced by YAWK\stats\drawPagesBox().
$phpSessionID
YAWK\stats::$phpSessionID
Parameters
int phpSessionID current php session ID
Definition at line 18 of file stats.php.
$referer
YAWK\stats::$referer
Parameters
string users url referer string
Definition at line 46 of file stats.php.
$remoteAddr
YAWK\stats::$remoteAddr
Parameters
string IP address who affected this entry
Definition at line 28 of file stats.php.
$uid
YAWK\stats::$uid = 0
Parameters
int uid (user id) who affected this entry
Definition at line 14 of file stats.php.
$userAgent
YAWK\stats::$userAgent
Parameters
string complete useragent info
Definition at line 30 of file stats.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/stats.php