YaWK: Ifsnop\Mysqldump\TypeAdapterFactory Class Reference
Ifsnop\Mysqldump\TypeAdapterFactory Class Reference
Public Member Functions
__construct ($dbHandler=null, $dumpSettings=array())
add_drop_database ()
add_drop_trigger ()
backup_parameters ()
commit_transaction ()
create_procedure ($procedureName)
create_table ($row)
create_trigger ($triggerName)
create_view ($row)
databases ()
drop_table ()
drop_view ()
end_add_disable_keys ()
end_add_lock_table ()
end_disable_foreign_keys_check ()
lock_table ()
parseColumnType ($colType)
restore_parameters ()
setup_transaction ()
show_columns ()
show_create_table ($tableName)
show_create_trigger ($triggerName)
show_create_view ($viewName)
show_events ()
show_procedures ()
show_tables ()
show_triggers ()
show_views ()
start_add_disable_keys ()
start_add_lock_table ()
start_disable_foreign_keys_check ()
start_transaction ()
unlock_table ()
Static Public Member Functions
static create ($c, $dbHandler=null, $dumpSettings=array())
Protected Attributes
$dbHandler = null
$dumpSettings = array()
Detailed Description
TypeAdapter Factory
Definition at line 1328 of file Mysqldump.php.
Constructor & Destructor Documentation
__construct()
Ifsnop\Mysqldump\TypeAdapterFactory::__construct ($dbHandler = null, $dumpSettings = array())
Definition at line 1347 of file Mysqldump.php.
     {
         $this->dbHandler = $dbHandler;
         $this->dumpSettings = $dumpSettings;
     }
References Ifsnop\Mysqldump\TypeAdapterFactory\$dbHandler, and Ifsnop\Mysqldump\TypeAdapterFactory\$dumpSettings.
Member Function Documentation
add_drop_database()
Ifsnop\Mysqldump\TypeAdapterFactory::add_drop_database ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1512 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
add_drop_trigger()
Ifsnop\Mysqldump\TypeAdapterFactory::add_drop_trigger ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1517 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
backup_parameters()
Ifsnop\Mysqldump\TypeAdapterFactory::backup_parameters ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1544 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
commit_transaction()
Ifsnop\Mysqldump\TypeAdapterFactory::commit_transaction ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1467 of file Mysqldump.php.
     {
         return "COMMIT";
     }
create()
static Ifsnop\Mysqldump\TypeAdapterFactory::create ($c, $dbHandler = null, $dumpSettings = array()) static
Parameters
string $c Type of database factory to create (Mysql, Sqlite,...)
PDO $dbHandler
Definition at line 1337 of file Mysqldump.php.
     {
         $c = ucfirst(strtolower($c));
         if (!TypeAdapter::isValid($c)) {
             throw new Exception("Database type support for ($c) not yet available");
         }
         $method = __NAMESPACE__."\\"."TypeAdapter".$c;
         return new $method($dbHandler, $dumpSettings);
     }
References Ifsnop\Mysqldump\TypeAdapterFactory\$dbHandler, Ifsnop\Mysqldump\TypeAdapterFactory\$dumpSettings, and Ifsnop\Mysqldump\TypeAdapter\isValid().
Referenced by Ifsnop\Mysqldump\Mysqldump\connect().
create_procedure()
Ifsnop\Mysqldump\TypeAdapterFactory::create_procedure ($procedureName)
function create_procedure Modify procedure code, add delimiters, etc
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1416 of file Mysqldump.php.
     {
         return "";
     }
create_table()
Ifsnop\Mysqldump\TypeAdapterFactory::create_table ($row)
function create_table Get table creation code from database
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1373 of file Mysqldump.php.
     {
         return "";
     }
create_trigger()
Ifsnop\Mysqldump\TypeAdapterFactory::create_trigger ($triggerName)
function create_trigger Modify trigger code, add delimiters, etc
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1407 of file Mysqldump.php.
     {
         return "";
     }
create_view()
Ifsnop\Mysqldump\TypeAdapterFactory::create_view ($row)
function create_view Get view creation code from database
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1389 of file Mysqldump.php.
     {
         return "";
     }
databases()
Ifsnop\Mysqldump\TypeAdapterFactory::databases ()
function databases Add sql to create and use database
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1357 of file Mysqldump.php.
     {
         return "";
     }
drop_table()
Ifsnop\Mysqldump\TypeAdapterFactory::drop_table ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1522 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
drop_view()
Ifsnop\Mysqldump\TypeAdapterFactory::drop_view ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1527 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
end_add_disable_keys()
Ifsnop\Mysqldump\TypeAdapterFactory::end_add_disable_keys ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1497 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
end_add_lock_table()
Ifsnop\Mysqldump\TypeAdapterFactory::end_add_lock_table ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1487 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
end_disable_foreign_keys_check()
Ifsnop\Mysqldump\TypeAdapterFactory::end_disable_foreign_keys_check ()
Definition at line 1507 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
lock_table()
Ifsnop\Mysqldump\TypeAdapterFactory::lock_table ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1472 of file Mysqldump.php.
     {
         return "";
     }
parseColumnType()
Ifsnop\Mysqldump\TypeAdapterFactory::parseColumnType ($colType)
Decode column metadata and fill info structure. type, is_numeric and is_blob will always be available.
Parameters
array $colType Array returned from "SHOW COLUMNS FROM tableName"
Returns
array
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1539 of file Mysqldump.php.
     {
         return array();
     }
restore_parameters()
Ifsnop\Mysqldump\TypeAdapterFactory::restore_parameters ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1549 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
setup_transaction()
Ifsnop\Mysqldump\TypeAdapterFactory::setup_transaction ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1457 of file Mysqldump.php.
     {
         return "";
     }
show_columns()
Ifsnop\Mysqldump\TypeAdapterFactory::show_columns ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1436 of file Mysqldump.php.
     {
         if (func_num_args() != 1) {
             return "";
         }
         $args = func_get_args();
         return "pragma table_info(${args[0]})";
     }
show_create_table()
Ifsnop\Mysqldump\TypeAdapterFactory::show_create_table ($tableName)
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1362 of file Mysqldump.php.
     {
         return "SELECT tbl_name as 'Table', sql as 'Create Table' ".
             "FROM sqlite_master ".
             "WHERE type='table' AND tbl_name='$tableName'";
     }
show_create_trigger()
Ifsnop\Mysqldump\TypeAdapterFactory::show_create_trigger ($triggerName)
function show_create_trigger Get trigger creation code from database
Todo:
make it do something with sqlite
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1398 of file Mysqldump.php.
     {
         return "";
     }
show_create_view()
Ifsnop\Mysqldump\TypeAdapterFactory::show_create_view ($viewName)
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1378 of file Mysqldump.php.
     {
         return "SELECT tbl_name as 'View', sql as 'Create View' ".
             "FROM sqlite_master ".
             "WHERE type='view' AND tbl_name='$viewName'";
     }
show_events()
Ifsnop\Mysqldump\TypeAdapterFactory::show_events ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1452 of file Mysqldump.php.
     {
         return "";
     }
show_procedures()
Ifsnop\Mysqldump\TypeAdapterFactory::show_procedures ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1447 of file Mysqldump.php.
     {
         return "";
     }
show_tables()
Ifsnop\Mysqldump\TypeAdapterFactory::show_tables ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1421 of file Mysqldump.php.
     {
         return "SELECT tbl_name FROM sqlite_master WHERE type='table'";
     }
show_triggers()
Ifsnop\Mysqldump\TypeAdapterFactory::show_triggers ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1431 of file Mysqldump.php.
     {
         return "SELECT name FROM sqlite_master WHERE type='trigger'";
     }
show_views()
Ifsnop\Mysqldump\TypeAdapterFactory::show_views ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1426 of file Mysqldump.php.
     {
         return "SELECT tbl_name FROM sqlite_master WHERE type='view'";
     }
start_add_disable_keys()
Ifsnop\Mysqldump\TypeAdapterFactory::start_add_disable_keys ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1492 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
start_add_lock_table()
Ifsnop\Mysqldump\TypeAdapterFactory::start_add_lock_table ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1482 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
start_disable_foreign_keys_check()
Ifsnop\Mysqldump\TypeAdapterFactory::start_disable_foreign_keys_check ()
Definition at line 1502 of file Mysqldump.php.
     {
         return PHP_EOL;
     }
start_transaction()
Ifsnop\Mysqldump\TypeAdapterFactory::start_transaction ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1462 of file Mysqldump.php.
     {
         return "BEGIN EXCLUSIVE";
     }
unlock_table()
Ifsnop\Mysqldump\TypeAdapterFactory::unlock_table ()
Reimplemented in Ifsnop\Mysqldump\TypeAdapterMysql.
Definition at line 1477 of file Mysqldump.php.
     {
         return "";
     }
Member Data Documentation
$dbHandler
Ifsnop\Mysqldump\TypeAdapterFactory::$dbHandler = null protected
Definition at line 1330 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\TypeAdapterFactory\__construct(), and Ifsnop\Mysqldump\TypeAdapterFactory\create().
$dumpSettings
Ifsnop\Mysqldump\TypeAdapterFactory::$dumpSettings = array() protected
Definition at line 1331 of file Mysqldump.php.
Referenced by Ifsnop\Mysqldump\TypeAdapterFactory\__construct(), and Ifsnop\Mysqldump\TypeAdapterFactory\create().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/mysqldump/Mysqldump.php