YaWK: YAWK\alert Class Reference
YAWK\alert Class Reference
Throws a fancy Bootstrap Alert (success, info, warning or danger)
Static Public Member Functions
static draw ($type, $title, $text, $redirect, $delay)
Detailed Description
Throws a fancy Bootstrap Alert (success, info, warning or danger)
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl www.yawk.io @license https://opensource.org/licenses/MIT
Throw default bootstrap-powered alerts. (warning, succes etc...) This lets you throw an alert message box at any time, anywhere in your script. Alert uses 5 Arguments, as shown below. Example: any place of your script where an error, info, success or danger Message needs to be thrown.
Class covers both, backend & frontend functionality. See Methods Summary for Details!
Definition at line 18 of file alert.php.
Member Function Documentation
draw()
static YAWK\alert::draw ($type, $title, $text, $redirect, $delay) static
Definition at line 30 of file alert.php.
         {
             // default animation when alert pops in
             $animatedEnter = "animated fadeInDown";
             // default animation when alert pops out
             $animatedExit = "animated fadeOutUp";
             // default placementFrom (top, bottom)
             $placementFrom = "top";
             // default placementFrom (left, center, right)
             $placementAlign = "center";
             // any URL to link to
             $url = "";
             // URL target
             $urlTarget = "_blank";
             // should it be allowed to dismiss this alert?
             $allowDismiss = "true";
             // display newest on top if there are more simultaneous alerts?
             $newestOnTop = "false";
             // display a progressbar to show how long the alert will stay
             $progressBar = "false";
             // offest X axis
             $offsetX = "10";
             // offest Y axis
             $offsetY = "62";
             // spacing
             $spacing = "10";
             // z-index
             $zIndex = "9999";
             // icon
             $icon = "fa fa-info-circle";
             if (!isset($type) || (empty($type)))
             {
                 $type = "info";
             }
             if (!isset($title) || (empty($title)))
             {
                 $title = "";
             }
             if (!isset($text) || (empty($text)))
             {
                 $text = "";
             }
             if (!isset($redirect) || (empty($redirect)))
             {
                 $redirect = "";
             }
             if (!isset($delay) || (empty($delay)))
             {
                 $delay = 0;
             }
             if (empty($type)) { $type="danger"; }
             if (empty($title)) { $title="ERROR!"; }
             if (empty($text)) { $text="Something strange has happened. Text is empty. Sorry that there is no more Information available. (Code 0)"; }
             if (empty($redirect)) { $redirect="null"; }
             if (empty($delay)) { $delay="null"; }
             if ($redirect === "null" && ($delay !== "null"))
             {
                 $n_delay = $delay;
             }
             else {
                 // calculate delay time for notify before redirect
                 $n_delay = $delay;
                 if (is_int($n_delay)){
                     $n_delay = $n_delay / 3;
                     $n_delay = round($n_delay);
                 }
             }
             if ($delay === "null")
             {
                 $n_delay = "null";
             }
             // switch icon
             switch ($type)
             {
                 case "danger":
                     $icon = "fa fa-exclamation-triangle";
                     break;
                 case "warning":
                     $icon = "fa fa-flash";
                     break;
                 case "success":
                     $icon = "fa fa-check-circle-o";
                     break;
                 case "tipofday":
                     $icon = "fa fa-lightbulb-o";
                     $type = "success";
                     $animatedEnter = "animated fadeInRight";
                     $animatedExit = "animated fadeOutRight";
                     $placementFrom = "top";
                     $placementAlign = "right";
                     break;
                 default:
                     $icon = "fa fa-info-circle";
                     break;
             }
             // run notify javascript
             echo "
   <script type=\"text/javascript\">
     $.notify({
         // options
         title: '<h4><i class=\"$icon\"></i>&nbsp; $title</h4>',
         message: '$text',
         url: '$url',
         target: '$urlTarget'
     }, {
         // settings
         type: '$type',
         element: 'body',
         position: null,
         allow_dismiss: '$allowDismiss',
         newest_on_top: '$newestOnTop',
         showProgressbar: $progressBar,
         placement: {
             from: '$placementFrom',
             align: '$placementAlign'
         },
         offset: {
             x: $offsetX,
             y: $offsetY
         },
         spacing: $spacing,
         z_index: $zIndex,
         delay: '$n_delay',
         timer: 420,
         url_target: '$urlTarget',
         mouse_over: 'pause',
         animate: {
             enter: '$animatedEnter',
             exit: '$animatedExit'
         }
     });
   </script>";
             if ($redirect !== "null" && ($delay !== "null"))
             {
                 // redirect after notify with given delay param
                 return \YAWK\sys::setTimeout("index.php?$redirect", $delay);
             }
             else
             {
                 return null;
             }
         } // ./draw
References $offsetX, $offsetY, $redirect, $type, and $url.
Referenced by YAWK\page\copy(), YAWK\stats\countLogins(), YAWK\page\create(), YAWK\page\delete(), YAWK\template\deleteSettingsCSSFile(), YAWK\BACKEND\AdminLTE\drawHtmlContent(), YAWK\tipOfDay\drawTip(), YAWK\settings\getAllSettingsArray(), YAWK\settings\getEditorSettings(), YAWK\sys\getGroupFromId(), YAWK\sys\getGroupId(), YAWK\user\getLoginData(), YAWK\settings\getLongSetting(), YAWK\page\getMetaTags(), YAWK\page\getProperty(), YAWK\settings\getSettingDescription(), YAWK\stats\getStatsArray(), YAWK\settings\getValueSettingsArray(), YAWK\settings\getWidgetSetting(), YAWK\sys\isBrowscapSet(), YAWK\page\save(), YAWK\user\sendResetEmail(), YAWK\settings\setLongSetting(), YAWK\settings\setSetting(), YAWK\settings\setTemplateSetting(), YAWK\settings\setWidgetSetting(), YAWK\installer\step2(), YAWK\installer\step3(), YAWK\installer\step4(), YAWK\installer\step5(), YAWK\menu\toggleItemOffline(), YAWK\page\toggleLock(), YAWK\page\toggleOffline(), and YAWK\settings\toggleOffline().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/alert.php