YaWK: YAWK\WIDGETS\CLOCK\CURRENT\clock Class Reference
YAWK\WIDGETS\CLOCK\CURRENT\clock Class Reference
Embed a digital real-time clock on your website.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
drawClock ()
Draw the clock on screen.
init ()
Initialize: prepare JS and start the clock.
loadJavascript ()
Load required javascript.
printObject ()
Print all object data.
Public Attributes
$clockAlign = 'text-center'
$clockClass = 'h1'
$clockColor = '#f5f5f5'
$widget = ''
Detailed Description
Embed a digital real-time clock on your website.
Embed a digital clock on your website.
The clock shows the current time. (wonder, oh wonder...) You can set the clock's font color, alignment (left, center or right) as well as a custom css class to design it and put some FX on if you need to. If you need an analog clock anywhere on your website, this widget does the job.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 16 of file clock.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\CLOCK\CURRENT\clock::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 32 of file clock.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawClock()
YAWK\WIDGETS\CLOCK\CURRENT\clock::drawClock ()
Draw the clock on screen.
This method draws the clock on screen
Definition at line 93 of file clock.php.
         {
             echo"
             <div class=\"$this->clockAlign\">
                 <div id=\"clockDiv\" class=\"$this->clockClass\" style=\"color:#$this->clockColor\"></div>
             </div>";
Referenced by YAWK\WIDGETS\CLOCK\CURRENT\clock\init().
init()
YAWK\WIDGETS\CLOCK\CURRENT\clock::init ()
Initialize: prepare JS and start the clock.
use this method to run the clock
Definition at line 57 of file clock.php.
         {
             $this->loadJavascript();
             $this->drawClock();
References YAWK\WIDGETS\CLOCK\CURRENT\clock\drawClock(), and YAWK\WIDGETS\CLOCK\CURRENT\clock\loadJavascript().
loadJavascript()
YAWK\WIDGETS\CLOCK\CURRENT\clock::loadJavascript ()
Load required javascript.
The engine behind this clock
Definition at line 67 of file clock.php.
         {
             echo"<body onload=\"clock();\">
             <script type=\"text/javascript\">
             function clock() {
                 var now = new Date();
                 var minute = now.getMinutes();
                 var second= now.getSeconds();
                 var hour = now.getHours();
                 if(minute<10) minute = \"0\" + minute;
                 if(second<10) second= \"0\" + second;
                 if(hour<10) hour=\"0\" + hour;
                 var outStr = hour+':'+minute+':'+second;
                 /*   output string without leading zero int
                  *   var outStr = now.getHours()+':'+now.getMinutes()+':'+now.getSeconds(); */
                 document.getElementById('clockDiv').innerHTML=outStr;
                 setTimeout('clock()',1000);
             }
             clock();
             </script>";
Referenced by YAWK\WIDGETS\CLOCK\CURRENT\clock\init().
printObject()
YAWK\WIDGETS\CLOCK\CURRENT\clock::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 46 of file clock.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
Member Data Documentation
$clockAlign
YAWK\WIDGETS\CLOCK\CURRENT\clock::$clockAlign = 'text-center'
Parameters
string Clock alignment
Definition at line 23 of file clock.php.
$clockClass
YAWK\WIDGETS\CLOCK\CURRENT\clock::$clockClass = 'h1'
Parameters
string Clock class
Definition at line 25 of file clock.php.
$clockColor
YAWK\WIDGETS\CLOCK\CURRENT\clock::$clockColor = '#f5f5f5'
Parameters
string Clock color
Definition at line 21 of file clock.php.
$widget
YAWK\WIDGETS\CLOCK\CURRENT\clock::$widget = ''
Parameters
object global widget object data
Definition at line 19 of file clock.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/clock/classes/clock.php