YaWK: YAWK\page Class Reference
YAWK\page Class Reference
The default pages class. Provide all functions to handle static pages.
Public Member Functions
copy ($db)
make a copy of a page
create ($db, $alias, $menuID, $locked, $blogid, $plugin)
create a new page
delete ($db)
delete a page
deleteContent ($dirprefix)
delete a static content page
getContent ($db, $lang)
get and include static page content
getCurrentLanguageByID ($db, $id)
getProperty ($db, $id, $property)
get any requested page property
loadProperties ($db, $alias)
load page properties and store as object properties
loadPropertiesByID ($db, $id)
load page properties and store as object properties
readContent ($dirPrefix)
read content from static page
save ($db)
save a static page including all settings
toggleLock ($db, $id, $locked)
toggle page lock to avoid unintended changes
toggleOffline ($db, $id, $published, $title)
toggle page status online or offline (plus corresponding menu entries)
writeContent ($content)
write content to static page
Static Public Member Functions
static countPages ($db)
count and return the pages in database
static getLatest ($db, $limit)
get latest pages
static getMetaTags ($db, $id, $type)
get and return meta tags for requested page
static getMetaTagsArray ($db, $id)
get and return meta tags of requested page as array
Public Attributes
$alias = ''
$alias_new = ''
$bgimage
$blogid
$date_created
$date_publish
$date_unpublish
$gid
$id = -1
$language
$locked
$menu = -1
$meta_keywords = "Meta Tag Keywords"
$meta_local = "Meta Tag Description"
$metadescription
$metakeywords
$newLanguage
$ownerid = -1
$path = "../content/pages/"
$plugin
$published = 0
$searchstring
$title = ''
$title_new = ''
Detailed Description
The default pages class. Provide all functions to handle static pages.
The default pages class. Provide all functions to handle static html pages.
All functions that are required to handle a page. Methods are: create, save, edit, delete and many more.
Class covers both, backend & frontend functionality. See Methods Summary for Details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 19 of file page.php.
Member Function Documentation
copy()
YAWK\page::copy ($db)
make a copy of a page
Parameters
object $db database
Returns
bool
Parameters
$db db
Definition at line 265 of file page.php.
         {
             /** @param $db db */
             // creation date
             $currentDateTime = date("Y-m-d G:i:s");
             // init helper vars for copy processing
             $page = '';
             $newPage = '';
             // if page name is not given
             if (!$this->alias) {
                 return false;
             }
             // ## select max id from pages
             if ($res = $db->query("SELECT MAX(id) FROM {pages}"))
             {
                 $row = mysqli_fetch_row($res);
                 $this->id = $row[0] + 1;
             }
             else
             {
                 sys::setSyslog($db, 7, 1, "could not fetch MAX(id) of pages database", 0, 0, 0, 0);
                 die ("Sorry, database error: could not fetch MAX(id).");
             }
             $this->id++;
             // ## add new page to db pages
             if ($result = $db->query("INSERT INTO {pages} (id,gid,date_created,date_publish,alias,title,blogid,locked,lang,meta_local,meta_keywords,plugin)
                                    VALUES ('" . $this->id . "',
                                            '" . $this->gid . "',
                                            '" . $currentDateTime . "',
                                            '" . $currentDateTime . "',
                                            '" . $this->alias.'-copy'."',
                                            '" . $this->title .'-copy'."',
                                            '" . $this->blogid . "',
                                            '" . $this->locked . "',
                                            '" . $this->language . "',
                                            '" . $this->meta_local . "',
                                            '" . $this->meta_keywords . "',
                                            '" . $this->plugin . "')"))
             {
                 /* TODO: COPY META TAGS when COPY PAGE
                 // generate local meta tags
                 $desc = "description";
                 $keyw = "keywords";
                 $words = "";
                 // add local meta tags
                 if (!$db->query("INSERT INTO {meta_local} (name,page,content)
                                           VALUES ('" . $desc . "', '" . $id . "', '" . $title . "')"))
                 {
                     \YAWK\sys::setSyslog($db, 8, 1, "failed to store local meta tags", 0, 0, 0, 0);
                     echo \YAWK\alert::draw("warning","Warning", "Could not store local meta tags", "", "");
                 }
                 // add local meta tags to db meta_local
                 if (!$db->query("INSERT INTO {meta_local} (name,page,content)
                         VALUES ('" . $keyw . "','" . $id . "','" . $words . "')"))
                 {
                     \YAWK\sys::setSyslog($db, 8, 1, "failed to store local meta tags", 0, 0, 0, 0);
                     echo \YAWK\alert::draw("warning","Warning", "Could not store local meta tags", "", "");
                 }
                 */
                 // copy page as new language requested
                 if ($this->newLanguage === true)
                 {   // check, if requested language dir exists
                     if (!is_dir($this->path.$this->language))
                     {   // if not, try to create it
                         mkdir($this->path.$this->language);
                         // prepare files to get copied into new language sub folder
                         $page = $this->path.$this->alias.".php";
                         $newPage = $this->path.$this->language."/".$this->alias."-copy.php";
                     }
                 }
                 else
                 {   // prepare files to get copied into content/pages/ root folder
                     $page = $this->path.$this->alias.".php";
                     $newPage = $this->path.$this->alias."-copy.php";
                 }
                 // copy file
                 if (!copy($page, $newPage) && !chmod($newPage, 0777))
                 {
                     sys::setSyslog($db, 8, 1, "copy failed: $page to $newPage", 0, 0, 0, 0);
                     print alert::draw("danger", "Error!", "File could not be copied. Check folder permissions of /content/pages !", "", "");
                 }
                 else {
                     // file copies successfully...
                     return true;
                 }
                 /*
                 // ## selectmenuID from menu db
                 if ($row = $db->query("SELECT menuID FROM {menu} WHERE title LIKE '" . $this->title . "'"))
                 {
                     $res = mysqli_fetch_row($row);
                     if (isset($res[0])){
                         $menuID = $res[0];
                     }
                     else {
                         $menuID = 0;
                     }
                 }
                 else
                 {   // select failed, throw error
                     sys::setSyslog($db, 23, 1, "failed to select menu entry for $this->title", 0, 0, 0, 0);
                     echo alert::draw("warning","Warning", "Could not select menu entry for: $this->title", "", "");
                     $menuID = '0';
                 }
                 // ## select max ID from menu
                 if ($row = $db->query("SELECT MAX(id) FROM {menu}"))
                 {
                     $res = mysqli_fetch_row($row);
                     if (!isset($res[0]))
                     { // if not, give it a ID of 1
                         $newMenuID = 1;
                     }
                     else
                     {   // if entry exists, add +1 to ID #
                         $newMenuID = $res[0]++;
                     }
                 }
                 else
                 {
                     $newMenuID = 0;
                     // select MAX(id) from menu failed, throw error
                     sys::setSyslog($db, 23, 1, "failed to fetch MAX(id) from menu", 0, 0, 0, 0);
                     echo alert::draw("warning","Warning", "Could not fetch MAX(id) from menu", "", "");
                 }
                 // to increment sort var correctly, check if there is an entry in the menu
                 if ($res = $db->query("SELECT MAX(sort) FROM {menu} WHERE menuID = '" . $menuID . "'"))
                 {
                     $row = mysqli_fetch_row($res);
                     if (!isset($row[0]))
                     {   // if not, give it a sort ID of 1
                         $sort = 1;
                     }
                     else
                     {   // if entry exists, add +1 to sort #
                         $sort = $row[0]++;
                     }
                     $link = "$this->alias" . ".html";
                     if ($db->query("INSERT INTO {menu} (id,sort,menuID,text,href)
                           VALUES('" . $newMenuID . "','" . $sort . "', '" . $menuID . "', '" . $this->title_new . "', '" . $link . "')"))
                     {
                         sys::setSyslog($db, 21, 0, "menu entry $this->title_new added", 0, 0, 0, 0);
                         return true;
                     }
                     else
                     {
                         // insert failed, throw error
                         sys::setSyslog($db, 23, 1, "failed to insert menu entry for: $this->title_new", 0, 0, 0, 0);
                         echo alert::draw("warning","Warning", "Could not insert menu entry for: $this->title_new", "", "");
                     }
                 }
                 else
                 {
                     // select failed, throw error
                     sys::setSyslog($db, 23, 1, "failed to select menu entry for: $menuID", 0, 0, 0, 0);
                     echo alert::draw("warning","Warning", "Could not select menu entry for: $menuID", "", "");
                 }
                     */
             }
             else
             {
                 sys::setSyslog($db, 7, 1, "could not insert data into pages table", 0, 0, 0, 0);
             }
             sys::setSyslog($db, 8, 1, "copy $this->path.$this->alias failed.", 0, 0, 0, 0);
             return false;
         }
References $db, $page, $res, $result, alias, date, die, and YAWK\alert\draw().
countPages()
static YAWK\page::countPages ($db) static
count and return the pages in database
Parameters
object $db database
Returns
int|bool
Parameters
$db db
Definition at line 75 of file page.php.
         {   /** @param $db db */
             if ($result = $db->query('SELECT count(id) FROM {pages}'))
             {
                 $i = mysqli_fetch_row($result);
                 return $i[0];
             }
             else
             {
                 return false;
             }
         }
References $db, $i, and $result.
create()
YAWK\page::create ($db, $alias, $menuID, $locked, $blogid, $plugin)
create a new page
Parameters
object $db database
string $alias page filename
int $menuID menu ID
int $locked 0|1 page lock status
int $blogid blog ID, if any
int $plugin plugin ID, if any
Returns
bool
Parameters
$db db
Definition at line 511 of file page.php.
         {
             // TODO: refactor this method to oop code
             $this->alias = $alias;
             $this->menu = $menuID;
             $this->locked = $locked;
             $this->blogid = $blogid;
             $this->plugin = $plugin;
             /** @param $db db */
             // init variables
             // if page name is not given
             if (!$alias) {
                 return false;
             }
             $alias = html_entity_decode($alias);
             // creation date
             $date_created = date("Y-m-d G:i:s");
 //            $date_unpublish = date('Y-m-d', strtotime('+25 year', strtotime($date_created)) );
 //            $date_unpublish = NULL;
             $title = $alias;
             /* alias string manipulation */
             $alias = mb_strtolower($alias); // lowercase
             $alias = str_replace(" ", "-", $alias); // replace all ' ' with -
             // special chars
             $ersetze = array("//", "//", "//", "//", "//", "//", "//"); // array of special chars
             $umlaute = array("ae", "ue", "oe", "Ae", "Ue", "Oe", "ss"); // array of replacement chars
             $alias = preg_replace($ersetze, $umlaute, $alias);      // replace with preg
             // convert special chars
             $alias = sys::encodeChars($alias);
             // final check: just numbers and chars are allowed
             $alias = preg_replace("/[^a-z0-9\-\/]/i", "", $alias);
             // final filename
             $link = "$alias" . ".html";
             // if menu select field is not empty
             if ($menuID !== "empty") {
                 // ## select max ID from menu + add menu entry
                 if ($res = $db->query("SELECT MAX(id) FROM {menu}"))
                 {
                     $row = mysqli_fetch_row($res);
                     if (!isset($row[0])) { // if not, give it a ID of 1
                         $id = 1;
                     } else {
                         $id = $row[0] + 1; // if entry exists, add +1 to ID #
                     }
                 }
                 else
                 {   // throw error
                     $id = 1;
                     sys::setSyslog($db, 7, 1, "failed to fetch MAX(id) FROM {menu}", 0, 0, 0, 0);
                     alert::draw("danger","Error:", "Could not fetch MAX(id) FROM {menu}", "page=page-new", "4300");
                 }
                 // to increment sort var correctly, check if there is an entry in the menu
                 if ($res = $db->query("SELECT MAX(sort) FROM {menu} WHERE menuID = '" . $menuID . "'"))
                 {
                     $row = mysqli_fetch_row($res);
                     if (!isset($row[0]))
                     {   // if not, give it a ID of 1
                         $sort = 1;
                     }
                     else
                     {   // if entry exists, add +1 to sort #
                         $sort = $row[0] + 1;
                     }
                 }
                 else
                 {   // throw error
                     $sort = 1;
                     sys::setSyslog($db, 7, 1, "failed to fetch MAX(id) FROM {menu} WHERE menuID = $menuID", 0, 0, 0, 0);
                     alert::draw("danger","Error:", "Could not fetch MAX(id) FROM {menu} WHERE menuID = $menuID", "page=page-new", "4300");
                 }
                 if ($plugin) {
                     if (strlen($plugin) >= 1) {
                         $menu_published = 1;
                     }
                     else {
                         $menu_published = 0;
                     }
                 }
                 else {
                     $menu_published = 0;
                 }
                 $title = htmlentities($title);
                 $tmpID = 0;
                 $titleText = '';
                 // insert menu data
                 if (!$res = $db->query("INSERT INTO {menu} (id,sort,menuID,published,title,text,href,blogid, menuLanguage)
                                        VALUES('" . $id . "',
                                               '" . $sort . "',
                                               '" . $menuID . "',
                                               '" . $menu_published . "',
                                             '" . $titleText . "',
                                               '" . $title . "',
                                               '" . $link . "',
                                               '" . $blogid . "',
                                               '" . $this->language . "')"))
                 {   // throw error
                     sys::setSyslog($db, 23, 1, "failed to insert data into {menu}", 0, 0, 0, 0);
                     alert::draw("danger", "Error:", "could not insert menu data", "page=page-new", "4300");
                 }
                 else
                 {   // success syslog entry
                     sys::setSyslog($db, 21, 0, "added new menu: $title (id: $id)", 0, 0, 0, 0);
                 }
             } // ./ if menu != empty
             // if the method is called from the blog, set settings
             if ($locked === '0' && $blogid === '0') {
                 $locked = 0;
                 $published = 0;
                 $content = "leer";
             } else {
                 $published = 0;
                 $content = "<?php \$blog_id = $blogid; include 'system/plugins/blog/blog.php'; ?>";
             }
             // if the method is called from the plugin, set settings
             if ($plugin) {
                 if (is_array($plugin)){
                     $plugin = array("tos", $_POST['signup_tospage'], $_POST['signup_terms-long']);
                     if ($plugin[0] === 'tos'){
                         $published = 1;
                         $locked = 1;
                         $alias = "$plugin[1]";
                         $content = "$plugin[2]";
                         $plugin = "signup";
                     }
                 }
                 else if (strlen($plugin) >= 1) {
                     $published = 1;
                     $locked = 1;
                     $content = "<?php include 'system/plugins/$plugin/$plugin.php'; ?>";
                 }
             }
             else {
                 $plugin = 0;
             }
             // ## select max id from pages
             if ($res = $db->query("SELECT MAX(id) FROM {pages}"))
             {
                 $row = mysqli_fetch_row($res);
                 $id = $row[0] + 1;
             }
             else
             {
                 $id = 1;
                 sys::setSyslog($db, 7, 1, "failed to select MAX(id) from pages db", 0, 0, 0, 0);
             }
             $alias = htmlentities($alias);
             // ## add new page to db pages
             if (!$db->query("INSERT INTO {pages} (id,published,date_created,date_changed,date_publish,date_unpublish,alias,title,locked,blogid,plugin,lang)
                                    VALUES ('" . $id . "',
                                            '" . $published . "',
                                            '" . $date_created . "',
                                            '" . $date_created . "',
                                            '" . $date_created . "',
                                            NULL,
                                            '" . $alias . "',
                                            '" . $title . "',
                                            '" . $locked . "',
                                            '" . $blogid . "',
                                            '".$plugin."',
                                            '".$this->language."')"))
             {   // error inserting page into database - throw error
                 sys::setSyslog($db, 7, 2, "unable to add page $alias into database.", 0, 0, 0, 0);
                 alert::draw("danger", "Error!", "unable to add new page ($alias) id: $id into pages database.", "", 4300);
             }
             // check if language is set
             if (isset($this->language) && (!empty($this->language)))
             {   // set path for new language page
                 $filename = $this->path.$this->language."/".$alias.".php";
                 if (!is_dir($this->path.$this->language)){
                     if (!mkdir($this->path.$this->language)){
                         sys::setSyslog($db, 7, 2, "failed to create language folder: $this->path.$this->language");
                         return false;
                     }
                 }
             }
             else
             {   // set path for root dir
                 $filename = $this->path.$alias.".php";
             }
             // create file
             if (!file_exists($filename)) {
                 $handle = fopen($filename, "wr");
                 fwrite($handle, $content);
                 fclose($handle);
                 chmod($filename, 0777);
             }
             // page created successfully
             sys::setSyslog($db, 5, 0, "created $filename", 0, 0, 0, 0);
             return true;
         }
References YAWK\page\$alias, YAWK\page\$blogid, $content, YAWK\page\$date_created, $db, $filename, YAWK\page\$id, YAWK\page\$locked, YAWK\page\$plugin, YAWK\page\$published, $res, YAWK\page\$title, alias, blogid, date, YAWK\alert\draw(), and YAWK\sys\encodeChars().
delete()
YAWK\page::delete ($db)
delete a page
Parameters
object $db database
Returns
bool
Parameters
$db db
Definition at line 449 of file page.php.
         {
             /** @param $db db */
             // delete item from pages db
             if (!$db->query("DELETE FROM {pages} WHERE id = '" . $this->id . "'")) {
                 sys::setSyslog($db, 7, 1, "failed to delete page $this->alias from database", 0, 0, 0, 0);
                 alert::draw("danger", "Error:", "could not delete page from database", "pages", "4300");
             }
             else
             {   // page deleted
                 sys::setSyslog($db, 5, 0, "deleted page $this->alias from database", 0, 0, 0, 0);
             }
             // delete item from menu db
             if (!$db->query("DELETE FROM {menu} WHERE href = '" . $this->alias . ".html'")) {
                 sys::setSyslog($db, 23, 1, "failed to delete menu entry of page $this->alias from database", 0, 0, 0, 0);
                 alert::draw("danger", "Error:", "could not delete menu entry from database", "pages", "4300");
             }
             else
             {   // deleted menu syslog entry
                 sys::setSyslog($db, 21, 0, "deleted menu of ../content/pages/$this->alias.php", 0, 0, 0, 0);
             }
             // check, if language is set and build path + filename
             if (isset($this->language) && (!empty($this->language)))
             {   // file should be in corresponding language folder
                 $filename = $this->path.$this->language."/".$this->alias.".php";
             }
             else
             {   // file should be in pages root folder
                 $filename = $this->path.$this->alias.".php";
             }
             // check if file exists
             if (file_exists($filename))
             {   // delete file
                 if (!unlink($filename))
                 {   // delete failed
                     sys::setSyslog($db, 8, 2, "unable to delete $filename", 0, 0, 0, 0);
                     alert::draw("danger", "Error:", "could not delete file from /content/ folder", "pages", "4300");
                     return false;
                 }
                 else
                 {   // delete successful
                     sys::setSyslog($db, 5, 0, "deleted $filename", 0, 0, 0, 0);
                     return true;
                 }
             }
             // file does not exist.
             sys::setSyslog($db, 7, 1, "file $filename does not exist. page->delete() failed", 0, 0, 0, 0);
             return false;
         }
References $db, $filename, alias, and YAWK\alert\draw().
deleteContent()
YAWK\page::deleteContent ($dirprefix)
delete a static content page
Parameters
string $dirprefix directory prefix
Definition at line 819 of file page.php.
         {
             global $dirprefix;
             if (isset($this->language) && (!empty($this->language)))
             {
                 $filename = $dirprefix.$this->path.$this->language."/".$this->alias.".php";
             }
             else
             {
                 $filename = $dirprefix.$this->path.$this->alias."php";
             }
             if (file_exists($filename))
             {
                 if (unlink($filename))
                 {
                     return true;
                 }
                 else
                 {
                     return false;
                 }
             }
             else
             {
                 return true;
             }
         }
References $dirprefix, $filename, and alias.
getContent()
YAWK\page::getContent ($db, $lang)
get and include static page content
Parameters
object $db database
object $lang language obj
Returns
mixed
@noinspection PhpIncludeInspection
@noinspection PhpIncludeInspection
@noinspection PhpIncludeInspection
@noinspection PhpIncludeInspection
Definition at line 1116 of file page.php.
References $_GET, $db, $lang, YAWK\page\$language, $now, YAWK\page\$path, date, die, exit, YAWK\controller\filterfilename(), and YAWK\settings\getSetting().
getCurrentLanguageByID()
YAWK\page::getCurrentLanguageByID ($db, $id)
Parameters
$db db $res
Definition at line 929 of file page.php.
{
             /** @param $db db $res */
             if (isset($id) && (!empty($id)))
             {   // query db for given page ID
                 $res = $db->query("SELECT lang FROM {pages} WHERE id ='".$id."'");
                 $currentLanguage = mysqli_fetch_row($res);
             }
             // check, if page got a language set
             if (isset($currentLanguage[0]) && (!empty($currentLanguage[0])))
             {   // return page language
                 return $currentLanguage[0];
             }
             else
             {   // no language set, return empty string
                 return "";
             }
         }
References $db, YAWK\page\$id, and $res.
getLatest()
static YAWK\page::getLatest ($db, $limit) static
get latest pages
Parameters
object $db database
int $limit limit to n entries
Returns
array|string
Parameters
$db db
Definition at line 1058 of file page.php.
         {   /** @param $db db */
             // check and set default value
             if (!isset($limit) && (empty($limit))) { $limit = 4; }
             // select latest n page titles
             if ($res = $db->query("SELECT id, alias, title, published, date_publish
                                    FROM {pages}
                                    WHERE blogid = 0
                                    AND plugin = 0
                                    ORDER BY date_created
                                    DESC LIMIT $limit"))
             {
                 $latestPages = array();
                 while ($row = mysqli_fetch_assoc($res))
                 {
                     $latestPages[] = $row;
                 }
                 return $latestPages;
             }
             else
             {
                 return "no pages found.";
             }
         }
References $db, and $res.
Referenced by YAWK\BACKEND\dashboard\drawLatestPagesBox().
getMetaTags()
static YAWK\page::getMetaTags ($db, $id, $type) static
get and return meta tags for requested page
Parameters
object $db database
int $id affected page ID
string $type meta description
Returns
string|bool meta tags as string
Parameters
$db db $res
Definition at line 95 of file page.php.
         {   /** @param $db db $res */
             if ($row = $db->query("SELECT meta_local, meta_keywords
                                   FROM {pages}
                                   WHERE id = '".$id."'"))
             {   // output meta content description
                 $res = $row->fetch_assoc();
                 if (!empty($type))
                 {
                     if ($type == "meta_local"){
                         if (!empty($res['meta_local'])){
                             return $res['meta_local'];
                         }
                         else {
                             return null;
                         }
                     }
                     else if ($type == "meta_keywords"){
                         if (!empty($res['meta_keywords'])){
                             return $res['meta_keywords'];
                         }
                         else {
                             return null;
                         }
                     }
                     else {
                         return null;
                     }
                 }
             }
             else {
                 // throw alert
                 sys::setSyslog($db, 7, 1, "failed to fetch meta $type for page ID $id", 0, 0, 0, 0);
                 return alert::draw("warning", "Warning", "Could not fetch meta $type for page ID $id", "",4200);
             }
             // q failed
             return false;
         }
References $db, $res, $type, and YAWK\alert\draw().
getMetaTagsArray()
static YAWK\page::getMetaTagsArray ($db, $id) static
get and return meta tags of requested page as array
Parameters
object $db database
int $id affected page ID
string $type meta description
Returns
array|bool meta tags as array
Parameters
$db db $res
Definition at line 141 of file page.php.
         {   /** @param $db db $res */
             if ($row = $db->query("SELECT meta_local, meta_keywords
                                   FROM {pages}
                                   WHERE id = '".$id."'"))
             {   // output meta content description
                 $res = $row->fetch_assoc();
                 if (is_array($res)
                     && (!empty($res['meta_local'])
                         && (!empty($res['meta_keywords'])))){
                     return $res;
                 }
                 else {
                     // meta tags not set, get global meta tags
                     $res['meta_local'] = \YAWK\settings::getSetting($db, "globalmetatext");
                     $res['meta_keywords'] = \YAWK\settings::getSetting($db, "globalmetakeywords");
                     if (!empty($res['meta_local']) && (!empty($res['meta_keywords']))){
                         return $res;
                     }
                     else {
                         $res['meta_local'] = "Unable to get Meta Description for this page. Neither local or global meta description found.";
                         $res['meta_keywords'] = "Unable to get Meta Keywords for this page. Neither local or global meta keywords found.";
                         return $res;
                     }
                 }
             }
             else {
                 // throw alert
                 sys::setSyslog($db, 7, 1, "failed to fetch meta tags for page ID $id", 0, 0, 0, 0);
                 $res['meta_local'] = "Unable to get Meta Description for this page. Neither local or global meta description found.";
                 $res['meta_keywords'] = "Unable to get Meta Keywords for this page. Neither local or global meta keywords found.";
                 return $res;
             }
         }
References $db, $res, and YAWK\settings\getSetting().
getProperty()
YAWK\page::getProperty ($db, $id, $property)
get any requested page property
Parameters
object $db database
int $id affected page ID
string $property database field to get
Returns
string|bool the selected property or false
Parameters
$db db $res
Definition at line 1090 of file page.php.
         {   /** @param $db db $res */
             // select property from pages db
             if ($res = $db->query("SELECT $property FROM {pages}
                         WHERE id = '" . $id . "'"))
             {   // fetch data
                 if ($row = mysqli_fetch_row($res)){
                     return $row[0];
                 }
             }
             else
             {   // throw error
                 sys::setSyslog($db, 7, 1, "unable to get property: $property from pages database.", 0, 0, 0, 0);
                 alert::draw("warning", "Warning", "unable to get property: $property from Paged Database.", "", "4200");
                 return false;
             }
             // q failed
             return null;
         }
References $db, YAWK\page\$id, $res, and YAWK\alert\draw().
loadProperties()
YAWK\page::loadProperties ($db, $alias)
load page properties and store as object properties
Parameters
object $db database
string $alias page filename
Parameters
$db db $res
Definition at line 952 of file page.php.
         {
             /** @param $db db $res */
             if (isset($alias) && (!empty($alias)))
             {
                 $res = $db->query("SELECT * FROM {pages} WHERE alias = '".$alias."'");
                 if ($row = mysqli_fetch_assoc($res))
                 {
                     $this->id = $row['id'];
                     $this->date_created = $row['date_created'];
                     $this->date_publish = $row['date_publish'];
                     $this->date_unpublish = $row['date_unpublish'];
                     $this->published = $row['published'];
                     $this->gid = $row['gid'];
                     $this->title = $row['title'];
                     $this->ownerid = $row['owner'];
                     $this->menu = $row['menu'];
                     $this->bgimage = $row['bgimage'];
                     $this->locked = $row['locked'];
                     $this->blogid = $row['blogid'];
                     $this->plugin = $row['plugin'];
                     $this->language = $row['lang'];
                     $this->meta_local = $row['meta_local'];
                     $this->meta_keywords = $row['meta_keywords'];
                     $this->alias = $alias;
                 }
                 else
                 {   // 404 error handling
                     if ($this->alias == "content/errors/404")
                     {   // check if user is logged in (session uid is set in that case)
                         if (isset($_SESSION['uid']) && (!empty($_SESSION['uid'])))
                         {   // logged in user created a 404 error
                             sys::setSyslog($db, 7, 2, "404: file not found - displayed $alias instead", $_SESSION['uid'], 0, 0, 0);
                         }
                         else
                         {   // user is not logged in - unknown user created a 404 error
                             sys::setSyslog($db, 7, 2, "404: file not found - displayed $alias instead", 0, 0, 0, 0);
                         }
                     }
                 }
             }
             else
             {   // page not set - unable to load page properties
                 sys::setSyslog($db, 7, 2, "failed to load properties because page alias was not set", 0, 0, 0, 0);
             }
         }
References YAWK\page\$alias, $db, $res, alias, bgimage, blogid, date_publish, date_unpublish, gid, meta_keywords, meta_local, published, and title.
loadPropertiesByID()
YAWK\page::loadPropertiesByID ($db, $id)
load page properties and store as object properties
Parameters
object $db database
string $id page id
Parameters
$db db $res
Definition at line 1004 of file page.php.
         {
             /** @param $db db $res */
             if (isset($id) && (!empty($id)))
             {
                 $res = $db->query("SELECT * FROM {pages} WHERE id = '".$id."'");
                 if ($row = mysqli_fetch_assoc($res))
                 {
                     $this->id = $row['id'];
                     $this->date_created = $row['date_created'];
                     $this->date_publish = $row['date_publish'];
                     $this->date_unpublish = $row['date_unpublish'];
                     $this->published = $row['published'];
                     $this->gid = $row['gid'];
                     $this->alias = $row['alias'];
                     $this->title = $row['title'];
                     $this->ownerid = $row['owner'];
                     $this->menu = $row['menu'];
                     $this->bgimage = $row['bgimage'];
                     $this->locked = $row['locked'];
                     $this->blogid = $row['blogid'];
                     $this->plugin = $row['plugin'];
                     $this->language = $row['lang'];
                     $this->meta_local = $row['meta_local'];
                     $this->meta_keywords = $row['meta_keywords'];
                 }
                 else
                 {   // 404 error handling
                     if ($this->alias == "content/errors/404")
                     {   // check if user is logged in (session uid is set in that case)
                         if (isset($_SESSION['uid']) && (!empty($_SESSION['uid'])))
                         {   // logged in user created a 404 error
                             sys::setSyslog($db, 7, 2, "404: file not found - displayed $this->alias instead", $_SESSION['uid'], 0, 0, 0);
                         }
                         else
                         {   // user is not logged in - unknown user created a 404 error
                             sys::setSyslog($db, 7, 2, "404: file not found - displayed $this->alias instead", 0, 0, 0, 0);
                         }
                     }
                 }
             }
             else
             {   // page ID not set - unable to load page properties
                 sys::setSyslog($db, 7, 2, "failed to load properties because page ID was not set", 0, 0, 0, 0);
             }
         }
References $db, YAWK\page\$id, $res, alias, bgimage, blogid, date_publish, date_unpublish, gid, meta_keywords, meta_local, published, and title.
readContent()
YAWK\page::readContent ($dirPrefix)
read content from static page
Parameters
string $dirPrefix directory prefix
Returns
string html content
Definition at line 901 of file page.php.
                                         : string
         {
             // check, if language is set
             if (isset($this->language) && (!empty($this->language)))
             {   // if so, build path including language folder
                 $filename = $this->path.$this->language."/".$this->alias.".php";
             }
             else
             {   // no language set, build path for content/pages root folder
                 $filename = $this->path.$this->alias.".php";
             }
             if(file_exists($filename)){
                 // open page file
                 $handle = @fopen($filename, "rw");
                 // read content into var
                 $content = @fread($handle, filesize($filename));
                 // close resource
                 fclose($handle);
                 // and return page content
                 return $content;
             }
             else
             {
                 return 'ERROR: Unable to read content of file: '.$filename.'
 Maybe the file has been physically deleted, moved or renamed.';
             }
         }
References $content, $filename, and alias.
save()
YAWK\page::save ($db)
save a static page including all settings
Parameters
object $db database
Returns
bool
Parameters
$db db
Definition at line 718 of file page.php.
         {
             /** @param $db db */
             $date_changed = date("Y-m-d G:i:s");
             /* alias string manipulation */
             $this->alias = mb_strtolower($this->alias); // lowercase
             $this->alias = str_replace(" ", "-", $this->alias); // replace all ' ' with -
             // special chars
             $umlaute = array("//", "//", "//", "//", "//", "//", "//"); // array of special chars
             $ersetze = array("ae", "ue", "oe", "ae", "ue", "oe", "ss"); // array of replacement chars
             $this->alias = preg_replace($umlaute, $ersetze, $this->alias);        // replace with preg
             $this->alias = preg_replace("/[^a-z0-9\-\/]/i", "", $this->alias); // final check: just numbers and chars are allowed
             // old alias string
             $oldAlias = substr($this->searchstring, 0, -5);  // remove last 5 chars (.html) to get the plain filename
             // update menu entry
             /*
             if (!$db->query("UPDATE {menu}
                   SET text = '" . $this->title ."',
                       href = '" . $this->alias . ".html',
                        gid = '" . $this->gid . "',
                       published = '" . $this->published . "'
                 WHERE href = '" . $this->searchstring . "'"))
             {
                 // throw error
                 \YAWK\sys::setSyslog($db, 23, 1, "failed to update menu entry $this->title.", 0, 0, 0, 0);
                 \YAWK\alert::draw("warning", "Warning", "menu entry could not be stored in database.", "", 6200);
             }
             */
             // update page db
             // check unpublish date
             if ($this->date_unpublish == "0000-00-00 00:00:00" || (empty($this->date_unpublish) || $this->date_unpublish == NULL))
             {
                 // sql code with NULL unpublish date
                 if (!$db->query("UPDATE {pages}
                     SET published = '" . $this->published . "',
                         gid = '" . $this->gid . "',
                         date_changed = '" . $date_changed . "',
                         date_publish = '" . $this->date_publish . "',
                         date_unpublish = NULL,
                         title = '" . $this->title . "',
                         alias = '" . $this->alias . "',
                         bgimage = '" . $this->bgimage . "',
                         lang = '" . $this->language . "',
                         meta_local = '" . $this->meta_local . "',
                         meta_keywords = '" . $this->meta_keywords . "'
                     WHERE id = '" . $this->id . "'"))
                 {
                     // throw error
                     sys::setSyslog($db, 23, 1, "failed to update database of page $this->title", 0, 0, 0, 0);
                     // \YAWK\alert::draw("warning", "Warning", "page data could not be stored in database.", "", 6200);
                     // \YAWK\alert::draw("danger", 'MySQL Error: ('.mysqli_errno().')', 'Database error: '.mysqli_error($db).'', "", 0);
                     return false;
                 }
                 else
                 {
                     // update pages db worked, all fin
                     sys::setSyslog($db, 5, 0, "updated $this->alias", 0, 0, 0, 0);
                     return true;
                 }
             }
             else
             {
                 // sql code with correct, user-selected unpublish date
                 if (!$db->query("UPDATE {pages}
                     SET published = '" . $this->published . "',
                         gid = '" . $this->gid . "',
                         date_changed = '" . $date_changed . "',
                         date_publish = '" . $this->date_publish . "',
                         date_unpublish = '" . $this->date_unpublish . "',
                         title = '" . $this->title . "',
                         alias = '" . $this->alias . "',
                         bgimage = '" . $this->bgimage . "',
                         lang = '" . $this->language . "',
                         meta_local = '" . $this->meta_local . "',
                         meta_keywords = '" . $this->meta_keywords . "'
                     WHERE id = '" . $this->id . "'"))
                 {
                     // throw error
                     sys::setSyslog($db, 23, 1, "failed to update page $this->title", 0, 0, 0, 0);
                     alert::draw("warning", "Warning", "failed to store data of $this->alias in database.", "", 6200);
                     return false;
                 }
                 else
                 {
                     // update pages db worked, all fin
                     sys::setSyslog($db, 5, 0, "updated $this->alias", 0, 0, 0, 0);
                     return true;
                 }
             }
         } // ./ save function
References $db, alias, date, date_unpublish, and YAWK\alert\draw().
toggleLock()
YAWK\page::toggleLock ($db, $id, $locked)
toggle page lock to avoid unintended changes
Parameters
object $db database
int $id affected page id
int $locked 0|1 lock status
Returns
bool page toggle lock status
Definition at line 241 of file page.php.
         {
             /* @param $db db */
             $id = $db->quote($id);
             $locked = $db->quote($locked);
             if ($db->query("UPDATE {pages} SET locked = '".$locked."' WHERE id = '".$id."'")) {
                 /* free result set */
                 // $res->close();
                 return true;
             }
             else
             {   //
                 print alert::draw("danger", "Error", "Site Lock could not be toggled.","page=pages",4200);
                 if ($locked === "0") { $status = "unlocked"; } else { $status = "locked"; }
                 sys::setSyslog($db, 5,0,  "set status $status page id #$id", 0, 0, 0, 0);
                 return false;
             }
         }
References $db, YAWK\page\$id, YAWK\page\$locked, and YAWK\alert\draw().
toggleOffline()
YAWK\page::toggleOffline ($db, $id, $published, $title)
toggle page status online or offline (plus corresponding menu entries)
Parameters
object $db database
int $id affected page ID
int $published 0|1 page publish status
string $title page title
Returns
bool page toggle on/offline status
Definition at line 184 of file page.php.
         {   /* @param $db db */
             // check data types
             if (is_numeric($id) && (is_numeric($published) && is_string($title)))
             {
                 if ($published === '1')
                 { $published = 0; }
                 else if ($published === '0')
                 { $published = 1; }
                 // escape vars
                 $id = $db->quote($id);
                 $published = $db->quote($published);
                 $title = $db->quote($title);
                 if ($published === "0") { $status = "offline"; } else { $status = "online"; }
                 // TOGGLE PAGES
                 if (!$db->query("UPDATE {pages}
                                         SET published = '" . $published . "'
                                         WHERE id = '" . $id . "'"))
                 {   // could not update pages db table
                     $status = sys::iStatusToString($published, "online", "offline");
                     sys::setSyslog($db, 7, 1, "failed to toggle $title status to $status", 0, 0, 0, 0);
                     print alert::draw("danger", "Error", "Site Status could not be toggled.", "", 4200);
                 }
                 else
                 {   // ok, set syslog entry
                     sys::setSyslog($db, 5, 0, "toggled page $id to $status", 0, 0, 0, 0);
                 }
                 // TOGGLE MENU STATUS
                 if (!$db->query("UPDATE {menu}
                                         SET published = '" . $published . "'
                                         WHERE title = '" . $title . "'")) {
                     // could not update pages db table
                     print alert::draw("danger", "Error", "Menu Status could not be toggled.", "", 4200);
                 }
                 else
                 {   // ok, set syslog entry
                     sys::setSyslog($db, 21, 0, "toggled menu $id to $status", 0, 0, 0, 0);
                 }
             }
             else
             {   // data type is incorrect, throw yoda's hint
                 print alert::draw("danger", "Error", "YaWK said: variable manipulate you shall not do!", "", 4200);
             }
             return true;
         }
References $db, YAWK\page\$id, YAWK\page\$published, YAWK\page\$title, YAWK\alert\draw(), and YAWK\sys\iStatusToString().
writeContent()
YAWK\page::writeContent ($content)
write content to static page
Parameters
string $content the content to write
Returns
bool true|false
Parameters
$db db $alias
Definition at line 853 of file page.php.
         {
             /** @param $db db $alias */
             /* alias string manipulation */
             $this->alias = mb_strtolower($this->alias); // lowercase
             $this->alias = str_replace(" ", "-", $this->alias); // replace all ' ' with -
             // special chars
             $specialChars = array("//", "//", "//", "//", "//", "//", "//"); // array of special chars
             $replacementChars = array("ae", "ue", "oe", "ae", "ue", "oe", "ss"); // array of replacement chars
             $this->alias = preg_replace($specialChars, $replacementChars, $this->alias);        // replace with preg
             $this->alias = preg_replace("/[^a-z0-9\-\/]/i", "", $this->alias); // final check: just numbers and chars are allowed
             if (!empty($this->language))
             {
                 $this->language = mb_substr($this->language, 0, 2);
                 // check if requested language directory exists
                 if (!is_dir($this->path.$this->language))
                 {   // if not, create it
                     mkdir ($this->path.$this->language);
                 }
                 // store file to corresponding language folder
                 $filename = $this->path.$this->language."/".$this->alias.".php";
             }
             else
             {   // store file to content/pages root folder
                 $filename = $this->path.$this->alias.".php";
             }
             // open file
             $handle = fopen($filename, "w+");
             if (fwrite($handle, $content))
             {   // write content + close
                 fclose($handle);
                 // set file perms
                 chmod($filename, 0777);
                 return true;
             }
             else
             {   // writeContent failed
                 sys::setSyslog($db, 7, 2, "unable to write content to file $filename", 0, 0, 0, 0);
                 return false;
             }
         }
References $content, $db, $filename, $specialChars, and alias.
Member Data Documentation
$alias
YAWK\page::$alias = ''
Parameters
string page filename
Definition at line 24 of file page.php.
Referenced by YAWK\page\create(), and YAWK\page\loadProperties().
$alias_new
YAWK\page::$alias_new = ''
Parameters
string new page filename (used by copy function)
Definition at line 26 of file page.php.
$bgimage
YAWK\page::$bgimage
Parameters
string bg image
Definition at line 58 of file page.php.
$blogid
YAWK\page::$blogid
Parameters
int blog ID of that page
Definition at line 48 of file page.php.
Referenced by YAWK\page\create().
$date_created
YAWK\page::$date_created
Parameters
string date when the site is created
Definition at line 40 of file page.php.
Referenced by YAWK\page\create().
$date_publish
YAWK\page::$date_publish
Parameters
string date when the site is published
Definition at line 42 of file page.php.
$date_unpublish
YAWK\page::$date_unpublish
Parameters
string date when the site should be unpublished
Definition at line 44 of file page.php.
$gid
YAWK\page::$gid
Parameters
int group id for this page
Definition at line 38 of file page.php.
$id
YAWK\page::$id = -1
Parameters
int every page got its own id
Definition at line 22 of file page.php.
Referenced by YAWK\page\create(), YAWK\page\getCurrentLanguageByID(), YAWK\page\getProperty(), YAWK\page\loadPropertiesByID(), YAWK\page\toggleLock(), and YAWK\page\toggleOffline().
$language
YAWK\page::$language
Parameters
string page language
Definition at line 60 of file page.php.
Referenced by YAWK\page\getContent().
$locked
YAWK\page::$locked
Parameters
int 0|1 to check if the page is locked
Definition at line 50 of file page.php.
Referenced by YAWK\page\create(), and YAWK\page\toggleLock().
$menu
YAWK\page::$menu = -1
Parameters
int menu id according to this page
Definition at line 36 of file page.php.
$meta_keywords
YAWK\page::$meta_keywords = "Meta Tag Keywords"
Parameters
string the meta tags keywords of this page
Definition at line 68 of file page.php.
$meta_local
YAWK\page::$meta_local = "Meta Tag Description"
Parameters
string the meta tags description of this page
Definition at line 66 of file page.php.
$metadescription
YAWK\page::$metadescription
Parameters
string meta description for this page
Definition at line 52 of file page.php.
$metakeywords
YAWK\page::$metakeywords
Parameters
string meta keywords for this page
Definition at line 54 of file page.php.
$newLanguage
YAWK\page::$newLanguage
Parameters
bool copy page into new language indicator
Definition at line 62 of file page.php.
$ownerid
YAWK\page::$ownerid = -1
Parameters
int uid (user id) of the page owner
Definition at line 34 of file page.php.
$path
YAWK\page::$path = "../content/pages/"
Parameters
string the root path where pages are physically stored
Definition at line 64 of file page.php.
Referenced by YAWK\page\getContent().
$plugin
YAWK\page::$plugin
Parameters
int plugin ID of that page
Definition at line 46 of file page.php.
Referenced by YAWK\page\create().
$published
YAWK\page::$published = 0
Parameters
int 0|1 published status
Definition at line 32 of file page.php.
Referenced by YAWK\page\create(), and YAWK\page\toggleOffline().
$searchstring
YAWK\page::$searchstring
Parameters
string search string for this page
Definition at line 56 of file page.php.
$title
YAWK\page::$title = ''
Parameters
string page title
Definition at line 28 of file page.php.
Referenced by YAWK\page\create(), and YAWK\page\toggleOffline().
$title_new
YAWK\page::$title_new = ''
Parameters
string new page title (used by copy function)
Definition at line 30 of file page.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/page.php