YaWK: YAWK\WIDGETS\GOOGLE\MAPS\googleMaps Class Reference
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps Class Reference
Embed Google Maps on your page.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embed ()
init ()
Init and embed Google Maps.
printObject ()
Print all object data.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
Public Attributes
$googleMapsEmbedHtmlCode = ''
$googleMapsHeading = ''
$googleMapsSubtext = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Embed Google Maps on your page.
Google Maps Widget - Embed a Google Map on your page
This Widget serves all methods to draw any Google Map on your website. To do this: go to Google Maps, click on embed and you will get a piece of html code. Simply copy/paste the code into the textarea, click save and your google map will be displayed in your chosen widget position.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file googleMaps.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 33 of file googleMaps.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
         }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embed()
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::embed ()
Definition at line 63 of file googleMaps.php.
         {
             // draw heading above google map
             echo $this->getHeading($this->googleMapsHeading, $this->googleMapsSubtext);
             // check if embed html code is set and correct data type
             if (isset($this->googleMapsEmbedHtmlCode)
                 && (!empty($this->googleMapsEmbedHtmlCode))
                 && (is_string($this->googleMapsEmbedHtmlCode)))
             {
                 // embed code seems to be valid -
                 // draw Google Map...
                 echo $this->googleMapsEmbedHtmlCode;
             }
             else
                 {
                     echo "Here should be a Google Map, but the required embed code was not set.";
                 }
         }
References YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\$googleMapsEmbedHtmlCode, and YAWK\widget\getHeading().
Referenced by YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\init().
init()
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::init ()
Init and embed Google Maps.
Embed Google Maps
Definition at line 58 of file googleMaps.php.
         {   // embed Google Maps
             $this->embed();
         }
References YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\embed().
printObject()
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::printObject ()
Print all object data.
(for development and testing purpose)
Reimplemented from YAWK\widget.
Definition at line 47 of file googleMaps.php.
         {   // output data to screen
             echo "<pre>";
             print_r($this);
             echo "</pre>";
         }
Member Data Documentation
$googleMapsEmbedHtmlCode
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::$googleMapsEmbedHtmlCode = ''
Parameters
string the html code you'll get from google <iframe...>
Definition at line 22 of file googleMaps.php.
Referenced by YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\embed().
$googleMapsHeading
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::$googleMapsHeading = ''
Parameters
string Heading above Google Map
Definition at line 24 of file googleMaps.php.
$googleMapsSubtext
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::$googleMapsSubtext = ''
Parameters
string Subtext beside heading
Definition at line 26 of file googleMaps.php.
$widget
YAWK\WIDGETS\GOOGLE\MAPS\googleMaps::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file googleMaps.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/googleMaps/classes/googleMaps.php