YaWK: YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus Class Reference
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus Class Reference
Embed Bubbl.us Presentations on your pages.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
init ()
Embed any BubblUs mindmaps.
printObject ()
Print all object data.
setProperties ()
Set widget properties from database and fill object params.
Public Attributes
$bubblusHeading = ''
$bubblusHeadline = ''
$bubblusHeight = '370'
$bubblusSubtext = ''
$bubblusUrl = ''
$bubblusWidth = '100%'
$widget = ''
Detailed Description
Embed Bubbl.us Presentations on your pages.
Embed any bubbl.us mindmap on your page.
Bubbl.us is a service, where you can create mindmaps and share them with your friends and the web. With this widget, you are able to embed any public Bubbl.us mindmaps. Simply enter the URL of your mindmap and a view settings. Embedding and sharing mindmaps has never been easier.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 16 of file bubblus.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 38 of file bubblus.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
init()
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::init ()
Embed any BubblUs mindmaps.
This method does the setup and embed job
Definition at line 95 of file bubblus.php.
         {
             // set widget obj properties
             $this->setProperties();
             // draw headline, if set
             echo "$this->bubblusHeadline";
             // embed mindmap via iframe...
             echo "<iframe width=\"$this->bubblusWidth\" height=\"$this->bubblusHeight\" allowfullscreen frameborder=\"0\" src=\"$this->bubblusUrl\"></iframe>";
References YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus\setProperties().
printObject()
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 52 of file bubblus.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
setProperties()
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::setProperties ()
Set widget properties from database and fill object params.
Load all widget settings.
Definition at line 63 of file bubblus.php.
         {
             // if a heading is set and not empty
             if (isset($this->bubblusHeading) && (!empty($this->bubblusHeading)))
             {
                 // if subtext is set, add <small> subtext to string
                 if (isset($this->bubblusSubtext) && (!empty($this->bubblusSubtext)))
                 {   // build a headline with heading and subtext
                     $this->bubblusSubtext = "<small>$this->bubblusSubtext</small>";
                     $this->bubblusHeadline = "<div id=\"bubblusHeading\"><h1>$this->bubblusHeading&nbsp;"."$this->bubblusSubtext</h1></div>";
                 }
                 else
                 {   // build just a headline - without subtext
                     $this->bubblusHeadline = "<h1>$this->bubblusHeading</h1>";    // draw just the heading
                 }
             }
             else
             {   // leave empty if it's not set
                 $this->bubblusHeadline = '';
             }
             // prepare url
             if (isset($this->bubblusUrl) && (!empty($this->bubblusUrl)))
             {   // remove trailing slash
                 $this->bubbleusUrl = rtrim("/", $this->bubblusUrl);
             }
Referenced by YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus\init().
Member Data Documentation
$bubblusHeading
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusHeading = ''
Parameters
string Heading
Definition at line 27 of file bubblus.php.
$bubblusHeadline
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusHeadline = ''
Parameters
string Headline HTML Markup
Definition at line 31 of file bubblus.php.
$bubblusHeight
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusHeight = '370'
Parameters
string Height in px
Definition at line 25 of file bubblus.php.
$bubblusSubtext
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusSubtext = ''
Parameters
string Subtext
Definition at line 29 of file bubblus.php.
$bubblusUrl
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusUrl = ''
Parameters
string URL of your bubblus presentation
Definition at line 21 of file bubblus.php.
$bubblusWidth
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$bubblusWidth = '100%'
Parameters
string Width in percent
Definition at line 23 of file bubblus.php.
$widget
YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus::$widget = ''
Parameters
object global widget object data
Definition at line 19 of file bubblus.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/bubblus/classes/bubblus.php