YaWK: YAWK\WIDGETS\GALLERY\IMAGES\gallery Class Reference
YAWK\WIDGETS\GALLERY\IMAGES\gallery Class Reference
Embed a photo gallery on your website.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
drawImageGallery ($db)
Draw the gallery.
init ($db)
Init Gallery and load methods.
loadJavascript ()
Check if lightbox asset is loaded and set lightbox options.
printObject ()
Print all object data.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
Public Attributes
$filename = ''
$galleryAlbumLabel = 'Image %1 of %2'
$galleryDisableScrolling = false
$galleryFadeDuration = '600'
$galleryFitImagesInViewport = true
$galleryHeading = ''
$galleryID = ''
$galleryImageClass = 'img-responsive img-rounded hvr-grow'
$galleryImageFadeDuration = '600'
$galleryLayoutRows = 3
$galleryMaxHeight = ''
$galleryMaxWidth = ''
$galleryNavOnTouchDevices = false
$galleryPositionFromTop = '50'
$galleryResizeDuration = '700'
$galleryShowImageNumberLabel = true
$galleryShuffle = false
$gallerySubtext = ''
$galleryTnHeight = ''
$galleryTnWidth = ''
$galleryWidthMarkup = ''
$galleryWrapAround = false
$headline = ''
$itemAuthor = ''
$itemAuthorUrl = ''
$itemID = ''
$itemTitle = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Embed a photo gallery on your website.
Embed plugin: photo gallery
This is the widget to the gallery plugin. With this widget you can embed image galleries that you've created before using the gallery plugin. Simply set the ID of the photo gallery you would like to embed.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 16 of file gallery.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\GALLERY\IMAGES\gallery::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 85 of file gallery.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawImageGallery()
YAWK\PLUGINS\GALLERY\gallery::drawImageGallery ($db)
Draw the gallery.
Parameters
db object Database object
(for development and testing purpose)
Parameters
object $db database
array $lang language array
int $galleryID gallery ID to load
Parameters
$db \YAWK\db
$widget \YAWK\widget
Definition at line 155 of file gallery.php.
         {   /** @param $db \YAWK\db **/
             if (!isset($this->galleryID) || (empty($this->galleryID)))
             {
                 echo "Error: unable to load photo gallery because there is no gallery selected.";
             }
             if ($res = $db->query("SELECT folder from {plugin_gallery} WHERE id = '".$this->galleryID."'"))
             {
                 while ($row = mysqli_fetch_assoc($res))
                 {   // check if shuffle is enabled
                     if (isset($this->galleryShuffle) && ($this->galleryShuffle === 'true'))
                     {   // randomize pictures
                         $order = "ORDER BY RAND()";
                     }
                     else
                         {   // order by sortation
                             $order = "ORDER BY sort ASC";
                         }
                     if (!$getPreviewImages = $db->query("SELECT id, galleryID, sort, filename, title, author, authorUrl
                                                          from {plugin_gallery_items}
                                                          WHERE galleryID = '".$this->galleryID."' $order"))
                     {   // store info msg, if files could not be retrieved
                         $previewError = "Sorry, could not get preview images";
                     }
                     if (isset($previewError))
                     {   // if files could not be loaded from db
                         echo $previewError;
                     }
                     else
                     {
                         // prepare loop vars
                         $count = 0;
                         $divider = 3;
                         /** @param $widget \YAWK\widget */
                         // get headline
                         $this->headline = $this->getHeading($this->galleryHeading, $this->gallerySubtext);
                         // draw headline
                         echo $this->headline;
                         echo '<div class="container-fluid">
                             <div class="row text-center">';
                         // check gallery layout (how many cols per row)
                         if ($this->galleryLayoutRows === "1")
{
                             $col = "col-md-12";
                             $divider = 1;
                         }
                         elseif ($this->galleryLayoutRows === "2")
{
                             $col = "col-md-6";
                             $divider = 2;
                         }
                         elseif ($this->galleryLayoutRows === "3")
{
                             $col = "col-md-4";
                             $divider = 3;
                         }
                         elseif ($this->galleryLayoutRows === "4")
{
                             $col = "col-md-3";
                             $divider = 4;
                         }
                         elseif ($this->galleryLayoutRows === "6")
{
                             $col = "col-md-2";
                             $divider = 6;
                         }
                         elseif ($this->galleryLayoutRows === "12")
{
                             $col = "col-md-1";
                             $divider = 12;
                         }
                         else
{
                                 $col = "col-md-4";
                             }
                         // check thumbnail width
                         if (isset($this->galleryTnWidth) && (!empty($this->galleryTnWidth)))
                         {   // set tn width markup
                             $this->galleryWidthMarkup = "width=\"$this->galleryTnWidth\" ";
                         }
                         else
                             {   // no width markup needed
                                 $this->galleryWidthMarkup = '';
                             }
                         foreach ($getPreviewImages as $property => $image)
                         {   // display preview images
                             for ($i = 0; $i < count($property); $i++)
{
                                 $this->itemID = $image['id'];
                                 $this->sort = $image['sort'];
                                 $this->filename = $image['filename'];
                                 $this->itemTitle = $image['title'];
                                 $this->itemAuthor = $image['author'];
                                 $this->itemAuthorUrl = $image['authorUrl'];
                                 // $rnd = uniqid();
                                 echo "
                                 <div class=\"$col text-center\" id=\"imgCol-".$this->itemID."\">
                                     <a href=\"$row[folder]/$this->filename\" data-lightbox=\"$this->galleryID\" data-title=\"$this->itemTitle\"><img ".$this->galleryWidthMarkup."class=\"$this->galleryImageClass\" id=\"img-$this->itemID\" title=\"$this->itemTitle\" src=\"$row[folder]/$this->filename\"></a><br><br>
                                 </div>
                                       ";
                                 $count++;
                                 // close tag, but never before the first run
                                 if ($count > 1)
{
                                     if($count % $divider == 0) echo '
                             </div> <!-- end row -->
                                 <div class="row text-center">';
                                 }
                             }
                         }
                         echo "</div></div>";
                     }
                 }
             }
References $col, $db, YAWK\WIDGETS\GALLERY\IMAGES\gallery\$headline, $i, $res, and YAWK\widget\getHeading().
Referenced by YAWK\WIDGETS\GALLERY\IMAGES\gallery\init().
init()
YAWK\WIDGETS\GALLERY\IMAGES\gallery::init ($db)
Init Gallery and load methods.
load Javascript and draw image gallery
Definition at line 110 of file gallery.php.
         {
             $this->loadJavascript();
             $this->drawImageGallery($db);
References $db, YAWK\WIDGETS\GALLERY\IMAGES\gallery\drawImageGallery(), and YAWK\WIDGETS\GALLERY\IMAGES\gallery\loadJavascript().
loadJavascript()
YAWK\WIDGETS\GALLERY\IMAGES\gallery::loadJavascript ()
Check if lightbox asset is loaded and set lightbox options.
check lightbox asset and set options
Definition at line 120 of file gallery.php.
         {
             // check if gallery max width is set
             if (isset($this->galleryMaxWidth) && (empty($this->galleryMaxWidth)))
             {   // nope, no markup needed
                 $maxWidthMarkup = '';
             }
             else
                 {   // set gallery markup
                     $maxWidthMarkup = "
                     'maxWidth': $this->galleryMaxWidth,";
                 }
             echo "
             <script type=\"text/javascript\">
                 lightbox.option({
                     'alwaysShowNavOnTouchDevices': $this->galleryNavOnTouchDevices,
                     'albumLabel': \"$this->galleryAlbumLabel\",
                     'disableScrolling': $this->galleryDisableScrolling,
                     'fadeDuration': $this->galleryFadeDuration,
                     'fitImagesInViewport': $this->galleryFitImagesInViewport,
                     'imageFadeDuration': $this->galleryImageFadeDuration,$maxWidthMarkup
                     'positionFromTop': $this->galleryPositionFromTop,
                     'resizeDuration': $this->galleryResizeDuration,
                     'showImageNumberLabel': $this->galleryShowImageNumberLabel,
                     'wrapAround': $this->galleryWrapAround
                 });
             </script>";
Referenced by YAWK\WIDGETS\GALLERY\IMAGES\gallery\init().
printObject()
YAWK\WIDGETS\GALLERY\IMAGES\gallery::printObject ()
Print all object data.
(for development and testing purpose)
Reimplemented from YAWK\widget.
Definition at line 99 of file gallery.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
Member Data Documentation
$filename
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$filename = ''
Parameters
string Image filename
Definition at line 30 of file gallery.php.
$galleryAlbumLabel
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryAlbumLabel = 'Image %1 of %2'
Parameters
string The text displayed below the caption when viewing an image set. The default text shows the current image number and the total number of images in the set.
Definition at line 43 of file gallery.php.
$galleryDisableScrolling
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryDisableScrolling = false
Parameters
bool If true, prevent the page from scrolling while Lightbox is open. This works by settings overflow hidden on the body.
Definition at line 45 of file gallery.php.
$galleryFadeDuration
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryFadeDuration = '600'
Parameters
string The time it takes for the Lightbox container and overlay to fade in and out, in milliseconds.
Definition at line 47 of file gallery.php.
$galleryFitImagesInViewport
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryFitImagesInViewport = true
Parameters
bool If true, resize images that would extend outside of the viewport so they fit neatly inside of it. This saves the user from having to scroll to see the entire image.
Definition at line 49 of file gallery.php.
$galleryHeading
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 23 of file gallery.php.
$galleryID
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryID = ''
Parameters
int Gallery ID
Definition at line 21 of file gallery.php.
$galleryImageClass
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryImageClass = 'img-responsive img-rounded hvr-grow'
Parameters
string Image Class
Definition at line 77 of file gallery.php.
$galleryImageFadeDuration
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryImageFadeDuration = '600'
Parameters
string The time it takes for the image to fade in once loaded, in milliseconds.
Definition at line 51 of file gallery.php.
$galleryLayoutRows
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryLayoutRows = 3
Parameters
int How many pictures should be drawn per row?
Definition at line 70 of file gallery.php.
$galleryMaxHeight
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryMaxHeight = ''
Parameters
string If set, the image height will be limited to this number, in pixels. Aspect ratio will not be maintained.
Definition at line 55 of file gallery.php.
$galleryMaxWidth
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryMaxWidth = ''
Parameters
string If set, the image width will be limited to this number, in pixels. Aspect ratio will not be maintained.
Definition at line 53 of file gallery.php.
$galleryNavOnTouchDevices
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryNavOnTouchDevices = false
Parameters
bool galleryNavOnTouchDevices If true, the left and right navigation arrows which appear on mouse hover when viewing image sets will always be visible on devices which support touch.
Definition at line 41 of file gallery.php.
$galleryPositionFromTop
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryPositionFromTop = '50'
Parameters
string The distance from top of viewport that the Lightbox container will appear, in pixels
Definition at line 61 of file gallery.php.
$galleryResizeDuration
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryResizeDuration = '700'
Parameters
string The time it takes for the Lightbox container to animate its width and height when transition between different size images, in milliseconds.
Definition at line 63 of file gallery.php.
$galleryShowImageNumberLabel
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryShowImageNumberLabel = true
Parameters
bool If false, the text indicating the current image number and the total number of images in set (Ex. "image 2 of 4") will be hidden.
Definition at line 65 of file gallery.php.
$galleryShuffle
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryShuffle = false
Parameters
bool true|false Shuffle Images
Definition at line 72 of file gallery.php.
$gallerySubtext
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$gallerySubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 25 of file gallery.php.
$galleryTnHeight
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryTnHeight = ''
Parameters
string If set, the thumbnail image height will be limited to this number, in pixels. Aspect ratio will not be maintained.
Definition at line 59 of file gallery.php.
$galleryTnWidth
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryTnWidth = ''
Parameters
string If set, the thumbnail image width will be limited to this number, in pixels. Aspect ratio will not be maintained.
Definition at line 57 of file gallery.php.
$galleryWidthMarkup
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryWidthMarkup = ''
Parameters
string <img Width HTML Markup
Definition at line 75 of file gallery.php.
$galleryWrapAround
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$galleryWrapAround = false
Parameters
bool If true, when a user reaches the last image in a set, the right navigation arrow will appear and they will be to continue moving forward which will take them back to the first image in the set.
Definition at line 67 of file gallery.php.
$headline
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$headline = ''
Parameters
string Headline above widget
Definition at line 38 of file gallery.php.
Referenced by YAWK\WIDGETS\GALLERY\IMAGES\gallery\drawImageGallery().
$itemAuthor
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$itemAuthor = ''
Parameters
string Image Author (Copyright Notice)
Definition at line 34 of file gallery.php.
$itemAuthorUrl
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$itemAuthorUrl = ''
Parameters
string Image Author URL
Definition at line 36 of file gallery.php.
$itemID
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$itemID = ''
Parameters
int Image Item ID
Definition at line 28 of file gallery.php.
$itemTitle
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$itemTitle = ''
Parameters
string Image Description
Definition at line 32 of file gallery.php.
$widget
YAWK\WIDGETS\GALLERY\IMAGES\gallery::$widget = ''
Parameters
object global widget object data
Definition at line 19 of file gallery.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/gallery/classes/gallery.php