YaWK: YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter Class Reference
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter Class Reference
Embed any YouTube Video on your pages.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object params.
drawForm ()
Draw the newsletter html form.
includeJS ()
Load all required javascript files.
init ()
Init Function: Loads the required JS, set properties and draw the form.
printObject ()
Print all object data.
setProperties ()
Set all object properties and html markup codes depending on current widget settings.
Public Attributes
$markupBtnAlign = ''
$markupBtnClass = ''
$markupBtnMarginTop = ''
$markupEmailLabel = ''
$markupFontSizeEnd = '</H2>'
$markupFontSizeStart = '<H2>'
$markupFormWidth = ''
$markupIcon = ''
$markupNameLabel = ''
$newsletterBtnAlign = 'text-center'
$newsletterBtnClass = 'btn btn-success'
$newsletterBtnMarginTop = '5px'
$newsletterBtnText = 'Subscribe Newsletter'
$newsletterEmailPlaceholder = 'Email'
$newsletterFontSize = 'h2'
$newsletterHideLabels = 'false'
$newsletterIcon = 'fa fa-envelope-o'
$newsletterNamePlaceholder = 'Name'
$newsletterSubtext = 'subscribe'
$newsletterThankYouSubtext = 'for subscribing to our newsletter!'
$newsletterThankYouTitle = 'Thank You'
$newsletterTitle = 'Newsletter'
$newsletterWidth = ''
$widget = ''
Detailed Description
Embed any YouTube Video on your pages.
Let your users subscribe to a newsletter database.
With this widget, you are able to collect email addresses to build up your newsletter database. The user can enter his email address and (or) his/hers name. The form will be processed via ajax which means the page will not refresh by clicking on submit. Data will be entered in the newsletter database, which other plugins and widgets can access easily. In future releases, it is planned to implement a newsletter plugin, where admins can manage and send newsletters within the backend.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 18 of file newsletter.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::__construct ($db)
Load all widget settings from database and fill object params.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 74 of file newsletter.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawForm()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::drawForm ()
Draw the newsletter html form.
Definition at line 216 of file newsletter.php.
         {
             echo"
             <div class=\"container-fluid\">
             <div class=\"row\">
             <div class=\"col-md-12\">
             <div id=\"formWrapper\">
             <div id=\"newsletterTitle\">$this->markupFontSizeStart$this->markupIcon$this->newsletterTitle <small>$this->newsletterSubtext</small>$this->markupFontSizeEnd</div>
             <form class=\"form-horizontal\" id=\"form\" method=\"post\">
                 $this->markupNameLabel
                 <input type=\"text\" name=\"name\" id=\"name\" class=\"form-control\" placeholder=\"$this->newsletterNamePlaceholder\"$this->markupFormWidth>
                 $this->markupEmailLabel
                 <input type=\"text\" name=\"email\" id=\"email\" class=\"form-control\" placeholder=\"$this->newsletterEmailPlaceholder\"$this->markupFormWidth>
                 <input type=\"hidden\" name=\"thankYouTitle\" id=\"thankYouTitle\" value=\"$this->newsletterThankYouTitle\">
                 <input type=\"hidden\" name=\"thankYouSubtext\" id=\"thankYouSubtext\" value=\"$this->newsletterThankYouSubtext\">
                 <div$this->markupBtnAlign$this->markupFormWidth>
                     <input type=\"button\" class=\"$this->markupBtnClass\" id=\"submit\" name=\"submit\" value=\"$this->newsletterBtnText\"$this->markupBtnMarginTop>
                 </div>
             </form>
             </div>
             <div id=\"thankYouMessage\"></div>
             </div>
             </div>
             </div>";
Referenced by YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\init().
includeJS()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::includeJS ()
Load all required javascript files.
include required javascript assets (validade, messages and ajax js file)
Definition at line 113 of file newsletter.php.
         {
             // load validate js
             echo "<script type=\"text/javascript\" src=\"system/engines/jquery/jquery.validate.min.js\"></script>";
             // if current language is german
             if (\YAWK\language::getCurrentLanguageStatic() == "de-DE")
             {   // load german language file
                 echo "<script type=\"text/javascript\" src=\"system/engines/jquery/messages_de.min.js\"></script>";
             }
             // load ajax file
             echo "<script type=\"text/javascript\" src=\"system/widgets/newsletter/js/nl.js\"></script>";
References YAWK\language\getCurrentLanguageStatic().
Referenced by YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\init().
init()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::init ()
Init Function: Loads the required JS, set properties and draw the form.
This method does the setup and embed job
Definition at line 99 of file newsletter.php.
         {
             // load required javascript files
             $this->includeJS();
             // prepare properties and settings
             $this->setProperties();
             // lets start - draw newsletter form
             $this->drawForm();
References YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\drawForm(), YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\includeJS(), and YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\setProperties().
printObject()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::printObject ()
Print all object data.
(for development and testing purpose)
Definition at line 88 of file newsletter.php.
         {
             echo "<pre>";
             print_r($this);
             echo "</pre>";
setProperties()
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::setProperties ()
Set all object properties and html markup codes depending on current widget settings.
Set object properties and html markup
Definition at line 130 of file newsletter.php.
         {
             // check if btn margin top is set
             if (isset($this->newsletterBtnMarginTop) && (!empty($this->newsletterBtnMarginTop)))
             {   // set markup
                 $this->markupBtnMarginTop = " style=\"margin-top:$this->newsletterBtnMarginTop\"";
             }
             else
             {   // no btn margin set, leave markup empty
                 $this->markupBtnMarginTop = '';
             }
             // check btn class and alignment
             if (isset($this->newsletterBtnClass) && (!empty($this->newsletterBtnClass)))
             {   // set markup
                 $this->markupBtnClass = "$this->newsletterBtnClass";
             }
             else
             {   // no btn margin set, leave markup empty
                 $this->markupBtnClass = '';
             }
             // check button alignment
             if (isset($this->newsletterBtnAlign) && (!empty($this->newsletterBtnAlign)))
             {   // set btn align markup
                 $this->markupBtnAlign = " class=\"$this->newsletterBtnAlign\"";
             }
             else
             {   // no markup needed, leave empty
                 $this->markupBtnAlign = '';
             }
             // check if labels should be hidden
             if (isset($this->newsletterHideLabels) && ($this->newsletterHideLabels == "false"))
             {   // label html markup code
                 $this->markupNameLabel = "<label for=\"name\">$this->newsletterNamePlaceholder</label>";
                 $this->markupEmailLabel = "<br><label for=\"email\">$this->newsletterEmailPlaceholder</label>";
             }
             else
             {   // no labels
                 $this->markupNameLabel = '';
                 $this->markupEmailLabel = '';
             }
             // check if icon is set
             if (isset($this->newsletterIcon) && (!empty($this->newsletterIcon)))
             {   // icon html markup
                 $this->markupIcon = "<i class=\"$this->newsletterIcon\"></i>&nbsp;";
             }
             else
             {   // no icon, no markup
                 $this->markupIcon = '';
             }
             // check which font size is set
             if (isset($this->newsletterFontSize) && (!empty($this->newsletterFontSize)))
             {   // set markup for h tags
                 $this->markupFontSizeStart = "<$this->newsletterFontSize>";
                 $this->markupFontSizeEnd = "</$this->newsletterFontSize>";
             }
             else
             {   // if font size is not set, use default:
                 $this->markupFontSizeStart = "<H2>";
                 $this->markupFontSizeEnd = "</H2>";
             }
             // check if form width is set
             if (isset($this->newsletterWidth) && (!empty($this->newsletterWidth)))
             {   // check if user appended a % sign
                 if (substr($this->newsletterWidth, -1) != "%")
                 {   // if not, append it for the user
                     $this->newsletterWidth = $this->newsletterWidth."%";
                 }
                 // set html markup
                 $this->markupFormWidth = " style=\"width: $this->newsletterWidth;\"";
             }
             else
                 {   // no width requested, leave empty
                     $this->markupFormWidth = '';
                 }
Referenced by YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\init().
Member Data Documentation
$markupBtnAlign
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupBtnAlign = ''
Parameters
string Btn Alignment HTML Markup
Definition at line 55 of file newsletter.php.
$markupBtnClass
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupBtnClass = ''
Parameters
string Btn Class HTML Markup
Definition at line 53 of file newsletter.php.
$markupBtnMarginTop
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupBtnMarginTop = ''
Parameters
string Btn Margin HTML Markup
Definition at line 51 of file newsletter.php.
$markupEmailLabel
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupEmailLabel = ''
Parameters
string Email Label HTML Markup
Definition at line 59 of file newsletter.php.
$markupFontSizeEnd
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupFontSizeEnd = '</H2>'
Parameters
string Font Size (H1-H6) HTML Markup End
Definition at line 65 of file newsletter.php.
$markupFontSizeStart
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupFontSizeStart = '<H2>'
Parameters
string Font Size (H1-H6) HTML Markup Start
Definition at line 63 of file newsletter.php.
$markupFormWidth
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupFormWidth = ''
Parameters
string Form width HTML Markup
Definition at line 67 of file newsletter.php.
$markupIcon
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupIcon = ''
Parameters
string Icon HTML Markup
Definition at line 61 of file newsletter.php.
$markupNameLabel
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$markupNameLabel = ''
Parameters
string Name Label HTML Markup
Definition at line 57 of file newsletter.php.
$newsletterBtnAlign
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterBtnAlign = 'text-center'
Parameters
string Button Button Alignment
Definition at line 41 of file newsletter.php.
$newsletterBtnClass
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterBtnClass = 'btn btn-success'
Parameters
string Button CSS Class
Definition at line 33 of file newsletter.php.
$newsletterBtnMarginTop
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterBtnMarginTop = '5px'
Parameters
string Button Button Margin Top
Definition at line 39 of file newsletter.php.
$newsletterBtnText
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterBtnText = 'Subscribe Newsletter'
Parameters
string Button Text
Definition at line 31 of file newsletter.php.
$newsletterEmailPlaceholder
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterEmailPlaceholder = 'Email'
Parameters
string Email Field Placeholder
Definition at line 37 of file newsletter.php.
$newsletterFontSize
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterFontSize = 'h2'
Parameters
string Font size of icon, heading and subtext
Definition at line 47 of file newsletter.php.
$newsletterHideLabels
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterHideLabels = 'false'
Parameters
string Hide Form Labels?
Definition at line 43 of file newsletter.php.
$newsletterIcon
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterIcon = 'fa fa-envelope-o'
Parameters
string Newsletter Icon (eg. font awesome or glyphicons)
Definition at line 45 of file newsletter.php.
$newsletterNamePlaceholder
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterNamePlaceholder = 'Name'
Parameters
string Name Field Placeholder
Definition at line 35 of file newsletter.php.
$newsletterSubtext
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterSubtext = 'subscribe'
Parameters
string Thank You Subtext
Definition at line 25 of file newsletter.php.
$newsletterThankYouSubtext
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterThankYouSubtext = 'for subscribing to our newsletter!'
Parameters
string Thank You SubText
Definition at line 29 of file newsletter.php.
$newsletterThankYouTitle
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterThankYouTitle = 'Thank You'
Parameters
string Thank You Title Text
Definition at line 27 of file newsletter.php.
$newsletterTitle
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterTitle = 'Newsletter'
Parameters
string Title Text
Definition at line 23 of file newsletter.php.
$newsletterWidth
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$newsletterWidth = ''
Parameters
string Width of the form elements
Definition at line 49 of file newsletter.php.
$widget
YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter::$widget = ''
Parameters
object global widget object data
Definition at line 21 of file newsletter.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/newsletter/classes/newsletter.php