YaWK: SSilence\ImapClient\ImapClient Class Reference
SSilence\ImapClient\ImapClient Class Reference
Public Member Functions
__construct ($mailbox=null, $username=null, $password=null, $encryption=null)
__destruct ()
addFolder ($name, $subscribe=false)
close ()
connectAdvanced (array $config)
connectDefault ($mailbox, $username, $password, $encryption=null)
convertToUtf8 ($str)
countMessages ()
countUnreadMessages ()
deleteMessage ($id)
deleteMessages ($ids)
getBriefInfoMessages ()
getError ()
getFolders ($separator=null, $type=0)
getId ($uid)
getImap ()
getImapConnection ()
getMailboxStatistics ()
getMessage ($id, $decode=IncomingMessage::DECODE)
getMessageHeader ($id)
getMessageOverview ($id, $options=null)
getMessages ($number=0, $start=0, $order='DESC', $filter='ALL')
getMessagesByCriteria ($criteria='', $number=0, $start=0, $order='DESC')
getMessagesOverview ($id, $options=null)
getQuota ($mailbox)
getQuotaRoot ($mailbox)
getSection ($id, $section)
getUid ($id)
getUnreadMessages ($read=true)
imapFetchOverview ($sequence, $options=null)
imapFetchStructure ($id)
imapHeaderInfo ($id)
isConnected ()
moveMessage ($id, $target)
moveMessages ($ids, $target)
purge ()
removeFolder ($name)
renameFolder ($name, $newname)
saveAttachments ($options=null)
saveAttachmentsMessagesBySubject ($subject, $dir=null, $charset=null)
saveEmail ($file=null, $id=null, $part=null)
saveEmailSafe ($file=null, $id=null, $part=null, $streamFilter='convert.base64-decode')
saveMessageInSent ($header, $body)
selectFolder ($folder)
sendMail ()
setSeenMessage ($ids)
setUnseenMessage ($ids)
unSubscribe ()
Static Public Member Functions
static setConnectAdvanced ()
static setConnectConfig (array $config)
static setConnectDefault ()
Public Attributes
$connection
$currentFolder
$incomingMessage
const CONNECT_ADVANCED = 'connectAdvanced'
const CONNECT_DEFAULT = 'connectDefault'
const ENCRYPT_SSL = 'ssl'
const ENCRYPT_TLS = 'tls'
Static Public Attributes
static $connect
static $connectConfig
Protected Member Functions
arrayToAddress ($addresses)
getEncoding ($id)
getSent ()
getTrash ()
toAddress ($headerinfos)
Protected Attributes
$folder = "INBOX"
$imap
$mailbox = ""
Private Member Functions
checkMessageId ($id)
Detailed Description
Class ImapClient is helper class for imap access.
Copyright
Copyright (c) Tobias Zeising (http://www.aditu.de)
Author
Tobias Zeising tobia.nosp@m.s.ze.nosp@m.ising.nosp@m.@adi.nosp@m.tu.de
Definition at line 15 of file ImapClient.php.
Constructor & Destructor Documentation
__construct()
SSilence\ImapClient\ImapClient::__construct ($mailbox = null, $username = null, $password = null, $encryption = null)
Initialize imap helper
Parameters
string $mailbox
string $username
string $password
string $encryption use ImapClient::ENCRYPT_SSL or ImapClient::ENCRYPT_TLS
Definition at line 93 of file ImapClient.php.
     {
         if(isset($mailbox) && is_string($mailbox)){
             $this->setConnectDefault();
         };
         if(isset($mailbox) && is_array($mailbox)){
             $this->setConnectAdvanced();
             $this->setConnectConfig($mailbox);
         };
         if(!isset(self::$connect) || self::$connect === self::CONNECT_DEFAULT){
             $this->connectDefault($mailbox, $username, $password, $encryption);
         };
         if(self::$connect === self::CONNECT_ADVANCED){
             $this->connectAdvanced(self::$connectConfig);
         };
     }
References $encryption, SSilence\ImapClient\ImapClient\$mailbox, $password, $username, SSilence\ImapClient\ImapClient\connectAdvanced(), SSilence\ImapClient\ImapClient\connectDefault(), SSilence\ImapClient\ImapClient\setConnectAdvanced(), SSilence\ImapClient\ImapClient\setConnectConfig(), and SSilence\ImapClient\ImapClient\setConnectDefault().
__destruct()
SSilence\ImapClient\ImapClient::__destruct ()
Close connection
Also called during garbage collection
Returns
void
Definition at line 219 of file ImapClient.php.
     {
         if (is_resource($this->imap))
         {
             imap_close($this->imap);
         }
     }
Member Function Documentation
addFolder()
SSilence\ImapClient\ImapClient::addFolder ($name, $subscribe = false)
Add a new folder
Parameters
string $name of the folder
bool | false $subscribe immediately subscribe to folder
Returns
bool success or not
Definition at line 821 of file ImapClient.php.
     {
         $success = imap_createmailbox($this->imap, $this->mailbox . $name);
         if ($success && $subscribe) {
             $success = imap_subscribe($this->imap, $this->mailbox . $name);
         }
         return $success;
     }
References $name.
Referenced by SSilence\ImapClient\ImapClient\getSent(), and SSilence\ImapClient\ImapClient\getTrash().
arrayToAddress()
SSilence\ImapClient\ImapClient::arrayToAddress ($addresses) protected
Converts imap given array of addresses as strings
Parameters
array $addresses imap given addresses as array
Returns
array with strings (e.g. ["Name <email@bla.de>", "Name2 <email2@bla.de>"]
Definition at line 1127 of file ImapClient.php.
{
         $addressesAsString = array();
         foreach ($addresses as $address) {
             $addressesAsString[] = $this->toAddress($address);
         }
         return $addressesAsString;
     }
References as, and SSilence\ImapClient\ImapClient\toAddress().
checkMessageId()
SSilence\ImapClient\ImapClient::checkMessageId ($id) private
Check message id
Parameters
integer $id
Returns
void
Exceptions
ImapClientException
Definition at line 1257 of file ImapClient.php.
     {
         if(!is_int($id)){
             throw new ImapClientException('$id must be an integer!');
         };
         if($id <= 0){
             throw new ImapClientException('$id must be greater then 0!');
         };
         if($id > $this->countMessages()){
             throw new ImapClientException('$id does not exist');
         }
     }
References $id, and SSilence\ImapClient\ImapClient\countMessages().
Referenced by SSilence\ImapClient\ImapClient\getMessage().
close()
SSilence\ImapClient\ImapClient::close ()
Explicitly close imap connection
Definition at line 976 of file ImapClient.php.
{
         if ($this->imap !== false) {
             imap_close($this->imap);
         }
     }
connectAdvanced()
SSilence\ImapClient\ImapClient::connectAdvanced (array $config)
Advanced connect
Parameters
array $config
Returns
void
Exceptions
ImapClientException
Definition at line 197 of file ImapClient.php.
     {
         if(!isset($config['flags'])){$config['flags'] = null;};
         if(!isset($config['mailbox'])){$config['mailbox'] = null;};
         if(!isset($config['connect'])){
             throw new ImapClientException('Option connect must be installed');
         };
         $connect = new ImapConnect();
         $connect->prepareFlags($config['flags']);
         $connect->prepareMailbox($config['mailbox']);
         $connect->connect($config['connect']);
         $this->imap = $connect->getImap();
         $this->mailbox = $connect->getMailbox();
     }
References SSilence\ImapClient\ImapClient\$connect.
Referenced by SSilence\ImapClient\ImapClient\__construct().
connectDefault()
SSilence\ImapClient\ImapClient::connectDefault ($mailbox, $username, $password, $encryption = null)
The default connection. Not used a lot of imap connection options. Use only ENCRYPT_SSL and VALIDATE_CERT.
If you need a more advanced connection settings, use connectAdvanced() method.
Parameters
string $mailbox
string $username
string $password
string $encryption use ImapClient::ENCRYPT_SSL or ImapClient::ENCRYPT_TLS
Returns
void
Definition at line 175 of file ImapClient.php.
     {
         $connect = new ImapConnect();
         if($encryption === ImapClient::ENCRYPT_SSL){
             $connect->prepareFlags(ImapConnect::SERVICE_IMAP, ImapConnect::ENCRYPT_SSL, ImapConnect::NOVALIDATE_CERT);
         };
         if($encryption === ImapClient::ENCRYPT_TLS){
             $connect->prepareFlags(ImapConnect::SERVICE_IMAP, ImapConnect::ENCRYPT_TLS, ImapConnect::NOVALIDATE_CERT);
         };
         $connect->prepareMailbox($mailbox);
         $connect->connect(null, $username, $password);
         $this->imap = $connect->getImap();
         $this->mailbox = $connect->getMailbox();
     }
References SSilence\ImapClient\ImapClient\$connect, $encryption, SSilence\ImapClient\ImapClient\$mailbox, $password, $username, SSilence\ImapClient\ImapClient\ENCRYPT_SSL, SSilence\ImapClient\ImapConnect\ENCRYPT_SSL, SSilence\ImapClient\ImapClient\ENCRYPT_TLS, SSilence\ImapClient\ImapConnect\ENCRYPT_TLS, SSilence\ImapClient\ImapConnect\NOVALIDATE_CERT, and SSilence\ImapClient\ImapConnect\SERVICE_IMAP.
Referenced by SSilence\ImapClient\ImapClient\__construct().
convertToUtf8()
SSilence\ImapClient\ImapClient::convertToUtf8 ($str)
Convert to utf8 if necessary.
Parameters
string $str utf8 encoded string
Returns
bool
Definition at line 1141 of file ImapClient.php.
{
         if (mb_detect_encoding($str, "UTF-8, ISO-8859-1, GBK")!="UTF-8") {
             $str = utf8_encode($str);
         }
         $str = iconv('UTF-8', 'UTF-8//IGNORE', $str);
         return $str;
     }
Referenced by SSilence\ImapClient\ImapClient\toAddress().
countMessages()
SSilence\ImapClient\ImapClient::countMessages ()
Returns the number of messages in the current folder
Returns
int message count
Definition at line 419 of file ImapClient.php.
     {
         return imap_num_msg($this->imap);
     }
Referenced by SSilence\ImapClient\ImapClient\checkMessageId(), and SSilence\ImapClient\ImapClient\getMessages().
countUnreadMessages()
SSilence\ImapClient\ImapClient::countUnreadMessages ()
Returns the number of unread messages in the current folder
Returns
integer Message count
Definition at line 451 of file ImapClient.php.
{
         $result = imap_search($this->imap, 'UNSEEN');
         if ($result === false) {
             return 0;
         }
         return count($result);
     }
References $result.
deleteMessage()
SSilence\ImapClient\ImapClient::deleteMessage ($id)
Delete the given message
Parameters
int $id of the message
Returns
bool success or not
Definition at line 745 of file ImapClient.php.
     {
         return $this->deleteMessages(array($id));
     }
References $id, and SSilence\ImapClient\ImapClient\deleteMessages().
deleteMessages()
SSilence\ImapClient\ImapClient::deleteMessages ($ids)
Delete messages
Returns
bool success or not
Parameters
$ids array of ids
Definition at line 756 of file ImapClient.php.
     {
         foreach ($ids as $id) {
             imap_delete($this->imap, $id, FT_UID);
         };
         return imap_expunge($this->imap);
     }
References $id, and as.
Referenced by SSilence\ImapClient\ImapClient\deleteMessage().
getBriefInfoMessages()
SSilence\ImapClient\ImapClient::getBriefInfoMessages ()
Returns an array of brief information about each message in the current mailbox.
Returns the following structure of the array of arrays.
$array = [
    [ 'id'=>4, 'info'=>'brief info' ]
    [ 'id'=>5, 'info'=>'brief info' ]
]
Returns
array
Definition at line 436 of file ImapClient.php.
     {
         $array = imap_headers($this->imap);
         $newArray = [];
         foreach ($array as $key => $string) {
             $newArray[] = ['id'=>$key+1, 'info' => $string];
         };
         return $newArray;
     }
References as.
getEncoding()
SSilence\ImapClient\ImapClient::getEncoding ($id) protected
Identify encoding by charset attribute in header
Parameters
$id
Returns
string
Definition at line 1155 of file ImapClient.php.
     {
         $header = $this->imapFetchStructure($id);
         $params = $header->parameters ?: [];
             foreach ($params as $k => $v) {
                 if (stristr($v->attribute, 'charset')) {
                     return $v->value;
                 }
             }
         return 'utf-8';
     }
References $header, $id, as, and SSilence\ImapClient\ImapClient\imapFetchStructure().
getError()
SSilence\ImapClient\ImapClient::getError ()
Returns the last imap error
Returns
string error message
Definition at line 344 of file ImapClient.php.
     {
         return imap_last_error();
     }
getFolders()
SSilence\ImapClient\ImapClient::getFolders ($separator = null, $type = 0)
Returns all available folders
Parameters
string $separator default is '.'
integer $type has three meanings 0,1,2. If 0 return nested array, if 1 return an array of strings, if 2 return raw imap_list()
Returns
array with folder names
Definition at line 373 of file ImapClient.php.
     {
         if(preg_match( '/^{.+}/', $this->mailbox, $matches)){
             $mailbox = $matches[0];
         }else{
             $mailbox = $this->mailbox;
         };
         $folders = imap_list($this->imap, $mailbox, "*");
         if ($type == 2) {
             return $folders;
         };
         if ($type == 1) {
             return str_replace($mailbox, "", $folders);
         };
         if ($type == 0) {
             $arrayRaw = str_replace($mailbox, "", $folders);
             if (!isset($separator)) {
                 $separator = '.';
             };
             $arrayNew = [];
             foreach ($arrayRaw as $string) {
                 $array = explode($separator, $string);
                 $count = count($array);
                 $count = $count-1;
                 $cache = false;
                 for($i=$count; $i>=0; $i--){
                     if($i == $count){
                         $cache = [$array[$i]=>[]];
                     }else{
                         $cache = [$array[$i] => $cache];
                     };
                 };
                 $arrayNew = array_merge_recursive($arrayNew, $cache);
             };
             return $arrayNew;
         }
         return null;
     }
References $i, SSilence\ImapClient\ImapClient\$mailbox, $type, and as.
Referenced by SSilence\ImapClient\ImapClient\getSent(), and SSilence\ImapClient\ImapClient\getTrash().
getId()
SSilence\ImapClient\ImapClient::getId ($uid)
Get id from uid
Parameters
int $uid
Returns
integer
Definition at line 1234 of file ImapClient.php.
     {
         return imap_msgno($this->imap, $uid);
     }
References $uid.
getImap()
SSilence\ImapClient\ImapClient::getImap ()
Get the imap resource
Returns
resource
Definition at line 116 of file ImapClient.php.
     {
         return $this->imap;
     }
References SSilence\ImapClient\ImapClient\$imap.
getImapConnection()
SSilence\ImapClient\ImapClient::getImapConnection ()
Get the imap connection
$return imap
Definition at line 146 of file ImapClient.php.
{
         return $this->imap;
     }
References SSilence\ImapClient\ImapClient\$imap.
getMailboxStatistics()
SSilence\ImapClient\ImapClient::getMailboxStatistics ()
Return general mailbox statistics
Returns
bool|resource object
Definition at line 1172 of file ImapClient.php.
     {
         return $this->isConnected() ? imap_mailboxmsginfo($this->imap) : false ;
     }
References SSilence\ImapClient\ImapClient\isConnected().
getMessage()
SSilence\ImapClient\ImapClient::getMessage ($id, $decode = IncomingMessage::DECODE)
Returns one email by given id
Examples:
Structure
$imap = new ImapClient();
$imap->getMessage(5);
You can see all structure that
var_dump($imap->incomingMessage)
But use like this
$imap->incomingMessage->header->subject
$imap->incomingMessage->header->from
$imap->incomingMessage->header->to
# cc or bcc
$imap->incomingMessage->header->details->cc
$imap->incomingMessage->header->details->bcc
# and other ...
var_dump($imap->incomingMessage->header)
Next Text or Html body
$imap->incomingMessage->message->html
$imap->incomingMessage->message->plain
# below is array
$imap->incomingMessage->message->info
Array attachments
$imap->incomingMessage->attachment
Attachment have structure and body
$imap->incomingMessage->attachment[0]
$imap->incomingMessage->attachment[0]->structure
$imap->incomingMessage->attachment[0]->body
Count section
$imap->incomingMessage->section
And structure all message
$imap->incomingMessage->structure
Save all attachments
$imap->getMessage(5);
$imap->saveAttachments();
See also
IncomingMessage
Parameters
integer $id
string $decode IncomingMessage::DECODE or IncomingMessage::NOT_DECODE
Returns
object IncomingMessage
Definition at line 677 of file ImapClient.php.
     {
         $this->checkMessageId($id);
         $this->incomingMessage = new IncomingMessage($this->imap, $id, $decode);
         return $this->incomingMessage;
     }
References $id, SSilence\ImapClient\ImapClient\$incomingMessage, and SSilence\ImapClient\ImapClient\checkMessageId().
Referenced by SSilence\ImapClient\ImapClient\getMessages(), SSilence\ImapClient\ImapClient\getMessagesByCriteria(), SSilence\ImapClient\ImapClient\getUnreadMessages(), and SSilence\ImapClient\ImapClient\saveAttachmentsMessagesBySubject().
getMessageHeader()
SSilence\ImapClient\ImapClient::getMessageHeader ($id)
Fetch message by id
Parameters
integer $id of the message
Returns
object|false header
Definition at line 1024 of file ImapClient.php.
     {
         return $this->imapHeaderInfo($id);
     }
References $id, and SSilence\ImapClient\ImapClient\imapHeaderInfo().
getMessageOverview()
SSilence\ImapClient\ImapClient::getMessageOverview ($id, $options = null)
Get message overview
See also
ImapClient::imapFetchOverview()
Parameters
integer $id
null $options
Returns
object
Definition at line 1037 of file ImapClient.php.
     {
         $array = $this->imapFetchOverview($id, $options);
         return $array[0];
     }
References $id, $options, and SSilence\ImapClient\ImapClient\imapFetchOverview().
getMessages()
SSilence\ImapClient\ImapClient::getMessages ($number = 0, $start = 0, $order = 'DESC', $filter = 'ALL')
Get messages
Parameters
int $number Number of messages. 0 to get all
int $start Starting message number
string $order ASC or DESC
string $filter ALL, SEEN, UNSEEN....
Returns
array IncomingMessage of objects
Definition at line 570 of file ImapClient.php.
     {
         if ($number == 0)
         {
             $number = $this->countMessages();
         }
         if (!isset($start) || (empty($start)))
         {
             $start = 0;
         }
         $emails = array();
         $result = imap_search($this->imap, $filter);
         if ($result)
         {
             $ids = array();
             foreach ($result as $k => $i)
             {
                 $ids[] = $i;
             }
             if ($order == 'DESC')
             {
                 $ids = array_reverse($ids);
             }
             if (count($ids) > $number) {
                 $ids = array_chunk($ids, $number);
                 $ids = $ids[$start];
             }
             if (isset($ids)) {
                 foreach ($ids as $id) {
                     $emails[] = $this->getMessage($id);
                 }
             }
         }
         return $emails;
     }
References $i, $id, $result, as, SSilence\ImapClient\ImapClient\countMessages(), and SSilence\ImapClient\ImapClient\getMessage().
getMessagesByCriteria()
SSilence\ImapClient\ImapClient::getMessagesByCriteria ($criteria = '', $number = 0, $start = 0, $order = 'DESC')
Get Messages by Criteria
See also
http://php.net/manual/en/function.imap-search.php
Parameters
string $criteria ALL, UNSEEN, FLAGGED, UNANSWERED, DELETED, UNDELETED, etc (e.g. FROM "joey smith")
int $number
int $start
string $order
Returns
array
Exceptions
ImapClientException
Definition at line 501 of file ImapClient.php.
     {
         $emails = array();
         $result = imap_search($this->imap, $criteria);
         if(!$result){
             throw new ImapClientException('Messages not found. Or this criteria not supported on your email server.');
         };
         if ($number == 0)
         {
             $number = count($result);
         }
         if ($result)
         {
             $ids = array();
             foreach ($result as $k => $i)
             {
                 $ids[] = $i;
             }
             $ids = array_chunk($ids, $number);
             $ids = array_slice($ids[0], $start, $number);
             $emails = array();
             foreach ($ids as $id)
             {
                 $emails[] = $this->getMessage($id);
             }
         }
         if ($order == 'DESC')
         {
             $emails = array_reverse($emails);
         }
         return $emails;
     }
References $i, $id, $result, as, and SSilence\ImapClient\ImapClient\getMessage().
getMessagesOverview()
SSilence\ImapClient\ImapClient::getMessagesOverview ($id, $options = null)
Get messages overview
Parameters
string $id
null $options
Returns
array
Definition at line 1050 of file ImapClient.php.
     {
         return $this->imapFetchOverview($id, $options);
     }
References $id, $options, and SSilence\ImapClient\ImapClient\imapFetchOverview().
getQuota()
SSilence\ImapClient\ImapClient::getQuota ($mailbox)
Retrieve the quota level settings, and usage statics per mailbox.
Parameters
string $mailbox
Returns
array
Definition at line 1198 of file ImapClient.php.
     {
         $quota = imap_get_quota($this->imap, "user.".$mailbox);
         return $quota;
     }
References SSilence\ImapClient\ImapClient\$mailbox.
getQuotaRoot()
SSilence\ImapClient\ImapClient::getQuotaRoot ($mailbox)
Retrieve the quota level settings, and usage statics per mailbox.
Parameters
string $mailbox
Returns
array
Definition at line 1211 of file ImapClient.php.
     {
         $quota = imap_get_quotaroot($this->imap, "user.".$mailbox);
         return $quota;
     }
References SSilence\ImapClient\ImapClient\$mailbox.
getSection()
SSilence\ImapClient\ImapClient::getSection ($id, $section)
Get a section of the message
Parameters
integer $id
string $section
Returns
object
Definition at line 691 of file ImapClient.php.
     {
         $incomingMessage = new IncomingMessage($this->imap, $id);
         return $incomingMessage->getSection($section);
     }
References $id, and SSilence\ImapClient\ImapClient\$incomingMessage.
getSent()
SSilence\ImapClient\ImapClient::getSent () protected
Get sent
Returns
string sent folder name
Definition at line 1005 of file ImapClient.php.
     {
         foreach ($this->getFolders(null, 1) as $folder) {
             if (in_array(strtolower($folder), array('sent', 'gesendet', 'inbox.gesendet'))) {
                 return $folder;
             }
         }
         // no sent folder found? create one
         $this->addFolder('Sent');
         return 'Sent';
     }
References SSilence\ImapClient\ImapClient\$folder, SSilence\ImapClient\ImapClient\addFolder(), as, and SSilence\ImapClient\ImapClient\getFolders().
Referenced by SSilence\ImapClient\ImapClient\saveMessageInSent().
getTrash()
SSilence\ImapClient\ImapClient::getTrash () protected
Get trash folder
Returns
string trash folder name
Definition at line 987 of file ImapClient.php.
     {
         foreach ($this->getFolders(null, 1) as $folder) {
             if (in_array(strtolower($folder), array('trash', 'inbox.trash', 'papierkorb'))) {
                 return $folder;
             }
         }
         // no trash folder found? create one
         $this->addFolder('Trash');
         return 'Trash';
     }
References SSilence\ImapClient\ImapClient\$folder, SSilence\ImapClient\ImapClient\addFolder(), as, and SSilence\ImapClient\ImapClient\getFolders().
Referenced by SSilence\ImapClient\ImapClient\purge().
getUid()
SSilence\ImapClient\ImapClient::getUid ($id)
Get uid from id
Parameters
integer $id
Returns
integer
Definition at line 1223 of file ImapClient.php.
     {
         return imap_uid($this->imap, $id);
     }
References $id.
getUnreadMessages()
SSilence\ImapClient\ImapClient::getUnreadMessages ($read = true)
Returns unseen emails in the current folder
Parameters
bool $read Mark message like SEEN or no.
Returns
array objects IncomingMessage
Exceptions
ImapClientException
Definition at line 466 of file ImapClient.php.
{
         $emails = [];
         $result = imap_search($this->imap, 'UNSEEN');
         if(!$result){
             throw new ImapClientException('No read messages were found.');
         };
         $ids = ''; $countId = count($result);
         foreach($result as $key=>$id) {
             $emails[]= $this->getMessage($id);
             if(($countId-1) == $key){
                 $ids .= $id;
             }else{
                 $ids .= $id.',';
             };
         }
         /* Set flag UNSEEN */
         if(!$read){
             $this->setUnseenMessage($ids);
         }else{
             $this->setSeenMessage($ids);
         };
         return $emails;
     }
References $id, $result, as, SSilence\ImapClient\ImapClient\getMessage(), SSilence\ImapClient\ImapClient\setSeenMessage(), and SSilence\ImapClient\ImapClient\setUnseenMessage().
imapFetchOverview()
SSilence\ImapClient\ImapClient::imapFetchOverview ($sequence, $options = null)
Wrapper for php imap_fetch_overview()
See also
http://php.net/manual/ru/function.imap-fetch-overview.php
Parameters
string $sequence a message sequence description, you can enumerate desired messages with the X,Y syntax, or retrieve all messages within an interval with the X:Y syntax
int $options sequence will contain a sequence of message indices or UIDs, if this parameter is set to FT_UID.
Returns
array
Definition at line 1066 of file ImapClient.php.
     {
         return imap_fetch_overview($this->imap, $sequence, $options);
     }
References $options.
Referenced by SSilence\ImapClient\ImapClient\getMessageOverview(), and SSilence\ImapClient\ImapClient\getMessagesOverview().
imapFetchStructure()
SSilence\ImapClient\ImapClient::imapFetchStructure ($id)
Wrapper for imap_fetchstructure()
See also
http://php.net/manual/ru/function.imap-fetchstructure.php
Parameters
integer $id
Returns
object
Definition at line 1091 of file ImapClient.php.
     {
         return imap_fetchstructure($this->imap, $id);
     }
References $id.
Referenced by SSilence\ImapClient\ImapClient\getEncoding().
imapHeaderInfo()
SSilence\ImapClient\ImapClient::imapHeaderInfo ($id)
Wrapper for php imap_headerinfo()
See also
http://php.net/manual/ru/function.imap-headerinfo.php
http://php.net/manual/en/function.imap-headerinfo.php#98809
Parameters
integer $id
Returns
object|false
Definition at line 1079 of file ImapClient.php.
     {
         return imap_rfc822_parse_headers(imap_fetchheader($this->imap, $id));
     }
References $id.
Referenced by SSilence\ImapClient\ImapClient\getMessageHeader().
isConnected()
SSilence\ImapClient\ImapClient::isConnected ()
Returns true after successful connection
Returns
bool true on success
Definition at line 232 of file ImapClient.php.
     {
         return $this->imap !== false;
     }
Referenced by SSilence\ImapClient\ImapClient\getMailboxStatistics().
moveMessage()
SSilence\ImapClient\ImapClient::moveMessage ($id, $target)
Move given message in new folder
Parameters
int $id of the message
string $target new folder
Returns
bool success or not
Definition at line 771 of file ImapClient.php.
     {
         return $this->moveMessages(array($id), $target);
     }
References $id, and SSilence\ImapClient\ImapClient\moveMessages().
moveMessages()
SSilence\ImapClient\ImapClient::moveMessages ($ids, $target)
Move given message in new folder
Parameters
array $ids array of message ids
string $target new folder
Returns
bool success or not
Definition at line 783 of file ImapClient.php.
     {
         if (imap_mail_move($this->imap, implode(",", $ids), $target, CP_UID) === false)
             return false;
         return imap_expunge($this->imap);
     }
Referenced by SSilence\ImapClient\ImapClient\moveMessage().
purge()
SSilence\ImapClient\ImapClient::purge ()
Clean up trash AND spam folder
Returns
bool success or not
Definition at line 860 of file ImapClient.php.
     {
         // delete trash and spam
         if ($this->folder==$this->getTrash() || strtolower($this->folder)=="spam") {
             if (imap_delete($this->imap,'1:*') === false) {
                 return false;
             }
             return imap_expunge($this->imap);
             // move others to trash
         } else {
             if (imap_mail_move($this->imap,'1:*', $this->getTrash()) == false) {
                 return false;
             }
             return imap_expunge($this->imap);
         }
     }
References SSilence\ImapClient\ImapClient\getTrash().
removeFolder()
SSilence\ImapClient\ImapClient::removeFolder ($name)
Remove a folder
Parameters
string $name of the folder
Returns
bool success or not
Definition at line 838 of file ImapClient.php.
     {
         return imap_deletemailbox($this->imap, $this->mailbox . $name);
     }
References $name.
renameFolder()
SSilence\ImapClient\ImapClient::renameFolder ($name, $newname)
Rename a folder
Parameters
string $name of the folder
string $newname of the folder
Returns
bool success or not
Definition at line 850 of file ImapClient.php.
     {
         return imap_renamemailbox($this->imap, $this->mailbox . $name, $this->mailbox . $newname);
     }
References $name.
saveAttachments()
SSilence\ImapClient\ImapClient::saveAttachments ($options = null)
Save attachments one incoming message
The allowed types are TypeAttachments You can add your own
Parameters
array $options have next parameters
# it is directory for save attachments
$options['dir']
# it is incomingMessage object
$options['incomingMessage']
Returns
void
Definition at line 712 of file ImapClient.php.
     {
         if(!isset($options['dir'])){
             $dir = __DIR__.DIRECTORY_SEPARATOR;
         }else{
             $dir = $options['dir'];
         };
         if(!isset($options['incomingMessage'])){
             $incomingMessage = $this->incomingMessage;
         }else{
             $incomingMessage = $options['incomingMessage'];
         };
         foreach ($incomingMessage->attachments as $key => $attachment) {
             $newFileName = $attachment->name;
             if (file_put_contents($dir.DIRECTORY_SEPARATOR.$newFileName, base64_decode($attachment->body)) == false)
             {
                 // return false;
             }
             else
                 {
                     // return true;
                 }
         }
     }
References SSilence\ImapClient\ImapClient\$incomingMessage, $options, and as.
Referenced by SSilence\ImapClient\ImapClient\saveAttachmentsMessagesBySubject().
saveAttachmentsMessagesBySubject()
SSilence\ImapClient\ImapClient::saveAttachmentsMessagesBySubject ($subject, $dir = null, $charset = null)
Save Attachments Messages By Subject
Parameters
string $subject
string $dir for save attachments
string $charset for search
Returns
void
Exceptions
ImapClientException
Definition at line 545 of file ImapClient.php.
     {
         $criteria = 'SUBJECT "'.$subject.'"';
         $ids = imap_search($this->imap, $criteria, null, $charset);
         if(!$ids){
             throw new ImapClientException('Messages not found. Or this criteria not supported on your email server.');
         };
         foreach ($ids as $id) {
             $this->getMessage($id);
             if(isset($dir)){
                 $dir = ['dir'=>$dir];
             };
             $this->saveAttachments($dir);
         };
     }
References $id, as, SSilence\ImapClient\ImapClient\getMessage(), and SSilence\ImapClient\ImapClient\saveAttachments().
saveEmail()
SSilence\ImapClient\ImapClient::saveEmail ($file = null, $id = null, $part = null)
Saves the email into a file Note: If your server does not have alot of RAM, this may break
Parameters
string $file
integer $id
string $part
Returns
bool true on success
Exceptions
ImapClientException
Definition at line 247 of file ImapClient.php.
      {
          // Null checks
          if($file === null)
          {
              throw new ImapClientException('File must be specified for saveEmail()');
          }
          if($id === null)
          {
              throw new ImapClientException('Email id must be specified for saveEmail()');
          }
          if($part === null)
          {
              $parts = false;
          }
          else {
              $parts = true;
          }
          // Is type checks
          if(!is_string($file))
          {
              throw new ImapClientException('File must be a string for saveEmail()');
          }
          if(!is_int($id))
          {
              throw new ImapClientException('$id must be a integer for saveEmail()');
          }
          $saveFile = fopen($file,'w');
          if($parts)
          {
              $ret = imap_savebody($this->imap, $saveFile, $id, $part);
          }
          else {
              $ret = imap_savebody($this->imap, $saveFile, $id);
          }
          fclose($saveFile);
          return $ret;
      }
References $id.
saveEmailSafe()
SSilence\ImapClient\ImapClient::saveEmailSafe ($file = null, $id = null, $part = null, $streamFilter = 'convert.base64-decode')
Saves the email into a file Note: This is safer then saveEmail for slower servers
Parameters
string $file
integer $id
string $part
string $streamFilter
Returns
bool true on success
Exceptions
ImapClientException
Definition at line 298 of file ImapClient.php.
       {
           // Null checks
           if($file === null)
           {
               throw new ImapClientException('File must be specified for saveEmailSafe()');
           }
           if($id === null)
           {
               throw new ImapClientException('Email id must be specified for saveEmailSafe()');
           }
           if($part === null)
           {
               $parts = false;
           }
           else {
               $parts = true;
           }
           // Is type checks
           if(!is_string($file))
           {
               throw new ImapClientException('File must be a string for saveEmailSafe()');
           }
           if(!is_int($id))
           {
               throw new ImapClientException('$id must be a integer for saveEmailSafe()');
           }
           $saveFile = fopen($file,'w');
           stream_filter_append($saveFile, $streamFilter, STREAM_FILTER_WRITE);
           if($parts)
           {
               $ret = imap_savebody($this->imap, $saveFile, $id, $part);
           }
           else {
               $ret = imap_savebody($this->imap, $saveFile, $id);
           };
           fclose($saveFile);
           return $ret;
       }
References $id.
saveMessageInSent()
SSilence\ImapClient\ImapClient::saveMessageInSent ($header, $body)
Save email in sent
Parameters
string $header
string $body
Returns
bool
Definition at line 969 of file ImapClient.php.
{
         return imap_append($this->imap, $this->mailbox . $this->getSent(), $header . "\r\n" . $body . "\r\n", "\\Seen");
     }
References $header, and SSilence\ImapClient\ImapClient\getSent().
selectFolder()
SSilence\ImapClient\ImapClient::selectFolder ($folder)
Select the given folder folder and set $this->folder
Parameters
string $folder name
Returns
bool successful opened folder
Definition at line 356 of file ImapClient.php.
     {
         $result = imap_reopen($this->imap, $this->mailbox . $folder);
         if ($result === true) {
             $this->folder = $folder;
         }
         return $result;
     }
References SSilence\ImapClient\ImapClient\$folder, and $result.
sendMail()
SSilence\ImapClient\ImapClient::sendMail ()
Send an email
Returns
void
Definition at line 1244 of file ImapClient.php.
     {
         $outMessage = new AdapterForOutgoingMessage(self::$connectConfig);
         $outMessage->send();
     }
setConnectAdvanced()
static SSilence\ImapClient\ImapClient::setConnectAdvanced () static
Set connection to advanced
Returns
void
Definition at line 126 of file ImapClient.php.
     {
         static::$connect = self::CONNECT_ADVANCED;
     }
References SSilence\ImapClient\ImapClient\CONNECT_ADVANCED.
Referenced by SSilence\ImapClient\ImapClient\__construct().
setConnectConfig()
static SSilence\ImapClient\ImapClient::setConnectConfig (array $config) static
Set connection config
Parameters
array $config
Returns
void
Definition at line 156 of file ImapClient.php.
     {
         static::$connectConfig = $config;
     }
Referenced by SSilence\ImapClient\ImapClient\__construct().
setConnectDefault()
static SSilence\ImapClient\ImapClient::setConnectDefault () static
Set connection to default
Returns
void
Definition at line 136 of file ImapClient.php.
     {
         static::$connect = self::CONNECT_DEFAULT;
     }
References SSilence\ImapClient\ImapClient\CONNECT_DEFAULT.
Referenced by SSilence\ImapClient\ImapClient\__construct().
setSeenMessage()
SSilence\ImapClient\ImapClient::setSeenMessage ($ids)
Set flag message SEEN
Parameters
int $ids or string like 1,2,3,4,5 or string like 1:5
Returns
bool
Definition at line 796 of file ImapClient.php.
     {
         // We need better docs for this
         return imap_setflag_full($this->imap, $ids, "\\Seen");
     }
Referenced by SSilence\ImapClient\ImapClient\getUnreadMessages().
setUnseenMessage()
SSilence\ImapClient\ImapClient::setUnseenMessage ($ids)
Delete flag message SEEN
Parameters
int $ids or string like 1,2,3,4,5 or string like 1:5
Returns
bool
Definition at line 808 of file ImapClient.php.
     {
         // We need better docs for this
         return imap_clearflag_full($this->imap, $ids, "\\Seen");
     }
Referenced by SSilence\ImapClient\ImapClient\getUnreadMessages().
toAddress()
SSilence\ImapClient\ImapClient::toAddress ($headerinfos) protected
Convert imap given address into string
Parameters
object $headerinfos the infos given by imap
Returns
string in format "Name <email@bla.de>"
Definition at line 1102 of file ImapClient.php.
{
         $email = "";
         $name = "";
         if (isset($headerinfos->mailbox) && isset($headerinfos->host)) {
             $email = $headerinfos->mailbox . "@" . $headerinfos->host;
         }
         if (!empty($headerinfos->personal)) {
             $name = imap_mime_header_decode($headerinfos->personal);
             $name = $name[0]->text;
         } else {
             $name = $email;
         }
         $name = $this->convertToUtf8($name);
         return $name . " <" . $email . ">";
     }
References $email, $name, and SSilence\ImapClient\ImapClient\convertToUtf8().
Referenced by SSilence\ImapClient\ImapClient\arrayToAddress().
unSubscribe()
SSilence\ImapClient\ImapClient::unSubscribe ()
Unsubscribe from a mail box
Returns
bool
Definition at line 1181 of file ImapClient.php.
     {
         if (imap_unsubscribe($this->imap, $this->mailbox)) {
             return true;
         }
         else {
             return false;
         }
     }
Member Data Documentation
$connect
SSilence\ImapClient\ImapClient::$connect static
Definition at line 34 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\connectAdvanced(), and SSilence\ImapClient\ImapClient\connectDefault().
$connectConfig
SSilence\ImapClient\ImapClient::$connectConfig static
Definition at line 48 of file ImapClient.php.
$connection
SSilence\ImapClient\ImapClient::$connection
Definition at line 41 of file ImapClient.php.
$currentFolder
SSilence\ImapClient\ImapClient::$currentFolder
Definition at line 55 of file ImapClient.php.
$folder
SSilence\ImapClient\ImapClient::$folder = "INBOX" protected
Definition at line 83 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\getSent(), SSilence\ImapClient\ImapClient\getTrash(), and SSilence\ImapClient\ImapClient\selectFolder().
$imap
SSilence\ImapClient\ImapClient::$imap protected
Definition at line 69 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\getImap(), and SSilence\ImapClient\ImapClient\getImapConnection().
$incomingMessage
SSilence\ImapClient\ImapClient::$incomingMessage
Definition at line 62 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\getMessage(), SSilence\ImapClient\ImapClient\getSection(), and SSilence\ImapClient\ImapClient\saveAttachments().
$mailbox
SSilence\ImapClient\ImapClient::$mailbox = "" protected
Definition at line 76 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\__construct(), SSilence\ImapClient\ImapClient\connectDefault(), SSilence\ImapClient\ImapClient\getFolders(), SSilence\ImapClient\ImapClient\getQuota(), and SSilence\ImapClient\ImapClient\getQuotaRoot().
CONNECT_ADVANCED
const SSilence\ImapClient\ImapClient::CONNECT_ADVANCED = 'connectAdvanced'
Definition at line 26 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\setConnectAdvanced().
CONNECT_DEFAULT
const SSilence\ImapClient\ImapClient::CONNECT_DEFAULT = 'connectDefault'
Definition at line 27 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\setConnectDefault().
ENCRYPT_SSL
const SSilence\ImapClient\ImapClient::ENCRYPT_SSL = 'ssl'
Use the Secure Socket Layer to encrypt the session
Definition at line 20 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\connectDefault().
ENCRYPT_TLS
const SSilence\ImapClient\ImapClient::ENCRYPT_TLS = 'tls'
Force use of start-TLS to encrypt the session, and reject connection to servers that do not support it
Definition at line 25 of file ImapClient.php.
Referenced by SSilence\ImapClient\ImapClient\connectDefault().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/imapClient/ImapClient.php