YaWK: YAWK\BACKUP\DATABASE\mysqlBackup Class Reference
YAWK\BACKUP\DATABASE\mysqlBackup Class Reference
Public Member Functions
doSqlBackup ($db)
Start mysqldump and check if .sql file exists. Zip it afterwards if enabled.
excludeTables ($excludeTables)
Exclude tables from backup.
generateZipArchive ($db, $sqlBackup)
ZIP Archive method generates a zip archive from .sql file.
getDatabaseConfig ()
Get current database config.
getHashValue ($db)
get hash value from .sql backup file
includeMysqldumpClass ($db)
Include mysqldump-php and create new dump object.
includeTables ($includeTables)
Include only this tables into backup.
initMysqlBackup ($db, $overwriteBackup, $zipBackup, $storeSqlTmp)
Initialize this database backup class.
setDumpSettings ()
Set mysqldump settings.
sqlFileExists ()
Check if .sql backup file exists.
startMysqlBackup ($db)
Start and manage mysql backup routine.
Public Member Functions inherited from YAWK\BACKUP\backup
__construct ($db)
backup constructor. prepare temp folder on class instantiation
checkFolders ($restoreFolders)
check restore folders, check + set permissions of restore folders
checkPermissions ($folder)
check folder permissions and return permissions as string (eg 0755)
checkZipFunction ()
Check if ZipArchive function exists.
doRestore ($db, $restoreFolders)
Restore Data physically to folder, restore .sql file to database if needed.
getArchiveBackupFilesArray ()
get all files from archive backup folder into array
getCurrentBackupFilesArray ()
get all files from current backup folder into array
init ($db)
Init Backup Class (run backup)
parseIniFile ($db, $iniFile)
Parse backup ini file.
restore ($db, $file, $folder)
Manage how a backup will be restored from backup folder.
run ($db)
Run a new backup, depending on chosen backup method.
runDatabaseBackup ($db, $storeSqlTmp)
Include mysql backup class and run mysqldump backup.
runFileBackup ($db)
Run File Backup from $sourceFolder.
setIniFile (object $db)
Set backup information file (backup.ini)
setPermissions ($folder, $filemode)
set folder permissions and do some chmod stuff to with given $filemode to $folder
zipFolder ($db, $source, $destination)
Zip a whole folder from $source to $destination.zip.
Public Attributes
$backupMode = 'include'
$backupSqlFile = 'database-backup.sql'
$dumpSettings = array()
$excludeTablesArray = array()
$hashValue = ''
$includeTablesArray = array()
$mysqldump
$sqlBackup = ''
$sqlPath = '../system/backup/current/'
$zip
Public Attributes inherited from YAWK\BACKUP\backup
$archiveBackupFile = ''
$archiveBackupFiles = array()
$archiveBackupFolder = '../system/backup/archive/'
$archiveBackupNewFile = ''
$archiveBackupSubFolder = ''
$archiveBackupSubFolders = array()
$backupMethod = "database"
$backupSettings = array()
$configFile = ''
$configFilename = "backup.ini"
$currentBackupFiles = array()
$currentBackupFolder = '../system/backup/current/'
$downloadFolder = '../system/backup/download/'
$fileBackup
$mysqlBackup
$overwriteBackup = "true"
$removeAfterZip = "true"
$restoreFile = ''
$restoreFiles = array()
$restoreFolder = ''
$restoreFolders = array()
$restoreMode = ''
$restoreStatus = array()
$sourceFolder = ''
$storeSqlTmp = "false"
$targetFolder = '../system/backup/current/'
$tmpFolder = '../system/backup/tmp/'
$zipBackup = "true"
Private Attributes
$config
$dbname
$host
$pass
$port
$prefix
$user
Detailed Description
Definition at line 23 of file backup-mysqlBackup.php.
Member Function Documentation
doSqlBackup()
YAWK\BACKUP\DATABASE\mysqlBackup::doSqlBackup ($db)
Start mysqldump and check if .sql file exists. Zip it afterwards if enabled.
return bool if $this->sqlBackup exists
Returns
bool true|false
Definition at line 311 of file backup-mysqlBackup.php.
         {
             // check if .sql file should be stored in tmp folder...
             if (isset($this->storeSqlTmp) && ($this->storeSqlTmp == "true"))
             {   // check if subdir database exists
                 if (is_writeable($this->tmpFolder))
                 {   // check if tmp subdir (database) exists...
                     if (!is_dir($this->tmpFolder."database"))
                     {   // if not, create it
                         mkdir($this->tmpFolder."database");
                     }
                     // set sql path to temp folder
                     $this->sqlPath = $this->tmpFolder."database/";
                     // set whole sql backup file path + filename
                     $this->sqlBackup = $this->sqlPath.$this->backupSqlFile;
                 }
                 else
                     {
                         \YAWK\sys::setSyslog($db, 51, 1, "failed to create database backup: $this->tmpFolder is not writeable", 0, 0, 0, 0);
                         return false;
                     }
             }
             // check if .sql path is writeable
             if (is_writeable($this->sqlPath))
             {
                 // ok then...
                 try
                 {   // try to start backup
                     $this->mysqldump->start($this->sqlBackup, $this->dumpSettings);
                 }
                 // on fail: catch error
                 catch (Exception $e)
                 {
                     // output mysqldump error
                     \YAWK\sys::setSyslog($db, 52, 2, "".$e->getMessage()."", 0, 0, 0, 0);
                     // echo 'mysqldump-php error: ' . $e->getMessage();
                 }
                 // check if file exists
                 if ($this->sqlFileExists())
                 {
                     // ok, backup done
                     // add ini file
                     $this->backupSettings = $this->setBackupSettings($db);
                     if ($this->setIniFile($db) === true)
                     {
                         // backup ini file written
                     }
                     else
{
                             // set syslog entry: ini file not written
                             \YAWK\sys::setSyslog($db, 51, 1, "failed to write $this->configFile", 0, 0, 0, 0);
                         }
                     // check if .sql file should be zipped
                     if ($this->zipBackup == "true")
                     {
                         // generate zip archive
                         if ($this->generateZipArchive($db, $this->sqlBackup) === true)
{
                             // zip archive created
                             \YAWK\sys::setSyslog($db, 49, 0, "created database backup $this->sqlBackup", 0, 0, 0, 0);
                             return true;
                         }
                         else
                             {   // failed to create zip archive
                                 \YAWK\sys::setSyslog($db, 51, 1, "failed to create database zip archive", 0, 0, 0, 0);
                                 return false;
                             }
                     }
                     else
                         {   // zip backup diabled, no zip needed
                             return true;
                         }
                 }
                 else
                 {   // .sql file does not exist - backup failed?
                     return false;
                 }
             }
             else
                 {
                     \YAWK\sys::setSyslog($db, 51, 1, "failed to create database backup: $this->sqlPath is not writeable", 0, 0, 0, 0);
                     return false;
                 }
References $db, YAWK\BACKUP\DATABASE\mysqlBackup\generateZipArchive(), YAWK\BACKUP\backup\setIniFile(), and YAWK\BACKUP\DATABASE\mysqlBackup\sqlFileExists().
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup().
excludeTables()
YAWK\BACKUP\DATABASE\mysqlBackup::excludeTables ($excludeTables)
Exclude tables from backup.
Parameters
array $excludeTables array
Returns
array $this->dumpSettings
awaits an array with all tables that should be excluded
Definition at line 117 of file backup-mysqlBackup.php.
         {   // check if exclude tables are set
             if (isset($excludeTables) && (is_array($excludeTables) && (!empty($excludeTables))))
             {
                 // set excludeTables array
                 $this->excludeTablesArray = $excludeTables;
                 // walk through exclude tables array
                 foreach ($this->excludeTablesArray AS $exclude => $table)
                 {   // add exclude table to array
                     $this->dumpSettings['exclude-tables'][] = $table;
                 }
             }
             // check if dump settings array is set and not empty
             if (isset($this->dumpSettings['exclude-tables']) && (is_array($this->dumpSettings['exclude-tables']) && (!empty($this->dumpSettings['exclude-tables']))))
             {   // return dump settings array
                 return $this->dumpSettings;
             }
             else
                 {   // no tables set for inclusion - return empty array
                     return $this->dumpSettings['exclude-tables'] = array();
                 }
References YAWK\BACKUP\DATABASE\mysqlBackup\$dumpSettings.
generateZipArchive()
YAWK\BACKUP\DATABASE\mysqlBackup::generateZipArchive ($db, $sqlBackup)
ZIP Archive method generates a zip archive from .sql file.
Parameters
string $sqlBackup relative path + filename to the .sql backup file
zip the .sql file and return bool if zip archive exists
Returns
bool true|false
Definition at line 406 of file backup-mysqlBackup.php.
         {
             if ($this->zipBackup == "true")
             {   // check if ZipArchive class is available
                 if ($this->checkZipFunction() == true)
                 {
                     // ok, create new zip object
                     $zip = new \ZipArchive();
                     // get sql backup filename
                     if (isset($sqlBackup) && (!empty($sqlBackup) && (is_string($sqlBackup))))
                     {   // set this obj property
                         $this->sqlBackup = $sqlBackup;
                     }
                     // generate zip filename
                     $filename = $this->sqlBackup.".zip";
                     // open new zip archive
                     if ($zip->open($filename, \ZipArchive::CREATE) !== TRUE)
                     {   // failed to create new zip archive
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create new zip archive $filename", 0, 0, 0, 0);
                         return false;
                     }
                     // add .sql file to zip archive
                     $zip->addFile($this->sqlBackup,$this->backupSqlFile);
                     // check if there is a backup.ini / config file
                     if (is_file($this->sqlPath.$this->configFilename))
                     {   // add backup.ini config file to zip archive
                         $zip->addFile($this->sqlPath.$this->configFilename, $this->configFilename);
                     }
                     else
                         {   // backup config ini file not found
                             \YAWK\sys::setSyslog($db, 51, 2, "failed to add $this->configFilename to archive $filename", 0, 0, 0, 0);
                         }
                     // echo "numfiles: " . $zip->numFiles . "\n";
                     // echo "status:" . $zip->status . "\n";
                     // ok, close zip file
                     $zip->close();
                     // check if zip file exists
                     if (is_file($filename))
                     {
                         // zip file created
                         if ($this->removeAfterZip == "true")
                         {   // remove files
                             if (unlink ($this->sqlPath.$this->backupSqlFile)
                             && (unlink ($this->sqlPath.$this->configFilename)))
{
                                 return true;
                             }
                             else
                                 {   // unable to delete backup files after zipping
                                     \YAWK\sys::setSyslog($db, 51, 1, "failed to delete backup files after adding .zip archive $filename", 0, 0, 0, 0);
                                     return true;
                                 }
                         }
                         return true;
                     }
                     else
                     {   // zip file not created
                         \YAWK\sys::setSyslog($db, 51, 1, "failed to create .zip file: $filename", 0, 0, 0, 0);
                         return false;
                     }
                 }
                 else
                 {   // ZipArchive class not available
                     \YAWK\sys::setSyslog($db, 51, 1, "failed create .zip archive - PHP ZIP class not available. Ask your web hosting provider about that", 0, 0, 0, 0);
                     return false;
                 }
             }
             else
                 {   // zip not enabled due settings
                     return false;
                 }
References $db, $filename, YAWK\BACKUP\DATABASE\mysqlBackup\$sqlBackup, YAWK\BACKUP\DATABASE\mysqlBackup\$zip, and YAWK\BACKUP\backup\checkZipFunction().
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\doSqlBackup().
getDatabaseConfig()
YAWK\BACKUP\DATABASE\mysqlBackup::getDatabaseConfig ()
Get current database config.
Get mysql configuration and set settings as private properties
Definition at line 177 of file backup-mysqlBackup.php.
         {
             // get database configuration
             require ("../system/classes/dbconfig.php");
             // set configuration vars for mysqldump-php
             $this->host = $this->config['server'];
             $this->user = $this->config['username'];
             $this->pass = $this->config['password'];
             $this->dbname = $this->config['dbname'];
             $this->prefix = $this->config['prefix'];
             $this->port = $this->config['port'];
References config.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\includeMysqldumpClass().
getHashValue()
YAWK\BACKUP\DATABASE\mysqlBackup::getHashValue ($db)
get hash value from .sql backup file
Parameters
$db
Returns
bool|string
Definition at line 291 of file backup-mysqlBackup.php.
         {
             // check if sql backup file is accessable
             if (is_file($this->sqlBackup))
             {   // generate hash value
                 return $this->hashValue = hash_file('md5', $this->sqlBackup);
             }
             else
                 {   // sql backup file not found
                     // unable to generate hash value
                     \YAWK\sys::setSyslog($db, 52, 2, "failed to generate hash value - $this->sqlBackup not accessable", 0, 0, 0, 0);
                     return false;
                 }
References $db.
includeMysqldumpClass()
YAWK\BACKUP\DATABASE\mysqlBackup::includeMysqldumpClass ($db)
Include mysqldump-php and create new dump object.
Returns
bool true|false
Exceptions
Exception create new $this->mysqldump object Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com 1.0.0
Definition at line 199 of file backup-mysqlBackup.php.
         {
             // check if mysqldump class is there
             if (is_file('../system/engines/mysqldump/Mysqldump.php'))
             {
                 // ok, include class
                 require_once('../system/engines/mysqldump/Mysqldump.php');
                 // check if database tables form is set
                 if (isset($_POST['database']) && (!empty($_POST['database'])))
                 {
                     // walk through database tables array
                     foreach ($_POST['database'] as $table)
                     {
                         // store table in array
                         $this->includeTablesArray[] = $table;
                     }
                     // set tables to include
                     $this->dumpSettings = $this->includeTables($this->includeTablesArray);
                 }
                 else
                     {   // set default settings (dump all)
                         $this->setDumpSettings();
                     }
                 // load database config into this object
                 $this->getDatabaseConfig();
                 // create new mysqldump object
                 $this->mysqldump = new \Ifsnop\Mysqldump\Mysqldump("mysql:host=$this->host;dbname=$this->dbname", $this->user, $this->pass, $this->dumpSettings);
                 return true;
             }
             else
             {   // unable to include class
                 \YAWK\sys::setSyslog($db, 52, 2, "unable to backup: failed to include mysqldump class", 0, 0, 0, 0);
                 return false;
             }
References $db, YAWK\BACKUP\DATABASE\mysqlBackup\getDatabaseConfig(), YAWK\BACKUP\DATABASE\mysqlBackup\includeTables(), and YAWK\BACKUP\DATABASE\mysqlBackup\setDumpSettings().
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup().
includeTables()
YAWK\BACKUP\DATABASE\mysqlBackup::includeTables ($includeTables)
Include only this tables into backup.
Parameters
array $includeTables array
Returns
array $this->dumpSettings
awaits an array with all tables that should be included
Definition at line 148 of file backup-mysqlBackup.php.
         {   // check if include tables are set
             if (isset($includeTables) && (is_array($includeTables) && (!empty($includeTables))))
             {
                 // set includeTables array
                 $this->includeTablesArray = $includeTables;
                 // walk through include tables array
                 foreach ($this->includeTablesArray AS $include => $table)
                 {   // add include table to array
                     $this->dumpSettings['include-tables'][] = $table;
                 }
             }
             // check if dump settings array is set and not empty
             if (isset($this->dumpSettings['include-tables']) && (is_array($this->dumpSettings['include-tables']) && (!empty($this->dumpSettings['include-tables']))))
             {   // return dump settings array
                 return $this->dumpSettings;
             }
             else
             {   // no tables set for inclusion - return empty array
                 return $this->dumpSettings['include-tables'] = array();
             }
References YAWK\BACKUP\DATABASE\mysqlBackup\$dumpSettings.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\includeMysqldumpClass().
initMysqlBackup()
YAWK\BACKUP\DATABASE\mysqlBackup::initMysqlBackup ($db, $overwriteBackup, $zipBackup, $storeSqlTmp)
Initialize this database backup class.
Parameters
object $db database object
string $overwriteBackup if overwrite backup is allowed or not "true" | "false"
string $zipBackup if backup should be zipped or not "true" | "false"
string $storeSqlTmp if backup should be stored in tmp/database "true" | "false"
Returns
bool
Definition at line 69 of file backup-mysqlBackup.php.
         {
             // if overwrite backup is true
             $this->overwriteBackup = $overwriteBackup;
             // zip true|false
             $this->zipBackup = $zipBackup;
             // store .sql in tmp folder true|false
             $this->storeSqlTmp = $storeSqlTmp;
             // check if .sql file should be stored in tmp folder
             if (isset($this->storeSqlTmp) && ($this->storeSqlTmp == "true"))
             {   // if so, do not zip
                 $this->zipBackup = "false";
             }
             // start database backup
             if ($this->startMysqlBackup($db) === true)
             {   // mysql backup done
                 return true;
             }
             else
             {   // mysql backup failed
                 return false;
             }
References $db, YAWK\BACKUP\backup\$overwriteBackup, YAWK\BACKUP\backup\$storeSqlTmp, YAWK\BACKUP\backup\$zipBackup, and YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup().
setDumpSettings()
YAWK\BACKUP\DATABASE\mysqlBackup::setDumpSettings ()
Set mysqldump settings.
Returns
array $this->dumpSettings
mysqldump settings eg. include or exclude tables from database
Definition at line 100 of file backup-mysqlBackup.php.
         {
             // generate dump settings array
             $this->dumpSettings = array(
                 'include-tables'
                 => array(),
                 'exclude-tables'
                 => array());
             return $this->dumpSettings;
References YAWK\BACKUP\DATABASE\mysqlBackup\$dumpSettings.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\includeMysqldumpClass().
sqlFileExists()
YAWK\BACKUP\DATABASE\mysqlBackup::sqlFileExists ()
Check if .sql backup file exists.
return bool if $this->sqlBackup exists
Returns
bool true|false
Definition at line 244 of file backup-mysqlBackup.php.
         {
             // set path + filename (store as string in $this->sqlBackup)
             $this->sqlBackup = $this->sqlPath.$this->backupSqlFile;// .sql backup file exists
             // check if .sql backup file is already there
             if (is_file($this->sqlBackup))
             {
                 // build sqlBackup string
                 return true;
             }
             else
             {
                 // .sql backup file does not exist
                 return false;
             }
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\doSqlBackup(), and YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup().
startMysqlBackup()
YAWK\BACKUP\DATABASE\mysqlBackup::startMysqlBackup ($db)
Start and manage mysql backup routine.
First of all, mysqldump class will be included. Then, a check runs if a .sql backup file exists. if so, check if overwrite backup is allowed. If this is true, doSqlBackup method will be called. (This function does the real job).
return bool if zip archive exists
Returns
bool true|false
Definition at line 493 of file backup-mysqlBackup.php.
         {
             // include mysqldump class
             $this->includeMysqldumpClass($db);
             // check if backup overwrite is allowed
             if ($this->overwriteBackup == "false")
             {
                 if (isset($_POST))
                 {
                     // check if new folder was entered by user
                     if (isset($_POST['newFolder']) && (!empty($_POST['newFolder'])))
                     {
                         // create new archive sub folder path
                         $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['newFolder']."/";
                         // create new directory in archive
                         if (!is_dir($this->archiveBackupSubFolder))
{
                             if (mkdir($this->archiveBackupSubFolder))
                             {   // all good, new archive subfolder created
                                 // set syslog entry: dir created
                                 \YAWK\sys::setSyslog($db, 49, 0, "archive directory created: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                             }
                             else
                             {   // failed to create new archive subfolder
                                 // set syslog entry: failed
                                 \YAWK\sys::setSyslog($db, 52, 0, "failed to create archive directory: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                             }
                         }
                     }
                     // check if existing folder was selected by user
                     else if (isset($_POST['selectFolder']) && (!empty($_POST['selectFolder'])))
                     {   // set archive sub foder path
                         $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['selectFolder']."/";
                     }
                     // SET PATH WHERE .SQL FILE SHOULD BE STORED
                     $this->sqlPath = $this->archiveBackupSubFolder;
                     // set archive backup subfolder
                     $this->targetFolder = $this->archiveBackupSubFolder;
                 }
             }
             // check if a backup exists
             if ($this->sqlFileExists() === true)
             {
                 // do database backup
                 if ($this->doSqlBackup($db) === true)
                 {   // ok, backup done
                     \YAWK\sys::setSyslog($db, 50, 3, "database backup overwritten", 0, 0, 0, 0);
                     return true;
                 }
                 else
                 {   // backup failed - unable to overwrite - check chmod settings!
                     \YAWK\sys::setSyslog($db, 52, 2, "failed to overwrite database backup", 0, 0, 0, 0);
                     return false;
                 }
             }
             else
             {   // .sql file does not exist - do database backup
                 if ($this->doSqlBackup($db) === true)
                 {   // ok, backup done!
                     // \YAWK\sys::setSyslog($db, 50, 3, "created database backup", 0, 0, 0, 0);
                     return true;
                 }
                 else
                 {   // backup failed!
                     \YAWK\sys::setSyslog($db, 52, 2, "failed to write database backup", 0, 0, 0, 0);
                     return false;
                 }
             }
References YAWK\BACKUP\backup\$archiveBackupSubFolder, $db, YAWK\BACKUP\DATABASE\mysqlBackup\doSqlBackup(), YAWK\BACKUP\DATABASE\mysqlBackup\includeMysqldumpClass(), and YAWK\BACKUP\DATABASE\mysqlBackup\sqlFileExists().
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\initMysqlBackup().
Member Data Documentation
$backupMode
YAWK\BACKUP\DATABASE\mysqlBackup::$backupMode = 'include'
Parameters
string backup mode (include|exclude|all)
Definition at line 44 of file backup-mysqlBackup.php.
$backupSqlFile
YAWK\BACKUP\DATABASE\mysqlBackup::$backupSqlFile = 'database-backup.sql'
Parameters
string default filename of mysqldump .sql file
Definition at line 54 of file backup-mysqlBackup.php.
$config
YAWK\BACKUP\DATABASE\mysqlBackup::$config private
Parameters
array mysql config array
Definition at line 30 of file backup-mysqlBackup.php.
$dbname
YAWK\BACKUP\DATABASE\mysqlBackup::$dbname private
Parameters
string mysql database name
Definition at line 34 of file backup-mysqlBackup.php.
$dumpSettings
YAWK\BACKUP\DATABASE\mysqlBackup::$dumpSettings = array()
Parameters
array mysqldump settings
Definition at line 50 of file backup-mysqlBackup.php.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\excludeTables(), YAWK\BACKUP\DATABASE\mysqlBackup\includeTables(), and YAWK\BACKUP\DATABASE\mysqlBackup\setDumpSettings().
$excludeTablesArray
YAWK\BACKUP\DATABASE\mysqlBackup::$excludeTablesArray = array()
Parameters
array exclude tables
Definition at line 46 of file backup-mysqlBackup.php.
$hashValue
YAWK\BACKUP\DATABASE\mysqlBackup::$hashValue = ''
Parameters
string hash value of .sql file
Definition at line 58 of file backup-mysqlBackup.php.
$host
YAWK\BACKUP\DATABASE\mysqlBackup::$host private
Parameters
string mysql server hostname
Definition at line 32 of file backup-mysqlBackup.php.
$includeTablesArray
YAWK\BACKUP\DATABASE\mysqlBackup::$includeTablesArray = array()
Parameters
array include tables
Definition at line 48 of file backup-mysqlBackup.php.
$mysqldump
YAWK\BACKUP\DATABASE\mysqlBackup::$mysqldump
Parameters
object mysqldump object
Definition at line 26 of file backup-mysqlBackup.php.
$pass
YAWK\BACKUP\DATABASE\mysqlBackup::$pass private
Parameters
string mysql pass
Definition at line 38 of file backup-mysqlBackup.php.
$port
YAWK\BACKUP\DATABASE\mysqlBackup::$port private
Parameters
string mysql port
Definition at line 42 of file backup-mysqlBackup.php.
$prefix
YAWK\BACKUP\DATABASE\mysqlBackup::$prefix private
Parameters
string mysql prefix
Definition at line 40 of file backup-mysqlBackup.php.
$sqlBackup
YAWK\BACKUP\DATABASE\mysqlBackup::$sqlBackup = ''
Parameters
string name of the backup .sql file
Definition at line 56 of file backup-mysqlBackup.php.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\generateZipArchive().
$sqlPath
YAWK\BACKUP\DATABASE\mysqlBackup::$sqlPath = '../system/backup/current/'
Parameters
string path, where the backup will be stored
Definition at line 52 of file backup-mysqlBackup.php.
$user
YAWK\BACKUP\DATABASE\mysqlBackup::$user private
Parameters
string mysql user
Definition at line 36 of file backup-mysqlBackup.php.
$zip
YAWK\BACKUP\DATABASE\mysqlBackup::$zip
Parameters
object zip object
Definition at line 28 of file backup-mysqlBackup.php.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\generateZipArchive().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/backup-mysqlBackup.php