YaWK: YAWK\Mobile_Detect Class Reference
YAWK\Mobile_Detect Class Reference
Public Member Functions
__call ($name, $arguments)
__construct (array $headers=null, $userAgent=null)
checkHttpHeadersForMobile ()
getCfHeaders ()
getHttpHeader ($header)
getHttpHeaders ()
getMatchesArray ()
getMatchingRegex ()
getMobileDetectionRulesExtended ()
getMobileHeaders ()
getRules ()
getUaHttpHeaders ()
getUserAgent ()
is ($key, $userAgent=null, $httpHeaders=null)
isMobile ($userAgent=null, $httpHeaders=null)
isTablet ($userAgent=null, $httpHeaders=null)
match ($regex, $userAgent=null)
mobileGrade ()
prepareVersionNo ($ver)
setCfHeaders ($cfHeaders=null)
setDetectionType ($type=null)
setHttpHeaders ($httpHeaders=null)
setUserAgent ($userAgent=null)
version ($propertyName, $type=self::VERSION_TYPE_STRING)
Static Public Member Functions
static getBrowsers ()
static getMobileDetectionRules ()
static getOperatingSystems ()
static getPhoneDevices ()
static getProperties ()
static getScriptVersion ()
static getTabletDevices ()
static getUserAgents ()
static getUtilities ()
Public Attributes
const DETECTION_TYPE_EXTENDED = 'extended'
const DETECTION_TYPE_MOBILE = 'mobile'
const MOBILE_GRADE_A = 'A'
const MOBILE_GRADE_B = 'B'
const MOBILE_GRADE_C = 'C'
const VER = '([\w._\+]+)'
const VERSION = '2.8.32'
const VERSION_TYPE_FLOAT = 'float'
const VERSION_TYPE_STRING = 'text'
Protected Member Functions
matchDetectionRulesAgainstUA ($userAgent=null)
matchUAAgainstKey ($key)
Protected Attributes
$cache = array()
$cloudfrontHeaders = array()
$detectionType = self::DETECTION_TYPE_MOBILE
$httpHeaders = array()
$matchesArray = null
$matchingRegex = null
$userAgent = null
Static Protected Attributes
static $browsers
static $mobileHeaders
static $operatingSystems
static $phoneDevices
static $properties
static $tabletDevices
static $uaHttpHeaders
static $utilities
Private Member Functions
prepareUserAgent ($userAgent)
Detailed Description
Mobile Detect Library
Definition at line 27 of file Mobile_Detect.php.
Constructor & Destructor Documentation
__construct()
YAWK\Mobile_Detect::__construct (array $headers = null, $userAgent = null)
Construct an instance of this class.
Parameters
array $headers Specify the headers as injection. Should be PHP SERVER flavored. If left empty, will use the global _SERVER['HTTP*'] vars instead.
string $userAgent Inject the User-Agent header. If null, will use HTTP_USER_AGENT from the $headers array instead.
Definition at line 683 of file Mobile_Detect.php.
         {
             $this->setHttpHeaders($headers);
             $this->setUserAgent($userAgent);
         }
References YAWK\Mobile_Detect\$userAgent, YAWK\Mobile_Detect\setHttpHeaders(), and YAWK\Mobile_Detect\setUserAgent().
Member Function Documentation
__call()
YAWK\Mobile_Detect::__call ($name, $arguments)
Magic overloading method.
@method boolean is[...]()
Parameters
string $name
array $arguments
Returns
mixed
Exceptions
BadMethodCallException when the method doesn't exist and doesn't start with 'is'
Definition at line 1085 of file Mobile_Detect.php.
         {
             // make sure the name starts with 'is', otherwise
             if (substr($name, 0, 2) !== 'is') {
                 throw new BadMethodCallException("No such method exists: $name");
             }
             $this->setDetectionType(self::DETECTION_TYPE_MOBILE);
             $key = substr($name, 2);
             return $this->matchUAAgainstKey($key);
         }
References $name, YAWK\Mobile_Detect\matchUAAgainstKey(), and YAWK\Mobile_Detect\setDetectionType().
checkHttpHeadersForMobile()
YAWK\Mobile_Detect::checkHttpHeadersForMobile ()
Check the HTTP headers for signs of mobile. This is the fastest mobile check possible; it's used inside isMobile() method.
Returns
bool
Definition at line 1053 of file Mobile_Detect.php.
         {
             foreach ($this->getMobileHeaders() as $mobileHeader => $matchType) {
                 if (isset($this->httpHeaders[$mobileHeader])) {
                     if (is_array($matchType['matches'])) {
                         foreach ($matchType['matches'] as $_match) {
                             if (strpos($this->httpHeaders[$mobileHeader], $_match) !== false) {
                                 return true;
                             }
                         }
                         return false;
                     } else {
                         return true;
                     }
                 }
             }
             return false;
         }
References as, and YAWK\Mobile_Detect\getMobileHeaders().
Referenced by YAWK\Mobile_Detect\isMobile().
getBrowsers()
static YAWK\Mobile_Detect::getBrowsers () static
Retrieve the list of known browsers. Specifically, the user agents.
Returns
array List of browsers / user agents.
Definition at line 953 of file Mobile_Detect.php.
         {
             return self::$browsers;
         }
References YAWK\Mobile_Detect\$browsers.
Referenced by YAWK\Mobile_Detect\getUserAgents().
getCfHeaders()
YAWK\Mobile_Detect::getCfHeaders ()
Retrieves the cloudfront headers.
Returns
array
Definition at line 827 of file Mobile_Detect.php.
         {
             return $this->cloudfrontHeaders;
         }
References YAWK\Mobile_Detect\$cloudfrontHeaders.
Referenced by YAWK\Mobile_Detect\isMobile(), YAWK\Mobile_Detect\isTablet(), and YAWK\Mobile_Detect\setUserAgent().
getHttpHeader()
YAWK\Mobile_Detect::getHttpHeader ($header)
Retrieves a particular header. If it doesn't exist, no exception/error is caused. Simply null is returned.
Parameters
string $header The name of the header to retrieve. Can be HTTP compliant such as "User-Agent" or "X-Device-User-Agent" or can be php-esque with the all-caps, HTTP_ prefixed, underscore seperated awesomeness.
Returns
string|null The value of the header.
Definition at line 753 of file Mobile_Detect.php.
         {
             // are we using PHP-flavored headers?
             if (strpos($header, '_') === false) {
                 $header = str_replace('-', '_', $header);
                 $header = strtoupper($header);
             }
             // test the alternate, too
             $altHeader = 'HTTP_' . $header;
             //Test both the regular and the HTTP_ prefix
             if (isset($this->httpHeaders[$header])) {
                 return $this->httpHeaders[$header];
             } elseif (isset($this->httpHeaders[$altHeader])) {
                 return $this->httpHeaders[$altHeader];
             }
             return null;
         }
References $header.
getHttpHeaders()
YAWK\Mobile_Detect::getHttpHeaders ()
Retrieves the HTTP headers.
Returns
array
Definition at line 738 of file Mobile_Detect.php.
         {
             return $this->httpHeaders;
         }
References YAWK\Mobile_Detect\$httpHeaders.
getMatchesArray()
YAWK\Mobile_Detect::getMatchesArray ()
Definition at line 913 of file Mobile_Detect.php.
         {
             return $this->matchesArray;
         }
References YAWK\Mobile_Detect\$matchesArray.
getMatchingRegex()
YAWK\Mobile_Detect::getMatchingRegex ()
Definition at line 908 of file Mobile_Detect.php.
         {
             return $this->matchingRegex;
         }
References YAWK\Mobile_Detect\$matchingRegex.
getMobileDetectionRules()
static YAWK\Mobile_Detect::getMobileDetectionRules () static
Method gets the mobile detection rules. This method is used for the magic methods $detect->is*().
Deprecated:
since version 2.6.9
Returns
array All the rules (but not extended).
Definition at line 975 of file Mobile_Detect.php.
         {
             static $rules;
             if (!$rules) {
                 $rules = array_merge(
                     self::$phoneDevices,
                     self::$tabletDevices,
                     self::$operatingSystems,
                     self::$browsers
                 );
             }
             return $rules;
         }
Referenced by YAWK\Mobile_Detect\getRules().
getMobileDetectionRulesExtended()
YAWK\Mobile_Detect::getMobileDetectionRulesExtended ()
Method gets the mobile detection rules + utilities. The reason this is separate is because utilities rules don't necessary imply mobile. This method is used inside the new $detect->is('stuff') method.
Deprecated:
since version 2.6.9
Returns
array All the rules + extended.
Definition at line 1002 of file Mobile_Detect.php.
         {
             static $rules;
             if (!$rules) {
                 // Merge all rules together.
                 $rules = array_merge(
                     self::$phoneDevices,
                     self::$tabletDevices,
                     self::$operatingSystems,
                     self::$browsers,
                     self::$utilities
                 );
             }
             return $rules;
         }
Referenced by YAWK\Mobile_Detect\getRules().
getMobileHeaders()
YAWK\Mobile_Detect::getMobileHeaders ()
Definition at line 774 of file Mobile_Detect.php.
         {
             return self::$mobileHeaders;
         }
References YAWK\Mobile_Detect\$mobileHeaders.
Referenced by YAWK\Mobile_Detect\checkHttpHeadersForMobile().
getOperatingSystems()
static YAWK\Mobile_Detect::getOperatingSystems () static
Retrieve the list of mobile operating systems.
Returns
array The list of mobile operating systems.
Definition at line 1041 of file Mobile_Detect.php.
         {
             return self::$operatingSystems;
         }
References YAWK\Mobile_Detect\$operatingSystems.
getPhoneDevices()
static YAWK\Mobile_Detect::getPhoneDevices () static
Retrieve the list of known phone devices.
Returns
array List of phone devices.
Definition at line 923 of file Mobile_Detect.php.
         {
             return self::$phoneDevices;
         }
References YAWK\Mobile_Detect\$phoneDevices.
getProperties()
static YAWK\Mobile_Detect::getProperties () static
Get the properties array.
Returns
array
Definition at line 1274 of file Mobile_Detect.php.
         {
             return self::$properties;
         }
References YAWK\Mobile_Detect\$properties.
Referenced by YAWK\Mobile_Detect\version().
getRules()
YAWK\Mobile_Detect::getRules ()
Retrieve the current set of rules.
Deprecated:
since version 2.6.9
Returns
array
Definition at line 1027 of file Mobile_Detect.php.
         {
             if ($this->detectionType == self::DETECTION_TYPE_EXTENDED) {
                 return self::getMobileDetectionRulesExtended();
             } else {
                 return self::getMobileDetectionRules();
             }
         }
References YAWK\Mobile_Detect\getMobileDetectionRules(), and YAWK\Mobile_Detect\getMobileDetectionRulesExtended().
Referenced by YAWK\Mobile_Detect\matchDetectionRulesAgainstUA(), and YAWK\Mobile_Detect\matchUAAgainstKey().
getScriptVersion()
static YAWK\Mobile_Detect::getScriptVersion () static
Get the current script version. This is useful for the demo.php file, so people can check on what version they are testing for mobile devices.
Returns
string The version number in semantic version format.
Definition at line 700 of file Mobile_Detect.php.
         {
             return self::VERSION;
         }
References YAWK\Mobile_Detect\VERSION.
getTabletDevices()
static YAWK\Mobile_Detect::getTabletDevices () static
Retrieve the list of known tablet devices.
Returns
array List of tablet devices.
Definition at line 933 of file Mobile_Detect.php.
         {
             return self::$tabletDevices;
         }
References YAWK\Mobile_Detect\$tabletDevices.
getUaHttpHeaders()
YAWK\Mobile_Detect::getUaHttpHeaders ()
Get all possible HTTP headers that can contain the User-Agent string.
Returns
array List of HTTP headers.
Definition at line 785 of file Mobile_Detect.php.
         {
             return self::$uaHttpHeaders;
         }
References YAWK\Mobile_Detect\$uaHttpHeaders.
Referenced by YAWK\Mobile_Detect\setUserAgent().
getUserAgent()
YAWK\Mobile_Detect::getUserAgent ()
Retrieve the User-Agent.
Returns
string|null The user agent if it's set.
Definition at line 881 of file Mobile_Detect.php.
         {
             return $this->userAgent;
         }
References YAWK\Mobile_Detect\$userAgent.
Referenced by YAWK\Mobile_Detect\isMobile(), and YAWK\Mobile_Detect\isTablet().
getUserAgents()
static YAWK\Mobile_Detect::getUserAgents () static
Alias for getBrowsers() method.
Returns
array List of user agents.
Definition at line 943 of file Mobile_Detect.php.
         {
             return self::getBrowsers();
         }
References YAWK\Mobile_Detect\getBrowsers().
getUtilities()
static YAWK\Mobile_Detect::getUtilities () static
Retrieve the list of known utilities.
Returns
array List of utilities.
Definition at line 963 of file Mobile_Detect.php.
         {
             return self::$utilities;
         }
References YAWK\Mobile_Detect\$utilities.
is()
YAWK\Mobile_Detect::is ($key, $userAgent = null, $httpHeaders = null)
This method checks for a certain property in the userAgent.
Todo:
: The httpHeaders part is not yet used.
Parameters
string $key
string $userAgent deprecated
string $httpHeaders deprecated
Returns
bool|int|null
Definition at line 1226 of file Mobile_Detect.php.
         {
             // Set the UA and HTTP headers only if needed (eg. batch mode).
             if ($httpHeaders) {
                 $this->setHttpHeaders($httpHeaders);
             }
             if ($userAgent) {
                 $this->setUserAgent($userAgent);
             }
             $this->setDetectionType(self::DETECTION_TYPE_EXTENDED);
             return $this->matchUAAgainstKey($key);
         }
References YAWK\Mobile_Detect\$httpHeaders, YAWK\Mobile_Detect\$userAgent, YAWK\Mobile_Detect\matchUAAgainstKey(), YAWK\Mobile_Detect\setDetectionType(), YAWK\Mobile_Detect\setHttpHeaders(), and YAWK\Mobile_Detect\setUserAgent().
Referenced by YAWK\Mobile_Detect\mobileGrade().
isMobile()
YAWK\Mobile_Detect::isMobile ($userAgent = null, $httpHeaders = null)
Check if the device is mobile. Returns true if any type of mobile device detected, including special ones
Parameters
null $userAgent deprecated
null $httpHeaders deprecated
Returns
bool
Definition at line 1158 of file Mobile_Detect.php.
         {
             if ($httpHeaders) {
                 $this->setHttpHeaders($httpHeaders);
             }
             if ($userAgent) {
                 $this->setUserAgent($userAgent);
             }
             // Check specifically for cloudfront headers if the useragent === 'Amazon CloudFront'
             if ($this->getUserAgent() === 'Amazon CloudFront') {
                 $cfHeaders = $this->getCfHeaders();
                 if (array_key_exists('HTTP_CLOUDFRONT_IS_MOBILE_VIEWER', $cfHeaders) && $cfHeaders['HTTP_CLOUDFRONT_IS_MOBILE_VIEWER'] === 'true') {
                     return true;
                 }
             }
             $this->setDetectionType(self::DETECTION_TYPE_MOBILE);
             if ($this->checkHttpHeadersForMobile()) {
                 return true;
             } else {
                 return $this->matchDetectionRulesAgainstUA();
             }
         }
References YAWK\Mobile_Detect\$httpHeaders, YAWK\Mobile_Detect\$userAgent, YAWK\Mobile_Detect\checkHttpHeadersForMobile(), YAWK\Mobile_Detect\getCfHeaders(), YAWK\Mobile_Detect\getUserAgent(), YAWK\Mobile_Detect\matchDetectionRulesAgainstUA(), YAWK\Mobile_Detect\setDetectionType(), YAWK\Mobile_Detect\setHttpHeaders(), and YAWK\Mobile_Detect\setUserAgent().
Referenced by YAWK\Mobile_Detect\mobileGrade().
isTablet()
YAWK\Mobile_Detect::isTablet ($userAgent = null, $httpHeaders = null)
Check if the device is a tablet. Return true if any type of tablet device is detected.
Parameters
string $userAgent deprecated
array $httpHeaders deprecated
Returns
bool
Definition at line 1195 of file Mobile_Detect.php.
         {
             // Check specifically for cloudfront headers if the useragent === 'Amazon CloudFront'
             if ($this->getUserAgent() === 'Amazon CloudFront') {
                 $cfHeaders = $this->getCfHeaders();
                 if (array_key_exists('HTTP_CLOUDFRONT_IS_TABLET_VIEWER', $cfHeaders) && $cfHeaders['HTTP_CLOUDFRONT_IS_TABLET_VIEWER'] === 'true') {
                     return true;
                 }
             }
             $this->setDetectionType(self::DETECTION_TYPE_MOBILE);
             foreach (self::$tabletDevices as $_regex) {
                 if ($this->match($_regex, $userAgent)) {
                     return true;
                 }
             }
             return false;
         }
References YAWK\Mobile_Detect\$userAgent, as, YAWK\Mobile_Detect\getCfHeaders(), YAWK\Mobile_Detect\getUserAgent(), YAWK\Mobile_Detect\match(), and YAWK\Mobile_Detect\setDetectionType().
match()
YAWK\Mobile_Detect::match ($regex, $userAgent = null)
Some detection rules are relative (not standard), because of the diversity of devices, vendors and their conventions in representing the User-Agent or the HTTP headers.
This method will be used to check custom regexes against the User-Agent string.
Parameters
$regex
string $userAgent
Returns
bool
Todo:
: search in the HTTP headers too.
Definition at line 1257 of file Mobile_Detect.php.
         {
             $match = (bool)preg_match(sprintf('#%s#is', $regex), (false === empty($userAgent) ? $userAgent : $this->userAgent), $matches);
             // If positive match is found, store the results for debug.
             if ($match) {
                 $this->matchingRegex = $regex;
                 $this->matchesArray = $matches;
             }
             return $match;
         }
References YAWK\Mobile_Detect\$userAgent.
Referenced by YAWK\Mobile_Detect\isTablet(), YAWK\Mobile_Detect\matchDetectionRulesAgainstUA(), YAWK\Mobile_Detect\matchUAAgainstKey(), and YAWK\Mobile_Detect\mobileGrade().
matchDetectionRulesAgainstUA()
YAWK\Mobile_Detect::matchDetectionRulesAgainstUA ($userAgent = null) protected
Find a detection rule that matches the current User-agent.
Parameters
null $userAgent deprecated
Returns
boolean
Definition at line 1105 of file Mobile_Detect.php.
         {
             // Begin general search.
             foreach ($this->getRules() as $_regex) {
                 if (empty($_regex)) {
                     continue;
                 }
                 if ($this->match($_regex, $userAgent)) {
                     return true;
                 }
             }
             return false;
         }
References YAWK\Mobile_Detect\$userAgent, as, YAWK\Mobile_Detect\getRules(), and YAWK\Mobile_Detect\match().
Referenced by YAWK\Mobile_Detect\isMobile().
matchUAAgainstKey()
YAWK\Mobile_Detect::matchUAAgainstKey ($key) protected
Search for a certain key in the rules array. If the key is found then try to match the corresponding regex against the User-Agent.
Parameters
string $key
Returns
boolean
Definition at line 1130 of file Mobile_Detect.php.
         {
             // Make the keys lowercase so we can match: isIphone(), isiPhone(), isiphone(), etc.
             $key = strtolower($key);
             if (false === isset($this->cache[$key])) {
                 // change the keys to lower case
                 $_rules = array_change_key_case($this->getRules());
                 if (false === empty($_rules[$key])) {
                     $this->cache[$key] = $this->match($_rules[$key]);
                 }
                 if (false === isset($this->cache[$key])) {
                     $this->cache[$key] = false;
                 }
             }
             return $this->cache[$key];
         }
References YAWK\Mobile_Detect\getRules(), and YAWK\Mobile_Detect\match().
Referenced by YAWK\Mobile_Detect\__call(), and YAWK\Mobile_Detect\is().
mobileGrade()
YAWK\Mobile_Detect::mobileGrade ()
Retrieve the mobile grading, using self::MOBILE_GRADE_* constants.
Returns
string One of the self::MOBILE_GRADE_* constants.
Definition at line 1358 of file Mobile_Detect.php.
         {
             $isMobile = $this->isMobile();
             if (
                 // Apple iOS 4-7.0  Tested on the original iPad (4.3 / 5.0), iPad 2 (4.3 / 5.1 / 6.1), iPad 3 (5.1 / 6.0), iPad Mini (6.1), iPad Retina (7.0), iPhone 3GS (4.3), iPhone 4 (4.3 / 5.1), iPhone 4S (5.1 / 6.0), iPhone 5 (6.0), and iPhone 5S (7.0)
                 $this->is('iOS') && $this->version('iPad', self::VERSION_TYPE_FLOAT) >= 4.3 ||
                 $this->is('iOS') && $this->version('iPhone', self::VERSION_TYPE_FLOAT) >= 4.3 ||
                 $this->is('iOS') && $this->version('iPod', self::VERSION_TYPE_FLOAT) >= 4.3 ||
                 // Android 2.1-2.3 - Tested on the HTC Incredible (2.2), original Droid (2.2), HTC Aria (2.1), Google Nexus S (2.3). Functional on 1.5 & 1.6 but performance may be sluggish, tested on Google G1 (1.5)
                 // Android 3.1 (Honeycomb)  - Tested on the Samsung Galaxy Tab 10.1 and Motorola XOOM
                 // Android 4.0 (ICS)  - Tested on a Galaxy Nexus. Note: transition performance can be poor on upgraded devices
                 // Android 4.1 (Jelly Bean)  - Tested on a Galaxy Nexus and Galaxy 7
                 ($this->version('Android', self::VERSION_TYPE_FLOAT) > 2.1 && $this->is('Webkit')) ||
                 // Windows Phone 7.5-8 - Tested on the HTC Surround (7.5), HTC Trophy (7.5), LG-E900 (7.5), Nokia 800 (7.8), HTC Mazaa (7.8), Nokia Lumia 520 (8), Nokia Lumia 920 (8), HTC 8x (8)
                 $this->version('Windows Phone OS', self::VERSION_TYPE_FLOAT) >= 7.5 ||
                 // Tested on the Torch 9800 (6) and Style 9670 (6), BlackBerry Torch 9810 (7), BlackBerry Z10 (10)
                 $this->is('BlackBerry') && $this->version('BlackBerry', self::VERSION_TYPE_FLOAT) >= 6.0 ||
                 // Blackberry Playbook (1.0-2.0) - Tested on PlayBook
                 $this->match('Playbook.*Tablet') ||
                 // Palm WebOS (1.4-3.0) - Tested on the Palm Pixi (1.4), Pre (1.4), Pre 2 (2.0), HP TouchPad (3.0)
                 ($this->version('webOS', self::VERSION_TYPE_FLOAT) >= 1.4 && $this->match('Palm|Pre|Pixi')) ||
                 // Palm WebOS 3.0  - Tested on HP TouchPad
                 $this->match('hp.*TouchPad') ||
                 // Firefox Mobile 18 - Tested on Android 2.3 and 4.1 devices
                 ($this->is('Firefox') && $this->version('Firefox', self::VERSION_TYPE_FLOAT) >= 18) ||
                 // Chrome for Android - Tested on Android 4.0, 4.1 device
                 ($this->is('Chrome') && $this->is('AndroidOS') && $this->version('Android', self::VERSION_TYPE_FLOAT) >= 4.0) ||
                 // Skyfire 4.1 - Tested on Android 2.3 device
                 ($this->is('Skyfire') && $this->version('Skyfire', self::VERSION_TYPE_FLOAT) >= 4.1 && $this->is('AndroidOS') && $this->version('Android', self::VERSION_TYPE_FLOAT) >= 2.3) ||
                 // Opera Mobile 11.5-12: Tested on Android 2.3
                 ($this->is('Opera') && $this->version('Opera Mobi', self::VERSION_TYPE_FLOAT) >= 11.5 && $this->is('AndroidOS')) ||
                 // Meego 1.2 - Tested on Nokia 950 and N9
                 $this->is('MeeGoOS') ||
                 // Tizen (pre-release) - Tested on early hardware
                 $this->is('Tizen') ||
                 // Samsung Bada 2.0 - Tested on a Samsung Wave 3, Dolphin browser
                 // @todo: more tests here!
                 $this->is('Dolfin') && $this->version('Bada', self::VERSION_TYPE_FLOAT) >= 2.0 ||
                 // UC Browser - Tested on Android 2.3 device
                 (($this->is('UC Browser') || $this->is('Dolfin')) && $this->version('Android', self::VERSION_TYPE_FLOAT) >= 2.3) ||
                 // Kindle 3 and Fire  - Tested on the built-in WebKit browser for each
                 ($this->match('Kindle Fire') ||
                     $this->is('Kindle') && $this->version('Kindle', self::VERSION_TYPE_FLOAT) >= 3.0) ||
                 // Nook Color 1.4.1 - Tested on original Nook Color, not Nook Tablet
                 $this->is('AndroidOS') && $this->is('NookTablet') ||
                 // Chrome Desktop 16-24 - Tested on OS X 10.7 and Windows 7
                 $this->version('Chrome', self::VERSION_TYPE_FLOAT) >= 16 && !$isMobile ||
                 // Safari Desktop 5-6 - Tested on OS X 10.7 and Windows 7
                 $this->version('Safari', self::VERSION_TYPE_FLOAT) >= 5.0 && !$isMobile ||
                 // Firefox Desktop 10-18 - Tested on OS X 10.7 and Windows 7
                 $this->version('Firefox', self::VERSION_TYPE_FLOAT) >= 10.0 && !$isMobile ||
                 // Internet Explorer 7-9 - Tested on Windows XP, Vista and 7
                 $this->version('IE', self::VERSION_TYPE_FLOAT) >= 7.0 && !$isMobile ||
                 // Opera Desktop 10-12 - Tested on OS X 10.7 and Windows 7
                 $this->version('Opera', self::VERSION_TYPE_FLOAT) >= 10 && !$isMobile
             ) {
                 return self::MOBILE_GRADE_A;
             }
             if (
                 $this->is('iOS') && $this->version('iPad', self::VERSION_TYPE_FLOAT) < 4.3 ||
                 $this->is('iOS') && $this->version('iPhone', self::VERSION_TYPE_FLOAT) < 4.3 ||
                 $this->is('iOS') && $this->version('iPod', self::VERSION_TYPE_FLOAT) < 4.3 ||
                 // Blackberry 5.0: Tested on the Storm 2 9550, Bold 9770
                 $this->is('Blackberry') && $this->version('BlackBerry', self::VERSION_TYPE_FLOAT) >= 5 && $this->version('BlackBerry', self::VERSION_TYPE_FLOAT) < 6 ||
                 //Opera Mini (5.0-6.5) - Tested on iOS 3.2/4.3 and Android 2.3
                 ($this->version('Opera Mini', self::VERSION_TYPE_FLOAT) >= 5.0 && $this->version('Opera Mini', self::VERSION_TYPE_FLOAT) <= 7.0 &&
                     ($this->version('Android', self::VERSION_TYPE_FLOAT) >= 2.3 || $this->is('iOS'))) ||
                 // Nokia Symbian^3 - Tested on Nokia N8 (Symbian^3), C7 (Symbian^3), also works on N97 (Symbian^1)
                 $this->match('NokiaN8|NokiaC7|N97.*Series60|Symbian/3') ||
                 // @todo: report this (tested on Nokia N71)
                 $this->version('Opera Mobi', self::VERSION_TYPE_FLOAT) >= 11 && $this->is('SymbianOS')
             ) {
                 return self::MOBILE_GRADE_B;
             }
             if (
                 // Blackberry 4.x - Tested on the Curve 8330
                 $this->version('BlackBerry', self::VERSION_TYPE_FLOAT) <= 5.0 ||
                 // Windows Mobile - Tested on the HTC Leo (WinMo 5.2)
                 $this->match('MSIEMobile|Windows CE.*Mobile') || $this->version('Windows Mobile', self::VERSION_TYPE_FLOAT) <= 5.2 ||
                 // Tested on original iPhone (3.1), iPhone 3 (3.2)
                 $this->is('iOS') && $this->version('iPad', self::VERSION_TYPE_FLOAT) <= 3.2 ||
                 $this->is('iOS') && $this->version('iPhone', self::VERSION_TYPE_FLOAT) <= 3.2 ||
                 $this->is('iOS') && $this->version('iPod', self::VERSION_TYPE_FLOAT) <= 3.2 ||
                 // Internet Explorer 7 and older - Tested on Windows XP
                 $this->version('IE', self::VERSION_TYPE_FLOAT) <= 7.0 && !$isMobile
             ) {
                 return self::MOBILE_GRADE_C;
             }
             // All older smartphone platforms and featurephones - Any device that doesn't support media queries
             // will receive the basic, C grade experience.
             return self::MOBILE_GRADE_C;
         }
References YAWK\Mobile_Detect\is(), YAWK\Mobile_Detect\isMobile(), YAWK\Mobile_Detect\match(), YAWK\Mobile_Detect\MOBILE_GRADE_A, YAWK\Mobile_Detect\MOBILE_GRADE_B, YAWK\Mobile_Detect\MOBILE_GRADE_C, and YAWK\Mobile_Detect\version().
prepareUserAgent()
YAWK\Mobile_Detect::prepareUserAgent ($userAgent) private
Parameters
string $userAgent
Returns
string
Definition at line 836 of file Mobile_Detect.php.
         {
             $userAgent = trim($userAgent);
             $userAgent = substr($userAgent, 0, 500);
             return $userAgent;
         }
References YAWK\Mobile_Detect\$userAgent.
Referenced by YAWK\Mobile_Detect\setUserAgent().
prepareVersionNo()
YAWK\Mobile_Detect::prepareVersionNo ($ver)
Prepare the version number.
Todo:
Remove the error supression from str_replace() call.
Parameters
string $ver The string version, like "2.6.21.2152";
Returns
float
Definition at line 1288 of file Mobile_Detect.php.
         {
             $ver = str_replace(array('_', ' ', '/'), '.', $ver);
             $arrVer = explode('.', $ver, 2);
             if (isset($arrVer[1])) {
                 $arrVer[1] = @str_replace('.', '', $arrVer[1]); // @todo: treat strings versions.
             }
             return (float)implode('.', $arrVer);
         }
Referenced by YAWK\Mobile_Detect\version().
setCfHeaders()
YAWK\Mobile_Detect::setCfHeaders ($cfHeaders = null)
Set CloudFront headers http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-device
Parameters
array $cfHeaders List of HTTP headers
Returns
boolean If there were CloudFront headers to be set
Definition at line 799 of file Mobile_Detect.php.
         {
             // use global _SERVER if $cfHeaders aren't defined
             if (!is_array($cfHeaders) || !count($cfHeaders)) {
                 $cfHeaders = $_SERVER;
             }
             // clear existing headers
             $this->cloudfrontHeaders = array();
             // Only save CLOUDFRONT headers. In PHP land, that means only _SERVER vars that
             // start with cloudfront-.
             $response = false;
             foreach ($cfHeaders as $key => $value) {
                 if (substr(strtolower($key), 0, 16) === 'http_cloudfront_') {
                     $this->cloudfrontHeaders[strtoupper($key)] = $value;
                     $response = true;
                 }
             }
             return $response;
         }
References $value, and as.
Referenced by YAWK\Mobile_Detect\setHttpHeaders().
setDetectionType()
YAWK\Mobile_Detect::setDetectionType ($type = null)
Set the detection type. Must be one of self::DETECTION_TYPE_MOBILE or self::DETECTION_TYPE_EXTENDED. Otherwise, nothing is set.
Deprecated:
since version 2.6.9
Parameters
string $type The type. Must be a self::DETECTION_TYPE_* constant. The default parameter is null which will default to self::DETECTION_TYPE_MOBILE.
Definition at line 895 of file Mobile_Detect.php.
         {
             if ($type === null) {
                 $type = self::DETECTION_TYPE_MOBILE;
             }
             if ($type !== self::DETECTION_TYPE_MOBILE && $type !== self::DETECTION_TYPE_EXTENDED) {
                 return;
             }
             $this->detectionType = $type;
         }
References $type, and YAWK\Mobile_Detect\DETECTION_TYPE_MOBILE.
Referenced by YAWK\Mobile_Detect\__call(), YAWK\Mobile_Detect\is(), YAWK\Mobile_Detect\isMobile(), and YAWK\Mobile_Detect\isTablet().
setHttpHeaders()
YAWK\Mobile_Detect::setHttpHeaders ($httpHeaders = null)
Set the HTTP Headers. Must be PHP-flavored. This method will reset existing headers.
Parameters
array $httpHeaders The headers to set. If null, then using PHP's _SERVER to extract the headers. The default null is left for backwards compatibility.
Definition at line 711 of file Mobile_Detect.php.
         {
             // use global _SERVER if $httpHeaders aren't defined
             if (!is_array($httpHeaders) || !count($httpHeaders)) {
                 $httpHeaders = $_SERVER;
             }
             // clear existing headers
             $this->httpHeaders = array();
             // Only save HTTP headers. In PHP land, that means only _SERVER vars that
             // start with HTTP_.
             foreach ($httpHeaders as $key => $value) {
                 if (substr($key, 0, 5) === 'HTTP_') {
                     $this->httpHeaders[$key] = $value;
                 }
             }
             // In case we're dealing with CloudFront, we need to know.
             $this->setCfHeaders($httpHeaders);
         }
References YAWK\Mobile_Detect\$httpHeaders, $value, as, and YAWK\Mobile_Detect\setCfHeaders().
Referenced by YAWK\Mobile_Detect\__construct(), YAWK\Mobile_Detect\is(), and YAWK\Mobile_Detect\isMobile().
setUserAgent()
YAWK\Mobile_Detect::setUserAgent ($userAgent = null)
Set the User-Agent to be used.
Parameters
string $userAgent The user agent string to set.
Returns
string|null
Definition at line 850 of file Mobile_Detect.php.
         {
             // Invalidate cache due to #375
             $this->cache = array();
             if (false === empty($userAgent)) {
                 return $this->userAgent = $this->prepareUserAgent($userAgent);
             } else {
                 $this->userAgent = null;
                 foreach ($this->getUaHttpHeaders() as $altHeader) {
                     if (false === empty($this->httpHeaders[$altHeader])) { // @todo: should use getHttpHeader(), but it would be slow. (Serban)
                         $this->userAgent .= $this->httpHeaders[$altHeader] . " ";
                     }
                 }
                 if (!empty($this->userAgent)) {
                     return $this->userAgent = $this->prepareUserAgent($this->userAgent);
                 }
             }
             if (count($this->getCfHeaders()) > 0) {
                 return $this->userAgent = 'Amazon CloudFront';
             }
             return $this->userAgent = null;
         }
References YAWK\Mobile_Detect\$userAgent, as, YAWK\Mobile_Detect\getCfHeaders(), YAWK\Mobile_Detect\getUaHttpHeaders(), YAWK\Mobile_Detect\prepareUserAgent(), and userAgent.
Referenced by YAWK\Mobile_Detect\__construct(), YAWK\Mobile_Detect\is(), and YAWK\Mobile_Detect\isMobile().
version()
YAWK\Mobile_Detect::version ($propertyName, $type = self::VERSION_TYPE_STRING)
Check the version of the given property in the User-Agent. Will return a float number. (eg. 2_0 will return 2.0, 4.3.1 will return 4.31)
Parameters
string $propertyName The name of the property. See self::getProperties() array keys for all possible properties.
string $type Either self::VERSION_TYPE_STRING to get a string value or self::VERSION_TYPE_FLOAT indicating a float value. This parameter is optional and defaults to self::VERSION_TYPE_STRING. Passing an invalid parameter will default to the this type as well.
Returns
string|float The version of the property we are trying to extract.
Definition at line 1313 of file Mobile_Detect.php.
         {
             if (empty($propertyName)) {
                 return false;
             }
             // set the $type to the default if we don't recognize the type
             if ($type !== self::VERSION_TYPE_STRING && $type !== self::VERSION_TYPE_FLOAT) {
                 $type = self::VERSION_TYPE_STRING;
             }
             $properties = self::getProperties();
             // Check if the property exists in the properties array.
             if (true === isset($properties[$propertyName])) {
                 // Prepare the pattern to be matched.
                 // Make sure we always deal with an array (string is converted).
                 $properties[$propertyName] = (array)$properties[$propertyName];
                 foreach ($properties[$propertyName] as $propertyMatchString) {
                     $propertyPattern = str_replace('[VER]', self::VER, $propertyMatchString);
                     // Identify and extract the version.
                     preg_match(sprintf('#%s#is', $propertyPattern), $this->userAgent, $match);
                     if (false === empty($match[1])) {
                         $version = ($type == self::VERSION_TYPE_FLOAT ? $this->prepareVersionNo($match[1]) : $match[1]);
                         return $version;
                     }
                 }
             }
             return false;
         }
References YAWK\Mobile_Detect\$properties, $type, as, YAWK\Mobile_Detect\getProperties(), YAWK\Mobile_Detect\prepareVersionNo(), userAgent, and YAWK\Mobile_Detect\VERSION_TYPE_STRING.
Referenced by YAWK\Mobile_Detect\mobileGrade().
Member Data Documentation
$browsers
YAWK\Mobile_Detect::$browsers static protected
Definition at line 521 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getBrowsers().
$cache
YAWK\Mobile_Detect::$cache = array() protected
Definition at line 84 of file Mobile_Detect.php.
$cloudfrontHeaders
YAWK\Mobile_Detect::$cloudfrontHeaders = array() protected
Definition at line 102 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getCfHeaders().
$detectionType
YAWK\Mobile_Detect::$detectionType = self::DETECTION_TYPE_MOBILE protected
Definition at line 126 of file Mobile_Detect.php.
$httpHeaders
YAWK\Mobile_Detect::$httpHeaders = array() protected
Definition at line 96 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getHttpHeaders(), YAWK\Mobile_Detect\is(), YAWK\Mobile_Detect\isMobile(), and YAWK\Mobile_Detect\setHttpHeaders().
$matchesArray
YAWK\Mobile_Detect::$matchesArray = null protected
Definition at line 117 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getMatchesArray().
$matchingRegex
YAWK\Mobile_Detect::$matchingRegex = null protected
Definition at line 109 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getMatchingRegex().
$mobileHeaders
YAWK\Mobile_Detect::$mobileHeaders static protected
Initial value:
= array(
            'HTTP_ACCEPT' => array('matches' => array(
                'application/x-obml2d',
                'application/vnd.rim.html',
                'text/vnd.wap.wml',
                'application/vnd.wap.xhtml+xml'
            )),
            'HTTP_X_WAP_PROFILE' => null,
            'HTTP_X_WAP_CLIENTID' => null,
            'HTTP_WAP_CONNECTION' => null,
            'HTTP_PROFILE' => null,
            'HTTP_X_OPERAMINI_PHONE_UA' => null,
            'HTTP_X_NOKIA_GATEWAY_ID' => null,
            'HTTP_X_ORANGE_ID' => null,
            'HTTP_X_VODAFONE_3GPDPCONTEXT' => null,
            'HTTP_X_HUAWEI_USERID' => null,
            'HTTP_UA_OS' => null,
            'HTTP_X_MOBILE_GATEWAY' => null,
            'HTTP_X_ATT_DEVICEID' => null,
            'HTTP_UA_CPU' => array('matches' => array('ARM')),
        )
Definition at line 134 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getMobileHeaders().
$operatingSystems
YAWK\Mobile_Detect::$operatingSystems static protected
Initial value:
= array(
            'AndroidOS' => 'Android',
            'BlackBerryOS' => 'blackberry|\bBB10\b|rim tablet os',
            'PalmOS' => 'PalmOS|avantgo|blazer|elaine|hiptop|palm|plucker|xiino',
            'SymbianOS' => 'Symbian|SymbOS|Series60|Series40|SYB-[0-9]+|\bS60\b',
            'WindowsMobileOS' => 'Windows CE.*(PPC|Smartphone|Mobile|[0-9]{3}x[0-9]{3})|Window Mobile|Windows Phone [0-9.]+|WCE;',
            'WindowsPhoneOS' => 'Windows Phone 10.0|Windows Phone 8.1|Windows Phone 8.0|Windows Phone OS|XBLWP7|ZuneWP7|Windows NT 6.[23]; ARM;',
            'iOS' => '\biPhone.*Mobile|\biPod|\biPad|AppleCoreMedia',
            'MeeGoOS' => 'MeeGo',
            'MaemoOS' => 'Maemo',
            'JavaOS' => 'J2ME/|\bMIDP\b|\bCLDC\b',
            'webOS' => 'webOS|hpwOS',
            'badaOS' => '\bBada\b',
            'BREWOS' => 'BREW',
        )
Definition at line 485 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getOperatingSystems().
$phoneDevices
YAWK\Mobile_Detect::$phoneDevices static protected
Definition at line 169 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getPhoneDevices().
$properties
YAWK\Mobile_Detect::$properties static protected
Definition at line 605 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getProperties(), and YAWK\Mobile_Detect\version().
$tabletDevices
YAWK\Mobile_Detect::$tabletDevices static protected
Definition at line 217 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getTabletDevices().
$uaHttpHeaders
YAWK\Mobile_Detect::$uaHttpHeaders static protected
Initial value:
= array(
            'HTTP_USER_AGENT',
            'HTTP_X_OPERAMINI_PHONE_UA',
            'HTTP_X_DEVICE_USER_AGENT',
            'HTTP_X_ORIGINAL_USER_AGENT',
            'HTTP_X_SKYFIRE_PHONE',
            'HTTP_X_BOLT_PHONE_UA',
            'HTTP_DEVICE_STOCK_UA',
            'HTTP_X_UCBROWSER_DEVICE_UA'
        )
Definition at line 585 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getUaHttpHeaders().
$userAgent
YAWK\Mobile_Detect::$userAgent = null protected
Definition at line 90 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\__construct(), YAWK\Mobile_Detect\getUserAgent(), YAWK\Mobile_Detect\is(), YAWK\Mobile_Detect\isMobile(), YAWK\Mobile_Detect\isTablet(), YAWK\Mobile_Detect\match(), YAWK\Mobile_Detect\matchDetectionRulesAgainstUA(), YAWK\Mobile_Detect\prepareUserAgent(), and YAWK\Mobile_Detect\setUserAgent().
$utilities
YAWK\Mobile_Detect::$utilities static protected
Initial value:
= array(
            'Bot' => 'Googlebot|facebookexternalhit|AdsBot-Google|Google Keyword Suggestion|Facebot|YandexBot|YandexMobileBot|bingbot|ia_archiver|AhrefsBot|Ezooms|GSLFbot|WBSearchBot|Twitterbot|TweetmemeBot|Twikle|PaperLiBot|Wotbox|UnwindFetchor|Exabot|MJ12bot|YandexImages|TurnitinBot|Pingdom',
            'MobileBot' => 'Googlebot-Mobile|AdsBot-Google-Mobile|YahooSeeker/M1A1-R2D2',
            'DesktopMode' => 'WPDesktop',
            'TV' => 'SonyDTV|HbbTV',
            'WebKit' => '(webkit)[ /]([\w.]+)',
            'Console' => '\b(Nintendo|Nintendo WiiU|Nintendo 3DS|Nintendo Switch|PLAYSTATION|Xbox)\b',
            'Watch' => 'SM-V700',
        )
Definition at line 564 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getUtilities().
DETECTION_TYPE_EXTENDED
const YAWK\Mobile_Detect::DETECTION_TYPE_EXTENDED = 'extended'
Extended detection type.
Deprecated:
since version 2.6.9
Definition at line 41 of file Mobile_Detect.php.
DETECTION_TYPE_MOBILE
const YAWK\Mobile_Detect::DETECTION_TYPE_MOBILE = 'mobile'
Mobile detection type.
Deprecated:
since version 2.6.9
Definition at line 34 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\setDetectionType().
MOBILE_GRADE_A
const YAWK\Mobile_Detect::MOBILE_GRADE_A = 'A'
Top-level device.
Definition at line 53 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\mobileGrade().
MOBILE_GRADE_B
const YAWK\Mobile_Detect::MOBILE_GRADE_B = 'B'
Mid-level device.
Definition at line 58 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\mobileGrade().
MOBILE_GRADE_C
const YAWK\Mobile_Detect::MOBILE_GRADE_C = 'C'
Low-level device.
Definition at line 63 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\mobileGrade().
VER
const YAWK\Mobile_Detect::VER = '([\w._\+]+)'
A frequently used regular expression to extract version s.
Deprecated:
since version 2.6.9
Definition at line 48 of file Mobile_Detect.php.
VERSION
const YAWK\Mobile_Detect::VERSION = '2.8.32'
Stores the version number of the current release.
Definition at line 68 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\getScriptVersion().
VERSION_TYPE_FLOAT
const YAWK\Mobile_Detect::VERSION_TYPE_FLOAT = 'float'
A type for the version() method indicating a float return value.
Definition at line 78 of file Mobile_Detect.php.
VERSION_TYPE_STRING
const YAWK\Mobile_Detect::VERSION_TYPE_STRING = 'text'
A type for the version() method indicating a string return value.
Definition at line 73 of file Mobile_Detect.php.
Referenced by YAWK\Mobile_Detect\version().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/mobiledetect/Mobile_Detect.php