YaWK: YAWK\WIDGETS\PLYR\PLAYER\plyr Class Reference
YAWK\WIDGETS\PLYR\PLAYER\plyr Class Reference
Plyr HTML5 Media Player Widget.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
checkMediaFileType ()
Check and set media file type.
checkTextTrack ()
embedPlyr ()
init ()
Init example widget and call a function for demo purpose.
setPoster ()
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$plyrAutoplay = false
$plyrClickToPlay = true
$plyrDisableContextMenu = true
$plyrFiletype = ''
$plyrHeading = ''
$plyrHideControls = true
$plyrMediaFile = ''
$plyrPoster = ''
$plyrPosterHtml = ''
$plyrShowPosterOnEnd = false
$plyrSubtext = ''
$plyrTextTrackFile = ''
$plyrTextTrackFileHtmlOutput = ''
$plyrTextTrackLabel = ''
$plyrTextTrackSrcLang = ''
$plyrWidth = '100%'
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Plyr HTML5 Media Player Widget.
Plyr Widget - html5 based video player
Plyr is a a simple, accessible and customisable and wide-known media player for HTML 5 Video, Audio, YouTube, and Vimeo. All you need is the url to your media file. As you wish, you can set some settings like width, height, poster image, media control functions, autoplay and much more.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file plyr.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\PLYR\PLAYER\plyr::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 59 of file plyr.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
checkMediaFileType()
YAWK\WIDGETS\PLYR\PLAYER\plyr::checkMediaFileType ()
Check and set media file type.
check and set media file type
Definition at line 90 of file plyr.php.
         {
             if (isset($this->plyrMediaFile) && (!empty($this->plyrMediaFile)))
             {
                 if (strpos($this->plyrMediaFile, '.mp4') !== false)
                 {
                     $this->plyrFiletype = "video/mp4";
                 }
                 if (strpos($this->plyrMediaFile, '.webm') !== false)
                 {
                     $this->plyrFiletype = "video/webm";
                 }
             }
             else
                 {
                     echo "Plyr Error: unable to detect media file type - no file was set!";
                 }
Referenced by YAWK\WIDGETS\PLYR\PLAYER\plyr\init().
checkTextTrack()
YAWK\WIDGETS\PLYR\PLAYER\plyr::checkTextTrack ()
Definition at line 121 of file plyr.php.
         {
             // check if text track file, language and label are set
             if (isset($this->plyrTextTrackFile) && (!empty($this->plyrTextTrackFile)))
             {   // language not found
                 if (!isset($this->plyrTextTrackSrcLang) || (empty($this->plyrTextTrackSrcLang)))
                 {   // set default language:
                     $this->plyrTextTrackSrcLang = "en";
                 }
                 // label is not set
                 if (!isset($this->plyrTextTrackLabel) || (empty($this->plyrTextTrackLabel)))
                 {   // set default label:
                     $this->plyrTextTrackLabel = "English";
                 }
                 // output text track html...
                 $this->plyrTextTrackFileHtmlOutput = "<track kind=\"captions\" label=\"$this->plyrTextTrackLabel\" srclang=\"$this->plyrTextTrackSrcLang\" src=\"$this->plyrTextTrackFile\" default>";
             }
             else
             {   // no text track is set, output nothing
                 $this->plyrTextTrackFileHtmlOutput = '';
             }
Referenced by YAWK\WIDGETS\PLYR\PLAYER\plyr\init().
embedPlyr()
YAWK\WIDGETS\PLYR\PLAYER\plyr::embedPlyr ()
Definition at line 144 of file plyr.php.
         {
             echo '
             <!-- output plyr html player -->
             <section>
                 <video '.$this->plyrPosterHtml.' controls style="width: '.$this->plyrWidth.'">
                     <source src="'.$this->plyrMediaFile.'" type="'.$this->plyrFiletype.'">
                     <!-- Text track file -->
                     '.$this->plyrTextTrackFileHtmlOutput.'
                     <!-- Fallback for browsers that dont support the <video> element -->
                     <a href="'.$this->plyrMediaFile.'" download>Download</a>
                 </video>
             </section>
             <!-- plyr js -->
             <script src="system/widgets/plyr/js/plyr.js"></script>
             <!-- run plyr -->
             <script>
             plyr.setup({
                 "autoplay":'.$this->plyrAutoplay.',
                 "disableContextMenu": '.$this->plyrDisableContextMenu.',
                 "hideControls": '.$this->plyrHideControls.',
                 "showPosterOnEnd": '.$this->plyrShowPosterOnEnd.',
                 "clickToPlay": '.$this->plyrClickToPlay.'
             });
             </script>
             <!-- plyr css -->
             <link type="text/css" rel="stylesheet" href="system/widgets/plyr/js/plyr.css">
             <!-- Rangetouch to fix <input type="range"> on touch devices (see https://rangetouch.com) -->
             <script src="system/widgets/plyr/js/rangetouch.js" async></script>';
Referenced by YAWK\WIDGETS\PLYR\PLAYER\plyr\init().
init()
YAWK\WIDGETS\PLYR\PLAYER\plyr::init ()
Init example widget and call a function for demo purpose.
Example Widget Init
Definition at line 73 of file plyr.php.
         {   // call any functions or methods you have previously defined in this class
             echo $this->getHeading($this->plyrHeading, $this->plyrSubtext);
             // check and set media file type
             $this->checkMediaFileType();
             // check and set poster image
             $this->setPoster();
             // check and set text track
             $this->checkTextTrack();
             // finally: embed plyr media player
             $this->embedPlyr();
References YAWK\WIDGETS\PLYR\PLAYER\plyr\checkMediaFileType(), YAWK\WIDGETS\PLYR\PLAYER\plyr\checkTextTrack(), YAWK\WIDGETS\PLYR\PLAYER\plyr\embedPlyr(), YAWK\widget\getHeading(), and YAWK\WIDGETS\PLYR\PLAYER\plyr\setPoster().
setPoster()
YAWK\WIDGETS\PLYR\PLAYER\plyr::setPoster ()
Definition at line 109 of file plyr.php.
         {
             if (isset($this->plyrPoster) && (!empty($this->plyrPoster)))
             {   // poster is set...
                 $this->plyrPosterHtml = "poster=\"$this->plyrPoster\"";
             }
             else
             {   // no poster set, leave output empty
                 $this->plyrPosterHtml = "poster=\"\"";
             }
Referenced by YAWK\WIDGETS\PLYR\PLAYER\plyr\init().
Member Data Documentation
$plyrAutoplay
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrAutoplay = false
Parameters
bool Autoplay true|false
Definition at line 44 of file plyr.php.
$plyrClickToPlay
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrClickToPlay = true
Parameters
bool Click to play true|false
Definition at line 46 of file plyr.php.
$plyrDisableContextMenu
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrDisableContextMenu = true
Parameters
bool Context Menus enabled?
Definition at line 48 of file plyr.php.
$plyrFiletype
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrFiletype = ''
Parameters
string The media file type
Definition at line 28 of file plyr.php.
$plyrHeading
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 22 of file plyr.php.
$plyrHideControls
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrHideControls = true
Parameters
bool Hide player controls true|false
Definition at line 50 of file plyr.php.
$plyrMediaFile
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrMediaFile = ''
Parameters
string URL of the media file to play
Definition at line 26 of file plyr.php.
$plyrPoster
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrPoster = ''
Parameters
string Poster Image
Definition at line 32 of file plyr.php.
$plyrPosterHtml
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrPosterHtml = ''
Parameters
string Poster Html Markup
Definition at line 34 of file plyr.php.
$plyrShowPosterOnEnd
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrShowPosterOnEnd = false
Parameters
bool Display poster on video end true|false
Definition at line 52 of file plyr.php.
$plyrSubtext
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 24 of file plyr.php.
$plyrTextTrackFile
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrTextTrackFile = ''
Parameters
string Text Track File
Definition at line 36 of file plyr.php.
$plyrTextTrackFileHtmlOutput
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrTextTrackFileHtmlOutput = ''
Parameters
string Text Track Html Markup
Definition at line 38 of file plyr.php.
$plyrTextTrackLabel
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrTextTrackLabel = ''
Parameters
string Text Track Label
Definition at line 40 of file plyr.php.
$plyrTextTrackSrcLang
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrTextTrackSrcLang = ''
Parameters
string Text Track Src Language
Definition at line 42 of file plyr.php.
$plyrWidth
YAWK\WIDGETS\PLYR\PLAYER\plyr::$plyrWidth = '100%'
Parameters
string Player width in pixel or %
Definition at line 30 of file plyr.php.
$widget
YAWK\WIDGETS\PLYR\PLAYER\plyr::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file plyr.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/plyr/classes/plyr.php