YaWK: YAWK\BACKUP\FILES\fileBackup Class Reference
YAWK\BACKUP\FILES\fileBackup Class Reference
Public Member Functions
copyFolder ($db, $folder, $targetFolder)
Copy a folder from source to target, including all subdirectories.
doFolderBackup ($db)
Copy files to tmp folder, zip it and move it to the place where this backup should be stored (current or archive...)
getHashValue ($db, $file)
Get and return hash value of $file.
initFolderBackup (object $db, string $overwriteBackup, string $zipBackup)
Initialize and start file backup.
setBackupSettings ()
Write backup.ini file (used by backup restore methods)
startFileBackup ($db)
Check settings and start file backup.
zipFileExists ()
Check if .zip backup file exists.
Public Member Functions inherited from YAWK\BACKUP\backup
__construct ($db)
backup constructor. prepare temp folder on class instantiation
checkFolders ($restoreFolders)
check restore folders, check + set permissions of restore folders
checkPermissions ($folder)
check folder permissions and return permissions as string (eg 0755)
checkZipFunction ()
Check if ZipArchive function exists.
doRestore ($db, $restoreFolders)
Restore Data physically to folder, restore .sql file to database if needed.
getArchiveBackupFilesArray ()
get all files from archive backup folder into array
getCurrentBackupFilesArray ()
get all files from current backup folder into array
init ($db)
Init Backup Class (run backup)
parseIniFile ($db, $iniFile)
Parse backup ini file.
restore ($db, $file, $folder)
Manage how a backup will be restored from backup folder.
run ($db)
Run a new backup, depending on chosen backup method.
runDatabaseBackup ($db, $storeSqlTmp)
Include mysql backup class and run mysqldump backup.
runFileBackup ($db)
Run File Backup from $sourceFolder.
setIniFile (object $db)
Set backup information file (backup.ini)
setPermissions ($folder, $filemode)
set folder permissions and do some chmod stuff to with given $filemode to $folder
zipFolder ($db, $source, $destination)
Zip a whole folder from $source to $destination.zip.
Public Attributes
$backupZipFile = 'backup-custom.zip'
$contentFolder = '../content/'
$currentFolder = ''
$finalFilename = ''
$hashValue = ''
$mediaFolder = '../media/'
$sourceFolder = ''
$systemFolder = '../system/'
$targetFolder = '../system/backup/current/'
$zip
Public Attributes inherited from YAWK\BACKUP\backup
$archiveBackupFile = ''
$archiveBackupFiles = array()
$archiveBackupFolder = '../system/backup/archive/'
$archiveBackupNewFile = ''
$archiveBackupSubFolder = ''
$archiveBackupSubFolders = array()
$backupMethod = "database"
$backupSettings = array()
$configFile = ''
$configFilename = "backup.ini"
$currentBackupFiles = array()
$currentBackupFolder = '../system/backup/current/'
$downloadFolder = '../system/backup/download/'
$fileBackup
$mysqlBackup
$overwriteBackup = "true"
$removeAfterZip = "true"
$restoreFile = ''
$restoreFiles = array()
$restoreFolder = ''
$restoreFolders = array()
$restoreMode = ''
$restoreStatus = array()
$sourceFolder = ''
$storeSqlTmp = "false"
$targetFolder = '../system/backup/current/'
$tmpFolder = '../system/backup/tmp/'
$zipBackup = "true"
Detailed Description
Definition at line 14 of file backup-fileBackup.php.
Member Function Documentation
copyFolder()
YAWK\BACKUP\FILES\fileBackup::copyFolder ($db, $folder, $targetFolder)
Copy a folder from source to target, including all subdirectories.
Parameters
$db
$folder
$targetFolder
Returns
bool
Definition at line 425 of file backup-fileBackup.php.
         {
             // set source folder
             $this->sourceFolder = $this->currentFolder.$folder;
             // set target folder
             $this->targetFolder = $targetFolder;
             // copy source folder to target folder
             if (\YAWK\sys::xcopy($this->sourceFolder, $this->targetFolder) === false)
             {   // failed to copy content folder
                 \YAWK\sys::setSyslog($db, 52, 2, "failed to copy $this->sourceFolder to $this->targetFolder", 0, 0, 0, 0);
                 return false;
             }
             else
                 {   // copy folder successful
                     return true;
                 }
References $db, YAWK\BACKUP\FILES\fileBackup\$targetFolder, and YAWK\sys\xcopy().
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
doFolderBackup()
YAWK\BACKUP\FILES\fileBackup::doFolderBackup ($db)
Copy files to tmp folder, zip it and move it to the place where this backup should be stored (current or archive...)
return bool if $this->backupZipFile exists
Returns
bool true|false
Definition at line 134 of file backup-fileBackup.php.
         {
             // check if temp folder is writeable
             if (!is_writeable($this->tmpFolder) && (!empty($this->tmpFolder)))
             {   // tmp folder not writeable...
                 return false;
             }
             // CONTENT FOLDER PROCESSING
             if (isset($_POST['contentFolder']) && (!empty($_POST['contentFolder'])))
             {   // create content folder
                 if (!is_dir($this->tmpFolder.'content'))
                 {
                     if (!mkdir($this->tmpFolder . 'content'))
                     {
                         // return false
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create " . $this->tmpFolder . "content", 0, 0, 0, 0);
                     }
                 }
                 // walk through content folder subdirectories
                 foreach ($_POST['contentFolder'] as $folder)
                 {
                     // set current content folder property
                     $this->currentFolder = $this->contentFolder;
                     $this->targetFolder = $this->tmpFolder.'content/';
                     // check if parent dir exists
                     if (is_dir($this->currentFolder.$folder))
                     {
                         // check if subdir NOT exists
                         if (!is_dir($this->targetFolder.$folder))
{
                             // create subdir
                             mkdir($this->targetFolder.$folder);
                             $this->targetFolder = $this->tmpFolder.'content/'.$folder;
                         }
                         else
                             {   // subdir exists, set target path
                                 $this->targetFolder = $this->tmpFolder.'content/'.$folder;
                             }
                     }
                     // copy content subfolder
                     if ($this->copyFolder($db, $folder, $this->targetFolder) !== true)
                     {
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create ".$this->contentFolder."$folder", 0, 0, 0, 0);
                     }
                 }
             }
             // MEDIA FOLDER PROCESSING
             if (isset($_POST['mediaFolder']) && (!empty($_POST['mediaFolder'])))
             {   // create content folder
                 if (!is_dir($this->tmpFolder.'media'))
                 {
                     if (!mkdir($this->tmpFolder . 'media'))
                     {
                         // return false
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create " . $this->tmpFolder . "media", 0, 0, 0, 0);
                     }
                 }
                 // walk through content folder subdirectories
                 foreach ($_POST['mediaFolder'] as $folder)
                 {
                     // set current content folder property
                     $this->currentFolder = $this->mediaFolder;
                     $this->targetFolder = $this->tmpFolder.'media/';
                     // check if parent dir exists
                     if (is_dir($this->currentFolder.$folder))
                     {
                         // check if subdir NOT exists
                         if (!is_dir($this->targetFolder.$folder))
{
                             // create subdir
                             mkdir($this->targetFolder.$folder);
                             $this->targetFolder = $this->tmpFolder.'media/'.$folder;
                         }
                         else
                         {   // subdir exists, set target path
                             $this->targetFolder = $this->tmpFolder.'media/'.$folder;
                         }
                     }
                     // copy media subfolder
                     if ($this->copyFolder($db, $folder, $this->targetFolder) !== true)
                     {
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create ".$this->mediaFolder."$folder", 0, 0, 0, 0);
                     }
                 }
             }
             // SYSTEM FOLDER PROCESSING
             if (isset($_POST['systemFolder']) && (!empty($_POST['systemFolder'])))
             {   // create content folder
                 if (!is_dir($this->tmpFolder.'system'))
                 {
                     if (!mkdir($this->tmpFolder . 'system'))
                     {
                         // return false
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create " . $this->tmpFolder . "system", 0, 0, 0, 0);
                     }
                 }
                 // walk through system folder subdirectories
                 foreach ($_POST['systemFolder'] as $folder)
                 {
                     // set current content folder property
                     $this->currentFolder = $this->systemFolder;
                     $this->targetFolder = $this->tmpFolder.'system/';
                     // check if parent dir exists
                     if (is_dir($this->currentFolder.$folder))
                     {
                         // check if subdir NOT exists
                         if (!is_dir($this->targetFolder.$folder))
{
                             // create subdir
                             mkdir($this->targetFolder.$folder);
                             $this->targetFolder = $this->tmpFolder.'system/'.$folder;
                         }
                         else
                         {   // subdir exists, set target path
                             $this->targetFolder = $this->tmpFolder.'system/'.$folder;
                         }
                     }
                     // copy system subfolder
                     if ($this->copyFolder($db, $folder, $this->targetFolder) !== true)
                     {
                         \YAWK\sys::setSyslog($db, 51, 2, "failed to create ".$this->systemFolder."$folder", 0, 0, 0, 0);
                     }
                 }
             }
             // PREPARE FINAL FILENAME
             // set filename of backup .zip archive (including path to tmp folder)
             // check, which filename the backup should have:
             if (isset($_POST['backupMethod']) && (!empty($_POST['backupMethod'])))
             {
                 switch ($_POST['backupMethod'])
                 {
                     case "complete" :
                     {
                         $this->finalFilename = "complete-backup.zip";
                         $this->backupMethod = "complete";
                     }
                     break;
                     case "mediaFolder" :
                     {
                         $this->finalFilename = "mediafolder-backup.zip";
                         $this->backupMethod = "mediaFolder";
                     }
                     break;
                     case "custom" :
                     {
                         $this->finalFilename = "custom-backup.zip";
                         $this->backupMethod = "custom";
                     }
                     break;
                     default:
                     {
                         $this->finalFilename = "backup.zip";
                         $this->backupMethod = "unknown";
                     }
                 }
             }
             // set backup settings
             $this->backupSettings = $this->setBackupSettings();
             // check if ini file was written
             if (\YAWK\sys::writeIniFile($this->backupSettings, $this->tmpFolder.$this->configFilename) === true)
             {
                 // check if config file is there
                 if (!is_file($this->tmpFolder.$this->configFilename))
                 {   // config file not found
                     \YAWK\sys::setSyslog($db, 51, 1, "backup ini file written, but not found - please check: $this->configFilename", 0, 0, 0, 0);
                     return false;
                 }
             }
             // ZIP FOLDER + COPY TO FINAL DESTINATION
             // try to zip the whole tmp/ folder
             if ($this->zipFolder($db, $this->tmpFolder, $this->tmpFolder."$this->finalFilename") == true)
             {
                 // check if POST data is sent
                 if (isset($_POST))
                 {
                     // check if backup overwrite is allowed
                     if (isset($_POST['overwriteBackup']) && ($_POST['overwriteBackup'] == "false"))
                     {
                         // check if new folder was entered by user
                         if (isset($_POST['newFolder']) && (!empty($_POST['newFolder'])))
{
                             // create new archive sub folder path
                             $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['newFolder']."/";
                             // create new directory in archive
                             if (!is_dir($this->archiveBackupSubFolder))
{
                                 if (mkdir($this->archiveBackupSubFolder))
                                 {   // all good, new archive subfolder created
                                     // set syslog entry: dir created
                                     \YAWK\sys::setSyslog($db, 49, 0, "archive directory created: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                                 }
                                 else
                                 {   // failed to create new archive subfolder
                                     // set syslog entry: failed
                                     \YAWK\sys::setSyslog($db, 52, 0, "failed to create archive directory: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                                 }
                             }
                         }
                         // check if existing folder was selected by user
                         else if (isset($_POST['selectFolder']) && (!empty($_POST['selectFolder'])))
                         {   // set archive sub foder path
                             $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['selectFolder']."/";
                         }
                         // STORE TO ARCHIVE FOLDER
                         // move final *****-backup .zip to archive backup folder
                         if (rename($this->tmpFolder.$this->finalFilename, $this->archiveBackupSubFolder.$this->finalFilename))
                         {   // check if final filename exists
                             if (is_file($this->archiveBackupSubFolder.$this->finalFilename))
{
                                 // ok, delete tmp folder recursive
                                 \YAWK\sys::recurseRmdir($this->tmpFolder);
                                 // set positive syslog entry
                                 \YAWK\sys::setSyslog($db, 49, 3, "created ".$this->archiveBackupSubFolder."$this->finalFilename", 0, 0, 0, 0);
                                 return true;
                             }
                             else
                                 {   // failed to create backup
                                     \YAWK\sys::setSyslog($db, 52, 0, "failed to create ".$this->archiveBackupSubFolder."$this->finalFilename", 0, 0, 0, 0);
                                     return false;
                                 }
                         }
                         else
                             {   // failed to move final backup file
                                 \YAWK\sys::setSyslog($db, 52, 0, "failed to move ".$this->archiveBackupSubFolder."$this->finalFilename", 0, 0, 0, 0);
                                 return false;
                             }
                     }
                     else
                     {   // STORE TO CURRENT FOLDER
                         // move final *****-backup .zip to current backup folder
                         if (rename($this->tmpFolder.$this->finalFilename, $this->currentBackupFolder.$this->finalFilename))
{
                             // check if final backup file is available in current folder
                             if (is_file($this->currentBackupFolder.$this->finalFilename))
                             {   // ok, remove tmp dir recursivly
                                 \YAWK\sys::recurseRmdir($this->tmpFolder);
                                 // set positive syslog entry
                                 \YAWK\sys::setSyslog($db, 49, 3, "created ".$this->currentBackupFolder."$this->finalFilename", 0, 0, 0, 0);
                                 return true;
                             }
                             else
                             {   // failed to create current backup
                                 \YAWK\sys::setSyslog($db, 52, 0, "failed to create ".$this->currentBackupFolder."$this->finalFilename", 0, 0, 0, 0);
                                 return false;
                             }
                         }
                         else
                         {   // failed to move backup archive to current folder
                             \YAWK\sys::setSyslog($db, 52, 0, "failed to move ".$this->currentBackupFolder."$this->finalFilename", 0, 0, 0, 0);
                             return false;
                         }
                     }
                 }
                 else
                     {   // post data not sent
                         \YAWK\sys::setSyslog($db, 52, 0, "failed to backup: POST data not sent", 0, 0, 0, 0);
                         return true;
                     }
             }
             else
                 {   // failed to zip final backup file
                     \YAWK\sys::setSyslog($db, 52, 0, "unable to zip ".$this->finalFilename."", 0, 0, 0, 0);
                     return false;
                 }
References YAWK\BACKUP\FILES\fileBackup\$contentFolder, $db, $folder, YAWK\BACKUP\FILES\fileBackup\$mediaFolder, YAWK\BACKUP\FILES\fileBackup\$systemFolder, YAWK\BACKUP\FILES\fileBackup\copyFolder(), YAWK\sys\recurseRmdir(), YAWK\BACKUP\FILES\fileBackup\setBackupSettings(), YAWK\sys\writeIniFile(), and YAWK\BACKUP\backup\zipFolder().
Referenced by YAWK\BACKUP\FILES\fileBackup\startFileBackup().
getHashValue()
YAWK\BACKUP\FILES\fileBackup::getHashValue ($db, $file)
Get and return hash value of $file.
return hashed string or false
Returns
string|bool
Definition at line 108 of file backup-fileBackup.php.
         {
             // check if file is set
             if (!isset($file) || (empty($file)))
             {   // file not set
                 return false;
             }
             // check if sql backup file is accessable
             if (is_file($file))
             {   // generate hash value
                 return $this->hashValue = hash_file('md5', $file);
             }
             else
             {   // file not found: unable to generate hash value
                 \YAWK\sys::setSyslog($db, 52, 2, "failed to generate hash value - $file is not accessable", 0, 0, 0, 0);
                 return false;
             }
References $db.
initFolderBackup()
YAWK\BACKUP\FILES\fileBackup::initFolderBackup (object $db, string $overwriteBackup, string $zipBackup)
Initialize and start file backup.
Parameters
object $db database object
string $overwriteBackup if overwrite backup is allowed or not "true" | "false"
string $zipBackup if backup should be zipped or not "true" | "false"
Returns
bool
Version
1.0.0 Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Definition at line 48 of file backup-fileBackup.php.
                                                                                                 : bool
         {
             // start file backup
             $this->overwriteBackup = $overwriteBackup;
             $this->zipBackup = $zipBackup;
             if ($this->startFileBackup($db) === true)
             {   // file backup done
                 return true;
             }
             else
             {   // file backup failed
                 return false;
             }
References YAWK\BACKUP\backup\$overwriteBackup, YAWK\BACKUP\backup\$zipBackup, and YAWK\BACKUP\FILES\fileBackup\startFileBackup().
setBackupSettings()
YAWK\BACKUP\FILES\fileBackup::setBackupSettings ()
Write backup.ini file (used by backup restore methods)
write all relevant backup information into this file
Returns
array $this->backupSettings
Definition at line 92 of file backup-fileBackup.php.
         {
             // set some backup info variables
             $this->backupSettings['DATE'] = \YAWK\sys::now();
             $this->backupSettings['METHOD'] = $this->backupMethod;
             $this->backupSettings['FILE'] = $this->finalFilename;
             $this->backupSettings['PATH'] = $this->targetFolder;
             $this->backupSettings['USER_ID'] = $_SESSION['uid'];
             return $this->backupSettings;
References YAWK\BACKUP\backup\$backupMethod, YAWK\BACKUP\backup\$backupSettings, YAWK\BACKUP\FILES\fileBackup\$finalFilename, YAWK\BACKUP\FILES\fileBackup\$targetFolder, and YAWK\sys\now().
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
startFileBackup()
YAWK\BACKUP\FILES\fileBackup::startFileBackup ($db)
Check settings and start file backup.
return bool if zip archive exists
Returns
bool true|false
Definition at line 449 of file backup-fileBackup.php.
         {
             // check if backup overwrite is allowed
             if ($this->overwriteBackup == "false")
             {   // check if POST array is set (form was sent)
                 if (isset($_POST))
                 {
                     // check if new folder was entered by user
                     if (isset($_POST['newFolder']) && (!empty($_POST['newFolder'])))
                     {
                         // create new archive sub folder path
                         $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['newFolder']."/";
                         // create new directory in archive
                         if (!is_dir($this->archiveBackupSubFolder))
                         {   // try to create archive subfolder
                             if (mkdir($this->archiveBackupSubFolder))
                             {   // all good, new archive subfolder created
                                 // set syslog entry: dir created
                                 \YAWK\sys::setSyslog($db, 49, 0, "archive directory created: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                             }
                             else
                             {   // failed to create new archive subfolder
                                 // set syslog entry: failed
                                 \YAWK\sys::setSyslog($db, 52, 0, "failed to create archive directory: $this->archiveBackupSubFolder", 0, 0, 0, 0);
                             }
                         }
                     }
                     // check if existing folder was selected by user
                     else if (isset($_POST['selectFolder']) && (!empty($_POST['selectFolder'])))
                     {   // set archive sub folder path
                         $this->archiveBackupSubFolder = $this->archiveBackupFolder.$_POST['selectFolder']."/";
                     }
                     // set backup target folder
                     $this->targetFolder = $this->archiveBackupSubFolder;
                 }
             }
             // check if a backup exists
             if ($this->zipFileExists() === true)
             {
                 // do folder backup
                 if ($this->doFolderBackup($db) === true)
                 {   // ok, backup done
                     \YAWK\sys::setSyslog($db, 50, 3, "file backup overwritten", 0, 0, 0, 0);
                     return true;
                 }
                 else
                 {   // backup failed - unable to overwrite - check chmod settings!
                     \YAWK\sys::setSyslog($db, 52, 2, "failed to overwrite file backup", 0, 0, 0, 0);
                     return false;
                 }
             }
             else
             {   // file does not exist - do file backup
                 if ($this->doFolderBackup($db) === true)
                 {   // ok, backup done!
                     // \YAWK\sys::setSyslog($db, 50, 3, "created file backup", 0, 0, 0, 0);
                     return true;
                 }
                 else
                 {   // backup failed!
                     \YAWK\sys::setSyslog($db, 52, 2, "failed to write file backup", 0, 0, 0, 0);
                     return false;
                 }
             }
References YAWK\BACKUP\backup\$archiveBackupSubFolder, $db, YAWK\BACKUP\FILES\fileBackup\doFolderBackup(), and YAWK\BACKUP\FILES\fileBackup\zipFileExists().
Referenced by YAWK\BACKUP\FILES\fileBackup\initFolderBackup().
zipFileExists()
YAWK\BACKUP\FILES\fileBackup::zipFileExists ()
Check if .zip backup file exists.
return bool if $this->backupZipFile exists
Returns
bool true|false
Definition at line 70 of file backup-fileBackup.php.
                                        : bool
         {
             // set path + filename (store as string in $this->backupZipFile)
             $this->backupZipFile = $this->targetFolder.$this->backupZipFile;// .sql backup file exists
             // check if .zip file is already there
             if (is_file($this->backupZipFile))
             {
                 // .zip file exists
                 return true;
             }
             else
             {
                 // .zip file does not exist
                 return false;
             }
Referenced by YAWK\BACKUP\FILES\fileBackup\startFileBackup().
Member Data Documentation
$backupZipFile
YAWK\BACKUP\FILES\fileBackup::$backupZipFile = 'backup-custom.zip'
Parameters
string default filename of .zip file
Definition at line 23 of file backup-fileBackup.php.
$contentFolder
YAWK\BACKUP\FILES\fileBackup::$contentFolder = '../content/'
Parameters
string content folder
Definition at line 27 of file backup-fileBackup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
$currentFolder
YAWK\BACKUP\FILES\fileBackup::$currentFolder = ''
Parameters
string current processing folder
Definition at line 33 of file backup-fileBackup.php.
$finalFilename
YAWK\BACKUP\FILES\fileBackup::$finalFilename = ''
Parameters
string final filename
Definition at line 35 of file backup-fileBackup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\setBackupSettings().
$hashValue
YAWK\BACKUP\FILES\fileBackup::$hashValue = ''
Parameters
string hash value of .zip file
Definition at line 25 of file backup-fileBackup.php.
$mediaFolder
YAWK\BACKUP\FILES\fileBackup::$mediaFolder = '../media/'
Parameters
string media folder
Definition at line 29 of file backup-fileBackup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
$sourceFolder
YAWK\BACKUP\FILES\fileBackup::$sourceFolder = ''
Parameters
string source folder to backup
Definition at line 19 of file backup-fileBackup.php.
$systemFolder
YAWK\BACKUP\FILES\fileBackup::$systemFolder = '../system/'
Parameters
string system folder
Definition at line 31 of file backup-fileBackup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
$targetFolder
YAWK\BACKUP\FILES\fileBackup::$targetFolder = '../system/backup/current/'
Parameters
string path, where the backup will be stored
Definition at line 21 of file backup-fileBackup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\copyFolder(), and YAWK\BACKUP\FILES\fileBackup\setBackupSettings().
$zip
YAWK\BACKUP\FILES\fileBackup::$zip
Parameters
object zip object
Definition at line 17 of file backup-fileBackup.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/backup-fileBackup.php