YaWK: YAWK\db Class Reference
YAWK\db Class Reference
Mysqli database class; returns db connection object.
Public Member Functions
__construct ()
beginTransaction ()
clearResults ()
close ()
commit ()
connect ()
Connect to the database.
deleteDatabase ($database)
Delete a whole database (including all tables)
dropTables ($tables)
Drop table from a database.
error ()
Fetch last error from the database.
get_tables ()
Get all tables from a database and return as array.
import ($sqlfile, $lang)
Import data from .sql file into database.
more_results ()
Checks if there are more query results from a multi query.
multi_query ($query)
next_result ()
Move to next result set of a multi query.
prepare ($sql)
query ($query)
Execute any sql query.
quote ($value)
Quote and escape value for use in a database query *.
real_escape_string ($migrationSql)
rollback ()
select ($query)
Fetch rows from database (SELECT query)
Public Attributes
$config
$connection
Detailed Description
Mysqli database class; returns db connection object.
Database class - connect to mysqli and return connection object
This class establish the database connection if none already exists. It serves some handy methods as well, like quote data, get and delete tables, import .sql files, as well as typical select and query methods.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2012-2018 Daniel Retzl yawk.io @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 16 of file db.php.
Constructor & Destructor Documentation
__construct()
YAWK\db::__construct ()
db constructor - Include the database config file
Definition at line 26 of file db.php.
         {   // include config array
             require_once ("dbconfig.php");
Member Function Documentation
beginTransaction()
YAWK\db::beginTransaction ()
Exceptions
Exception
Definition at line 74 of file db.php.
                                           : void
         {
             $this->connection->begin_transaction();
clearResults()
YAWK\db::clearResults ()
Clear all pending result sets after a multi-query
Returns
bool true if successful, false otherwise
Definition at line 171 of file db.php.
         {
             try
             {
                 // Check if there are more result sets available
                 while ($this->connection->more_results() && $this->connection->next_result())
                 {
                     // Store the current result set
                     $result = $this->connection->store_result();
                     // Free the current result set
                     if ($result !== false)
                     {
                         $result->free();
                     }
                 }
                 return true;
             }
             catch (\Exception $e)
             {
                 error_log("Error clearing result sets: " . $e->getMessage());
                 return false;
             }
References $result.
close()
YAWK\db::close ()
Definition at line 66 of file db.php.
                                : void
         {
             $this->connection->close();
commit()
YAWK\db::commit ()
Definition at line 89 of file db.php.
                                 : void
         {   // commit transaction
             $this->connection->commit();
connect()
YAWK\db::connect ()
Connect to the database.
Returns
object|bool false on failure / mysqli MySQLi object instance on success
Exceptions
Exception
Definition at line 36 of file db.php.
                                  : object|bool
         {
             // if connection is not set
             if (!isset($this->connection))
             {
                 try {
                     // create new database object
                     $this->connection = new \mysqli(
                         $this->config['server'],
                         $this->config['username'],
                         $this->config['password'],
                         $this->config['dbname'],
                         $this->config['port']
                     );
                     // connection established successfully
                     return $this->connection;
                 } catch (\mysqli_sql_exception $e) {
                     // failed to connect to database (wrong credentials?)
                     throw new Exception('Failed to connect to database: ' . $e->getMessage());
                 } catch (Exception $e) {
                     throw new Exception('Database connection error: ' . $e->getMessage());
                 }
             }
             else
             {
                 // connection already established...
                 return $this->connection;
             }
References YAWK\db\$connection, and config.
Referenced by YAWK\db\error(), YAWK\db\query(), and YAWK\db\quote().
deleteDatabase()
YAWK\db::deleteDatabase ($database)
Delete a whole database (including all tables)
Parameters
$database
Definition at line 367 of file db.php.
                                                  : bool
         {
             $deletedTables = 0;
             $errors = 0;
             // get all tables as array
             $result = $this->query("SHOW TABLES IN `$database`");
             // check if result is set
             if (isset($result) && (!empty($result)))
             {
                 // walk through result array
                 while ($table = mysqli_fetch_array($result))
                 {   // store tablename in var
                     $tableName = $table[0];
                     // try to delete table
                     if ($this->query("DROP TABLE `$database`.`$tableName`"))
                     {   // output(?)
                         //echo "$tableName was cleared <br>";
                         $deletedTables++;
                     }
                     else
                     {   // output error
                         $errors++;
                     }
                 }
             }
             // something went wrong
             if ($errors > 0)
             {   // output error
                 return false;
             }
             else {
                 return true;
             }
dropTables()
YAWK\db::dropTables ($tables)
Drop table from a database.
Parameters
array $tables the tables to drop
Returns
bool
Definition at line 427 of file db.php.
         {
             $processed = 0;
             // check if table was set
             if (!isset($tables) || (empty($tables)) || (!array($tables)))
             {
                 return false;
             }
             foreach ($tables as $table)
             {
                 if ($this->query("DROP TABLE `".$table."`") === true)
                 {
                     $processed++;
                 }
             }
             return true;
error()
YAWK\db::error ()
Fetch last error from the database.
Returns
string database error
Definition at line 265 of file db.php.
         {
             // connect to database
             $this->connection = $this->connect();
             // return latest error
             return $this->connection->error;
References YAWK\db\connect().
get_tables()
YAWK\db::get_tables ()
Get all tables from a database and return as array.
Returns
array tableList
Definition at line 408 of file db.php.
         {
             // set tableList array
             $tableList = array();
             // get tables from database
             $res = $this->query("SHOW TABLES");
             // walk through result
             while($row = mysqli_fetch_array($res))
             {   // fill array
                 $tableList[] = $row[0];
             }
             return $tableList;
import()
YAWK\db::import ($sqlfile, $lang)
Import data from .sql file into database.
Parameters
$sqlfile
$lang
Returns
bool
Definition at line 292 of file db.php.
         {
             // http://stackoverflow.com/questions/19751354/how-to-import-sql-file-in-mysql-database-using-php
             if (!isset($sqlfile) || (empty($sqlfile)))
             {
                 $filename = 'yawk_database.sql';
             }
             else
                 {
                     $filename = $sqlfile;
                 }
             // filename
             // $maxRuntime = 8; // less then your max script execution limit
             // $maxRuntime = 8; // less then your max script execution limit
             // $deadline = time()+$maxRuntime;
             $progressFilename = $filename.'_filepointer'; // tmp file for progress
             $errorFilename = $filename.'_error'; // tmp file for erro
             ($fp = fopen($filename, 'r')) OR die('failed to open file:'.$filename);
             // check for previous error
             if(file_exists($errorFilename) )
             {
                // die('<pre> previous error: '.file_get_contents($errorFilename));
             }
             // go to previous file position
             $filePosition = 0;
             if(file_exists($progressFilename))
             {
                 $filePosition = file_get_contents($progressFilename);
                 fseek($fp, $filePosition);
             }
             $queryCount = 0;
             $query = '';
             while($line=fgets($fp, 1024000))
             {
                 if(substr($line,0,2)=='--' OR trim($line)=='' )
                 {
                     continue;
                 }
                 $query .= $line;
                 if( substr(trim($query),-1)==';' )
                 {
                     if(!$this->query($query))
                     {   // error handling
                        $error = 'Error performing query \'<strong>' . $query . '\': ' . @mysqli_error($this);
                        @file_put_contents($errorFilename, $error."\n");
                        //exit;
                     }
                     $query = '';
                     @file_put_contents($progressFilename, ftell($fp)); // save the current file position for
                     $queryCount++;
                 }
             }
             if(feof($fp))
             {
                 return true;
             }
             else
                 {
                     // $status .= ftell($fp).'/'.filesize($filename).' '.(round(ftell($fp)/filesize($filename), 2)*100).'%'."\n";
                     return false;
                 }
References $error, $filename, die, and YAWK\db\query().
more_results()
YAWK\db::more_results ()
Checks if there are more query results from a multi query.
Returns
bool
Definition at line 154 of file db.php.
                                       : bool
         {
             if (method_exists($this->connection, 'more_results'))
             {
 //                sys::setSyslog($this->connection, 53, 0, "more migration results available", 0, 0, 0, 0);
                 return $this->connection->more_results() && $this->connection->next_result() && $this->connection->store_result();
             }
             else
             {
                 return false;
             }
Referenced by YAWK\db\next_result().
multi_query()
YAWK\db::multi_query ($query)
Definition at line 79 of file db.php.
         {   // query database
             return $this->connection->multi_query($query);
next_result()
YAWK\db::next_result ()
Move to next result set of a multi query.
Returns
bool
Definition at line 133 of file db.php.
         {
             if (method_exists($this->connection, 'next_result'))
             {
 //                sys::setSyslog($this->connection, 53, 0, "next result called", 0, 0, 0, 0);
                 return $this->connection->next_result();
             }
             else
             {
                 // Free any active result sets
                 while ($this->more_results() && $this->connection->next_result()) {
 //                    sys::setSyslog($this->connection, 53, 0, "free any active result sets", 0, 0, 0, 0);
                 }
                 return true;
             }
References YAWK\db\more_results().
prepare()
YAWK\db::prepare ($sql)
Definition at line 84 of file db.php.
         {   // prepare statement
             return $this->connection->prepare($sql);
References $sql.
query()
YAWK\db::query ($query)
Execute any sql query.
Parameters
string $query the sql query string
Returns
mixed The mysqli result
Definition at line 205 of file db.php.
         {
             // connect to database
             if ($this->connection = $this->connect())
             {
                 // if connection is successful
                 // replace {} in str to add table prefix
                 $query = str_replace("}", "", $query);
                 $query = str_replace("{", $this->config['prefix'], $query);
                 // query database
                 return $this->connection->query($query);
             }
             else
                 {   // could not connect to database, exit with error
                     die ('Database error: '.mysqli_connect_error().'('.mysqli_connect_errno().')');
                 }
References config, YAWK\db\connect(), and die.
Referenced by YAWK\db\import(), and YAWK\db\select().
quote()
YAWK\db::quote ($value)
Quote and escape value for use in a database query *.
Parameters
string $value the value to be quoted and escaped
Returns
string the quoted and escaped string
Definition at line 278 of file db.php.
         {
             // connect to database
             $this->connection = $this->connect();
             // escape and return string
             return $this->connection->real_escape_string($value);
References $value, and YAWK\db\connect().
real_escape_string()
YAWK\db::real_escape_string ($migrationSql)
Definition at line 94 of file db.php.
{
             return $this->connection->real_escape_string($migrationSql);
rollback()
YAWK\db::rollback ()
Rollback the current transaction
Returns
bool true if rollback succeeded, false otherwise
Definition at line 103 of file db.php.
         {
             try
             {
                 while ($this->connection->more_results())
                 {
                     $this->connection->next_result();
                 }
                 // Rollback the transaction
                 $result = $this->connection->rollback();
                 if ($result)
                 {   // Rollback succeeded
                     return true;
                 }
             }
             catch (\Exception $e)
             {
                 // An exception was thrown, so rollback failed
                 return false;
             }
             return false;
References $result.
select()
YAWK\db::select ($query)
Fetch rows from database (SELECT query)
Parameters
string $query the sql query string
Returns
array|bool on failure
Definition at line 230 of file db.php.
         {
             // init result rows array
             $rows = array();
             // query database
             $result = $this->query($query);
             // check if result is false
             if ($result === false)
             {
                 // $error = $this->error();
                 //\YAWK\sys::setSyslog($db, 5, "$error", 0, 0, 0, 0);
                 return false;
             }
             else
             {   // fetch associative result
                 while ($row = $result->fetch_assoc())
                 {   // fill array
                     $rows[] = $row;
                 }
             }
             // check if result rows array is set
             if (isset($rows) && (!empty($rows) && (is_array($rows))))
             {   // ok, return result rows
                 return $rows;
             }
             else
                 {   // no result set
                     return false;
                 }
References $result, $rows, and YAWK\db\query().
Member Data Documentation
$config
YAWK\db::$config
Parameters
array $config mysql configuration (host, username, database etc...)
Definition at line 19 of file db.php.
$connection
YAWK\db::$connection
Parameters
object $connection holds the mysqli database connection
Definition at line 21 of file db.php.
Referenced by YAWK\db\connect().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/db.php