YaWK: SSilence\ImapClient\OutgoingMessage Class Reference
SSilence\ImapClient\OutgoingMessage Class Reference
Public Member Functions
createBody ()
createMimeMessage ()
send ()
setAttachment ()
setFrom ($from)
setMessage ($message)
setSubject ($subject)
setTo ($to)
Protected Member Functions
preparingSend ()
Private Attributes
$additional_headers
$bcc
$body
$cc
$envelope
$message
$properties
$rpath
$subject
$to
Detailed Description
Class for all outgoing messages.
Due to the fact that this class is a W.I.P, I have not added comments as I assume they will be added later...
Copyright
Copyright (c) Tobias Zeising (http://www.aditu.de)
Author
Tobias Zeising tobia.nosp@m.s.ze.nosp@m.ising.nosp@m.@adi.nosp@m.tu.de, sergey144010
Definition at line 18 of file OutgoingMessage.php.
Member Function Documentation
createBody()
SSilence\ImapClient\OutgoingMessage::createBody ()
Create body.
Returns
void
Definition at line 179 of file OutgoingMessage.php.
     {
         $this->envelope['date'] = '29.03.2017';
         $this->envelope['message_id'] = '81';
         $part1['type'] = TYPEMULTIPART;
         $part1['subtype'] = 'mixed';
         $part3['type'] = TYPETEXT;
         $part3['subtype'] = 'plain';
         $part3['description'] = 'description3';
         $part3['contents.data'] = "contents.data3\n\n\n\t";
         $body[1] = $part1;
         //$body[2] = $part2;
         $body[3] = $part3;
         $this->body = $body;
     }
References SSilence\ImapClient\OutgoingMessage\$body.
Referenced by SSilence\ImapClient\OutgoingMessage\createMimeMessage().
createMimeMessage()
SSilence\ImapClient\OutgoingMessage::createMimeMessage ()
Create Mime Message.
See also
http://php.net/manual/ru/function.imap-mail-compose.php
Returns
string
Definition at line 150 of file OutgoingMessage.php.
     {
         $this->createBody();
         $envelopeAllowedType = array(
             'remail', 'return_path', 'date', 'from', 'reply_to', 'in_reply_to',
             'subject', 'to', 'cc', 'bcc', 'message_id', 'custom_headers',
         );
         /* @var $envelope array */
         $envelope = Helper::preparingProperties($this->envelope, $envelopeAllowedType, Helper::OUT_ARRAY);
         $bodyAllowedType = array(
             'type', 'encoding', 'charset', 'type.parameters', 'subtype',
             'id', 'description', 'disposition.type', 'disposition', 'contents.data',
             'lines', 'bytes', 'md5',
         );
         /* @var $body array */
         foreach ($this->body as $key => $part) {
             $this->body[$key] = Helper::preparingProperties($part, $bodyAllowedType, Helper::OUT_ARRAY);
         }
         $body = $this->body;
         return imap_mail_compose($envelope, $body);
     }
References SSilence\ImapClient\OutgoingMessage\$body, SSilence\ImapClient\OutgoingMessage\$envelope, as, SSilence\ImapClient\OutgoingMessage\createBody(), SSilence\ImapClient\Helper\OUT_ARRAY, and SSilence\ImapClient\Helper\preparingProperties().
Referenced by SSilence\ImapClient\OutgoingMessage\send().
preparingSend()
SSilence\ImapClient\OutgoingMessage::preparingSend () protected
Preparing properties.
Returns
void
Definition at line 126 of file OutgoingMessage.php.
     {
         $allowedProperties = array(
             'to', 'subject', 'message', 'additional_headers', 'cc', 'bcc', 'rpath',
         );
         $properties = array(
             'to' => $this->to,
             'subject' => $this->subject,
             'message' => $this->message,
             'additional_headers' => $this->additional_headers,
             'cc' => $this->cc,
             'bcc' => $this->bcc,
             'rpath' => $this->rpath,
         );
         $this->properties = Helper::preparingProperties($properties, $allowedProperties);
     }
References SSilence\ImapClient\OutgoingMessage\$properties, SSilence\ImapClient\Helper\preparingProperties(), and to.
Referenced by SSilence\ImapClient\OutgoingMessage\send().
send()
SSilence\ImapClient\OutgoingMessage::send ()
Send message via imap_mail.
Returns
void
Definition at line 105 of file OutgoingMessage.php.
     {
         $mimeMessage = $this->createMimeMessage();
         $this->message = $mimeMessage;
         $this->preparingSend();
         imap_mail(
             $this->properties->to,
             $this->properties->subject,
             $this->properties->message,
             $this->properties->additional_headers,
             $this->properties->cc,
             $this->properties->bcc,
             $this->properties->rpath
         );
     }
References SSilence\ImapClient\OutgoingMessage\createMimeMessage(), and SSilence\ImapClient\OutgoingMessage\preparingSend().
setAttachment()
SSilence\ImapClient\OutgoingMessage::setAttachment ()
Set attachment.
Definition at line 202 of file OutgoingMessage.php.
     {
     }
setFrom()
SSilence\ImapClient\OutgoingMessage::setFrom ($from)
Set From.
Parameters
string $from
Definition at line 211 of file OutgoingMessage.php.
     {
         $this->envelope['from'] = $from;
         $this->additional_headers = 'From: '.$from;
     }
setMessage()
SSilence\ImapClient\OutgoingMessage::setMessage ($message)
Set Message.
Parameters
string $message
Definition at line 244 of file OutgoingMessage.php.
     {
         $this->message = $message;
     }
References SSilence\ImapClient\OutgoingMessage\$message.
setSubject()
SSilence\ImapClient\OutgoingMessage::setSubject ($subject)
Set Subject.
Parameters
string $subject
Definition at line 233 of file OutgoingMessage.php.
     {
         $this->subject = $subject;
         $this->envelope['subject'] = $subject;
     }
References SSilence\ImapClient\OutgoingMessage\$subject.
setTo()
SSilence\ImapClient\OutgoingMessage::setTo ($to)
Set To.
Parameters
string $to
Definition at line 222 of file OutgoingMessage.php.
     {
         $this->to = $to;
         $this->envelope['to'] = $to;
     }
References SSilence\ImapClient\OutgoingMessage\$to, and to.
Member Data Documentation
$additional_headers
SSilence\ImapClient\OutgoingMessage::$additional_headers private
Definition at line 54 of file OutgoingMessage.php.
$bcc
SSilence\ImapClient\OutgoingMessage::$bcc private
Definition at line 72 of file OutgoingMessage.php.
$body
SSilence\ImapClient\OutgoingMessage::$body private
Definition at line 98 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\createBody(), and SSilence\ImapClient\OutgoingMessage\createMimeMessage().
$cc
SSilence\ImapClient\OutgoingMessage::$cc private
Definition at line 63 of file OutgoingMessage.php.
$envelope
SSilence\ImapClient\OutgoingMessage::$envelope private
For createMimeMessage() method.
Definition at line 91 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\createMimeMessage().
$message
SSilence\ImapClient\OutgoingMessage::$message private
Definition at line 45 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\setMessage().
$properties
SSilence\ImapClient\OutgoingMessage::$properties private
For send() method.
Definition at line 86 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\preparingSend().
$rpath
SSilence\ImapClient\OutgoingMessage::$rpath private
Definition at line 81 of file OutgoingMessage.php.
$subject
SSilence\ImapClient\OutgoingMessage::$subject private
Definition at line 36 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\setSubject().
$to
SSilence\ImapClient\OutgoingMessage::$to private
Definition at line 27 of file OutgoingMessage.php.
Referenced by SSilence\ImapClient\OutgoingMessage\setTo().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/imapClient/OutgoingMessage.php