YaWK: SMTP Class Reference
SMTP Class Reference
Public Member Functions
authenticate ($username, $password, $authtype='LOGIN', $realm='', $workstation='')
client_send ($data)
close ()
connect ($host, $port=null, $timeout=30, $options=array())
connected ()
data ($msg_data)
getDebugLevel ()
getDebugOutput ()
getError ()
getLastReply ()
getTimeout ()
getVerp ()
hello ($host='')
mail ($from)
noop ()
quit ($close_on_error=true)
recipient ($toaddr)
reset ()
sendAndMail ($from)
setDebugLevel ($level=0)
setDebugOutput ($method='echo')
setTimeout ($timeout=0)
setVerp ($enabled=false)
startTLS ()
turn ()
verify ($name)
Public Attributes
$CRLF = "\r\n"
$Debugoutput = 'echo'
$do_debug = 0
$do_verp = false
$SMTP_PORT = 25
$Timelimit = 30
$Timeout = 300
$Version = '5.2.8'
const CRLF = "\r\n"
const DEFAULT_SMTP_PORT = 25
const MAX_LINE_LENGTH = 998
const VERSION = '5.2.8'
Protected Member Functions
edebug ($str)
get_lines ()
hmac ($data, $key)
sendCommand ($command, $commandstring, $expect)
sendHello ($hello, $host)
Protected Attributes
$error = array()
$helo_rply = null
$last_reply = ''
$smtp_conn
Detailed Description
Definition at line 27 of file class.smtp.php.
Member Function Documentation
authenticate()
SMTP::authenticate ($username, $password, $authtype = 'LOGIN', $realm = '', $workstation = '')
Perform SMTP authentication. Must be run after hello().
See also
hello()
Parameters
string $username The user name
string $password The password
string $authtype The auth type (PLAIN, LOGIN, NTLM, CRAM-MD5)
string $realm The auth realm for NTLM
string $workstation The auth workstation for NTLM @access public
Returns
boolean True if successfully authenticated.
Definition at line 317 of file class.smtp.php.
       {
         if (empty($authtype)) {
             $authtype = 'LOGIN';
         }
         switch ($authtype) {
             case 'PLAIN':
                 // Start authentication
                 if (!$this->sendCommand('AUTH', 'AUTH PLAIN', 334)) {
                     return false;
                 }
                 // Send encoded username and password
                 if (!$this->sendCommand(
                     'User & Password',
                     base64_encode("\0" . $username . "\0" . $password),
                     235
                 )
                 ) {
                     return false;
                 }
                 break;
             case 'LOGIN':
                 // Start authentication
                 if (!$this->sendCommand('AUTH', 'AUTH LOGIN', 334)) {
                     return false;
                 }
                 if (!$this->sendCommand("Username", base64_encode($username), 334)) {
                     return false;
                 }
                 if (!$this->sendCommand("Password", base64_encode($password), 235)) {
                     return false;
                 }
                 break;
             case 'NTLM':
                 /*
                  * ntlm_sasl_client.php
                  * Bundled with Permission
                  *
                  * How to telnet in windows:
                  * http://technet.microsoft.com/en-us/library/aa995718%28EXCHG.65%29.aspx
                  * PROTOCOL Docs http://curl.haxx.se/rfc/ntlm.html#ntlmSmtpAuthentication
                  */
                 require_once 'extras/ntlm_sasl_client.php';
                 $temp = new stdClass();
                 $ntlm_client = new ntlm_sasl_client_class;
                 //Check that functions are available
                 if (!$ntlm_client->Initialize($temp)) {
                     $this->error = array('error' => $temp->error);
                     if ($this->do_debug >= 1) {
                         $this->edebug(
                             'You need to enable some modules in your php.ini file: '
                             . $this->error['error']
                         );
                     }
                     return false;
                 }
                 //msg1
                 $msg1 = $ntlm_client->TypeMsg1($realm, $workstation); //msg1
                 if (!$this->sendCommand(
                     'AUTH NTLM',
                     'AUTH NTLM ' . base64_encode($msg1),
                     334
                 )
                 ) {
                     return false;
                 }
                 //Though 0 based, there is a white space after the 3 digit number
                 //msg2
                 $challenge = substr($this->last_reply, 3);
                 $challenge = base64_decode($challenge);
                 $ntlm_res = $ntlm_client->NTLMResponse(
                     substr($challenge, 24, 8),
                     $password
                 );
                 //msg3
                 $msg3 = $ntlm_client->TypeMsg3(
                     $ntlm_res,
                     $username,
                     $realm,
                     $workstation
                 );
                 // send encoded username
                 return $this->sendCommand('Username', base64_encode($msg3), 235);
             case 'CRAM-MD5':
                 // Start authentication
                 if (!$this->sendCommand('AUTH CRAM-MD5', 'AUTH CRAM-MD5', 334)) {
                     return false;
                 }
                 // Get the challenge
                 $challenge = base64_decode(substr($this->last_reply, 4));
                 // Build the response
                 $response = $username . ' ' . $this->hmac($challenge, $password);
                 // send encoded credentials
                 return $this->sendCommand('Username', base64_encode($response), 235);
         }
         return true;
     }
References $password, $username, edebug(), error, hmac(), and sendCommand().
client_send()
SMTP::client_send ($data)
Send raw data to the server.
Parameters
string $data The data to send @access public
Returns
integer|boolean The number of bytes sent to the server or false on error
Definition at line 798 of file class.smtp.php.
     {
         if ($this->do_debug >= 1) {
             $this->edebug("CLIENT -> SERVER: $data");
         }
         return fwrite($this->smtp_conn, $data);
     }
References $data, and edebug().
Referenced by data(), and sendCommand().
close()
SMTP::close ()
Close the socket and clean up the state of the class. Don't use this function without first trying to use QUIT.
See also
quit() @access public
Returns
void
Definition at line 490 of file class.smtp.php.
     {
         $this->error = array();
         $this->helo_rply = null;
         if (is_resource($this->smtp_conn)) {
             // close the connection and cleanup
             fclose($this->smtp_conn);
             if ($this->do_debug >= 3) {
                 $this->edebug('Connection: closed');
             }
         }
     }
References edebug(), and error.
Referenced by connected(), and quit().
connect()
SMTP::connect ($host, $port = null, $timeout = 30, $options = array())
Connect to an SMTP server.
Parameters
string $host SMTP server IP or host name
integer $port The port number to connect to
integer $timeout How long to wait for the connection to open
array $options An array of options for stream_context_create() @access public
Returns
boolean
Definition at line 200 of file class.smtp.php.
     {
         static $streamok;
         //This is enabled by default since 5.0.0 but some providers disable it
         //Check this once and cache the result
         if (is_null($streamok)) {
             $streamok = function_exists('stream_socket_client');
         }
         // Clear errors to avoid confusion
         $this->error = array();
         // Make sure we are __not__ connected
         if ($this->connected()) {
             // Already connected, generate error
             $this->error = array('error' => 'Already connected to a server');
             return false;
         }
         if (empty($port)) {
             $port = self::DEFAULT_SMTP_PORT;
         }
         // Connect to the SMTP server
         if ($this->do_debug >= 3) {
             $this->edebug("Connection: opening to $host:$port, t=$timeout, opt=".var_export($options, true));
         }
         $errno = 0;
         $errstr = '';
         if ($streamok) {
             $socket_context = stream_context_create($options);
             //Suppress errors; connection failures are handled at a higher level
             $this->smtp_conn = @stream_socket_client(
                 $host . ":" . $port,
                 $errno,
                 $errstr,
                 $timeout,
                 STREAM_CLIENT_CONNECT,
                 $socket_context
             );
         } else {
             //Fall back to fsockopen which should work in more places, but is missing some features
             if ($this->do_debug >= 3) {
                 $this->edebug("Connection: stream_socket_client not available, falling back to fsockopen");
             }
             $this->smtp_conn = fsockopen(
                 $host,
                 $port,
                 $errno,
                 $errstr,
                 $timeout
             );
         }
         // Verify we connected properly
         if (!is_resource($this->smtp_conn)) {
             $this->error = array(
                 'error' => 'Failed to connect to server',
                 'errno' => $errno,
                 'errstr' => $errstr
             );
             if ($this->do_debug >= 1) {
                 $this->edebug(
                     'SMTP ERROR: ' . $this->error['error']
                     . ": $errstr ($errno)"
                 );
             }
             return false;
         }
         if ($this->do_debug >= 3) {
             $this->edebug('Connection: opened');
         }
         // SMTP server can take longer to respond, give longer timeout for first read
         // Windows does not have support for this timeout function
         if (substr(PHP_OS, 0, 3) != 'WIN') {
             $max = ini_get('max_execution_time');
             if ($max != 0 && $timeout > $max) { // Don't bother if unlimited
                 @set_time_limit($timeout);
             }
             stream_set_timeout($this->smtp_conn, $timeout, 0);
         }
         // Get any announcement
         $announce = $this->get_lines();
         if ($this->do_debug >= 2) {
             $this->edebug('SERVER -> CLIENT: ' . $announce);
         }
         return true;
     }
References $host, $options, $port, connected(), DEFAULT_SMTP_PORT, edebug(), error, and get_lines().
connected()
SMTP::connected ()
Check connection state. @access public
Returns
boolean True if connected.
Definition at line 464 of file class.smtp.php.
     {
         if (is_resource($this->smtp_conn)) {
             $sock_status = stream_get_meta_data($this->smtp_conn);
             if ($sock_status['eof']) {
                 // the socket is valid but we are not connected
                 if ($this->do_debug >= 1) {
                     $this->edebug(
                         'SMTP NOTICE: EOF caught while checking if connected'
                     );
                 }
                 $this->close();
                 return false;
             }
             return true; // everything looks good
         }
         return false;
     }
References close(), and edebug().
Referenced by connect(), and sendCommand().
data()
SMTP::data ($msg_data)
Send an SMTP DATA command. Issues a data command and sends the msg_data to the server, finializing the mail transaction. $msg_data is the message that is to be send with the headers. Each header needs to be on a single line followed by a <CRLF> with the message headers and the message body being separated by and additional <CRLF>. Implements rfc 821: DATA <CRLF>
Parameters
string $msg_data Message data to send @access public
Returns
boolean
Definition at line 515 of file class.smtp.php.
     {
         if (!$this->sendCommand('DATA', 'DATA', 354)) {
             return false;
         }
         /* The server is ready to accept data!
          * According to rfc821 we should not send more than 1000 characters on a single line (including the CRLF)
          * so we will break the data up into lines by \r and/or \n then if needed we will break each of those into
          * smaller lines to fit within the limit.
          * We will also look for lines that start with a '.' and prepend an additional '.'.
          * NOTE: this does not count towards line-length limit.
          */
         // Normalize line breaks before exploding
         $lines = explode("\n", str_replace(array("\r\n", "\r"), "\n", $msg_data));
         /* To distinguish between a complete RFC822 message and a plain message body, we check if the first field
          * of the first line (':' separated) does not contain a space then it _should_ be a header and we will
          * process all lines before a blank line as headers.
          */
         $field = substr($lines[0], 0, strpos($lines[0], ':'));
         $in_headers = false;
         if (!empty($field) && strpos($field, ' ') === false) {
             $in_headers = true;
         }
         foreach ($lines as $line) {
             $lines_out = array();
             if ($in_headers and $line == '') {
                 $in_headers = false;
             }
             // ok we need to break this line up into several smaller lines
             //This is a small micro-optimisation: isset($str[$len]) is equivalent to (strlen($str) > $len)
             while (isset($line[self::MAX_LINE_LENGTH])) {
                 //Working backwards, try to find a space within the last MAX_LINE_LENGTH chars of the line to break on
                 //so as to avoid breaking in the middle of a word
                 $pos = strrpos(substr($line, 0, self::MAX_LINE_LENGTH), ' ');
                 if (!$pos) { //Deliberately matches both false and 0
                     //No nice break found, add a hard break
                     $pos = self::MAX_LINE_LENGTH - 1;
                     $lines_out[] = substr($line, 0, $pos);
                     $line = substr($line, $pos);
                 } else {
                     //Break at the found point
                     $lines_out[] = substr($line, 0, $pos);
                     //Move along by the amount we dealt with
                     $line = substr($line, $pos + 1);
                 }
                 /* If processing headers add a LWSP-char to the front of new line
                  * RFC822 section 3.1.1
                  */
                 if ($in_headers) {
                     $line = "\t" . $line;
                 }
             }
             $lines_out[] = $line;
             // Send the lines to the server
             foreach ($lines_out as $line_out) {
                 //RFC2821 section 4.5.2
                 if (!empty($line_out) and $line_out[0] == '.') {
                     $line_out = '.' . $line_out;
                 }
                 $this->client_send($line_out . self::CRLF);
             }
         }
         // Message data has been sent, complete the command
         return $this->sendCommand('DATA END', '.', 250);
     }
References $field, as, client_send(), and sendCommand().
edebug()
SMTP::edebug ($str) protected
Output debugging info via a user-selected method.
See also
SMTP::$Debugoutput
SMTP::$do_debug
Parameters
string $str Debug string to output
Returns
void
Definition at line 159 of file class.smtp.php.
     {
         if (is_callable($this->Debugoutput)) {
             call_user_func($this->Debugoutput, $str, $this->do_debug);
             return;
         }
         switch ($this->Debugoutput) {
             case 'error_log':
                 //Don't output, just log
                 error_log($str);
                 break;
             case 'html':
                 //Cleans up output a bit for a better looking, HTML-safe output
                 echo htmlentities(
                     preg_replace('/[\r\n]+/', '', $str),
                     ENT_QUOTES,
                     'UTF-8'
                 )
                 . "<br>\n";
                 break;
             case 'echo':
             default:
                 //Normalize line breaks
                 $str = preg_replace('/(\r\n|\r|\n)/ms', "\n", $str);
                 echo gmdate('Y-m-d H:i:s') . "\t" . str_replace(
                     "\n",
                     "\n                   \t                  ",
                     trim($str)
                 )."\n";
         }
     }
Referenced by authenticate(), client_send(), close(), connect(), connected(), get_lines(), sendCommand(), and turn().
get_lines()
SMTP::get_lines () protected
Read the SMTP server's response. Either before eof or socket timeout occurs on the operation. With SMTP we can tell if we have more lines to read if the 4th character is '-' symbol. If it is a space then we don't need to read anything else. @access protected
Returns
string
Definition at line 835 of file class.smtp.php.
     {
         // If the connection is bad, give up straight away
         if (!is_resource($this->smtp_conn)) {
             return '';
         }
         $data = '';
         $endtime = 0;
         stream_set_timeout($this->smtp_conn, $this->Timeout);
         if ($this->Timelimit > 0) {
             $endtime = time() + $this->Timelimit;
         }
         while (is_resource($this->smtp_conn) && !feof($this->smtp_conn)) {
             $str = @fgets($this->smtp_conn, 515);
             if ($this->do_debug >= 4) {
                 $this->edebug("SMTP -> get_lines(): \$data was \"$data\"");
                 $this->edebug("SMTP -> get_lines(): \$str is \"$str\"");
             }
             $data .= $str;
             if ($this->do_debug >= 4) {
                 $this->edebug("SMTP -> get_lines(): \$data is \"$data\"");
             }
             // If 4th character is a space, we are done reading, break the loop, micro-optimisation over strlen
             if ((isset($str[3]) and $str[3] == ' ')) {
                 break;
             }
             // Timed-out? Log and break
             $info = stream_get_meta_data($this->smtp_conn);
             if ($info['timed_out']) {
                 if ($this->do_debug >= 4) {
                     $this->edebug(
                         'SMTP -> get_lines(): timed-out (' . $this->Timeout . ' sec)'
                     );
                 }
                 break;
             }
             // Now check if reads took too long
             if ($endtime and time() > $endtime) {
                 if ($this->do_debug >= 4) {
                     $this->edebug(
                         'SMTP -> get_lines(): timelimit reached ('.
                         $this->Timelimit . ' sec)'
                     );
                 }
                 break;
             }
         }
         return $data;
     }
References $data, $Timelimit, and edebug().
Referenced by connect(), and sendCommand().
getDebugLevel()
SMTP::getDebugLevel ()
Get debug output level.
Returns
integer
Definition at line 934 of file class.smtp.php.
     {
         return $this->do_debug;
     }
References $do_debug.
getDebugOutput()
SMTP::getDebugOutput ()
Get debug output method.
Returns
string
Definition at line 916 of file class.smtp.php.
     {
         return $this->Debugoutput;
     }
References $Debugoutput.
getError()
SMTP::getError ()
Get the latest error. @access public
Returns
array
Definition at line 811 of file class.smtp.php.
     {
         return $this->error;
     }
References $error.
getLastReply()
SMTP::getLastReply ()
Get the last reply from the server. @access public
Returns
string
Definition at line 821 of file class.smtp.php.
     {
         return $this->last_reply;
     }
References $last_reply.
getTimeout()
SMTP::getTimeout ()
Get SMTP timeout.
Returns
integer
Definition at line 952 of file class.smtp.php.
     {
         return $this->Timeout;
     }
References $Timeout.
getVerp()
SMTP::getVerp ()
Get VERP address generation mode.
Returns
boolean
Definition at line 898 of file class.smtp.php.
     {
         return $this->do_verp;
     }
References $do_verp.
hello()
SMTP::hello ($host = '')
Send an SMTP HELO or EHLO command. Used to identify the sending server to the receiving server. This makes sure that client and server are in a known state. Implements RFC 821: HELO <SP> <domain> <CRLF> and RFC 2821 EHLO.
Parameters
string $host The host name or IP to connect to @access public
Returns
boolean
Definition at line 597 of file class.smtp.php.
     {
         // Try extended hello first (RFC 2821)
         return (boolean)($this->sendHello('EHLO', $host) or $this->sendHello('HELO', $host));
     }
References $host, and sendHello().
hmac()
SMTP::hmac ($data, $key) protected
Calculate an MD5 HMAC hash. Works like hash_hmac('md5', $data, $key) in case that function is not available
Parameters
string $data The data to hash
string $key The key to hash with @access protected
Returns
string
Definition at line 432 of file class.smtp.php.
     {
         if (function_exists('hash_hmac')) {
             return hash_hmac('md5', $data, $key);
         }
         // The following borrowed from
         // http://php.net/manual/en/function.mhash.php#27225
         // RFC 2104 HMAC implementation for php.
         // Creates an md5 HMAC.
         // Eliminates the need to install mhash to compute a HMAC
         // Hacked by Lance Rushing
         $bytelen = 64; // byte length for md5
         if (strlen($key) > $bytelen) {
             $key = pack('H*', md5($key));
         }
         $key = str_pad($key, $bytelen, chr(0x00));
         $ipad = str_pad('', $bytelen, chr(0x36));
         $opad = str_pad('', $bytelen, chr(0x5c));
         $k_ipad = $key ^ $ipad;
         $k_opad = $key ^ $opad;
         return md5($k_opad . pack('H*', md5($k_ipad . $data)));
     }
References $data.
Referenced by authenticate().
mail()
SMTP::mail ($from)
Send an SMTP MAIL command. Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. Implements rfc 821: MAIL <SP> FROM:<reverse-path> <CRLF>
Parameters
string $from Source address of this message @access public
Returns
boolean
Definition at line 630 of file class.smtp.php.
     {
         $useVerp = ($this->do_verp ? ' XVERP' : '');
         return $this->sendCommand(
             'MAIL FROM',
             'MAIL FROM:<' . $from . '>' . $useVerp,
             250
         );
     }
References sendCommand().
noop()
SMTP::noop ()
Send an SMTP NOOP command. Used to keep keep-alives alive, doesn't actually do anything @access public
Returns
boolean
Definition at line 767 of file class.smtp.php.
     {
         return $this->sendCommand('NOOP', 'NOOP', 250);
     }
References sendCommand().
quit()
SMTP::quit ($close_on_error = true)
Send an SMTP QUIT command. Closes the socket if there is no error or the $close_on_error argument is true. Implements from rfc 821: QUIT <CRLF>
Parameters
boolean $close_on_error Should the connection close if an error occurs? @access public
Returns
boolean
Definition at line 648 of file class.smtp.php.
     {
         $noerror = $this->sendCommand('QUIT', 'QUIT', 221);
         $err = $this->error; //Save any error
         if ($noerror or $close_on_error) {
             $this->close();
             $this->error = $err; //Restore any error from the quit command
         }
         return $noerror;
     }
References $error, close(), error, and sendCommand().
recipient()
SMTP::recipient ($toaddr)
Send an SMTP RCPT command. Sets the TO argument to $toaddr. Returns true if the recipient was accepted false if it was rejected. Implements from rfc 821: RCPT <SP> TO:<forward-path> <CRLF>
Parameters
string $toaddr The address the message is being sent to @access public
Returns
boolean
Definition at line 668 of file class.smtp.php.
     {
         return $this->sendCommand(
             'RCPT TO',
             'RCPT TO:<' . $toaddr . '>',
             array(250, 251)
         );
     }
References sendCommand().
reset()
SMTP::reset ()
Send an SMTP RSET command. Abort any transaction that is currently in progress. Implements rfc 821: RSET <CRLF> @access public
Returns
boolean True on success.
Definition at line 684 of file class.smtp.php.
     {
         return $this->sendCommand('RSET', 'RSET', 250);
     }
References sendCommand().
sendAndMail()
SMTP::sendAndMail ($from)
Send an SMTP SAML command. Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. This command will send the message to the users terminal if they are logged in and send them an email. Implements rfc 821: SAML <SP> FROM:<reverse-path> <CRLF>
Parameters
string $from The address the message is from @access public
Returns
boolean
Definition at line 745 of file class.smtp.php.
     {
         return $this->sendCommand('SAML', "SAML FROM:$from", 250);
     }
References sendCommand().
sendCommand()
SMTP::sendCommand ($command, $commandstring, $expect) protected
Send a command to an SMTP server and check its return code.
Parameters
string $command The command name - not sent to the server
string $commandstring The actual command to send
integer | array $expect One or more expected integer success codes @access protected
Returns
boolean True on success.
Definition at line 697 of file class.smtp.php.
     {
         if (!$this->connected()) {
             $this->error = array(
                 'error' => "Called $command without being connected"
             );
             return false;
         }
         $this->client_send($commandstring . self::CRLF);
         $this->last_reply = $this->get_lines();
         $code = substr($this->last_reply, 0, 3);
         if ($this->do_debug >= 2) {
             $this->edebug('SERVER -> CLIENT: ' . $this->last_reply);
         }
         if (!in_array($code, (array)$expect)) {
             $this->error = array(
                 'error' => "$command command failed",
                 'smtp_code' => $code,
                 'detail' => substr($this->last_reply, 4)
             );
             if ($this->do_debug >= 1) {
                 $this->edebug(
                     'SMTP ERROR: ' . $this->error['error'] . ': ' . $this->last_reply
                 );
             }
             return false;
         }
         $this->error = array();
         return true;
     }
References client_send(), connected(), edebug(), error, and get_lines().
Referenced by authenticate(), data(), mail(), noop(), quit(), recipient(), reset(), sendAndMail(), sendHello(), startTLS(), and verify().
sendHello()
SMTP::sendHello ($hello, $host) protected
Send an SMTP HELO or EHLO command. Low-level implementation used by hello()
See also
hello()
Parameters
string $hello The HELO string
string $host The hostname to say we are @access protected
Returns
boolean
Definition at line 612 of file class.smtp.php.
     {
         $noerror = $this->sendCommand($hello, $hello . ' ' . $host, 250);
         $this->helo_rply = $this->last_reply;
         return $noerror;
     }
References $host, $last_reply, and sendCommand().
Referenced by hello().
setDebugLevel()
SMTP::setDebugLevel ($level = 0)
Set debug output level.
Parameters
integer $level
Definition at line 925 of file class.smtp.php.
     {
         $this->do_debug = $level;
     }
setDebugOutput()
SMTP::setDebugOutput ($method = 'echo')
Set debug output method.
Parameters
string $method The function/method to use for debugging output.
Definition at line 907 of file class.smtp.php.
     {
         $this->Debugoutput = $method;
     }
setTimeout()
SMTP::setTimeout ($timeout = 0)
Set SMTP timeout.
Parameters
integer $timeout
Definition at line 943 of file class.smtp.php.
     {
         $this->Timeout = $timeout;
     }
setVerp()
SMTP::setVerp ($enabled = false)
Enable or disable VERP address generation.
Parameters
boolean $enabled
Definition at line 889 of file class.smtp.php.
     {
         $this->do_verp = $enabled;
     }
startTLS()
SMTP::startTLS ()
Initiate a TLS (encrypted) session. @access public
Returns
boolean
Definition at line 289 of file class.smtp.php.
     {
         if (!$this->sendCommand('STARTTLS', 'STARTTLS', 220)) {
             return false;
         }
         // Begin encrypted connection
         if (!stream_socket_enable_crypto(
             $this->smtp_conn,
             true,
             STREAM_CRYPTO_METHOD_TLS_CLIENT
         )) {
             return false;
         }
         return true;
     }
References sendCommand().
turn()
SMTP::turn ()
Send an SMTP TURN command. This is an optional command for SMTP that this class does not support. This method is here to make the RFC821 Definition complete for this class and may be implemented in future Implements from rfc 821: TURN <CRLF> @access public
Returns
boolean
Definition at line 781 of file class.smtp.php.
     {
         $this->error = array(
             'error' => 'The SMTP TURN command is not implemented'
         );
         if ($this->do_debug >= 1) {
             $this->edebug('SMTP NOTICE: ' . $this->error['error']);
         }
         return false;
     }
References edebug(), and error.
verify()
SMTP::verify ($name)
Send an SMTP VRFY command.
Parameters
string $name The name to verify @access public
Returns
boolean
Definition at line 756 of file class.smtp.php.
     {
         return $this->sendCommand('VRFY', "VRFY $name", array(250, 251));
     }
References sendCommand().
Member Data Documentation
$CRLF
SMTP::$CRLF = "\r\n"
SMTP reply line ending. @type string
Deprecated:
Use the CRLF constant instead
See also
SMTP::CRLF
Definition at line 75 of file class.smtp.php.
$Debugoutput
SMTP::$Debugoutput = 'echo'
How to handle debug output. Options:
echo Output plain-text as-is, appropriate for CLI
html Output escaped, line breaks converted to <br>, appropriate for browser output
error_log Output to error log as configured in php.ini
Alternatively, you can provide a callable expecting two params: a message string and the debug level: $smtp->Debugoutput = function($str, $level) {echo "debug level $level; message: $str";}; @type string|callable
Definition at line 102 of file class.smtp.php.
Referenced by getDebugOutput().
$do_debug
SMTP::$do_debug = 0
Debug output level. Options:
0 No output
1 Commands
2 Data and commands
3 As 2 plus connection status
4 Low-level data output @type integer
Definition at line 87 of file class.smtp.php.
Referenced by getDebugLevel().
$do_verp
SMTP::$do_verp = false
Whether to use VERP. http://www.postfix.org/VERP_README.html Info on VERP boolean
Definition at line 110 of file class.smtp.php.
Referenced by getVerp().
$error
SMTP::$error = array() protected
Error message, if any, for the last call. @type array
Definition at line 137 of file class.smtp.php.
Referenced by getError(), and quit().
$helo_rply
SMTP::$helo_rply = null protected
The reply the server sent to us for HELO. If null, no HELO string has yet been received. @type string|null
Definition at line 144 of file class.smtp.php.
$last_reply
SMTP::$last_reply = '' protected
The most recent reply received from the server. @type string
Definition at line 150 of file class.smtp.php.
Referenced by getLastReply(), and sendHello().
$smtp_conn
SMTP::$smtp_conn protected
The socket for the server connection. @type resource
Definition at line 131 of file class.smtp.php.
$SMTP_PORT
SMTP::$SMTP_PORT = 25
SMTP server port number. @type integer
Deprecated:
This is only ever used as a default value, so use the DEFAULT_SMTP_PORT constant instead
See also
SMTP::DEFAULT_SMTP_PORT
Definition at line 67 of file class.smtp.php.
$Timelimit
SMTP::$Timelimit = 30
The SMTP timelimit value for reads, in seconds. @type integer
Definition at line 125 of file class.smtp.php.
Referenced by get_lines().
$Timeout
SMTP::$Timeout = 300
The timeout value for connection, in seconds. Default of 5 minutes (300sec) is from RFC2821 section 4.5.3.2 This needs to be quite high to function correctly with hosts using greetdelay as an anti-spam measure. integer
Definition at line 119 of file class.smtp.php.
Referenced by getTimeout().
$Version
SMTP::$Version = '5.2.8'
The PHPMailer SMTP Version number. @type string
Deprecated:
Use the VERSION constant instead
See also
SMTP::VERSION
Definition at line 59 of file class.smtp.php.
CRLF
const SMTP::CRLF = "\r\n"
SMTP line break constant. @type string
Definition at line 39 of file class.smtp.php.
DEFAULT_SMTP_PORT
const SMTP::DEFAULT_SMTP_PORT = 25
The SMTP port to use if one is not specified. @type integer
Definition at line 45 of file class.smtp.php.
Referenced by connect().
MAX_LINE_LENGTH
const SMTP::MAX_LINE_LENGTH = 998
The maximum line length allowed by RFC 2822 section 2.1.1 @type integer
Definition at line 51 of file class.smtp.php.
VERSION
const SMTP::VERSION = '5.2.8'
The PHPMailer SMTP version number. @type string
Definition at line 33 of file class.smtp.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/phpMailer/class.smtp.php