YaWK: SSilence\ImapClient\IncomingMessageAttachment Class Reference
SSilence\ImapClient\IncomingMessageAttachment Class Reference
Public Member Functions
__construct (Section $incomingObject)
Public Attributes
$body
$name
Protected Member Functions
getBody ()
getName ()
Private Attributes
$_incomingObject
Detailed Description
Class IncomingMessageAttachment for all incoming message attachments.
Copyright
Copyright (c) Tobias Zeising (http://www.aditu.de)
Author
Tobias Zeising tobia.nosp@m.s.ze.nosp@m.ising.nosp@m.@adi.nosp@m.tu.de
Definition at line 15 of file IncomingMessageAttachment.php.
Constructor & Destructor Documentation
__construct()
SSilence\ImapClient\IncomingMessageAttachment::__construct (Section $incomingObject)
The constructor.
Set $this->name and $this->body
Parameters
Section $incomingObject
Returns
IncomingMessageAttachment
Definition at line 49 of file IncomingMessageAttachment.php.
     {
         $this->_incomingObject = $incomingObject;
         $this->getName();
         $this->getBody();
     }
References SSilence\ImapClient\IncomingMessageAttachment\getBody(), and SSilence\ImapClient\IncomingMessageAttachment\getName().
Member Function Documentation
getBody()
SSilence\ImapClient\IncomingMessageAttachment::getBody () protected
Returns the body of the e-mail.
Returns
string
Definition at line 90 of file IncomingMessageAttachment.php.
     {
         $this->body = $this->_incomingObject->body;
     }
Referenced by SSilence\ImapClient\IncomingMessageAttachment\__construct().
getName()
SSilence\ImapClient\IncomingMessageAttachment::getName () protected
Returns the name of the attachment along with file extension.
Returns
string
Definition at line 61 of file IncomingMessageAttachment.php.
     {
         // Check for different types of inline attachments.
         if (is_object($this->_incomingObject->structure) &&
             property_exists($this->_incomingObject->structure, 'ifdparameters') &&
             $this->_incomingObject->structure->ifdparameters) {
             foreach ($this->_incomingObject->structure->dparameters as $param) {
                 if (strtolower($param->attribute) === 'filename') {
                     $this->name = $param->value;
                     break;
                 }
             }
         } elseif (is_object($this->_incomingObject->structure) &&
             property_exists($this->_incomingObject->structure, 'ifparameters') &&
             $this->_incomingObject->structure->ifparameters) {
             foreach ($this->_incomingObject->structure->parameters as $param) {
                 if (strtolower($param->attribute) === 'name') {
                     $this->name = $param->value;
                     break;
                 }
             }
         }
     }
References as, and name.
Referenced by SSilence\ImapClient\IncomingMessageAttachment\__construct().
Member Data Documentation
$_incomingObject
SSilence\ImapClient\IncomingMessageAttachment::$_incomingObject private
Definition at line 38 of file IncomingMessageAttachment.php.
$body
SSilence\ImapClient\IncomingMessageAttachment::$body
Definition at line 29 of file IncomingMessageAttachment.php.
$name
SSilence\ImapClient\IncomingMessageAttachment::$name
Definition at line 22 of file IncomingMessageAttachment.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/imapClient/IncomingMessageAttachment.php