YaWK: YAWK\WIDGETS\INSTAGRAM\POSTING\instagram Class Reference
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram Class Reference
Embed Instagram on your page.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
embed ()
init ()
Init and embed Instagram.
printObject ()
Print all object data.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
Public Attributes
$instagramHeading = ''
$instagramSubtext = ''
$instagramTarget = ''
$instagramUrl = ''
$instagramWidth = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Embed Instagram on your page.
Instagram Widget - embed any single instagram posting
If you want to embed instagram on your page, this is the widget to do it. All you need is a valid instagram url and (optional) some settings, like width or link target. Of course you can set a custom heading and subtext above posting.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 16 of file instagram.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 36 of file instagram.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
         }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
embed()
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::embed ()
Definition at line 66 of file instagram.php.
         {
             // draw heading above google map
             echo $this->getHeading($this->instagramHeading, $this->instagramSubtext);
             // check if embed html code is set and correct data type
             if (isset($this->instagramUrl)
                 && (!empty($this->instagramUrl))
                 && (is_string($this->instagramUrl)))
             {
                 // url seems to be valid...
                 echo '
 <blockquote class="instagram-media"
             data-instgrm-captioned data-instgrm-version="7"
             style="background:#fff;
                    border:0;
                    border-radius:3px;
                    box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15);
                    margin: 1px;
                    max-width:'.$this->instagramWidth.';
                    padding:0;
                    width:'.$this->instagramWidth.';">
     <p style="margin:8px 0 0 0; padding:0 4px;">
         <a href="'.$this->instagramUrl.'"
            style="color:#000;
                   font-family:Arial,sans-serif;
                   font-size:14px;
                   font-style:normal;
                   font-weight:normal;
                   line-height:17px;
                   text-decoration:none;
                   word-wrap:break-word;"
            target="'.$this->instagramTarget.'"></a>
     </p>
 </blockquote>
 <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>';
             }
             else
                 {   // url not valid, throw error msg
                     echo "Here should be an Instagram posting, but the required url was not set.";
                 }
         }
References YAWK\widget\getHeading().
Referenced by YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\init().
init()
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::init ()
Init and embed Instagram.
Embed Google Maps
Definition at line 61 of file instagram.php.
         {   // embed Instagram
             $this->embed();
         }
References YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\embed().
printObject()
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::printObject ()
Print all object data.
(for development and testing purpose)
Reimplemented from YAWK\widget.
Definition at line 50 of file instagram.php.
         {   // output data to screen
             echo "<pre>";
             print_r($this);
             echo "</pre>";
         }
Member Data Documentation
$instagramHeading
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$instagramHeading = ''
Parameters
string Heading above widget
Definition at line 27 of file instagram.php.
$instagramSubtext
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$instagramSubtext = ''
Parameters
string Subtext beside heading
Definition at line 29 of file instagram.php.
$instagramTarget
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$instagramTarget = ''
Parameters
string Link target (_blank, _parent, _self)
Definition at line 25 of file instagram.php.
$instagramUrl
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$instagramUrl = ''
Parameters
string Any valid instagram url
Definition at line 21 of file instagram.php.
$instagramWidth
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$instagramWidth = ''
Parameters
string Width of your posting
Definition at line 23 of file instagram.php.
$widget
YAWK\WIDGETS\INSTAGRAM\POSTING\instagram::$widget = ''
Parameters
object global widget object data
Definition at line 19 of file instagram.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/instagram/classes/instagram.php