YaWK: YAWK\filemanager Class Reference
YAWK\filemanager Class Reference
Basic File Manager (Backend)
Public Member Functions
__construct ()
filemanager constructor. check if all media subfolder exists, if not, try to create them
Static Public Member Functions
static countFilesFromFolder ($folder)
count files from folder
static deleteItem ($file)
delete file from folder
static drawTableFooter ()
draw: output html end table body, end table
static drawTableHeader ($lang, $i)
draw the table header with labeling
static getCurrentMimeTypes ()
Fast generation of a complete uptodate mime types list.
static getFilesFromFolder ($folder, $lang)
returns a list of all files in given folder. expect $folder as string
static getFilesFromFolderToArray ($folder)
returns an array containing only files from folder (no subfolders)
static getFilesOnlyFromFolder ($folder)
output a list showing only files from folder (no subfolders)
static getPhpMaxUploadSize ()
get and return PHP max file size setting
static getPostMaxSize ()
get and return post_max_size value from phpinfo()
static getSubfoldersToArray ($folder)
returns an array containing only files from folder (no subfolders)
static getUploadMaxFilesize ()
get and return upload max filesize value from phpinfo()
static recursiveRemoveDirectory ($directory)
Delete a directory recursive.
static removeSpecialChars ($string)
remove special chars as well as leading and trailing slashes from string
static ritit ($folder)
returns an multidimensional array containing subfolders + files of given folder
static sizeFilter ($bytes, $precision)
calculate filesize from bytes
static subdirToOptions ($path)
all folders in $path as select <option>...</option>
Detailed Description
Basic File Manager (Backend)
Basic File Manager (Backend)
This basic file manager class provides simple view, delete and upload methods.
Class covers backend functionality. See Methods Summary for details!
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl yawk.goodconnect.net @license https://opensource.org/licenses/MIT
Since
File available since Release 1.0.0
Definition at line 16 of file filemanager.php.
Constructor & Destructor Documentation
__construct()
YAWK\filemanager::__construct ()
filemanager constructor. check if all media subfolder exists, if not, try to create them
Definition at line 23 of file filemanager.php.
         {
             $folders = array('../media/images',
                             '../media/audio',
                             '../media/backup',
                             '../media/documents',
                             '../media/downloads',
                             '../media/mailbox',
                             '../media/uploads',
                             '../media/video');
             foreach ($folders as $folder)
             {
                 if (!is_dir($folder))
                 {
                     if (!mkdir($folder))
                     {
                         // todo: syslog: unable to create $folder
                         return false;
                     }
                 }
             }
             return true;
         }
References $folder.
Member Function Documentation
countFilesFromFolder()
static YAWK\filemanager::countFilesFromFolder ($folder) static
count files from folder
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $folder to search for files
Returns
int number of files in folder
Definition at line 448 of file filemanager.php.
         {
             $i = 0;
             foreach (new \DirectoryIterator($folder) as $fileInfo) {
                 if($fileInfo->isDot()) continue;
                 if($fileInfo->isDir()) continue;
                 $i++;
             }
             return $i;
         }
References $folder, and $i.
deleteItem()
static YAWK\filemanager::deleteItem ($file) static
delete file from folder
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $file file to delete
string $folder folder containing the file
Definition at line 328 of file filemanager.php.
         {
             // check if it is a directory or a file and set relevant actions
             // FOLDER
             if (is_dir($file))
             {   // lets run recursive directory removal function...
                 if (self::recursiveRemoveDirectory($file))
                 {   // folder + its content deleted
                     return true;
                 }
                 else
                     {   // could not recursive delete folder
                         // die ("recursiveRemoveDirectory failed");
                         return false;
                     }
             }
             // FILE
             else if (is_file($file))
             {   // check if unlink worked
                 if (@unlink($file))
                 {   // all good
                     return true;
                 }
                 else
                 {   // on error
                     return false;
                 }
             }
             else
                 {   // item is not a file nor a directory
                     // die ("item not found.");
                     return false;
                 }
         }
drawTableFooter()
static YAWK\filemanager::drawTableFooter () static
draw: output html end table body, end table
Definition at line 81 of file filemanager.php.
         {
             print "</tbody></table><br><br>";
         }
drawTableHeader()
static YAWK\filemanager::drawTableHeader ($lang, $i) static
draw the table header with labeling
Parameters
array $lang language array
integer $i
Definition at line 53 of file filemanager.php.
         {
             if (isset($_GET['path']) && (!empty($_GET['path'])))
             {
                 $backBtn = "<a class=\"btn btn-success pull-right\" href=\"index.php?page=filemanager\" onclick=\"window.history.back();\"><i class=\"fa fa-level-up\"></i> &nbsp;$lang[BACK]</a>";
             }
             else
             {
                 $backBtn = '';
             }
             print $backBtn;
             print "<table style=\"width:100%;\" class=\"table table-responsive table-hover\" id=\"table-sort$i\">
   <thead>
     <tr>
       <td style=\"width:10%;\" class=\"text-right\"><b>$lang[FILEMAN_SIZE]</b></td>
       <td style=\"width:70%;\" class=\"text-left\"><b>$lang[FILEMAN_FILENAME]</b></td>
       <td style=\"width:10%;\" class=\"text-center\"><b>$lang[FILEMAN_RIGHTS]</b></td>
       <td style=\"width:10%;\" class=\"text-center\"><b>$lang[ACTIONS]</b></td>
     </tr>
   </thead>
   <tbody>";
         }
References $_GET.
getCurrentMimeTypes()
static YAWK\filemanager::getCurrentMimeTypes () static
Fast generation of a complete uptodate mime types list.
Returns
bool|string
Definition at line 609 of file filemanager.php.
         {
             $url = "http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types";
             $s=array();
             foreach(@explode("\n",@file_get_contents($url))as $x)
                 if(isset($x[0])&&$x[0]!=='#'&&preg_match_all('#([^\s]+)#',$x,$out)&&isset($out[1])&&($c=count($out[1]))>1)
                     for($i=1;$i<$c;$i++)
                         $s[]='&nbsp;&nbsp;&nbsp;\''.$out[1][$i].'\' => \''.$out[1][0].'\'';
             return @sort($s)?'$mime_types = array(<br />'.implode($s,',<br />').'<br />);':false;
         }
References $i, and $url.
getFilesFromFolder()
static YAWK\filemanager::getFilesFromFolder ($folder, $lang) static
returns a list of all files in given folder. expect $folder as string
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2015 Daniel Retzl yawk.goodconnect.net @license https://opensource.org/licenses/MIT
Parameters
string $folder folder to look for files
string $path path to workout
array $lang current language array
Definition at line 157 of file filemanager.php.
         {
             global $file_value;
             // check if a path is requested via GET variable
             if (isset($_GET['path']) && (!empty($_GET['path'])))
             {   // set folder to given value
                 $folder = $_GET['path'];
             }
             // if no folder is set
             if (!isset($folder)) {
                 // show up any default folder
                 $folder = "../media/images";
             }
             // if requested folder not exists, folder structure may be corrupt.
             // this can cause a crash if a system-needed folder was deleted.
             if (!is_dir($folder))
             {   // try to catch this - create missing folder
                 if (!mkdir($folder))
                 {   // could not create missing folder - bad exit, bad warning.
                     die ("$lang[FILEMAN_FOLDER_MISSING]");
                 }
                 // in any other case, everything is ok - go on...
             }
             // set path variable
             $path = "$folder";
             // walk through file structure...
             foreach (new \DirectoryIterator($path) as $file) {
                 // fill files array
                 if ($file->isFile()) {
                     // create files array
                     $files[] = htmlentities($file);
                     // get permissions
                     $file_perms[] = substr(sprintf('%o', fileperms($path . "/" . $file)), -4);
                     // get filesize
                     $file_size[] = filesize($path . "/" . $file);
                 }
                 // fill folders array
                 if ($file->isDir() AND (!$file->isDot())) {
                     $folders[] = htmlentities($file);
                     $dir_perms[] = substr(sprintf('%o', fileperms($path . "/" . $file)), -4);
                 }
             }
             // sort files asc/desc
             if (!empty($files)) {
                 // insert sort here - if needed
             }
             // sort folders asc/desc
             if (!empty($folders)) {
                 // sort($folders);
             }
             // if no files or folder was found
             if (empty($files) && (empty($folders)))
             {   // this directory is empty, show msg and draw back btn
                 $errorMsg = "$lang[FILEMAN_THIS_EMPTY_DIR]<br>
                              <a href=\"index.php?page=filemanager\" onclick=\"window.history.back();\"> $lang[BACK]</a>";
             }
             else
                 {   // no error message
                     $errorMsg = '';
                 }
             /* OUTPUT:
              * list folders + files
              */
             // first of all, draw folders from array
             if (isset($folders))
             { // print folders
                 $i = 0;
                 $deleteIcon = "<i class=\"fa fa-trash-o\"></i>";
                 foreach ($folders as $dir_value)
                 {
                     // avoid warnings if no files or directories are found
                     if (!isset($file_perms[$i])){ $file_perms[$i] = ''; }
                     if (!isset($dir_perms[$i])){ $dir_perms[$i] = ''; }
                     // LIST FOLDERS
                     //    print "<strong>$dir_perms $dir_value</strong><br>";
                     echo "<tr>
           <td class=\"text-right\"><a href=\"?page=filemanager&path=$path" . "/$dir_value\"><div style=\"width:100%\"><i class=\"fa fa-folder\"></i></div></a></td>
           <td class=\"text-left\"><a href=\"?page=filemanager&path=$path" . "/$dir_value\"><div style=\"width:100%\">$dir_value</div></a></td>
           <td class=\"text-center\">$dir_perms[$i] <small><a class=\"fa fa-edit\" onclick=\"setChmodCode('$path/$file_value', '$file_perms[$i]');\" data-toggle=\"modal\" data-target=\"#chmodModal\" data-foldername=\"$file_perms[$i]\" title=\"$lang[FILEMAN_CHMOD]\" href=\"#myModal\"></a></small> </td>
           <td class=\"text-center\">
            <a class=\"fa fa-trash-o\" data-title=\"$lang[FILEMAN_REMOVE_FOLDER]\" data-itemtype=\"$lang[FOLDER]\" role=\"dialog\" data-confirm=\"$lang[FILEMAN_DELETE] &laquo;$dir_value&raquo;\"
             title=\"$lang[FILEMAN_REMOVE_FOLDER]\" data-target=\"#deleteModal\" data-toggle=\"modal\" href=\"index.php?page=filemanager&delete=1&path=$path&item=$dir_value&folder=$folder\"></a>
             &nbsp;
            <a class=\"fa fa-pencil\" id=\"renameToggle\" onclick=\"setRenameFieldState('$path', '$dir_value', '$lang[FILEMAN_RENAME_FOLDER]');\" data-toggle=\"modal\" data-target=\"#renameModal\" data-foldername=\"$dir_value\" title=\"$lang[RENAME]\" href=\"#myModal\"></a>
           </td>
         </tr>";
                     $i++;
                 }
             }
             else
                 {   // if directory is empty, display this info instead of data
                     echo "<tr>
                             <td></td>
                             <td>$errorMsg</td>
                             <td></td>
                             <td></td>
                           </tr>";
                 }
             // secondly draw files from array
             if (isset($files))
             { // print files
                 $i = 0;
                 foreach ($files as $file_value) {
                     $fsize = \YAWK\filemanager::sizeFilter($file_size[$i], 1);
                     echo "<tr>
           <td class=\"text-right\">$fsize</td>
           <td class=\"text-left\"><a href='$path" . "/$file_value'><div style=\"width:100%\">$file_value</div></a></td>
           <td class=\"text-center\">$file_perms[$i] <small><a class=\"fa fa-edit\" onclick=\"setChmodCode('$path/$file_value', '$file_perms[$i]');\" data-toggle=\"modal\" data-target=\"#chmodModal\" data-foldername=\"$file_perms[$i]\" title=\"$lang[FILEMAN_CHMOD]\" href=\"#myModal\"></a></small></td>
           <td class=\"text-center\">
            <a class=\"fa fa-trash-o\" role=\"dialog\" data-confirm=\"$lang[FILEMAN_DELETE] &laquo;$file_value&raquo;\"
             title=\"$lang[FILEMAN_REMOVE_FILE]\" data-target=\"#moveModal\" data-toggle=\"modal\" href='index.php?page=filemanager&delete=1&path=$path&item=$file_value&folder=$folder'></a>
             &nbsp;
            <a class=\"fa fa-pencil\" onclick=\"setRenameFieldState('$path', '$file_value', '$lang[FILEMAN_RENAME_FILE]');\" data-toggle=\"modal\" data-target=\"#renameModal\" data-foldername=\"$file_value\" title=\"$lang[RENAME]\" href=\"#myModal\"></a>
           </td>
         </tr>";
                     $i++;
                 }
             } else {
                 //  print "<br><h4>There are no files in $folder.</h4>";
             }
         }
References $_GET, $errorMsg, $folder, $i, die, and YAWK\filemanager\sizeFilter().
getFilesFromFolderToArray()
static YAWK\filemanager::getFilesFromFolderToArray ($folder) static
returns an array containing only files from folder (no subfolders)
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $folder to get files from
Definition at line 512 of file filemanager.php.
         {
             $files = array();
             foreach (new \DirectoryIterator($folder) as $fileInfo) {
                 if($fileInfo->isDot()) continue;
                 if($fileInfo->isDir()) continue;
                 $files[] = $fileInfo->getFilename();
             }
             return $files;
         }
References $folder.
Referenced by YAWK\BACKUP\backup\getArchiveBackupFilesArray(), YAWK\BACKUP\backup\getCurrentBackupFilesArray(), and YAWK\language\getSupportedLanguages().
getFilesOnlyFromFolder()
static YAWK\filemanager::getFilesOnlyFromFolder ($folder) static
output a list showing only files from folder (no subfolders)
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $folder to get files from
Definition at line 466 of file filemanager.php.
         {
             foreach (new \DirectoryIterator($folder) as $fileInfo) {
                 if($fileInfo->isDot()) continue;
                 if($fileInfo->isDir()) continue;
                 echo $fileInfo->getFilename() . "<br>\n";
             }
         }
References $folder.
getPhpMaxUploadSize()
static YAWK\filemanager::getPhpMaxUploadSize () static
get and return PHP max file size setting
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
bool|string
Definition at line 417 of file filemanager.php.
         {
             $returnValue = '';
             if ($postMaxSize = ini_get('post_max_size'))
             {   // return post max filesize
                 $returnValue = $postMaxSize;
             }
             if ($upload_max_filesize = ini_get('upload_max_filesize'))
             {   // upload_max_filesize
                 $returnValue .= " (".$upload_max_filesize.")";
             }
             else
                 {   // ini_get failed
                     if (!isset($db)) { $db = new \YAWK\db(); }
                     \YAWK\sys::setSyslog($db, 27, 1, "failed to ini_get post_max_size", 0, 0, 0, 0);
                     return false;
                 }
             return $returnValue;
         }
References $db.
getPostMaxSize()
static YAWK\filemanager::getPostMaxSize () static
get and return post_max_size value from phpinfo()
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
string|false
Definition at line 372 of file filemanager.php.
         {
             if ($postMaxSize = ini_get('post_max_size'))
             {   // return post max filesize
                 return $postMaxSize;
             }
             else
             {   // ini_get failed
                 if (!isset($db)) { $db = new \YAWK\db(); }
                 \YAWK\sys::setSyslog($db, 27, 1, "failed to ini_get post_max_size", 0, 0, 0, 0);
                 echo "Unable to get post_max_size";
                 return false;
             }
         }
References $db.
getSubfoldersToArray()
static YAWK\filemanager::getSubfoldersToArray ($folder) static
returns an array containing only files from folder (no subfolders)
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $folder to get files from
Definition at line 530 of file filemanager.php.
         {
             $subFolders = array();
             foreach (new \DirectoryIterator($folder) as $fileInfo) {
                 if($fileInfo->isDot()) continue;
                 if($fileInfo->isFile()) continue;
                 if($fileInfo->isDir())
                 $subFolders[] = $fileInfo->getFilename();
             }
             return $subFolders;
         }
References $folder.
Referenced by YAWK\BACKUP\backup\restore().
getUploadMaxFilesize()
static YAWK\filemanager::getUploadMaxFilesize () static
get and return upload max filesize value from phpinfo()
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Returns
string|false
Definition at line 395 of file filemanager.php.
         {
             if ($upload_max_filesize = ini_get('upload_max_filesize'))
             {   // upload_max_filesize
                 return $upload_max_filesize;
             }
             else
             {   // ini_get failed
                 if (!isset($db)) { $db = new \YAWK\db(); }
                 \YAWK\sys::setSyslog($db, 27, 1, "failed to ini_get upload_max_filesize", 0, 0, 0, 0);
                 return false;
             }
         }
References $db.
recursiveRemoveDirectory()
static YAWK\filemanager::recursiveRemoveDirectory ($directory) static
Delete a directory recursive.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2017 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $directory folder to delete
Definition at line 296 of file filemanager.php.
         {   // walk through directory
             foreach(glob("{$directory}/*") as $file)
             {   // if it's a directory
                 if(is_dir($file))
                 {   // call ourself
                     self::recursiveRemoveDirectory($file);
                 }
                 else
                     {   // delete folder
                         unlink($file);
                     }
             }
             // directory removed
             if (rmdir($directory))
             {   // successful
                 return true;
             }
             else
                 {   // remove folder failed
                     return false;
                 }
         }
Referenced by YAWK\template\downloadTemplate(), YAWK\template\emptyTmpFolder(), and YAWK\template\uploadTemplate().
removeSpecialChars()
static YAWK\filemanager::removeSpecialChars ($string) static
remove special chars as well as leading and trailing slashes from string
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2017 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
string $string the affected string
Definition at line 482 of file filemanager.php.
         {
             if (isset($string) && (!empty($string)))
             {
                 // $string = 'V!er$s%c&h/i(e)d=e?n`e So{n[d]e]r}z\ei+c*h~e#n';
                 // remove special chars
                 $string = preg_replace ('/[^a-z0-9-. ]/i', '', $string);
                 // trim any whitespaces left or right
                 $string = trim($string);
                 // change any backslashes to regular slashes
                 $string = strtr($string,"\\","/");
                 // remove all leading slashes
                 $string = ltrim($string, "/");
                 // remove all trailing slashes
                 $string = rtrim($string, "/");
                 return $string;
             }
             else
                 {
                     return null;
                 }
         }
ritit()
static YAWK\filemanager::ritit ($folder) static
returns an multidimensional array containing subfolders + files of given folder
Parameters
string $folder to get files from
Returns
array|null
Definition at line 547 of file filemanager.php.
         {
             if (isset($folder) && (!empty($folder) && (is_string($folder))))
             {
                 $ritit = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($folder, \RecursiveDirectoryIterator::SKIP_DOTS), \RecursiveIteratorIterator::CHILD_FIRST);
                 $r = array();
                 foreach ($ritit as $splFileInfo) {
                     $path = $splFileInfo->isDir()
                         ? array($splFileInfo->getFilename() => array())
                         : array($splFileInfo->getFilename());
                     for ($depth = $ritit->getDepth() - 1; $depth >= 0; $depth--) {
                         $path = array($ritit->getSubIterator($depth)->current()->getFilename() => $path);
                     }
                     $r = array_merge_recursive($r, $path);
                 }
                 if (is_array($r))
                 {
                     return $r;
                 }
                 else
                     {
                         return null;
                     }
             }
             else
                 {
                     return null;
                 }
         }
References $folder.
sizeFilter()
static YAWK\filemanager::sizeFilter ($bytes, $precision) static
calculate filesize from bytes
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2016 Daniel Retzl @license https://opensource.org/licenses/MIT
Parameters
int | string $bytes
int | string $precision how many decimal places?
Returns
string rounded, human-readable bytes
Definition at line 589 of file filemanager.php.
         {
             // if no precision is set
             if (!isset($precision) || (empty($precision)))
             {   // set default: no decimal place
                 $precision = 0;
             }
             // different sizes
             $label = array('B', 'KB', 'MB', 'GB', 'TB', 'PB');
             // calculate filesize
             for ($i = 0; $bytes >= 1024 && $i < (count($label) - 1); $bytes /= 1024, $i++) ;
             // return calculated filesize
             return (round($bytes, $precision) . " " . $label[$i]);
         } // end class filter
References $i.
Referenced by YAWK\filemanager\getFilesFromFolder().
subdirToOptions()
static YAWK\filemanager::subdirToOptions ($path) static
all folders in $path as select <option>...</option>
Parameters
string $path rootpath that should be scanned and returned
Definition at line 91 of file filemanager.php.
         {
             if (isset($path) && (!empty($path) && (is_dir($path))))
             {
                 // init new iterator object
                 $iter = new \RecursiveIteratorIterator(
                     new \RecursiveDirectoryIterator($path, \RecursiveDirectoryIterator::SKIP_DOTS),
                     \RecursiveIteratorIterator::SELF_FIRST,
                     \RecursiveIteratorIterator::CATCH_GET_CHILD // Ignore "Permission denied"
                 );
                 // if you wish to return an array, uncomment following line:
                 // $paths = array($root);
                 echo "<optgroup label=\"Subfolder\">";
                 foreach ($iter as $path => $dir)
                 {
                     if($dir->getFilename() === "audio") continue;
                     if($dir->getFilename() === "backup") continue;
                     if($dir->getFilename() === "documents") continue;
                     if($dir->getFilename() === "downloads") continue;
                     if($dir->getFilename() === "images") continue;
                     if($dir->getFilename() === "mailbox") continue;
                     if($dir->getFilename() === "uploads") continue;
                     if($dir->getFilename() === "video") continue;
                     if ($dir->isDir())
                     {
                         // if you wish to return an array, uncomment following line:
                         //  $paths[] = $path;
                         // you need subdir only in a var?- uncomment following line:
                         // $subdir = $dir->getFilename();
                     // adjust path
                     $subpath = ltrim($path, "..");          // remove dots
                     $subpath = ltrim($subpath, "/");        // remove pre slash
                     $subpath = ltrim($subpath, "media");    // remove not needed path
                     $subpath = ltrim($subpath, "/");        // remove trailing slash
                     $subpath = strtr($subpath,"\\","/");    // if run on win: backslashes2slashes
                     $label = ltrim($subpath, "/");          // remove trailing slash
                     $label = ucfirst($label);               // uppercase first char of label
                     echo "<option value=\"$subpath\">&nbsp;$label</option>";
                     }
                 }
                 // if you wish to return an array, uncomment following code block:
                 /*
                 if (isset($paths) && (is_array($paths)))
                 {
                     return $paths;
                 }
                 else
                     {
                         return null;
                     }
                 */
             }
         }
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/filemanager.php