YaWK: Ifsnop\Mysqldump\TypeAdapterMysql Class Reference
Ifsnop\Mysqldump\TypeAdapterMysql Class Reference
Public Member Functions
add_drop_database ()
add_drop_trigger ()
backup_parameters ()
commit_transaction ()
create_event ($row)
create_procedure ($row)
create_table ($row)
create_trigger ($row)
create_view ($row)
databases ()
drop_table ()
drop_view ()
end_add_disable_keys ()
end_add_lock_table ()
end_disable_autocommit ()
getDatabaseHeader ()
lock_table ()
parseColumnType ($colType)
restore_parameters ()
setup_transaction ()
show_columns ()
show_create_event ($eventName)
show_create_procedure ($procedureName)
show_create_table ($tableName)
show_create_trigger ($triggerName)
show_create_view ($viewName)
show_events ()
show_procedures ()
show_tables ()
show_triggers ()
show_views ()
start_add_disable_keys ()
start_add_lock_table ()
start_disable_autocommit ()
start_transaction ()
unlock_table ()
Public Member Functions inherited from Ifsnop\Mysqldump\TypeAdapterFactory
__construct ($dbHandler=null, $dumpSettings=array())
end_disable_foreign_keys_check ()
start_disable_foreign_keys_check ()
Public Attributes
$mysqlTypes
const DEFINER_RE = 'DEFINER=`(?:[^`]|``)*`@`(?:[^`]|``)*`'
Private Member Functions
check_parameters ($num_args, $expected_num_args, $method_name)
Additional Inherited Members
Static Public Member Functions inherited from Ifsnop\Mysqldump\TypeAdapterFactory
static create ($c, $dbHandler=null, $dumpSettings=array())
Protected Attributes inherited from Ifsnop\Mysqldump\TypeAdapterFactory
$dbHandler = null
$dumpSettings = array()
Detailed Description
Definition at line 1567 of file Mysqldump.php.
Member Function Documentation
add_drop_database()
Ifsnop\Mysqldump\TypeAdapterMysql::add_drop_database ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1916 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "/*!40000 DROP DATABASE IF EXISTS `${args[0]}`*/;".
             PHP_EOL.PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
add_drop_trigger()
Ifsnop\Mysqldump\TypeAdapterMysql::add_drop_trigger ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1924 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "DROP TRIGGER IF EXISTS `${args[0]}`;".PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
backup_parameters()
Ifsnop\Mysqldump\TypeAdapterMysql::backup_parameters ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1984 of file Mysqldump.php.
     {
         $ret = "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;".PHP_EOL.
             "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;".PHP_EOL.
             "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;".PHP_EOL.
             "/*!40101 SET NAMES ".$this->dumpSettings['default-character-set']." */;".PHP_EOL;
         if (false === $this->dumpSettings['skip-tz-utc']) {
             $ret .= "/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;".PHP_EOL.
                 "/*!40103 SET TIME_ZONE='+00:00' */;".PHP_EOL;
         }
         $ret .= "/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;".PHP_EOL.
             "/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;".PHP_EOL.
             "/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;".PHP_EOL.
             "/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;".PHP_EOL.PHP_EOL;
         return $ret;
     }
check_parameters()
Ifsnop\Mysqldump\TypeAdapterMysql::check_parameters ($num_args, $expected_num_args, $method_name) private
Check number of parameters passed to function, useful when inheriting. Raise exception if unexpected.
Parameters
integer $num_args
integer $expected_num_args
string $method_name
Definition at line 2031 of file Mysqldump.php.
     {
         if ($num_args != $expected_num_args) {
             throw new Exception("Unexpected parameter passed to $method_name");
         }
         return;
     }
Referenced by Ifsnop\Mysqldump\TypeAdapterMysql\add_drop_database(), Ifsnop\Mysqldump\TypeAdapterMysql\add_drop_trigger(), Ifsnop\Mysqldump\TypeAdapterMysql\databases(), Ifsnop\Mysqldump\TypeAdapterMysql\drop_table(), Ifsnop\Mysqldump\TypeAdapterMysql\drop_view(), Ifsnop\Mysqldump\TypeAdapterMysql\end_add_disable_keys(), Ifsnop\Mysqldump\TypeAdapterMysql\getDatabaseHeader(), Ifsnop\Mysqldump\TypeAdapterMysql\lock_table(), Ifsnop\Mysqldump\TypeAdapterMysql\show_columns(), Ifsnop\Mysqldump\TypeAdapterMysql\show_events(), Ifsnop\Mysqldump\TypeAdapterMysql\show_procedures(), Ifsnop\Mysqldump\TypeAdapterMysql\show_tables(), Ifsnop\Mysqldump\TypeAdapterMysql\show_triggers(), Ifsnop\Mysqldump\TypeAdapterMysql\show_views(), Ifsnop\Mysqldump\TypeAdapterMysql\start_add_disable_keys(), and Ifsnop\Mysqldump\TypeAdapterMysql\start_add_lock_table().
commit_transaction()
Ifsnop\Mysqldump\TypeAdapterMysql::commit_transaction ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1860 of file Mysqldump.php.
     {
         return "COMMIT";
     }
create_event()
Ifsnop\Mysqldump\TypeAdapterMysql::create_event ($row)
Definition at line 1746 of file Mysqldump.php.
     {
         $ret = "";
         if (!isset($row['Create Event'])) {
             throw new Exception("Error getting event code, unknown output. ".
                 "Please check 'http://stackoverflow.com/questions/10853826/mysql-5-5-create-event-gives-syntax-error'");
         }
         $eventName = $row['Event'];
         $eventStmt = $row['Create Event'];
         $sqlMode = $row['sql_mode'];
         $definerStr = $this->dumpSettings['skip-definer'] ? '' : '/*!50117 \2*/ ';
         if ($eventStmtReplaced = preg_replace(
             '/^(CREATE)\s+('.self::DEFINER_RE.')?\s+(EVENT .*)$/',
             '/*!50106 \1*/ '.$definerStr.'/*!50106 \3 */',
             $eventStmt,
             1
         )) {
             $eventStmt = $eventStmtReplaced;
         }
         $ret .= "/*!50106 SET @save_time_zone= @@TIME_ZONE */ ;".PHP_EOL.
             "/*!50106 DROP EVENT IF EXISTS `".$eventName."` */;".PHP_EOL.
             "DELIMITER ;;".PHP_EOL.
             "/*!50003 SET @saved_cs_client      = @@character_set_client */ ;;".PHP_EOL.
             "/*!50003 SET @saved_cs_results     = @@character_set_results */ ;;".PHP_EOL.
             "/*!50003 SET @saved_col_connection = @@collation_connection */ ;;".PHP_EOL.
             "/*!50003 SET character_set_client  = utf8 */ ;;".PHP_EOL.
             "/*!50003 SET character_set_results = utf8 */ ;;".PHP_EOL.
             "/*!50003 SET collation_connection  = utf8_general_ci */ ;;".PHP_EOL.
             "/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;;".PHP_EOL.
             "/*!50003 SET sql_mode              = '".$sqlMode."' */ ;;".PHP_EOL.
             "/*!50003 SET @saved_time_zone      = @@time_zone */ ;;".PHP_EOL.
             "/*!50003 SET time_zone             = 'SYSTEM' */ ;;".PHP_EOL.
             $eventStmt." ;;".PHP_EOL.
             "/*!50003 SET time_zone             = @saved_time_zone */ ;;".PHP_EOL.
             "/*!50003 SET sql_mode              = @saved_sql_mode */ ;;".PHP_EOL.
             "/*!50003 SET character_set_client  = @saved_cs_client */ ;;".PHP_EOL.
             "/*!50003 SET character_set_results = @saved_cs_results */ ;;".PHP_EOL.
             "/*!50003 SET collation_connection  = @saved_col_connection */ ;;".PHP_EOL.
             "DELIMITER ;".PHP_EOL.
             "/*!50106 SET TIME_ZONE= @save_time_zone */ ;".PHP_EOL.PHP_EOL;
         // Commented because we are doing this in restore_parameters()
         // "/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;" . PHP_EOL . PHP_EOL;
         return $ret;
     }
create_procedure()
Ifsnop\Mysqldump\TypeAdapterMysql::create_procedure ($procedureName)
function create_procedure Modify procedure code, add delimiters, etc
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1725 of file Mysqldump.php.
     {
         $ret = "";
         if (!isset($row['Create Procedure'])) {
             throw new Exception("Error getting procedure code, unknown output. ".
                 "Please check 'https://bugs.mysql.com/bug.php?id=14564'");
         }
         $procedureStmt = $row['Create Procedure'];
         $ret .= "/*!50003 DROP PROCEDURE IF EXISTS `".
             $row['Procedure']."` */;".PHP_EOL.
             "/*!40101 SET @saved_cs_client     = @@character_set_client */;".PHP_EOL.
             "/*!40101 SET character_set_client = ".$this->dumpSettings['default-character-set']." */;".PHP_EOL.
             "DELIMITER ;;".PHP_EOL.
             $procedureStmt." ;;".PHP_EOL.
             "DELIMITER ;".PHP_EOL.
             "/*!40101 SET character_set_client = @saved_cs_client */;".PHP_EOL.PHP_EOL;
         return $ret;
     }
create_table()
Ifsnop\Mysqldump\TypeAdapterMysql::create_table ($row)
function create_table Get table creation code from database
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1655 of file Mysqldump.php.
     {
         if (!isset($row['Create Table'])) {
             throw new Exception("Error getting table code, unknown output");
         }
         $createTable = $row['Create Table'];
         if ($this->dumpSettings['reset-auto-increment']) {
             $match = "/AUTO_INCREMENT=[0-9]+/s";
             $replace = "";
             $createTable = preg_replace($match, $replace, $createTable);
         }
         $ret = "/*!40101 SET @saved_cs_client     = @@character_set_client */;".PHP_EOL.
             "/*!40101 SET character_set_client = ".$this->dumpSettings['default-character-set']." */;".PHP_EOL.
             $createTable.";".PHP_EOL.
             "/*!40101 SET character_set_client = @saved_cs_client */;".PHP_EOL.
             PHP_EOL;
         return $ret;
     }
create_trigger()
Ifsnop\Mysqldump\TypeAdapterMysql::create_trigger ($triggerName)
function create_trigger Modify trigger code, add delimiters, etc
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1701 of file Mysqldump.php.
     {
         $ret = "";
         if (!isset($row['SQL Original Statement'])) {
             throw new Exception("Error getting trigger code, unknown output");
         }
         $triggerStmt = $row['SQL Original Statement'];
         $definerStr = $this->dumpSettings['skip-definer'] ? '' : '/*!50017 \2*/ ';
         if ($triggerStmtReplaced = preg_replace(
             '/^(CREATE)\s+('.self::DEFINER_RE.')?\s+(TRIGGER\s.*)$/s',
             '/*!50003 \1*/ '.$definerStr.'/*!50003 \3 */',
             $triggerStmt,
             1
         )) {
             $triggerStmt = $triggerStmtReplaced;
         }
         $ret .= "DELIMITER ;;".PHP_EOL.
             $triggerStmt.";;".PHP_EOL.
             "DELIMITER ;".PHP_EOL.PHP_EOL;
         return $ret;
     }
create_view()
Ifsnop\Mysqldump\TypeAdapterMysql::create_view ($row)
function create_view Get view creation code from database
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1676 of file Mysqldump.php.
     {
         $ret = "";
         if (!isset($row['Create View'])) {
             throw new Exception("Error getting view structure, unknown output");
         }
         $viewStmt = $row['Create View'];
         $definerStr = $this->dumpSettings['skip-definer'] ? '' : '/*!50013 \2 */'.PHP_EOL;
         if ($viewStmtReplaced = preg_replace(
             '/^(CREATE(?:\s+ALGORITHM=(?:UNDEFINED|MERGE|TEMPTABLE))?)\s+('
             .self::DEFINER_RE.'(?:\s+SQL SECURITY DEFINER|INVOKER)?)?\s+(VIEW .+)$/',
             '/*!50001 \1 */'.PHP_EOL.$definerStr.'/*!50001 \3 */',
             $viewStmt,
             1
         )) {
             $viewStmt = $viewStmtReplaced;
         };
         $ret .= $viewStmt.';'.PHP_EOL.PHP_EOL;
         return $ret;
     }
databases()
Ifsnop\Mysqldump\TypeAdapterMysql::databases ()
function databases Add sql to create and use database
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1607 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         $databaseName = $args[0];
         $resultSet = $this->dbHandler->query("SHOW VARIABLES LIKE 'character_set_database';");
         $characterSet = $resultSet->fetchColumn(1);
         $resultSet->closeCursor();
         $resultSet = $this->dbHandler->query("SHOW VARIABLES LIKE 'collation_database';");
         $collationDb = $resultSet->fetchColumn(1);
         $resultSet->closeCursor();
         $ret = "";
         $ret .= "CREATE DATABASE /*!32312 IF NOT EXISTS*/ `${databaseName}`".
             " /*!40100 DEFAULT CHARACTER SET ${characterSet} ".
             " COLLATE ${collationDb} */;".PHP_EOL.PHP_EOL.
             "USE `${databaseName}`;".PHP_EOL.PHP_EOL;
         return $ret;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
drop_table()
Ifsnop\Mysqldump\TypeAdapterMysql::drop_table ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1931 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "DROP TABLE IF EXISTS `${args[0]}`;".PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
drop_view()
Ifsnop\Mysqldump\TypeAdapterMysql::drop_view ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1938 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "DROP TABLE IF EXISTS `${args[0]}`;".PHP_EOL.
             "/*!50001 DROP VIEW IF EXISTS `${args[0]}`*/;".PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
end_add_disable_keys()
Ifsnop\Mysqldump\TypeAdapterMysql::end_add_disable_keys ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1898 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "/*!40000 ALTER TABLE `${args[0]}` ENABLE KEYS */;".
             PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
end_add_lock_table()
Ifsnop\Mysqldump\TypeAdapterMysql::end_add_lock_table ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1885 of file Mysqldump.php.
     {
         return "UNLOCK TABLES;".PHP_EOL;
     }
end_disable_autocommit()
Ifsnop\Mysqldump\TypeAdapterMysql::end_disable_autocommit ()
Definition at line 1911 of file Mysqldump.php.
     {
         return "COMMIT;".PHP_EOL;
     }
getDatabaseHeader()
Ifsnop\Mysqldump\TypeAdapterMysql::getDatabaseHeader ()
Definition at line 1946 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "--".PHP_EOL.
             "-- Current Database: `${args[0]}`".PHP_EOL.
             "--".PHP_EOL.PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
lock_table()
Ifsnop\Mysqldump\TypeAdapterMysql::lock_table ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1865 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return $this->dbHandler->exec("LOCK TABLES `${args[0]}` READ LOCAL");
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
parseColumnType()
Ifsnop\Mysqldump\TypeAdapterMysql::parseColumnType ($colType)
Decode column metadata and fill info structure. type, is_numeric and is_blob will always be available.
Parameters
array $colType Array returned from "SHOW COLUMNS FROM tableName"
Returns
array
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1962 of file Mysqldump.php.
     {
         $colInfo = array();
         $colParts = explode(" ", $colType['Type']);
         if ($fparen = strpos($colParts[0], "(")) {
             $colInfo['type'] = substr($colParts[0], 0, $fparen);
             $colInfo['length'] = str_replace(")", "", substr($colParts[0], $fparen + 1));
             $colInfo['attributes'] = isset($colParts[1]) ? $colParts[1] : NULL;
         } else {
             $colInfo['type'] = $colParts[0];
         }
         $colInfo['is_numeric'] = in_array($colInfo['type'], $this->mysqlTypes['numerical']);
         $colInfo['is_blob'] = in_array($colInfo['type'], $this->mysqlTypes['blob']);
         // for virtual columns that are of type 'Extra', column type
         // could by "STORED GENERATED" or "VIRTUAL GENERATED"
         // MySQL reference: https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html
         $colInfo['is_virtual'] = strpos($colType['Extra'], "VIRTUAL GENERATED") !== false || strpos($colType['Extra'], "STORED GENERATED") !== false;
         return $colInfo;
     }
restore_parameters()
Ifsnop\Mysqldump\TypeAdapterMysql::restore_parameters ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 2004 of file Mysqldump.php.
     {
         $ret = "";
         if (false === $this->dumpSettings['skip-tz-utc']) {
             $ret .= "/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;".PHP_EOL;
         }
         $ret .= "/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;".PHP_EOL.
             "/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;".PHP_EOL.
             "/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;".PHP_EOL.
             "/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;".PHP_EOL.
             "/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;".PHP_EOL.
             "/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;".PHP_EOL.
             "/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;".PHP_EOL.PHP_EOL;
         return $ret;
     }
setup_transaction()
Ifsnop\Mysqldump\TypeAdapterMysql::setup_transaction ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1850 of file Mysqldump.php.
     {
         return "SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ";
     }
show_columns()
Ifsnop\Mysqldump\TypeAdapterMysql::show_columns ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1819 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SHOW COLUMNS FROM `${args[0]}`;";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
show_create_event()
Ifsnop\Mysqldump\TypeAdapterMysql::show_create_event ($eventName)
Definition at line 1650 of file Mysqldump.php.
     {
         return "SHOW CREATE EVENT `$eventName`";
     }
show_create_procedure()
Ifsnop\Mysqldump\TypeAdapterMysql::show_create_procedure ($procedureName)
Definition at line 1645 of file Mysqldump.php.
     {
         return "SHOW CREATE PROCEDURE `$procedureName`";
     }
show_create_table()
Ifsnop\Mysqldump\TypeAdapterMysql::show_create_table ($tableName)
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1630 of file Mysqldump.php.
     {
         return "SHOW CREATE TABLE `$tableName`";
     }
show_create_trigger()
Ifsnop\Mysqldump\TypeAdapterMysql::show_create_trigger ($triggerName)
function show_create_trigger Get trigger creation code from database
Todo:
make it do something with sqlite
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1640 of file Mysqldump.php.
     {
         return "SHOW CREATE TRIGGER `$triggerName`";
     }
show_create_view()
Ifsnop\Mysqldump\TypeAdapterMysql::show_create_view ($viewName)
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1635 of file Mysqldump.php.
     {
         return "SHOW CREATE VIEW `$viewName`";
     }
show_events()
Ifsnop\Mysqldump\TypeAdapterMysql::show_events ()
Get query string to ask for names of events from current database.
Parameters
string Name of database
Returns
string
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1841 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SELECT EVENT_NAME AS event_name ".
             "FROM INFORMATION_SCHEMA.EVENTS ".
             "WHERE EVENT_SCHEMA='${args[0]}'";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
show_procedures()
Ifsnop\Mysqldump\TypeAdapterMysql::show_procedures ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1826 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SELECT SPECIFIC_NAME AS procedure_name ".
             "FROM INFORMATION_SCHEMA.ROUTINES ".
             "WHERE ROUTINE_TYPE='PROCEDURE' AND ROUTINE_SCHEMA='${args[0]}'";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
show_tables()
Ifsnop\Mysqldump\TypeAdapterMysql::show_tables ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1794 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SELECT TABLE_NAME AS tbl_name ".
             "FROM INFORMATION_SCHEMA.TABLES ".
             "WHERE TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA='${args[0]}'";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
show_triggers()
Ifsnop\Mysqldump\TypeAdapterMysql::show_triggers ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1812 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SHOW TRIGGERS FROM `${args[0]}`;";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
show_views()
Ifsnop\Mysqldump\TypeAdapterMysql::show_views ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1803 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "SELECT TABLE_NAME AS tbl_name ".
             "FROM INFORMATION_SCHEMA.TABLES ".
             "WHERE TABLE_TYPE='VIEW' AND TABLE_SCHEMA='${args[0]}'";
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
start_add_disable_keys()
Ifsnop\Mysqldump\TypeAdapterMysql::start_add_disable_keys ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1890 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "/*!40000 ALTER TABLE `${args[0]}` DISABLE KEYS */;".
             PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
start_add_lock_table()
Ifsnop\Mysqldump\TypeAdapterMysql::start_add_lock_table ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1878 of file Mysqldump.php.
     {
         $this->check_parameters(func_num_args(), $expected_num_args = 1, __METHOD__);
         $args = func_get_args();
         return "LOCK TABLES `${args[0]}` WRITE;".PHP_EOL;
     }
References Ifsnop\Mysqldump\TypeAdapterMysql\check_parameters().
start_disable_autocommit()
Ifsnop\Mysqldump\TypeAdapterMysql::start_disable_autocommit ()
Definition at line 1906 of file Mysqldump.php.
     {
         return "SET autocommit=0;".PHP_EOL;
     }
start_transaction()
Ifsnop\Mysqldump\TypeAdapterMysql::start_transaction ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1855 of file Mysqldump.php.
     {
         return "START TRANSACTION";
     }
unlock_table()
Ifsnop\Mysqldump\TypeAdapterMysql::unlock_table ()
Reimplemented from Ifsnop\Mysqldump\TypeAdapterFactory.
Definition at line 1873 of file Mysqldump.php.
     {
         return $this->dbHandler->exec("UNLOCK TABLES");
     }
Member Data Documentation
$mysqlTypes
Ifsnop\Mysqldump\TypeAdapterMysql::$mysqlTypes
Definition at line 1573 of file Mysqldump.php.
DEFINER_RE
const Ifsnop\Mysqldump\TypeAdapterMysql::DEFINER_RE = 'DEFINER=`(?:[^`]|``)*`@`(?:[^`]|``)*`'
Definition at line 1569 of file Mysqldump.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/engines/mysqldump/Mysqldump.php