YaWK: YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar Class Reference
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar Class Reference
Social Bar display icons with links to your social network accounts.
Public Member Functions
__construct ($db)
Load all widget settings from database and fill object.
drawSocialBar ()
Draw social bar.
filterUrl ($url)
Filter and sanitize any socialBar URL.
init ()
Init example widget and call a function for demo purpose.
setSocialBarElements ()
Set an array with all social button elements.
Public Member Functions inherited from YAWK\widget
getHeading ($heading, $subtext)
Get widget heading and subtext, return headline.
getWidgetSettingsArray ($db)
Get widget settings and return it as array.
printObject ()
Print all object data.
Public Attributes
$socialBarAlign = 'horizontal'
$socialBarClass = ''
$socialBarElements = ''
$socialBarFacebookIcon = ''
$socialBarFacebookUrl = ''
$socialBarGooglePlusIcon = ''
$socialBarGooglePlusUrl = ''
$socialBarHeading = ''
$socialBarInstagramIcon = ''
$socialBarInstagramUrl = ''
$socialBarLinkColor = ''
$socialBarLinkedInIcon = ''
$socialBarLinkedInUrl = ''
$socialBarLinkTarget = ''
$socialBarLinkTitle = ''
$socialBarMarkup = ''
$socialBarPinterestIcon = ''
$socialBarPinterestUrl = ''
$socialBarSize = 'H2'
$socialBarSubtext = ''
$socialBarTumblrIcon = ''
$socialBarTumblrUrl = ''
$socialBarTwitterIcon = ''
$socialBarTwitterUrl = ''
$socialBarXingIcon = ''
$socialBarXingUrl = ''
$socialBarYouTubeIcon = ''
$socialBarYouTubeUrl = ''
$widget = ''
Public Attributes inherited from YAWK\widget
$data
$date_publish
$date_unpublish
$folder
$id
$marginBottom
$marginTop
$name
$pageID
$position
$published
$sort
$widgetTitle
$widgetType
Additional Inherited Members
Static Public Member Functions inherited from YAWK\widget
static getAllSettingsIntoArray ($db, $widgetID)
Returns an array with all widget settings data.
static getAllWidgetTypes ($db)
Return all widget types as associative array.
static getCurrentWidgetPath ($db)
return current widget path
static getFacebookLikeBox ()
return the facebook likebox widget
static getLoginBox ()
return the user login box widget
static loadWidgetsOfPage ($db, $page)
Returns an array of all widgets that are linked with given page->id.
Detailed Description
Social Bar display icons with links to your social network accounts.
Social Bar - display icons with links to your social network accounts
Embed Links to Twitter, Facebook, Instagram, Pinterest, YouTube and more. You can set any font awesome icon (or any other icon set that you have loaded in the assets section before). If a link is set, the corresponding icon will be drawn.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2018 Daniel Retzl
Version
1.0.0
Definition at line 17 of file socialBar.php.
Constructor & Destructor Documentation
__construct()
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::__construct ($db)
Load all widget settings from database and fill object.
Parameters
object $db Database Object
Load all widget settings on object init.
Definition at line 83 of file socialBar.php.
         {
             // load this widget settings from db
             $this->widget = new \YAWK\widget();
             $settings = $this->widget->getWidgetSettingsArray($db);
             foreach ($settings as $property => $value) {
                 $this->$property = $value;
             }
References $db, $settings, $value, and YAWK\widget\getWidgetSettingsArray().
Member Function Documentation
drawSocialBar()
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::drawSocialBar ()
Draw social bar.
Set settings and draw social bar
Definition at line 172 of file socialBar.php.
         {
             // check if social bar elements array is set
             if (isset($this->socialBarElements) && (is_array($this->socialBarElements)))
             {   // walk through elements
                 echo "<div class=\"row\">";
                 echo "<div class=\"col-md-12\">";
                 // markup <H2, H3, H4, P... start>
                 echo "<".$this->socialBarSize.">";
                 foreach ($this->socialBarElements AS $element => $data)
                 {   // only if url is set...
                     if (!empty($data['url']))
                     {
                         // filter url before output
                         $data['url'] = $this->filterUrl($data['url']);
                         // check if color is set
                         if (isset($data['color']) && (!empty($data['color'])))
                         {   // set css style tag
                             $this->socialBarLinkColor = " style=\"color:#$data[color];\"";
                         }
                         else
                         {   // no link color - no css markup
                             $this->socialBarLinkColor = '';
                         }
                         // set title
                         if (isset($this->socialBarLinkTitle) && (!empty($this->socialBarLinkTitle)))
{
                             $title = " title=\"".$this->socialBarLinkTitle." $element\"";
                         }
                         else
{
                             $title = '';
                         }
                         // check alignment
                         if (isset($this->socialBarAlign) && (!empty($this->socialBarAlign)))
                         {   // if alignment is set to vertical
                             if ($this->socialBarAlign === 'vertical')
                             {   // generate linebreak markup
                                 $lineBreak = "<br>";
                             }
                             else
                                 {   // no linebreak, two blank spaces instead
                                     $lineBreak = '&nbsp;&nbsp;';
                                 }
                         }
                         else
                             {   // no alignment set - two blank spaces are default
                                 $lineBreak = '&nbsp;&nbsp;';
                             }
                         // check if icon is set
                         if (isset($data['icon']) && (!empty($data['icon'])))
{
                             // check social bar element class
                             if (isset($this->socialBarClass) && (!empty($this->socialBarClass)))
                             {   // set css class for this element
                                 $cssClass = " ".$this->socialBarClass."";
                             }
                             else
                             {   // no class required, leave empty
                                 $cssClass = '';
                             }
                             // draw social button
                             echo "<a href=\"$data[url]\"".$this->socialBarLinkColor."$title target=\"$this->socialBarLinkTarget\"><i class=\"$data[icon]".$cssClass."\"></i></a>".$lineBreak."";
                         }
                         else
{
                                 // check social bar element class
                                 if (isset($this->socialBarClass) && (!empty($this->socialBarClass)))
                                 {   // set css class for this element
                                     $cssClass = " class=\"".$this->socialBarClass."\"";
                                 }
                                 else
                                 {   // no class required, leave empty
                                     $cssClass = '';
                                 }
                                 // draw textlink
                                 echo "<a href=\"$data[url]\" title=\"$this->socialBarLinkTitle\" target=\"$this->socialBarLinkTarget\"".$cssClass.">$data[url]</a>".$lineBreak."";
                             }
                     }
                 }
                 echo "</".$this->socialBarSize.">";
                 echo "</div>";
                 echo "</div>";
             }
References YAWK\widget\$data, and YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\filterUrl().
Referenced by YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\init().
filterUrl()
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::filterUrl ($url)
Filter and sanitize any socialBar URL.
filter, sanitize and strip tags from URLs
Definition at line 152 of file socialBar.php.
         {   // check if url is set and not empty
             if (isset($url) && (!empty($url)))
             {
                 // remove illegal chars from url
                 $url = filter_var($url, FILTER_SANITIZE_URL);
                 // strip html tags
                 $url = strip_tags($url);
                 return $url;
             }
             else
                 {   // nothing to return
                     return null;
                 }
References $url.
Referenced by YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\drawSocialBar().
init()
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::init ()
Init example widget and call a function for demo purpose.
Example Widget Init
Definition at line 97 of file socialBar.php.
         {   // call any function or method you have previously defined in this class
             echo $this->getHeading($this->socialBarHeading, $this->socialBarSubtext);
             $this->setSocialBarElements();
             $this->drawSocialBar();
References YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\drawSocialBar(), YAWK\widget\getHeading(), and YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\setSocialBarElements().
setSocialBarElements()
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::setSocialBarElements ()
Set an array with all social button elements.
Helper function that set an array with all social elements. Need to be called before drawSocialBar();
Definition at line 109 of file socialBar.php.
         {   // for every widget data setting create an element with data
             foreach ($this->widget->data AS $element => $data)
             {   // if element is a URL
                 if (strpos($element, 'Url'))
                 {   // get name of this social element
                     $substring = substr("$element", 9);
                     $substring = substr("$substring", 0, -3);
                     // store url property in array
                     $this->socialBarElements[$substring]['url'] = $data;
                 }
                 // if element is an icon
                 else if (strpos($element, 'Icon'))
                 {   // get name of this social element
                     $substring = substr("$element", 9);
                     $substring = substr("$substring", 0, -4);
                     // store icon property in array
                     $this->socialBarElements[$substring]['icon'] = $data;
                 }
                 // if element is a color
                 else if (strpos($element, 'Color'))
                 {   // get name of this social element
                     $substring = substr("$element", 9);
                     $substring = substr("$substring", 0, -5);
                     // store icon property in array
                     $this->socialBarElements[$substring]['color'] = $data;
                 }
             }
             // check if social array is set and not empty
             if (is_array($this->socialBarElements) && (!empty($this->socialBarElements)))
             {   // all good, return social bar data array
                 return $this->socialBarElements;
             }
             else
                 {   // no data here
                     return false;
                 }
References YAWK\widget\$data, and YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\$socialBarElements.
Referenced by YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\init().
Member Data Documentation
$socialBarAlign
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarAlign = 'horizontal'
Parameters
string Social Bar Alignment (horizontal or vertical
Definition at line 74 of file socialBar.php.
$socialBarClass
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarClass = ''
Parameters
string Social Bar CSS Class
Definition at line 76 of file socialBar.php.
$socialBarElements
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarElements = ''
Parameters
array Social Bar Elements
Definition at line 70 of file socialBar.php.
Referenced by YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\setSocialBarElements().
$socialBarFacebookIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarFacebookIcon = ''
Parameters
string Facebook Icon
Definition at line 44 of file socialBar.php.
$socialBarFacebookUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarFacebookUrl = ''
Parameters
string Facebook URL
Definition at line 26 of file socialBar.php.
$socialBarGooglePlusIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarGooglePlusIcon = ''
Parameters
string Google Plus Icon
Definition at line 60 of file socialBar.php.
$socialBarGooglePlusUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarGooglePlusUrl = ''
Parameters
string Google Plus URL
Definition at line 42 of file socialBar.php.
$socialBarHeading
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarHeading = ''
Parameters
string Title that will be shown above widget
Definition at line 22 of file socialBar.php.
$socialBarInstagramIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarInstagramIcon = ''
Parameters
string Instagram Icon
Definition at line 48 of file socialBar.php.
$socialBarInstagramUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarInstagramUrl = ''
Parameters
string Instagram URL
Definition at line 30 of file socialBar.php.
$socialBarLinkColor
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarLinkColor = ''
Parameters
string Social Bar Link Color
Definition at line 68 of file socialBar.php.
$socialBarLinkedInIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarLinkedInIcon = ''
Parameters
string LinkedIn Icon
Definition at line 56 of file socialBar.php.
$socialBarLinkedInUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarLinkedInUrl = ''
Parameters
string LinkedIn URL
Definition at line 38 of file socialBar.php.
$socialBarLinkTarget
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarLinkTarget = ''
Parameters
string Social Bar Link Target
Definition at line 64 of file socialBar.php.
$socialBarLinkTitle
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarLinkTitle = ''
Parameters
string Social Bar Link Target
Definition at line 66 of file socialBar.php.
$socialBarMarkup
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarMarkup = ''
Parameters
string Social Bar Html Markup
Definition at line 62 of file socialBar.php.
$socialBarPinterestIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarPinterestIcon = ''
Parameters
string Pinterest Icon
Definition at line 50 of file socialBar.php.
$socialBarPinterestUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarPinterestUrl = ''
Parameters
string Pinterest URL
Definition at line 32 of file socialBar.php.
$socialBarSize
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarSize = 'H2'
Parameters
string Social Bar Size
Definition at line 72 of file socialBar.php.
$socialBarSubtext
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarSubtext = ''
Parameters
string Subtext will be displayed beside title
Definition at line 24 of file socialBar.php.
$socialBarTumblrIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarTumblrIcon = ''
Parameters
string Tumblr Icon
Definition at line 54 of file socialBar.php.
$socialBarTumblrUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarTumblrUrl = ''
Parameters
string Tumblr URL
Definition at line 36 of file socialBar.php.
$socialBarTwitterIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarTwitterIcon = ''
Parameters
string Twitter Icon
Definition at line 52 of file socialBar.php.
$socialBarTwitterUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarTwitterUrl = ''
Parameters
string Twitter URL
Definition at line 34 of file socialBar.php.
$socialBarXingIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarXingIcon = ''
Parameters
string Xing Icon
Definition at line 58 of file socialBar.php.
$socialBarXingUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarXingUrl = ''
Parameters
string Xing URL
Definition at line 40 of file socialBar.php.
$socialBarYouTubeIcon
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarYouTubeIcon = ''
Parameters
string YouTube Icon
Definition at line 46 of file socialBar.php.
$socialBarYouTubeUrl
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$socialBarYouTubeUrl = ''
Parameters
string YouTube URL
Definition at line 28 of file socialBar.php.
$widget
YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar::$widget = ''
Parameters
object global widget object data
Definition at line 20 of file socialBar.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/widgets/socialBar/classes/socialBar.php