YaWK: YAWK\BACKUP\backup Class Reference
YAWK\BACKUP\backup Class Reference
Public Member Functions
__construct ($db)
backup constructor. prepare temp folder on class instantiation
checkFolders ($restoreFolders)
check restore folders, check + set permissions of restore folders
checkPermissions ($folder)
check folder permissions and return permissions as string (eg 0755)
checkZipFunction ()
Check if ZipArchive function exists.
doRestore ($db, $restoreFolders)
Restore Data physically to folder, restore .sql file to database if needed.
getArchiveBackupFilesArray ()
get all files from archive backup folder into array
getCurrentBackupFilesArray ()
get all files from current backup folder into array
init ($db)
Init Backup Class (run backup)
parseIniFile ($db, $iniFile)
Parse backup ini file.
restore ($db, $file, $folder)
Manage how a backup will be restored from backup folder.
run ($db)
Run a new backup, depending on chosen backup method.
runDatabaseBackup ($db, $storeSqlTmp)
Include mysql backup class and run mysqldump backup.
runFileBackup ($db)
Run File Backup from $sourceFolder.
setIniFile (object $db)
Set backup information file (backup.ini)
setPermissions ($folder, $filemode)
set folder permissions and do some chmod stuff to with given $filemode to $folder
zipFolder ($db, $source, $destination)
Zip a whole folder from $source to $destination.zip.
Public Attributes
$archiveBackupFile = ''
$archiveBackupFiles = array()
$archiveBackupFolder = '../system/backup/archive/'
$archiveBackupNewFile = ''
$archiveBackupSubFolder = ''
$archiveBackupSubFolders = array()
$backupMethod = "database"
$backupSettings = array()
$configFile = ''
$configFilename = "backup.ini"
$currentBackupFiles = array()
$currentBackupFolder = '../system/backup/current/'
$downloadFolder = '../system/backup/download/'
$fileBackup
$mysqlBackup
$overwriteBackup = "true"
$removeAfterZip = "true"
$restoreFile = ''
$restoreFiles = array()
$restoreFolder = ''
$restoreFolders = array()
$restoreMode = ''
$restoreStatus = array()
$sourceFolder = ''
$storeSqlTmp = "false"
$targetFolder = '../system/backup/current/'
$tmpFolder = '../system/backup/tmp/'
$zipBackup = "true"
Detailed Description
Definition at line 20 of file backup.php.
Constructor & Destructor Documentation
__construct()
YAWK\BACKUP\backup::__construct ($db)
backup constructor. prepare temp folder on class instantiation
Parameters
$db
Definition at line 84 of file backup.php.
         {   // prepare temp folder on class instantiation
             // check and create required folders
             $requiredFolders = array($this->tmpFolder, $this->currentBackupFolder, $this->archiveBackupFolder);
             foreach ($requiredFolders as $folder)
             {
                 // if tmp folder does not exist
                 if (!is_dir($folder))
                 {   // create tmp folder
                     if (!mkdir($folder))
                     {   // unable to create tmp folder
                         \YAWK\sys::setSyslog($db, 52, 2, "failed to create " . $folder . "", 0, 0, 0, 0);
                         // return false;
                     }
                     else
                     {   // tmp folder created - try to set owner + group writeable
                         if (chmod($folder, 0775))
                         {   // ok...
                             // return true;
                         }
                         else
                         {   // unable to set folder properties
                             \YAWK\sys::setSyslog($db, 52, 2, "failed to set permissions of folder " . $folder . "", 0, 0, 0, 0);
                             // return false;
                         }
                     }
                 }
             }
References $db, and $folder.
Member Function Documentation
checkFolders()
YAWK\BACKUP\backup::checkFolders ($restoreFolders)
check restore folders, check + set permissions of restore folders
Parameters
$restoreFolders
Returns
bool
Definition at line 821 of file backup.php.
         {
             if (!isset($restoreFolders) || (empty($restoreFolders)))
             {
                 return false;
             }
             // set folders to process
             // $restoreFolders = array('../content/', '../media/', '../system/fonts/', '../system/widgets/');
             // set filemode
             $filemode = 0755;
             // walk through folders
             foreach ($restoreFolders as $folder)
             {   // check if permissions are high enough
                 if ($this->checkPermissions($folder) !== 0775
                 || ($this->checkPermissions($folder) !== 0777))
                 {
                     $folder = "../".$folder;
                     // if not:
                     // iterate folder recursive
                     $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($folder));
                     // walk through items...
                     foreach($iterator as $item)
                     {   // try to set folder permissions
                         if ($this->setPermissions($item, $filemode) === false)
                         {   // unable to set permissions
                             return false;
                         }
                     }
                 }
             }
             return true;
References $folder, $item, YAWK\BACKUP\backup\$restoreFolders, YAWK\BACKUP\backup\checkPermissions(), and YAWK\BACKUP\backup\setPermissions().
checkPermissions()
YAWK\BACKUP\backup::checkPermissions ($folder)
check folder permissions and return permissions as string (eg 0755)
Parameters
$folder
Returns
false|string|null
Definition at line 905 of file backup.php.
         {
             // check if folder is set, not empty and correct type
             if (isset($folder) && (!empty($folder) && (is_string($folder))))
             {
                 // set path
                 $folder = "../".$folder;
                 // check if folder exists...
                 if (is_dir(dirname($folder)))
                 {   // return permissions as string eg '0755'
                     return substr(sprintf('%o', fileperms($folder)), -4);
                 }
                 else
                 {   // folder does not exist
                     return null;
                 }
             }
             else
             {   // folder not set, empty or wrong type
                 return null;
             }
References $folder.
Referenced by YAWK\BACKUP\backup\checkFolders().
checkZipFunction()
YAWK\BACKUP\backup::checkZipFunction ()
Check if ZipArchive function exists.
Returns
bool
Definition at line 423 of file backup.php.
         {
             // check if zip extension is loaded
             if (extension_loaded('zip'))
             {   // ok...
                 return true;
             }
             else
                 {   // zip extension is not loaded
                     return false;
                 }
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\generateZipArchive(), YAWK\BACKUP\backup\restore(), and YAWK\BACKUP\backup\zipFolder().
doRestore()
YAWK\BACKUP\backup::doRestore ($db, $restoreFolders)
Restore Data physically to folder, restore .sql file to database if needed.
Parameters
$db
$restoreFolders
Returns
array
Parameters
db $db
Definition at line 695 of file backup.php.
         {
             /** @param db $db */
             // check if restore folders are set
             if (isset($restoreFolders) && (!empty($restoreFolders)))
             {   // restore folders not set or empty
                 $this->restoreFolders = $restoreFolders;
             }
             // restore each required folder
             foreach ($this->restoreFolders as $folder)
             {
                 // check if content, database, media and system folder exists...
                 if (is_dir(dirname($this->tmpFolder.$folder)))
                 {
                     // copy all folders except database
                     if ($folder !== "database")
                     {
                         // restore folder
                         if (\YAWK\sys::xcopy($this->tmpFolder . $folder, "../$folder") === true)
{
                             $this->restoreStatus[][$folder]['success'] = "true";
                         }
                         else
{
                             // failed to restore folder
                             $this->restoreStatus[][$folder]['success'] = "false";
                             $this->restoreStatus[][$folder]['error'] = "failed to copy " . $this->tmpFolder . "$folder check permissions of ../$folder";
                         }
                     }
                     // IF DATABASE RESTORE IS REQUESTED
                     else
{
                             if (is_file($this->tmpFolder."database-backup.sql_error"))
{
                                 unlink($this->tmpFolder."database-backup.sql_error");
                             }
                             if (is_file($this->tmpFolder."database-backup.sql_filepointer"))
{
                                 unlink($this->tmpFolder."database-backup.sql_filepointer");
                             }
                             // check if database file is in tmp/
                             if (file_exists($this->tmpFolder."database-backup.sql"))
{
                                 // check if backup.ini exists in tmp/database folder
                                 if (is_file($this->tmpFolder.$this->configFilename))
{
                                     // ok, database folder found, parse data from database/folder
                                     $this->backupSettings = $this->parseIniFile($db, $this->tmpFolder.$this->configFilename);
                                     // get array with all tables that should be updated
                                     $activeTables = explode(',', $this->backupSettings['TABLES']);
                                     // delete not needed last item of array
                                     array_pop($activeTables);
                                     // drop all tables that should be updated
                                     $db->dropTables($activeTables);
                                 }
                                 if ($db->import($this->tmpFolder."database-backup.sql", '') === true)
{
                                     $this->restoreStatus[]['database']['success'] = "true";
                                     //return $this->restoreStatus;
                                 }
                                 else
{
                                         $this->restoreStatus[]['database']['success'] = "true";
                                         $this->restoreStatus[]['database']['error'] = "failed to restore database backup.";
                                         //return $this->restoreStatus;
                                     }
                             }
                             // check if database dir exists: tmp/database
                             else if (is_dir(dirname($this->tmpFolder."database/")))
{
                                 // check if backup.ini exists in tmp/database folder
                                 if (is_file($this->tmpFolder."database/".$this->configFilename))
{
                                     // ok, database folder found, parse data from database/folder
                                     $this->backupSettings = $this->parseIniFile($db, $this->tmpFolder."database/".$this->configFilename);
                                     // get array with all tables that should be updated
                                     $activeTables = explode(',', $this->backupSettings['TABLES']);
                                     // delete not needed last item of array
                                     array_pop($activeTables);
                                     // drop all tables that should be updated
                                     $db->dropTables($activeTables);
                                 }
                                 // check if database file exists in tmp/database
                                 if (file_exists($this->tmpFolder."database/database-backup.sql"))
{
                                     if ($db->import($this->tmpFolder."database/database-backup.sql", '') === true)
{
                                         $this->restoreStatus[]['database']['success'] = "true";
                                         //return $this->restoreStatus;
                                     }
                                     else
{
                                         $this->restoreStatus[]['database']['success'] = "true";
                                         $this->restoreStatus[]['database']['error'] = "failed to restore database backup.";
                                         //return $this->restoreStatus;
                                     }
                                 }
                             }
                         }
                 }
                 else
                 {   // failed to restore - folder does not exist or not writeable
                     $this->restoreStatus[][$folder]['error'] = "failed to restore ../$folder : folder is not there or not writeable";
                 }
             }
             // restore fin - delete tmp folder
             \YAWK\sys::recurseRmdir($this->tmpFolder);
             // and return restore status
             return $this->restoreStatus;
References $db, $folder, YAWK\BACKUP\backup\$restoreFolders, YAWK\BACKUP\backup\$restoreStatus, YAWK\BACKUP\backup\parseIniFile(), YAWK\sys\recurseRmdir(), and YAWK\sys\xcopy().
Referenced by YAWK\BACKUP\backup\restore().
getArchiveBackupFilesArray()
YAWK\BACKUP\backup::getArchiveBackupFilesArray ()
get all files from archive backup folder into array
Returns
array|false
Definition at line 354 of file backup.php.
         {
             // get current backup files into array
             $this->archiveBackupFiles = \YAWK\filemanager::getFilesFromFolderToArray($this->archiveBackupSubFolder);
             // check if backup files are set
             if (is_array($this->archiveBackupFiles))
             {   // ok, return files
                 return $this->archiveBackupFiles;
             }
             else
             {   // array is not set
                 return false;
             }
References YAWK\BACKUP\backup\$archiveBackupFiles, archiveBackupFiles, and YAWK\filemanager\getFilesFromFolderToArray().
getCurrentBackupFilesArray()
YAWK\BACKUP\backup::getCurrentBackupFilesArray ()
get all files from current backup folder into array
Returns
array|false
Definition at line 335 of file backup.php.
         {
             // get current backup files into array
             $this->currentBackupFiles = \YAWK\filemanager::getFilesFromFolderToArray($this->currentBackupFolder);
             // check if backup files are set
             if (is_array($this->currentBackupFiles))
             {   // ok, return files
                 return $this->currentBackupFiles;
             }
             else
                 {   // array is not set
                     return false;
                 }
References YAWK\BACKUP\backup\$currentBackupFiles, and YAWK\filemanager\getFilesFromFolderToArray().
init()
YAWK\BACKUP\backup::init ($db)
Init Backup Class (run backup)
Parameters
object $db database object
Returns
bool true: backup init success | false: backup init failed
Definition at line 120 of file backup.php.
         {
             // run backup system
             if ($this->run($db) === true)
             {   // init successful
                 return true;
             }
             else
                 {   // backup init failed
                     return false;
                 }
References $db, and YAWK\BACKUP\backup\run().
parseIniFile()
YAWK\BACKUP\backup::parseIniFile ($db, $iniFile)
Parse backup ini file.
Parameters
$db
$iniFile
Returns
array|false
Definition at line 304 of file backup.php.
         {   // set config file property
             $this->configFile = $iniFile;
             // check if ini file is there
             if (is_file($this->configFile))
             {
                 // update backup settings from ini file
                 $this->backupSettings = parse_ini_file($this->configFile);
                 // check backup settings array is set
                 if (is_array($this->backupSettings))
                 {   // array is set, return backup settings
                     return $this->backupSettings;
                 }
                 else
                     {   // failed parse ini file: but array is not set
                         \YAWK\sys::setSyslog($db, 52, 1, "failed to parse ini file: $this->configFile is there, but backupSettings array is not set", 0, 0, 0, 0);
                         return false;
                     }
             }
             else
                 {   // no ini file found!
                     // set syslog entry
                     \YAWK\sys::setSyslog($db, 51, 1, "failed to parse ini file: $this->configFile not found", 0, 0, 0, 0);
                     return false;
                 }
References YAWK\BACKUP\backup\$backupSettings, and $db.
Referenced by YAWK\BACKUP\backup\doRestore(), and YAWK\BACKUP\backup\restore().
restore()
YAWK\BACKUP\backup::restore ($db, $file, $folder)
Manage how a backup will be restored from backup folder.
Parameters
$db
$file
$folder
Returns
array|false
Definition at line 552 of file backup.php.
         {
             if (isset($file) && (!empty($file)
             && (isset($folder) && (!empty($folder)))))
             {
                 // set restore file property
                 $this->restoreFile = $file;
                 $this->restoreFolder = $folder;
                 // check which backup should be made
                 if (is_writeable($this->tmpFolder))
                 {
                     $source = $this->restoreFolder.$this->restoreFile;
                     $target = $this->tmpFolder.$this->restoreFile;
                     // copy file to tmp folder
                     copy($source, $target);
                     // check if backup file was copied...
                     if (is_file($target))
                     {   // file exists...
                         if ($this->checkZipFunction() === true)
                         {   // ok, create new zip object
                             $zip = new \ZipArchive;
                             // open zip archive
                             $res = $zip->open($target);
                             // if zip open was successful
                             if ($res === TRUE)
                             {   // extract zip file
                                 $zip->extractTo($this->tmpFolder);
                                 // close zip file
                                 $zip->close();
                                 // zip extraction successful
                                 // check if backup.ini file is there...
                                 if (is_file($this->tmpFolder.$this->configFilename))
{
                                     // ok, backup.ini found, parse data from file into array
                                     $this->backupSettings = $this->parseIniFile($db, $this->tmpFolder.$this->configFilename);
                                     // check if backup settings array is set and not empty
                                     if (is_array($this->backupSettings) && (!empty($this->backupSettings)))
{
                                         // PROCESS RESTORE METHODS
                                         switch ($this->backupSettings['METHOD'])
{
                                             // COMPLETE PROCESSING
                                             case "complete":
{
                                                 // set folders for complete restore
                                                 $this->restoreFolders = \YAWK\filemanager::getSubfoldersToArray($this->tmpFolder);
                                                 $this->restoreStatus = $this->doRestore($db, $this->restoreFolders);
{
                                                     return $this->restoreStatus;
                                                 }
                                             }
                                             break;
                                             case "database":
                                             {   // restore database
                                                 $this->restoreFolders = array('database');
                                                 $this->restoreStatus = $this->doRestore($db, $this->restoreFolders);
{
                                                     return $this->restoreStatus;
                                                 }
                                             }
                                             break;
                                             case "mediaFolder":
                                             {   // set media folder restore
                                                 // $this->restoreFolders = \YAWK\filemanager::getSubfoldersToArray($this->tmpFolder);
                                                 $this->restoreFolders = array('media/');
                                                 $this->restoreStatus = $this->doRestore($db, $this->restoreFolders);
{
                                                     return $this->restoreStatus;
                                                 }
                                             }
                                             break;
                                             case "custom":
                                             {   // get custom restore folders
                                                 $this->restoreFolders = \YAWK\filemanager::getSubfoldersToArray($this->tmpFolder);
                                                 $this->restoreStatus = $this->doRestore($db, $this->restoreFolders);
{
                                                     return $this->restoreStatus;
                                                 }
                                             }
                                             break;
                                         }
 //                                        return true;
                                     }
                                     else
{
                                         // backup settings not set or empty
                                         \YAWK\sys::setSyslog($db, 52, 1, "failed to restore backup: restore settings array is not set", 0, 0, 0, 0);
                                         return false;
                                     }
                                 }
                                 else
{
                                         // backup.ini file not found - abort
                                         \YAWK\sys::setSyslog($db, 52, 1, "failed to restore backup: ini file not found - $this->tmpFolder.$this->configFilename", 0, 0, 0, 0);
                                         return false;
                                     }
                             }
                             else
                             {   // unable to open zip file
                                 \YAWK\sys::setSyslog($db, 52, 1, "failed to restore: unable to open ZIP file", 0, 0, 0, 0);
                                 return false;
                             }
                         }
                         else
                             {   // zip extension not loaded
                                 \YAWK\sys::setSyslog($db, 52, 1, "failed to restore: unable to unzip backup package - ZIP extension not loaded.", 0, 0, 0, 0);
                                 return false;
                             }
                     }
                     else
                         {   // target file not found - no backup file copied to tmp folder
                             \YAWK\sys::setSyslog($db, 52, 1, "failed to copy backup package: $source not copied to $target", 0, 0, 0, 0);
                             return false;
                         }
                 }
                 else
                     {
                         // tmp folder is not writeable
                         \YAWK\sys::setSyslog($db, 52, 1, "failed to restore backup: tmp folder ($this->tmpFolder) is not writeable", 0, 0, 0, 0);
                         return false;
                     }
             }
             else
                 {   // no file set
                     \YAWK\sys::setSyslog($db, 52, 1, "failed to restore backup: file not set", 0, 0, 0, 0);
                     return false;
                 }
References $db, $folder, $res, YAWK\BACKUP\backup\$restoreStatus, YAWK\BACKUP\backup\checkZipFunction(), YAWK\BACKUP\backup\doRestore(), YAWK\filemanager\getSubfoldersToArray(), and YAWK\BACKUP\backup\parseIniFile().
run()
YAWK\BACKUP\backup::run ($db)
Run a new backup, depending on chosen backup method.
Parameters
object $db database object
Returns
bool true: backup successful | false: backup failed
Parameters
$db db
Definition at line 138 of file backup.php.
         {   /** @param $db db */
             // check if backup method is set
             if (isset($this->backupMethod) && (!empty($this->backupMethod)))
             {   // which backup method should be executed?
                 switch ($this->backupMethod)
                 {
                     // do a complete backup
                     case "complete":
                     {
                         $this->storeSqlTmp = "true";
                         // run database backup
                         if ($this->runDatabaseBackup($db, $this->storeSqlTmp) === true)
                         {   // db backup was successful
                             // return true;
                         }
                         else
                         {   // failed to run db backup
                             // set syslog entry: db backup could not be made
                         }
                         // run backup of complete system (including database)
                         if ($this->runFileBackup($db) === true)
                         {   // success
                             return true;
                         }
                         else
                         {   // media folder backup failed
                             return false;
                         }
                     }
                     break;
                     // database only
                     case "database":
                     {
                         $this->storeSqlTmp = "false";
                         // run database backup
                         if ($this->runDatabaseBackup($db, $this->storeSqlTmp) === true)
                         {   // db backup was successful
                             return true;
                         }
                         else
                             {   // failed to run db backup
                                 return false;
                             }
                     }
                     break;
                     // media folder only
                     case "mediaFolder":
                     {   // run backup of media folder
                         if ($this->runFileBackup($db) === true)
                         {   // success
                             return true;
                         }
                         else
                             {   // media folder backup failed
                                 return false;
                             }
                     }
                     break;
                     // custom backup selected
                     case "custom":
                     {
                         // store .sql file in tmp folder (because we're doing a file package)
                         $this->storeSqlTmp = "true";
                         // check if database backup is requested by form
                         if (isset($_POST['database']) && (!empty($_POST['database'])))
{
                             // run database backup
                             if ($this->runDatabaseBackup($db, $this->storeSqlTmp) === true)
{
                                 // db backup successful
                             }
                             else
                             {   // db backup FAILED
                                 // return false;
                             }
                         }
                         // run backup of custom folder
                         if($this->runFileBackup($db) === true)
                         {   // success
                             return true;
                         }
                         else
                         {   // custom folder backup failed
                             return false;
                         }
                     }
                     break;
                 }
                 // unknown backup method -
                 return false;
             }
             else
                 {
                     // what if no backup method is set?
                     // add default behavior
                     return false;
                 }
References $db, YAWK\BACKUP\backup\runDatabaseBackup(), and YAWK\BACKUP\backup\runFileBackup().
Referenced by YAWK\BACKUP\backup\init().
runDatabaseBackup()
YAWK\BACKUP\backup::runDatabaseBackup ($db, $storeSqlTmp)
Include mysql backup class and run mysqldump backup.
Returns
bool
Definition at line 373 of file backup.php.
         {
             if (isset($storeSqlTmp) && (!empty($storeSqlTmp)))
             {
                 $this->storeSqlTmp = $storeSqlTmp;
             }
             // include backup-database class
             require_once 'backup-mysqlBackup.php';
             // create new database backup object
             $this->mysqlBackup = new \YAWK\BACKUP\DATABASE\mysqlBackup($this->backupSettings);
             // initialize database backup (this will run mysqldump-php)
             if ($this->mysqlBackup->initMysqlBackup($db, $this->overwriteBackup, $this->zipBackup, $this->storeSqlTmp) === true)
             {   // database backup successful
                 return true;
             }
             else
             {   // database backup failed
                 return false;
             }
References $db, and YAWK\BACKUP\backup\$storeSqlTmp.
Referenced by YAWK\BACKUP\backup\run().
runFileBackup()
YAWK\BACKUP\backup::runFileBackup ($db)
Run File Backup from $sourceFolder.
Returns
bool
Definition at line 400 of file backup.php.
         {
             // include fileBackup class
             require_once 'backup-fileBackup.php';
             // create new file backup object
             $this->fileBackup = new \YAWK\BACKUP\FILES\fileBackup($db);
             // initialize database backup (this will run mysqldump-php)
             if ($this->fileBackup->initFolderBackup($db, $this->overwriteBackup, $this->zipBackup) === true)
             {   // file backup successful
                 return true;
             }
             else
             {   // file backup failed
                 return false;
             }
References $db.
Referenced by YAWK\BACKUP\backup\run().
setIniFile()
YAWK\BACKUP\backup::setIniFile (object $db)
Set backup information file (backup.ini)
Parameters
object $db database handle
Returns
bool
will be added to every .zip file to identify what to do during restore process
Version
1.0.0 Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Definition at line 254 of file backup.php.
                                               : bool
         {   // check if target folder is set
             // check if target folder is writeable
             if (is_writeable($this->targetFolder))
             {   // set configfile (string that includes path + filename)
                 $this->configFile = $this->targetFolder.$this->configFilename;
                 if (isset($this->storeSqlTmp) && ($this->storeSqlTmp == "true"))
                 {
                     if (!is_dir($this->tmpFolder."database"))
                     {
                         mkdir($this->tmpFolder."database");
                     }
                     $this->configFile = $this->tmpFolder."database/".$this->configFilename;
                 }
                 // check if ini file was written
                 if (\YAWK\sys::writeIniFile($this->backupSettings, $this->configFile) === true)
                 {
                     // check if config file is there
                     if (is_file($this->configFile))
                     {   // config file found!
                         return true;
                     }
                     else
                         {   // config file not found
                             \YAWK\sys::setSyslog($db, 51, 1, "backup ini file written, but not found - please check: $this->configFile", 0, 0, 0, 0);
                             return false;
                         }
                 }
                 else
                     {   // unable to write config file
                         \YAWK\sys::setSyslog($db, 52, 2, "failed to write backup config file $this->configFile", 0, 0, 0, 0);
                         return false;
                     }
             }
             else
                 {   // target folder not writeable
                     \YAWK\sys::setSyslog($db, 51, 1, "failed to write backup config file: $this->configFile - target folder not writeable", 0, 0, 0, 0);
                     return false;
                 }
References YAWK\BACKUP\backup\$configFilename, $db, and YAWK\sys\writeIniFile().
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\doSqlBackup().
setPermissions()
YAWK\BACKUP\backup::setPermissions ($folder, $filemode)
set folder permissions and do some chmod stuff to with given $filemode to $folder
Parameters
$folder
$filemode
Returns
bool
Definition at line 861 of file backup.php.
                                                           : bool
         {   // check if filemode is set
             if (!isset($filemode) || (empty($filemode)))
             {   // nope -
                 return false;
             }
             // check if folder is set, not empty and correct type
             if (isset($folder) && (!empty($folder) && (is_string($folder))))
             {
                 // set path
                 $folder = "../".$folder;
                 // check if folder exists...
                 if (is_dir(dirname($folder)))
                 {
                     // try to set folder to writeable for owner + group
                     if (chmod($folder, $filemode))
                     {
                         return true;
                     }
                     else
                         {   // failed to chmod
                             // PERMISSION PROBLEM - user have to edit chmod settings via FTP manually
                             return false;
                         }
                 }
                 else
                     {   // directory not exists
                         return false;
                     }
             }
             else
                 {   // folder not set, empty or wrong type
                     return false;
                 }
References $folder.
Referenced by YAWK\BACKUP\backup\checkFolders().
zipFolder()
YAWK\BACKUP\backup::zipFolder ($db, $source, $destination)
Zip a whole folder from $source to $destination.zip.
Returns
bool
Definition at line 440 of file backup.php.
         {
             // check if zip extension is available
             if ($this->checkZipFunction() === false)
             {   // if not
                 return false;
             }
             // make sure $source file/folder exists
             if (!file_exists($source))
             {   // if not
                 return false;
             }
             // create new zip object
             $zip = new \ZipArchive();
             // make sure to create and open new zip archive
             if (!$zip->open($destination, \ZIPARCHIVE::CREATE))
             {   // if not
                 return false;
             }
             // set path slashes correctly
             $source = str_replace('\\', '/', realpath($source));
             // check if $source is a directoy
             if (is_dir($source) === true)
             {
                 // run recusrive iterators to store files in array
                 $elements = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($source), \RecursiveIteratorIterator::SELF_FIRST);
                 // walk through folder
                 foreach ($elements as $file)
                 {
                     // set path slashes correctly
                     $file = str_replace('\\', '/', $file);
                     // ignore dot folders (. and ..)
                     if( in_array(substr($file, strrpos($file, '/')+1), array('.', '..')) )
                     continue;
                     // set file including path
                     $file = realpath($file);
                     // check if current element is a directory
                     if (is_dir($file) === true)
                     {   // add folder to zip file
                         $zip->addEmptyDir(str_replace($source . '/', '', $file . '/'));
                     }
                     // check if current element is a file
                     else if (is_file($file) === true)
                     {   // add file to zip archive
                         $zip->addFromString(str_replace($source . '/', '', $file), file_get_contents($file));
                     }
                 }
             }
             // if $source is a file
             else if (is_file($source) === true)
             {   // add file to zip archive
                 $zip->addFromString(basename($source), file_get_contents($source));
             }
             // all done, close (and write) zip archive
             $zip->close();
             // check if .zip file is there
             if (is_file($destination))
             {
                 // INSTANT-DOWNLOAD WORKAROUND -
                 // to improve usability, the file will be served as direct downloaded.
                 // this piece of JS code changes the link (from generating .zip to download/zipfile.zip)
                 // due this method its not needed to send location headers (which is not possible at this stage)
                 // this 'hack' should work in most browsers, but may not work in some. (eg: untested in safari)
                 // check if archive ID is set
                 if (isset($_GET['archiveID']) && (!empty($_GET['archiveID'])))
                 {   // set var for JS: downloadArchiveLink (selector)
                     $downloadArchiveLink = "#archive-".$_GET['archiveID'];
                     // set var for JS: link to the file to download
                     $downloadFile = $this->downloadFolder.$_GET['folder'].".zip";
                     // dirty lil piece of JS code to emulate the user's click
                     // (this avoids that he have to click twice to 1)generate + 2)download)
                     echo "
                             <script type='text/javascript'>
                                 $(document).ready(function()
                                 {   // change href attribute for this archive to direct donwload file
                                     $('$downloadArchiveLink').attr('href', '$downloadFile')
                                     // emulate a users click to force direct download
                                     $('$downloadArchiveLink')[0].click();
                                     // if this is not working, the user have to click on that link.
                                 });
                             </script>";
                 }
                 // ZIP file created, force download js fired.
                 return true;
             }
             else
                 {   // failed to create download archive
                     \YAWK\sys::setSyslog($db, 52, 3, "failed to create download archive: $destination", 0, 0, 0, 0);
                     return false;
                 }
References $_GET, $db, and YAWK\BACKUP\backup\checkZipFunction().
Referenced by YAWK\BACKUP\FILES\fileBackup\doFolderBackup().
Member Data Documentation
$archiveBackupFile
YAWK\BACKUP\backup::$archiveBackupFile = ''
Parameters
string archive backup file
Definition at line 43 of file backup.php.
$archiveBackupFiles
YAWK\BACKUP\backup::$archiveBackupFiles = array()
Parameters
array files in archive backup folder
Definition at line 41 of file backup.php.
Referenced by YAWK\BACKUP\backup\getArchiveBackupFilesArray().
$archiveBackupFolder
YAWK\BACKUP\backup::$archiveBackupFolder = '../system/backup/archive/'
Parameters
string archive backup folder path
Definition at line 35 of file backup.php.
$archiveBackupNewFile
YAWK\BACKUP\backup::$archiveBackupNewFile = ''
Parameters
string new archive file
Definition at line 45 of file backup.php.
$archiveBackupSubFolder
YAWK\BACKUP\backup::$archiveBackupSubFolder = ''
Parameters
string archive working subfolder
Definition at line 39 of file backup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\startFileBackup(), and YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup().
$archiveBackupSubFolders
YAWK\BACKUP\backup::$archiveBackupSubFolders = array()
Parameters
array all sub folders in archiveBackupFolder
Definition at line 37 of file backup.php.
$backupMethod
YAWK\BACKUP\backup::$backupMethod = "database"
Parameters
string files|database|complete
Definition at line 51 of file backup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\setBackupSettings().
$backupSettings
YAWK\BACKUP\backup::$backupSettings = array()
Parameters
array backup settings
Definition at line 57 of file backup.php.
Referenced by YAWK\BACKUP\backup\parseIniFile(), and YAWK\BACKUP\FILES\fileBackup\setBackupSettings().
$configFile
YAWK\BACKUP\backup::$configFile = ''
Parameters
string config file, including path
Definition at line 55 of file backup.php.
$configFilename
YAWK\BACKUP\backup::$configFilename = "backup.ini"
Parameters
string filename of the config file (default: backup.ini)
Definition at line 53 of file backup.php.
Referenced by YAWK\BACKUP\backup\setIniFile().
$currentBackupFiles
YAWK\BACKUP\backup::$currentBackupFiles = array()
Parameters
array files in current backup folder
Definition at line 33 of file backup.php.
Referenced by YAWK\BACKUP\backup\getCurrentBackupFilesArray().
$currentBackupFolder
YAWK\BACKUP\backup::$currentBackupFolder = '../system/backup/current/'
Parameters
string current backup folder path
Definition at line 31 of file backup.php.
$downloadFolder
YAWK\BACKUP\backup::$downloadFolder = '../system/backup/download/'
Parameters
string upload folder
Definition at line 47 of file backup.php.
$fileBackup
YAWK\BACKUP\backup::$fileBackup
Parameters
object files backup object
Definition at line 25 of file backup.php.
$mysqlBackup
YAWK\BACKUP\backup::$mysqlBackup
Parameters
object mysql backup object
Definition at line 23 of file backup.php.
$overwriteBackup
YAWK\BACKUP\backup::$overwriteBackup = "true"
Parameters
string overwrite backup files?
Definition at line 59 of file backup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\initFolderBackup(), and YAWK\BACKUP\DATABASE\mysqlBackup\initMysqlBackup().
$removeAfterZip
YAWK\BACKUP\backup::$removeAfterZip = "true"
Parameters
string remove files after zip is complete
Definition at line 63 of file backup.php.
$restoreFile
YAWK\BACKUP\backup::$restoreFile = ''
Parameters
string restore file (zip file)
Definition at line 67 of file backup.php.
$restoreFiles
YAWK\BACKUP\backup::$restoreFiles = array()
Parameters
array restorable files (files from tmp folder)
Definition at line 69 of file backup.php.
$restoreFolder
YAWK\BACKUP\backup::$restoreFolder = ''
Parameters
string restore from folder
Definition at line 73 of file backup.php.
$restoreFolders
YAWK\BACKUP\backup::$restoreFolders = array()
Parameters
array restore folders (content, media, system)
Definition at line 71 of file backup.php.
Referenced by YAWK\BACKUP\backup\checkFolders(), and YAWK\BACKUP\backup\doRestore().
$restoreMode
YAWK\BACKUP\backup::$restoreMode = ''
Parameters
string restore mode (database, mediafolder, complete, custom)
Definition at line 75 of file backup.php.
$restoreStatus
YAWK\BACKUP\backup::$restoreStatus = array()
Parameters
array holds information about the restore process states
Definition at line 77 of file backup.php.
Referenced by YAWK\BACKUP\backup\doRestore(), and YAWK\BACKUP\backup\restore().
$sourceFolder
YAWK\BACKUP\backup::$sourceFolder = ''
Parameters
string source folder to backup
Definition at line 29 of file backup.php.
$storeSqlTmp
YAWK\BACKUP\backup::$storeSqlTmp = "false"
Parameters
string should .sql backup be stored in tmp folder?
Definition at line 65 of file backup.php.
Referenced by YAWK\BACKUP\DATABASE\mysqlBackup\initMysqlBackup(), and YAWK\BACKUP\backup\runDatabaseBackup().
$targetFolder
YAWK\BACKUP\backup::$targetFolder = '../system/backup/current/'
Parameters
string path, where the backup will be stored
Definition at line 27 of file backup.php.
$tmpFolder
YAWK\BACKUP\backup::$tmpFolder = '../system/backup/tmp/'
Parameters
string tmp folder
Definition at line 49 of file backup.php.
$zipBackup
YAWK\BACKUP\backup::$zipBackup = "true"
Parameters
string zip backup if possible
Definition at line 61 of file backup.php.
Referenced by YAWK\BACKUP\FILES\fileBackup\initFolderBackup(), and YAWK\BACKUP\DATABASE\mysqlBackup\initMysqlBackup().
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/backup.php