YaWK: YAWK\update Class Reference
YAWK\update Class Reference
The update class - handles yawk's system update functions.
Public Member Functions
__construct ()
update constructor. Check if allow_url_fopen is enabled
generateLocalFilebase (object $db, array $lang)
Read all files of current YaWK installation and write each file with path + MD5 hash to ini file to compare it later with the possible update files. This is used to verify the integrity of the files.
getUpdateSettings ()
get update settings from local update folder (system/update/update.ini) and return array|false
isServerReachable (string $url)
check if update server is reachable
readUpdateFilebaseFromServer ()
read filebase.ini from update server (https://update.yawk.io/filebase.ini) and return array|false
readUpdateIniFromServer ()
read update.ini from update server (https://update.yawk.io/update.ini) and return array|false
runMigration ($db)
Run the migration SQL file.
Public Attributes
string $base_dir = ''
string $localUpdateSystemPath = 'system/update/'
string $updateFile = 'update.ini'
string $updateFilebase = 'filebase.ini'
string $updateServer = 'https://update.yawk.io/'
array $updateSettings = array()
string $updateVersion = ''
Detailed Description
The update class - handles yawk's system update functions.
YaWK System Updater Class
The YaWK System Updater Class provides methods to facilitate the updating process of the system. It includes features such as checking for new versions, verifying and comparing files to ensure a stable and reliable update. This class aims to simplify the update process and minimize the risk of any errors or issues during the update.
Author
Daniel Retzl danie.nosp@m.lret.nosp@m.zl@gm.nosp@m.ail..nosp@m.com
Copyright
2009-2023 Daniel Retzl @license https://opensource.org/licenses/MIT
Version
1.0.0
Definition at line 17 of file update.php.
Constructor & Destructor Documentation
__construct()
YAWK\update::__construct ()
update constructor. Check if allow_url_fopen is enabled
will be called by xhr request from admin/js/update-generateLocalFilebase.php
Definition at line 52 of file update.php.
         {
             // Get the value of the allow_url_fopen setting
             $allowUrlFopen = ini_get('allow_url_fopen');
             // Check if allow_url_fopen is enabled
             if (!$allowUrlFopen)
             {   // allow_url_fopen is disabled, exit with error
                 // todo: syslog entry
                 echo "allow_url_fopen is disabled, but required to use the update methods. Please enable allow_url_fopen in your php.ini file or ask your admin / hoster for assistance.";
             }
             // check if update server is reachable
             if ($this->isServerReachable($this->updateServer.$this->updateFile) === false)
             {   // todo: syslog entry
                 echo "Update server $this->updateServer not reachable. Update not possible at the moment - please try again later.<br>";
             }
         }
References YAWK\update\isServerReachable().
Member Function Documentation
generateLocalFilebase()
YAWK\update::generateLocalFilebase (object $db, array $lang)
Read all files of current YaWK installation and write each file with path + MD5 hash to ini file to compare it later with the possible update files. This is used to verify the integrity of the files.
Parameters
$db object global db object
$lang array global language array
Returns
void
Definition at line 259 of file update.php.
                                                                       : void
         {
             $this->base_dir = dirname(__FILE__);
             $this->base_dir = substr($this->base_dir, 0, -15); // remove last 15 chars
             // echo "<p>Base directory: $this->base_dir</p>";
             // set path and filename of the ini file
             $updatePath = '/system/update/';
             $updateFolder = $this->base_dir.$updatePath;
             if (!is_dir($updateFolder)){
                 if (!mkdir($updateFolder, 0777, true) && !is_dir($updateFolder)) {
                     throw new \RuntimeException(sprintf('Unable to create "%s" - please check folder permissions or create folder by hand', $updateFolder));
                 }
             }
             $iniFileName = 'filebase.current.ini';
             $input_folder = $this->base_dir;
             $output_file = $updateFolder.$iniFileName;
             $writeIniFile = true;
             // delete old file if exists
             if (is_file($output_file)){
                 unlink($output_file);
             }
             // Open the output file for writing
             $output_handle = fopen($output_file, 'w');
             if (!$output_handle) {
                 // handle the error (e.g. show an error message or log the error)
                 die("Failed to open file");
             }
             // Get the full path of the input folder
             $input_folder = realpath($input_folder);
             // Loop through all files in the input folder and its subfolders
             echo "<p>Building filebase of: <i><small>$input_folder</small></i></p>";
             $root_files = array();
             $subfolder_files = array();
             foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($input_folder)) as $file_path)
             {
                 // Skip some excluded directories and hidden files
                 if ($file_path->isDir()
                     || $file_path->getFilename()[0] == '.'
                     || strpos($file_path, '/.git/') !== false
                     || strpos($file_path, '/.github/') !== false
                     || strpos($file_path, '/.idea/') !== false
                     || strpos($file_path, '/content/') !== false
                     || strpos($file_path, '/media/') !== false)
                 {   // skip this file/folder
                     continue;
                 }
                 // Calculate the MD5 hash of the file
                 $md5_hash = md5_file($file_path);
                 // Get the full path of the file
                 $full_path = realpath($file_path);
                 // Remove the input folder path from the full path to get the relative path
                 $relative_path = substr($full_path, strlen($input_folder) + 1);
                 // Split the relative path into an array of path components
                 $path_components = explode('/', $relative_path);
                 // Check if the path has only one component (i.e. it's a file in the root folder)
                 if (count($path_components) == 1) {
                     $root_files[$relative_path] = $md5_hash;
                 } else {
                     $subfolder_files[$relative_path] = $md5_hash;
                 }
             }
             // Sort the arrays alphabetically by key (the relative path)
             ksort($root_files);
             ksort($subfolder_files);
             // Merge the two arrays so that the root files are listed first
             $hashes = array_merge($root_files, $subfolder_files);
             // init counters
             $totalFiles = count($hashes);   // count total files
             $totalFilesVerified = 0;        // number of verified files
             $totalFilesFailed = 0;          // number of failed files
             // Write the sorted array to the output file in the .ini format
             foreach ($hashes as $relative_path => $md5_hash)
             {   // write each file with its md5 hash to ini file
                 // echo "Writing $relative_path=$md5_hash to $output_file\n";
                 // Write the relative path and MD5 hash to the output file
                 if (file_put_contents($output_file, "$relative_path=$md5_hash\n", FILE_APPEND))
                 {   // line written successfully
                     // echo '<p class="text-success">Verified '.$relative_path.' <small>'.$md5_hash.'</small></p>';
                     $totalFilesVerified++;
                 }
                 else
                 {   // line failed
                     // echo '<p class="text-danger">Failed '.$relative_path.' <small>'.$md5_hash.'</small></p>';
                     $totalFilesFailed++;
                 }
             }
             // Close the output file
             echo '<p class="animated fadeIn slow delay-1s">Indexing <b>'.$totalFiles.'</b> files. Verified <b>'.$totalFilesVerified.'</b> files. Failed <b>'.$totalFilesFailed.'</b> files.</p>';
             if (!is_file($output_file))
             {   // unable to write ini file
                 $iniFileWritten = "<h4 class=\"text-danger\">".$iniFileName." could not be written</h4>";
             }
             else
             {   // ini file written successfully
                 $iniFileWritten = "<p class=\"animated fadeIn slow delay-5s\">Hash values written to: <b><a href=\"$updatePath$iniFileName\" target=\"_blank\">$updatePath$iniFileName</a></b></p>";
             }
             // check if all files were verified
             if ($totalFiles == $totalFilesVerified)
             {   // set success icon, message and colors
                 $icon = '<i class="fa fa-check-circle-o fa-2x text-success"></i>';
                 $done = "<h4 class=\"text-success animated fadeIn slow delay-4s\">".$totalFiles."&nbsp;".$lang['UPDATE_VERIFICATION_SUCCESS']."</h4>";
                 $iconFalse = '';
                 $successColor = ' text-success';
                 $failedColor = '';
             }
             else
             {   // set failure icon, message and colors
                 $iconFalse = '<i class="fa fa-exclamation-triangle fa-2x text-danger"></i>';
                 $done = "<h4 class=\"text-danger\"><b>".$totalFilesFailed." ".$lang['UPDATE_VERIFICATION_FAILED']."</b></h4>";
                 $failedColor = ' text-danger';
                 $successColor = '';
             }
             echo "
 <p class=\"animated fadeIn slow delay-2s$successColor\">$icon &nbsp;Generated hash values: <b>$totalFilesVerified / $totalFiles</b></p>
 <h4 class=\"animated fadeIn slow delay-3s\">$done</h4>
 <p class=\"animated fadeIn slow delay-4s$failedColor\">$iconFalse &nbsp;Failed to verify: <b>$totalFilesFailed</b></p>
 $iniFileWritten";
             // Close the output file
             if (!fclose($output_handle)){
                 echo '<p class="animated fadeIn slow delay-5s">failed to close: '.$updateFolder.$iniFileName.'</p>';
             }
         }
References YAWK\update\$base_dir, $lang, and die.
getUpdateSettings()
YAWK\update::getUpdateSettings ()
get update settings from local update folder (system/update/update.ini) and return array|false
will be called by xhr request from admin/js/update-generateLocalFilebase.php
Returns
array|false
Definition at line 104 of file update.php.
                                            : array|false
         {
             // read update.ini from local update folder
             $this->updateSettings = parse_ini_file($this->localUpdateSystemPath.$this->updateFile);
             if (count($this->updateSettings) < 1)
             {   // unable to read update.ini from local update folder
                 echo "Error: Unable to read update.ini from local update folder. Check if this file exists: ".$this->localUpdateSystemPath.$this->updateFile;
             }
             else {
                 // update.ini read successfully
                 // set update version
                 $this->updateVersion = $this->updateSettings['version'];
                 // return update settings array
                 return $this->updateSettings;
             }
             // return false if something went wrong
             return false;
         }
References YAWK\update\$updateSettings.
isServerReachable()
YAWK\update::isServerReachable (string $url)
check if update server is reachable
returns true if server is reachable, false if not
Parameters
$url string url to check
Returns
bool true|false
Definition at line 76 of file update.php.
                                                       : bool
         {
             $ch = curl_init($url);
             curl_setopt($ch, CURLOPT_NOBODY, true);
             curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
             curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
             curl_setopt($ch, CURLOPT_TIMEOUT, 30);
             curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
             curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
             curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (compatible; UpdateClient/1.0)');
             $response = curl_exec($ch);
             $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
             curl_close($ch);
             if ($httpCode >= 200 && $httpCode < 300) {
                 return true;
             } else {
                 return false;
             }
         }
References $url.
Referenced by YAWK\update\__construct().
readUpdateFilebaseFromServer()
YAWK\update::readUpdateFilebaseFromServer ()
read filebase.ini from update server (https://update.yawk.io/filebase.ini) and return array|false
will be called by xhr request from admin/js/update-readUpdateFilebase.php The filebase.ini contains a list of all files with their md5 hash. This function returns the filebase as array. (to compare it later with the local filebase)
Returns
array|false
Definition at line 131 of file update.php.
                                                       : false|array
         {
             // URL of the remote INI file
             $url = $this->updateServer.'filebase.ini';
             // Get the content of the remote INI file
             $iniContent = file_get_contents($url);
             // Check if the content was retrieved successfully
             if ($iniContent !== false)
             {   // Parse the INI content into an associative array
                 $filebase = parse_ini_string($iniContent);
                 // Print the contents of the array
                 foreach ($filebase as $key => $value)
                 {   // set update array
                     $updateFilebase[$key] = $value;
                 }
             }
             else
             {   // unable to read filebase from remote server
                 echo "Error: Unable to read filebase from remote server. Check if this file exists: $url";
             }
             // return array or false
             return $updateFilebase ?? false;
         }
References YAWK\update\$updateFilebase, $url, and $value.
readUpdateIniFromServer()
YAWK\update::readUpdateIniFromServer ()
read update.ini from update server (https://update.yawk.io/update.ini) and return array|false
Returns
false|array
Definition at line 226 of file update.php.
                                                  : false|array
         {
             // URL of the remote INI file
             $url = $this->updateServer.$this->updateFile;
             // Get the content of the remote INI file
             $iniContent = file_get_contents($url);
             // Check if the content was retrieved successfully
             if ($iniContent !== false)
             {   // Parse the INI content into an associative array
                 $config = parse_ini_string($iniContent);
                 // Print the contents of the array
                 foreach ($config as $key => $value)
                 {   // set update array
                     $updateConfig['UPDATE'][$key] = $value;
                 }
             }
             else
             {   // unable to read update.ini from remote server
                 echo "Error: Unable to read the remote INI file.";
             }
             return $updateConfig ?? false;
         }
References $url, and $value.
runMigration()
YAWK\update::runMigration ($db)
Run the migration SQL file.
if update.ini contains a migration file, this function will be called
Parameters
$db
Returns
void
Definition at line 164 of file update.php.
                                   : void
         {
             // build migration SQL file string
             $migrationUrl = $this->updateServer.$this->updateVersion.'-migration.sql';
             // Fetch the migration SQL file
             $migrationSql = file_get_contents($migrationUrl);
             if ($migrationSql === false) {
                 echo "Error: Unable to fetch migration file from $migrationUrl\n";
                 return;
             }
             // Check if the migration has already been executed
             $checkMigration = $db->prepare("SELECT `version` FROM `migrations` WHERE `version` = ?");
             $checkMigration->bind_param('s', $this->updateVersion);
             $checkMigration->execute();
             $result = $checkMigration->get_result();
             if ($result->num_rows === 0) {
                 // Execute the migration SQL
                 if ($db->multi_query($migrationSql)) {
                     // Record the successful migration
                     $insertMigration = $db->prepare("INSERT INTO `migrations` (`version`, `executed_at`) VALUES (?, NOW())");
                     $insertMigration->bind_param('s', $this->updateVersion);
                     // execute update migration
                     if ($insertMigration->execute())
                     {   // migration executed successfully
                         // todo: syslog entry
                         echo "Migration for version $this->updateVersion executed successfully.\n";
                     }
                     else
                     {   // migration failed
                         // todo: syslog entry
                         echo "Error recording migration for version $this->updateVersion: " . $insertMigration->error . "\n";
                     }
                     // close insert migration connection
                     $insertMigration->close();
                 }
                 else
                 {   // migration failed
                     // todo: syslog entry
                     echo "Error executing migration for version $this->updateVersion: " . $db->error . "\n";
                 }
             }
             else
             {   // migration already executed
                 // todo: syslog entry
                 echo "Migration for version $this->updateVersion already executed.\n";
             }
             // close check migration connection
             $checkMigration->close();
         }
References $db, and $result.
Member Data Documentation
$base_dir
string YAWK\update::$base_dir = ''
Definition at line 20 of file update.php.
Referenced by YAWK\update\generateLocalFilebase().
$localUpdateSystemPath
string YAWK\update::$localUpdateSystemPath = 'system/update/'
Definition at line 36 of file update.php.
$updateFile
string YAWK\update::$updateFile = 'update.ini'
Definition at line 26 of file update.php.
$updateFilebase
string YAWK\update::$updateFilebase = 'filebase.ini'
Definition at line 41 of file update.php.
Referenced by YAWK\update\readUpdateFilebaseFromServer().
$updateServer
string YAWK\update::$updateServer = 'https://update.yawk.io/'
Definition at line 23 of file update.php.
$updateSettings
array YAWK\update::$updateSettings = array()
Definition at line 46 of file update.php.
Referenced by YAWK\update\getUpdateSettings().
$updateVersion
string YAWK\update::$updateVersion = ''
Definition at line 31 of file update.php.
The documentation for this class was generated from the following file:
/var/www/htdocs/yawk.io/system/classes/update.php