YaWK: /var/www/htdocs/yawk.io/admin/js/decline-friend.php File Reference
decline-friend.php File Reference
Variables
if(!isset($db)) $id = $_POST['id']
$requestUsername = $_POST['requestUsername']
$sessionUID = $_POST['sessionUID']
$sessionUsername = \YAWK\user::getUserNameFromID($db, $sessionUID)
$uid = $_POST['uid']
if($sql=$db->query("UPDATE {friends} SET aborted = '1' WHERE id='". $id."'")) else
Variable Documentation
$id
if (!isset($db)) $id = $_POST['id']
Definition at line 13 of file decline-friend.php.
Referenced by SSilence\ImapClient\ImapClient\checkMessageId(), SSilence\ImapClient\ImapClient\deleteMessage(), SSilence\ImapClient\ImapClient\deleteMessages(), SSilence\ImapClient\ImapClient\getEncoding(), SSilence\ImapClient\ImapClient\getMessage(), SSilence\ImapClient\ImapClient\getMessageHeader(), SSilence\ImapClient\ImapClient\getMessageOverview(), SSilence\ImapClient\ImapClient\getMessages(), SSilence\ImapClient\ImapClient\getMessagesByCriteria(), SSilence\ImapClient\ImapClient\getMessagesOverview(), YAWK\sys\getProperty(), SSilence\ImapClient\ImapClient\getSection(), SSilence\ImapClient\ImapClient\getUid(), SSilence\ImapClient\ImapClient\getUnreadMessages(), SSilence\ImapClient\ImapClient\imapFetchStructure(), SSilence\ImapClient\ImapClient\imapHeaderInfo(), SSilence\ImapClient\ImapClient\moveMessage(), SSilence\ImapClient\ImapClient\saveAttachmentsMessagesBySubject(), SSilence\ImapClient\ImapClient\saveEmail(), and SSilence\ImapClient\ImapClient\saveEmailSafe().
$requestUsername
$requestUsername = $_POST['requestUsername']
Definition at line 15 of file decline-friend.php.
$sessionUID
$sessionUID = $_POST['sessionUID']
Definition at line 16 of file decline-friend.php.
$sessionUsername
$sessionUsername = \YAWK\user::getUserNameFromID($db, $sessionUID)
Definition at line 17 of file decline-friend.php.
$uid
$uid = $_POST['uid']
Definition at line 14 of file decline-friend.php.
else
if ($sql=$db->query("UPDATE {friends} SET aborted = '1' WHERE id='". $id."'")) else
Initial value:
{
    echo \YAWK\alert::draw("warning","Warning!", "Could not decline friendship status. Please try again.",'',4200)
Definition at line 23 of file decline-friend.php.