YaWK: /var/www/htdocs/yawk.io/system/engines/AdminLTE/js/demo.js File Reference
demo.js File Reference
Functions
demo_settings append ("<h4 class='control-sidebar-heading'>"+"Layout Options"+"</h4>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='fixed' class='pull-right'/> "+"Fixed layout"+"</label>"+"<p>Activate the fixed layout. You can't use fixed and boxed layouts together</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='layout-boxed'class='pull-right'/> "+"Boxed Layout"+"</label>"+"<p>Activate the boxed layout</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='sidebar-collapse' class='pull-right'/> "+"Toggle Sidebar"+"</label>"+"<p>Toggle the left sidebar's state (open or collapse)</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-enable='expandOnHover' class='pull-right'/> "+"Sidebar Expand on Hover"+"</label>"+"<p>Let the sidebar mini expand on hover</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-controlsidebar='control-sidebar-open' class='pull-right'/> "+"Toggle Right Sidebar Slide"+"</label>"+"<p>Toggle between slide over content and push content effects</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-sidebarskin='toggle' class='pull-right'/> "+"Toggle Right Sidebar Skin"+"</label>"+"<p>Toggle between dark and light skins for the right sidebar</p>"+"</div>")
function change_layout (cls)
function change_skin (cls)
function get (name)
parent () .before(tab_button)
setup ()
function store (name, val)
Variables
function AdminLTE
var demo_settings = $("<div />")
jQuery
var my_skins
var skin_black
var skin_black_light
var skin_blue
var skin_blue_light
var skin_green
var skin_green_light
var skin_purple
var skin_purple_light
var skin_red
var skin_red_light
var skin_yellow
var skin_yellow_light
var skins_list = $("<ul />", {"class": 'list-unstyled clearfix'})
var tab_button
var tab_pane
Function Documentation
append()
tab_pane append ("<h4 class='control-sidebar-heading'>"+"Layout Options"+"</h4>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='fixed' class='pull-right'/> "+"Fixed layout"+"</label>"+"<p>Activate the fixed layout. You can't use fixed and boxed layouts together</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='layout-boxed'class='pull-right'/> "+"Boxed Layout"+"</label>"+"<p>Activate the boxed layout</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-layout='sidebar-collapse' class='pull-right'/> "+"Toggle Sidebar"+"</label>"+"<p>Toggle the left sidebar's state (open or collapse)</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-enable='expandOnHover' class='pull-right'/> "+"Sidebar Expand on Hover"+"</label>"+"<p>Let the sidebar mini expand on hover</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-controlsidebar='control-sidebar-open' class='pull-right'/> "+"Toggle Right Sidebar Slide"+"</label>"+"<p>Toggle between slide over content and push content effects</p>"+"</div>"+"<div class='form-group'>"+"<label class='control-sidebar-subheading'>"+"<input type='checkbox' data-sidebarskin='toggle' class='pull-right'/> "+"Toggle Right Sidebar Skin"+"</label>"+"<p>Toggle between dark and light skins for the right sidebar</p>"+"</div>")
Referenced by ready().
change_layout()
function change_layout (cls)
Toggles layout classes
Parameters
String cls the layout class to toggle
Returns
void
Definition at line 221 of file demo.js.
{
     $("body").toggleClass(cls);
     AdminLTE.layout.fixSidebar();
     //Fix the problem with right sidebar and layout boxed
     if (cls == "layout-boxed")
       AdminLTE.controlSidebar._fix($(".control-sidebar-bg"));
     if ($('body').hasClass('fixed') && cls == 'fixed') {
       AdminLTE.pushMenu.expandOnHover();
       AdminLTE.layout.activate();
     }
     AdminLTE.controlSidebar._fix($(".control-sidebar-bg"));
     AdminLTE.controlSidebar._fix($(".control-sidebar"));
   }
References AdminLTE.
Referenced by setup().
change_skin()
function change_skin (cls)
Replaces the old skin with the new skin
Parameters
String cls the new skin class
Returns
Boolean false to prevent link's default action
Definition at line 240 of file demo.js.
{
     $.each(my_skins, function (i) {
       $("body").removeClass(my_skins[i]);
     });
     $("body").addClass(cls);
     store('skin', cls);
     return false;
   }
References addClass, i, my_skins, removeClass(), and store().
Referenced by setup().
get()
function get (name)
Get a prestored setting
Parameters
String name Name of of the setting
Returns
String The value of the setting | null
Definition at line 271 of file demo.js.
                      {
     if (typeof (Storage) !== "undefined") {
       return localStorage.getItem(name);
     } else {
       window.alert('Please use a modern browser to properly view this template!');
     }
   }
References name, and window.
parent()
parent ()
Referenced by _init().
setup()
function setup ()
Retrieve default settings and apply them to the template
Returns
void
Definition at line 284 of file demo.js.
                    {
     var tmp = get('skin');
     if (tmp && $.inArray(tmp, my_skins))
       change_skin(tmp);
     //Add the change skin listener
     $("[data-skin]").on('click', function (e) {
       if($(this).hasClass('knob'))
         return;
       e.preventDefault();
       change_skin($(this).data('skin'));
     });
     //Add the layout manager
     $("[data-layout]").on('click', function () {
       change_layout($(this).data('layout'));
     });
     $("[data-controlsidebar]").on('click', function () {
       change_layout($(this).data('controlsidebar'));
       var slide = !AdminLTE.options.controlSidebarOptions.slide;
       AdminLTE.options.controlSidebarOptions.slide = slide;
       if (!slide)
         $('.control-sidebar').removeClass('control-sidebar-open');
     });
     $("[data-sidebarskin='toggle']").on('click', function () {
       var sidebar = $(".control-sidebar");
       if (sidebar.hasClass("control-sidebar-dark")) {
         sidebar.removeClass("control-sidebar-dark")
         sidebar.addClass("control-sidebar-light")
       } else {
         sidebar.removeClass("control-sidebar-light")
         sidebar.addClass("control-sidebar-dark")
       }
     });
     $("[data-enable='expandOnHover']").on('click', function () {
       $(this).attr('disabled', true);
       AdminLTE.pushMenu.expandOnHover();
       if (!$('body').hasClass('sidebar-collapse'))
         $("[data-layout='sidebar-collapse']").click();
     });
     // Reset options
     if ($('body').hasClass('fixed')) {
       $("[data-layout='fixed']").attr('checked', 'checked');
     }
     if ($('body').hasClass('layout-boxed')) {
       $("[data-layout='layout-boxed']").attr('checked', 'checked');
     }
     if ($('body').hasClass('sidebar-collapse')) {
       $("[data-layout='sidebar-collapse']").attr('checked', 'checked');
     }
   }
References AdminLTE, change_layout(), change_skin(), e, my_skins, on, and removeClass().
store()
function store (name, val)
Store a new settings in the browser
Parameters
String name Name of the setting
String val Value of the setting
Returns
void
Definition at line 257 of file demo.js.
{
     if (typeof (Storage) !== "undefined") {
       localStorage.setItem(name, val);
     } else {
       window.alert('Please use a modern browser to properly view this template!');
     }
   }
References name, and window.
Referenced by change_skin().
Variable Documentation
AdminLTE
AdminLTE
Initial value:
{
  "use strict"
Definition at line 7 of file demo.js.
Referenced by change_layout(), and setup().
demo_settings
var demo_settings = $("<div />")
Definition at line 49 of file demo.js.
jQuery
jQuery
Definition at line 340 of file demo.js.
my_skins
var my_skins
Initial value:
= [
    "skin-blue",
    "skin-black",
    "skin-red",
    "skin-yellow",
    "skin-purple",
    "skin-green",
    "skin-blue-light",
    "skin-black-light",
    "skin-red-light",
    "skin-yellow-light",
    "skin-purple-light",
    "skin-green-light"
  ]
List of all the available skins
@type Array
Definition at line 16 of file demo.js.
Referenced by change_skin(), and setup().
skin_black
var skin_black
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-black' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div style='box-shadow: 0 0 2px rgba(0,0,0,0.1)' class='clearfix'><span style='display:block; width: 20%; float: left; height: 7px; background: #fefefe;'></span><span style='display:block; width: 80%; float: left; height: 7px; background: #fefefe;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Black</p>")
Definition at line 116 of file demo.js.
skin_black_light
var skin_black_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-black-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div style='box-shadow: 0 0 2px rgba(0,0,0,0.1)' class='clearfix'><span style='display:block; width: 20%; float: left; height: 7px; background: #fefefe;'></span><span style='display:block; width: 80%; float: left; height: 7px; background: #fefefe;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px'>Black Light</p>")
Definition at line 166 of file demo.js.
skin_blue
var skin_blue
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-blue' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px; background: #367fa9;'></span><span class='bg-light-blue' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222d32;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Blue</p>")
Definition at line 108 of file demo.js.
skin_blue_light
var skin_blue_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-blue-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px; background: #367fa9;'></span><span class='bg-light-blue' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px'>Blue Light</p>")
Definition at line 158 of file demo.js.
skin_green
var skin_green
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-green' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-green-active'></span><span class='bg-green' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222d32;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Green</p>")
Definition at line 132 of file demo.js.
skin_green_light
var skin_green_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-green-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-green-active'></span><span class='bg-green' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px'>Green Light</p>")
Definition at line 182 of file demo.js.
skin_purple
var skin_purple
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-purple' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-purple-active'></span><span class='bg-purple' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222d32;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Purple</p>")
Definition at line 124 of file demo.js.
skin_purple_light
var skin_purple_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-purple-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-purple-active'></span><span class='bg-purple' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px'>Purple Light</p>")
Definition at line 174 of file demo.js.
skin_red
var skin_red
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-red' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-red-active'></span><span class='bg-red' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222d32;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Red</p>")
Definition at line 140 of file demo.js.
skin_red_light
var skin_red_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-red-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-red-active'></span><span class='bg-red' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px'>Red Light</p>")
Definition at line 190 of file demo.js.
skin_yellow
var skin_yellow
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-yellow' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-yellow-active'></span><span class='bg-yellow' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #222d32;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin'>Yellow</p>")
Definition at line 148 of file demo.js.
skin_yellow_light
var skin_yellow_light
Initial value:
=
      $("<li />", {style: "float:left; width: 33.33333%; padding: 5px;"})
          .append("<a href='javascript:void(0);' data-skin='skin-yellow-light' style='display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)' class='clearfix full-opacity-hover'>"
          + "<div><span style='display:block; width: 20%; float: left; height: 7px;' class='bg-yellow-active'></span><span class='bg-yellow' style='display:block; width: 80%; float: left; height: 7px;'></span></div>"
          + "<div><span style='display:block; width: 20%; float: left; height: 20px; background: #f9fafc;'></span><span style='display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;'></span></div>"
          + "</a>"
          + "<p class='text-center no-margin' style='font-size: 12px;'>Yellow Light</p>")
Definition at line 198 of file demo.js.
skins_list
var skins_list = $("<ul />", {"class": 'list-unstyled clearfix'})
Definition at line 105 of file demo.js.
tab_button
var tab_button
Initial value:
= $("<li />", {"class": "active"})
      .html("<a href='#control-sidebar-theme-demo-options-tab' data-toggle='tab'>"
      + "<i class='fa fa-wrench'></i>"
      + "</a>")
Definition at line 38 of file demo.js.
tab_pane
var tab_pane
Initial value:
= $("<div />", {
    "id": "control-sidebar-theme-demo-options-tab",
    "class": "tab-pane active"
  })
Definition at line 32 of file demo.js.