YaWK: /var/www/htdocs/yawk.io/admin/js/dismiss-notifications.php File Reference
dismiss-notifications.php File Reference
Variables
$db = new \YAWK\db()
$uid = $_POST['uid']
if($db->query("UPDATE {syslog} SET seen = '1' WHERE seen = '0'")) else
Variable Documentation
$db
$db = new \YAWK\db()
Definition at line 4 of file dismiss-notifications.php.
Referenced by YAWK\BACKEND\AdminLTE\__construct(), YAWK\BACKUP\backup\__construct(), YAWK\user\__construct(), YAWK\PLUGINS\USERPAGE\stats\__construct(), YAWK\WIDGETS\BLOG\WIDGET\blogWidget\__construct(), YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus\__construct(), YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\__construct(), YAWK\WIDGETS\CLOCK\CURRENT\clock\__construct(), YAWK\WIDGETS\CONTENTANIMATOR\ANIMATE\contentAnimator\__construct(), YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\__construct(), YAWK\WIDGETS\CUSTOM_HTML\CODE\customHtml\__construct(), YAWK\WIDGETS\EMBED_PAGE\PAGE\embedPage\__construct(), YAWK\WIDGETS\EXAMPLE\DEMO\example\__construct(), YAWK\WIDGETS\FACEBOOK\FBCOVER\fbCover\__construct(), YAWK\WIDGETS\FACEBOOK\EVENTS\fbEvents\__construct(), YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\__construct(), YAWK\WIDGETS\FACEBOOK\FEED\fbFeed\__construct(), YAWK\WIDGETS\FACEBOOK\GALLERY\fbGallery\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEBUTTON\fbLikeButton\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\__construct(), YAWK\WIDGETS\FACEBOOK\POSTING\fbPosting\__construct(), YAWK\WIDGETS\FACEBOOK\VIDEO\fbVideo\__construct(), YAWK\WIDGETS\FUCKADBLOCK\BLOCK\fuckadblock\__construct(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\__construct(), YAWK\WIDGETS\GOOGLE\ANALYTICS\googleAnalytics\__construct(), YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\__construct(), YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\__construct(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\__construct(), YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\__construct(), YAWK\WIDGETS\PINTEREST\FOLLOW\pinterestFollow\__construct(), YAWK\WIDGETS\PINTEREST\PIN\pinterestPin\__construct(), YAWK\WIDGETS\PINTEREST\PROFILE\pinterestProfile\__construct(), YAWK\WIDGETS\PLYR\PLAYER\plyr\__construct(), YAWK\WIDGETS\PREZI\EMBED\prezi\__construct(), YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\__construct(), YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\__construct(), YAWK\WIDGETS\SPOTIFY\EMBED\spotify\__construct(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\__construct(), YAWK\WIDGETS\TWITCH\EMBED\twitch\__construct(), YAWK\WIDGETS\TWITTER\GRID\twitterGrid\__construct(), YAWK\WIDGETS\TWITTER\TIMELINE\twitterTimeline\__construct(), YAWK\WIDGETS\TWITTER\TWEET\twitterTweet\__construct(), YAWK\WIDGETS\TWITTER\BUTTON\twitterTweetButton\__construct(), YAWK\WIDGETS\YOUTUBE\VIDEO\youtube\__construct(), YAWK\PLUGINS\MESSAGES\messages\__construct(), YAWK\PLUGINS\USERPAGE\userpage\__construct(), YAWK\WIDGETS\BOOKING\FORM\bookingWidget\__construct(), YAWK\menu\addEntry(), YAWK\user\ajaxLogin(), YAWK\PLUGINS\SIGNUP\buildForm\buildForm(), YAWK\stats\calculateStatsFromArray(), YAWK\menu\changeLanguage(), YAWK\menu\changeTitle(), YAWK\sys\checkIfAssetsAreLoaded(), YAWK\template\checkIfTemplateAlreadyExists(), YAWK\user\checkResetToken(), YAWK\page\copy(), YAWK\BACKUP\FILES\fileBackup\copyFolder(), YAWK\stats\countBrowsers(), YAWK\stats\countDaytime(), YAWK\stats\countDeviceTypes(), YAWK\stats\countLogins(), YAWK\stats\countMessages(), YAWK\stats\countOS(), YAWK\stats\countOSVersions(), YAWK\page\countPages(), YAWK\user\countUsers(), YAWK\stats\countWeekdays(), YAWK\page\create(), YAWK\menu\createMenu(), YAWK\page\delete(), YAWK\menu\delete(), YAWK\menu\deleteEntry(), YAWK\stats\deleteOutdatedSessions(), YAWK\template\deleteSettingsCSSFile(), YAWK\menu\display(), YAWK\menu\displayEditable(), YAWK\menu\displayGlobalMenu(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu(), YAWK\BACKUP\FILES\fileBackup\doFolderBackup(), YAWK\BACKUP\backup\doRestore(), YAWK\BACKUP\DATABASE\mysqlBackup\doSqlBackup(), YAWK\template\downloadTemplate(), YAWK\template\drawAssetsSelectFields(), YAWK\template\drawAssetsTitles(), YAWK\WIDGETS\BLOG\WIDGET\blogWidget\drawBlogWidget(), YAWK\BACKEND\AdminLTE\drawHtmlContent(), YAWK\BACKEND\AdminLTE\drawHtmlEnd(), YAWK\BACKEND\AdminLTE\drawHtmlFooter(), YAWK\BACKEND\AdminLTE\drawHtmlLogo(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarMessagesMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarNotificationsMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarUserAccountMenu(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarWebmailMenu(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\drawImageGallery(), YAWK\BACKEND\dashboard\drawLatestPagesBox(), YAWK\BACKEND\dashboard\drawLatestUsers(), YAWK\backend\drawLoginBox(), YAWK\menu\drawLogoutMenu(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\drawMenu(), YAWK\PLUGINS\MESSAGES\messages\drawMenu(), YAWK\PLUGINS\USERPAGE\profile\drawProfile(), YAWK\backend\drawTemplateSelectField(), YAWK\WIDGETS\BOOKING\FORM\bookingWidget\drawThankYouMessage(), YAWK\tipOfDay\drawTip(), YAWK\stats\drawUserStats(), YAWK\backend\drawWidgetsOnPageBox(), YAWK\menu\editEntry(), YAWK\controller\filterfilename(), YAWK\BACKUP\DATABASE\mysqlBackup\generateZipArchive(), YAWK\template\getActiveBodyFont(), YAWK\template\getActivegfont(), YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields(), YAWK\settings\getAllSettingsArray(), YAWK\settings\getAllSettingsIntoArray(), YAWK\template\getAllSettingsIntoArray(), YAWK\widget\getAllSettingsIntoArray(), YAWK\widget\getAllWidgetTypes(), YAWK\template\getAssetsByType(), YAWK\page\getContent(), YAWK\language\getCurrentLanguage(), YAWK\page\getCurrentLanguageByID(), YAWK\language\getCurrentLanguageStatic(), YAWK\template\getCurrentTemplateId(), YAWK\widget\getCurrentWidgetPath(), YAWK\template\getCustomCSSFile(), YAWK\template\getCustomJSFile(), YAWK\sys\getDirPrefix(), YAWK\editor\getEditor(), YAWK\settings\getEditorSettings(), YAWK\PLUGINS\SIGNUP\buildForm\getForm(), YAWK\settings\getFormElements(), YAWK\template\getFormElements(), YAWK\backend\getFX(), YAWK\template\getGoogleFontsArray(), YAWK\sys\getGroupFromId(), YAWK\sys\getGroupId(), YAWK\sys\getGroups(), YAWK\BACKUP\DATABASE\mysqlBackup\getHashValue(), YAWK\BACKUP\FILES\fileBackup\getHashValue(), YAWK\sys\getHost(), YAWK\plugin\getIdByName(), YAWK\PLUGINS\MESSAGES\messages\getInbox(), YAWK\stats\getJsonBrowsers(), YAWK\stats\getJsonDaytimeBarChart(), YAWK\stats\getJsonDaytimeLineChart(), YAWK\stats\getJsonDaytimePieChart(), YAWK\stats\getJsonDeviceTypes(), YAWK\stats\getJsonLogins(), YAWK\stats\getJsonOS(), YAWK\stats\getJsonOSVersions(), YAWK\page\getLatest(), YAWK\user\getLatestUsers(), YAWK\PLUGINS\SIGNUP\buildForm\getLayout(), YAWK\PLUGINS\SIGNUP\buildForm\getLegend(), YAWK\user\getLoginData(), YAWK\settings\getLongSetting(), YAWK\template\getMaxId(), YAWK\menu\getMenuEntryStatus(), YAWK\menu\getMenuIdFromLanguage(), YAWK\sys\getMenuItem(), YAWK\menu\getMenuItemTitleByID(), YAWK\sys\getMenuLanguage(), YAWK\sys\getMenuName(), YAWK\menu\getMenuNameByID(), YAWK\backend\getMenuNamesArray(), YAWK\backend\getMenusArray(), YAWK\menu\getMenuStatus(), YAWK\page\getMetaTags(), YAWK\page\getMetaTagsArray(), YAWK\plugin\getNameById(), YAWK\stats\getOnlineUsers(), YAWK\openAI\getOpenAIKey(), YAWK\backend\getPagesArray(), YAWK\filemanager\getPhpMaxUploadSize(), YAWK\template\getPositionDivBox(), YAWK\template\getPositionIndicatorStatusArray(), YAWK\template\getPositionStatesArray(), YAWK\filemanager\getPostMaxSize(), YAWK\page\getProperty(), YAWK\sys\getProperty(), YAWK\sys\getRobotsText(), YAWK\PLUGINS\USERPAGE\userpage\getRootPage(), YAWK\settings\getSetting(), YAWK\settings\getSettingDescription(), YAWK\settings\getSettingsByType(), YAWK\stats\getStatsArray(), YAWK\sys\getSubMenu(), YAWK\PLUGINS\SIGNUP\buildForm\getSubmitButton(), YAWK\template\getTemplateIds(), YAWK\template\getTemplateSettingsArray(), YAWK\PLUGINS\SIGNUP\buildForm\getTerms(), YAWK\PLUGINS\SIGNUP\buildForm\getTitle(), YAWK\filemanager\getUploadMaxFilesize(), YAWK\user\getUserArray(), YAWK\user\getUserEmail(), YAWK\user\getUserList(), YAWK\PLUGINS\USERPAGE\userpage\getUserPage(), YAWK\stats\getUserStats(), YAWK\user\getUserTemplateID(), YAWK\template\getValidTemplateID(), YAWK\settings\getValueSettingsArray(), YAWK\settings\getWidgetSetting(), YAWK\widget\getWidgetSettingsArray(), YAWK\template\includeHeader(), YAWK\BACKUP\DATABASE\mysqlBackup\includeMysqldumpClass(), YAWK\BACKUP\backup\init(), YAWK\PLUGINS\SIGNUP\buildForm\init(), YAWK\PLUGINS\USERPAGE\profile\init(), YAWK\PLUGINS\USERPAGE\settings\init(), YAWK\WIDGETS\BLOG\WIDGET\blogWidget\init(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\init(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\init(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\init(), YAWK\WIDGETS\BOOKING\FORM\bookingWidget\init(), YAWK\language\init(), YAWK\PLUGINS\USERPAGE\userpage\init(), YAWK\BACKUP\DATABASE\mysqlBackup\initMysqlBackup(), YAWK\stats\insertData(), YAWK\user\isAllowedToOverrideTemplate(), YAWK\user\isAnybodyThere(), YAWK\menu\isPublished(), YAWK\user\isTemplateEqual(), YAWK\template\loadActiveAssets(), YAWK\template\loadActiveAssetsIntoArray(), YAWK\template\loadAllSettingsIntoArray(), YAWK\template\loadGoogleFonts(), YAWK\page\loadProperties(), YAWK\template\loadProperties(), YAWK\page\loadPropertiesByID(), YAWK\template\loadPropertiesIntoArray(), YAWK\template\loadSettingsTypesIntoArray(), YAWK\widget\loadWidgetsOfPage(), YAWK\PLUGINS\MESSAGES\messages\MessageView(), YAWK\BACKUP\backup\parseIniFile(), YAWK\installer\resetInstallation(), YAWK\BACKUP\backup\restore(), YAWK\template\returnCurrentBootstrapVersion(), YAWK\BACKUP\backup\run(), YAWK\BACKUP\backup\runDatabaseBackup(), YAWK\BACKUP\backup\runFileBackup(), YAWK\update\runMigration(), YAWK\page\save(), YAWK\template\saveAs(), YAWK\template\saveProperties(), YAWK\search\searchBlogs(), YAWK\search\searchMenus(), YAWK\search\searchPages(), YAWK\search\searchUsers(), YAWK\search\searchWidgets(), YAWK\user\sendResetEmail(), YAWK\BACKUP\backup\setIniFile(), YAWK\settings\setLongSetting(), YAWK\user\setNewPassword(), YAWK\stats\setOnlineUsers(), YAWK\template\setPosition(), YAWK\settings\setSetting(), YAWK\stats\setStats(), YAWK\settings\setTemplateSetting(), YAWK\user\setUserTemplate(), YAWK\settings\setWidgetSetting(), YAWK\PLUGINS\SIGNUP\signup\signUp(), YAWK\BACKUP\FILES\fileBackup\startFileBackup(), YAWK\BACKUP\DATABASE\mysqlBackup\startMysqlBackup(), YAWK\installer\step3(), YAWK\installer\step4(), YAWK\installer\step5(), YAWK\template\switchPositionIndicators(), YAWK\menu\toggleItemOffline(), YAWK\page\toggleLock(), YAWK\menu\toggleOffline(), YAWK\page\toggleOffline(), YAWK\settings\toggleOffline(), YAWK\template\uploadTemplate(), YAWK\page\writeContent(), and YAWK\BACKUP\backup\zipFolder().
$uid
$uid = $_POST['uid']
Definition at line 5 of file dismiss-notifications.php.
else
if ($db->query("UPDATE {syslog} SET seen = '1' WHERE seen = '0'")) else
Initial value:
{
    echo "false"
Definition at line 11 of file dismiss-notifications.php.