YaWK: /var/www/htdocs/yawk.io/admin/js/email-send.php File Reference
email-send.php File Reference
Variables
$imapStream = imap_open($server, $mail->Username, $mail->Password)
$mail = new PHPMailer(true)
$result = imap_append($imapStream, $server.'Sent', $mail->getSentMIMEMessage(), "\\Seen")
$server = "{".$webmailSettings['webmail_imap_server'].":".$webmailSettings['webmail_imap_port']."/imap/".$webmailSettings['webmail_imap_encrypt']."}"
if(!isset($db)) $webmailSettings = \YAWK\settings::getValueSettingsArray($db, "webmail_")
$mail AltBody = $_POST['body']
$mail Body = $_POST['body']
if(!empty($_FILES)) else
$mail Host = $webmailSettings['webmail_smtp_server']
$mail Password = $webmailSettings['webmail_smtp_pwd']
$mail Port = $webmailSettings['webmail_smtp_port']
$mail SMTPAuth = true
$mail SMTPSecure = $webmailSettings['webmail_smtp_encrypt']
$mail Subject = $_POST['subject']
try
$mail Username = $webmailSettings['webmail_smtp_username']
Variable Documentation
$imapStream
$imapStream = imap_open($server, $mail->Username, $mail->Password)
Definition at line 135 of file email-send.php.
$mail
$mail = new PHPMailer(true)
Definition at line 25 of file email-send.php.
Referenced by PHPMailer\sendmailSend().
$result
$result = imap_append($imapStream, $server.'Sent', $mail->getSentMIMEMessage(), "\\Seen")
Definition at line 137 of file email-send.php.
Referenced by YAWK\template\checkIfTemplateAlreadyExists(), YAWK\page\copy(), YAWK\page\countPages(), SSilence\ImapClient\ImapClient\countUnreadMessages(), YAWK\user\countUsers(), PHPMailer\createHeader(), PHPMailer\getBoundary(), YAWK\user\getLatestUsers(), PHPMailer\getMailMIME(), SSilence\ImapClient\ImapClient\getMessages(), SSilence\ImapClient\ImapClient\getMessagesByCriteria(), SSilence\ImapClient\ImapClient\getUnreadMessages(), YAWK\user\getUserArray(), YAWK\widget\loadWidgetsOfPage(), PHPMailer\mailPassthru(), PHPMailer\mailSend(), YAWK\sys\read_recursive(), YAWK\installer\resetInstallation(), YAWK\update\runMigration(), YAWK\SimpleImage\save(), YAWK\db\select(), SSilence\ImapClient\ImapClient\selectFolder(), PHPMailer\sendmailSend(), and PHPMailer\serverHostname().
$server
$server = "{".$webmailSettings['webmail_imap_server'].":".$webmailSettings['webmail_imap_port']."/imap/".$webmailSettings['webmail_imap_encrypt']."}"
Definition at line 133 of file email-send.php.
Referenced by YAWK\BACKEND\AdminLTE\drawHtmlNavbarWebmailMenu().
$webmailSettings
if (!isset($db)) $webmailSettings = \YAWK\settings::getValueSettingsArray($db, "webmail_")
Definition at line 22 of file email-send.php.
AltBody
$mail AltBody = $_POST['body']
Definition at line 129 of file email-send.php.
Referenced by PHPMailer\alternativeExists(), PHPMailer\createBody(), PHPMailer\msgHTML(), PHPMailer\preSend(), and PHPMailer\setWordWrap().
Body
$mail Body = $_POST['body']
Definition at line 127 of file email-send.php.
Referenced by PHPMailer\createBody(), PHPMailer\msgHTML(), PHPMailer\preSend(), and PHPMailer\setWordWrap().
else
if (!empty($_FILES)) else
Initial value:
{
            echo "<div class=\"row\">"
Definition at line 111 of file email-send.php.
Host
$mail Host = $webmailSettings['webmail_smtp_server']
Definition at line 34 of file email-send.php.
Referenced by PHPMailer\smtpConnect().
Password
$mail Password = $webmailSettings['webmail_smtp_pwd']
Definition at line 40 of file email-send.php.
Port
$mail Port = $webmailSettings['webmail_smtp_port']
Definition at line 44 of file email-send.php.
SMTPAuth
$mail SMTPAuth = true
Definition at line 36 of file email-send.php.
Referenced by PHPMailer\smtpConnect().
SMTPSecure
$mail SMTPSecure = $webmailSettings['webmail_smtp_encrypt']
Definition at line 42 of file email-send.php.
Referenced by PHPMailer\smtpConnect().
Subject
$mail Subject = $_POST['subject']
Definition at line 125 of file email-send.php.
Referenced by PHPMailer\createHeader(), PHPMailer\mailSend(), PHPMailer\preSend(), PHPMailer\sendmailSend(), and PHPMailer\smtpSend().
try
try
Initial value:
{
    $mail->SMTPDebug = 0
Definition at line 27 of file email-send.php.
Username
$mail Username = $webmailSettings['webmail_smtp_username']
Definition at line 38 of file email-send.php.