YaWK: /var/www/htdocs/yawk.io/system/engines/jquery/jquery.textillate.js File Reference
jquery.textillate.js File Reference
Functions
function animate ($t, effect, cb)
function animateTokens ($tokens, options, cb)
function getData (node)
function isInEffect (effect)
function isOutEffect (effect)
function shuffle (o)
function stringToBoolean (str)
Variables
fn textillate defaults
jQuery
var Textillate
Function Documentation
animate()
function animate ($t, effect, cb)
Definition at line 54 of file jquery.textillate.js.
{
     $t.addClass('animated ' + effect)
       .css('visibility', 'visible')
       .show();
     $t.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
         $t.removeClass('animated ' + effect);
         cb && cb();
     });
   }
References $t.
Referenced by animateTokens(), and ready().
animateTokens()
function animateTokens ($tokens, options, cb)
Definition at line 65 of file jquery.textillate.js.
{
     var that = this
       , count = $tokens.length;
     if (!count) {
       cb && cb();
       return;
     }
     if (options.shuffle) $tokens = shuffle($tokens);
     if (options.reverse) $tokens = $tokens.toArray().reverse();
     $.each($tokens, function (i, t) {
       var $token = $(t);
       function complete () {
         if (isInEffect(options.effect)) {
           $token.css('visibility', 'visible');
         } else if (isOutEffect(options.effect)) {
           $token.css('visibility', 'hidden');
         }
         count -= 1;
         if (!count && cb) cb();
       }
       var delay = options.sync ? options.delay : options.delay * i * options.delayScale;
       $token.text() ?
         setTimeout(function () { animate($token, options.effect, complete) }, delay) :
         complete();
     });
   };
References animate(), i, isInEffect(), isOutEffect(), options, shuffle(), t, and this.
getData()
function getData (node)
Definition at line 27 of file jquery.textillate.js.
{
     var attrs = node.attributes || []
       , data = {};
     if (!attrs.length) return data;
     $.each(attrs, function (i, attr) {
       var nodeName = attr.nodeName.replace(/delayscale/, 'delayScale');
       if (/^data-in-*/.test(nodeName)) {
         data.in = data.in || {};
         data.in[nodeName.replace(/data-in-/, '')] = stringToBoolean(attr.nodeValue);
       } else if (/^data-out-*/.test(nodeName)) {
         data.out = data.out || {};
         data.out[nodeName.replace(/data-out-/, '')] =stringToBoolean(attr.nodeValue);
       } else if (/^data-*/.test(nodeName)) {
         data[nodeName.replace(/data-/, '')] = stringToBoolean(attr.nodeValue);
       }
     })
     return data;
   }
References i, stringToBoolean(), and test().
isInEffect()
function isInEffect (effect)
Definition at line 12 of file jquery.textillate.js.
{
     return /In/.test(effect) || $.inArray(effect, $.fn.textillate.defaults.inEffects) >= 0;
   };
References fn, and In.
Referenced by animateTokens().
isOutEffect()
function isOutEffect (effect)
Definition at line 16 of file jquery.textillate.js.
{
     return /Out/.test(effect) || $.inArray(effect, $.fn.textillate.defaults.outEffects) >= 0;
   };
References fn.
Referenced by animateTokens().
shuffle()
function shuffle (o)
Definition at line 49 of file jquery.textillate.js.
{
       for (var j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
       return o;
   }
References i, j, o, and x.
Referenced by !function(), animateTokens(), and YAWK\WIDGETS\FACEBOOK\GALLERY\fbGallery::drawGallery().
stringToBoolean()
function stringToBoolean (str)
Definition at line 21 of file jquery.textillate.js.
{
     if (str !== "true" && str !== "false") return str;
     return (str === "true");
   };
Referenced by getData().
Variable Documentation
defaults
fn textillate defaults
Initial value:
= {
    selector: '.texts',
    loop: false,
    minDisplayTime: 2000,
    initialDelay: 0,
    in: {
      effect: 'fadeInLeftBig',
      delayScale: 1.5,
      delay: 50,
      sync: false,
      reverse: false,
      shuffle: false,
      callback: function () {}
    },
    out: {
      effect: 'hinge',
      delayScale: 1.5,
      delay: 50,
      sync: false,
      reverse: false,
      shuffle: false,
      callback: function () {}
    },
    autoStart: true,
    inEffects: [],
    outEffects: [ 'hinge' ],
    callback: function () {},
    type: 'char'
  }
Definition at line 259 of file jquery.textillate.js.
jQuery
jQuery
Definition at line 289 of file jquery.textillate.js.
Textillate
var Textillate
Definition at line 98 of file jquery.textillate.js.