YaWK: /var/www/htdocs/yawk.io/system/engines/codemirror/edit/matchbrackets.js File Reference
matchbrackets.js File Reference
Functions
CodeMirror defineExtension ("matchBrackets", function() {matchBrackets(this, true);})
CodeMirror defineOption ("matchBrackets", false, function(cm, val, old) { if(old &&old !=CodeMirror.Init) { cm.off("cursorActivity", doMatchBrackets);if(currentlyHighlighted) {currentlyHighlighted();currentlyHighlighted=null;} } if(val) { cm.state.matchBrackets=typeof val=="object" ? val :{};cm.on("cursorActivity", doMatchBrackets);} })
function doMatchBrackets (cm)
function findMatchingBracket (cm, where, strict, config)
else if (typeof define=="function" &&define.amd) define(["../../lib/codemirror"]
function matchBrackets (cm, autoclear, config)
else mod (CodeMirror)
function scanForBracket (cm, where, dir, style, config)
Variables
function CodeMirror
var currentlyHighlighted = null
var matching = {"(": ")>", ")": "(<", "[": "]>", "]": "[<", "{": "}>", "}": "{<"}
function mod
var Pos = CodeMirror.Pos
Function Documentation
defineExtension()
CodeMirror defineExtension ("matchBrackets" , function() {matchBrackets(this, true);})
References matchBrackets().
defineOption()
CodeMirror defineOption ("matchBrackets" , false , function(cm, val, old) { if(old &&old !=CodeMirror.Init) { cm.off("cursorActivity", doMatchBrackets);if(currentlyHighlighted) {currentlyHighlighted();currentlyHighlighted=null;} } if(val) { cm.state.matchBrackets=typeof val=="object" ? val :{};cm.on("cursorActivity", doMatchBrackets);} })
References CodeMirror, currentlyHighlighted, and doMatchBrackets().
doMatchBrackets()
function doMatchBrackets (cm)
Definition at line 97 of file matchbrackets.js.
{
         cm.operation(function() {
             if (currentlyHighlighted) {currentlyHighlighted(); currentlyHighlighted = null;}
             currentlyHighlighted = matchBrackets(cm, false, cm.state.matchBrackets);
         });
     }
References currentlyHighlighted, and matchBrackets().
Referenced by defineOption().
findMatchingBracket()
function findMatchingBracket (cm, where, strict, config)
Definition at line 19 of file matchbrackets.js.
{
         var line = cm.getLineHandle(where.line), pos = where.ch - 1;
         var match = (pos >= 0 && matching[line.text.charAt(pos)]) || matching[line.text.charAt(++pos)];
         if (!match) return null;
         var dir = match.charAt(1) == ">" ? 1 : -1;
         if (strict && (dir > 0) != (pos == where.ch)) return null;
         var style = cm.getTokenTypeAt(Pos(where.line, pos + 1));
         var found = scanForBracket(cm, Pos(where.line, pos + (dir > 0 ? 1 : 0)), dir, style || null, config);
         if (found == null) return null;
         return {from: Pos(where.line, pos), to: found && found.pos,
             match: found && found.ch == match.charAt(0), forward: dir > 0};
     }
References config, from, matching, Pos, scanForBracket(), to, and where.
Referenced by matchBrackets().
if()
else if (typeof define = = "function" && define.amd)
matchBrackets()
function matchBrackets (cm, autoclear, config)
Definition at line 67 of file matchbrackets.js.
{
         // Disable brace matching in long lines, since it'll cause hugely slow updates
         var maxHighlightLen = cm.state.matchBrackets.maxHighlightLineLength || 1000;
         var marks = [], ranges = cm.listSelections();
         for (var i = 0; i < ranges.length; i++) {
             var match = ranges[i].empty() && findMatchingBracket(cm, ranges[i].head, false, config);
             if (match && cm.getLine(match.from.line).length <= maxHighlightLen) {
                 var style = match.match ? "CodeMirror-matchingbracket" : "CodeMirror-nonmatchingbracket";
                 marks.push(cm.markText(match.from, Pos(match.from.line, match.from.ch + 1), {className: style}));
                 if (match.to && cm.getLine(match.to.line).length <= maxHighlightLen)
                     marks.push(cm.markText(match.to, Pos(match.to.line, match.to.ch + 1), {className: style}));
             }
         }
         if (marks.length) {
             // Kludge to work around the IE bug from issue #1193, where text
             // input stops going to the textare whever this fires.
             if (ie_lt8 && cm.state.focused) cm.focus();
             var clear = function() {
                 cm.operation(function() {
                     for (var i = 0; i < marks.length; i++) marks[i].clear();
                 });
             };
             if (autoclear) setTimeout(clear, 800);
             else return clear;
         }
     }
References clear, config, findMatchingBracket(), i, and Pos.
Referenced by defineExtension(), and doMatchBrackets().
mod()
else mod (CodeMirror)
scanForBracket()
function scanForBracket (cm, where, dir, style, config)
Definition at line 40 of file matchbrackets.js.
{
         var maxScanLen = (config && config.maxScanLineLength) || 10000;
         var maxScanLines = (config && config.maxScanLines) || 1000;
         var stack = [];
         var re = config && config.bracketRegex ? config.bracketRegex : /[(){}[\]]/;
         var lineEnd = dir > 0 ? Math.min(where.line + maxScanLines, cm.lastLine() + 1)
             : Math.max(cm.firstLine() - 1, where.line - maxScanLines);
         for (var lineNo = where.line; lineNo != lineEnd; lineNo += dir) {
             var line = cm.getLine(lineNo);
             if (!line) continue;
             var pos = dir > 0 ? 0 : line.length - 1, end = dir > 0 ? line.length : -1;
             if (line.length > maxScanLen) continue;
             if (lineNo == where.line) pos = where.ch - (dir < 0 ? 1 : 0);
             for (; pos != end; pos += dir) {
                 var ch = line.charAt(pos);
                 if (re.test(ch) && (style === undefined || cm.getTokenTypeAt(Pos(lineNo, pos + 1)) == style)) {
                     var match = matching[ch];
                     if ((match.charAt(1) == ">") == (dir > 0)) stack.push(ch);
                     else if (!stack.length) return {pos: Pos(lineNo, pos), ch: ch};
                     else stack.pop();
                 }
             }
         }
         return lineNo - dir == (dir > 0 ? cm.lastLine() : cm.firstLine()) ? false : null;
     }
References config, matching, Pos, re, undefined, and where.
Referenced by findMatchingBracket().
Variable Documentation
CodeMirror
function CodeMirror
Initial value:
{
    var ie_lt8 = /MSIE \d/.test(navigator.userAgent) &&
        (document.documentMode == null || document.documentMode < 8)
Definition at line 11 of file matchbrackets.js.
Referenced by defineOption().
currentlyHighlighted
var currentlyHighlighted = null
Definition at line 96 of file matchbrackets.js.
Referenced by defineOption(), and doMatchBrackets().
matching
var matching = {"(": ")>", ")": "(<", "[": "]>", "]": "[<", "{": "}>", "}": "{<"}
Definition at line 17 of file matchbrackets.js.
Referenced by findMatchingBracket(), and scanForBracket().
mod
else mod
Initial value:
{
    if (typeof exports == "object" && typeof module == "object")
        mod(require("../../lib/codemirror"))
Definition at line 4 of file matchbrackets.js.
Pos
var Pos = CodeMirror.Pos
Definition at line 15 of file matchbrackets.js.
Referenced by findMatchingBracket(), leftButtonSelect(), matchBrackets(), and scanForBracket().