YaWK: /var/www/htdocs/yawk.io/admin/includes/menus.php File Reference
menus.php File Reference
Variables
$globalMenuID = settings::getSetting($db, "globalmenuid")
print $lang ['MENU+']
$rows = backend::getMenusArray($db)
if(!isset($menu)) if(isset($_GET['toggle']) &&($_GET['toggle']==="1")) if(isset($_GET['add']) &&($_GET['add']==="1")) if (isset($_GET[ 'del']) &&($_GET[ 'del']==="1"))
Variable Documentation
$globalMenuID
$globalMenuID = settings::getSetting($db, "globalmenuid")
Definition at line 124 of file menus.php.
$lang
print $lang[ 'MENU+']
Definition at line 108 of file menus.php.
$rows
$rows = backend::getMenusArray($db)
Definition at line 126 of file menus.php.
Referenced by YAWK\backend\getMenuNamesArray(), YAWK\backend\getMenusArray(), and YAWK\db\select().
if
if (!isset($menu)) if (isset($_GET[ 'toggle']) &&($_GET[ 'toggle']==="1")) if (isset($_GET[ 'add']) &&($_GET[ 'add']==="1")) if(isset($_GET['del']) &&($_GET['del']==="1")) (isset($_GET[ 'del']) &&($_GET[ 'del']==="1"))
Definition at line 62 of file menus.php.