YaWK: /var/www/htdocs/yawk.io/admin/includes/menu-edit.php File Reference
menu-edit.php File Reference
Variables
print $lang ['BACK']
$menuLanguage = sys::getMenuLanguage($db, $_GET['menu'])
if(!isset($page)) if(!isset($db)) if(!isset($lang)) if(isset($_GET['toggleItem'])) if(isset($_GET['del']) &&($_GET['del']==="1")) if(isset($_POST['changetitle'])) if(isset($_POST['changeLanguage'])) if(isset($_POST['add'])) else if(isset($_POST['save'])) else $menuName = YAWK\sys::getMenuName($db, $_GET['menu'])
if (isset($menuLanguage) &&(!empty($menuLanguage)))
Variable Documentation
$lang
print $lang[ 'BACK']
Definition at line 240 of file menu-edit.php.
$menuLanguage
$menuLanguage = sys::getMenuLanguage($db, $_GET['menu'])
Definition at line 309 of file menu-edit.php.
Referenced by YAWK\menu\changeLanguage().
$menuName
if (!isset($page)) if (!isset($db)) if (!isset($lang)) if (isset($_GET[ 'toggleItem'])) if (isset($_GET[ 'del']) &&($_GET[ 'del']==="1")) if (isset($_POST[ 'changetitle'])) if (isset($_POST[ 'changeLanguage'])) if (isset($_POST[ 'add'])) else if (isset($_POST[ 'save'])) else $menuName = YAWK\sys::getMenuName($db, $_GET['menu'])
Definition at line 217 of file menu-edit.php.
Referenced by YAWK\menu\addEntry(), YAWK\menu\delete(), YAWK\menu\deleteEntry(), YAWK\menu\display(), YAWK\menu\editEntry(), and YAWK\menu\toggleOffline().
if
if(isset($menuLanguage) &&(!empty($menuLanguage))) (isset($menuLanguage) &&(!empty($menuLanguage)))
Definition at line 312 of file menu-edit.php.