YaWK: /var/www/htdocs/yawk.io/system/engines/codemirror/util/misc.js File Reference
misc.js File Reference
Functions
function export bind (f)
function export copyObj (obj, target, overwrite)
function export countColumn (string, end, tabSize, startIndex, startValue)
function export Delayed ()
Variables
Delayed prototype sel_mouse = {origin: "*mouse"}
Delayed prototype set
Function Documentation
bind()
function export bind (f)
Definition at line 1 of file misc.js.
{
   let args = Array.prototype.slice.call(arguments, 1)
   return function(){return f.apply(null, args)}
 }
References f.
Referenced by !function(), install(), and leftButtonDown().
copyObj()
function export copyObj (obj, target, overwrite)
Definition at line 6 of file misc.js.
{
   if (!target) target = {}
   for (let prop in obj)
     if (obj.hasOwnProperty(prop) && (overwrite !== false || !target.hasOwnProperty(prop)))
       target[prop] = obj[prop]
   return target
 }
countColumn()
function export countColumn (string, end, tabSize, startIndex, startValue)
Definition at line 16 of file misc.js.
{
   if (end == null) {
     end = string.search(/[^\s\u00a0]/)
     if (end == -1) end = string.length
   }
   for (let i = startIndex || 0, n = startValue || 0;;) {
     let nextTab = string.indexOf("\t", i)
     if (nextTab < 0 || nextTab >= end)
       return n + (end - i)
     n += nextTab - i
     n += tabSize - (n % tabSize)
     i = nextTab + 1
   }
 }
References i, n, and s.
Referenced by leftButtonSelect().
Delayed()
function export Delayed ()
Definition at line 31 of file misc.js.
 {this.id = null}
Variable Documentation
sel_mouse
Delayed prototype sel_mouse = {origin: "*mouse"}
Definition at line 51 of file misc.js.
Referenced by leftButtonSelect().
set
Delayed prototype set
Initial value:
= function(ms, f) {
  clearTimeout(this.id)
  this.id = setTimeout(f, ms)
}
export function indexOf(array, elt) {
  for (let i = 0; i < array.length; ++i)
    if (array[i] == elt) return i
  return -1
}
export let scrollerGap = 30
export let Pass = {toString: function(){return "CodeMirror.Pass"}}
export let sel_dontScroll = {scroll: false}
Definition at line 32 of file misc.js.