var namespaceYAWK_1_1WIDGETS_1_1JPLAYER =
[
    [ "AUDIO", "namespaceYAWK_1_1WIDGETS_1_1JPLAYER_1_1AUDIO.html", "namespaceYAWK_1_1WIDGETS_1_1JPLAYER_1_1AUDIO" ],
    [ "VIDEO", "namespaceYAWK_1_1WIDGETS_1_1JPLAYER_1_1VIDEO.html", "namespaceYAWK_1_1WIDGETS_1_1JPLAYER_1_1VIDEO" ]
];