var namespaceYAWK_1_1WIDGETS_1_1GOOGLE =
[
    [ "ANALYTICS", "namespaceYAWK_1_1WIDGETS_1_1GOOGLE_1_1ANALYTICS.html", "namespaceYAWK_1_1WIDGETS_1_1GOOGLE_1_1ANALYTICS" ],
    [ "MAPS", "namespaceYAWK_1_1WIDGETS_1_1GOOGLE_1_1MAPS.html", "namespaceYAWK_1_1WIDGETS_1_1GOOGLE_1_1MAPS" ]
];