var namespaceYAWK =
[
    [ "BACKEND", "namespaceYAWK_1_1BACKEND.html", "namespaceYAWK_1_1BACKEND" ],
    [ "BACKUP", "namespaceYAWK_1_1BACKUP.html", "namespaceYAWK_1_1BACKUP" ],
    [ "FRAMEWORK", "namespaceYAWK_1_1FRAMEWORK.html", "namespaceYAWK_1_1FRAMEWORK" ],
    [ "PLUGINS", "namespaceYAWK_1_1PLUGINS.html", "namespaceYAWK_1_1PLUGINS" ],
    [ "WIDGETS", "namespaceYAWK_1_1WIDGETS.html", "namespaceYAWK_1_1WIDGETS" ],
    [ "alert", "classYAWK_1_1alert.html", "classYAWK_1_1alert" ],
    [ "backend", "classYAWK_1_1backend.html", "classYAWK_1_1backend" ],
    [ "controller", "classYAWK_1_1controller.html", "classYAWK_1_1controller" ],
    [ "db", "classYAWK_1_1db.html", "classYAWK_1_1db" ],
    [ "editor", "classYAWK_1_1editor.html", "classYAWK_1_1editor" ],
    [ "email", "classYAWK_1_1email.html", "classYAWK_1_1email" ],
    [ "filemanager", "classYAWK_1_1filemanager.html", "classYAWK_1_1filemanager" ],
    [ "installer", "classYAWK_1_1installer.html", "classYAWK_1_1installer" ],
    [ "language", "classYAWK_1_1language.html", "classYAWK_1_1language" ],
    [ "licenses", "classYAWK_1_1licenses.html", "classYAWK_1_1licenses" ],
    [ "menu", "classYAWK_1_1menu.html", "classYAWK_1_1menu" ],
    [ "page", "classYAWK_1_1page.html", "classYAWK_1_1page" ],
    [ "plugin", "classYAWK_1_1plugin.html", "classYAWK_1_1plugin" ],
    [ "search", "classYAWK_1_1search.html", "classYAWK_1_1search" ],
    [ "settings", "classYAWK_1_1settings.html", "classYAWK_1_1settings" ],
    [ "SimpleImage", "classYAWK_1_1SimpleImage.html", "classYAWK_1_1SimpleImage" ],
    [ "stats", "classYAWK_1_1stats.html", "classYAWK_1_1stats" ],
    [ "sys", "classYAWK_1_1sys.html", "classYAWK_1_1sys" ],
    [ "template", "classYAWK_1_1template.html", "classYAWK_1_1template" ],
    [ "tipOfDay", "classYAWK_1_1tipOfDay.html", "classYAWK_1_1tipOfDay" ],
    [ "update", "classYAWK_1_1update.html", "classYAWK_1_1update" ],
    [ "user", "classYAWK_1_1user.html", "classYAWK_1_1user" ],
    [ "webmail", "classYAWK_1_1webmail.html", "classYAWK_1_1webmail" ],
    [ "widget", "classYAWK_1_1widget.html", "classYAWK_1_1widget" ],
    [ "true", "namespaceYAWK.html#a7859620f04fd7e1e5000fc12b154cd8e", null ]
];