YaWK: /var/www/htdocs/yawk.io/admin/includes/page-edit.php File Reference
page-edit.php File Reference
Variables
print $_GET ['id']
if(!isset($page)) if(!isset($db)) if(!isset($lang)) if(isset($_GET['id'])) if(isset($_POST['save'])) $dirprefix = YAWK\sys::getDirPrefix($db)
if($page->alias==="index") $editorSettings = settings::getEditorSettings($db, 14)
$host = YAWK\sys::getHost($db)
print $lang ['END_PUBLISH']
print $lang ['LANGUAGE']
foreach(YAWK\sys::getGroups($db, "pages") as $role) print $lang ['PAGE_STATUS']
print $lang ['PAGE_VISIBLE']
print $lang ['SAVE_CHANGES']
print $lang ['START_PUBLISH']
print $lang ['TITLE']
$publishedHtml = "<option value=\"1\" >online</option>"
$replacedChars = array("ae", "ue", "oe", "ae", "ue", "oe", "ss")
$specialChars = array("/ä/", "/ü/", "/ö/", "/Ä/", "/Ü/", "/Ö/", "/ß/")
$page alias = mb_strtolower($page->alias)
print $page bgimage
print $page date_publish
print $page date_unpublish
if($page->published==='1') else
if ($editorSettings[ 'editorAutoCodeview']==="true")
print $page meta_keywords
print $page meta_local
print $page title
Variable Documentation
$_GET
print $_GET[ 'id']
Definition at line 288 of file page-edit.php.
Referenced by YAWK\template\checkWrapper(), YAWK\template\downloadTemplate(), YAWK\webmail\drawFolders(), YAWK\BACKEND\AdminLTE\drawHtmlContent(), YAWK\BACKEND\AdminLTE\drawHtmlLeftSidebar(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarBackupIcon(), YAWK\BACKEND\AdminLTE\drawHtmlNavbarPreviewIcon(), YAWK\backend\drawLoginForm(), YAWK\webmail\drawMailboxControls(), YAWK\PLUGINS\MESSAGES\messages\drawMenu(), YAWK\PLUGINS\MESSAGES\messages\drawNewMessage(), YAWK\filemanager\drawTableHeader(), YAWK\controller\filterfilename(), YAWK\page\getContent(), YAWK\language\getCurrentLanguageStatic(), YAWK\filemanager\getFilesFromFolder(), YAWK\widget\getWidgetSettingsArray(), YAWK\language\inject(), YAWK\user\isAnybodyThere(), YAWK\stats\prepareData(), YAWK\template\setPosition(), and YAWK\BACKUP\backup\zipFolder().
$dirprefix
if (!isset($page)) if (!isset($db)) if (!isset($lang)) if (isset($_GET[ 'id'])) if (isset($_POST[ 'save'])) $dirprefix = YAWK\sys::getDirPrefix($db)
Definition at line 63 of file page-edit.php.
Referenced by YAWK\page\deleteContent(), and YAWK\sys\getDirPrefix().
$editorSettings
if ($page->alias==="index") $editorSettings = settings::getEditorSettings($db, 14)
Definition at line 87 of file page-edit.php.
Referenced by YAWK\editor\getEditor().
$host
$host = YAWK\sys::getHost($db)
Definition at line 65 of file page-edit.php.
Referenced by YAWK\PLUGINS\MESSAGES\messages\__construct(), YAWK\BACKEND\AdminLTE\drawHtmlFooter(), YAWK\BACKEND\AdminLTE\drawHtmlLogo(), YAWK\template\includeHeader(), YAWK\template\loadActiveAssets(), YAWK\installer\writeHtaccessFileToAdminFolder(), and YAWK\installer\writeHtaccessFileToRootFolder().
$lang [1/7]
print $lang[ 'END_PUBLISH']
Definition at line 355 of file page-edit.php.
$lang [2/7]
print $lang[ 'LANGUAGE']
Definition at line 318 of file page-edit.php.
$lang [3/7]
foreach (YAWK\sys::getGroups($db, "pages") as $role) print $lang[ 'PAGE_STATUS']
Definition at line 382 of file page-edit.php.
$lang [4/7]
print $lang[ 'PAGE_VISIBLE']
Definition at line 360 of file page-edit.php.
$lang [5/7]
print $lang[ 'SAVE_CHANGES']
Definition at line 283 of file page-edit.php.
$lang [6/7]
print $lang[ 'START_PUBLISH']
Definition at line 349 of file page-edit.php.
$lang [7/7]
print $lang[ 'TITLE']
Definition at line 307 of file page-edit.php.
$publishedHtml
$publishedHtml = "<option value=\"1\" >online</option>"
Definition at line 393 of file page-edit.php.
$replacedChars
$replacedChars = array("ae", "ue", "oe", "ae", "ue", "oe", "ss")
Definition at line 72 of file page-edit.php.
$specialChars
$specialChars = array("/ä/", "/ü/", "/ö/", "/Ä/", "/Ü/", "/Ö/", "/ß/")
Definition at line 71 of file page-edit.php.
Referenced by YAWK\page\writeContent().
alias
print $page alias = mb_strtolower($page->alias)
Definition at line 68 of file page-edit.php.
Referenced by YAWK\page\copy(), YAWK\page\create(), YAWK\page\delete(), YAWK\page\deleteContent(), YAWK\page\loadProperties(), YAWK\page\loadPropertiesByID(), YAWK\page\readContent(), YAWK\page\save(), and YAWK\page\writeContent().
bgimage
print $page bgimage
Definition at line 441 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), and YAWK\page\loadPropertiesByID().
date_publish
print $page date_publish
Definition at line 352 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), and YAWK\page\loadPropertiesByID().
date_unpublish
print $page date_unpublish
Definition at line 358 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), YAWK\page\loadPropertiesByID(), and YAWK\page\save().
else
if ($page->published==='1') else
Initial value:
{
                        $publishedHtml = "<option value=\"0\" selected=\"selected\">$lang[OFFLINE]</option>"
Definition at line 390 of file page-edit.php.
if
if(isset($page->language) &&(!empty($page->language))) ($editorSettings[ 'editorAutoCodeview'] = == "true")
Definition at line 169 of file page-edit.php.
meta_keywords
print $page meta_keywords
Definition at line 423 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), and YAWK\page\loadPropertiesByID().
meta_local
print $page meta_local
Definition at line 418 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), and YAWK\page\loadPropertiesByID().
title
print $page title
Definition at line 310 of file page-edit.php.
Referenced by YAWK\page\loadProperties(), YAWK\page\loadPropertiesByID(), and ready().