YaWK: /var/www/htdocs/yawk.io/admin/includes/settings-fonts.php File Reference
settings-fonts.php File Reference
Variables
$cssGoogleFont = ''
$cssOTF = ''
$cssTTF = ''
$cssWOFF = ''
$fontArray = template::getFontsFromFolder($fontFolder)
$fontFolder = "../system/fonts/"
if(isset($_GET) &&(!empty($_GET))) $googleFonts = template::getGoogleFontsArray($db)
if (isset($fontArray[ 'otf']) &&(!empty($fontArray[ 'otf'])))
if (isset($fontArray[ 'ttf']) &&(!empty($fontArray[ 'ttf'])))
if (isset($fontArray[ 'woff']) &&(!empty($fontArray[ 'woff'])))
if(isset($fontArray['ttf']) &&(!empty($fontArray['ttf']))) if(isset($fontArray['otf']) &&(!empty($fontArray['otf']))) if(isset($fontArray['woff']) &&(!empty($fontArray['woff']))) if (isset($googleFonts) &&(!empty($googleFonts)))
Variable Documentation
$cssGoogleFont
$cssGoogleFont = ''
Definition at line 129 of file settings-fonts.php.
$cssOTF
$cssOTF = ''
Definition at line 127 of file settings-fonts.php.
$cssTTF
$cssTTF = ''
Definition at line 126 of file settings-fonts.php.
$cssWOFF
$cssWOFF = ''
Definition at line 128 of file settings-fonts.php.
$fontArray
$fontArray = template::getFontsFromFolder($fontFolder)
Definition at line 124 of file settings-fonts.php.
Referenced by YAWK\backend\drawFontList(), and YAWK\template\getFontsFromFolder().
$fontFolder
$fontFolder = "../system/fonts/"
Definition at line 12 of file settings-fonts.php.
$googleFonts
if (isset($_GET) &&(!empty($_GET))) $googleFonts = template::getGoogleFontsArray($db)
Definition at line 122 of file settings-fonts.php.
Referenced by YAWK\template\drawFontFamilySelectField(), and YAWK\template\getGoogleFontsArray().
if [1/4]
if(isset($fontArray['otf']) &&(!empty($fontArray['otf']))) (isset($fontArray[ 'otf']) &&(!empty($fontArray[ 'otf'])))
Definition at line 262 of file settings-fonts.php.
if [2/4]
if(isset($fontArray['ttf']) &&(!empty($fontArray['ttf']))) (isset($fontArray[ 'ttf']) &&(!empty($fontArray[ 'ttf'])))
Definition at line 245 of file settings-fonts.php.
if [3/4]
if(isset($fontArray['woff']) &&(!empty($fontArray['woff']))) (isset($fontArray[ 'woff']) &&(!empty($fontArray[ 'woff'])))
Definition at line 279 of file settings-fonts.php.
if [4/4]
if(isset($googleFonts) &&(!empty($googleFonts))) (isset($googleFonts) &&(!empty($googleFonts)))
Definition at line 170 of file settings-fonts.php.