YaWK: /var/www/htdocs/yawk.io/admin/includes/settings-assets.php File Reference
settings-assets.php File Reference
Variables
$res = $db->query("SELECT * FROM {assets_types} ORDER BY asset")
if(isset($_GET['delete']) &&($_GET['delete']==1)) if(isset($_GET['toggle']) && $_GET['toggle']==1) if (isset($_POST) &&(!empty($_POST)))
while ($row=mysqli_fetch_assoc($res))
Variable Documentation
$res
$res = $db->query("SELECT * FROM {assets_types} ORDER BY asset")
Definition at line 149 of file settings-assets.php.
Referenced by YAWK\menu\addEntry(), YAWK\menu\changeLanguage(), YAWK\menu\changeTitle(), YAWK\sys\checkIfAssetsAreLoaded(), YAWK\user\checkResetToken(), YAWK\page\copy(), YAWK\stats\countBrowsers(), YAWK\stats\countDaytime(), YAWK\stats\countDeviceTypes(), YAWK\stats\countLogins(), YAWK\stats\countMessages(), YAWK\stats\countOS(), YAWK\stats\countOSVersions(), YAWK\stats\countWeekdays(), YAWK\page\create(), YAWK\menu\createMenu(), YAWK\menu\delete(), YAWK\menu\deleteEntry(), YAWK\menu\display(), YAWK\menu\displayEditable(), YAWK\menu\displayGlobalMenu(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\displaySubMenu(), YAWK\template\drawAssetsTitles(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\drawImageGallery(), YAWK\stats\drawPagesBox(), YAWK\menu\editEntry(), YAWK\template\getActivegfont(), YAWK\settings\getAllSettingsArray(), YAWK\settings\getAllSettingsIntoArray(), YAWK\template\getAllSettingsIntoArray(), YAWK\widget\getAllSettingsIntoArray(), YAWK\widget\getAllWidgetTypes(), YAWK\template\getAssetsByType(), YAWK\page\getCurrentLanguageByID(), YAWK\settings\getEditorSettings(), YAWK\sys\getGroupFromId(), YAWK\sys\getGroupId(), YAWK\sys\getGroups(), YAWK\plugin\getIdByName(), YAWK\page\getLatest(), YAWK\user\getLoginData(), YAWK\settings\getLongSetting(), YAWK\template\getMaxId(), YAWK\menu\getMenuEntryStatus(), YAWK\menu\getMenuIdFromLanguage(), YAWK\sys\getMenuItem(), YAWK\menu\getMenuItemTitleByID(), YAWK\sys\getMenuLanguage(), YAWK\sys\getMenuName(), YAWK\menu\getMenuNameByID(), YAWK\backend\getMenuNamesArray(), YAWK\backend\getMenusArray(), YAWK\menu\getMenuStatus(), YAWK\page\getMetaTags(), YAWK\page\getMetaTagsArray(), YAWK\plugin\getNameById(), YAWK\stats\getOnlineUsers(), YAWK\backend\getPagesArray(), YAWK\page\getProperty(), YAWK\sys\getProperty(), YAWK\settings\getSettingDescription(), YAWK\settings\getSettingsByType(), YAWK\stats\getStatsArray(), YAWK\sys\getSubMenu(), YAWK\template\getTemplateIds(), YAWK\template\getTemplateSettingsArray(), YAWK\user\getUserEmail(), YAWK\user\getUserList(), YAWK\stats\getUserStats(), YAWK\user\getUserTemplateID(), YAWK\settings\getValueSettingsArray(), YAWK\settings\getWidgetSetting(), YAWK\widget\getWidgetSettingsArray(), YAWK\user\isAllowedToOverrideTemplate(), YAWK\menu\isPublished(), YAWK\template\loadActiveAssets(), YAWK\template\loadAllSettingsIntoArray(), YAWK\page\loadProperties(), YAWK\template\loadProperties(), YAWK\page\loadPropertiesByID(), YAWK\template\loadPropertiesIntoArray(), YAWK\template\loadSettingsTypesIntoArray(), YAWK\BACKUP\backup\restore(), YAWK\template\saveAs(), YAWK\search\searchBlogs(), YAWK\search\searchMenus(), YAWK\search\searchPages(), YAWK\search\searchUsers(), YAWK\search\searchWidgets(), YAWK\user\sendResetEmail(), YAWK\settings\setLongSetting(), YAWK\user\setNewPassword(), YAWK\stats\setOnlineUsers(), YAWK\settings\setSetting(), YAWK\settings\setTemplateSetting(), YAWK\user\setUserTemplate(), YAWK\settings\setWidgetSetting(), YAWK\menu\toggleItemOffline(), YAWK\menu\toggleOffline(), YAWK\settings\toggleOffline(), YAWK\template\uploadTemplate(), and YAWK\sys\writeIniFile().
if
if (isset($_GET[ 'delete']) &&($_GET[ 'delete']==1)) if (isset($_GET[ 'toggle']) &&$_GET[ 'toggle']==1) if(isset($_POST) &&(!empty($_POST))) (isset($_POST) &&(!empty($_POST)))
Definition at line 51 of file settings-assets.php.
while
while ($row = mysqli_fetch_assoc($res))
Definition at line 150 of file settings-assets.php.