YaWK: /var/www/htdocs/yawk.io/admin/includes/settings-backend.php File Reference
settings-backend.php File Reference
Variables
if(isset($_POST['save'])) $settings = settings::getAllSettingsIntoArray($db)
Variable Documentation
$settings
if (isset($_POST[ 'save'])) $settings = settings::getAllSettingsIntoArray($db)
Definition at line 46 of file settings-backend.php.
Referenced by YAWK\WIDGETS\BLOG\WIDGET\blogWidget\__construct(), YAWK\WIDGETS\BUBBLUS\MINDMAP\bubblus\__construct(), YAWK\WIDGETS\CHATURBATE\STREAM\chaturbate\__construct(), YAWK\WIDGETS\CLOCK\CURRENT\clock\__construct(), YAWK\WIDGETS\CONTENTANIMATOR\ANIMATE\contentAnimator\__construct(), YAWK\WIDGETS\CULTURALBROADCASTING\STREAM\culturalBroadcastingArchive\__construct(), YAWK\WIDGETS\CUSTOM_HTML\CODE\customHtml\__construct(), YAWK\WIDGETS\EMBED_PAGE\PAGE\embedPage\__construct(), YAWK\WIDGETS\EXAMPLE\DEMO\example\__construct(), YAWK\WIDGETS\FACEBOOK\EVENTS\fbEvents\__construct(), YAWK\WIDGETS\FACEBOOK\EXAMPLE\fbExample\__construct(), YAWK\WIDGETS\FACEBOOK\FEED\fbFeed\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEBUTTON\fbLikeButton\__construct(), YAWK\WIDGETS\FACEBOOK\LIKEPAGE\fbLikePage\__construct(), YAWK\WIDGETS\FACEBOOK\POSTING\fbPosting\__construct(), YAWK\WIDGETS\FACEBOOK\VIDEO\fbVideo\__construct(), YAWK\WIDGETS\FUCKADBLOCK\BLOCK\fuckadblock\__construct(), YAWK\WIDGETS\GALLERY\IMAGES\gallery\__construct(), YAWK\WIDGETS\GOOGLE\ANALYTICS\googleAnalytics\__construct(), YAWK\WIDGETS\GOOGLE\MAPS\googleMaps\__construct(), YAWK\WIDGETS\INSTAGRAM\POSTING\instagram\__construct(), YAWK\WIDGETS\LOGINBOX\LOGIN\loginbox\__construct(), YAWK\WIDGETS\NEWSLETTER\SUBSCRIBE\newsletter\__construct(), YAWK\WIDGETS\PINTEREST\FOLLOW\pinterestFollow\__construct(), YAWK\WIDGETS\PINTEREST\PIN\pinterestPin\__construct(), YAWK\WIDGETS\PINTEREST\PROFILE\pinterestProfile\__construct(), YAWK\WIDGETS\PLYR\PLAYER\plyr\__construct(), YAWK\WIDGETS\PREZI\EMBED\prezi\__construct(), YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\__construct(), YAWK\WIDGETS\SOUNDCLOUD\PLAYER\soundcloud\__construct(), YAWK\WIDGETS\SPOTIFY\EMBED\spotify\__construct(), YAWK\WIDGETS\SUBMENU\EMBED\submenu\__construct(), YAWK\WIDGETS\TWITCH\EMBED\twitch\__construct(), YAWK\WIDGETS\TWITTER\GRID\twitterGrid\__construct(), YAWK\WIDGETS\TWITTER\TIMELINE\twitterTimeline\__construct(), YAWK\WIDGETS\TWITTER\TWEET\twitterTweet\__construct(), YAWK\WIDGETS\TWITTER\BUTTON\twitterTweetButton\__construct(), YAWK\WIDGETS\YOUTUBE\VIDEO\youtube\__construct(), YAWK\WIDGETS\BOOKING\FORM\bookingWidget\__construct(), and YAWK\template\getFormElements().