YaWK: /var/www/htdocs/yawk.io/admin/includes/template-positions.php File Reference
template-positions.php File Reference
Variables
$disabledBorder = "border: 1px dashed #ccc;"
$enabledBorder = "border: 1px solid #4CAE4C;"
if(!isset($db)) if(!isset($template)) if(!isset($user)) $getID = settings::getSetting($db, "selectedTemplate")
if(isset($_GET['positionIndicatorStatus'])) $templateSettings = template::getAllSettingsIntoArray($db, $user)
if(isset($templateSettings['pos-outerTop-enabled']['value']) &&($templateSettings['pos-outerTop-enabled']['value'])==="1") else { $outerTopEnabled = $disabledBorder
Variable Documentation
$disabledBorder
$disabledBorder = "border: 1px dashed #ccc;"
Definition at line 325 of file template-positions.php.
$enabledBorder
$enabledBorder = "border: 1px solid #4CAE4C;"
Definition at line 324 of file template-positions.php.
$getID
if (!isset($db)) if (!isset($template)) if (!isset($user)) $getID = settings::getSetting($db, "selectedTemplate")
Definition at line 22 of file template-positions.php.
$templateSettings
if (isset($_GET[ 'positionIndicatorStatus'])) $templateSettings = template::getAllSettingsIntoArray($db, $user)
Definition at line 37 of file template-positions.php.
Referenced by YAWK\template\downloadTemplate(), YAWK\template\getFontRow(), YAWK\template\loadAllSettingsIntoArray(), and YAWK\template\uploadTemplate().
else
if (isset($templateSettings[ 'pos-outerBottom-enabled'][ 'value']) &&($templateSettings[ 'pos-outerBottom-enabled'][ 'value'])==="1") else { $outerTopEnabled = $disabledBorder
Definition at line 330 of file template-positions.php.