YaWK: /var/www/htdocs/yawk.io/admin/includes/template-assets.php File Reference
template-assets.php File Reference
Variables
if(isset($_GET['id']) &&(is_numeric($_GET['id'])||(isset($_POST['id']) &&(is_numeric($_POST['id']))))) else
if(!isset($template)) if(!isset($user)) $template id = settings::getSetting($db, "selectedTemplate")
if (isset($_GET[ 'action']) &&($_GET[ 'action']==="setup"))
$template name = template::getTemplateNameById($db, $template->id)
Variable Documentation
else
if (isset($_GET[ 'id']) &&(is_numeric($_GET[ 'id'])||(isset($_POST[ 'id']) &&(is_numeric($_POST[ 'id']))))) else
Initial value:
{
    $previewButton = ""
Definition at line 89 of file template-assets.php.
id
if (!isset($template)) if (!isset($user)) $template id = settings::getSetting($db, "selectedTemplate")
Definition at line 25 of file template-assets.php.
Referenced by ready().
if
if(isset($_GET['action']) &&($_GET['action']==="setup")) (isset($_GET[ 'action']) &&($_GET[ 'action']==="setup"))
Definition at line 96 of file template-assets.php.
name
$template name = template::getTemplateNameById($db, $template->id)
Definition at line 26 of file template-assets.php.
Referenced by YAWK\template\downloadTemplate(), YAWK\template\loadProperties(), ready(), and YAWK\template\saveAs().