YaWK: /var/www/htdocs/yawk.io/admin/includes/user-new.php File Reference
user-new.php File Reference
Variables
$city = $db->quote($_POST['city'])
$country = $db->quote($_POST['country'])
$email = $db->quote($_POST['email'])
$facebook = $db->quote($_POST['facebook'])
$firstname = $db->quote($_POST['firstname'])
$gid = $db->quote($_POST['gid'])
$lastname = $db->quote($_POST['lastname'])
$password1 = $db->quote($_POST['password1'])
$password2 = $db->quote($_POST['password2'])
$street = $db->quote($_POST['street'])
$twitter = $db->quote($_POST['twitter'])
$url = $db->quote($_POST['url'])
$zipcode = $db->quote($_POST['zipcode'])
if(!isset($_POST['username'])) else
Variable Documentation
$city
$city = $db->quote($_POST['city'])
Definition at line 99 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
$country
$country = $db->quote($_POST['country'])
Definition at line 100 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
$email
$email = $db->quote($_POST['email'])
Definition at line 94 of file user-new.php.
Referenced by YAWK\webmail\drawHeaders(), YAWK\PLUGINS\MESSAGES\messages\drawInbox(), and SSilence\ImapClient\ImapClient\toAddress().
$facebook
$facebook = $db->quote($_POST['facebook'])
Definition at line 103 of file user-new.php.
$firstname
$firstname = $db->quote($_POST['firstname'])
Definition at line 95 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
$gid
$gid = $db->quote($_POST['gid'])
Definition at line 104 of file user-new.php.
Referenced by YAWK\menu\editEntry().
$lastname
$lastname = $db->quote($_POST['lastname'])
Definition at line 96 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
$password1
$password1 = $db->quote($_POST['password1'])
Definition at line 92 of file user-new.php.
$password2
$password2 = $db->quote($_POST['password2'])
Definition at line 93 of file user-new.php.
$street
$street = $db->quote($_POST['street'])
Definition at line 97 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
$twitter
$twitter = $db->quote($_POST['twitter'])
Definition at line 102 of file user-new.php.
$url
$url = $db->quote($_POST['url'])
Definition at line 101 of file user-new.php.
Referenced by YAWK\sys\addTrailingSlash(), YAWK\WIDGETS\FACEBOOK\EVENTS\fbEvents\display(), YAWK\alert\draw(), YAWK\WIDGETS\SOCIALBAR\DISPLAY\socialBar\filterUrl(), YAWK\filemanager\getCurrentMimeTypes(), YAWK\update\isServerReachable(), YAWK\template\loadActiveAssets(), PHPMailer\msgHTML(), YAWK\update\readUpdateFilebaseFromServer(), and YAWK\update\readUpdateIniFromServer().
$zipcode
$zipcode = $db->quote($_POST['zipcode'])
Definition at line 98 of file user-new.php.
Referenced by YAWK\PLUGINS\SIGNUP\buildForm\getAdditionalFields().
else
if (user::create($db, $username, $password1, $password2, $email, $url, $twitter, $facebook, $firstname, $lastname, $street, $zipcode, $city, $country, $blocked, $privacy, $job, $gid)) else
Initial value:
{
      $username = $db->quote($_POST['username'])
Definition at line 90 of file user-new.php.