YaWK: /var/www/htdocs/yawk.io/admin/includes/user-edit.php File Reference
user-edit.php File Reference
Variables
if($user->blocked==='1') else $code1 =""
if($user->privacy==='1') else $code2 =""
$date = \YAWK\sys::splitDateShort($user->date_created)
$friends = user::isFriendRequested($db, $_SESSION['uid'], $user->id)
$i_followers = user::countMyFollowers($db, $user->id)
$i_friends = user::countMyFriends($db, $user->id)
$isFriend = user::isFriend($db, $_SESSION['uid'], $user->id)
if(!isset($user)) else
< div class="box box-default">< div class="box-body">< label > foreach (YAWK\sys::getGroups($db, "users") as $role)
if ($_SESSION[ 'uid'] !=($user->id))
Variable Documentation
$code1
if ($user->blocked==='1') else $code1 =""
Definition at line 433 of file user-edit.php.
$code2
if ($user->privacy==='1') else $code2 =""
Definition at line 434 of file user-edit.php.
$date
$date = \YAWK\sys::splitDateShort($user->date_created)
Definition at line 285 of file user-edit.php.
Referenced by YAWK\stats\countDaytime(), YAWK\stats\countWeekdays(), YAWK\sys\getWeekday(), YAWK\sys\splitDate(), YAWK\sys\splitDateShort(), and YAWK\sys\time_ago().
$friends
$friends = user::isFriendRequested($db, $_SESSION['uid'], $user->id)
Definition at line 331 of file user-edit.php.
$i_followers
$i_followers = user::countMyFollowers($db, $user->id)
Definition at line 292 of file user-edit.php.
$i_friends
$i_friends = user::countMyFriends($db, $user->id)
Definition at line 311 of file user-edit.php.
$isFriend
$isFriend = user::isFriend($db, $_SESSION['uid'], $user->id)
Definition at line 330 of file user-edit.php.
else
if ($user->username==="admin" OR $user->username==="root") else
Definition at line 20 of file user-edit.php.
foreach
<div class="box box-default"><div class="box-body"><label> foreach(YAWK\sys::getGroups($db, "users") as $role) (YAWK\sys::getGroups($db, "users") as $role)
Definition at line 423 of file user-edit.php.
if
if($_SESSION['uid'] !=($user->id)) ($_SESSION ![ 'uid'] = ($user->id))
Definition at line 396 of file user-edit.php.